/**
 * Asya bölgesi havayolları — premium FSC odaklı.
 *
 * Singapore Airlines, Cathay Pacific, JAL, ANA, Korean Air, Air Asia, Garuda Indonesia.
 *
 * Her birinin mülakat süreci, İngilizce zorluğu ve tipik soruları gerçek
 * havacılık endüstri verilerinden derlenmiştir (2025 itibariyle).
 */
import type { AirlineProfile } from './airlineTypes';

export const ASIA_AIRLINES: AirlineProfile[] = [
  {
    id: 'singapore_airlines',
    name: 'Singapore Airlines',
    iataCode: 'SQ',
    icaoCode: 'SIA',
    country: 'Singapur',
    countryEmoji: '🇸🇬',
    region: 'asia',
    tier: 'flagship',
    hub: 'Singapore Changi (SIN)',
    fleetSize: 145,
    destinations: 130,
    employeeCount: 27000,
    primaryLanguage: 'English',
    prestige: 5,
    descriptionTr:
      'Skytrax "World\'s Best Airline" 6 kez. Premium global network, A380/B777 fleet. İngilizce yeterliliği çok yüksek bekleniyor.',
    insiderTipTr: 'Singapur\'a yolculuk gerekebilir, otel masraflarını karşıla. Premium grooming + zarafet kritik.',
    websiteUrl: 'https://www.singaporeair.com',
    hasMedicalRequirements: true,
    swimTestRequired: true,
    heightRequirementCm: { min: 158, max: 185 },
    interviews: [
      {
        role: 'cabin',
        englishWeight: 95,
        requiredLevel: 'B2',
        totalProcessDays: 120,
        successRatePercent: 3,
        hiringStatus: 'open',
        applicationUrl: 'https://careers.singaporeair.com',
        averageSalaryTryK: 90,
        perks: ['Singapore baz', 'Star Alliance', 'Premium cabin training'],
        stages: [
          {
            id: 'sq_c_app',
            titleTr: 'Online başvuru',
            titleEn: 'Application',
            durationMinutes: 45,
            format: 'online_form',
            descriptionTr: 'Profesyonel CV (İngilizce zorunlu) + headshot + boy/kilo + İngilizce sertifika.',
            passingTipsTr: ['IELTS 7.0+ veya equivalent', 'Headshot studio kalitesi', 'CV İngilizce, ATS uyumlu'],
          },
          {
            id: 'sq_c_video',
            titleTr: 'Video mülakat (HireVue)',
            titleEn: 'Video interview',
            durationMinutes: 30,
            format: 'video_interview',
            descriptionTr: '5-7 video soru, 90 saniye cevap. Tamamen İngilizce.',
            passingTipsTr: ['Net İngilizce telaffuz', 'STAR formatı', 'Singapore Girl image — şıklık + zarafet'],
          },
          {
            id: 'sq_c_assess',
            titleTr: 'Assessment day (Singapur)',
            titleEn: 'Assessment day',
            durationMinutes: 480,
            format: 'assessment_day',
            descriptionTr: 'Singapur\'a uçuş + tam gün. Group activity + 1-on-1 + role-play + grooming check.',
            passingTipsTr: ['Sahane İngilizce şart', 'Asya estetik standardı', 'Müşteri hikayesi hazırla'],
          },
          {
            id: 'sq_c_med',
            titleTr: 'Medical + safety swim',
            titleEn: 'Medical',
            durationMinutes: 360,
            format: 'medical',
            descriptionTr: 'Tam check + 50m yüzme.',
            passingTipsTr: ['BMI 18-23 kritik', 'Yüzme dayanıklılık'],
          },
        ],
        commonQuestionIds: ['q_cabin_motiv_1', 'q_cabin_diff_pax', 'q_cabin_culture', 'q_cabin_team'],
      },
      {
        role: 'pilot',
        englishWeight: 90,
        requiredLevel: 'B2',
        totalProcessDays: 180,
        successRatePercent: 5,
        hiringStatus: 'experienced_only',
        applicationUrl: 'https://www.singaporeair.com/en_UK/sg/careers/pilot/',
        averageSalaryTryK: 600,
        perks: ['A380/B777 captain progression', 'Singapur expat package'],
        stages: [
          {
            id: 'sq_p_app',
            titleTr: 'Type-rated başvuru',
            titleEn: 'Application',
            durationMinutes: 60,
            format: 'online_form',
            descriptionTr: 'ATPL + 5000+ saat + B777/A380 type tercihen + ICAO L4+.',
            passingTipsTr: ['Saat dökümü detaylı', 'B777 / A350 type avantaj'],
          },
          {
            id: 'sq_p_sim',
            titleTr: 'Sim check',
            titleEn: 'Sim',
            durationMinutes: 240,
            format: 'sim_check',
            descriptionTr: 'B777 sim — full procedure + emergency.',
            passingTipsTr: ['CRM kritik', 'Asya hiyerarşi anlayışı'],
          },
        ],
        commonQuestionIds: ['q_pilot_emergency', 'q_pilot_crm', 'q_pilot_decision'],
      },
    ],
  },
  {
    id: 'cathay_pacific',
    name: 'Cathay Pacific',
    iataCode: 'CX',
    icaoCode: 'CPA',
    country: 'Hong Kong',
    countryEmoji: '🇭🇰',
    region: 'asia',
    tier: 'flagship',
    hub: 'Hong Kong (HKG)',
    fleetSize: 180,
    destinations: 70,
    employeeCount: 21000,
    primaryLanguage: 'English',
    prestige: 5,
    descriptionTr:
      'Asya-Pasifik premium hub carrier. Çince + İngilizce çift dil bekleniyor. Oneworld alliance.',
    insiderTipTr: 'Hong Kong assessment day uçuş kendi cebinden. Mandarin temeli avantaj.',
    websiteUrl: 'https://www.cathaypacific.com',
    hasMedicalRequirements: true,
    swimTestRequired: true,
    heightRequirementCm: { min: 158, max: 185 },
    interviews: [
      {
        role: 'cabin',
        englishWeight: 90,
        requiredLevel: 'B2',
        totalProcessDays: 90,
        successRatePercent: 5,
        hiringStatus: 'open',
        applicationUrl: 'https://careers.cathaypacific.com',
        averageSalaryTryK: 80,
        perks: ['Hong Kong baz', 'Oneworld', 'Long-haul A350'],
        stages: [
          {
            id: 'cx_c_app',
            titleTr: 'Online başvuru',
            titleEn: 'Application',
            durationMinutes: 30,
            format: 'online_form',
            descriptionTr: 'CV + İngilizce sertifika + Çince bilenler avantajlı.',
            passingTipsTr: ['IELTS 6.5+', 'Çince bonus'],
          },
          {
            id: 'cx_c_assess',
            titleTr: 'Assessment day (Hong Kong)',
            titleEn: 'Assessment',
            durationMinutes: 360,
            format: 'assessment_day',
            descriptionTr: 'Group + 1-on-1 + role-play. Tamamen İngilizce.',
            passingTipsTr: ['Asia-Pacific kültür anlayışı', 'Premium service mindset'],
          },
        ],
        commonQuestionIds: ['q_cabin_motiv_1', 'q_cabin_diff_pax'],
      },
    ],
  },
  {
    id: 'jal',
    name: 'Japan Airlines (JAL)',
    iataCode: 'JL',
    icaoCode: 'JAL',
    country: 'Japonya',
    countryEmoji: '🇯🇵',
    region: 'asia',
    tier: 'flagship',
    hub: 'Tokyo Haneda (HND) + Narita (NRT)',
    fleetSize: 230,
    destinations: 95,
    employeeCount: 36000,
    primaryLanguage: 'Japanese',
    prestige: 5,
    descriptionTr:
      'Japonya bayrak taşıyıcısı. Oneworld. Japonca zorunlu, İngilizce yüksek beklenti. Kültürel disiplin kritik.',
    insiderTipTr: 'Japon iş kültürü çok resmi. Bowing, isim sırası, kart verme — hepsi ezbere.',
    websiteUrl: 'https://www.jal.com',
    hasMedicalRequirements: true,
    swimTestRequired: true,
    heightRequirementCm: { min: 158, max: 185 },
    interviews: [
      {
        role: 'cabin',
        englishWeight: 70,
        requiredLevel: 'B2',
        totalProcessDays: 150,
        successRatePercent: 4,
        hiringStatus: 'open',
        applicationUrl: 'https://www.jal.com/en/recruit/',
        averageSalaryTryK: 75,
        perks: ['Tokyo baz', 'Oneworld', 'Japon kültür merkezi'],
        stages: [
          {
            id: 'jl_c_app',
            titleTr: 'Online başvuru (Japonca + İngilizce)',
            titleEn: 'Application',
            durationMinutes: 60,
            format: 'online_form',
            descriptionTr: 'Çift dilli CV. Japonca N2+ tercih, İngilizce TOEIC 800+.',
            passingTipsTr: ['Japonca temeli olmalı', 'TOEIC 800+', 'Resmi Japon iş etiği'],
          },
          {
            id: 'jl_c_grp',
            titleTr: 'Grup mülakat',
            titleEn: 'Group',
            durationMinutes: 120,
            format: 'group',
            descriptionTr: 'Tokyo. Wa kavramı (uyum) ön planda.',
            passingTipsTr: ['Saygı dili', 'Grup uyumu', 'Selamlama kuralları'],
          },
        ],
        commonQuestionIds: ['q_cabin_culture', 'q_cabin_team'],
      },
    ],
  },
  {
    id: 'ana',
    name: 'All Nippon Airways (ANA)',
    iataCode: 'NH',
    icaoCode: 'ANA',
    country: 'Japonya',
    countryEmoji: '🇯🇵',
    region: 'asia',
    tier: 'flagship',
    hub: 'Tokyo Haneda (HND)',
    fleetSize: 220,
    destinations: 90,
    employeeCount: 39000,
    primaryLanguage: 'Japanese',
    prestige: 5,
    descriptionTr:
      "Japonya'nın en büyüğü. Star Alliance. Skytrax 5-Star 11 kez. Yüksek İngilizce + Japonca kültür şart.",
    insiderTipTr: 'Tokyo merkez. Kıyafet kuralları çok sıkı, başvurudan önce gözden geçir.',
    websiteUrl: 'https://www.ana.co.jp',
    hasMedicalRequirements: true,
    swimTestRequired: true,
    heightRequirementCm: { min: 158, max: 185 },
    interviews: [
      {
        role: 'cabin',
        englishWeight: 75,
        requiredLevel: 'B2',
        totalProcessDays: 150,
        successRatePercent: 4,
        hiringStatus: 'open',
        applicationUrl: 'https://www.ana.co.jp/group/en/recruit/',
        averageSalaryTryK: 78,
        perks: ['Star Alliance', '787 Dreamliner birinci operator'],
        stages: [
          {
            id: 'nh_c_app',
            titleTr: 'Online başvuru',
            titleEn: 'Application',
            durationMinutes: 60,
            format: 'online_form',
            descriptionTr: 'Japonca + İngilizce CV. TOEIC 700+, Japonca N3+.',
            passingTipsTr: ['Çift dil zorunlu', 'Resmi Japon protokolu'],
          },
        ],
        commonQuestionIds: ['q_cabin_culture'],
      },
    ],
  },
  {
    id: 'korean_air',
    name: 'Korean Air',
    iataCode: 'KE',
    icaoCode: 'KAL',
    country: 'Güney Kore',
    countryEmoji: '🇰🇷',
    region: 'asia',
    tier: 'flagship',
    hub: 'Seoul Incheon (ICN)',
    fleetSize: 160,
    destinations: 120,
    employeeCount: 19000,
    primaryLanguage: 'Korean',
    prestige: 4,
    descriptionTr:
      'Güney Kore bayrak taşıyıcı. SkyTeam. Asya-Amerika premium routes. Korece tercih, İngilizce iyi seviye şart.',
    insiderTipTr: 'Headshot Korean style — formal, krem boyalı arka plan, omuz hizası.',
    websiteUrl: 'https://www.koreanair.com',
    hasMedicalRequirements: true,
    swimTestRequired: true,
    heightRequirementCm: { min: 162, max: 185 },
    interviews: [
      {
        role: 'cabin',
        englishWeight: 75,
        requiredLevel: 'B1',
        totalProcessDays: 100,
        successRatePercent: 6,
        hiringStatus: 'open',
        applicationUrl: 'https://recruit.koreanair.com',
        averageSalaryTryK: 65,
        perks: ['SkyTeam', 'Long-haul A380'],
        stages: [
          {
            id: 'ke_c_app',
            titleTr: 'Online başvuru',
            titleEn: 'Application',
            durationMinutes: 45,
            format: 'online_form',
            descriptionTr: 'Korece tercihen, İngilizce TOEIC 750+.',
            passingTipsTr: ['Headshot Korean style (formal)', 'TOEIC 750+'],
          },
        ],
        commonQuestionIds: ['q_cabin_motiv_1'],
      },
    ],
  },
  {
    id: 'air_asia',
    name: 'AirAsia',
    iataCode: 'AK',
    icaoCode: 'AXM',
    country: 'Malezya',
    countryEmoji: '🇲🇾',
    region: 'asia',
    tier: 'lcc',
    hub: 'Kuala Lumpur (KUL)',
    fleetSize: 200,
    destinations: 130,
    employeeCount: 22000,
    primaryLanguage: 'English',
    prestige: 3,
    descriptionTr:
      'ASEAN\'ın en büyük LCC. "Now everyone can fly" sloganı. Hızlı işe alım, geniş kabul.',
    insiderTipTr: 'LCC mindset: hızlı, enerjik, müşteri odaklı. Aksan rahat, anlaşılırlık şart.',
    websiteUrl: 'https://www.airasia.com',
    hasMedicalRequirements: true,
    swimTestRequired: true,
    heightRequirementCm: { min: 158, max: 180 },
    interviews: [
      {
        role: 'cabin',
        englishWeight: 80,
        requiredLevel: 'B1',
        totalProcessDays: 60,
        successRatePercent: 15,
        hiringStatus: 'open',
        applicationUrl: 'https://careers.airasia.com',
        averageSalaryTryK: 35,
        perks: ['ASEAN network', 'Hızlı promosyon'],
        stages: [
          {
            id: 'ak_c_app',
            titleTr: 'Online başvuru',
            titleEn: 'Application',
            durationMinutes: 30,
            format: 'online_form',
            descriptionTr: 'Hızlı süreç. CV + İngilizce yeterlilik.',
            passingTipsTr: ['IELTS 5.5+', 'LCC mindset — verim odaklı'],
          },
          {
            id: 'ak_c_assess',
            titleTr: 'Walk-in assessment',
            titleEn: 'Walk-in',
            durationMinutes: 240,
            format: 'assessment_day',
            descriptionTr: 'KUL — açık gün, herkese açık.',
            passingTipsTr: ['Energetic personality', 'Swimsuit kontrol'],
          },
        ],
        commonQuestionIds: ['q_cabin_motiv_1', 'q_cabin_team'],
      },
    ],
  },
  {
    id: 'garuda_indonesia',
    name: 'Garuda Indonesia',
    iataCode: 'GA',
    icaoCode: 'GIA',
    country: 'Endonezya',
    countryEmoji: '🇮🇩',
    region: 'asia',
    tier: 'flagship',
    hub: 'Jakarta Soekarno-Hatta (CGK)',
    fleetSize: 90,
    destinations: 60,
    employeeCount: 8000,
    primaryLanguage: 'Indonesian',
    prestige: 4,
    descriptionTr:
      'Endonezya bayrak taşıyıcı. SkyTeam. Endonezce + İngilizce şart. Orta-uzak menzil.',
    insiderTipTr: 'Endonezce + İngilizce çift dil. Bahasa Indonesia anadil seviyesi olmadan zor.',
    websiteUrl: 'https://www.garuda-indonesia.com',
    hasMedicalRequirements: true,
    swimTestRequired: true,
    heightRequirementCm: { min: 158, max: 180 },
    interviews: [
      {
        role: 'cabin',
        englishWeight: 75,
        requiredLevel: 'B1',
        totalProcessDays: 80,
        successRatePercent: 8,
        hiringStatus: 'open',
        applicationUrl: 'https://career.garuda-indonesia.com',
        averageSalaryTryK: 30,
        perks: ['SkyTeam', 'Endonezya network'],
        stages: [
          {
            id: 'ga_c_app',
            titleTr: 'Online başvuru',
            titleEn: 'Application',
            durationMinutes: 30,
            format: 'online_form',
            descriptionTr: 'Endonezce + İngilizce CV.',
            passingTipsTr: ['TOEIC 600+', 'Bahasa Indonesia anadil'],
          },
        ],
        commonQuestionIds: ['q_cabin_motiv_1'],
      },
    ],
  },
];
