/**
 * Türkiye Havayolları — Pilot ve Kabin mülakat süreçleri.
 */
import type { AirlineProfile } from './airlineTypes';

export const TURKEY_AIRLINES: AirlineProfile[] = [
  {
    id: 'turkish_airlines',
    name: 'Türk Hava Yolları (THY)',
    iataCode: 'TK',
    icaoCode: 'THY',
    country: 'Türkiye',
    countryEmoji: '🇹🇷',
    region: 'turkey',
    tier: 'flagship',
    hub: 'İstanbul (IST) + Sabiha Gökçen (SAW)',
    fleetSize: 440,
    destinations: 350,
    employeeCount: 35000,
    primaryLanguage: 'Turkish',
    prestige: 5,
    hasMedicalRequirements: true,
    swimTestRequired: true,
    heightRequirementCm: { min: 160, max: 200 },
    interviews: [
      {
        role: 'cabin',
        englishWeight: 70,
        requiredLevel: 'B1',
        totalProcessDays: 90,
        successRatePercent: 8,
        hiringStatus: 'open',
        applicationUrl: 'https://www.turkishairlines.com/tr-tr/basin-odasi/insan-kaynaklari',
        averageSalaryTryK: 55,
        perks: ['ZTM yolda yemek', 'TK fligth privileges', 'Star Alliance'],
        stages: [
          { id: 'tk_c_app', titleTr: 'Online başvuru + ön eleme', titleEn: 'Application', durationMinutes: 60, format: 'online_form',
            descriptionTr: 'THY Kariyer portalı üzerinden başvuru. Diploma + İngilizce sertifika (TOEFL/YDS) + boy/kilo.',
            passingTipsTr: ['YDS 70+ hedefli ol', 'Headshot fotoğraf', 'CV özenli ve Türkçe-İngilizce'] },
          { id: 'tk_c_eng', titleTr: 'YDS / İngilizce yeterlilik', titleEn: 'English test', durationMinutes: 90, format: 'english_test',
            descriptionTr: 'İngilizce yeterlilik testi (YDS muafiyeti veya kurum içi).',
            passingTipsTr: ['Listening + reading kritik', 'Aviation vocab pratik', 'Telaffuz net'] },
          { id: 'tk_c_grp', titleTr: 'Grup mülakatı', titleEn: 'Group interview', durationMinutes: 90, format: 'group',
            descriptionTr: 'İstanbul (Genel Müdürlük) — 8-10 kişilik grup. Tartışma + sunum + role-play.',
            passingTipsTr: ['THY değerleri ezbere', 'Sıra kuralı — diğerlerini dinle', 'Türk misafirperverliği vurgu'] },
          { id: 'tk_c_bir', titleTr: 'Bireysel mülakat', titleEn: '1-on-1', durationMinutes: 30, format: 'one_on_one',
            descriptionTr: 'HR + senior cabin manager 1-on-1.',
            passingTipsTr: ['STAR formatı', 'Türkiye ve THY tarihi', 'Long-term commitment'] },
          { id: 'tk_c_med', titleTr: 'Sağlık + boy/kilo', titleEn: 'Medical', durationMinutes: 240, format: 'medical',
            descriptionTr: 'Anadolu Sağlık + tam check.',
            passingTipsTr: ['Yüzme zorunlu', 'BMI 18-25', 'Görme + işitme'] },
        ],
        commonQuestionIds: ['q_tk_1', 'q_tk_2', 'q_tk_3', 'q_cabin_motiv_1', 'q_cabin_diff_pax', 'q_cabin_team', 'q_cabin_culture'],
      },
      {
        role: 'pilot',
        englishWeight: 80,
        requiredLevel: 'B2',
        totalProcessDays: 120,
        successRatePercent: 6,
        hiringStatus: 'open',
        applicationUrl: 'https://www.turkishairlines.com/tr-tr/basin-odasi/insan-kaynaklari/uzun-menzilli-pilot',
        averageSalaryTryK: 350,
        perks: ['THY akademi mezunlar', 'Tüm filo (777/350/A330/737)', 'TR baz IST+SAW'],
        stages: [
          { id: 'tk_p_app', titleTr: 'Başvuru + lisans kontrol', titleEn: 'Application', durationMinutes: 60, format: 'online_form',
            descriptionTr: 'CPL/ATPL + ICAO 4 + saat dökümü + medical.',
            passingTipsTr: ['Tertemiz lisans', 'TR baz tercih ediyorsan belirt', 'YDS 70+ artı'] },
          { id: 'tk_p_yaz', titleTr: 'THY yazılı (mesleki + İngilizce)', titleEn: 'Written exam', durationMinutes: 120, format: 'psychometric',
            descriptionTr: 'THY HR yazılı sınav: aviation theory + English.',
            passingTipsTr: ['ATPL teori taze tut', 'Sayısal + kelime', 'Stres yönetimi'] },
          { id: 'tk_p_sim', titleTr: 'Sim assessment', titleEn: 'Sim', durationMinutes: 240, format: 'sim_check',
            descriptionTr: 'TK Akademi 737 veya A320 sim. Engine fail, ILS.',
            passingTipsTr: ['Standart calls', 'Manual flying', 'CRM örnek dağıtım'] },
          { id: 'tk_p_pan', titleTr: 'Panel mülakatı', titleEn: 'Panel', durationMinutes: 60, format: 'panel',
            descriptionTr: 'Senior captain + chief pilot + HR.',
            passingTipsTr: ['Türkiye uzun dönem motivasyonu', 'Liderlik örnekleri', 'CRM'] },
        ],
        commonQuestionIds: ['q_pilot_motiv', 'q_pilot_crm_fail', 'q_tk_pilot_1', 'q_pilot_decision'],
      },
    ],
    descriptionTr: 'Türkiye bayrak taşıyıcı, dünyanın en geniş network\'üne sahip (350+ destinasyon). Star Alliance.',
    insiderTipTr: 'Süreç uzun (3-4 ay). Türkçe + İngilizce dengeli. Sabırlı ol — başvurudan sonuca 90+ gün.',
    websiteUrl: 'https://www.turkishairlines.com',
  },

  {
    id: 'pegasus',
    name: 'Pegasus Hava Yolları',
    iataCode: 'PC',
    icaoCode: 'PGT',
    country: 'Türkiye',
    countryEmoji: '🇹🇷',
    region: 'turkey',
    tier: 'lcc',
    hub: 'İstanbul Sabiha Gökçen (SAW)',
    fleetSize: 110,
    destinations: 130,
    employeeCount: 7000,
    primaryLanguage: 'Turkish',
    prestige: 4,
    hasMedicalRequirements: true,
    swimTestRequired: true,
    heightRequirementCm: { min: 160, max: 200 },
    interviews: [
      {
        role: 'cabin',
        englishWeight: 65,
        requiredLevel: 'A2',
        totalProcessDays: 45,
        successRatePercent: 18,
        hiringStatus: 'open',
        applicationUrl: 'https://www.flypgs.com/kariyer',
        averageSalaryTryK: 40,
        stages: [
          { id: 'pc_c_app', titleTr: 'Online + AC SAW', titleEn: 'Application', durationMinutes: 240, format: 'assessment_day',
            descriptionTr: 'Online başvuru + Sabiha Gökçen\'de AC.',
            passingTipsTr: ['LCC tempo', 'Hızlı multitasking', 'Genç + enerjik tutum'] },
        ],
        commonQuestionIds: ['q_lcc_1', 'q_pc_1', 'q_cabin_motiv_1'],
      },
      {
        role: 'pilot',
        englishWeight: 75,
        requiredLevel: 'B1',
        totalProcessDays: 60,
        successRatePercent: 18,
        hiringStatus: 'open',
        applicationUrl: 'https://www.flypgs.com/kariyer/pilot',
        averageSalaryTryK: 220,
        stages: [
          { id: 'pc_p_app', titleTr: 'Application + sim', titleEn: 'Application', durationMinutes: 240, format: 'sim_check',
            descriptionTr: 'CV + 737/A320 sim check.',
            passingTipsTr: ['737 type rating tercih', 'TR vatandaşı tercih', 'Hızlı upgrade vaadi'] },
        ],
        commonQuestionIds: ['q_pilot_motiv', 'q_lcc_pace'],
      },
    ],
    descriptionTr: 'Türkiye\'nin en büyük LCC. Sabiha Gökçen hub. 737 + A320neo karma fleet.',
    insiderTipTr: 'Daha hızlı süreç, daha kolay giriş. Türk vatandaşı için TR\'de iş için iyi seçim.',
    websiteUrl: 'https://www.flypgs.com',
  },

  {
    id: 'sunexpress',
    name: 'SunExpress',
    iataCode: 'XQ',
    icaoCode: 'SXS',
    country: 'Türkiye/Almanya',
    countryEmoji: '🇹🇷',
    region: 'turkey',
    tier: 'major',
    hub: 'Antalya (AYT) + Frankfurt (FRA)',
    fleetSize: 65,
    destinations: 85,
    employeeCount: 4500,
    primaryLanguage: 'Turkish',
    prestige: 3,
    hasMedicalRequirements: true,
    swimTestRequired: true,
    interviews: [
      {
        role: 'cabin',
        englishWeight: 75,
        requiredLevel: 'B1',
        totalProcessDays: 45,
        successRatePercent: 20,
        hiringStatus: 'open',
        applicationUrl: 'https://career.sunexpress.com',
        averageSalaryTryK: 45,
        stages: [
          { id: 'xq_c_app', titleTr: 'Application + Antalya AC', titleEn: 'Application', durationMinutes: 240, format: 'assessment_day',
            descriptionTr: 'Online + AYT veya FRA AC.',
            passingTipsTr: ['Almanca B1+ büyük artı', 'TR-DE turist trafiği', 'Yaz sezon yoğun'] },
        ],
        commonQuestionIds: ['q_cabin_motiv_1', 'q_xq_1'],
      },
    ],
    descriptionTr: 'THY + Lufthansa ortak girişim. Antalya hub. Yaz turist trafiği.',
    insiderTipTr: 'Almanca konuşan TR vatandaşları için ideal. AYT bazı yaz çok yoğun.',
    websiteUrl: 'https://www.sunexpress.com',
  },

  {
    id: 'anadolujet',
    name: 'AnadoluJet',
    iataCode: 'TK',
    icaoCode: 'AJA',
    country: 'Türkiye',
    countryEmoji: '🇹🇷',
    region: 'turkey',
    tier: 'lcc',
    hub: 'Ankara (ESB) + İstanbul SAW',
    fleetSize: 75,
    destinations: 80,
    employeeCount: 2500,
    primaryLanguage: 'Turkish',
    prestige: 3,
    hasMedicalRequirements: true,
    swimTestRequired: true,
    interviews: [
      {
        role: 'cabin',
        englishWeight: 60,
        requiredLevel: 'A2',
        totalProcessDays: 45,
        successRatePercent: 25,
        hiringStatus: 'open',
        applicationUrl: 'https://www.anadolujet.com/tr/kariyer',
        averageSalaryTryK: 40,
        stages: [
          { id: 'aj_c_app', titleTr: 'Application + AC Ankara', titleEn: 'Application', durationMinutes: 240, format: 'assessment_day',
            descriptionTr: 'Online + Ankara veya İstanbul AC.',
            passingTipsTr: ['THY iştiraki — değerler ortak', 'İç hat yoğun', 'Anadolu kültürü vurgu'] },
        ],
        commonQuestionIds: ['q_lcc_1', 'q_cabin_motiv_1'],
      },
    ],
    descriptionTr: 'THY iştiraki. İç hat odaklı LCC.',
    insiderTipTr: 'THY\'ye geçiş yolu olarak görülebilir. Anadolu kültürü vurgular.',
    websiteUrl: 'https://www.anadolujet.com',
  },
];
