/**
 * Avrupa Havayolları — Pilot ve Kabin mülakat süreçleri.
 *
 * 16 havayolu: Lufthansa, Air France, KLM, BA, Virgin Atlantic, Ryanair,
 * easyJet, Wizz Air, SAS, Swiss, Austrian, TAP Portugal, Aegean, Iberia,
 * Vueling, Finnair, LOT, ITA Airways, Brussels.
 */
import type { AirlineProfile } from './airlineTypes';

export const EUROPE_AIRLINES: AirlineProfile[] = [
  // ═══ FULL SERVICE CARRIERS ═══
  {
    id: 'lufthansa',
    name: 'Lufthansa',
    iataCode: 'LH',
    icaoCode: 'DLH',
    country: 'Almanya',
    countryEmoji: '🇩🇪',
    region: 'europe-fsc',
    tier: 'flagship',
    hub: 'Frankfurt (FRA) + München (MUC)',
    fleetSize: 280,
    destinations: 220,
    employeeCount: 110000,
    primaryLanguage: 'German',
    prestige: 5,
    hasMedicalRequirements: true,
    swimTestRequired: true,
    heightRequirementCm: { min: 160, max: 195 },
    interviews: [
      {
        role: 'cabin',
        englishWeight: 70,
        requiredLevel: 'B1',
        totalProcessDays: 60,
        successRatePercent: 15,
        hiringStatus: 'open',
        applicationUrl: 'https://www.be-lufthansa.com',
        averageSalaryTryK: 90,
        perks: ['AB sosyal güvenlik', 'Lufthansa Group fligth privileges', 'Stabil iş'],
        stages: [
          { id: 'lh_c_app', titleTr: 'Online application + video', titleEn: 'Application + video', durationMinutes: 90, format: 'video_interview',
            descriptionTr: 'Online başvuru → digital video interview (Almanca + İngilizce sorular).',
            passingTipsTr: ['Almanca B1+ avantaj', 'Net video', 'Lufthansa servis felsefesi'] },
          { id: 'lh_c_ad', titleTr: 'Assessment Day Frankfurt', titleEn: 'Assessment Day', durationMinutes: 360, format: 'assessment_day',
            descriptionTr: 'Tam gün AC: grup egzersizi + role-play + 1-on-1 + İngilizce kontrol.',
            passingTipsTr: ['Yüksek profesyonellik', 'Multitasking', 'Avrupa kültür duyarlılık'] },
          { id: 'lh_c_med', titleTr: 'Medical + training', titleEn: 'Medical', durationMinutes: 240, format: 'medical',
            descriptionTr: 'Frankfurt\'ta tıbbi + 6-haftalık eğitim.',
            passingTipsTr: ['Yüzme zorunlu', 'BMI kontrol'] },
        ],
        commonQuestionIds: ['q_lh_1', 'q_eu_fsc_1', 'q_cabin_motiv_1', 'q_cabin_diff_pax', 'q_cabin_team'],
      },
      {
        role: 'pilot',
        englishWeight: 90,
        requiredLevel: 'C1',
        totalProcessDays: 90,
        successRatePercent: 7,
        hiringStatus: 'open',
        applicationUrl: 'https://www.be-lufthansa.com/jobs/pilot',
        averageSalaryTryK: 350,
        perks: ['EFTC mezuniyet seçeneği', 'A350/A380 fleet', 'EU stabilite'],
        stages: [
          { id: 'lh_p_dlr', titleTr: 'DLR Test (German Aerospace)', titleEn: 'DLR Test', durationMinutes: 480, format: 'psychometric',
            descriptionTr: 'Hamburg\'da 2 günlük DLR test — psikometrik + koordinasyon + bilgi.',
            passingTipsTr: ['Çok zor — pratik şart', 'Numerical + spatial pratiği', 'İngilizce + Almanca'] },
          { id: 'lh_p_sim', titleTr: 'Sim assessment (Frankfurt)', titleEn: 'Sim', durationMinutes: 240, format: 'sim_check',
            descriptionTr: 'A320 sim — partial panel, hand-flying.',
            passingTipsTr: ['Manual flying mükemmel', 'CRM güçlü', 'Stres altında performans'] },
          { id: 'lh_p_pan', titleTr: 'Panel + behavioral', titleEn: 'Panel', durationMinutes: 90, format: 'panel',
            descriptionTr: 'Senior pilots + chief + HR. Almanca + İngilizce karma.',
            passingTipsTr: ['Almanca konuşma artı', 'STAR örnek', 'Long-term commitment'] },
        ],
        commonQuestionIds: ['q_pilot_motiv', 'q_pilot_crm_fail', 'q_lh_pilot_1', 'q_pilot_decision'],
      },
    ],
    descriptionTr: 'Avrupa\'nın en büyük havayolu grubu. Lufthansa + Swiss + Austrian + Brussels + Eurowings.',
    insiderTipTr: 'DLR test pilotlar için çok zor — özel hazırlık şart. Cabin için Almanca B1+ ciddi avantaj.',
    websiteUrl: 'https://www.lufthansa.com',
  },

  {
    id: 'air_france',
    name: 'Air France',
    iataCode: 'AF',
    icaoCode: 'AFR',
    country: 'Fransa',
    countryEmoji: '🇫🇷',
    region: 'europe-fsc',
    tier: 'flagship',
    hub: 'Paris CDG + Orly (ORY)',
    fleetSize: 215,
    destinations: 200,
    employeeCount: 80000,
    primaryLanguage: 'French',
    prestige: 5,
    hasMedicalRequirements: true,
    swimTestRequired: true,
    heightRequirementCm: { min: 158, max: 198 },
    interviews: [
      {
        role: 'cabin',
        englishWeight: 60,
        requiredLevel: 'B1',
        totalProcessDays: 75,
        successRatePercent: 10,
        hiringStatus: 'open',
        applicationUrl: 'https://recrutement.airfrance.com',
        averageSalaryTryK: 85,
        perks: ['EU sosyal', 'Skyteam fligth privileges'],
        stages: [
          { id: 'af_c_fr', titleTr: 'Fransızca yeterlilik şart', titleEn: 'French required', durationMinutes: 60, format: 'english_test',
            descriptionTr: 'Fransızca B2+ ZORUNLU. Tüm mülakat Fransızca.',
            passingTipsTr: ['Fransızca anadil değilse C1+ pratik', 'DELF/DALF sertifika', 'Fransız kültür'] },
          { id: 'af_c_ad', titleTr: 'Assessment Day Paris', titleEn: 'Assessment Day', durationMinutes: 360, format: 'assessment_day',
            descriptionTr: 'Tam gün Paris\'te AC.',
            passingTipsTr: ['Profesyonel görünüm', 'Fransız servis stili', 'Kültürel uyum'] },
        ],
        commonQuestionIds: ['q_af_1', 'q_eu_fsc_1', 'q_cabin_motiv_1'],
      },
    ],
    descriptionTr: 'Fransa bayrak taşıyıcı. SkyTeam kurucu üyesi. KLM ile birleşik grup.',
    insiderTipTr: 'Fransızca olmadan zor. Lüks "art de vivre à la française" felsefesi vurgular.',
    websiteUrl: 'https://www.airfrance.com',
  },

  {
    id: 'klm',
    name: 'KLM Royal Dutch',
    iataCode: 'KL',
    icaoCode: 'KLM',
    country: 'Hollanda',
    countryEmoji: '🇳🇱',
    region: 'europe-fsc',
    tier: 'flagship',
    hub: 'Amsterdam Schiphol (AMS)',
    fleetSize: 110,
    destinations: 145,
    employeeCount: 33000,
    primaryLanguage: 'Dutch',
    prestige: 5,
    hasMedicalRequirements: true,
    swimTestRequired: true,
    heightRequirementCm: { min: 158, max: 200 },
    interviews: [
      {
        role: 'cabin',
        englishWeight: 75,
        requiredLevel: 'B2',
        totalProcessDays: 60,
        successRatePercent: 12,
        hiringStatus: 'open',
        applicationUrl: 'https://careers.klm.com',
        averageSalaryTryK: 90,
        perks: ['EU sosyal', 'AMS hub yaşam', 'Skyteam'],
        stages: [
          { id: 'kl_c_dut', titleTr: 'Hollandaca + İngilizce', titleEn: 'Dutch + English', durationMinutes: 60, format: 'english_test',
            descriptionTr: 'Hollandaca B1+ tercih (zorunlu değil ama büyük artı). İngilizce B2+ şart.',
            passingTipsTr: ['Hollandaca öğrenmeye açıklık', 'Net İngilizce', 'KLM "blue heart" değerleri'] },
          { id: 'kl_c_ad', titleTr: 'Assessment Day Schiphol', titleEn: 'AC', durationMinutes: 360, format: 'assessment_day',
            descriptionTr: 'AMS\'te tam gün AC.',
            passingTipsTr: ['Hollanda direktlik kültürü — açık konuş', 'Ekip oyuncusu', 'Sürdürülebilirlik vurgu'] },
        ],
        commonQuestionIds: ['q_kl_1', 'q_eu_fsc_1', 'q_cabin_motiv_1'],
      },
    ],
    descriptionTr: 'Dünyanın en eski faaliyetteki havayolu (1919). Air France grup.',
    insiderTipTr: 'Hollanda direktlik kültürü — fazla cilalı cevap kötü. Net, dürüst, ekip odaklı.',
    websiteUrl: 'https://www.klm.com',
  },

  {
    id: 'british_airways',
    name: 'British Airways',
    iataCode: 'BA',
    icaoCode: 'BAW',
    country: 'İngiltere',
    countryEmoji: '🇬🇧',
    region: 'europe-fsc',
    tier: 'flagship',
    hub: 'London Heathrow (LHR) + Gatwick (LGW)',
    fleetSize: 280,
    destinations: 200,
    employeeCount: 35000,
    primaryLanguage: 'English',
    prestige: 5,
    hasMedicalRequirements: true,
    swimTestRequired: true,
    heightRequirementCm: { min: 158, max: 191 },
    reachRequirementCm: 188,
    interviews: [
      {
        role: 'cabin',
        englishWeight: 90,
        requiredLevel: 'B2',
        totalProcessDays: 60,
        successRatePercent: 8,
        hiringStatus: 'open',
        applicationUrl: 'https://careers.ba.com',
        averageSalaryTryK: 75,
        perks: ['UK sosyal', 'oneworld fligth privileges', 'LHR hub'],
        stages: [
          { id: 'ba_c_app', titleTr: 'Online + situational test', titleEn: 'Online + SJT', durationMinutes: 90, format: 'online_form',
            descriptionTr: 'Application + situational judgment test + video.',
            passingTipsTr: ['Britanya vize sorununa hazır', 'BA "to fly. to serve." felsefesi', 'Premium servis'] },
          { id: 'ba_c_ad', titleTr: 'Assessment Day Heathrow', titleEn: 'AC LHR', durationMinutes: 360, format: 'assessment_day',
            descriptionTr: 'LHR yakınında tam gün AC.',
            passingTipsTr: ['Profesyonel UK style', 'Polite ama assertive', 'Premium kabin tonu'] },
        ],
        commonQuestionIds: ['q_ba_1', 'q_eu_fsc_1', 'q_cabin_motiv_1', 'q_cabin_diff_pax'],
      },
      {
        role: 'pilot',
        englishWeight: 95,
        requiredLevel: 'C1',
        totalProcessDays: 120,
        successRatePercent: 5,
        hiringStatus: 'experienced_only',
        applicationUrl: 'https://careers.ba.com/pilots',
        averageSalaryTryK: 380,
        stages: [
          { id: 'ba_p_app', titleTr: 'CV + tests', titleEn: 'Application', durationMinutes: 120, format: 'online_form',
            descriptionTr: 'CV + numerical/verbal tests + situational.',
            passingTipsTr: ['Min 1500 saat', 'Multi-crew jet', 'UK CAA / EASA lisans'] },
          { id: 'ba_p_sim', titleTr: 'Sim + interview LHR', titleEn: 'Sim', durationMinutes: 360, format: 'sim_check',
            descriptionTr: 'A320 sim + technical + HR panel.',
            passingTipsTr: ['Standart calls', 'CRM mükemmel', 'BA değerleri'] },
        ],
        commonQuestionIds: ['q_pilot_motiv', 'q_pilot_crm_fail', 'q_ba_pilot_1'],
      },
    ],
    descriptionTr: 'İngiltere bayrak taşıyıcı. oneworld kurucu. LHR Terminal 5 evi.',
    insiderTipTr: 'Britanya post-Brexit vize zorlu — UK passport / settled status önemli. Premium kabin standardı yüksek.',
    websiteUrl: 'https://www.britishairways.com',
  },

  {
    id: 'virgin_atlantic',
    name: 'Virgin Atlantic',
    iataCode: 'VS',
    icaoCode: 'VIR',
    country: 'İngiltere',
    countryEmoji: '🇬🇧',
    region: 'europe-fsc',
    tier: 'flagship',
    hub: 'London Heathrow + Gatwick + Manchester',
    fleetSize: 40,
    destinations: 30,
    employeeCount: 8500,
    primaryLanguage: 'English',
    prestige: 4,
    hasMedicalRequirements: true,
    swimTestRequired: true,
    heightRequirementCm: { min: 158, max: 188 },
    interviews: [
      {
        role: 'cabin',
        englishWeight: 85,
        requiredLevel: 'B2',
        totalProcessDays: 45,
        successRatePercent: 12,
        hiringStatus: 'open',
        applicationUrl: 'https://careersuk.virgin-atlantic.com',
        averageSalaryTryK: 70,
        perks: ['Virgin lifestyle', 'Atlantic uçuş', 'Genç kültür'],
        stages: [
          { id: 'vs_c_app', titleTr: 'Online + Recruitment Day', titleEn: 'Recruitment Day', durationMinutes: 240, format: 'assessment_day',
            descriptionTr: 'Online + LHR Recruitment Day. Daha relax atmosfer.',
            passingTipsTr: ['Karakter > beceri', 'Eğlenceli + profesyonel', 'Virgin "personality" arıyor'] },
        ],
        commonQuestionIds: ['q_vs_1', 'q_cabin_motiv_1'],
      },
    ],
    descriptionTr: 'Richard Branson\'ın havayolu. Karakter ve "rockstar" servis stili.',
    insiderTipTr: 'BA\'dan farklı — daha relax, kişilik vurgusu. "Why Virgin not BA?" sorusuna hazırlıklı ol.',
    websiteUrl: 'https://www.virginatlantic.com',
  },

  {
    id: 'swiss',
    name: 'Swiss International',
    iataCode: 'LX',
    icaoCode: 'SWR',
    country: 'İsviçre',
    countryEmoji: '🇨🇭',
    region: 'europe-fsc',
    tier: 'flagship',
    hub: 'Zürich (ZRH) + Geneva (GVA)',
    fleetSize: 90,
    destinations: 100,
    employeeCount: 9500,
    primaryLanguage: 'German',
    prestige: 5,
    hasMedicalRequirements: true,
    swimTestRequired: true,
    interviews: [
      {
        role: 'cabin',
        englishWeight: 75,
        requiredLevel: 'B2',
        totalProcessDays: 60,
        successRatePercent: 10,
        hiringStatus: 'open',
        applicationUrl: 'https://www.swiss.com/careers',
        averageSalaryTryK: 130,
        perks: ['CHF maaş yüksek', 'Lufthansa Group benefits', 'Zürich yaşam'],
        stages: [
          { id: 'lx_c_lng', titleTr: 'Almanca + İngilizce + Fransızca', titleEn: 'Multi-lang', durationMinutes: 60, format: 'english_test',
            descriptionTr: 'Almanca B1+ tercih, İngilizce B2 şart, Fransızca/İtalyanca artı.',
            passingTipsTr: ['Çok dilli — en az 2 dil', 'İsviçre "precision" vurgu', 'Premium servis'] },
        ],
        commonQuestionIds: ['q_lx_1', 'q_eu_fsc_1', 'q_cabin_motiv_1'],
      },
    ],
    descriptionTr: 'İsviçre bayrak taşıyıcı. Lufthansa Group. Premium İsviçre standardı.',
    insiderTipTr: 'Çok dilli kabin — sadece İngilizce yetmez. CHF maaş Avrupa\'nın en yüksek bandında.',
    websiteUrl: 'https://www.swiss.com',
  },

  {
    id: 'austrian',
    name: 'Austrian Airlines',
    iataCode: 'OS',
    icaoCode: 'AUA',
    country: 'Avusturya',
    countryEmoji: '🇦🇹',
    region: 'europe-fsc',
    tier: 'major',
    hub: 'Vienna (VIE)',
    fleetSize: 65,
    destinations: 130,
    employeeCount: 6500,
    primaryLanguage: 'German',
    prestige: 4,
    hasMedicalRequirements: true,
    swimTestRequired: true,
    interviews: [
      {
        role: 'cabin',
        englishWeight: 70,
        requiredLevel: 'B1',
        totalProcessDays: 45,
        successRatePercent: 18,
        hiringStatus: 'open',
        applicationUrl: 'https://www.austrian.com/career',
        averageSalaryTryK: 80,
        stages: [
          { id: 'os_c_app', titleTr: 'Application + Vienna AC', titleEn: 'Application', durationMinutes: 240, format: 'assessment_day',
            descriptionTr: 'Online + Viyana\'da AC.',
            passingTipsTr: ['Almanca B1+', 'Avrupa kültür', 'Lufthansa Group ortak'] },
        ],
        commonQuestionIds: ['q_eu_fsc_1', 'q_cabin_motiv_1'],
      },
    ],
    descriptionTr: 'Avusturya bayrak taşıyıcı. Lufthansa Group.',
    insiderTipTr: 'Lufthansa\'dan kolay giriş. Almanca B1 yeterli. Viyana yaşam + Avrupa networku.',
    websiteUrl: 'https://www.austrian.com',
  },

  {
    id: 'tap_portugal',
    name: 'TAP Air Portugal',
    iataCode: 'TP',
    icaoCode: 'TAP',
    country: 'Portekiz',
    countryEmoji: '🇵🇹',
    region: 'europe-fsc',
    tier: 'major',
    hub: 'Lisbon (LIS) + Porto (OPO)',
    fleetSize: 100,
    destinations: 90,
    employeeCount: 6000,
    primaryLanguage: 'Portuguese',
    prestige: 4,
    hasMedicalRequirements: true,
    swimTestRequired: true,
    interviews: [
      {
        role: 'cabin',
        englishWeight: 75,
        requiredLevel: 'B1',
        totalProcessDays: 45,
        successRatePercent: 18,
        hiringStatus: 'open',
        applicationUrl: 'https://flytap.com/careers',
        averageSalaryTryK: 55,
        stages: [
          { id: 'tp_c_app', titleTr: 'Application + Lisbon AC', titleEn: 'Application', durationMinutes: 240, format: 'assessment_day',
            descriptionTr: 'Online + Lizbon\'da AC.',
            passingTipsTr: ['Portekizce B1+ tercih', 'Brezilya/Afrika network odak', 'Star Alliance'] },
        ],
        commonQuestionIds: ['q_cabin_motiv_1'],
      },
    ],
    descriptionTr: 'Portekiz bayrak taşıyıcı. Brezilya + Afrika network güçlü.',
    insiderTipTr: 'Portekizce öğrenmeye açık olmak şart. Lizbon yaşam yumuşak ve ucuz.',
    websiteUrl: 'https://flytap.com',
  },

  {
    id: 'aegean',
    name: 'Aegean Airlines',
    iataCode: 'A3',
    icaoCode: 'AEE',
    country: 'Yunanistan',
    countryEmoji: '🇬🇷',
    region: 'europe-fsc',
    tier: 'major',
    hub: 'Athens (ATH)',
    fleetSize: 70,
    destinations: 150,
    employeeCount: 3500,
    primaryLanguage: 'English',
    prestige: 4,
    hasMedicalRequirements: true,
    swimTestRequired: true,
    interviews: [
      {
        role: 'cabin',
        englishWeight: 80,
        requiredLevel: 'B1',
        totalProcessDays: 30,
        successRatePercent: 20,
        hiringStatus: 'open',
        applicationUrl: 'https://en.aegeanair.com/careers',
        averageSalaryTryK: 50,
        stages: [
          { id: 'a3_c_app', titleTr: 'Application + Athens AC', titleEn: 'Application', durationMinutes: 240, format: 'assessment_day',
            descriptionTr: 'Online + Atina\'da AC.',
            passingTipsTr: ['Yunanca artı', 'Yaz yoğun sezon', 'Yunanistan turist tematik'] },
        ],
        commonQuestionIds: ['q_cabin_motiv_1'],
      },
    ],
    descriptionTr: 'Yunanistan bayrak taşıyıcı. Star Alliance. Skytrax 6+ kez "Avrupa\'nın en iyi regional".',
    insiderTipTr: 'Sıcak Yunan kültürü vurgu. Yaz turist sezonu çok yoğun.',
    websiteUrl: 'https://en.aegeanair.com',
  },

  {
    id: 'iberia',
    name: 'Iberia',
    iataCode: 'IB',
    icaoCode: 'IBE',
    country: 'İspanya',
    countryEmoji: '🇪🇸',
    region: 'europe-fsc',
    tier: 'flagship',
    hub: 'Madrid (MAD)',
    fleetSize: 95,
    destinations: 110,
    employeeCount: 16000,
    primaryLanguage: 'Spanish',
    prestige: 4,
    hasMedicalRequirements: true,
    swimTestRequired: true,
    interviews: [
      {
        role: 'cabin',
        englishWeight: 70,
        requiredLevel: 'B1',
        totalProcessDays: 60,
        successRatePercent: 15,
        hiringStatus: 'open',
        applicationUrl: 'https://grupo.iberia.com/empleo',
        averageSalaryTryK: 65,
        stages: [
          { id: 'ib_c_es', titleTr: 'İspanyolca şart', titleEn: 'Spanish required', durationMinutes: 60, format: 'english_test',
            descriptionTr: 'İspanyolca B2+ ZORUNLU. Mülakat İspanyolca.',
            passingTipsTr: ['DELE sertifika', 'Latin Amerika network odak', 'IAG (BA + Iberia) grubu'] },
          { id: 'ib_c_ad', titleTr: 'Assessment Day Madrid', titleEn: 'AC', durationMinutes: 360, format: 'assessment_day',
            descriptionTr: 'MAD\'da tam gün AC.',
            passingTipsTr: ['Latin sıcaklık + profesyonellik', 'IAG değerleri'] },
        ],
        commonQuestionIds: ['q_ib_1', 'q_eu_fsc_1', 'q_cabin_motiv_1'],
      },
    ],
    descriptionTr: 'İspanya bayrak taşıyıcı. IAG grubu (BA ile). Latin Amerika güçlü.',
    insiderTipTr: 'İspanyolca olmadan giriş yok. Madrid yaşam + Latam network avantajı.',
    websiteUrl: 'https://www.iberia.com',
  },

  {
    id: 'sas',
    name: 'SAS — Scandinavian',
    iataCode: 'SK',
    icaoCode: 'SAS',
    country: 'İsveç/Danimarka/Norveç',
    countryEmoji: '🇸🇪',
    region: 'europe-fsc',
    tier: 'flagship',
    hub: 'Copenhagen (CPH) + Stockholm (ARN) + Oslo (OSL)',
    fleetSize: 135,
    destinations: 100,
    employeeCount: 7000,
    primaryLanguage: 'English',
    prestige: 4,
    hasMedicalRequirements: true,
    swimTestRequired: true,
    interviews: [
      {
        role: 'cabin',
        englishWeight: 75,
        requiredLevel: 'B1',
        totalProcessDays: 60,
        successRatePercent: 15,
        hiringStatus: 'open',
        applicationUrl: 'https://www.sasgroup.net/careers',
        averageSalaryTryK: 95,
        perks: ['İskandinav sosyal güvenlik', 'Star Alliance benefits'],
        stages: [
          { id: 'sk_c_lng', titleTr: 'İsveççe/Danca/Norveççe (biri)', titleEn: 'Scandi lang', durationMinutes: 60, format: 'english_test',
            descriptionTr: 'En az bir İskandinav dili B1+ tercih (zorunlu olmayabilir bölgeye göre).',
            passingTipsTr: ['Local language büyük artı', 'İskandinav direktlik', 'Sürdürülebilirlik'] },
        ],
        commonQuestionIds: ['q_eu_fsc_1', 'q_cabin_motiv_1'],
      },
    ],
    descriptionTr: 'İskandinav 3 ülke ortak. Star Alliance. Yeniden yapılanma sonrası genişliyor.',
    insiderTipTr: 'En az bir İskandinav dili çok önemli. İskandinav iş kültürü ekip + eşitlik vurgular.',
    websiteUrl: 'https://www.sas.se',
  },

  {
    id: 'finnair',
    name: 'Finnair',
    iataCode: 'AY',
    icaoCode: 'FIN',
    country: 'Finlandiya',
    countryEmoji: '🇫🇮',
    region: 'europe-fsc',
    tier: 'major',
    hub: 'Helsinki (HEL)',
    fleetSize: 80,
    destinations: 100,
    employeeCount: 5000,
    primaryLanguage: 'English',
    prestige: 4,
    hasMedicalRequirements: true,
    swimTestRequired: true,
    interviews: [
      {
        role: 'cabin',
        englishWeight: 80,
        requiredLevel: 'B2',
        totalProcessDays: 45,
        successRatePercent: 18,
        hiringStatus: 'open',
        applicationUrl: 'https://careers.finnair.com',
        averageSalaryTryK: 80,
        stages: [
          { id: 'ay_c_app', titleTr: 'Application + HEL AC', titleEn: 'Application', durationMinutes: 240, format: 'assessment_day',
            descriptionTr: 'Online + Helsinki\'de AC.',
            passingTipsTr: ['İskandinav direktlik', 'Asia network odak', 'oneworld'] },
        ],
        commonQuestionIds: ['q_eu_fsc_1', 'q_cabin_motiv_1'],
      },
    ],
    descriptionTr: 'Finlandiya bayrak taşıyıcı. Asya hub stratejisi. oneworld.',
    insiderTipTr: 'Sessiz, dürüst kültür. Lüks yapay değil — gerçek bağlantı vurgu.',
    websiteUrl: 'https://www.finnair.com',
  },

  // ═══ LOW COST CARRIERS ═══
  {
    id: 'ryanair',
    name: 'Ryanair',
    iataCode: 'FR',
    icaoCode: 'RYR',
    country: 'İrlanda',
    countryEmoji: '🇮🇪',
    region: 'europe-lcc',
    tier: 'lcc',
    hub: 'Dublin (DUB) + 90+ baz',
    fleetSize: 600,
    destinations: 230,
    employeeCount: 22000,
    primaryLanguage: 'English',
    prestige: 3,
    hasMedicalRequirements: true,
    swimTestRequired: true,
    heightRequirementCm: { min: 157, max: 188 },
    interviews: [
      {
        role: 'cabin',
        englishWeight: 80,
        requiredLevel: 'B1',
        totalProcessDays: 30,
        successRatePercent: 30,
        hiringStatus: 'open',
        applicationUrl: 'https://careers.ryanair.com',
        averageSalaryTryK: 50,
        perks: ['Hızlı işe alım', 'Avrupa genişlik', 'Genç ekip'],
        stages: [
          { id: 'fr_c_rd', titleTr: 'Recruitment Day (genelde her şehirde)', titleEn: 'Recruitment Day', durationMinutes: 240, format: 'assessment_day',
            descriptionTr: 'Avrupa\'nın her büyük şehrinde Recruitment Day. Tek günde sonuç.',
            passingTipsTr: ['Hızlı düşünme', 'Çoklu görev', 'On-time obsesyonu'] },
          { id: 'fr_c_train', titleTr: 'Training (kendin öde — ~2K€)', titleEn: 'Self-funded training', durationMinutes: 1, format: 'medical',
            descriptionTr: '6-haftalık eğitim Dublin\'de — kendin ödüyorsun (~2000€). Bittikten sonra iş.',
            passingTipsTr: ['Eğitim masrafı önemli — bütçe planla', 'Sözleşme: ilk 6 ay düşük maaş'] },
        ],
        commonQuestionIds: ['q_lcc_1', 'q_cabin_motiv_1', 'q_lcc_pace'],
      },
      {
        role: 'pilot',
        englishWeight: 90,
        requiredLevel: 'B2',
        totalProcessDays: 45,
        successRatePercent: 25,
        hiringStatus: 'open',
        applicationUrl: 'https://careers.ryanair.com/pilots',
        averageSalaryTryK: 200,
        perks: ['Avrupa\'nın en aktif pilot işe alımı', '737 single-fleet', 'Hızlı upgrade'],
        stages: [
          { id: 'fr_p_app', titleTr: 'Application + sim', titleEn: 'Application', durationMinutes: 240, format: 'sim_check',
            descriptionTr: 'CV + 737 sim check. Type rated tercih.',
            passingTipsTr: ['737NG/MAX type rating tercih', 'Cleane lisans', 'Avrupa baz tercihi belirt'] },
        ],
        commonQuestionIds: ['q_pilot_motiv', 'q_lcc_pace', 'q_pilot_decision'],
      },
    ],
    descriptionTr: 'Avrupa\'nın en büyük LCC. Tek-tip 737 fleet. Hızlı tempo, ucuz bilet.',
    insiderTipTr: 'Cabin için training masrafı kendin ödüyorsun — biliyorsun. Pilot için Avrupa\'da işe en kolay giriş.',
    websiteUrl: 'https://www.ryanair.com',
  },

  {
    id: 'easyjet',
    name: 'easyJet',
    iataCode: 'U2',
    icaoCode: 'EZY',
    country: 'İngiltere',
    countryEmoji: '🇬🇧',
    region: 'europe-lcc',
    tier: 'lcc',
    hub: 'London Luton (LTN) + Gatwick + Geneva + 30 baz',
    fleetSize: 330,
    destinations: 150,
    employeeCount: 14000,
    primaryLanguage: 'English',
    prestige: 4,
    hasMedicalRequirements: true,
    swimTestRequired: true,
    heightRequirementCm: { min: 157, max: 191 },
    interviews: [
      {
        role: 'cabin',
        englishWeight: 85,
        requiredLevel: 'B1',
        totalProcessDays: 30,
        successRatePercent: 25,
        hiringStatus: 'open',
        applicationUrl: 'https://careers.easyjet.com',
        averageSalaryTryK: 60,
        perks: ['Avrupa baz seçimi', 'Daha relax LCC', 'Hızlı kariyer'],
        stages: [
          { id: 'u2_c_app', titleTr: 'Online + AC', titleEn: 'Application', durationMinutes: 240, format: 'assessment_day',
            descriptionTr: 'Online + bölgesel baz AC.',
            passingTipsTr: ['Orange spirit — eğlenceli + profesyonel', 'On-time + safety', 'Çoklu Avrupa şehir'] },
        ],
        commonQuestionIds: ['q_lcc_1', 'q_cabin_motiv_1', 'q_u2_1'],
      },
    ],
    descriptionTr: 'UK + Avrupa LCC. A320 fleet. Daha "premium LCC" pozisyonu.',
    insiderTipTr: 'Ryanair\'dan daha relax kültür. Brexit sonrası UK + EU bazları ayrıldı.',
    websiteUrl: 'https://www.easyjet.com',
  },

  {
    id: 'wizz_air',
    name: 'Wizz Air',
    iataCode: 'W6',
    icaoCode: 'WZZ',
    country: 'Macaristan',
    countryEmoji: '🇭🇺',
    region: 'europe-lcc',
    tier: 'lcc',
    hub: 'Budapest (BUD) + 40+ baz',
    fleetSize: 220,
    destinations: 200,
    employeeCount: 7500,
    primaryLanguage: 'English',
    prestige: 3,
    hasMedicalRequirements: true,
    swimTestRequired: true,
    heightRequirementCm: { min: 158, max: 188 },
    interviews: [
      {
        role: 'cabin',
        englishWeight: 75,
        requiredLevel: 'B1',
        totalProcessDays: 30,
        successRatePercent: 30,
        hiringStatus: 'open',
        applicationUrl: 'https://wizzair.com/careers',
        averageSalaryTryK: 45,
        perks: ['Doğu Avrupa baz', 'Türkiye baz mevcut (SAW)', 'Hızlı işe alım'],
        stages: [
          { id: 'w6_c_app', titleTr: 'Application + Recruitment Day', titleEn: 'Application', durationMinutes: 240, format: 'assessment_day',
            descriptionTr: 'Online + Recruitment Day (Budapest, İstanbul vb.).',
            passingTipsTr: ['Türkiye baz var — TR yararlı', 'Hızlı tempo LCC', 'Çok kültürlü ekip'] },
        ],
        commonQuestionIds: ['q_lcc_1', 'q_w6_1', 'q_cabin_motiv_1'],
      },
    ],
    descriptionTr: 'Doğu Avrupa\'nın en büyük LCC. İstanbul bazı var (Türk için yakın iş).',
    insiderTipTr: 'Türk vatandaşları için en yakın Avrupa LCC bazı. SAW (Sabiha) bazında çalışabilirsin.',
    websiteUrl: 'https://wizzair.com',
  },

  {
    id: 'vueling',
    name: 'Vueling',
    iataCode: 'VY',
    icaoCode: 'VLG',
    country: 'İspanya',
    countryEmoji: '🇪🇸',
    region: 'europe-lcc',
    tier: 'lcc',
    hub: 'Barcelona (BCN)',
    fleetSize: 130,
    destinations: 130,
    employeeCount: 4500,
    primaryLanguage: 'Spanish',
    prestige: 3,
    hasMedicalRequirements: true,
    swimTestRequired: true,
    interviews: [
      {
        role: 'cabin',
        englishWeight: 60,
        requiredLevel: 'B1',
        totalProcessDays: 30,
        successRatePercent: 22,
        hiringStatus: 'open',
        applicationUrl: 'https://www.vueling.com/careers',
        averageSalaryTryK: 50,
        stages: [
          { id: 'vy_c_app', titleTr: 'Application + Barcelona AC', titleEn: 'Application', durationMinutes: 240, format: 'assessment_day',
            descriptionTr: 'Online + Barcelona\'da AC.',
            passingTipsTr: ['İspanyolca B1+', 'Hızlı LCC tempo', 'Akdeniz kültür'] },
        ],
        commonQuestionIds: ['q_lcc_1', 'q_cabin_motiv_1'],
      },
    ],
    descriptionTr: 'IAG grubu LCC. Akdeniz odak.',
    insiderTipTr: 'İspanyolca lazım. Iberia\'ya geçiş yolu olarak görülebilir.',
    websiteUrl: 'https://www.vueling.com',
  },

  {
    id: 'ita_airways',
    name: 'ITA Airways',
    iataCode: 'AZ',
    icaoCode: 'ITY',
    country: 'İtalya',
    countryEmoji: '🇮🇹',
    region: 'europe-fsc',
    tier: 'major',
    hub: 'Rome Fiumicino (FCO)',
    fleetSize: 95,
    destinations: 70,
    employeeCount: 4500,
    primaryLanguage: 'Italian',
    prestige: 4,
    hasMedicalRequirements: true,
    swimTestRequired: true,
    interviews: [
      {
        role: 'cabin',
        englishWeight: 65,
        requiredLevel: 'B1',
        totalProcessDays: 60,
        successRatePercent: 18,
        hiringStatus: 'open',
        applicationUrl: 'https://careers.ita-airways.com',
        averageSalaryTryK: 70,
        stages: [
          { id: 'az_c_it', titleTr: 'İtalyanca + İngilizce', titleEn: 'Italian + English', durationMinutes: 60, format: 'english_test',
            descriptionTr: 'İtalyanca B2+ ZORUNLU. İngilizce B1+.',
            passingTipsTr: ['Italyan kültür', 'Lufthansa Group ortaklığı', 'Premium İtalyan tarz'] },
        ],
        commonQuestionIds: ['q_eu_fsc_1', 'q_cabin_motiv_1'],
      },
    ],
    descriptionTr: 'İtalya yeni bayrak taşıyıcı (Alitalia\'nın yerine). Lufthansa Group %41.',
    insiderTipTr: 'İtalyanca olmadan giriş yok. ITA "Made in Italy" lüks pozisyon.',
    websiteUrl: 'https://www.ita-airways.com',
  },

  {
    id: 'lot_polish',
    name: 'LOT Polish Airlines',
    iataCode: 'LO',
    icaoCode: 'LOT',
    country: 'Polonya',
    countryEmoji: '🇵🇱',
    region: 'europe-fsc',
    tier: 'major',
    hub: 'Warsaw (WAW)',
    fleetSize: 75,
    destinations: 100,
    employeeCount: 5000,
    primaryLanguage: 'Polish',
    prestige: 3,
    hasMedicalRequirements: true,
    swimTestRequired: true,
    interviews: [
      {
        role: 'cabin',
        englishWeight: 70,
        requiredLevel: 'B1',
        totalProcessDays: 45,
        successRatePercent: 22,
        hiringStatus: 'open',
        applicationUrl: 'https://www.lot.com/careers',
        averageSalaryTryK: 50,
        stages: [
          { id: 'lo_c_app', titleTr: 'Application + Warsaw AC', titleEn: 'Application', durationMinutes: 240, format: 'assessment_day',
            descriptionTr: 'Online + Varşova\'da AC.',
            passingTipsTr: ['Lehçe B1 büyük artı', 'Doğu Avrupa odak', 'Star Alliance'] },
        ],
        commonQuestionIds: ['q_eu_fsc_1', 'q_cabin_motiv_1'],
      },
    ],
    descriptionTr: 'Polonya bayrak taşıyıcı. Star Alliance. 787 long-haul ops.',
    insiderTipTr: 'Lehçe öğrenmek şart. Polonya işgücü piyasası rekabetçi.',
    websiteUrl: 'https://www.lot.com',
  },
];
