/**
 * Orta Doğu Havayolları — Pilot ve Kabin mülakat süreçleri.
 *
 * 11 havayolu: Emirates, Etihad, Qatar Airways, Saudia, Gulf Air,
 * Oman Air, Royal Jordanian, flynas, Flydubai, Air Arabia, MEA, EgyptAir.
 *
 * Mülakat süreçleri 2024-2025 verilerine göre. Kaynak: Pprune, RGN,
 * Cabin Crew Connect, official career portals.
 */
import type { AirlineProfile } from './airlineTypes';

export const MIDDLE_EAST_AIRLINES: AirlineProfile[] = [
  {
    id: 'emirates',
    name: 'Emirates',
    iataCode: 'EK',
    icaoCode: 'UAE',
    country: 'BAE (Birleşik Arap Emirlikleri)',
    countryEmoji: '🇦🇪',
    region: 'middle-east',
    tier: 'flagship',
    hub: 'Dubai (DXB) + Dubai World Central (DWC)',
    fleetSize: 260,
    destinations: 150,
    employeeCount: 100000,
    primaryLanguage: 'English',
    prestige: 5,
    hasMedicalRequirements: true,
    swimTestRequired: true,
    heightRequirementCm: { min: 160, max: 212 },
    reachRequirementCm: 212,
    interviews: [
      {
        role: 'cabin',
        englishWeight: 90,
        requiredLevel: 'B2',
        totalProcessDays: 60,
        successRatePercent: 5,
        hiringStatus: 'open_day_only',
        applicationUrl: 'https://www.emiratesgroupcareers.com',
        averageSalaryTryK: 90,
        perks: ['Konut + ulaşım Dubai\'de ücretsiz', 'Aile için ücretsiz uçuş', 'Vergi yok'],
        stages: [
          { id: 'em_c_od', titleTr: 'Open Day (CV drop)', titleEn: 'Open Day', durationMinutes: 60, format: 'group',
            descriptionTr: 'Düzenli olmayan periyotlarda dünyada şehir şehir Open Day düzenlenir. CV teslim + boy/kol uzunluğu ölçümü.',
            passingTipsTr: ['Profesyonel kıyafet (mavi takım/etek)', 'CV İngilizce', 'Profesyonel headshot fotoğraf'] },
          { id: 'em_c_grp1', titleTr: 'Grup egzersizi 1: Reach test + Article reading', titleEn: 'Reach + Reading', durationMinutes: 30, format: 'group',
            descriptionTr: 'Topuk üzerinde 212cm uzanma testi. Sonra grup içinde verilen makale yüksek sesle okunur.',
            passingTipsTr: ['Topuksuz 160cm zorunlu', 'Net telaffuz, doğal tempo', 'Stres altında gülümseme korunur'] },
          { id: 'em_c_grp2', titleTr: 'Grup egzersizi 2: Tartışma', titleEn: 'Group discussion', durationMinutes: 45, format: 'group',
            descriptionTr: 'Hayali senaryo verilir (örn: 5 yolcu, 3 koltuk — kim oturmalı). Grup tartışma + öneri.',
            passingTipsTr: ['Konuşma sırası — diğerlerini dinle', 'Aşırı baskın olma', 'Mantıklı çözüm + empati'] },
          { id: 'em_c_psy', titleTr: 'Psychometric Assessment', titleEn: 'Psychometric', durationMinutes: 90, format: 'psychometric',
            descriptionTr: 'Online numerical reasoning + situational judgment + personality. Final öncesi.',
            passingTipsTr: ['Hızlı ve doğru', 'Trick sorulara dikkat — "müşteriye bağırırım" gibi seçenek YOK', 'Pratik test çöz'] },
          { id: 'em_c_fin', titleTr: 'Final Interview (1-on-1, 60 dk)', titleEn: 'Final 1-on-1', durationMinutes: 60, format: 'one_on_one',
            descriptionTr: 'Senior recruiter + ofiste detaylı CV mülakatı. Davranışsal sorular (STAR), zorlu yolcu vb.',
            passingTipsTr: ['STAR formatı kullan', 'Real customer service örnekleri', 'Dubai yaşam motivasyonu'] },
          { id: 'em_c_med', titleTr: 'Medical + Background', titleEn: 'Medical + BG check', durationMinutes: 240, format: 'medical',
            descriptionTr: 'Tam tıbbi muayene Dubai\'de. Yüzme testi (50m). Geçmiş kontrolü.',
            passingTipsTr: ['Yüzme bilgisi şart', 'Vücut işareti / dövme açıkta görünmemeli', 'Sağlık raporu temiz'] },
        ],
        commonQuestionIds: ['q_em_1', 'q_em_2', 'q_gulf_1', 'q_gulf_2', 'q_gulf_3', 'q_cabin_motiv_1', 'q_cabin_diff_pax'],
      },
      {
        role: 'pilot',
        englishWeight: 85,
        requiredLevel: 'B2',
        totalProcessDays: 90,
        successRatePercent: 8,
        hiringStatus: 'experienced_only',
        applicationUrl: 'https://www.emiratesgroupcareers.com/pilots',
        averageSalaryTryK: 450,
        perks: ['Vergisiz maaş', 'Aile için Dubai konut', '150+ destination network'],
        stages: [
          { id: 'em_p_app', titleTr: 'Online application + logbook check', titleEn: 'Application', durationMinutes: 60, format: 'online_form',
            descriptionTr: 'Min 4000 saat, 2000 multi-crew jet. ATPL + ICAO 4 zorunlu.',
            passingTipsTr: ['Logbook tam, eksiksiz', 'Type rating geçerli', 'Cleane lisans'] },
          { id: 'em_p_tech', titleTr: 'Technical + sim assessment', titleEn: 'Sim check', durationMinutes: 240, format: 'sim_check',
            descriptionTr: '777 veya A380 simülatöründe 4 saatlik check. Engine failure, RTO, ILS.',
            passingTipsTr: ['Standart calls', 'CRM çoklu mürettebat etkin', 'Stres altında doğru karar'] },
          { id: 'em_p_hr', titleTr: 'HR + behavioral panel', titleEn: 'HR panel', durationMinutes: 60, format: 'panel',
            descriptionTr: '3 panel üyesi: senior captain + HR + chief pilot. Davranışsal + scenario.',
            passingTipsTr: ['Liderlik örnekleri', 'CRM hata yönetimi anlat', 'Dubai uzun dönem motivasyonu'] },
          { id: 'em_p_eng', titleTr: 'English proficiency', titleEn: 'English check', durationMinutes: 30, format: 'english_test',
            descriptionTr: 'ICAO 4 doğrulama + plain English scenario.',
            passingTipsTr: ['Akıcılık > kelime hazinesi', 'Aksanlı ama net', 'Frazeoloji kazasız'] },
        ],
        commonQuestionIds: ['q_pilot_motiv', 'q_pilot_crm_fail', 'q_pilot_decision', 'q_em_pilot_1', 'q_pilot_emergency_lead'],
      },
    ],
    descriptionTr: 'Dünyanın en geniş B777 + A380 filosuna sahip. Bayrak taşıyıcı, premium kabin standardı. Dubai hub.',
    insiderTipTr: 'Open Day formatında çok eleyici — hazırlıklı git: gülümseme + İngilizce + müşteri hizmeti hikayesi. Bekleme süresi 4-8 hafta normal.',
    websiteUrl: 'https://www.emirates.com',
  },

  {
    id: 'etihad',
    name: 'Etihad Airways',
    iataCode: 'EY',
    icaoCode: 'ETD',
    country: 'BAE (Abu Dhabi)',
    countryEmoji: '🇦🇪',
    region: 'middle-east',
    tier: 'flagship',
    hub: 'Abu Dhabi (AUH)',
    fleetSize: 90,
    destinations: 70,
    employeeCount: 17000,
    primaryLanguage: 'English',
    prestige: 5,
    hasMedicalRequirements: true,
    swimTestRequired: true,
    heightRequirementCm: { min: 161, max: 212 },
    reachRequirementCm: 212,
    interviews: [
      {
        role: 'cabin',
        englishWeight: 90,
        requiredLevel: 'B2',
        totalProcessDays: 45,
        successRatePercent: 6,
        hiringStatus: 'open',
        applicationUrl: 'https://careers.etihad.com',
        averageSalaryTryK: 85,
        perks: ['Abu Dhabi konut', 'Vergisiz', 'Lüks kabin standardı (Etihad Diamond)'],
        stages: [
          { id: 'et_c_app', titleTr: 'Online assessment', titleEn: 'Online assessment', durationMinutes: 90, format: 'online_form',
            descriptionTr: 'CV + video interview (HireVue) + situational judgment.',
            passingTipsTr: ['Video kalitesi yüksek', 'Aydınlık ortam', 'Net İngilizce'] },
          { id: 'et_c_ad', titleTr: 'Assessment Day (Abu Dhabi/online)', titleEn: 'Assessment Day', durationMinutes: 360, format: 'assessment_day',
            descriptionTr: 'Tam gün: reach test + grup egzersizi + role-play + 1-on-1 final.',
            passingTipsTr: ['Sabah erken — enerjik kal', 'Tüm aşamada gözlemleniyorsun', 'Cep telefonu kapalı'] },
          { id: 'et_c_med', titleTr: 'Medical + visa', titleEn: 'Medical', durationMinutes: 240, format: 'medical',
            descriptionTr: 'Abu Dhabi\'de tam check, vize işlemi.',
            passingTipsTr: ['Yüzme zorunlu', 'BMI kontrol', 'Vücut işareti açıkta yok'] },
        ],
        commonQuestionIds: ['q_et_1', 'q_gulf_1', 'q_gulf_2', 'q_cabin_motiv_1', 'q_cabin_diff_pax', 'q_cabin_team'],
      },
      {
        role: 'pilot',
        englishWeight: 85,
        requiredLevel: 'B2',
        totalProcessDays: 75,
        successRatePercent: 10,
        hiringStatus: 'experienced_only',
        applicationUrl: 'https://careers.etihad.com/pilots',
        averageSalaryTryK: 420,
        perks: ['Vergisiz maaş', 'A350/787 fleet', 'Cadet program (sınırlı)'],
        stages: [
          { id: 'et_p_app', titleTr: 'Application + screening', titleEn: 'Application', durationMinutes: 60, format: 'online_form',
            descriptionTr: 'Min 1500-3000 saat (FO/Captain bandına göre).',
            passingTipsTr: ['ICAO 4+ minimum', 'Type rating tercih (787/350)', 'Clean record'] },
          { id: 'et_p_sim', titleTr: 'Sim assessment', titleEn: 'Sim', durationMinutes: 180, format: 'sim_check',
            descriptionTr: 'A350 sim — handling + procedural.',
            passingTipsTr: ['SOP esaslı uçuş', 'Stable approach', 'Karar netliği'] },
          { id: 'et_p_pan', titleTr: 'Panel interview', titleEn: 'Panel', durationMinutes: 60, format: 'panel',
            descriptionTr: 'Senior pilots + HR + chief pilot.',
            passingTipsTr: ['STAR örnekler', 'Etihad değerleri', 'Long-term commitment'] },
        ],
        commonQuestionIds: ['q_pilot_motiv', 'q_pilot_crm_fail', 'q_et_pilot_1', 'q_pilot_decision'],
      },
    ],
    descriptionTr: 'BAE 2. büyük taşıyıcısı. A380 emekli edildi — yeni A350+787 fleet. Abu Dhabi premium hub.',
    insiderTipTr: 'Etihad "guest journey" felsefesi vurgular — yolcu deneyimi senin merkez konsept olmalı. Cabin: Abu Dhabi yaşam motivasyonu önemli.',
    websiteUrl: 'https://www.etihad.com',
  },

  {
    id: 'qatar',
    name: 'Qatar Airways',
    iataCode: 'QR',
    icaoCode: 'QTR',
    country: 'Katar',
    countryEmoji: '🇶🇦',
    region: 'middle-east',
    tier: 'flagship',
    hub: 'Doha (DOH) — Hamad International',
    fleetSize: 235,
    destinations: 170,
    employeeCount: 48000,
    primaryLanguage: 'English',
    prestige: 5,
    hasMedicalRequirements: true,
    swimTestRequired: true,
    heightRequirementCm: { min: 160, max: 212 },
    reachRequirementCm: 212,
    interviews: [
      {
        role: 'cabin',
        englishWeight: 95,
        requiredLevel: 'B2',
        totalProcessDays: 75,
        successRatePercent: 4,
        hiringStatus: 'open',
        applicationUrl: 'https://careers.qatarairways.com',
        averageSalaryTryK: 95,
        perks: ['Vergisiz maaş', 'Doha konut', 'Skytrax 5-star kabin'],
        stages: [
          { id: 'qr_c_app', titleTr: 'Online + video interview', titleEn: 'Online + video', durationMinutes: 90, format: 'video_interview',
            descriptionTr: 'CV + Pymetrics oyunu + 6 video sorusu (asynchronous).',
            passingTipsTr: ['Video sorularında 60-90 sn', 'Dürüst, samimi', 'Kostüm tam'] },
          { id: 'qr_c_od', titleTr: 'Open Day / Assessment', titleEn: 'Open Day', durationMinutes: 240, format: 'assessment_day',
            descriptionTr: 'Şehir Open Day + reach test + grup tartışma + role-play (zorlu yolcu).',
            passingTipsTr: ['CV "QR formatı" — düzenli', 'Reach test (212cm)', 'Grup içinde 2-3 kez konuş'] },
          { id: 'qr_c_fin', titleTr: 'Final 1-on-1 + telephonic', titleEn: 'Final', durationMinutes: 60, format: 'one_on_one',
            descriptionTr: 'Senior recruiter + ofiste detaylı CV mülakatı. Bazen telefonik final.',
            passingTipsTr: ['"Why Qatar?" net cevap', 'Doha relocation hazırlık', 'Long-term'] },
        ],
        commonQuestionIds: ['q_qr_1', 'q_qr_2', 'q_gulf_1', 'q_gulf_2', 'q_cabin_motiv_1', 'q_cabin_diff_pax'],
      },
      {
        role: 'pilot',
        englishWeight: 85,
        requiredLevel: 'B2',
        totalProcessDays: 90,
        successRatePercent: 7,
        hiringStatus: 'experienced_only',
        applicationUrl: 'https://careers.qatarairways.com/pilots',
        averageSalaryTryK: 480,
        perks: ['Vergisiz maaş', 'A350/777/787 fleet', 'Tax-free family allowance'],
        stages: [
          { id: 'qr_p_screen', titleTr: 'CV screening + invitation', titleEn: 'Screening', durationMinutes: 60, format: 'online_form',
            descriptionTr: 'Min 4000 saat captain / 1500 FO. Type rating tercih.',
            passingTipsTr: ['Multi-crew jet ağırlıkta', 'Long-haul tercih', 'Clean lisans'] },
          { id: 'qr_p_sim', titleTr: 'Sim check (A350 veya 777)', titleEn: 'Sim', durationMinutes: 240, format: 'sim_check',
            descriptionTr: 'Doha\'da yapılır. 4 saat sim — engine fail, RTO, manual flight.',
            passingTipsTr: ['Standart procedures', 'CRM mükemmel', 'Hava ile durum farkındalık'] },
          { id: 'qr_p_pan', titleTr: 'Panel + behavioral', titleEn: 'Panel', durationMinutes: 90, format: 'panel',
            descriptionTr: 'Senior captains + HR. Davranışsal + technical mix.',
            passingTipsTr: ['Skytrax 5-star kalite anlat', 'Liderlik vurgu', 'Doha yaşam'] },
        ],
        commonQuestionIds: ['q_pilot_motiv', 'q_pilot_crm_fail', 'q_qr_pilot_1', 'q_pilot_decision', 'q_pilot_emergency_lead'],
      },
    ],
    descriptionTr: 'Skytrax "World\'s Best Airline" 7 kez. Hamad International hub. Premium global network.',
    insiderTipTr: 'En seçici Gulf carrier. CV "QR template"e uygun olmalı (düzenli, fotoğraflı). Cabin için video soruları kritik — pratik yap.',
    websiteUrl: 'https://www.qatarairways.com',
  },

  {
    id: 'saudia',
    name: 'Saudia',
    iataCode: 'SV',
    icaoCode: 'SVA',
    country: 'Suudi Arabistan',
    countryEmoji: '🇸🇦',
    region: 'middle-east',
    tier: 'flagship',
    hub: 'Jeddah (JED) + Riyadh (RUH)',
    fleetSize: 145,
    destinations: 100,
    employeeCount: 12000,
    primaryLanguage: 'English',
    prestige: 4,
    hasMedicalRequirements: true,
    swimTestRequired: false,
    interviews: [
      {
        role: 'cabin',
        englishWeight: 75,
        requiredLevel: 'B1',
        totalProcessDays: 60,
        successRatePercent: 12,
        hiringStatus: 'open',
        applicationUrl: 'https://careers.saudia.com',
        averageSalaryTryK: 65,
        perks: ['Konut + ulaşım', 'Aile için uçuş', 'Hac/umre indirim'],
        stages: [
          { id: 'sv_c_app', titleTr: 'Online + Riyadh/Jeddah Open Day', titleEn: 'Online + Open Day', durationMinutes: 240, format: 'assessment_day',
            descriptionTr: 'Online başvuru → Suudi Arabistan içinde Open Day. Yabancı kadın için ek kontroller.',
            passingTipsTr: ['Modest dress code', 'Arapça bilmek artı', 'Kültüre saygı vurgu'] },
          { id: 'sv_c_int', titleTr: 'Interview + medical', titleEn: 'Interview', durationMinutes: 90, format: 'panel',
            descriptionTr: 'Panel mülakat + tıbbi muayene.',
            passingTipsTr: ['Cinsiyet ayrımına saygı', 'İslami kültürel uyum', 'Sabırlı kal'] },
        ],
        commonQuestionIds: ['q_sv_1', 'q_cabin_motiv_1', 'q_cabin_culture'],
      },
      {
        role: 'pilot',
        englishWeight: 70,
        requiredLevel: 'B1',
        totalProcessDays: 90,
        successRatePercent: 15,
        hiringStatus: 'open',
        applicationUrl: 'https://careers.saudia.com/pilots',
        averageSalaryTryK: 380,
        perks: ['Vergisiz maaş', 'Konut', '787/A330 fleet'],
        stages: [
          { id: 'sv_p_app', titleTr: 'Application + screening', titleEn: 'Application', durationMinutes: 60, format: 'online_form',
            descriptionTr: 'Min 1500 saat. ATPL + ICAO 4.',
            passingTipsTr: ['Type rating artı', 'Clean record', 'Müslüman tercih ama zorunlu değil'] },
          { id: 'sv_p_sim', titleTr: 'Sim assessment', titleEn: 'Sim', durationMinutes: 180, format: 'sim_check',
            descriptionTr: 'B777 veya A330 sim Jeddah\'da.',
            passingTipsTr: ['Standart SOP', 'CRM güçlü', 'Stres altında sakinlik'] },
        ],
        commonQuestionIds: ['q_pilot_motiv', 'q_sv_pilot_1', 'q_pilot_crm_fail'],
      },
    ],
    descriptionTr: 'Suudi Arabistan bayrak taşıyıcısı. Hac/umre dönemlerinde ek operasyon. Genişleyen filo.',
    insiderTipTr: 'Kadın çalışanlar için ülke kuralları farklı. Genelde Suudi vatandaşlar öncelikli ama yabancı pilot/cabin alımı sürekli.',
    websiteUrl: 'https://www.saudia.com',
  },

  {
    id: 'gulf_air',
    name: 'Gulf Air',
    iataCode: 'GF',
    icaoCode: 'GFA',
    country: 'Bahreyn',
    countryEmoji: '🇧🇭',
    region: 'middle-east',
    tier: 'flagship',
    hub: 'Bahrain (BAH)',
    fleetSize: 38,
    destinations: 50,
    employeeCount: 4500,
    primaryLanguage: 'English',
    prestige: 4,
    hasMedicalRequirements: true,
    swimTestRequired: true,
    heightRequirementCm: { min: 160, max: 200 },
    interviews: [
      {
        role: 'cabin',
        englishWeight: 85,
        requiredLevel: 'B1',
        totalProcessDays: 45,
        successRatePercent: 15,
        hiringStatus: 'open',
        applicationUrl: 'https://careers.gulfair.com',
        averageSalaryTryK: 70,
        perks: ['Bahreyn konut', 'Aile için uçuş', 'Vergisiz'],
        stages: [
          { id: 'gf_c_app', titleTr: 'Online + Open Day', titleEn: 'Application', durationMinutes: 240, format: 'assessment_day',
            descriptionTr: 'Online başvuru → Open Day Bahreyn veya bölgesel şehirlerde.',
            passingTipsTr: ['Net İngilizce', 'Bahreyn yaşam motivasyonu', 'Kültürel uyum'] },
        ],
        commonQuestionIds: ['q_gulf_1', 'q_gulf_2', 'q_cabin_motiv_1'],
      },
    ],
    descriptionTr: 'Bahreyn bayrak taşıyıcı. Lüks "Falcon Gold" business kabin standardı.',
    insiderTipTr: 'Daha ulaşılabilir bir Gulf carrier. Bahreyn nispeten liberal — yabancı için kolay yaşam.',
    websiteUrl: 'https://www.gulfair.com',
  },

  {
    id: 'oman_air',
    name: 'Oman Air',
    iataCode: 'WY',
    icaoCode: 'OMA',
    country: 'Umman',
    countryEmoji: '🇴🇲',
    region: 'middle-east',
    tier: 'flagship',
    hub: 'Muscat (MCT)',
    fleetSize: 50,
    destinations: 50,
    employeeCount: 5500,
    primaryLanguage: 'English',
    prestige: 4,
    hasMedicalRequirements: true,
    swimTestRequired: true,
    heightRequirementCm: { min: 160, max: 200 },
    interviews: [
      {
        role: 'cabin',
        englishWeight: 80,
        requiredLevel: 'B1',
        totalProcessDays: 45,
        successRatePercent: 18,
        hiringStatus: 'open',
        applicationUrl: 'https://careers.omanair.com',
        averageSalaryTryK: 65,
        perks: ['Muscat konut', 'Stabil rotasyon', 'Aile için uçuş'],
        stages: [
          { id: 'wy_c_app', titleTr: 'Application + Open Day', titleEn: 'Application', durationMinutes: 180, format: 'assessment_day',
            descriptionTr: 'Online + Open Day Muscat veya bölgesel.',
            passingTipsTr: ['Profesyonel görünüm', 'Net İngilizce', 'Servis hikayesi'] },
        ],
        commonQuestionIds: ['q_gulf_1', 'q_cabin_motiv_1'],
      },
    ],
    descriptionTr: 'Umman bayrak taşıyıcı. Muscat\'tan global network. Stabil ve aile dostu.',
    insiderTipTr: 'Muscat sakin bir hayat. Diğer Gulf carrier\'lara göre tempo daha düşük.',
    websiteUrl: 'https://www.omanair.com',
  },

  {
    id: 'royal_jordanian',
    name: 'Royal Jordanian',
    iataCode: 'RJ',
    icaoCode: 'RJA',
    country: 'Ürdün',
    countryEmoji: '🇯🇴',
    region: 'middle-east',
    tier: 'major',
    hub: 'Amman (AMM)',
    fleetSize: 25,
    destinations: 50,
    employeeCount: 3500,
    primaryLanguage: 'English',
    prestige: 3,
    hasMedicalRequirements: true,
    swimTestRequired: true,
    interviews: [
      {
        role: 'cabin',
        englishWeight: 75,
        requiredLevel: 'B1',
        totalProcessDays: 30,
        successRatePercent: 22,
        hiringStatus: 'open',
        applicationUrl: 'https://www.rj.com/en/careers',
        averageSalaryTryK: 45,
        stages: [
          { id: 'rj_c_app', titleTr: 'Application + interview Amman', titleEn: 'Application', durationMinutes: 120, format: 'panel',
            descriptionTr: 'Online + Amman\'da yüz yüze mülakat.',
            passingTipsTr: ['Arabic + English avantaj', 'Kültürel duyarlılık', 'Net hizmet hikayesi'] },
        ],
        commonQuestionIds: ['q_cabin_motiv_1', 'q_cabin_diff_pax'],
      },
    ],
    descriptionTr: 'Ürdün bayrak taşıyıcı. Oneworld üyesi. Amman hub.',
    insiderTipTr: 'Daha küçük operasyon, daha kişisel mülakat. Arapça bonus.',
    websiteUrl: 'https://www.rj.com',
  },

  {
    id: 'flynas',
    name: 'flynas',
    iataCode: 'XY',
    icaoCode: 'KNE',
    country: 'Suudi Arabistan',
    countryEmoji: '🇸🇦',
    region: 'middle-east',
    tier: 'lcc',
    hub: 'Riyadh (RUH) + Jeddah (JED)',
    fleetSize: 65,
    destinations: 70,
    employeeCount: 4000,
    primaryLanguage: 'English',
    prestige: 3,
    hasMedicalRequirements: true,
    swimTestRequired: false,
    interviews: [
      {
        role: 'cabin',
        englishWeight: 70,
        requiredLevel: 'A2',
        totalProcessDays: 30,
        successRatePercent: 25,
        hiringStatus: 'open',
        applicationUrl: 'https://careers.flynas.com',
        averageSalaryTryK: 45,
        stages: [
          { id: 'xy_c_app', titleTr: 'Application + Open Day', titleEn: 'Application', durationMinutes: 120, format: 'group',
            descriptionTr: 'Online + Riyadh/Jeddah Open Day.',
            passingTipsTr: ['Hacc/umre operasyon bilinci', 'Modest tutum', 'Energy & smile'] },
        ],
        commonQuestionIds: ['q_lcc_1', 'q_cabin_motiv_1'],
      },
    ],
    descriptionTr: 'Suudi düşük maliyetli. Hızlı büyüyor — Hac/umre yoğun.',
    insiderTipTr: 'Giriş seviyesi kabin için iyi başlangıç. Suudi vatandaş öncelikli.',
    websiteUrl: 'https://www.flynas.com',
  },

  {
    id: 'flydubai',
    name: 'Flydubai',
    iataCode: 'FZ',
    icaoCode: 'FDB',
    country: 'BAE',
    countryEmoji: '🇦🇪',
    region: 'middle-east',
    tier: 'lcc',
    hub: 'Dubai (DXB Terminal 2)',
    fleetSize: 85,
    destinations: 110,
    employeeCount: 4500,
    primaryLanguage: 'English',
    prestige: 4,
    hasMedicalRequirements: true,
    swimTestRequired: true,
    heightRequirementCm: { min: 160, max: 200 },
    interviews: [
      {
        role: 'cabin',
        englishWeight: 80,
        requiredLevel: 'B1',
        totalProcessDays: 30,
        successRatePercent: 18,
        hiringStatus: 'open',
        applicationUrl: 'https://careers.flydubai.com',
        averageSalaryTryK: 60,
        perks: ['Dubai konut', 'Vergisiz', 'Hızlı kariyer'],
        stages: [
          { id: 'fz_c_app', titleTr: 'Application + Assessment Day', titleEn: 'Application', durationMinutes: 240, format: 'assessment_day',
            descriptionTr: 'Online + Dubai\'de tek günlük AC.',
            passingTipsTr: ['Hızlı tempo LCC', 'Multitasking örnekler', 'Dubai motivasyon'] },
        ],
        commonQuestionIds: ['q_lcc_1', 'q_em_1', 'q_cabin_motiv_1'],
      },
      {
        role: 'pilot',
        englishWeight: 85,
        requiredLevel: 'B2',
        totalProcessDays: 60,
        successRatePercent: 15,
        hiringStatus: 'open',
        applicationUrl: 'https://careers.flydubai.com/pilots',
        averageSalaryTryK: 320,
        perks: ['737 single-fleet ops', 'Hızlı upgrade', 'Vergisiz'],
        stages: [
          { id: 'fz_p_sim', titleTr: 'Sim + interview', titleEn: 'Sim + interview', durationMinutes: 240, format: 'sim_check',
            descriptionTr: 'B737 sim check + panel interview Dubai\'de.',
            passingTipsTr: ['737 type rating bonus', 'CRM strong', 'Dubai relocation hazırlık'] },
        ],
        commonQuestionIds: ['q_pilot_motiv', 'q_pilot_crm_fail'],
      },
    ],
    descriptionTr: 'Dubai\'nin LCC operatörü. Emirates ile codeshare. 737 single-fleet.',
    insiderTipTr: 'Emirates\'a göre daha ulaşılabilir. 737 tip pilotlar için iyi giriş.',
    websiteUrl: 'https://www.flydubai.com',
  },

  {
    id: 'air_arabia',
    name: 'Air Arabia',
    iataCode: 'G9',
    icaoCode: 'ABY',
    country: 'BAE (Sharjah)',
    countryEmoji: '🇦🇪',
    region: 'middle-east',
    tier: 'lcc',
    hub: 'Sharjah (SHJ)',
    fleetSize: 75,
    destinations: 170,
    employeeCount: 5000,
    primaryLanguage: 'English',
    prestige: 3,
    hasMedicalRequirements: true,
    swimTestRequired: true,
    interviews: [
      {
        role: 'cabin',
        englishWeight: 75,
        requiredLevel: 'A2',
        totalProcessDays: 30,
        successRatePercent: 25,
        hiringStatus: 'open',
        applicationUrl: 'https://www.airarabia.com/careers',
        averageSalaryTryK: 50,
        stages: [
          { id: 'g9_c_app', titleTr: 'Application + interview', titleEn: 'Application', durationMinutes: 120, format: 'panel',
            descriptionTr: 'Online + Sharjah\'da panel mülakatı.',
            passingTipsTr: ['LCC tempo dayanıklılık', 'Hint Alt-Kıtası dil bonus', 'Çoklu durak operasyon'] },
        ],
        commonQuestionIds: ['q_lcc_1', 'q_cabin_motiv_1'],
      },
    ],
    descriptionTr: 'Orta Doğu\'nun en büyük LCC\'si. Sharjah hub. Hint Alt-Kıtası odaklı.',
    insiderTipTr: 'Hızlı operasyon, çoklu durak. Giriş seviyesi yabancı için kolay.',
    websiteUrl: 'https://www.airarabia.com',
  },

  {
    id: 'mea',
    name: 'Middle East Airlines (MEA)',
    iataCode: 'ME',
    icaoCode: 'MEA',
    country: 'Lübnan',
    countryEmoji: '🇱🇧',
    region: 'middle-east',
    tier: 'major',
    hub: 'Beirut (BEY)',
    fleetSize: 22,
    destinations: 40,
    employeeCount: 4000,
    primaryLanguage: 'English',
    prestige: 3,
    hasMedicalRequirements: true,
    swimTestRequired: true,
    interviews: [
      {
        role: 'cabin',
        englishWeight: 70,
        requiredLevel: 'B1',
        totalProcessDays: 45,
        successRatePercent: 18,
        hiringStatus: 'open',
        applicationUrl: 'https://www.mea.com.lb/careers',
        averageSalaryTryK: 35,
        stages: [
          { id: 'me_c_app', titleTr: 'Application + Beirut interview', titleEn: 'Application', durationMinutes: 120, format: 'panel',
            descriptionTr: 'Online + Beyrut\'ta yüz yüze.',
            passingTipsTr: ['Fransızca + Arapça artı', 'Lübnan konaklı tercih', 'Politik durum farkındalık'] },
        ],
        commonQuestionIds: ['q_cabin_motiv_1', 'q_cabin_diff_pax'],
      },
    ],
    descriptionTr: 'Lübnan bayrak taşıyıcı. Köklü ama küçük operasyon. SkyTeam üyesi.',
    insiderTipTr: 'Lübnan ekonomik durumu dalgalı. Genelde Lübnan vatandaşı tercih.',
    websiteUrl: 'https://www.mea.com.lb',
  },

  {
    id: 'egyptair',
    name: 'EgyptAir',
    iataCode: 'MS',
    icaoCode: 'MSR',
    country: 'Mısır',
    countryEmoji: '🇪🇬',
    region: 'middle-east',
    tier: 'flagship',
    hub: 'Cairo (CAI)',
    fleetSize: 75,
    destinations: 80,
    employeeCount: 30000,
    primaryLanguage: 'English',
    prestige: 3,
    hasMedicalRequirements: true,
    swimTestRequired: true,
    interviews: [
      {
        role: 'cabin',
        englishWeight: 70,
        requiredLevel: 'B1',
        totalProcessDays: 60,
        successRatePercent: 20,
        hiringStatus: 'open',
        applicationUrl: 'https://www.egyptair.com/en/careers',
        averageSalaryTryK: 30,
        stages: [
          { id: 'ms_c_app', titleTr: 'Application + Cairo interview', titleEn: 'Application', durationMinutes: 180, format: 'panel',
            descriptionTr: 'Online + Kahire\'de uzun mülakat süreci.',
            passingTipsTr: ['Mısırlı vatandaşlık genelde gerek', 'Arapça zorunlu', 'Ailevi ilişki bonusu (ortak)'] },
        ],
        commonQuestionIds: ['q_cabin_motiv_1'],
      },
    ],
    descriptionTr: 'Afrika\'nın en eski havayolu. Star Alliance üyesi.',
    insiderTipTr: 'Yabancı için zor giriş. Genelde Mısır vatandaşı tercih.',
    websiteUrl: 'https://www.egyptair.com',
  },
];
