/**
 * Genişletilmiş Kabin Memuru Mülakat Soruları (40+).
 * Kategoriler: motivation, behavioral, situational, role-play, tricky, english.
 */
import type { InterviewQuestion } from './airlineTypes';

export const CABIN_EXTRA_QUESTIONS: InterviewQuestion[] = [
  // ═══════════ MOTIVATION & BACKGROUND ═══════════
  {
    id: 'qc_m1',
    category: 'motivation',
    roles: ['cabin'],
    airlineIds: [],
    question: 'Tell me about yourself in 2 minutes.',
    difficulty: 2,
    goodAnswerPointsTr: [
      'Present-Past-Future yapısı (şu anda ne yapıyorsun, geçmişte ne, gelecek hedef)',
      'Kabin crew\'a uyan beceriler vurgu (servis, ekip, çoklu görev)',
      '90 saniye optimum',
      'Net açılış + kapanış',
    ],
    redFlagsTr: ['Tüm CV oku', 'Özel hayat detayı', '5 dakika sürdür', 'Negatif geçmiş anlat'],
    sampleAnswerTr: 'Ben Ayşe, 26 yaşında, 4 yıllık otelcilik deneyimine sahibim. Halen Marriott\'ta concierge supervisor olarak 8 kişilik ekip yönetiyorum — günde 200+ misafir çıkışı koordine ediyorum. Önceden Anadolu Üniversitesi Turizm İşletmeciliği mezunuyum, Erasmus\'la İspanya\'da 6 ay servis sektörü deneyimledim. İngilizce + İspanyolca + Türkçe rahat. Kabin crew rolüne geçmek istiyorum çünkü 5 yıldızlı servis felsefem havada da geçerli, ama daha global bir alan istiyorum.',
    modelAnswerEn: 'I\'m Ayşe, 26 years old, with 4 years in hospitality. Currently I\'m a concierge supervisor at Marriott Istanbul, leading an 8-person team and coordinating 200+ daily check-outs. I graduated from Anadolu University tourism program, studied 6 months in Spain via Erasmus, and I\'m fluent in Turkish, English, and Spanish. I want to transition to cabin crew because my 5-star service mindset translates directly to in-flight service, but I crave a more global environment.',
    tipsTr: ['90 saniye dene', 'Ayna karşısında pratik', 'STAR sona sakla'],
  },
  {
    id: 'qc_m2',
    category: 'motivation',
    roles: ['cabin'],
    airlineIds: [],
    question: 'Where do you see yourself in 5 years?',
    difficulty: 3,
    goodAnswerPointsTr: [
      'Şirket içi gerçekçi kariyer (purser → cabin manager)',
      'Şirkete bağlı kal — başka kariyer istemiyorsun ima',
      'Skill gelişim hedefi (eğitmen, dil, sertifika)',
      'Şirket ile uzun dönem',
    ],
    redFlagsTr: ['"Pilot olacağım" — kabin sözü vermiyor demektir', '"Belki kendi işim" — flight risk', '"Bilmiyorum"'],
    sampleAnswerTr: 'İlk 2 yıl junior cabin crew olarak deneyim biriktirmek, sonra purser sertifikasyonuna girmek istiyorum. 5. yılda inflight trainer rolüne geçerek hem uçuş hem yeni nesil eğitiminde olmak hedefim. THY\'nin trainer akademisi içinde gelişim yolu çok uygun.',
    tipsTr: ['Şirket içi yol harita bil', 'Realistik sürede kal', 'Şirkete sadakat'],
  },
  {
    id: 'qc_m3',
    category: 'motivation',
    roles: ['cabin'],
    airlineIds: [],
    question: 'What would you do if you were not selected today?',
    difficulty: 3,
    goodAnswerPointsTr: [
      'Pozitif kal — hayal kırıklığı kabul et ama ümitle bitir',
      'Feedback iste, eksiği gör',
      'Tekrar başvurma niyeti (genelde 6 ay bekleme)',
      'O zamana kadar gelişim planı',
    ],
    redFlagsTr: ['"Başka şirkete giderim" — sadakatsiz', 'Saldırgan/üzgün ton', '"Bilmem"'],
    sampleAnswerTr: 'Kabul ederim, fırsat çoktan beklenir. Önce HR\'dan gelişim alanı feedback isterdim. Sonraki 6 ayda İngilizcemi C1\'e çıkarır, ek bir dil (Arapça pratik) eklerdim. 6 ay sonra başvurmayı planlardım — çünkü bu şirkette çalışmak benim için sadece bir iş değil hedef.',
    tipsTr: ['Olgunluk göster', 'Geri bildirim talep et', 'Yeniden başvurma planı'],
  },
  {
    id: 'qc_m4',
    category: 'cv_based',
    roles: ['cabin'],
    airlineIds: [],
    question: 'Why did you leave your last job?',
    difficulty: 4,
    goodAnswerPointsTr: [
      'Pozitif framework — sebep "büyüme/öğrenme" odaklı',
      'Eski işveren kötülenmez',
      'Yeni rolde ne kazanacağına odaklan',
      'Dürüstlük + diplomatik',
    ],
    redFlagsTr: ['Eski patron kötüleme', '"Para az" — kötü görünür', '"Sıkıldım"', 'Çatışma anlat'],
    sampleAnswerTr: 'Marriott\'ta 4 yıl sonra benim için yeni meydan okuma zamanı geldi. Otelcilikte servis becerilerimi geliştirdim, ama global ölçekte çalışmak — bir gün Tokyo\'da, ertesi gün Londra\'da yolcuyla buluşmak — bir sonraki adım. Marriott\'tan ayrılırken iyi ilişkiler korudum, üç ay önceden bilgi verdim.',
    tipsTr: ['"Pull factor" üzerinde dur, "push" değil', 'Profesyonel ayrılış vurgu'],
  },

  // ═══════════ BEHAVIORAL (STAR) ═══════════
  {
    id: 'qc_b1',
    category: 'behavioral',
    roles: ['cabin'],
    airlineIds: [],
    question: 'Tell me about a time you went above and beyond for a customer.',
    difficulty: 3,
    goodAnswerPointsTr: ['STAR formatı', 'Spesifik detay (sayı, isim olmasa da yer)', 'Kişisel inisiyatif', 'Ölçülebilir sonuç'],
    redFlagsTr: ['Genel "her zaman yapardım"', 'STAR yok', 'Övünme tonu'],
    sampleAnswerTr: 'Marriott\'ta (S) bir Japon misafirin uçuşu son anda iptal oldu — 3 saatte bir başkasını organize etmem gerekti. Görevim (T) oteli kontrol etmek değildi ama o gece extra rezervasyon ve transfer ayarlamak. (A) Otelin shuttle\'ını ücretsiz kullandırdım, partner havayolu acentemi aradım, alternatif uçuşu booking\'ini kendim yaptım. (R) Misafir 3 hafta sonra bana özel teşekkür mektubu yolladı, oteli "Booking 9.8" puanladı.',
    tipsTr: ['Spesifik sayı + tarih ver', 'Kendi inisiyatif vurgu', 'Sonuç ölçülebilir'],
  },
  {
    id: 'qc_b2',
    category: 'behavioral',
    roles: ['cabin'],
    airlineIds: [],
    question: 'Describe a time you handled criticism poorly. What did you learn?',
    difficulty: 4,
    goodAnswerPointsTr: ['Dürüst — gerçek hata anlat', 'Tepkiyi sorumluluk olarak al', 'Ne öğrendiğin net', 'Davranış değişikliği örneği'],
    redFlagsTr: ['"Hiç kötü kullanmadım" — yalan görünür', 'Başkasını suçla', 'Öğrenme yok'],
    sampleAnswerTr: 'İlk yılım Marriott\'ta, supervisor\'ım sunum hızımı eleştirdi. Ben (yanlış) "Yeterli zaman vermedin" diye savunmaya geçtim. Eve giderken üzdüm, sonra fark ettim haklıydı — ben acele etmiştim. Ertesi gün özür diledim, "1 hafta detaylı pratik isterim" dedim. Sonraki sunumum mükemmeldi. Şimdi kritik geldiğinde önce dinlerim, savunmaya geçmem.',
    tipsTr: ['Olgun yansıt', 'Davranış değişimi göster', 'Spesifik dur'],
  },
  {
    id: 'qc_b3',
    category: 'behavioral',
    roles: ['cabin'],
    airlineIds: [],
    question: 'Tell me about a stressful situation and how you handled it.',
    difficulty: 3,
    goodAnswerPointsTr: ['STAR — yüksek baskı seçici', 'Sakin davranış', 'Probleme odak', 'Sonuç pozitif'],
    redFlagsTr: ['Stres altında kontrol kaybı', 'Çok dramatize'],
    sampleAnswerTr: 'New Year\'s Eve Marriott — restoran tam dolu, %30 ekip eksik (grip salgını). 4 saatlik shift\'te 200+ kuver. Ben supervisor\'dım. (A) Önce ekiple 30 saniye stand-up — kim ne masaya bakacak. Süreyi 8 dakikalık döngülere böldük. Yanımda her zaman su şişeleriyle dolaştım — masa arasında pratik su servisi. (R) 4 saat sonunda complaint sıfır, satış %12 yüksek. Misafirlerin 3\'ü yıldızlı yorum bıraktı.',
    tipsTr: ['Sakin lider örnek', 'Sayısal sonuç', 'Problemi parçala'],
  },
  {
    id: 'qc_b4',
    category: 'behavioral',
    roles: ['cabin'],
    airlineIds: [],
    question: 'Have you ever made a mistake at work? What did you do?',
    difficulty: 4,
    goodAnswerPointsTr: ['Dürüst — gerçek hata', 'Hızlı sahiplen', 'Düzeltici aksiyon', 'Tekrar olmama önlem'],
    redFlagsTr: ['"Hiç hata yapmadım"', 'Saklamayı dene', 'Başkasını suçla'],
    sampleAnswerTr: 'Bir gün gece vardiyasında VIP rezervasyonu sisteme yanlış oda numarasıyla girmişim. Sabah misafir başka odaya yönlendirilince anladım. (A) Hemen müdüre bildirdim, misafire şahsen özür dileyip suite\'e ücretsiz upgrade verdik. (R) Sonra rezervasyon double-check protokolü önerisi yaptım — ekip uyguladı. Misafir ertesi rezervasyonunda da bizi tercih etti.',
    tipsTr: ['Hata + sahiplen + düzelt + öğren', 'Olgun yaklaşım'],
  },
  {
    id: 'qc_b5',
    category: 'behavioral',
    roles: ['cabin'],
    airlineIds: [],
    question: 'Describe a time when you had to adapt to a sudden change.',
    difficulty: 3,
    goodAnswerPointsTr: ['Esneklik', 'Hızlı adaptasyon', 'Pozitif tutum', 'Sonuç başarılı'],
    redFlagsTr: ['Şikayet tonu', 'Adaptasyon zayıf'],
    sampleAnswerTr: 'COVID döneminde Marriott %50 kapasitede çalıştı, herkes çapraz eğitim aldı. Ben concierge\'dan 2 hafta housekeeping\'e geçtim. İlk gün şok ama 2. günde ekiple sistem kurdum. Misafirden anlık feedback aldık, %15 daha hızlı oda hazırladık.',
    tipsTr: ['Adaptive mindset göster', 'Ekip içi destek vurgu'],
  },

  // ═══════════ SITUATIONAL (uçak içi) ═══════════
  {
    id: 'qc_s1',
    category: 'situational',
    roles: ['cabin'],
    airlineIds: [],
    question: 'A passenger is having a panic attack during turbulence. What do you do?',
    difficulty: 4,
    goodAnswerPointsTr: [
      'Yanına diz çök (göz seviyesinde)',
      'Sakin nefes egzersizi (4-7-8)',
      'Eline temas (uygun ise) — biraz gerilim azalt',
      'Tıbbi belirtiler kontrol — kalp çarpıntısı',
      'Pursar\'a bildir, gerekirse on-board doctor anonsu',
    ],
    redFlagsTr: ['Görmezden gel', 'Otur ve kemer bağla emir tonu', 'Diğer yolcuların önünde utandır'],
    sampleAnswerTr: 'Yanına diz çöküp göz seviyesine inerim, "Yanınızdayım, bu normal türbülans" dimensions sakin sesle. 4-7-8 nefes (4 saniye nefes al, 7 tut, 8 ver) önerirm. Su getirmem. Pursar\'a bildiririm. Belirtiler ciddi olursa (kalp çarpıntısı, göğüs ağrısı) on-board doctor anonsu yapılır.',
    tipsTr: ['Empati önce, prosedür sonra', 'Diğer yolcuyu rahatsız etme'],
  },
  {
    id: 'qc_s2',
    category: 'situational',
    roles: ['cabin'],
    airlineIds: [],
    question: 'Two passengers are arguing loudly in row 14 over a reclining seat. Other passengers are getting upset. Action?',
    difficulty: 4,
    goodAnswerPointsTr: [
      'Hızlı müdahale — ses büyümeden',
      'İki yolcuyu ayrı ayrı dinle',
      'Empati + çözüm önerisi',
      'Gerekirse koltuk değişimi öner',
      'Israr ederse purser → captain decision',
    ],
    redFlagsTr: ['Birinin tarafını tut', 'Yüksek sesle azarla', 'Görmezden gel'],
    sampleAnswerTr: 'Önce ikisinin yanına aynı anda gider, "Yardımcı olabilirim?" derim. İkisini ayrı dinleme — biri arkaya yatırma talep ediyor, diğeri laptop için yer istiyor. Çözüm: laptop sahibinin koltuğunu boş bir koltuğa taşırım, diğerine "Şimdi rahatça yatırabilirsiniz" derim. İkisine de teşekkür ederim. Sorun büyürse purser çağırırım.',
    tipsTr: ['Ses tonu sakin', 'Diplomatik çözüm', 'Hiyerarşi kullan'],
  },
  {
    id: 'qc_s3',
    category: 'situational',
    roles: ['cabin'],
    airlineIds: [],
    question: 'A passenger asks for an alcoholic drink, but you can smell they\'re already drunk. What do you do?',
    difficulty: 4,
    goodAnswerPointsTr: [
      'Kibarca reddet — yasal sorumluluk',
      'Su veya non-alkol alternatif öner',
      'Pursar\'a bildir',
      'Davranış izle (saldırganlık riski)',
    ],
    redFlagsTr: ['Yargılayıcı ton', 'Yolcuyu utandır', 'Servis et zaten ödedi'],
    sampleAnswerTr: '"Beyefendi, bu uçuşta artık yasal sınırı aştığınızı düşünüyorum. Su veya kahve önerebilirim — bedava ve şu an daha iyi gelir." Eğer ısrar ederse pursar\'ı çağırırım. Yolcunun davranışını shift sonu raporuna yazarım.',
    tipsTr: ['"Aviation regulations" referans ver', 'Empati ile reddet', 'Hiyerarşi'],
  },
  {
    id: 'qc_s4',
    category: 'situational',
    roles: ['cabin'],
    airlineIds: [],
    question: 'A child is alone (UM — Unaccompanied Minor) and is crying after takeoff. What\'s your protocol?',
    difficulty: 3,
    goodAnswerPointsTr: [
      'UM özel protokolü bil',
      'Yanına gider, sakinleştir',
      'Koltuğa entertainment (oyuncak, kitap, screen)',
      'Şeker/atıştırmalık (allergen check)',
      'Pursar\'a UM check-in raporu',
    ],
    redFlagsTr: ['Görmezden gel', 'Koridordan "ağlama" demek', 'Tek bırak'],
    sampleAnswerTr: 'Önce yanına diz çöküp göz teması — "Merhaba, ben Ayşe. Korkuyor musun?" Çocuğun adını sorar, anne-baba bilgisi tekrar okurum. UM kit (oyuncak ayı, çikolata, çocuk dergisi) getiririm. Allerjen yoksa bisküvi öneririm. 30 dakika boyunca her 5-10 dk uğrarım. Pursar\'a periyodik bildirim.',
    tipsTr: ['UM = priority pax', 'Düzenli check-in', 'Allergen mutlaka kontrol'],
  },
  {
    id: 'qc_s5',
    category: 'situational',
    roles: ['cabin'],
    airlineIds: [],
    question: 'A passenger requests special meal that wasn\'t pre-ordered. Galley has limited options. Action?',
    difficulty: 3,
    goodAnswerPointsTr: [
      'Empati ile başla',
      'Galley kontrol — meal swap mümkün mü?',
      'Vegan/vegetarian mevcudu öner',
      'Limit varsa snack box + meyve + yoğurt karışımı',
      'Sonraki uçuş için ön sipariş hatırlatması',
    ],
    redFlagsTr: ['"Önceden sipariş etmediniz" tonla', 'Hiçbir şey verme'],
    sampleAnswerTr: '"Anlıyorum efendim, bunu kontrol edeyim." Galley\'e gider, mevcut "vegetarian" varsa ona yönlendiririm. Yoksa: meyve tabağı + yoğurt + helal kek + sıcak su ile çay = aslında çoğu yolcu bunu yeterli bulur. Sonra kart üzerinde "Bir sonraki uçuşta MEAL.com ile 24 saat öncesinden sipariş edebilirsiniz" hatırlatırım.',
    tipsTr: ['Empati + yaratıcı çözüm', 'Önleyici bilgi ver'],
  },
  {
    id: 'qc_s6',
    category: 'situational',
    roles: ['cabin'],
    airlineIds: [],
    question: 'Mid-flight, you spill hot coffee on a business class passenger\'s laptop. What do you do?',
    difficulty: 4,
    goodAnswerPointsTr: [
      'Hemen özür + havlu',
      'Yolcunun yanan tehlikesini önce kontrol',
      'Laptop\'a hızlı kuru havlu, açık ise kapat (su = elektrik tehlikesi)',
      'Pursar\'a bildir — şirket sigortası beyanı',
      'Yolcuya yazılı tazminat bilgisi (genelde havayolu öder)',
    ],
    redFlagsTr: ['Saklamaya çalış', 'Sorumluluk reddetme', 'Ödeme yapmamak için tartış'],
    sampleAnswerTr: '"Çok özür dilerim efendim!" Hemen havlu — önce yolcunun yanmaya karşı kontrol, sonra laptop. Pursar bildirim. Yazılı complaint formu doldurmasına yardım. THY\'nin damage policy hatırlat — laptop tamir/replacement kapsanır.',
    tipsTr: ['Hızlı sahiplen', 'Şirket policy bil', 'Sigorta süreci'],
  },
  {
    id: 'qc_s7',
    category: 'situational',
    roles: ['cabin'],
    airlineIds: [],
    question: 'A pregnant woman feels unwell. What\'s your assessment?',
    difficulty: 4,
    goodAnswerPointsTr: [
      'Belirti sorgu — sancı, kanama, baş dönmesi',
      'Kaç haftalık? (28+ hafta = yüksek risk)',
      'Hemen pursar — gerekirse on-board doctor anonsu',
      'On-board first aid kit hazırla',
      'Captain\'a bilgi — gerekirse divert',
    ],
    redFlagsTr: ['"Geçer" deme', 'Tek başına bırakma', 'Panik göster'],
    sampleAnswerTr: 'Önce hızlı assessment: "Karnınızda ağrı var mı? Kaç haftalıksınız?" 32 haftada acil belirti = yüksek risk. Pursar bildirim, on-board doctor anonsu. Captain\'a iletilir, gerekirse closest suitable airport divert. First aid kit + oxygen hazırla. Yolcuyu sırtüstü değil sol-yan yatırırım (veterocaval syndrome önleme).',
    tipsTr: ['Tıbbi belirtileri bil', 'Hiyerarşi kullan', 'Pasaj pozisyonu önemli'],
  },
  {
    id: 'qc_s8',
    category: 'situational',
    roles: ['cabin'],
    airlineIds: [],
    question: 'You suspect human trafficking — a young woman with an older man, she seems fearful and won\'t make eye contact. What do you do?',
    difficulty: 5,
    goodAnswerPointsTr: [
      'Doğrudan yolcuya soru sorma — adamın önünde tehlikeli',
      'Yolcuyu lavoboya tek davet etmek (özel sebep — meal preference)',
      'Lavoba\'da gizlice "Yardıma ihtiyacın var mı?" sor',
      'Pursar + Captain\'a hemen bildir',
      'Discreet işaretler ile pasifik IATA #IATAFlightsAgainstTrafficking',
    ],
    redFlagsTr: ['Doğrudan ele al', 'Adamla konuş', 'Görmezden gel'],
    sampleAnswerTr: 'Discreet observation — kadını "menü tercihi" için lavoba yakını alanında tek başına davet edirim. "Yardıma ihtiyacın var mı?" sessizce sorar — gözlerimi kullanırım. Pursar\'a hemen bildiririm. Captain\'a — varış noktasında police welcome talep eder. IATA #IATAFlightsAgainstTrafficking protokol uygulanır.',
    tipsTr: ['Bu dünya çapında ciddi sorun', 'IATA eğitimi var', 'Ele verme'],
  },
  {
    id: 'qc_s9',
    category: 'situational',
    roles: ['cabin'],
    airlineIds: [],
    question: 'A passenger complains that crew is "flirting" with their partner. How do you respond?',
    difficulty: 4,
    goodAnswerPointsTr: [
      'Sakin ton — defansif olma',
      'İddia konusunda dinle',
      'Profesyonellik vurgu ama yargılama yok',
      'Pursar\'a bildir — değişikliği yap (başka crew servis et)',
      'Olay raporu',
    ],
    redFlagsTr: ['"Saçmalık" deme', 'Kavgaya gir', 'Görmezden gel'],
    sampleAnswerTr: '"Sizi anlıyorum efendim, profesyonelliğimiz hakkındaki endişe ciddi. Hemen pursar\'ım bilgilendireceğim ve servisinizi başka bir crew member üstlenecek." Ses tonu sakin. Pursar\'a bildirir, rotasyon yapılır. Olay sonrası incidence report.',
    tipsTr: ['Diplomatik dur', 'Şikayetin doğruluğu sorgulanmaz — profesyonellik düzelt'],
  },

  // ═══════════ ROLE-PLAY ═══════════
  {
    id: 'qc_r1',
    category: 'role_play',
    roles: ['cabin'],
    airlineIds: [],
    question: 'Role-play: You\'re welcoming a famous actress in business class. She seems tired and irritable. What\'s your opening?',
    difficulty: 3,
    goodAnswerPointsTr: [
      'Tanıma ama overdose hayranlık değil',
      'Sessiz environment teklif',
      'Pre-takeoff drink önerisi',
      'Discreet privacy guarantee',
    ],
    redFlagsTr: ['Selfie iste', 'Çok konuş', 'Diğer yolcuya söyle'],
    sampleAnswerTr: '"İyi akşamlar Hanım, koltuğunuza buyrun. Pre-takeoff şampanya ister misiniz, yoksa sıcak çay daha iyi gelir? Battaniye + uyku takımı hazır. Beni çağırmak için butonu kullanın — özel bir şey ister misiniz?" Eye contact normal seviye, gülümseme rahatlatıcı.',
    tipsTr: ['Profesyonel mesafe', 'VIP yapma havası yok', 'Discreet servis'],
  },
  {
    id: 'qc_r2',
    category: 'role_play',
    roles: ['cabin'],
    airlineIds: [],
    question: 'Role-play: A passenger lost their wallet during the flight. Walk me through how you handle.',
    difficulty: 3,
    goodAnswerPointsTr: [
      'Sakin bilgi al — son gördüğünüzde nerede?',
      'Yolcunun çevresini sistematik kontrol',
      'Lost & Found protokolü',
      'Indirme öncesi tüm crew bildirim',
      'Found olursa: ID kontrol + iade',
    ],
    redFlagsTr: ['Suç gibi davran', 'Diğer yolcudan şüphelen ima', 'Sorumlu değilim deme'],
    sampleAnswerTr: '"Anladım efendim, sakin olun. Son ne zaman gördünüz? Koltukta mı, lavabo mu?" Ben de yardım ederim — koltuk altı, kavalye cebi, battaniye altı kontrol. Bulamazsak: pursar\'a bildirim, post-flight tam temizlik aramaası yapılır. Vardığımız havaalanında Lost & Found bilgisi verilir.',
    tipsTr: ['Sakin profesyonel', 'Sistematik arama', 'Sonuç süreç bilgisi'],
  },

  // ═══════════ ENGLISH (reading aloud / PA) ═══════════
  {
    id: 'qc_e1',
    category: 'english',
    roles: ['cabin'],
    airlineIds: [],
    question: 'Read aloud this PA announcement: "Ladies and gentlemen, welcome on board flight TK 6. Our flight time today is approximately 12 hours and 30 minutes. We will be cruising at 38,000 feet. Please ensure your seatbelt is fastened and your seat is in the upright position."',
    difficulty: 3,
    goodAnswerPointsTr: [
      'Net telaffuz: "approximately", "cruising", "38,000"',
      'Ton: sıcak ama profesyonel',
      'Hız: orta — yolcunun anlayacağı tempo',
      'Vurgu: kritik bilgi (süre, yükseklik)',
      'Tek nefes ile mantıklı bölme',
    ],
    redFlagsTr: ['Hızlı oku', 'Monoton', 'Yanlış telaffuz', 'Aksanı saklamaya çalış'],
    tipsTr: ['Yüksek sesle pratik', 'Aynaya karşı tonlu pratik', 'Aksanı kabul et — net olsun'],
  },
  {
    id: 'qc_e2',
    category: 'english',
    roles: ['cabin'],
    airlineIds: [],
    question: 'Read aloud: "In the unlikely event of a sudden loss of cabin pressure, oxygen masks will descend automatically from above your seat. Pull the mask towards you, place it firmly over your nose and mouth, secure with the elastic band, and breathe normally."',
    difficulty: 3,
    goodAnswerPointsTr: ['Sakin ama net — panik değil', 'Hareket fiilleri vurgu (pull, place, secure)', 'Yavaş + mantıklı'],
    redFlagsTr: ['Hızlı', 'Korkutucu ton', 'Net olmayan kelime'],
    tipsTr: ['Safety briefing standardı', 'Vücut dili eşliğinde'],
  },
  {
    id: 'qc_e3',
    category: 'english',
    roles: ['cabin'],
    airlineIds: [],
    question: 'How do you say "Welcome aboard, please make yourself comfortable" in 3 different polite ways?',
    difficulty: 3,
    goodAnswerPointsTr: [
      '"Welcome on board, hope you enjoy your flight"',
      '"Good morning/evening, please take your seat and relax"',
      '"Welcome — let us know if there\'s anything we can do for you"',
    ],
    redFlagsTr: ['Sadece bir varyasyon', 'Robot benzeri tekrar'],
    tipsTr: ['Vary your greetings', 'Yolcunun durumuna göre seç (yorgun, neşeli)'],
  },
  {
    id: 'qc_e4',
    category: 'english',
    roles: ['cabin'],
    airlineIds: [],
    question: 'What is the difference between "could" and "would" in cabin service?',
    difficulty: 4,
    goodAnswerPointsTr: [
      'Could = ability/possibility ("Could I have water?" = mümkün mü)',
      'Would = polite preference ("Would you like water?" = ister misiniz)',
      'Cabin service: "Would you like..." daha uygun (servis sunma)',
      'Could you... = yolcudan istek (rica)',
    ],
    redFlagsTr: ['"Aynı şey" deme', 'Yanlış örnek'],
    sampleAnswerTr: '"Could" yetenek/olasılık ifade eder ("Could I have water?" = su alabilir miyim — mümkün mü). "Would" daha kibar/şart ifade eder ("Would you like water?" = su ister misiniz — sıralı tercih). Kabin servisinde "Would you like..." kullanırız (yolcuya servis sunarken). "Could you..." yolcudan ricaya kullanılır ("Could you fasten your seatbelt?" = kemerinizi bağlar mısınız).',
    tipsTr: ['Polite request gramer kritik', 'Yolcu segmentine göre uygun ton'],
  },

  // ═══════════ TRICKY ═══════════
  {
    id: 'qc_t1',
    category: 'tricky',
    roles: ['cabin'],
    airlineIds: [],
    question: 'Why should we hire YOU and not the other 200 candidates?',
    difficulty: 4,
    goodAnswerPointsTr: [
      'Self-confidence + dürüstlük',
      '3 spesifik nokta (hizmet deneyimi, dil, kişilik)',
      'Şirkete ne katarsın somut',
      'Kendini diğerlerine üstün gösterme — kendine odaklan',
    ],
    redFlagsTr: ['"Hepsinden iyiyim"', 'Genelleme', 'Kibirli'],
    sampleAnswerTr: 'Diğer adayların hepsi muhtemelen iyi hazır, bunu kabul ediyorum. Benim 3 farkım: 1) 4 yıl 5-yıldız hospitality — VIP/ünlü servisinde direkt deneyim. 2) Türkçe/İngilizce/İspanyolca rahat konuşma — yolcu çeşitliliğinizde direkt fayda. 3) Bütün ekiplerimde "feedback champion"sım — kritik kabul + uygulamada güçlü. Bu üç nitelik ilk 6 ay içinde size somut katkı verir.',
    tipsTr: ['3 spesifik bullet', 'Şirkete kazanım vurgu', 'Diğerleri kötülenmez'],
  },
  {
    id: 'qc_t2',
    category: 'tricky',
    roles: ['cabin'],
    airlineIds: [],
    question: 'What\'s your biggest weakness?',
    difficulty: 4,
    goodAnswerPointsTr: [
      'Gerçek bir zayıflık (mükemmellik talep, perfeksiyonist gibi cliché değil)',
      'Üzerinde çalışma örneği',
      'Pozitif framework — gelişim',
      'İş için kritik olmayan zayıflık seç',
    ],
    redFlagsTr: ['"Çok perfeksiyonistim" — clichéd', '"Hiç zayıflık yok"', 'İş kritik bir zayıflık seç (ekip oyunu kötü, dakik değilim)'],
    sampleAnswerTr: 'Önceden public speaking — büyük gruplarda sunum gergin oluyordum. Marriott\'ta supervisor olduğumdan beri ekip toplantılarında haftada 3 kez sunum yapıyorum. Ek olarak 1 yıl Toastmasters üyesiyim. Şu an 30 kişiye sunum konforlu. Hala büyük grup öncesi 5 dk hazırlık ritüelim var — ama "stres" "fokus" oldu.',
    tipsTr: ['Üzerinde aktif çalıştığın bir nokta seç', 'Spesifik gelişim kanıtı'],
  },
  {
    id: 'qc_t3',
    category: 'tricky',
    roles: ['cabin'],
    airlineIds: [],
    question: 'If you saw a colleague stealing from the galley, what would you do?',
    difficulty: 5,
    goodAnswerPointsTr: [
      'Önce direct gözlem — emin ol',
      'Kişisel konuş (önce — pürüzsüz)',
      'Etik zorunluluk: pursar/HR bildirim',
      'Whistleblower hakları farkındalık',
      'Davranış ahlaki standart — uçak güvenliği üstün',
    ],
    redFlagsTr: ['"İlişki bozulmasın" görmezden gel', 'Direkt patrona koş', 'Asla raporlama'],
    sampleAnswerTr: 'Önce kesinlikle gördüğüme emin olmam gerek — yorgunum, yanlış görmüş olabilirim. 2 farklı uçuşta tekrarlanırsa: önce kişiyle özel konuşurum ("Senden şunu fark ettim, açıklar mısın?"). Açıklayamazsa veya devam ederse pursar\'a bildirim. Yasal: hırsızlık iş suçu + şirket sigortası etkilenir. Kendi etik zorunluluğum — ihbar etmemek beni de suç ortağı yapar.',
    tipsTr: ['Etik + due process', 'Hassas konu — diplomatik'],
  },
  {
    id: 'qc_t4',
    category: 'tricky',
    roles: ['cabin'],
    airlineIds: [],
    question: 'What if your purser asks you to do something you believe is wrong?',
    difficulty: 5,
    goodAnswerPointsTr: [
      'Önce: emin ol gerçekten yanlış mı yoksa procedure tanımıyor muyum',
      'Özel olarak konuş ("Şunu sorgulamak istedim")',
      'Israr ederse: chain of command takip',
      'Captain\'a bildirim (last resort)',
      'Olay raporu yaz',
    ],
    redFlagsTr: ['"Yapmam!" — direnme', 'Diğer crew\'a şikayet', 'Sessiz kal + sonra suçla'],
    sampleAnswerTr: 'Önce kendi emin olurum: pursar bilmediğim bir procedure mi takip ediyor? Sonra özel konuşurum: "Yardımcı olmak için soruyorum, bunu nasıl yapmamızı istiyorsunuz?" Açıklama mantıklıysa OK. Israr ederse + gerçekten yanlışsa: captain\'a bilgi vermek görevim (CRM gereği). Sonra olay raporu yazarım.',
    tipsTr: ['Hiyerarşi + etik denge', 'Diplomatik ama prensiplere bağlı'],
  },
  {
    id: 'qc_t5',
    category: 'tricky',
    roles: ['cabin'],
    airlineIds: [],
    question: 'Are you willing to relocate to a city where you don\'t speak the language?',
    difficulty: 3,
    goodAnswerPointsTr: ['Açık kabul', 'Adaptasyon plan (dil kursu, kültür)', 'Önceden taşınma deneyimi varsa anlat', 'Long-term commitment'],
    redFlagsTr: ['"Sadece şu şehirde" — esnek değil', 'Tereddüt'],
    sampleAnswerTr: 'Tabi ki. Erasmus\'la İspanya\'da 6 ay yaşadım — başlangıçta ispanyolca yoktu, 6 ay sonra rahat konuştum. Kabin crew rolü beni Tokyo, Paris, Beijing\'e götürebilir — bu beni heyecanlandırıyor. Yeni şehirde önce 3 ay yoğun dil kursu + yerel ekiple network kurarım.',
    tipsTr: ['Past adaptation kanıtı', 'Plan göster'],
  },

  // ═══════════ COMPANY KNOWLEDGE — JENERIK ═══════════
  {
    id: 'qc_ck1',
    category: 'company_knowledge',
    roles: ['cabin'],
    airlineIds: [],
    question: 'What 3 things do you know about our airline that excite you?',
    difficulty: 2,
    goodAnswerPointsTr: ['3 spesifik fact (filo, network, ödül)', 'Heyecan — somut sebep', 'Son gelişme bil', 'Felsefe + değer'],
    redFlagsTr: ['Genel "iyi şirket"', 'Yanlış fact'],
    tipsTr: ['Mülakat öncesi LinkedIn + websitesi', 'Son haberler tarama'],
  },
  {
    id: 'qc_ck2',
    category: 'company_knowledge',
    roles: ['cabin'],
    airlineIds: [],
    question: 'Who is our CEO and what do you think of their leadership?',
    difficulty: 3,
    goodAnswerPointsTr: ['CEO adı doğru', 'Stratejik vizyon bil (recent statement)', 'Pozitif ama dürüst görüş', 'Şirket trajektory'],
    redFlagsTr: ['Yanlış isim', '"Bilmiyorum"', 'Politik yorum'],
    tipsTr: ['Şirket yıllık raporu oku', 'CEO LinkedIn takip et'],
  },

  // ═══════════ GROUP EXERCISE ═══════════
  {
    id: 'qc_g1',
    category: 'group_exercise',
    roles: ['cabin'],
    airlineIds: ['emirates', 'qatar', 'etihad', 'lufthansa', 'british_airways'],
    question: 'GROUP TASK: A flight is overbooked. 3 passengers volunteered. As a team, decide which 3 to give the bumped seats to: a pregnant woman with no urgency, a family of 4 going to a wedding, a businessman with a critical meeting, an elderly couple, a backpacker with flexible plans.',
    difficulty: 4,
    goodAnswerPointsTr: [
      'Grup etkin katıl — sıra sırası',
      'Mantıklı değerlendirme (urgency, vulnerability)',
      'Diğerlerini dinle — tek başına savunma yok',
      'Final consensus — özet',
      'Empati + ticari logic dengesi',
    ],
    redFlagsTr: ['Çok baskın (her şeyi sen söyle)', 'Sessiz kal', 'Diğerlerini kes'],
    sampleAnswerTr: 'Önce gruba "Listeyi prioritize edelim" derim. 1) Hamile + acil değil — kalmalı (sağlık riski + vulnerability). 2) Aile düğüne gidiyor — uzun vadeli plan, alternatif zor — kalmalı. 3) Yaşlı çift — vulnerability, kalmalı. Backpacker + businessman: backpacker esnek plan, çıkmaya hazır olabilir; businessman ticari önemli ama next flight 3 saat sonra varsa — businessman da çıkabilir. Ben grup tartışmasını özetleyip oylama önereirim.',
    tipsTr: ['Grup içi rol — moderatör/özet', 'Empati ile mantık', 'Konsensüs vurgu'],
  },
];
