/**
 * Genişletilmiş Pilot Mülakat Soruları (35+).
 * Kategoriler: technical, situational, behavioral, motivation, tricky.
 */
import type { InterviewQuestion } from './airlineTypes';

export const PILOT_EXTRA_QUESTIONS: InterviewQuestion[] = [
  // ═══════════ TECHNICAL ═══════════
  {
    id: 'qp_te1',
    category: 'technical',
    roles: ['pilot'],
    airlineIds: [],
    question: 'Explain V1, VR, V2 in your own words.',
    difficulty: 4,
    goodAnswerPointsTr: [
      'V1 = decision speed (motor arızası: V1\'den önce abort, V1+1 takeoff)',
      'VR = rotation speed (yoke pull, nose up)',
      'V2 = takeoff safety speed (engine out climb)',
      'V1 ≤ VR ≤ V2 ilişkisi',
      'OEI ve weight etkisi',
    ],
    redFlagsTr: ['Karıştır', 'Aviation terim İngilizce zayıf'],
    sampleAnswerTr: 'V1 — karar hızı. V1\'in altında motor arızası: kalkışı iptal. V1\'i geçtikten sonra: kalkış zorunlu (mesafe yetmez). VR — rotasyon hızı, kontrol kolunu çekip burnu kaldırma. V2 — minimum güvenli tırmanış hızı, tek motor durumda bile uçak güvenle yükselir. Sıralama: V1 ≤ VR ≤ V2. OEI (One Engine Inoperative) durumda V2 minimum, weight + altitude ile değişir.',
    modelAnswerEn: 'V1 is the decision speed — below V1 you abort if engine fails; above V1 you must continue takeoff because there isn\'t enough runway to stop. VR is rotation speed — pull the yoke, nose up. V2 is takeoff safety speed, the minimum speed at which the aircraft can climb safely on one engine. Order is V1 ≤ VR ≤ V2. These speeds are calculated based on weight, altitude, temperature, and runway condition.',
    tipsTr: ['Frazeoloji ezbere', 'Pratik hesap örneği'],
  },
  {
    id: 'qp_te2',
    category: 'technical',
    roles: ['pilot'],
    airlineIds: [],
    question: 'What is the difference between IAS, TAS, GS, and Mach?',
    difficulty: 4,
    goodAnswerPointsTr: [
      'IAS = Indicated Airspeed (pitot okur, density düzeltmesi yok)',
      'TAS = True Airspeed (yükseklik + sıcaklık düzeltmesi)',
      'GS = Ground Speed (TAS ± wind component)',
      'Mach = Hız ÷ ses hızı (yüksek altitude\'da ses hızı düşer)',
      'Climb-cruise: IAS sabit, TAS artar, Mach artar',
    ],
    redFlagsTr: ['Karıştır', 'Yüzde hata'],
    sampleAnswerTr: 'IAS = pitot tüpün okuduğu, dinamik basınç bazlı, density düzeltmesi yok. TAS = IAS + yükseklik + sıcaklık düzeltmesi (FL350\'de TAS IAS\'tan ~%50 yüksek). GS = TAS ± rüzgar (headwind GS\'i azaltır, tailwind artırır). Mach = hız ÷ local ses hızı. Cruise\'da Mach sabit tutulur (M.78), IAS azalır TAS sabit kalır.',
    tipsTr: ['Üç tane farklı durum hesapla pratik', 'FAA airspeed handbook'],
  },
  {
    id: 'qp_te3',
    category: 'technical',
    roles: ['pilot'],
    airlineIds: [],
    question: 'What does "PNF" and "PF" mean in CRM?',
    difficulty: 3,
    goodAnswerPointsTr: [
      'PF = Pilot Flying — uçağı kontrol eden',
      'PNF/PM = Pilot Not Flying / Pilot Monitoring — diğer roller',
      'Görev paylaşımı: PF radio yapmaz, PNF radio + checklist',
      'Tekrar değişim: descend before approach',
    ],
    redFlagsTr: ['Karıştır'],
    sampleAnswerTr: 'PF (Pilot Flying) = uçağı aktif uçuran. PNF/PM (Pilot Monitoring) = diğer pilot — radio communications, checklist, monitoring instruments. Görev paylaşımı: PF\'in elleri tamamen uçakta — uçma + thrust + AP yönetimi. PNF/PM = ATC ile konuşma, ECAM/EICAS okuma, callout yapma. Approach öncesi rotasyon yapılabilir (örn captain landing yapacaksa F/O cruise PF olabilir).',
    tipsTr: ['CRM standart hierarchy', 'Multi-crew SOP'],
  },
  {
    id: 'qp_te4',
    category: 'technical',
    roles: ['pilot'],
    airlineIds: [],
    question: 'Explain TCAS Resolution Advisory (RA) — what do you do?',
    difficulty: 4,
    goodAnswerPointsTr: [
      'RA = TCAS\'in çatışma önleme komutu',
      '"Climb!" or "Descend!" — DERHAL takip et',
      'ATC clearance\'i geçici override',
      'Standart calls: "TCAS climb, TCAS climb"',
      'AP disengage (manual flight)',
      'Conflict cleared: "Clear of conflict" callout, return to ATC instructions',
    ],
    redFlagsTr: ['ATC\'ye sor', 'Çift bakar', 'Yavaş tepki'],
    sampleAnswerTr: 'RA = TCAS\'in trafik çatışması önleme komutu. Komut "Climb climb" veya "Descend descend" net direktif. AP disengage, manual fly, target rate (~1500 fpm) takip. ATC\'ye "TCAS RA" callout. ATC clearance\'i geçici override edilir — TCAS önceliklidir. "Clear of conflict" gelince ATC direction\'a dön ve heading + altitude bildir.',
    tipsTr: ['Standart callouts ezbere', 'Reaction time < 5 seconds', 'AP off zorunlu'],
  },
  {
    id: 'qp_te5',
    category: 'technical',
    roles: ['pilot'],
    airlineIds: [],
    question: 'Walk me through approach minima — what does "CAT II" mean?',
    difficulty: 4,
    goodAnswerPointsTr: [
      'CAT I: DH 200 ft, RVR 550m',
      'CAT II: DH 100 ft, RVR 300m (dual ILS, autoland gerek)',
      'CAT III A/B/C: DH < 100 ft, RVR daha düşük',
      'Aircraft + airport + crew certification gerekli',
      'Decision height: aşağıda visual reference yoksa go-around',
    ],
    redFlagsTr: ['Karıştır', 'CAT III alt türlerini bilme'],
    sampleAnswerTr: 'ILS approach kategorileri görüş düşüklüğüne göre: CAT I = DH 200ft, RVR 550m (single ILS yeter). CAT II = DH 100ft, RVR 300m (dual ILS + autoland gerekli, both pilot CAT II yetkili olmalı, aircraft equipment listed). CAT IIIA/B/C = DH 50/0/0 ft (daha sıkı). Decision height: aşağı geldiğinde visual reference (runway, lights) yoksa go-around şart.',
    tipsTr: ['Şirket OPS spec bil', 'CAT III autoland prosedürü'],
  },
  {
    id: 'qp_te6',
    category: 'technical',
    roles: ['pilot'],
    airlineIds: [],
    question: 'What\'s a stabilized approach? Why is it critical?',
    difficulty: 4,
    goodAnswerPointsTr: [
      '1000ft AGL\'da on path, on speed, on configuration',
      'Sink rate < 1000 fpm normal',
      'Engine spooled up (anti-spool delay)',
      'Speed Vref +5/-0 hedef',
      'Land or go-around — half-stable approach yok',
    ],
    redFlagsTr: ['Spesifik kriter bilmeme'],
    sampleAnswerTr: 'Stable approach = 1000 ft AGL\'da gerekli koşullar: localizer ± 1 dot, glide path ± 1 dot, speed Vref +5/-0, gear extended, flaps in landing config, sink rate < 1000 fpm, thrust at landing power. Tüm bu kriterler karşılanmazsa approach unstable — go-around şart. Çünkü unstable approach kazaların %66\'ında risk faktörü (FAA data).',
    tipsTr: ['Şirket "stable gates" kuralı bil (1000ft IMC, 500ft VMC)', 'No half measures'],
  },
  {
    id: 'qp_te7',
    category: 'technical',
    roles: ['pilot'],
    airlineIds: [],
    question: 'Explain the difference between MEL and CDL.',
    difficulty: 5,
    goodAnswerPointsTr: [
      'MEL = Minimum Equipment List (system inoperative — operate olabilir mi?)',
      'CDL = Configuration Deviation List (missing/damaged external part)',
      'Hem dispatch + flight tarafından kontrol edilir',
      'Restrictions/limitations belirtilir',
      'AOG (Aircraft on Ground) önlemenin standart yolu',
    ],
    redFlagsTr: ['Karıştır'],
    sampleAnswerTr: 'MEL = Minimum Equipment List. Bir sistem inop ise (mesela one autopilot, GPS) operate edilebilir mi, koşullar ne — MEL gösterir. CDL = Configuration Deviation List. External part eksik/hasarlı (mesela static wick, bir flap track fairing) operate edilebilir mi — CDL belirler. İkisi de OEM (Boeing/Airbus) tarafından yayımlanır + havayolu tarafından regulator approval ile kullanılır. MEL/CDL penalti: speed limit, altitude limit, weight limit gibi restrictions.',
    tipsTr: ['MEL/CDL category bil', 'Dispatch + crew shared responsibility'],
  },
  {
    id: 'qp_te8',
    category: 'technical',
    roles: ['pilot'],
    airlineIds: [],
    question: 'You have a "ENG 2 FAIL" message after takeoff. Walk me through the first 5 minutes.',
    difficulty: 5,
    goodAnswerPointsTr: [
      'Memory items first: pitch attitude, max thrust working engine, gear up, cleanup',
      'Flight path: positive rate of climb at V2',
      'PF aviates, PNF/PM communicates ATC',
      'ECAM: confirm + execute (or QRH)',
      'Mayday call when stable',
      'Climb to safe altitude',
      'Workload management: cabin brief, fuel check, divert plan',
      'Captain decides: return / divert',
    ],
    redFlagsTr: ['QRH önce — memory items kaçır', 'CRM unutulmuş'],
    sampleAnswerTr: 'Memory items: yawn rudder asymmetric thrust, set max thrust good engine, pitch ~10° (V2 hedefi), gear up positive rate, lateral cleanup. PF flies, PNF/PM ATC: "Mayday mayday mayday Turkish 1, engine failure, request return". 1500ft AGL minimum yükseklik > ECAM action complete. QRH oku — confirm thrust setting, fuel system, electrical. CRM: cabin secure call, captain decision (return vs alternate), fuel dump if needed. Stable climb to safe altitude (10K+).',
    tipsTr: ['Aviate-Navigate-Communicate', 'A.NIPS.D mnemonic', 'Stress under simulated reps'],
  },
  {
    id: 'qp_te9',
    category: 'technical',
    roles: ['pilot'],
    airlineIds: [],
    question: 'What is fuel planning — explain reserves.',
    difficulty: 4,
    goodAnswerPointsTr: [
      'Trip fuel = origin to destination',
      'Contingency fuel = %5 of trip (or 5 min)',
      'Alternate fuel = destination to alternate airport',
      'Final reserve = 30 min holding at 1500ft',
      'Extra fuel (commander discretion)',
      'Total = trip + cont + alt + final + extra',
    ],
    redFlagsTr: ['Reserve kategori bilme'],
    sampleAnswerTr: 'Standart EU-OPS planlama: 1) Trip fuel (origin→destination). 2) Contingency = %5 trip (turbulence, vector). 3) Alternate fuel (destination→alternate). 4) Final reserve = 30 dakika holding at 1500ft (ICAO). 5) Extra (captain discretion — known weather, etc). Toplam yakıt = trip + cont + alt + final + extra. Min landing fuel = final reserve + alternate.',
    tipsTr: ['EASA Annex IV fuel rules', 'Decision point procedure'],
  },
  {
    id: 'qp_te10',
    category: 'technical',
    roles: ['pilot'],
    airlineIds: [],
    question: 'Explain wake turbulence categories and separation requirements.',
    difficulty: 4,
    goodAnswerPointsTr: [
      'Heavy/Medium/Light/Super (A380)',
      'Heavy behind Heavy: 4 NM',
      'Medium behind Heavy: 5 NM',
      'Light behind Heavy: 6 NM',
      'Time-based: 2-3 min behind heavy',
    ],
    redFlagsTr: ['Sayı bilmeme'],
    sampleAnswerTr: 'ICAO kategorileri: Light (<7 ton), Medium (7-136 ton), Heavy (>136 ton), Super (A380). Vortex strength weight + speed + wing span ilişkili. Min separation: heavy behind heavy 4NM, medium behind heavy 5NM, light behind heavy 6NM. Time-based take-off: 2 min behind heavy, 3 min behind super. Cross-runway: 3 min mandatory.',
    tipsTr: ['ICAO Doc 4444 separation', 'Wake encounter procedure'],
  },

  // ═══════════ SITUATIONAL (DECISION) ═══════════
  {
    id: 'qp_s1',
    category: 'situational',
    roles: ['pilot'],
    airlineIds: [],
    question: 'You\'re cruising at FL370 and a passenger requires medical diversion. Closest airport is 200 NM behind, ahead is 350 NM. Both have poor weather. How do you decide?',
    difficulty: 5,
    goodAnswerPointsTr: [
      'On-board doctor consultation — durum acil mi?',
      'Medlink/Medaire (medical advisory)',
      'Two airport weather + facilities',
      'Behind: turn-back fuel, descend time',
      'Ahead: continue forward speed advantage',
      'Captain decision after data',
      'Cabin briefing + crew',
    ],
    redFlagsTr: ['Bilgi toplamadan karar', 'CRM atla'],
    sampleAnswerTr: 'Önce: cabin\'den medical situation detayı al, on-board doctor mı var. Medlink call (PFA-equipped airline\'larda standard) — physician advisory. Sonra weather check her iki havaalanı + medical facilities. Behind 200NM = turn back + descend ~25 min. Ahead 350NM = ~40 min ama önümde yön. Eğer kalp krizi/stroke = yakın olan kritik (golden hour). Eğer stable = ileri continue. Decision tree CRM ile co-pilot consult. Final captain command.',
    tipsTr: ['Medlink/Medaire bil', 'Golden hour concept', 'Captain authority + CRM'],
  },
  {
    id: 'qp_s2',
    category: 'situational',
    roles: ['pilot'],
    airlineIds: [],
    question: 'During preflight, you discover a previous crew\'s tech log has unusual entry: "minor turbulence, smoke briefly seen in galley". Maintenance signed off as "investigated, no defect found". You\'re uncomfortable. Action?',
    difficulty: 5,
    goodAnswerPointsTr: [
      'Tech log signature kontrol — engineer name + time',
      'Önce maintenance ile direct konuş — detay iste',
      'Şüphe sürerse: chief pilot / ops control bildirim',
      'Captain authority — uçmayı reddedebilirim eğer şüphe makul',
      'Uçtuğun anda tüm fire detection sistemler aktif kontrol',
    ],
    redFlagsTr: ['Sessiz kal — uç', 'Sadece kendi crew\'a şikayet'],
    sampleAnswerTr: 'Tech log entries\'i tekrar dikkatle okurum + engineer signature kontrol. Maintenance hangar\'a gider direkt sorarım: "ne araştırıldı, neden no defect found?" Mantıklı açıklama varsa OK. Şüphe sürerse: chief pilot duty officer\'a bildirim → ek inspection talep. Captain authority kullanırım: makul şüphe varsa uçmayı reddedebilirim, dispatch tarafından ücret cezası YOK (CAR/EASA captain authority).',
    tipsTr: ['Captain authority bil', 'Documentation chain', 'No-blame culture'],
  },
  {
    id: 'qp_s3',
    category: 'situational',
    roles: ['pilot'],
    airlineIds: [],
    question: 'You\'re short final to land. F/O calls "go around — runway not clear". You can\'t see anything wrong. What do you do?',
    difficulty: 5,
    goodAnswerPointsTr: [
      'F/O call = trust + execute go-around',
      'CRM: assertiveness saygı',
      '"Yes, going around" + standart procedure',
      'Stable climb-out + ATC notify',
      'Sonradan: F/O ne gördüyse debrief',
      'Reject "ego mode"',
    ],
    redFlagsTr: ['"Görmüyorum" deyip devam et', 'F/O\'yu sorgulа landing during', 'Geç tepki'],
    sampleAnswerTr: 'Hemen "Going around" call yapar, max thrust + pitch attitude pull-up, gear up positive rate, flap retract, ATC inform. F/O\'nun görüşüne saygı — multi-crew CRM\'in özü budur (her ikisi gözlüyor, bir tane yeterli karar). Sonra debrief: F/O ne gördüğü? Vehicle? Bird? Animal? Senin bakış açın blocked olabilir.',
    tipsTr: ['CRM "any pilot can call go-around"', 'Trust > ego', 'Debrief later'],
  },
  {
    id: 'qp_s4',
    category: 'situational',
    roles: ['pilot'],
    airlineIds: [],
    question: 'You\'re tired but commercial pressure says fly. How do you handle?',
    difficulty: 4,
    goodAnswerPointsTr: [
      'Fatigue = real safety risk',
      '"Fit to fly" honest self-assessment',
      'Captain authority — refuse if not fit',
      'Crew scheduler bilgilendir',
      'No retaliation — protected by FRMS regulations',
      'Personal coffee/snack alternatif değil — yorgun = unsafe',
    ],
    redFlagsTr: ['Uç + kendine söyle "iyiyim"', 'Pressure altında karar'],
    sampleAnswerTr: 'Fatigue gerçek bir hazard — boring approach + mistake = kazaya yol. "Fit to fly" self-assessment dürüstçe yaparım: kaç saat uyku, son uçuş ne zaman, current alertness. Yetersizsem: schedulers\'i bilgilendirir, "I\'m not fit to fly" dururum. EASA/FAA/SHGM fatigue rules pilotları korur — ücret cezası YOK. Kahve quick fix değil — yorgun = unsafe.',
    tipsTr: ['FRMS bil', 'IM SAFE checklist (Illness, Medication, Stress, Alcohol, Fatigue, Eating)'],
  },

  // ═══════════ BEHAVIORAL ═══════════
  {
    id: 'qp_b1',
    category: 'behavioral',
    roles: ['pilot'],
    airlineIds: [],
    question: 'Tell me about a time when you disagreed with a captain\'s decision.',
    difficulty: 4,
    goodAnswerPointsTr: [
      'STAR formatı',
      'Anlaşmazlık olgun şekilde ifade',
      'Captain authority\'a respect',
      'Sonuç: hangi karar alındı, ne oldu',
      'CRM teknikleri: PACE (Probe, Alert, Challenge, Emergency override)',
    ],
    redFlagsTr: ['Captain kötüleme', '"Haklı çıktım" tonu', 'Çatışma genişletme'],
    sampleAnswerTr: 'F/O olarak (S) düşük tabanlı buluttan ILS yaklaşma yapacaktık, hava limit\'a yakındı. Captain "continue" dedi. (T) Ben advisory ile probe ettim: "Captain, RVR 550m sınırda, alternative\'mizi taze tutalım mı?" (A) Captain açıklama yaptı: "Wind shift 10 dk önce, RVR yükseldi, ATC report aldım." Mantıklıydı. (R) Indik. Ama post-flight debrief\'te, "İlk briefing\'de bilgi paylaşılsa daha iyi olurdu" feedback verdim. Captain takdir etti.',
    tipsTr: ['PACE technique', 'Authority + assertiveness denge'],
  },
  {
    id: 'qp_b2',
    category: 'behavioral',
    roles: ['pilot'],
    airlineIds: [],
    question: 'Describe a time when you handled a stressful in-flight situation.',
    difficulty: 4,
    goodAnswerPointsTr: ['STAR + spesifik', 'Aviate-Navigate-Communicate', 'CRM kullanımı', 'Sonuç pozitif + öğrenilen'],
    redFlagsTr: ['Genel cevap', 'Stres altında kontrol kayıp anlat'],
    sampleAnswerTr: '737 cruise FL370\'te (S) cabin altitude warning aktif oldu — 10K\'da bile kaçak basınç düşüyor. (T) F/O olarak monitor + CRM. (A) Captain memory items: oxygen masks, emergency descent. Ben ATC + cabin call. 10 dakikada FL100\'a indik. (R) Cabin pressurization sealed flight deck door seal failure çıktı. Closest airport\'a divert ettik. Tüm yolcular OK, hizmet geri kazanıldı 24 saat içinde.',
    tipsTr: ['Spesifik teknik detay', 'Multi-crew rolleri net'],
  },

  // ═══════════ MOTIVATION + TRICKY ═══════════
  {
    id: 'qp_m1',
    category: 'motivation',
    roles: ['pilot'],
    airlineIds: [],
    question: 'Why did you choose to be a pilot?',
    difficulty: 2,
    goodAnswerPointsTr: ['Kişisel + spesifik', 'İlk uçuş anısı', 'Profesyonel motivation', 'Lifelong learning'],
    redFlagsTr: ['"Gökyüzünü severim" yüzeysel', 'Para odaklı'],
    sampleAnswerTr: 'İlk uçuş — 8 yaşında babamla TK 1\'de, kaptan kabini ziyaret. O an bu mesleği seçtim. Çünkü uçmak hem teknik mükemmellik (fizik, matematik, mühendislik) hem insan factor (CRM, leadership) hem de coğrafyaya hakim olma — bu üçü bir mesleğin nadir kombinasyonu. Lifelong learning aspect (yeni tip ratings, regulations, sim) beni asla sıkmıyor.',
    tipsTr: ['Spesifik anekdot', 'Çok yönlü motivasyon'],
  },
  {
    id: 'qp_t1',
    category: 'tricky',
    roles: ['pilot'],
    airlineIds: [],
    question: 'If you fail this interview, what will you do?',
    difficulty: 4,
    goodAnswerPointsTr: ['Pozitif + olgun', 'Feedback iste', 'Tekrar başvurma planı', 'Beklerken gelişim'],
    redFlagsTr: ['"Başka şirkete giderim"', 'Olumsuz tepki'],
    tipsTr: ['Olgunluk + bağlılık'],
  },
  {
    id: 'qp_t2',
    category: 'tricky',
    roles: ['pilot'],
    airlineIds: [],
    question: 'You see a co-pilot drinking the night before a 0600 flight. What do you do?',
    difficulty: 5,
    goodAnswerPointsTr: [
      'IATA "8 hours bottle to throttle" rule',
      'Önce direct konuş — discreet',
      'Sabah fit-to-fly kontrol',
      'Şüphe varsa: chief pilot bildirim',
      'Etik zorunluluk + safety',
    ],
    redFlagsTr: ['Sessiz kal', 'Direkt patrona gitme without warning'],
    sampleAnswerTr: 'Bottle-to-throttle 8 saat (FAA 8h, EASA 8h) — limit. Eğer co-pilot 0600 flight\'a 2200\'de 5 bira içti = limit\'e çok yakın. Önce direkt konuşurum: "Yarınki uçuş için kaç saat var?" Eğer kabul ederse — break-in protocol, restrekas. Reddederse veya sabah fit görünmezse: chief pilot duty officer hemen bildirim. Etik zorunluluk + safety şart.',
    tipsTr: ['Industry standards bil', 'Discreet ama firm'],
  },
  {
    id: 'qp_t3',
    category: 'tricky',
    roles: ['pilot'],
    airlineIds: [],
    question: 'You\'ve been offered the same role at three different airlines. Why us?',
    difficulty: 4,
    goodAnswerPointsTr: ['Şirket için spesifik 3 sebep', 'Diğerlerini kötüleme', 'Long-term commitment', 'Şirket ile growth'],
    redFlagsTr: ['Sadece para', 'Diğerlerini kötüle'],
    tipsTr: ['Şirket cultural fit vurgu'],
  },
  {
    id: 'qp_t4',
    category: 'tricky',
    roles: ['pilot'],
    airlineIds: [],
    question: 'How do you handle financial pressure to "press on" against your judgment?',
    difficulty: 5,
    goodAnswerPointsTr: ['"Captain authority is final" — hayır deme yetki', 'Pilot Code of Ethics', 'Şirket safety culture', 'No pressure should override safety'],
    redFlagsTr: ['"Pressure altında uçarım" tonu', 'Etik bilinç eksik'],
    sampleAnswerTr: 'Hayır basit: captain authority final, hiçbir commercial pressure safety\'i geçemez. Şirket gerçekten safety-conscious ise bu cevap takdir görür. EASA + FAA captain authority koruyor. Pilot olarak ben, pasaj + crew güvenliğinden sorumlu. Schedule problem ise — şirket çözer. Safety problem ise — ben çözmem ama kabul etmem.',
    tipsTr: ['Etik prensip net', 'Endüstri ahlakı bil'],
  },

  // ═══════════ ENGLISH (ICAO 4 STYLE) ═══════════
  {
    id: 'qp_e1',
    category: 'english',
    roles: ['pilot'],
    airlineIds: [],
    question: 'You receive: "Turkish 1, vectors 270 to intercept localizer 24L, descend 4000". Read back.',
    difficulty: 4,
    goodAnswerPointsTr: [
      'Standart readback: vector + descent + altitude + intercept + runway',
      'Callsign sonda',
      'Tempo orta',
      'Frazeoloji ICAO Doc 9432 uyumlu',
    ],
    redFlagsTr: ['Eksik bilgi readback', 'Yanlış sıra'],
    sampleAnswerTr: '"Heading 270 to intercept localizer 24 left, descending 4000, Turkish 1."',
    modelAnswerEn: '"Heading 270 to intercept localizer 24 left, descending 4000 feet, Turkish 1."',
    tipsTr: ['Readback rules ezbere', 'Numbers fonetik (tree, fife, niner)'],
  },
  {
    id: 'qp_e2',
    category: 'english',
    roles: ['pilot'],
    airlineIds: [],
    question: 'Describe in plain English to ATC: you have a fuel pump failure but flight can continue.',
    difficulty: 4,
    goodAnswerPointsTr: [
      '"PAN PAN PAN PAN PAN PAN" — urgency level',
      'Flight ID + nature problem + assistance',
      'Plain English — phraseology yetmediğinde',
      'Sakin + net',
    ],
    redFlagsTr: ['Mayday declare et — yanlış level', 'Phraseology yok'],
    sampleAnswerTr: '"Pan Pan Pan Pan Pan Pan, Istanbul Approach, Turkish 6, we have a fuel pump failure on the right tank, but flight can continue normally. Request priority handling and a closer alternate if needed. We have 3 hours of fuel remaining."',
    modelAnswerEn: '"Pan Pan Pan Pan Pan Pan, Istanbul Approach, Turkish 6, we have a fuel pump failure on the right tank, flight able to continue. Request priority handling. Three hours fuel remaining."',
    tipsTr: ['Mayday vs Pan Pan farkı', 'Plain English net + brief'],
  },
];
