/**
 * Genişletilmiş rol soruları V2 — Teknisyen + Yer hizmetleri + Student dengesi.
 *
 * V1 (questionsRolesExtra.ts) toplam 22 soru: technician 7, ground 6, student 6.
 * V2 +90 soru ile rol başına ~37 soruya çıkıyor — pilot+kabin'le orantılı.
 *
 * detailedExplanationTr boş — Gemini content pipeline tarafından doldurulur.
 * Inject sonrası 18 dile çevrilir.
 */
import type { InterviewQuestion } from './airlineTypes';

export const ROLES_EXTRA_QUESTIONS_V2: InterviewQuestion[] = [
  // ═══════════════════════════════════════════════════
  //  TEKNİSYEN +30 (qt_te8 → qt_te37)
  // ═══════════════════════════════════════════════════

  {
    id: 'qt_te8',
    category: 'technical',
    roles: ['technician'],
    airlineIds: [],
    question: 'What is hot section maintenance for turbine engines?',
    difficulty: 4,
    goodAnswerPointsTr: ['Combustion chamber + HPT/LPT zone', 'Sıcaklık 1400°C+', 'Borescope + crack check', 'TBO interval', 'Module replacement'],
    redFlagsTr: ['Hot section bilmeme'],
    sampleAnswerTr: 'Hot section = combustion chamber + HP/LP turbine bölgesi (1400°C+). HSI (Hot Section Inspection) interval (örn 4000 cycle CFM56). Borescope ile crack, burn-through, eksik blade tespiti. Engine on-wing veya shop\'ta. Module bazlı replacement: combustion liner, HPT blade set.',
    tipsTr: ['EGT margin trend takibi', 'Borescope yetkinliği'],
  },
  {
    id: 'qt_te9',
    category: 'technical',
    roles: ['technician'],
    airlineIds: [],
    question: 'What ETOPS dispatch requirements does maintenance need to verify?',
    difficulty: 5,
    goodAnswerPointsTr: ['ETOPS-significant systems', 'Dual independent task verification', 'Separation of tasks (different mech)', 'Pre-departure check', '180/240 min capability'],
    redFlagsTr: ['ETOPS bilmeme'],
    sampleAnswerTr: 'ETOPS dispatch için ETOPS-significant systems (engines, fuel, electrical, hydraulic) ayrı mekanikler tarafından onaylanmalı (separation of tasks principle). Pre-departure check özel. CMP (Configuration Management Plan) compliance. ETOPS 180/240/330 min capability sertifikalı. Single-thread fault tolerance.',
    tipsTr: ['Part-CAT ETOPS bilgisi', 'B767/A330 ETOPS deneyim'],
  },
  {
    id: 'qt_te10',
    category: 'technical',
    roles: ['technician'],
    airlineIds: [],
    question: 'Difference between MEL and CDL?',
    difficulty: 4,
    goodAnswerPointsTr: ['MEL = Minimum Equipment List (sistemler)', 'CDL = Configuration Deviation List (eksik panel/yapı)', 'OEM yayınlar', 'O/C/B kategoriler', 'Operational restrictions'],
    redFlagsTr: ['Karıştır'],
    sampleAnswerTr: 'MEL = Minimum Equipment List, hangi sistemler INOP olabilir + dispatch koşulları (örn 1 nav radio inop ile 3 günlük). CDL = Configuration Deviation List, hangi yapısal/aerodynamic parça eksik kalabilir (örn küçük gear door panel) + speed/altitude/range restriction.',
    tipsTr: ['MEL O/C/B/D kategori bilgi', 'CDL placard practice'],
  },
  {
    id: 'qt_te11',
    category: 'technical',
    roles: ['technician'],
    airlineIds: [],
    question: 'When and how do you perform a borescope inspection?',
    difficulty: 4,
    goodAnswerPointsTr: ['Engine HSI interval', 'Damage/FOD raporu sonrası', 'Cooling fan giriş + igniter port', 'Photo + video kayıt', 'Damage chart compare'],
    redFlagsTr: ['Borescope bilmeme'],
    sampleAnswerTr: `Borescope = motor iç bakımı için fiber-optik kamera. HSI interval, FOD ingestion sonrası, ya da pilot raporu (vibration, EGT spike) sonrası. Igniter port veya dedicated port'tan girer, video kayıt. Blade crack, burn, missing piece, FOD damage tespiti. Damage chart (AMM/CMM) ile compare → in-limit, repair, replacement.`,
    tipsTr: ['Engine type-spec borescope', 'Photo documentation'],
  },
  {
    id: 'qt_te12',
    category: 'technical',
    roles: ['technician'],
    airlineIds: [],
    question: 'What are the 5 main NDT (Non-Destructive Testing) methods?',
    difficulty: 4,
    goodAnswerPointsTr: ['Visual', 'Liquid Penetrant (LP)', 'Magnetic Particle (MP)', 'Eddy Current (EC)', 'Ultrasonic (UT)', 'Radiographic (RT)'],
    redFlagsTr: ['Az tip say'],
    sampleAnswerTr: 'NDT = parçayı bozmadan crack tespiti. 1) Visual (gözle / büyüteç) 2) LP = surface crack için sıvı + developer 3) MP = ferromagnetic parçalarda manyetik alan + iron particle 4) EC = induced current iletkenlik 5) UT = ultrasonik dalga deeper crack 6) RT = X-ray internal. Level 1/2/3 sertifikasyonu var (NAS 410, EN 4179).',
    tipsTr: ['NDT Level 2 sertifika hedefi', 'Method seçimi material/defect bağlı'],
  },
  {
    id: 'qt_te13',
    category: 'technical',
    roles: ['technician'],
    airlineIds: [],
    question: 'Cycle vs Flight Hour: which interval drives more maintenance?',
    difficulty: 3,
    goodAnswerPointsTr: ['Cycle = takeoff+landing', 'Pressurization fatigue → cycle-driven', 'Engine wear → mostly FH', 'Landing gear → cycle', 'Whichever comes first'],
    redFlagsTr: ['Karıştır'],
    sampleAnswerTr: `Cycle = 1 takeoff + 1 landing. Fuselage pressurization, landing gear, brakes cycle-driven (her kalkış-iniş yorgunluk). Engine, oil, filter çoğunlukla flight hour. Maintenance task interval "1500 FH or 600 FC, whichever comes first" şeklindedir. Short-haul (TK) cycle'a yetişir, long-haul (Emirates) FH'a.`,
    tipsTr: ['MPD interval okuma', 'Aircraft type cycle/FH oranı bil'],
  },
  {
    id: 'qt_te14',
    category: 'technical',
    roles: ['technician'],
    airlineIds: [],
    question: 'AMM vs CMM — when do you use each?',
    difficulty: 3,
    goodAnswerPointsTr: ['AMM = Aircraft Maintenance Manual (full aircraft)', 'CMM = Component Maintenance Manual (component shop)', 'AMM line/base, CMM shop', 'AMM ATA chapter, CMM PN'],
    redFlagsTr: ['Karıştır'],
    sampleAnswerTr: 'AMM = uçak üzerinde line + base maintenance için. ATA chapter organize, troubleshooting, removal/install, servicing. CMM = removed component shop\'ta açıp tamir/test ederken. PN-specific, internal disassembly, calibration. Pratik: line tech AMM kullanır, shop tech CMM. Boeing/Airbus AMM ücretsiz fakat CMM vendor-specific lisans.',
    tipsTr: ['AMM ATA navigasyon', 'CMM access izin'],
  },
  {
    id: 'qt_te15',
    category: 'technical',
    roles: ['technician'],
    airlineIds: [],
    question: 'How do you handle an Airworthiness Directive (AD)?',
    difficulty: 5,
    goodAnswerPointsTr: ['AD = mandatory FAA/EASA action', 'Compliance deadline', 'CAMO planning', 'Tech log entry + signature', 'Reporting back to authority'],
    redFlagsTr: ['Optional sayma'],
    sampleAnswerTr: 'AD = Airworthiness Directive, FAA/EASA tarafından mandatory issued. Critical safety issue (örn structural crack, engine fault). Compliance deadline (örn 100 FH, 6 ay, 1 cycle next inspection). CAMO planning yapar, base maintenance içinde uygular. Tech log entry "AD compliance per [reference]". Authority\'ye compliance report gönder.',
    tipsTr: ['EASA AD database takip', 'CAMO / Part-M role'],
  },
  {
    id: 'qt_te16',
    category: 'technical',
    roles: ['technician'],
    airlineIds: [],
    question: 'What\'s the difference between an SB and an AD?',
    difficulty: 3,
    goodAnswerPointsTr: ['SB = OEM Service Bulletin (önerilir)', 'AD = Authority mandatory', 'AD compliance zorunlu', 'SB cost-benefit kararı', 'AD bazen SB referansı verir'],
    redFlagsTr: ['Karıştır'],
    sampleAnswerTr: 'SB = Service Bulletin, OEM\'in (Boeing, Airbus, CFM) önerdiği değişiklik/inspeksiyon. Optional except recommended. AD = Authority (FAA/EASA) tarafından mandatory bağlı. AD genelde "comply with SB X by date Y" şeklinde SB\'yi mandatory yapar. Compliance status maintenance records\'ta tutulur.',
    tipsTr: ['SB vs AD doku trail', 'Operator policy bil'],
  },
  {
    id: 'qt_te17',
    category: 'technical',
    roles: ['technician'],
    airlineIds: [],
    question: 'Type Certificate vs STC — what are they?',
    difficulty: 4,
    goodAnswerPointsTr: ['TC = original aircraft certification (FAA/EASA)', 'STC = Supplemental Type Certificate (modifications)', 'STC sahibi her tür modify olabilir', 'Holder rights', 'Cert basis önemli'],
    redFlagsTr: ['STC bilmeme'],
    sampleAnswerTr: 'TC = Type Certificate, Boeing/Airbus için orijinal aircraft sertifikası. STC = Supplemental Type Certificate, üçüncü taraf modifikasyonu (örn Wi-Fi installation, IFE upgrade, winglet retrofit). STC holder approve eder, operator install eder. Cert basis (CFR Part 25, CS-25) zincirden bağımsız değil.',
    tipsTr: ['STC market knowledge', 'Modification approval flow'],
  },
  {
    id: 'qt_thy_te1',
    category: 'company_knowledge',
    roles: ['technician'],
    airlineIds: ['turkish_airlines'],
    question: 'What does Turkish Technic do for THY and other airlines?',
    difficulty: 3,
    goodAnswerPointsTr: ['THY MRO subsidiary', 'A320/B737/B777/A330/A350 capability', 'Engine shop', 'Component overhaul', '3rd party customer'],
    redFlagsTr: ['Bilmeme'],
    sampleAnswerTr: 'Turkish Technic = THY\'nın MRO (Maintenance Repair Overhaul) iştiraki. Sabiha Gökçen + İstanbul hangar facility. THY filo bakımı + 3rd party havayolları (Asia/Africa/MEA) için heavy maintenance, engine shop (CFM56, GE90), component overhaul. EASA Part-145 + FAA approved.',
    tipsTr: ['Türkiye MRO leader', 'TK Tech career path'],
  },
  {
    id: 'qt_thy_te2',
    category: 'company_knowledge',
    roles: ['technician'],
    airlineIds: ['turkish_airlines'],
    question: 'Why work at Turkish Technic instead of Lufthansa Technik or AFI KLM E&M?',
    difficulty: 3,
    goodAnswerPointsTr: ['Türkiye merkezli + uluslararası', 'Hızlı büyüme', 'Türk personel için language fit', 'Career path on-shore', '3rd party portföy büyümekte'],
    redFlagsTr: ['Sadece "Türk" deme'],
    sampleAnswerTr: 'Turkish Technic Türkiye\'de + global müşteri portföyü = on-shore çalışırken international exposure. Türk teknisyenler için language barrier yok ama İngilizce skill geliştirme fırsatı. THY group içinde long-term career path. Lufthansa Technik > Almanya based, AFI KLM > FR/NL based — relocation gerek.',
    tipsTr: ['Specific projects bil (B777 hold cargo mod)', 'TK Tech yatırım planları'],
  },
  {
    id: 'qt_lh_te1',
    category: 'company_knowledge',
    roles: ['technician'],
    airlineIds: [],
    question: 'What is Lufthansa Technik\'s base maintenance scope and where are their facilities?',
    difficulty: 3,
    goodAnswerPointsTr: ['Hamburg + Frankfurt main', 'Manila, Sofia, Malta', 'A320/A330/A340/A380 base', 'B747/B777 base', 'VIP completion'],
    redFlagsTr: ['Bilmeme'],
    sampleAnswerTr: 'Lufthansa Technik = global MRO leader. Hamburg ana hangar (B747/A380 D-check). Frankfurt hangar 6 (A330/A350). LTM Manila (A320/B737), Sofia/Malta. VIP/government completion (Bombardier Global, Boeing BBJ). Engine shop (CF6, GEnx, Trent), component (LRU repair).',
    tipsTr: ['LHT specific career programs', 'Engine vs airframe choice'],
  },
  {
    id: 'qt_te18',
    category: 'technical',
    roles: ['technician'],
    airlineIds: [],
    question: 'What is EASA Part-145 organization approval?',
    difficulty: 4,
    goodAnswerPointsTr: ['MRO yasal yetki belgesi', 'Approved scope (rating)', 'Quality system + manuals', 'Personnel licensing', 'Audit cycle 24 ay'],
    redFlagsTr: ['Part-145 bilmeme'],
    sampleAnswerTr: 'Part-145 = EASA regülasyonu MRO organizasyonu için. "Approved Maintenance Organization" (AMO) olmak için: 1) Quality system kurulu 2) Approved scope (rating: A1 large aircraft, B1 engine, C component) 3) Personnel licensing (CAT A/B1/B2/C) 4) Facilities + tools 5) Continuing airworthiness 6) Audit cycle 24 ay. Form 4 manager approval.',
    tipsTr: ['Part-145.A.30 personnel', 'Quality department fonksiyonu'],
  },
  {
    id: 'qt_te19',
    category: 'situational',
    roles: ['technician'],
    airlineIds: [],
    question: 'During a routine inspection, you find a minor discrepancy not in the work card. What do you do?',
    difficulty: 4,
    goodAnswerPointsTr: ['Doğru: yine de raporla', 'Tech log non-routine entry', 'AMM consult', 'In-limit ise temporary, out-of-limit AOG', 'Kayıt zinciri'],
    redFlagsTr: ['Görmezden gel', 'Sessiz tamir'],
    sampleAnswerTr: '"Out-of-scope" diye atlamam — safety culture\'da "if you see, you write" kural. Tech log non-routine entry. AMM consult — in-limit (örn küçük dent on non-critical structure): temporary record + monitor. Out-of-limit veya unsure: chief engineer + supervisor + delay if needed. Kayıt zinciri zorunlu.',
    tipsTr: ['Just culture', 'Documentation everything'],
  },
  {
    id: 'qt_te20',
    category: 'behavioral',
    roles: ['technician'],
    airlineIds: [],
    question: 'Tell me about a time you had a conflict with a colleague during night shift.',
    difficulty: 3,
    goodAnswerPointsTr: ['STAR formatı', 'Operasyon-odaklı çözüm', 'CRM kullanım', 'Documentation', 'Geri bildirim'],
    redFlagsTr: ['"Hiç yaşamadım"', 'Suçlama'],
    sampleAnswerTr: 'Situation: Gece vardiya, A320 brake change. Bir kolega torque sequence atladı, ben prosedüre göre redo iste. O direnci. Task: Quality risk önle. Action: Sakin "AMM ATA 32 prosedür şu, beraber bakalım" diyerek manuel açtım. Sequence yanlışını gösterdim. Result: Redo edildi. Sonra shift end\'de, sakin geri bildirim. İlişki bozulmadı, prosedür doğru.',
    tipsTr: ['STAR formatı', 'Just culture geri bildirim'],
  },
  {
    id: 'qt_te21',
    category: 'motivation',
    roles: ['technician'],
    airlineIds: [],
    question: 'Why do you want to be an aircraft maintenance technician?',
    difficulty: 2,
    goodAnswerPointsTr: ['Spesifik motivasyon', 'Hands-on engineering', 'Safety-critical role', 'Continuous learning', 'Long-term plan'],
    redFlagsTr: ['"Para iyi"', 'Genel cevap'],
    sampleAnswerTr: 'Çocukluğumdan beri mekanik problemleri çözmek tutkum. Lise teknik (uçak teknolojisi)\'de A320 sistemleri öğrenirken sertifikalı teknisyen olmak hedefim oldu. Aviation safety = zero-tolerance domain — bizim imzamız 200 yolcu hayatı. Plan: B1 lisans → type rating A320 → 5 yıl sonra senior B1 → 10 yıl mentor + Form 4 path.',
    tipsTr: ['Spesifik plan göster', 'Safety culture vurgu'],
  },
  {
    id: 'qt_te22',
    category: 'technical',
    roles: ['technician'],
    airlineIds: [],
    question: 'What is the difference between a B1 and B2 license?',
    difficulty: 3,
    goodAnswerPointsTr: ['B1 = mechanical (engine, gear, structure, hydraulic)', 'B2 = avionics (electrical, instruments, autoflight)', 'Both AMM compliance', 'Type rating ayrı'],
    redFlagsTr: ['Karıştır'],
    sampleAnswerTr: 'B1 = mechanical. Engine, landing gear, hydraulic, structure, fuel, pneumatic. B2 = avionics. Electrical, instruments, autoflight, comm/nav, FMS. CRS imzası kendi alan içinde. Modern uçaklarda B1+B2 dual license popüler — pratik flexibility. Her iki için type rating gerek (A320, B737, etc).',
    tipsTr: ['B1.1 (turbine) vs B1.2 (piston)', 'EASA Part-66'],
  },
  {
    id: 'qt_te23',
    category: 'technical',
    roles: ['technician'],
    airlineIds: [],
    question: 'How do you read and interpret a Wiring Diagram Manual (WDM)?',
    difficulty: 4,
    goodAnswerPointsTr: ['Block diagram + schematic + wire list', 'Signal flow trace', 'Equipment identification (Item Number)', 'Wire color/gauge code', 'Ground point labeling'],
    redFlagsTr: ['WDM bilmeme'],
    sampleAnswerTr: 'WDM = uçağın elektrik şeması. 4 ana bölüm: 1) Block diagram (sistem üst seviye) 2) Schematic (detaylı) 3) Wire list (PN, color, gauge, route) 4) Equipment list. Troubleshooting: signal flow trace, breaker position, connector pin identifikasyon. ATA 91 numara genellikle WDM index\'i.',
    tipsTr: ['Avionics troubleshooting beceri', 'Connector pin diagram'],
  },
  {
    id: 'qt_te24',
    category: 'technical',
    roles: ['technician'],
    airlineIds: [],
    question: 'What is the FOD prevention program in your maintenance facility?',
    difficulty: 3,
    goodAnswerPointsTr: ['Tool control (kalibre + count in/out)', 'FOD bag + container', 'FOD walks', 'Magnetic bar GSE', 'Personal item policy'],
    redFlagsTr: ['Sadece "dikkatli olurum"'],
    sampleAnswerTr: 'Tool control: shadow board + check-in/out, kalibre kayıtlı. FOD bag tüm work area + container. Daily FOD walks (apron + hangar). Magnetic bar tow tractor + GSE. Personal item (telefon, key, bayan saç tokası) policy: kayıt + sayım. Pre-flight inspection FOD focus.',
    tipsTr: ['FOD walk record', 'Tool calibration policy'],
  },
  {
    id: 'qt_te25',
    category: 'situational',
    roles: ['technician'],
    airlineIds: [],
    question: 'You discover a tool missing after the shift. What do you do?',
    difficulty: 5,
    goodAnswerPointsTr: ['DURDUR — uçak release engelle', 'Last work area inceleme', 'Engine + cargo bay + landing gear search', 'Supervisor immediately', 'Rapor + investigation', 'Tech log entry'],
    redFlagsTr: ['"Sonra bakarım"', 'Sessiz devam'],
    sampleAnswerTr: 'Tool missing = potansiyel FOD = potansiyel catastrophic. Hemen DURDUR — uçak release engelle. Last work area exhaustive search (engine, gear bay, cargo, panel). Supervisor + chief engineer immediately. Eğer tool bulunamazsa: AOG decision, X-ray scan, full disassembly review. Investigation report (tool control violation). Tech log entry zorunlu.',
    tipsTr: ['"FOD = catastrophic" mentality', 'Just culture rapor'],
  },
  {
    id: 'qt_te26',
    category: 'technical',
    roles: ['technician'],
    airlineIds: [],
    question: 'How does ESD (electrostatic discharge) damage avionics, and how do you prevent it?',
    difficulty: 4,
    goodAnswerPointsTr: ['Static charge → semiconductor damage', 'Wrist strap + grounded mat', 'ESD-safe packaging', 'Humidity control', 'Personnel training'],
    redFlagsTr: ['ESD bilmeme'],
    sampleAnswerTr: 'ESD = static charge transfer, modern avionics chip\'leri (CMOS, MOSFET) yakar — latent damage = sonra fail. Önleme: 1) Wrist strap (1 MΩ) ground 2) ESD mat workstation 3) ESD-safe bag (silver/pink) 4) Humidity 30-50% 5) Personnel training. ESD-sensitive label\'lı parçalar özel handling.',
    tipsTr: ['Avionics shop ESD policy', 'IPC J-STD-001'],
  },
  {
    id: 'qt_te27',
    category: 'technical',
    roles: ['technician'],
    airlineIds: [],
    question: 'What is fuel system contamination and how do you check for water?',
    difficulty: 4,
    goodAnswerPointsTr: ['Water = sediment in tank', 'Microbial growth (HUM-bug)', 'Sump drain check', 'Water-finding paste', 'Fuel sample lab analysis'],
    redFlagsTr: ['Water normal sayma'],
    sampleAnswerTr: 'Fuel contamination = water (condensation), particulates (rust, dirt), microbial (HUM-bug bacteria). Water tankın altına çöker, daily sump drain ile kontrol. Water-finding paste + clear container ile fark görülür (su tabaka kalın). Microbial growth: lab analysis + biocide treatment. Critical: fuel filter check.',
    tipsTr: ['Fuel quality manual', 'Microbiology HUM-bug'],
  },
  {
    id: 'qt_te28',
    category: 'technical',
    roles: ['technician'],
    airlineIds: [],
    question: 'Explain the function of the Auxiliary Power Unit (APU).',
    difficulty: 2,
    goodAnswerPointsTr: ['Tail-mounted small turbine', 'Main engine start için', 'Electric + bleed air ground', 'In-flight backup'],
    redFlagsTr: ['APU yer farketme'],
    sampleAnswerTr: 'APU = Auxiliary Power Unit, tail-mounted küçük turbine engine. Functions: 1) Main engine start (bleed air for starter) 2) Ground electric + bleed air (gate\'te AC pack çalıştır) 3) In-flight emergency backup (engine failure, electrical loss). APU run-up sound (turbine high-pitched whine).',
    tipsTr: ['Honeywell APS3200 / Pratt & Whitney APUs', 'APU MEL kategori'],
  },
  {
    id: 'qt_te29',
    category: 'technical',
    roles: ['technician'],
    airlineIds: [],
    question: 'What\'s a hard landing inspection and when is it required?',
    difficulty: 3,
    goodAnswerPointsTr: ['Pilot raporu + FDR data', 'g-load threshold (e.g. 1.7g+)', 'Landing gear visual + jack', 'Wing root + spar inspection', 'Document trail'],
    redFlagsTr: ['Pilot raporu görmezden'],
    sampleAnswerTr: 'Hard landing = vertical descent rate / g-load yüksek (genelde >1.7g threshold). Pilot raporu + FDR (Flight Data Recorder) verifikasyon. Inspection: landing gear strut visual + jack check (compression), wheel/tire, wing root (carry-through structure), spar bolts. AMM\'de "hard landing" inspection chapter (genelde ATA 05). In-limit: continue. Out: structural rework.',
    tipsTr: ['FDR readout işbirliği', 'Engineering team escalation'],
  },
  {
    id: 'qt_te30',
    category: 'motivation',
    roles: ['technician'],
    airlineIds: [],
    question: 'What\'s the biggest technical challenge you\'ve faced and how did you solve it?',
    difficulty: 4,
    goodAnswerPointsTr: ['STAR formatı', 'Real teknik detay', 'Teamwork', 'AMM/SRM use', 'Outcome'],
    redFlagsTr: ['Vague', '"Bir kez bir şey oldu"'],
    sampleAnswerTr: 'Situation: A320 ETOPS dispatch öncesi engine bleed leak rapor. Action: 30 dk turnaround içinde, AMM TSM ATA 36 + leak pinpoint. Eski seal değiştir + system pressure test. Documentation: tech log + non-routine card. Result: Dispatch 12 dk delay ile tamamlandı, ETOPS limits intact. Öğrendim: prep + manual access + team comm critical.',
    tipsTr: ['Real story bil', 'STAR + technical depth'],
  },
  {
    id: 'qt_te31',
    category: 'behavioral',
    roles: ['technician'],
    airlineIds: [],
    question: 'How do you stay current with new aircraft technologies and procedures?',
    difficulty: 3,
    goodAnswerPointsTr: ['SB/AD subscription takip', 'Type-specific training', 'OEM publication', 'Industry forum (Aviation Pros)', 'Recurrent training'],
    redFlagsTr: ['"Lazım olduğunda öğrenirim"'],
    sampleAnswerTr: 'OEM publication subscription (Boeing FOTC, Airbus AEO). EASA AD database weekly check. Internal recurrent training (ETOPS, RVSM, RNP). Industry: AviationProsTV, AINonline. Type-specific upgrade kursları (örn A320 → A320NEO delta). Peer-to-peer: experienced colleague mentorship. Annual review: license renewal.',
    tipsTr: ['Continuous learning showcase', 'Active subscription göster'],
  },
  {
    id: 'qt_te32',
    category: 'behavioral',
    roles: ['technician'],
    airlineIds: [],
    question: 'Are you comfortable with night shifts and on-call duties?',
    difficulty: 2,
    goodAnswerPointsTr: ['Realistic kabul', 'Schedule planning', 'Family balance', 'Health (sleep)', 'Long-term sustainability'],
    redFlagsTr: ['"Sevmem"', 'Aşırı esnek görün'],
    sampleAnswerTr: 'Aviation maintenance = 24/7 operation, night shift + on-call doğal parça. Önceki rolümde 3 yıl rotational shift (gece/gündüz) yaptım. Schedule planning: blackout curtains, regular meal, exercise routine. On-call: hazırlık çantası, telefon erişilebilir. Long-term sustainability için: sufficient rest between shifts.',
    tipsTr: ['Sürdürülebilirlik vurgu', 'Health awareness göster'],
  },
  {
    id: 'qt_te33',
    category: 'behavioral',
    roles: ['technician'],
    airlineIds: [],
    question: 'How do you handle pressure during AOG (Aircraft On Ground) situations?',
    difficulty: 4,
    goodAnswerPointsTr: ['Sakin + metodolojik', 'Priority communication', 'Resource management', 'Documentation despite pressure', 'Team coordination'],
    redFlagsTr: ['Panik admit', 'Kestirim karar'],
    sampleAnswerTr: 'AOG = costly + stressful ama metodoloji aynı. 1) Quick assessment + AMM TSM 2) Resource check (parts, tooling, manpower) 3) Comms (chief eng + ops + customer) 4) Action plan + ETA realistic 5) Execute step-by-step + document. Pressure altında shortcut yok — yanlış karar = bigger AOG.',
    tipsTr: ['Calm under pressure göster', 'Resource awareness'],
  },
  {
    id: 'qt_te34',
    category: 'company_knowledge',
    roles: ['technician'],
    airlineIds: [],
    question: 'What aircraft types are you type-rated on, and which would you like to add?',
    difficulty: 2,
    goodAnswerPointsTr: ['Net liste', 'Logical progression', 'Future plan', 'Industry trend awareness'],
    redFlagsTr: ['Karışık liste', 'Bilmeme'],
    sampleAnswerTr: 'Şu an A320 family (CEO + NEO) B1 type-rated. Geçmişte A330 sahaja deneyim. Eklemek istediğim: A350 (composite + IMA platform öğrenme) + B777 (long-haul ETOPS). Industry trend: A321XLR + 787 NG yaygınlaşıyor — kariyer planı bunlara doğru.',
    tipsTr: ['Realistic progression', 'Industry awareness'],
  },
  {
    id: 'qt_te35',
    category: 'situational',
    roles: ['technician'],
    airlineIds: [],
    question: 'A captain refuses to accept your aircraft release. What do you do?',
    difficulty: 5,
    goodAnswerPointsTr: ['Captain authority kabul', 'Spesifik soru: hangi item?', 'AMM/MEL referans göster', 'Common ground arama', 'Eskaler if needed'],
    redFlagsTr: ['Tartış', '"Imzalattım = kapanır"'],
    sampleAnswerTr: 'Captain final authority on aircraft acceptance — bu hak. Saygılı sorum: "Hangi item için endişeli?" Spesifik teknik konu: AMM + MEL + tech log birlikte aç, gösterelim. Eğer captain hâlâ kabul etmezse: chief eng + duty manager involve. Bazen captain risk perception haklı (örn weather + minor MEL kombinasyonu), bazen technical detayı bilmiyor. Profesyonel comm + kayıt.',
    tipsTr: ['CRM in maintenance', 'Captain authority respect'],
  },
  {
    id: 'qt_te36',
    category: 'technical',
    roles: ['technician'],
    airlineIds: [],
    question: 'What is the function of a CVR (Cockpit Voice Recorder) and FDR (Flight Data Recorder)?',
    difficulty: 3,
    goodAnswerPointsTr: ['CVR = audio cockpit (2 hr)', 'FDR = flight parameters (25 hr+)', 'Underwater Locator Beacon', 'Crash investigation', 'Maintenance test interval'],
    redFlagsTr: ['Karıştır'],
    sampleAnswerTr: 'CVR = Cockpit Voice Recorder, son 2 saat audio (4 channel: pilot 1, pilot 2, ambient, radio). FDR = Flight Data Recorder, 25+ saat parametre (88+ value: speed, altitude, control surface, engine). Both crash-survivable casing, ULB (Underwater Locator Beacon) 30 günü. Maintenance: 2 yıllık readout + functional test.',
    tipsTr: ['ATA 31 inst recording', 'Black box renk turuncu'],
  },
  {
    id: 'qt_te37',
    category: 'company_knowledge',
    roles: ['technician'],
    airlineIds: ['turkish_airlines'],
    question: 'What aircraft models does Turkish Airlines operate, and what maintenance challenges do they pose?',
    difficulty: 3,
    goodAnswerPointsTr: ['B737/A320/A321/A330/A350/B777/B787', 'Hub maintenance Sabiha + IST', 'Mixed fleet challenges', 'Type rating combo'],
    redFlagsTr: ['Filo bilmeme'],
    sampleAnswerTr: 'THY filo: A320 family (NEO + CEO ~150), A321NEO/XLR, A330ceo, A350-900 (~14), B737NG/MAX, B777-300ER, B787-9. Mixed fleet: short-haul (A320/B737) hub turnaround hız, long-haul (777/787/A350) ETOPS + maintenance window. Sabiha + Yeşilköy hangar. Challenge: 7+ type rating combo, parts inventory büyük, vendor support ağı.',
    tipsTr: ['Filo composition bil', 'Strategic fleet plan'],
  },

  // ═══════════════════════════════════════════════════
  //  YER HİZMETLERİ +30 (qg_te7 → qg_te36)
  // ═══════════════════════════════════════════════════

  {
    id: 'qg_te7',
    category: 'technical',
    roles: ['ground'],
    airlineIds: [],
    question: 'What is IGOM and why is it important?',
    difficulty: 3,
    goodAnswerPointsTr: ['IATA Ground Operations Manual', 'Standard procedures global', 'Safety + efficiency', 'Training reference', 'Audit baseline'],
    redFlagsTr: ['IGOM bilmeme'],
    sampleAnswerTr: 'IGOM = IATA Ground Operations Manual. Global standardize ramp procedures (loading, pushback, refueling, deicing, etc). 200+ havayolu adopt. Safety + efficiency baseline. Eğitim referansı, ISAGO audit kullanır. New revision yıllık. Ground ops için "bible".',
    tipsTr: ['IGOM chapter index bil', 'IATA training certificate'],
  },
  {
    id: 'qg_te8',
    category: 'technical',
    roles: ['ground'],
    airlineIds: [],
    question: 'What\'s the difference between AHM and IGOM?',
    difficulty: 4,
    goodAnswerPointsTr: ['AHM = IATA Airport Handling Manual (broader)', 'IGOM = subset focused on ramp ops', 'AHM commercial + technical', 'IGOM operational tactical'],
    redFlagsTr: ['Karıştır'],
    sampleAnswerTr: 'AHM = Airport Handling Manual, broader scope: commercial + technical + admin (cargo, passenger handling, baggage). IGOM = subset focused on ramp/turnaround ops, tactical procedures. AHM reference + standardize commercial agreements (SGHA — Standard Ground Handling Agreement). IGOM = "how to do" practical guide.',
    tipsTr: ['SGHA contract bil', 'AHM 590 GSE'],
  },
  {
    id: 'qg_te9',
    category: 'technical',
    roles: ['ground'],
    airlineIds: [],
    question: 'How is a loadsheet calculated and why is it critical?',
    difficulty: 4,
    goodAnswerPointsTr: ['Pax + bag + cargo + fuel weight', 'CG (center of gravity) zarf', 'MZFW + MTOW limits', 'Captain final accept', 'Weight & balance affect'],
    redFlagsTr: ['Loadsheet bilmeme'],
    sampleAnswerTr: 'Loadsheet = uçağın final ağırlık ve denge dokümantasyonu. Hesap: DOW (Dry Operating Weight) + Pax (avg weight × #) + Bag + Cargo + Fuel = TOW. CG (center of gravity) check — limit zarf içinde olmalı. MZFW (max zero fuel weight) + MTOW (max takeoff weight) limit. Final captain imzalar — yanlış W&B = takeoff abort, stall risk.',
    tipsTr: ['IATA AHM 510 W&B', 'Captain accept zorunlu'],
  },
  {
    id: 'qg_te10',
    category: 'technical',
    roles: ['ground'],
    airlineIds: [],
    question: 'What does CG (center of gravity) mean and why does it matter?',
    difficulty: 3,
    goodAnswerPointsTr: ['Uçağın denge noktası', 'Forward / aft limit', '%MAC (Mean Aerodynamic Chord)', 'Fuel burn değişir', 'Pitch stability + control'],
    redFlagsTr: ['CG bilmeme'],
    sampleAnswerTr: 'CG = Center of Gravity, uçağın ağırlık dengesi noktası. %MAC ile expressed (Mean Aerodynamic Chord). Forward limit + aft limit zarfı içinde olmalı. CG forward → trim issue, fuel burn yüksek. CG aft → instability, stall risk. Loading sequence (cargo position, pax distribution) CG\'yi etkiler. Fuel burn flight içinde CG kayar.',
    tipsTr: ['Trim sheet', 'Loading priorities'],
  },
  {
    id: 'qg_te11',
    category: 'technical',
    roles: ['ground'],
    airlineIds: [],
    question: 'What are the IATA dangerous goods classes?',
    difficulty: 4,
    goodAnswerPointsTr: ['9 class', '1: Explosives', '2: Gases', '3: Flammable liquid', '4: Flammable solid', '5: Oxidizer', '6: Toxic', '7: Radioactive', '8: Corrosive', '9: Misc'],
    redFlagsTr: ['Class sayma'],
    sampleAnswerTr: '9 class IATA DGR (Dangerous Goods Regulations): 1) Explosives (fireworks) 2) Gases (oxygen, butane) 3) Flammable liquid (alcohol, fuel) 4) Flammable solid 5) Oxidizing substance + organic peroxide 6) Toxic + infectious 7) Radioactive 8) Corrosive 9) Miscellaneous (lithium battery, dry ice). Each\'in özel packaging + label + manifesto + cargo plan zorunlu.',
    tipsTr: ['IATA DGR yıllık update', 'Cat 1/2/3 staff certification'],
  },
  {
    id: 'qg_te12',
    category: 'technical',
    roles: ['ground'],
    airlineIds: [],
    question: 'How do you handle live animal shipments (AVI)?',
    difficulty: 4,
    goodAnswerPointsTr: ['IATA LAR compliance', 'Specific container CR', 'Climate control cargo', 'Acceptance + handling priority', 'Stress monitoring'],
    redFlagsTr: ['Standard cargo gibi handle'],
    sampleAnswerTr: 'AVI = Animal in Cargo. IATA LAR (Live Animals Regulations) compliance. Specific Container Requirement (örn dog: ventilation, water, secure). Climate control: temperature 5-25°C cargo hold. Acceptance: vet certificate, owner declaration, container check. Handling priority — last loaded, first unloaded. Stress signs check.',
    tipsTr: ['IATA LAR özel sertifika', 'Dog/cat species spec'],
  },
  {
    id: 'qg_te13',
    category: 'situational',
    roles: ['ground'],
    airlineIds: [],
    question: 'A passenger\'s checked bag is missing on arrival. What do you do?',
    difficulty: 3,
    goodAnswerPointsTr: ['Empati önce', 'WorldTracer entry (PIR)', 'Bag tag info collect', 'Tracking promise', 'Compensation policy', 'Forward when found'],
    redFlagsTr: ['"Sorumlu değiliz"', 'Suçlama'],
    sampleAnswerTr: '"Çok özür diliyorum, hemen yardımcı olayım." WorldTracer system\'de PIR (Property Irregularity Report) aç, bag tag info input. Tracking number ver. Travel essentials için emergency kit (toiletries voucher) sun. 24 saat içinde update promise. Bag bulunduğunda: home delivery. Compensation: havayolu policy bağlı (genelde $50-100/gün limit).',
    tipsTr: ['WorldTracer kullanım', 'EU 261 baggage rules'],
  },
  {
    id: 'qg_te14',
    category: 'situational',
    roles: ['ground'],
    airlineIds: [],
    question: 'You have an Unaccompanied Minor (UM) with a missed connection. What do you do?',
    difficulty: 5,
    goodAnswerPointsTr: ['Child safety priority', 'UM dedicated staff escort', 'Rebooking next flight', 'Parents communication', 'Comfort + meal voucher', 'Document chain'],
    redFlagsTr: ['Yalnız bırak', 'Standard pax handle'],
    sampleAnswerTr: 'UM safety = absolute priority. Dedicated UM staff escort 1-on-1. Rebooking next available flight + UM service confirmed. Parents call (departure airport + arrival airport). Comfort: meal voucher, kid-friendly area, supervised waiting. Document chain: UM packet (passport, parents contact, medical info) sıkı tut. Handover destination dedicated staff + ID verification.',
    tipsTr: ['UM age limits 5-11', 'Yearly UM training'],
  },
  {
    id: 'qg_te15',
    category: 'technical',
    roles: ['ground'],
    airlineIds: [],
    question: 'What does WCHR stand for and how do you handle it?',
    difficulty: 3,
    goodAnswerPointsTr: ['Wheelchair Request (Ramp)', 'WCHR vs WCHS vs WCHC', 'Pre-board priority', 'Aisle chair use', 'Stowage'],
    redFlagsTr: ['WCHR bilmeme'],
    sampleAnswerTr: 'WCHR = Wheelchair Ramp, kategorili: WCHR (long distance, kendi kendi), WCHS (steps issue), WCHC (totally immobile, aisle chair). Pre-board priority. Aisle chair (narrow uçak içinde) ile seat\'a transfer. Wheelchair gate-checked + tag (return to gate). PRM (Persons with Reduced Mobility) sertifika gerek staff.',
    tipsTr: ['EU 1107/2006 PRM rights', 'Dignity-first handling'],
  },
  {
    id: 'qg_te16',
    category: 'technical',
    roles: ['ground'],
    airlineIds: [],
    question: 'What is PETC and how do you handle pet-in-cabin requests?',
    difficulty: 3,
    goodAnswerPointsTr: ['Pet in Cabin', 'Container size + weight limits', 'Documentation (vet)', 'Allergy considerations', 'Booking priority'],
    redFlagsTr: ['Standard cargo'],
    sampleAnswerTr: 'PETC = Pet in Cabin (small dog/cat, container under seat). Container size + weight limits airline policy (genelde <8kg, 40x30x25cm). Vet documentation 10 gün önce + microchip + vaccine record. Country entry rules (USDA, EU, etc). Allergy considerations: maks 2 PETC per flight, separate seating. Booking priority — limited capacity.',
    tipsTr: ['Avianca/JetBlue policy bil', 'BREEDS restrictions'],
  },
  {
    id: 'qg_te17',
    category: 'situational',
    roles: ['ground'],
    airlineIds: [],
    question: 'A group of 50 passengers is checking in 30 min before departure. How do you handle it?',
    difficulty: 4,
    goodAnswerPointsTr: ['Group check-in priority queue', 'Multiple desk allocation', 'Pre-printed boarding passes', 'Bag tag + count', 'Group leader communication'],
    redFlagsTr: ['"Sorun yok"', 'Standard handle'],
    sampleAnswerTr: 'Hızlı + organize: 1) Group check-in priority queue (varsa) 2) 2-3 desk allocation simultaneously 3) Group leader → manifesto + ID list al 4) Pre-printed boarding pass batch (PNR\'dan) 5) Bag tag rapid + count 6) Boarding announcement priority. Risk: gate close + delay. Threshold (örn 20 min) altında split group / next flight.',
    tipsTr: ['IATA group handling', 'Flexibility + speed'],
  },
  {
    id: 'qg_thy_te1',
    category: 'company_knowledge',
    roles: ['ground'],
    airlineIds: ['turkish_airlines'],
    question: 'How is Turkish Airlines Ground Handling structured at IST?',
    difficulty: 3,
    goodAnswerPointsTr: ['THY HG (Hizmet Grubu)', 'Çelebi competition same hub', 'Multiple terminals', 'Multi-shift 24/7', 'Cargo + pax separate'],
    redFlagsTr: ['Bilmeme'],
    sampleAnswerTr: `THY Ground = THY Hizmet Grubu (HG). IST hub'da Çelebi ile competition aynı yer. Pax handling + cargo + ramp + fuel coordination. Multiple terminal coverage (T1 international, T2 domestic). 24/7 multi-shift. THY-specific: Star Alliance hub coordination.`,
    tipsTr: ['THY HG vs HavaIST', 'Career path advancement'],
  },
  {
    id: 'qg_thy_te2',
    category: 'company_knowledge',
    roles: ['ground'],
    airlineIds: ['turkish_airlines'],
    question: 'Why work at THY Ground instead of Çelebi or Havaş?',
    difficulty: 3,
    goodAnswerPointsTr: ['THY airline kültürü', 'Star Alliance exposure', 'Career progression THY group', 'Long-term stability'],
    redFlagsTr: ['Sadece "Türk"'],
    sampleAnswerTr: 'THY Ground = THY group içinde, airline kültürü direkt. Star Alliance hub exposure (UA, LH, Air Canada coordination). Long-term THY group career path. Çelebi + Havaş 3rd party — multiple airline contracts, ama dahili career ladder farklı. THY salary/benefits genelde 3rd party\'den iyi.',
    tipsTr: ['Specific perks bil', 'Internal mobility'],
  },
  {
    id: 'qg_te18',
    category: 'company_knowledge',
    roles: ['ground'],
    airlineIds: [],
    question: 'What does Çelebi Aviation do and at which airports?',
    difficulty: 3,
    goodAnswerPointsTr: ['Türkiye + India + Hungary', 'Multiple airline 3rd party', 'Pax + ramp + cargo + fuel', 'IATA ISAGO certified', '40+ stations'],
    redFlagsTr: ['Bilmeme'],
    sampleAnswerTr: 'Çelebi Aviation = Türkiye HQ, ground handling 3rd party global. 40+ station: Türkiye (IST, SAW, ESB, ADB), India (DEL, BLR), Hungary (BUD), Turkey + Asia + Europe. Pax handling + ramp + cargo + fuel. 3rd party multiple airlines. IATA ISAGO certified.',
    tipsTr: ['Çelebi expansion plans', 'India operation special'],
  },
  {
    id: 'qg_te19',
    category: 'situational',
    roles: ['ground'],
    airlineIds: [],
    question: 'A passenger refuses to follow safety instructions during deplaning. What do you do?',
    difficulty: 3,
    goodAnswerPointsTr: ['Sakin + assertive', 'Safety reason explain', 'Authority escalation', 'Other passengers protect', 'Document'],
    redFlagsTr: ['Tartışmaya gir'],
    sampleAnswerTr: 'Sakin + nazik: "Hanımefendi/Beyefendi, güvenliğiniz için ramp\'ta yürürken çizgileri takip etmemiz gerek." Reason explain (ramp = motor + GSE traffic = ölümcül). Eğer direnci sürerse: marshaller + supervisor call. Other passengers protect — diğerlerini güvenli bölgeye yönlendir. Documentation: incident report.',
    tipsTr: ['Ramp safety zero-tolerance', 'De-escalation skill'],
  },
  {
    id: 'qg_te20',
    category: 'technical',
    roles: ['ground'],
    airlineIds: [],
    question: 'What is the standard turnaround time and what activities happen during it?',
    difficulty: 4,
    goodAnswerPointsTr: ['Short-haul 25-45 min', 'Long-haul 60-90 min', 'Deplane → cleaning → catering → fuel → load → boarding', 'Parallel operations', 'Bottleneck analysis'],
    redFlagsTr: ['Sequence yanlış'],
    sampleAnswerTr: 'Short-haul (A320): 25-45 dk. Long-haul (777): 60-90 dk + heavy clean. Sequence: 1) Deplane (10-15 min) 2) Cleaning + catering (paralel 15 min) 3) Fuel (15-30 min depending volume) 4) Bag/cargo unload + load (paralel) 5) Boarding (15-20 min) 6) Pushback prep. Bottleneck genelde fuel + cleaning. LCC (Pegasus, Ryanair) 25 min target.',
    tipsTr: ['Critical path management', 'GSE coordination'],
  },
  {
    id: 'qg_te21',
    category: 'technical',
    roles: ['ground'],
    airlineIds: [],
    question: 'What is ISAGO and how does it audit ground operations?',
    difficulty: 4,
    goodAnswerPointsTr: ['IATA Safety Audit Ground Operations', '2 yıllık cycle', 'Document review + ramp observation', 'Findings → corrective action', 'Standardization'],
    redFlagsTr: ['ISAGO bilmeme'],
    sampleAnswerTr: 'ISAGO = IATA Safety Audit for Ground Operations. 2 yıllık audit cycle. 2 stage: 1) Document review (manuals, training records) 2) On-site ramp observation (procedures execution). Findings: "Major" → 30-day corrective, "Minor" → next audit. Pass = ISAGO certified, customer airline trust. ICAO Annex 19 SMS framework.',
    tipsTr: ['ISAGO standards bil', 'Audit prep checklist'],
  },
  {
    id: 'qg_te22',
    category: 'technical',
    roles: ['ground'],
    airlineIds: [],
    question: 'Explain the standard hand signals for marshalling an aircraft to the gate.',
    difficulty: 3,
    goodAnswerPointsTr: ['Wand visible day/night', 'Continue forward (one wand sweep)', 'Stop (crossed wands)', 'Turn (one wand horizontal)', 'Engine cut'],
    redFlagsTr: ['El bilmeme'],
    sampleAnswerTr: 'Marshalling: 1) "Continue forward" = bir wand straight up + diğer arms motion forward 2) "Turn left/right" = inside arm horizontal extend 3) "STOP" = wands crossed in X 4) "Cut engines" = wand throat-cutting motion 5) "Chocks in" = wands point chock area 6) "Brakes set" = thumbs up. Visibility critical: day reflective, night light.',
    tipsTr: ['ICAO Annex 2 hand signals', 'Practice in simulator'],
  },
  {
    id: 'qg_te23',
    category: 'technical',
    roles: ['ground'],
    airlineIds: [],
    question: 'What is de-icing fluid Type I/II/III/IV and when do you use each?',
    difficulty: 4,
    goodAnswerPointsTr: ['Type I = orange, immediate clean (60% glycol)', 'Type II = thicker, hold time short', 'Type III = light aircraft', 'Type IV = green, longest hold time', 'Holdover Time chart'],
    redFlagsTr: ['Type bilmeme'],
    sampleAnswerTr: 'Type I = orange/red, %60 glycol + water, immediate cleaning ice/snow + minimal hold. Type II = thicker (yellow), hold time 30-60 min in light snow. Type III = light aircraft (75 kt+ rotation). Type IV = green, longest hold (60+ min in moderate snow). Holdover Time chart\'a göre weather + Type seçilir. Application: Step 1 (Type I de-ice) + Step 2 (Type II/IV anti-ice).',
    tipsTr: ['Holdover Time chart bil', 'Glycol environmental'],
  },
  {
    id: 'qg_te24',
    category: 'situational',
    roles: ['ground'],
    airlineIds: [],
    question: 'A flight is overbooked by 3 passengers. How do you handle this?',
    difficulty: 4,
    goodAnswerPointsTr: ['Voluntary first (compensation offer)', 'Tier-based eligibility (frequent flyer)', 'Involuntary criteria last', 'EU 261/US DOT compensation', 'Documentation'],
    redFlagsTr: ['"Random pick"', 'Aggressive tone'],
    sampleAnswerTr: 'Önce voluntary call: "Sonraki uçuşa geçmek isteyen 3 yolcu için $XXX voucher + hotel." Genelde yeterli sayı çıkar. Yetersiz: tier-based (frequent flyer status, fare class) involuntary denied boarding. Compensation EU 261 ($250-600) veya US DOT 4x ticket. Documentation: rebook confirmation, compensation voucher, complaint form.',
    tipsTr: ['EU 261 reg detayı bil', 'De-escalation comm'],
  },
  {
    id: 'qg_te25',
    category: 'technical',
    roles: ['ground'],
    airlineIds: [],
    question: 'Why is connecting baggage handling different from origin-destination baggage?',
    difficulty: 3,
    goodAnswerPointsTr: ['Tight transfer time', 'Aircraft hold position', 'IATA Baggage Identification Number (BIN)', 'BSM transfer data', 'Recovery if missed'],
    redFlagsTr: ['Aynı sayma'],
    sampleAnswerTr: 'Connecting bag = origin → hub → final destination. Tight transfer time (örn 45 min). BIN (Baggage Identification Number) ile track. BSM (Baggage Source Message) data exchange between airlines. Aircraft hold position (forward vs aft) hızlı unload + reload için. Missed → WorldTracer + forward to next available flight + customer notify.',
    tipsTr: ['Baggage system database', 'IATA Resolution 753'],
  },
  {
    id: 'qg_te26',
    category: 'behavioral',
    roles: ['ground'],
    airlineIds: [],
    question: 'How do you stay motivated during long shifts in extreme weather conditions?',
    difficulty: 3,
    goodAnswerPointsTr: ['Mental resilience', 'Team support', 'Equipment correctly use', 'Break management', 'Mission focus (passenger service)'],
    redFlagsTr: ['"Zor" admit', 'Aşırı'],
    sampleAnswerTr: 'Ramp work all weather — yağmur, kar, sıcak, soğuk. Mental: "200 yolcu eve gitmek istiyor, biz aracı olalım" mission focus. Team: peer support kritik (kahve molası, joke break). Equipment: layered clothing, waterproof boots, hand warmers, sunscreen yaz. Break management: regular hydration, micro-breaks, crew room reset. Long-term: physical fitness routine.',
    tipsTr: ['Resilience showcase', 'Team-first mentality'],
  },
  {
    id: 'qg_te27',
    category: 'motivation',
    roles: ['ground'],
    airlineIds: [],
    question: 'Why ground operations instead of cabin crew or pilot?',
    difficulty: 2,
    goodAnswerPointsTr: ['Operasyon arkasını görmek istek', 'Hands-on tactical work', 'Team coordination', 'Behind-the-scenes critical role', 'Career path stability'],
    redFlagsTr: ['"Pilot olamadım"'],
    sampleAnswerTr: 'Cabin crew + pilot uçuş içinde. Ground = uçuş öncesi/sonrası tactical operations. Hands-on: GSE, pushback, marshalling, baggage. Team coordination 5-10 kişi simultaneous. Behind-the-scenes ama uçağın güvenli + zamanında kalkması bizim. Long-term career: ramp → supervisor → operations manager → station manager path.',
    tipsTr: ['Specific role passion', 'Career growth plan'],
  },
  {
    id: 'qg_te28',
    category: 'situational',
    roles: ['ground'],
    airlineIds: [],
    question: 'During pushback, you notice the towbar shear pin has not engaged correctly. Action?',
    difficulty: 5,
    goodAnswerPointsTr: ['STOP pushback hemen', 'Tractor + aircraft separate immediately', 'Shear pin replace', 'Hand signal to cockpit', 'Documentation'],
    redFlagsTr: ['Devam et', 'Görmezden'],
    sampleAnswerTr: 'STOP pushback hemen — shear pin = tractor + aircraft koruma sistem. Engaged değilse force transfer kontrolsüz, nose gear damage riski. Hand signal "STOP" wing/nose. Comms: cockpit + tow operator. Tractor disengage (chock first). New shear pin install (correct PN). Re-engagement check. Pushback resume safe state\'de. Doc: incident card.',
    tipsTr: ['Towbar safety pin function', 'Pushback SOP knowledge'],
  },
  {
    id: 'qg_te29',
    category: 'company_knowledge',
    roles: ['ground'],
    airlineIds: [],
    question: 'What\'s the difference between SunExpress, Pegasus, and Anadolujet ground operations?',
    difficulty: 3,
    goodAnswerPointsTr: ['SunExpress = THY/Lufthansa JV (charter heavy)', 'Pegasus = LCC (fast turnaround)', 'Anadolujet = THY low-cost branch'],
    redFlagsTr: ['Bilmeme'],
    sampleAnswerTr: 'SunExpress = THY + Lufthansa JV, charter + leisure focus, AYT/DLM hub. Pegasus = independent LCC, SAW hub, A320 family fleet, fast 25-30 min turnaround. Anadolujet = THY low-cost subsidiary, ESB hub. Ground ops: SunExpress sezon ağırlık, Pegasus volume hız, AnadoluJet THY infra share.',
    tipsTr: ['LCC vs FSC ground ops fark', 'Hub strategy'],
  },
  {
    id: 'qg_te30',
    category: 'technical',
    roles: ['ground'],
    airlineIds: [],
    question: 'What is GPU vs PCA and when do you use each?',
    difficulty: 3,
    goodAnswerPointsTr: ['GPU = Ground Power Unit (electric)', 'PCA = Pre-Conditioned Air (climate)', 'APU yerine yer eko', 'Concurrent use turnaround', 'Eco-GSE'],
    redFlagsTr: ['Karıştır'],
    sampleAnswerTr: 'GPU = Ground Power Unit, 115V 400Hz AC + 28V DC sağlar (APU yerine). PCA = Pre-Conditioned Air, conditioned air (heat/cool) cabin\'a (APU AC pack yerine). Concurrent kullanım: turnaround sırasında APU off, GPU + PCA gate-mounted veya mobile. Eco benefit: jet fuel save + emisyon. Modern airports built-in jet bridge GPU + PCA.',
    tipsTr: ['Eco-GSE trend', 'Connection sequence'],
  },
  {
    id: 'qg_te31',
    category: 'situational',
    roles: ['ground'],
    airlineIds: [],
    question: 'Bird strike confirmed by departing aircraft. They want to return for inspection. What do you coordinate?',
    difficulty: 4,
    goodAnswerPointsTr: ['Emergency vehicle standby', 'Maintenance team alert', 'Gate available', 'Pax handling (potential delay)', 'Documentation', 'Wildlife report'],
    redFlagsTr: ['Standard handle'],
    sampleAnswerTr: 'Coordination: 1) ATC + tower confirm landing slot 2) Emergency vehicle standby (RFFS) — bird strike sometimes engine fire 3) Maintenance team alert engine inspection 4) Gate available + GPU 5) Pax: safe deplane + delay communication 6) Documentation: tech log + airport bird strike report (FAA wildlife strike database). Engineering decision: continue / AOG.',
    tipsTr: ['Bird strike coordination', 'Wildlife management airport'],
  },
  {
    id: 'qg_te32',
    category: 'company_knowledge',
    roles: ['ground'],
    airlineIds: ['turkish_airlines'],
    question: 'What is THY\'s slot strategy at IST and how does ground handling support it?',
    difficulty: 4,
    goodAnswerPointsTr: ['IST hub Star Alliance', 'Wave structure (banks)', 'Tight connection MCT', 'Turnaround target <60 min', 'Bag connect priority'],
    redFlagsTr: ['Slot bilmeme'],
    sampleAnswerTr: 'THY IST hub = Star Alliance major. Slot strategy: wave structure (banks) — multiple flights arrive/depart aynı window. MCT (Min Connection Time) ~45 dk international. Ground handling support: turnaround target <60 min, bag connect priority (forward hold), pax fast track, gate change minimum. THY HG dedicated turnaround crew.',
    tipsTr: ['Hub-and-spoke model', 'Wave coordination'],
  },
  {
    id: 'qg_te33',
    category: 'technical',
    roles: ['ground'],
    airlineIds: [],
    question: 'What is a NOTOC and when is it required?',
    difficulty: 4,
    goodAnswerPointsTr: ['Notification To Captain', 'Dangerous goods cargo', 'Special cargo info', 'Pre-flight briefing', 'Captain accept'],
    redFlagsTr: ['NOTOC bilmeme'],
    sampleAnswerTr: 'NOTOC = Notification To Captain (Special Load Notification). Required when cargo includes: dangerous goods, live animals, perishables, valuable cargo, weapons, human remains. Cargo agent prepares + ramp sup verifies. Pre-flight briefing captain — class, quantity, location in hold, emergency response. Captain accepts → loadsheet sign.',
    tipsTr: ['IATA AHM 540 NOTOC', 'Captain authority'],
  },
  {
    id: 'qg_te34',
    category: 'situational',
    roles: ['ground'],
    airlineIds: [],
    question: 'Smoke is reported from cargo hold during loading. Action?',
    difficulty: 5,
    goodAnswerPointsTr: ['STOP loading immediately', 'Evacuate ramp area', 'RFFS notify', 'Investigate source', 'AAIB if confirmed'],
    redFlagsTr: ['Devam et', 'Sessiz'],
    sampleAnswerTr: 'STOP loading hemen + evacuate ramp area. RFFS (Rescue & Fire Fighting Services) notify immediate. Aircraft cargo doors open + smoke source identify. Common: lithium battery fire, fuel spill, electrical short. Fire extinguisher class D (metal fire) ready. Investigation: cargo manifesto check, last item review. If serious: AAIB report, NTSB notify.',
    tipsTr: ['Lithium battery hazard', 'Cargo fire protocols'],
  },
  {
    id: 'qg_te35',
    category: 'behavioral',
    roles: ['ground'],
    airlineIds: [],
    question: 'How do you maintain accuracy in fast-paced check-in operations?',
    difficulty: 3,
    goodAnswerPointsTr: ['Standard process discipline', 'Checklist mental', 'Document verification triple', 'PNR + APIS sync', 'Calm under pressure'],
    redFlagsTr: ['"Hızlı"', 'Aşırı"'],
    sampleAnswerTr: 'Hız + accuracy denge — accuracy non-negotiable. Standard process: 1) PNR open 2) ID match (passport name = booking name) 3) Document verify (visa, ESTA, ETIAS) 4) Bag tag + count 5) Boarding pass print + verify gate/seat. Mental checklist sıralı tutmak — atlama olmaz. Triple-check: passport, ticket, system. Calm tone bile rush\'ta — empathetic communication.',
    tipsTr: ['APIS regulations', 'Document fraud awareness'],
  },
  {
    id: 'qg_te36',
    category: 'motivation',
    roles: ['ground'],
    airlineIds: [],
    question: 'Where do you see yourself in 5 years in airport operations?',
    difficulty: 2,
    goodAnswerPointsTr: ['Realistic progression', 'Specific goals (supervisor, ops manager)', 'Skill development plan', 'Long-term commitment'],
    redFlagsTr: ['Vague', 'Unrealistic ("Pilot olacağım")'],
    sampleAnswerTr: '5 yıl: Ramp agent → Senior agent (year 2) → Shift supervisor (year 3-4) → Operations duty manager (year 5). Skill plan: IATA DGR cat 1 cert (year 1), AHM safety lead (year 2), CMA training (year 3). Long-term: station manager 10 yıl. Bu havayoluyla long-term commit.',
    tipsTr: ['Realistic ladder', 'Specific certifications'],
  },

  // ═══════════════════════════════════════════════════
  //  ÖĞRENCİ +30 (qs_t4 → qs_x33)
  // ═══════════════════════════════════════════════════

  {
    id: 'qs_t4',
    category: 'technical',
    roles: ['student'],
    airlineIds: [],
    question: 'What is PPL and what does the training cover?',
    difficulty: 2,
    goodAnswerPointsTr: ['Private Pilot License', '~45 saat min', 'Single-engine VFR', 'Solo cross-country', 'Theory exams 9'],
    redFlagsTr: ['PPL bilmeme'],
    sampleAnswerTr: 'PPL = Private Pilot License, single-engine + VFR (Visual Flight Rules). EASA Part-FCL 45 saat minimum (genelde 60-80). Theory: 9 sınav (Air Law, Met, Nav, etc). Pratik: solo 10 saat + cross-country 5 saat dahil. PPL\'lien profesyonel uçamazsın — hobi/kişisel. Foundation CPL için.',
    tipsTr: ['PPL → CPL → ATPL ladder', 'EASA vs FAA differences'],
  },
  {
    id: 'qs_t5',
    category: 'technical',
    roles: ['student'],
    airlineIds: [],
    question: 'What is the multi-engine rating and why is it needed?',
    difficulty: 3,
    goodAnswerPointsTr: ['ME rating EASA Part-FCL', 'Twin-engine aircraft', 'Single-engine emergency proc', 'Critical engine concept', 'Required for airline'],
    redFlagsTr: ['ME bilmeme'],
    sampleAnswerTr: 'ME (Multi-Engine) Rating = twin/multi-engine uçaklar için. Single-engine PPL/CPL\'in üzerine eklenir. Spesifik training: critical engine identifikasyon (Vmc), single-engine emergency procedures, asymmetric thrust handling, EFATO (Engine Failure After Takeoff). 6 saat min + checkride. Airline F/O için zorunlu (B737/A320 multi-engine).',
    tipsTr: ['Vmc critical engine', 'Asymmetric thrust ops'],
  },
  {
    id: 'qs_t6',
    category: 'technical',
    roles: ['student'],
    airlineIds: [],
    question: 'What is the Instrument Rating (IR) and what does it allow?',
    difficulty: 3,
    goodAnswerPointsTr: ['IFR uçma yetkisi', 'IMC (cloud) penetrate', 'ILS approach yapabilir', '50 saat instrument time', 'Annual proficiency check'],
    redFlagsTr: ['IR bilmeme'],
    sampleAnswerTr: 'IR (Instrument Rating) = IFR (Instrument Flight Rules) altında uçma yetkisi. VFR (görsel) yetersiz: bulut, gece, IMC (Instrument Meteorological Conditions). 50 saat instrument time training. ILS (Instrument Landing System), VOR, GPS approach. PCAA + ICAO Annex 6. Annual proficiency check zorunlu. Airline pilot için IR + ME zorunlu.',
    tipsTr: ['IFR rules vs VFR', 'Instrument approach types'],
  },
  {
    id: 'qs_t7',
    category: 'technical',
    roles: ['student'],
    airlineIds: [],
    question: 'What is a Type Rating and how do you obtain one?',
    difficulty: 3,
    goodAnswerPointsTr: ['Spesifik aircraft için', 'Theory + simulator + line training', 'A320 / B737 / B777 type', '3-6 ay süreç', 'Sponsor/airline'],
    redFlagsTr: ['Type rating bilmeme'],
    sampleAnswerTr: 'Type Rating = spesifik uçak modeli için (örn A320, B737, B777) yetkilendirme. Process: 1) Ground school (system, performance, FCOM ders) 2) Simulator (FFS Level D) 30-50 saat 3) Base flight (uçakta 4-6 takeoff/landing) 4) Line training (revenue flight 30-100 saat) 5) Final Line Check. Süre: 3-6 ay. Cost: $20-50K (havayolu sponsor genelde).',
    tipsTr: ['Type rating cost financing', 'Airline sponsored programs'],
  },
  {
    id: 'qs_t8',
    category: 'technical',
    roles: ['student'],
    airlineIds: [],
    question: 'How do you decode a METAR? Give an example.',
    difficulty: 4,
    goodAnswerPointsTr: ['METAR routine weather report', 'Header + wind + visibility + sky + temp/dew + pressure', 'Each field bilgi', 'TAF forecast'],
    redFlagsTr: ['Decode edememe'],
    sampleAnswerTr: 'METAR = Meteorological Aerodrome Report. Örn: "METAR LTBA 121200Z 27015KT 9999 FEW040 25/12 Q1018 NOSIG". Decode: LTBA (İstanbul Atatürk), 12 Z 1200 (gün/saat UTC), wind 270° at 15 knots, visibility 10+ km, few clouds 4000 ft, temp 25°C / dew 12°C, pressure 1018 hPa, no significant change. Pilot pre-flight zorunlu okuma.',
    tipsTr: ['Skill: 100 METAR pratik', 'Bad weather decode'],
  },
  {
    id: 'qs_t9',
    category: 'technical',
    roles: ['student'],
    airlineIds: [],
    question: 'What are ICAO Annex 1 and Annex 6, and why are they relevant to a pilot?',
    difficulty: 4,
    goodAnswerPointsTr: ['Annex 1 = Personnel Licensing', 'Annex 6 = Operations of Aircraft', 'ICAO 18 annex', 'Member state implementation', 'Aviation legal foundation'],
    redFlagsTr: ['Annex bilmeme'],
    sampleAnswerTr: 'ICAO Annex 1 = Personnel Licensing — pilot lisansları, medical, ICAO Level 4 İngilizce dahil. Annex 6 = Operations of Aircraft — flight operations, fuel, equipment, MEL/CDL. Annex 2 (rules of the air), Annex 11 (ATC), Annex 14 (airport). 19 annex toplam. Üye devlet (Türkiye dahil) compliance — SHGM ICAO\'ya raporlar.',
    tipsTr: ['ICAO Doc 9432 frazeoloji', 'Annex high-level summary'],
  },
  {
    id: 'qs_t10',
    category: 'technical',
    roles: ['student'],
    airlineIds: [],
    question: 'Explain Bernoulli\'s principle in the context of aircraft lift.',
    difficulty: 3,
    goodAnswerPointsTr: ['Hız artar → basınç düşer', 'Wing camber upper surface uzun yol', 'Pressure differential = lift', 'Sadece kısmi açıklama (Newton da var)', 'Real lift = combined'],
    redFlagsTr: ['Yanlış formula'],
    sampleAnswerTr: 'Bernoulli: akışkan hızı artar → statik basınç düşer (P + ½ρV² = const). Wing camber: üst yüzey uzun yol → hava hızlı → basınç düşük. Alt yüzey hızlı yok → basınç yüksek. Pressure differential = lift. NOT: Bernoulli yetersiz açıklama, Newton 3rd law (downwash) da kritik. Modern aero combined model.',
    tipsTr: ['L = ½ρV²S CL formula', 'AoA ve Cl ilişki'],
  },
  {
    id: 'qs_t11',
    category: 'technical',
    roles: ['student'],
    airlineIds: [],
    question: 'What is stall and how do you recover from it?',
    difficulty: 3,
    goodAnswerPointsTr: ['Stall = critical AoA exceed', 'Lift sudden loss', 'Recovery: nose down + power + roll level', 'Practice in trainer', 'Fatal if not recover'],
    redFlagsTr: ['Recovery bilmeme'],
    sampleAnswerTr: 'Stall = wing critical AoA (Angle of Attack) ~15° exceed eder, smooth airflow ayrılır, lift ani kaybı. Recovery procedure: 1) Nose down (AoA reduce) 2) Power add (max thrust) 3) Roll level (banking olursa) 4) Climb resume after recovery. NOT: aşağı bakmak inatla — alt mahkum, yanlış. Stall warning (stick shaker, horn) erken uyarı.',
    tipsTr: ['Aerodynamics fundamentals', 'Stall practice CPL'],
  },
  {
    id: 'qs_t12',
    category: 'technical',
    roles: ['student'],
    airlineIds: [],
    question: 'What\'s the difference between a spin and a spiral dive?',
    difficulty: 4,
    goodAnswerPointsTr: ['Spin = stalled autorotation', 'Spiral dive = unstalled diving turn', 'Recovery procedure farklı', 'Spin: pro-spin controls oppose', 'Spiral: power reduce + level'],
    redFlagsTr: ['Karıştır (kritik)'],
    sampleAnswerTr: 'Spin = stalled wing autorotates around vertical axis (one wing more stalled). Recovery: power idle, ailerons neutral, rudder OPPOSITE rotation, stick FORWARD. Spiral dive = unstalled but tightly turning + descending fast (speed increasing). Recovery: power idle, level wings (ailerons), pull out smoothly. Karıştırırsa spin recovery spiral\'i kötüleştirir.',
    tipsTr: ['Aerobatic training spin', 'Recognition critical'],
  },
  {
    id: 'qs_e1',
    category: 'company_knowledge',
    roles: ['student'],
    airlineIds: [],
    question: 'What aviation universities in Turkey would you consider, and why?',
    difficulty: 2,
    goodAnswerPointsTr: ['THK Üniversitesi, Anadolu, Atılım, ESOGÜ, Erciyes', 'Pilot vs aviation management', 'Cost + scholarship', 'Industry connection', 'Faculty quality'],
    redFlagsTr: ['Bilmeme'],
    sampleAnswerTr: 'THK Üniversitesi (Türk Hava Kurumu), Anadolu Üniversitesi Pilotaj, Atılım Üniversitesi (özel), ESOGÜ Eskişehir, Erciyes Üniversitesi. Pilotaj programı (4 yıl, ATPL teori + pratik dahil) vs Aviation Management (operations, finance focus). Cost: devlet ücretsiz, özel ~$30K/yıl. THY/Pegasus partnership olan üniversiteler avantajlı (THK, Anadolu).',
    tipsTr: ['THY Cadet Programs', 'Üniversite + havayolu sponsor'],
  },
  {
    id: 'qs_e2',
    category: 'technical',
    roles: ['student'],
    airlineIds: [],
    question: 'What is the typical CPL training cost in Turkey?',
    difficulty: 3,
    goodAnswerPointsTr: ['Modular ~$70-100K', 'Integrated ~$120-180K', 'PPL → CPL → IR → ME stages', 'Cadet program sponsor', 'Bond agreement common'],
    redFlagsTr: ['Cost bilmeme'],
    sampleAnswerTr: 'Modular path: PPL ($15K) + Hour Building ($10K) + CPL ($25K) + IR ($20K) + ME ($10K) = ~$80-100K. Integrated path (450 saat tek kurs): $120-180K. Türkiye\'de Çukurova HÇK, Atlas Jet Aviation, ÖİV major schools. Cadet programlar (THY, Pegasus) sponsor — bond agreement (5-10 yıl commit).',
    tipsTr: ['Cadet program eligibility', 'Bond consequences'],
  },
  {
    id: 'qs_e3',
    category: 'technical',
    roles: ['student'],
    airlineIds: [],
    question: 'What\'s the difference between EASA and FAA pilot licenses?',
    difficulty: 4,
    goodAnswerPointsTr: ['EASA = Europe/Türkiye', 'FAA = USA', 'Theory differences', 'Conversion possible', 'Industry preferences'],
    redFlagsTr: ['Karıştır'],
    sampleAnswerTr: 'EASA = European Union Aviation Safety Agency, AB + Türkiye + UK + İsviçre. FAA = Federal Aviation Administration, USA. Theory ders sayısı: EASA 14, FAA fewer + different approach. EASA daha yapısal, FAA daha esnek. Conversion: EASA → FAA kolayca, FAA → EASA bridge course gerek. Airline pref: Avrupa havayolları EASA, US havayolları FAA.',
    tipsTr: ['Conversion process bil', 'Career region planning'],
  },
  {
    id: 'qs_e4',
    category: 'technical',
    roles: ['student'],
    airlineIds: [],
    question: 'What is MCC and why is it required for airline pilots?',
    difficulty: 3,
    goodAnswerPointsTr: ['Multi-Crew Cooperation', '20 saat sim', 'Crew coordination', 'CRM principles', 'Airline F/O için zorunlu'],
    redFlagsTr: ['MCC bilmeme'],
    sampleAnswerTr: 'MCC = Multi-Crew Cooperation. Single-pilot CPL\'den airline 2-pilot environment\'a geçiş kursu. 20-25 saat simulator (FNPT II MCC veya FFS). Crew coordination, CRM (Crew Resource Management), task sharing, briefing, sterile cockpit, threat & error management. Airline F/O hire öncesi zorunlu (genelde Type Rating ile birlikte).',
    tipsTr: ['CRM principles', 'JOC (Jet Orientation Course) eklenir bazen'],
  },
  {
    id: 'qs_e5',
    category: 'company_knowledge',
    roles: ['student'],
    airlineIds: ['turkish_airlines'],
    question: 'What are THY\'s pilot cadet programs and how do you qualify?',
    difficulty: 4,
    goodAnswerPointsTr: ['THY Pilot Eğitim Programı', 'University + flight school combo', 'Selection process (test + sim)', 'Bond 6-10 yıl', 'Salary during training'],
    redFlagsTr: ['THY cadet bilmeme'],
    sampleAnswerTr: 'THY Pilot Eğitim Programı: lise sonrası başvuru, üniversite (4 yıl pilotaj) + flight school (CPL/IR/ME) entegre. Selection: matematik/fizik test, English (B2 min), psychometric (DLR-ish), simulator screening, medical Class 1. Bond 6-10 yıl post-graduation (~$100K equivalent). Eğitim süresi: 4 yıl üni + 1 yıl flight = 5 yıl. Salary: stage geliştikçe artar.',
    tipsTr: ['Application early planning', 'Selection prep critical'],
  },
  {
    id: 'qs_h1',
    category: 'technical',
    roles: ['student'],
    airlineIds: [],
    question: 'What are the EASA Class 1 medical requirements for a commercial pilot?',
    difficulty: 4,
    goodAnswerPointsTr: ['Vision: 20/20 corrected', 'Color vision: pass Ishihara', 'Hearing: audiogram', 'Heart: ECG', 'No diabetes (insulin), epilepsy', 'Annual until 40, 6-aylı 60+'],
    redFlagsTr: ['Medical bilmeme'],
    sampleAnswerTr: 'EASA Class 1 Medical (Part-MED): 1) Vision 6/6 corrected (glasses OK); color vision Ishihara pass 2) Hearing: audiogram speech 60dB at 500-3000Hz 3) Cardiology: ECG normal, no major arrhythmia 4) No insulin-dependent diabetes 5) No epilepsy/seizures 6) Mental health stable. Renewal: <40 yıllık, 40-60 yarıyıl, 60+ 6-aylı. AME (Aero-Medical Examiner) certified yapar.',
    tipsTr: ['Class 1 vs Class 2 fark', 'Limitation accept (corrective)'],
  },
  {
    id: 'qs_h2',
    category: 'technical',
    roles: ['student'],
    airlineIds: [],
    question: 'Is color blindness disqualifying for a pilot?',
    difficulty: 3,
    goodAnswerPointsTr: ['Tam color blind = disqualifying', 'Mild deficiency = limited', 'Aviation Color Vision Test (CAD)', 'Single-pilot ATPL not allowed if fail', 'Each authority strict'],
    redFlagsTr: ['"Sorun değil"'],
    sampleAnswerTr: 'Yes mostly. Ishihara test fail = secondary CAD test (Color Assessment & Diagnosis). Failed CAD: ICAO Annex 1 Class 1 medical fail = pilot olamaz. Mild deficiency (CAD pass): bazı limitations (örn UK CAA day VFR only). EASA daha katı. Color: red (warning lights), green (taxi), white critical.',
    tipsTr: ['CAD test prep', 'Pre-screen kid'],
  },
  {
    id: 'qs_h3',
    category: 'technical',
    roles: ['student'],
    airlineIds: [],
    question: 'What is the height and BMI requirement for THY pilot positions?',
    difficulty: 2,
    goodAnswerPointsTr: ['Boy 165-200cm typical', 'BMI 18-25', 'Cockpit reach + visibility', 'Medical Class 1 supersede', 'Each airline policy'],
    redFlagsTr: ['Bilmeme'],
    sampleAnswerTr: 'THY pilot: boy 165-200cm typical (cockpit reach + rudder pedal + visibility). BMI 18-25 healthy range — over: risk Class 1 fail (cardio risk), under: risk underweight medical issues. Yıllık medical Class 1 zorunlu — boy/kilo bunun parçası. Cabin crew daha katı (160-180 boy + cabin overhead reach).',
    tipsTr: ['Pre-employment health check', 'Long-term fitness'],
  },
  {
    id: 'qs_b1',
    category: 'behavioral',
    roles: ['student'],
    airlineIds: [],
    question: 'Tell me about a time you failed at something and what you learned.',
    difficulty: 3,
    goodAnswerPointsTr: ['Honest specific failure', 'Reflection + learning', 'Action change', 'STAR format', 'Show resilience'],
    redFlagsTr: ['"Hiç başarısız olmadım"', 'Blame'],
    sampleAnswerTr: 'Situation: Lise 11. sınıf matematik final, hazırlandığımı düşünüyordum, 65 aldım. Task: Üni hazırlık etkilenecek. Action: 1) Why fail analysis — soru tipini ezberlemiştim, mantığı anlamamıştım 2) Tutoring + farklı kaynak 3) Daily problem solving rutin. Result: Bir sonraki dönem 92, üni sınavında matematik %85. Learn: ezber surface, anlamak deep. Aviation\'da AMM ezber yetmez — neden anla.',
    tipsTr: ['Genuine failure', 'Specific learning + action change'],
  },
  {
    id: 'qs_b2',
    category: 'behavioral',
    roles: ['student'],
    airlineIds: [],
    question: 'How do you handle stress during high-stakes exams?',
    difficulty: 3,
    goodAnswerPointsTr: ['Preparation = best stress mgmt', 'Sleep + nutrition routine', 'Visualization', 'Breathing technique', 'Past success reference'],
    redFlagsTr: ['"Stress yok"'],
    sampleAnswerTr: 'Preparation = primary defense. Aylık + günlük plan. Exam öncesi hafta: 7 saat sleep priority, balanced meal, exercise 3x. Sınav günü: meditation 5 min, breathing technique (4-7-8), visualization. Past success: "Geçen sefer YDS 88, hazırlığım iyi". Aviation\'da pressure normal — stress management uçucu trait.',
    tipsTr: ['Stress management technique', 'Aviation pressure practice'],
  },
  {
    id: 'qs_b3',
    category: 'behavioral',
    roles: ['student'],
    airlineIds: [],
    question: 'Why do you want to fly for our airline specifically?',
    difficulty: 3,
    goodAnswerPointsTr: ['Spesifik araştırma', 'Şirket kültür/değer match', 'Network/destination strategy', 'Future opportunity', 'Pasajik commit'],
    redFlagsTr: ['Generic'],
    sampleAnswerTr: 'THY için: Star Alliance hub kapasitesi (300+ destination), genç + büyüyen filo (787, A350), Türkiye merkezli + global exposure. Kültür: "Widen Your World" mottosu — diversity + service excellence. Pilot career: 5 yıl F/O → senior F/O → captain path. Long-term commit: 10+ yıl planlıyorum, training maliyetin geri ödüyorum (bond accept).',
    tipsTr: ['Specific airline research', 'Culture match show'],
  },
  {
    id: 'qs_b4',
    category: 'motivation',
    roles: ['student'],
    airlineIds: [],
    question: 'Where do you see yourself in 10 years?',
    difficulty: 3,
    goodAnswerPointsTr: ['Realistic milestone (Captain)', 'Specific aircraft/route', 'Continued learning', 'Industry contribution', 'Long-term commit'],
    redFlagsTr: ['Vague', 'Unrealistic'],
    sampleAnswerTr: '10 yıl: F/O start → senior F/O 4 yıl → command upgrade → Captain (long-haul A350 ya da B777). 5000+ FH accumulated. Type rating expansion. Mentorship junior F/O\'lara. Industry contribution: SMS contributor, training role. THY group içinde uzun-dönem path. Goal: 50 yaş senior captain + check airman.',
    tipsTr: ['Realistic upgrade timeline', 'Continued growth show'],
  },
  {
    id: 'qs_b5',
    category: 'behavioral',
    roles: ['student'],
    airlineIds: [],
    question: 'What\'s your backup plan if you don\'t become a pilot?',
    difficulty: 3,
    goodAnswerPointsTr: ['Realistic alternative aviation', 'Skill transferable', 'Continued passion', 'Honest acknowledgment', 'Show resilience'],
    redFlagsTr: ['"Yok"', 'Aviation çıkışı'],
    sampleAnswerTr: 'Aviation passion sürer — alternatif: 1) Aviation Operations Manager (CPL eğitim baz, ground operations) 2) Aviation Safety Inspector (SHGM, EASA) 3) Flight Dispatcher (operations control). Skills transferable: aviation knowledge, decision-making, regulations, English. Acknowledged: medical fail veya selection failure olursa, kendimi adapt ederim. Realism + passion combo.',
    tipsTr: ['Mature acknowledgment', 'Transferable skills show'],
  },
  {
    id: 'qs_b6',
    category: 'situational',
    roles: ['student'],
    airlineIds: [],
    question: 'How would you handle pressure from a more experienced captain pushing you to skip a checklist item?',
    difficulty: 5,
    goodAnswerPointsTr: ['Assertive + respectful', 'Reference to SOP', 'CRM PACE protocol', 'Don\'t skip safety', 'Document if needed'],
    redFlagsTr: ['"Captain karar"', 'Sessiz kal'],
    sampleAnswerTr: 'CRM training: PACE protocol (Probe → Alert → Challenge → Emergency). 1) Probe: "Captain, bu checklist item\'ı atlamamız işime yetişmek için mi?" Polite query. 2) Alert: "SOP bu item\'ı zorunlu kılıyor — örn before-takeoff flap check". 3) Challenge: "Atlarsak risk şu — atmadan devam edelim". 4) Emergency: "Reject takeoff" çağırma hakkım. Doc: ASR (Air Safety Report) sonra. F/O assertiveness life-saving.',
    tipsTr: ['CRM PACE memorize', 'Air France 447 example'],
  },
  {
    id: 'qs_t13',
    category: 'technical',
    roles: ['student'],
    airlineIds: [],
    question: 'What is V1 in aviation?',
    difficulty: 3,
    goodAnswerPointsTr: ['Decision speed', 'Critical engine fail point', 'Below V1: abort', 'Above V1: continue', 'Calculated per condition'],
    redFlagsTr: ['V1 bilmeme'],
    sampleAnswerTr: 'V1 = Decision Speed, takeoff sırasında engine failure olursa "abort or continue" karar noktası. V1 öncesi: stop (RTO — Rejected Takeoff). V1 sonrası: continue (kalkış kalan distance + V2 climb). Calculated per: weight, runway length, altitude, temperature, wet/dry. Pilot announce "V1" + remove hand from throttle (commit decision). Critical engine failure scenarios training.',
    tipsTr: ['V1, VR, V2 tüm bil', 'RTO procedure'],
  },
  {
    id: 'qs_t14',
    category: 'technical',
    roles: ['student'],
    airlineIds: [],
    question: 'What is the difference between IFR and VFR?',
    difficulty: 2,
    goodAnswerPointsTr: ['IFR = Instrument Flight Rules', 'VFR = Visual Flight Rules', 'IFR ATC + IMC OK', 'VFR weather min visibility', 'Airline ops IFR'],
    redFlagsTr: ['Karıştır'],
    sampleAnswerTr: 'VFR (Visual Flight Rules) = pilot dış göz referans, weather minimums (visibility 5km+ class C, cloud clearance). IFR (Instrument Flight Rules) = instrument panel referans, ATC clearance bağlı, IMC (Instrument Meteorological Conditions — bulut, gece) izin. Airline operations =100% IFR (regulatory + safety). PPL VFR-only, CPL/ATPL IFR rated.',
    tipsTr: ['VMC vs IMC bil', 'IFR clearance components'],
  },
  {
    id: 'qs_t15',
    category: 'technical',
    roles: ['student'],
    airlineIds: [],
    question: 'What does "squawk 7700" mean?',
    difficulty: 3,
    goodAnswerPointsTr: ['Emergency transponder code', '7700 = general emergency', '7600 = lost comms', '7500 = hijack', 'ATC immediate priority'],
    redFlagsTr: ['Karıştır'],
    sampleAnswerTr: 'Squawk = transponder kod set etmek. 7700 = general emergency (engine failure, medical, vs). 7600 = lost communication (radio fail). 7500 = hijack/unlawful interference. ATC anında priority handling: clearance, vector, support. Pilot Mayday call + 7700 squawk parallel — radar + voice alert. ICAO Annex 11 standard.',
    tipsTr: ['Memorize 7700/7600/7500', 'Mayday + squawk procedure'],
  },
];

export default ROLES_EXTRA_QUESTIONS_V2;
