/**
 * Genişletilmiş Teknisyen, Yer Hizmetleri ve Öğrenci Mülakat Soruları (40+).
 */
import type { InterviewQuestion } from './airlineTypes';

export const ROLES_EXTRA_QUESTIONS: InterviewQuestion[] = [
  // ═══════════ TEKNİSYEN ═══════════
  {
    id: 'qt_te1',
    category: 'technical',
    roles: ['technician'],
    airlineIds: [],
    question: 'What\'s the difference between an A-check, B-check, C-check, D-check?',
    difficulty: 4,
    goodAnswerPointsTr: [
      'A-check: 400-600 FH, ramp/hangar, 1 gece, basit kontroller',
      'B-check: 6-8 ay, hangarda 1-3 gün (artık çoğu havayolunda kaldırıldı)',
      'C-check: 18-24 ay, hangarda 1-2 hafta, derinlemesine inceleme',
      'D-check: 6-10 yıl, 4-6 hafta hangarda overhaul',
    ],
    redFlagsTr: ['Karıştır', 'Süreleri yanlış'],
    sampleAnswerTr: 'A-check = 400-600 uçuş saati, ramp/hangar, 1 gecelik. Filter check, fluid, basic systems. B-check artık yaygın değil. C-check = 18-24 ay, hangar 1-2 hafta, açıkça yapısal incele, sistem deep-dive. D-check = 6-10 yıl, 4-6 hafta, full overhaul, soyma + boyama, ciddi yapısal kontrol. Her check sonrası CRS imzası.',
    tipsTr: ['ATA chapter ile bağla', 'Each level\'da typical bulgu örnek'],
  },
  {
    id: 'qt_te2',
    category: 'technical',
    roles: ['technician'],
    airlineIds: [],
    question: 'A pilot reports "right brake pulsation on landing". You\'re assigned. Walk me through your troubleshooting.',
    difficulty: 5,
    goodAnswerPointsTr: [
      'Tech log + write-up read',
      'Tire condition check (flat spot)',
      'Brake disc visual + thickness measurement',
      'Anti-skid system check (test on jacks)',
      'Hydraulic pressure reading',
      'BSCU (Brake System Control Unit) BITE',
      'AMM TSM (Trouble Shooting Manual) reference',
    ],
    redFlagsTr: ['Random part replacement', 'AMM bakmama'],
    sampleAnswerTr: 'Önce tech log + pilot write-up okurum. Tire flat spot kontrol — eğer var, hızlı kalkış sırasında lock olduğunu işaret. Brake disc visual + thickness gauge ölç (wear limit AMM\'de). Anti-skid sistem operate test — uçak jack üzerinde, BSCU BITE oku. Hydraulic line pressure kontrol. AMM ATA 32-40 TSM page açık, fault tree takip. Most common: tire flat spot veya brake stuck (carbon disc).',
    tipsTr: ['ATA 32-40 brakes', 'TSM fault isolation', 'BITE results dokümante'],
  },
  {
    id: 'qt_te3',
    category: 'technical',
    roles: ['technician'],
    airlineIds: [],
    question: 'What does CRS stand for and what are you signing?',
    difficulty: 4,
    goodAnswerPointsTr: [
      'CRS = Certificate of Release to Service',
      'Maintenance task tamamlandı + airworthy',
      'B1/B2/C lisans gerekli',
      'Type-specific authorization',
      'Yasal bağlayıcı belge',
    ],
    redFlagsTr: ['Genel "imzalıyorum"'],
    sampleAnswerTr: 'CRS = Certificate of Release to Service. EASA Part-145 altında, bir maintenance task tamamlandığında yetkili teknisyen "uçak/sistem airworthy ve operasyona uygun" beyanını yasal olarak imzalar. Sadece B1 (mechanical), B2 (avionics), veya C (base maintenance) lisanslı + type-rated kişi imzalar. Yanlış imza = yasal sorumluluk + lisans iptal.',
    tipsTr: ['EASA Part-145.A.50 referans', 'License + type rating + scope'],
  },
  {
    id: 'qt_te4',
    category: 'technical',
    roles: ['technician'],
    airlineIds: [],
    question: 'Read this AMM excerpt aloud and explain: "Apply torque seal to lockwire installation per ATA 20-50-12, ensuring witness mark is visible after curing."',
    difficulty: 4,
    goodAnswerPointsTr: [
      'Net İngilizce telaffuz',
      'Açıklama: torque seal = kuruyan boya, lockwire üzerine markalı',
      'Witness mark = sonradan oynamaması kontrol',
      'ATA 20 = standart practice',
    ],
    redFlagsTr: ['Telaffuz zayıf', 'Anlam bilmeme'],
    sampleAnswerTr: 'Bu pasaj diyor: "ATA 20-50-12\'ye göre lockwire kurulumuna torque seal uygula, kuruduktan sonra witness mark görünebilir olmalı." Yani: lockwire + cıvata sıktıktan sonra üzerine kuruyan renk işaretle (torque seal). Bu kuruyup sonradan kıllar — eğer cıvata oynar, kıllar bozulur. Witness mark = sonraki inspeksiyonda "oynamadı" kontrolü.',
    tipsTr: ['AMM jargon bil', 'ATA 20 standard practices'],
  },
  {
    id: 'qt_te5',
    category: 'situational',
    roles: ['technician'],
    airlineIds: [],
    question: 'You\'re halfway through a brake change and you notice the part number on the new brake doesn\'t match the IPC. Action?',
    difficulty: 5,
    goodAnswerPointsTr: [
      'STOP work — yanlış part takılmaz',
      'IPC + applicable revision recheck',
      'Part Marketing/inventory contact',
      'Stores\'a iade — doğru part talep',
      'Olay raporu (yanlış part packing)',
    ],
    redFlagsTr: ['"Ne olur ki" diye tak', 'Sessiz kal'],
    sampleAnswerTr: 'Hemen DURDUR — yanlış part = airworthiness ihlal + uçak yere mahkum + lisans riski. IPC ve son revizyonu tekrar bak. Part marketing/stores arar, "P/N XYZ talep ettim ama ABC geldi" rapor. Doğru part talep, yanlışı iade. Yanlış packing/labeling olayı incidence report yazılır (Quality department investigates supplier).',
    tipsTr: ['Quality + safety culture', 'Supply chain hata sıkça', 'Documentation chain'],
  },
  {
    id: 'qt_te6',
    category: 'technical',
    roles: ['technician'],
    airlineIds: [],
    question: 'What\'s the difference between scheduled and unscheduled maintenance?',
    difficulty: 3,
    goodAnswerPointsTr: [
      'Scheduled: maintenance program (A/B/C/D, daily, transit)',
      'Unscheduled: pilot reports, fault, AOG',
      'Hard time vs on-condition',
      'MPD (Maintenance Planning Document) sahibi: OEM',
    ],
    redFlagsTr: ['Karıştır'],
    sampleAnswerTr: 'Scheduled = OEM\'in MPD (Maintenance Planning Document)\'ine göre planlı bakım: daily, transit, A-check, C-check, D-check. Hard time intervals (FH, FC, calendar). Unscheduled = pilot raporu, BITE fault, AOG (Aircraft On Ground). On-condition = component shop\'a sonra check — bozulmadıkça değiştirme yok.',
    tipsTr: ['Maintenance program structure', 'CAMO planning role'],
  },
  {
    id: 'qt_te7',
    category: 'situational',
    roles: ['technician'],
    airlineIds: [],
    question: 'On midnight shift, you find a small crack on a wing skin during walk-around. AOG situation. Action?',
    difficulty: 5,
    goodAnswerPointsTr: [
      'Photo + measurement (caliper)',
      'SRM (Structural Repair Manual) reference',
      'Damage chart compare',
      'In-allowable: temporary repair, MEL/CDL check',
      'Out-of-limit: AOG declare, engineering call',
      'Tech log entry + write-up',
    ],
    redFlagsTr: ['Görmezden gel', 'Tahmin ile karar'],
    sampleAnswerTr: 'Photo çek (length, width, location). Caliper ile ölç. AMM ATA chapter\'a git (örn ATA 57 wings). SRM aç — crack için allowable limits tablosu. Eğer in-limit: temporary patch + monitor (MEL/CDL kategori). Eğer out-of-limit: chief engineer call → AOG declare → uçak grounded → permanent repair plan (çoğu zaman OEM consult).',
    tipsTr: ['SRM jargon bil', 'Damage measurement standartları', 'Engineering chain'],
  },

  // ═══════════ YER HİZMETLERİ ═══════════
  {
    id: 'qg_te1',
    category: 'technical',
    roles: ['ground'],
    airlineIds: [],
    question: 'What does GPU mean and when do you use it?',
    difficulty: 2,
    goodAnswerPointsTr: ['Ground Power Unit', 'APU yerine yerden 115V 400Hz AC', 'Gate\'te yakıt tasarrufu', 'Çevre dostu'],
    redFlagsTr: ['Yanlış akronim'],
    sampleAnswerTr: 'GPU = Ground Power Unit. Uçak gate\'teyken APU yerine yerden 115V 400Hz AC + 28V DC sağlar. APU yakıt yakacağına GPU\'da elektrik kullanır — yakıt tasarrufu (saatte ~150 kg jet fuel) + emisyon azaltma + APU MTBR uzatma.',
    tipsTr: ['Eco-GSE trend', 'Connection sequence: chock → GPU → AC'],
  },
  {
    id: 'qg_te2',
    category: 'situational',
    roles: ['ground'],
    airlineIds: [],
    question: 'During pushback, the headset cable disconnects. What\'s your immediate action?',
    difficulty: 4,
    goodAnswerPointsTr: [
      'Hemen pushback STOP işareti — wing/nose tow operator',
      'Cockpit\'le visual signal kullan',
      'Hand signal: cross arms = STOP',
      'Yeni headset bağla / spare',
      'Captain\'a "lost comms" hand signal',
      'Sonra: cause analysis (pin defect)',
    ],
    redFlagsTr: ['Devam et — büyük tehlike'],
    sampleAnswerTr: 'STOP işareti hemen — kollarımı çapraz çevir. Pushback driver\'a komuta hand signal ile. Cockpit ve ben görsel temasta — captain\'a "lost comms" gestürü (ses olmadığı). Spare headset / yeni cable bağlama. Comms restore: hand signal "good comms" → resume push. Olay sonrası: cable defect raporu, equipment service order.',
    tipsTr: ['Hand signal dictionary ezbere', 'Pushback safety = #1', 'Spare equipment'],
  },
  {
    id: 'qg_te3',
    category: 'situational',
    roles: ['ground'],
    airlineIds: [],
    question: 'IRROPS — A flight is delayed 4 hours due to weather, 180 passengers waiting at gate. Manager asks you to lead. What do you do?',
    difficulty: 4,
    goodAnswerPointsTr: [
      'PA announcement net + dürüst',
      'Sebep + tahmini + recovery plan',
      'Vouchers (yemek, su)',
      'Ailelerle yolcular için seating uzaklaştır',
      'Aktif info refresh — 30 dk\'da bir',
      'Kritik yolcular (UM, MEDA, transit) öncelik',
    ],
    redFlagsTr: ['"Bilgi yok" deme', 'Dağılan yolcular', 'Kalabalık panik'],
    sampleAnswerTr: 'İlk 5 dk: gate PA — "Hava nedeniyle uçuşumuz 4 saat gecikti, sebep XYZ, beklenen kalkış HH:MM". Sonra ekiple stand-up: 1 kişi gate desk (info), 1 kişi voucher dağıtım, 1 kişi UM/MEDA/transit özel ihtiyaç. 30 dk\'da bir refresh announcement. Sosyal medya kanallar update. Yolcu sıkıntı arttığında: rebooking option offer, hotel voucher EU 261 kapsamında.',
    tipsTr: ['EU 261 yolcu hakları', 'Crisis communication', 'Resource allocation'],
  },
  {
    id: 'qg_te4',
    category: 'technical',
    roles: ['ground'],
    airlineIds: [],
    question: 'What is FOD and why is it dangerous?',
    difficulty: 3,
    goodAnswerPointsTr: [
      'FOD = Foreign Object Debris',
      'Engine ingestion = catastrophic damage',
      'Tire damage at speed',
      'Pilot/structure injury',
      'FOD walk: günlük zorunluluk',
      'Concorde 2000 example',
    ],
    redFlagsTr: ['Akronim bilmeme'],
    sampleAnswerTr: 'FOD = Foreign Object Debris (yabancı obje atık). Pist/ramp/taxiway\'de kalan herhangi bir cisim: vida, taş, plastik, kuş. Engine ingestion = motor catastrophic damage (Concorde 2000 = 113 ölü, runway\'de bir titanyum şerit). Tire blowout at high speed. FOD walk = ekip günlük yapılır, gözle pist/ramp tarayışı. Magnetic FOD bar GSE\'lere takılır.',
    tipsTr: ['FOD walk standartı', 'Air France 4590 case', 'GSE preventive measure'],
  },
  {
    id: 'qg_te5',
    category: 'situational',
    roles: ['ground'],
    airlineIds: [],
    question: 'Hot brake light on incoming aircraft. Action?',
    difficulty: 4,
    goodAnswerPointsTr: [
      'Maintain safe distance (200ft min)',
      'Soğumayı bekle',
      'Chock yapma — risk genişler',
      'Fire extinguisher ready',
      'Aircraft personnel safe distance',
      'Engineering bildirim',
      'Su KULLANMA (termal şok = fracture risk)',
    ],
    redFlagsTr: ['Hemen chock', 'Su sık'],
    sampleAnswerTr: 'Min 200 ft mesafe koru — patlama / yangın riski. Chocks yapma yet. Fire extinguisher ekibi hazır bekle. Soğuma süresi (30-60 dk genelde). Su KULLANMA — sıcak metal\'e su = thermal shock = wheel/disc fracture. Engineering bildirim, brake fan / cooling cart talep mümkünse. Cleared once temp normal: chocks + GPU connection + standart turnaround.',
    tipsTr: ['Hot brake protocol IATA AHM', 'Ramp safety SOP'],
  },
  {
    id: 'qg_te6',
    category: 'situational',
    roles: ['ground'],
    airlineIds: [],
    question: 'A passenger arrives 10 minutes before departure with checked bags. Gate just closed. What do you do?',
    difficulty: 3,
    goodAnswerPointsTr: [
      'Strict gate close policy — uçak waitirilmez',
      'Empati + alternatif sun',
      'Rebooking + bag forward',
      'Yolcu hakları açıkla (no-show kategori — biz bilet kapsam dışı)',
      'Sonraki uçuş availability',
    ],
    redFlagsTr: ['Gate aç', '"Maybe" diyerek umut ver'],
    sampleAnswerTr: '"Çok özür dilerim, gate kapandı ve uçak hareket halinde. Sizi alamayız ama yardımcı olayım." Rebooking sonraki uçuşa (sometimes ücretsiz, sometimes değişim ücretiyle). Checked bags = ya forward to destination ya iade. Empati + hızlı çözüm.',
    tipsTr: ['Customer service script bil', 'No exceptions for safety'],
  },

  // ═══════════ ÖĞRENCİ ═══════════
  {
    id: 'qs_m1',
    category: 'motivation',
    roles: ['student'],
    airlineIds: [],
    question: 'Why do you want to study aviation?',
    difficulty: 2,
    goodAnswerPointsTr: ['Spesifik kişisel motivation', 'Sektör tutku örneği', 'Uzun dönem hedef bil', 'Sektör trends bil'],
    redFlagsTr: ['"Para iyi" yüzeysel', '"Bilmiyorum kesin"'],
    sampleAnswerTr: '8 yaşında babamla TK 1 İstanbul-Frankfurt uçuşunda kaptan kabini ziyaret etti — o anda hayalim oldu. Lise sonrası fizik+matematik\'e odaklandım, MTAL pilotaj programı bitirdim, şu an üniversite. Hedefim: ATPL teori + CPL pratik + ICAO 4. 5 yıl sonra TK F/O olarak uçacağım. Sektör trend\'leri (sürdürülebilirlik, eVTOL, otomatizasyon) yakından takip ediyorum.',
    tipsTr: ['Spesifik plan göster', 'Sektör bilgili görün'],
  },
  {
    id: 'qs_m2',
    category: 'motivation',
    roles: ['student'],
    airlineIds: [],
    question: 'What aviation career path interests you most and why?',
    difficulty: 3,
    goodAnswerPointsTr: ['Net path seçimi (pilot/cabin/tech/ground)', 'Realistic neden', 'Eğitim plan bil', 'Backup plan'],
    redFlagsTr: ['Kararsız', 'Üç yolu birlikte iste'],
    tipsTr: ['Bir yola odaklan', 'Plan B kabul et'],
  },
  {
    id: 'qs_t1',
    category: 'technical',
    roles: ['student'],
    airlineIds: [],
    question: 'What is ATPL and how is it different from CPL?',
    difficulty: 3,
    goodAnswerPointsTr: [
      'ATPL = Airline Transport Pilot License (en üst)',
      'CPL = Commercial Pilot License',
      'ATPL = captain olabilir, CPL = F/O',
      'ATPL = 1500 saat min (FAA), 1500 (ICAO)',
      'Frozen ATPL = teori bitti pratik eksik',
    ],
    redFlagsTr: ['Karıştır'],
    sampleAnswerTr: 'CPL = ticari pilot lisansı, F/O olarak uçabilirsin (~250 saat). ATPL = airline transport pilot, captain olabilirsin (1500 saat min). ATPL teorisi 14 ders + 14 sınav (ICAO/EASA). "Frozen ATPL" = teori bitti ama saat eksik (CPL ile uçarsın, saat dolunca ATPL "unfreeze"). MCC (Multi-Crew Cooperation) ekstra kurs, multi-crew uçaklarda zorunlu.',
    tipsTr: ['EASA Part-FCL bil', 'Path: PPL → CPL → IR → MCC → ATPL'],
  },
  {
    id: 'qs_t2',
    category: 'technical',
    roles: ['student'],
    airlineIds: [],
    question: 'What does ICAO Level 4 require?',
    difficulty: 3,
    goodAnswerPointsTr: [
      '6-area rubric: pron, struct, vocab, fluency, comprehension, interactions',
      'Operational level — non-routine\'de plain English yeterli',
      '3 yıl geçerli (Level 4)',
      'Pilot, ATC için zorunlu',
    ],
    redFlagsTr: ['ICAO 4 = TOEFL gibi düşün'],
    sampleAnswerTr: 'ICAO Level 4 = "Operational" — pilot/ATC\'nin uluslararası uçuşlar için min İngilizce yeterliliği. 6 alan: telaffuz, yapı, kelime, akıcılık, anlama, etkileşim — her biri 1-6 puan, tümü Level 4 olmalı (ortalama değil). Operational anlamı: standart frazeoloji + olağandışı durumda plain English ile baş edebilme. 3 yıl geçerli (Level 5 = 6 yıl, Level 6 = lifetime).',
    tipsTr: ['ICAO Annex 1 ek', 'AirSpeak ICAO 4 modülü pratik'],
  },
  {
    id: 'qs_b1',
    category: 'behavioral',
    roles: ['student'],
    airlineIds: [],
    question: 'Tell me about a time you led a team project at school.',
    difficulty: 3,
    goodAnswerPointsTr: ['STAR formatı', 'Spesifik proje + rol', 'Liderlik beceri', 'Sonuç + öğrenilen'],
    redFlagsTr: ['Kendini kibirli göster', 'Genel cevap'],
    sampleAnswerTr: 'Üniversitede aviation safety dersi için (S) 5 kişilik proje: bir kaza analizi (Air France 447). (T) Ben proje lideri seçildim. (A) Görev dağıttım: 2 kişi pilot input, 1 weather, 1 systems, 1 ben sentez. Haftalık standup, Trello board kurdum. Çatışma vardı (bir arkadaş geç teslim) — özel konuştum, schedule reset. (R) %95 not + presentation prize.',
    tipsTr: ['Spesifik detay', 'Çatışma yönetimi örneği'],
  },
  {
    id: 'qs_t3',
    category: 'tricky',
    roles: ['student'],
    airlineIds: [],
    question: 'How do you afford pilot training? It costs €100,000+.',
    difficulty: 4,
    goodAnswerPointsTr: [
      'Dürüst plan (kredi, scholarship, cadet program)',
      'Aile desteği (varsa) belirt',
      'Cadet program araştırma (Lufthansa, Etihad, etc)',
      'Türkiye seçenekleri (THY Akademi, Atlas Akademi)',
      'Long-term ROI hesabı',
    ],
    redFlagsTr: ['"Bilmem nasıl" — plansız', 'Tek kaynak (sadece aile)'],
    sampleAnswerTr: 'Plan: 1) Cadet program başvurusu (THY Akademi, Etihad, Lufthansa, BA) — sponsorlu eğitim. 2) Devlet kredisi (KYK + ek) ~₺500K. 3) Aile desteği var ama tam değil — aileyle paylaşırım. 4) Yedek: PPL kendim öderim, sonra modular CPL/ATPL. ROI hesabı: 3 yıl maliyet vs 30 yıl pilot kazancı (yıllık ₺350K+) — çok pozitif.',
    tipsTr: ['Realistik finansal plan', 'Industry sponsorship bil', 'Long-term math'],
  },

  // ═══════════ KABİN — SHGM/THY EK ═══════════
  {
    id: 'qc_shgm1',
    category: 'company_knowledge',
    roles: ['cabin'],
    airlineIds: ['turkish_airlines', 'pegasus', 'sunexpress', 'anadolujet'],
    question: 'SHGM CCD (Cabin Crew Diploma) zorunluluğunun amacı nedir?',
    difficulty: 3,
    goodAnswerPointsTr: [
      'Sivil havacılık güvenliği standart',
      'Min English yeterlilik garantisi',
      'PA + emergency comms',
      'Türkiye için yasal zorunluluk',
      '5 yıl renewal',
    ],
    redFlagsTr: ['Bilmiyorum'],
    sampleAnswerTr: 'SHGM CCD = Cabin Crew Diploma. Türkiye\'de kabin memuru olmak için yasal zorunlu. Amaç: kabin crew\'un sivil havacılık güvenliği standardına ulaştığını belgeler — emergency procedures, PA İngilizce, yolcu iletişimi. 5 yıl geçerli, renewal\'da güncel eğitim. SHGM auditing yapar.',
    tipsTr: ['SHGM Genelge 2017/4', 'CCD eğitim merkezleri (THY, Pegasus akademileri)'],
  },
  {
    id: 'qc_thy_extra',
    category: 'situational',
    roles: ['cabin'],
    airlineIds: ['turkish_airlines'],
    question: 'TK 1 IST-JFK 12 saat uçuşunda yolcu kalp krizi geçiriyor. Sen senior crew\'sun. Aksiyon?',
    difficulty: 5,
    goodAnswerPointsTr: [
      'Hemen on-board doctor anonsu',
      'Captain bilgilendir',
      'AED hazır + first aid kit',
      'Yolcu konum: koltukta ya da koridor',
      'CPR başlat varsa endikasyon',
      'Captain divert decision',
      'Closest suitable airport (ETOPS rules)',
    ],
    redFlagsTr: ['Panik', 'Doktor anonsu atla'],
    sampleAnswerTr: 'Hemen "Aramızda doktor var mı? Acil tıbbi yardım gerek" anonsu çift dilde. AED hazır al, first aid kit. Captain bildirimi: "Medical emergency, possible cardiac, request divert assessment". Doktor varsa direktiflerle CPR/AED. Yoksa: Medlink konsültasyon (TK Medlink program). Captain decision divert or continue (12h flight, North Atlantic — closest suitable Gander veya Reykjavik). Cabin crew rotational support.',
    tipsTr: ['TK Medlink protokol', 'AED kullanım', 'NAT track divert opsiyon'],
  },

  // ═══════════ DAHA FAZLA EUROPEAN/GULF ÖZEL ═══════════
  {
    id: 'qc_pre_grp',
    category: 'group_exercise',
    roles: ['cabin'],
    airlineIds: ['emirates', 'qatar', 'etihad'],
    question: 'GROUP TASK: Your aircraft is preparing for emergency landing. You have 4 minutes. As cabin crew team, prioritize 5 actions in order.',
    difficulty: 5,
    goodAnswerPointsTr: [
      'Captain brief listen + understand',
      'Cabin announcement (calm, clear)',
      'Brace position + commands hazır',
      'Special pax (UM, MEDA, elderly) special instructions',
      'Crew rotational checks',
      'Exit assignment confirm',
    ],
    redFlagsTr: ['Panik', 'Tek başına karar'],
    tipsTr: ['Emergency protocol ezbere', 'Crew rotation', 'Communication chain'],
  },
];
