/**
 * Kabin Memuru vocabulary seed — Faz 1.
 * 60 terim: PA anonsları, emniyet, servis, yolcu tipi, koordinasyon, mülakat.
 */
import type { VocabularyTerm } from './pilotVocab';

export const CABIN_VOCAB_FAZ1: VocabularyTerm[] = [
  // ===== PA & PASSENGER COMMUNICATION (12) =====
  { id: 'voc_cabin_001', term: 'cabin crew', termTr: 'kabin ekibi', pronunciation: '/ˈkæb.ɪn kruː/', category: 'staff', difficulty: 1,
    definitionEn: 'The flight attendants and stewards working in the passenger cabin.',
    definitionTr: 'Yolcu kabininde çalışan hostes ve stewardlar.',
    examples: [
      { en: 'Cabin crew, prepare for departure.', tr: 'Kabin ekibi, kalkışa hazırlanın.' },
      { en: 'Our cabin crew speaks four languages.', tr: 'Kabin ekibimiz 4 dil konuşuyor.' },
    ],
    relatedTerms: ['flight attendant', 'purser', 'steward'],
  },
  { id: 'voc_cabin_002', term: 'fasten seatbelt', termTr: 'emniyet kemerini bağla', pronunciation: '/ˈfæs.ən ˈsiːt.belt/', category: 'safety', difficulty: 1,
    definitionEn: 'To secure the seatbelt across the lap before takeoff, landing, or turbulence.',
    definitionTr: 'Kalkış, iniş veya türbülans öncesi kemerin bele bağlanması.',
    examples: [
      { en: '"Please fasten your seatbelt and stow your tray table."', tr: '"Lütfen kemerinizi bağlayın ve tepsinizi kapatın."' },
      { en: 'The seatbelt sign is on.', tr: 'Kemer takın işareti yanıyor.' },
    ],
    relatedTerms: ['seatbelt sign', 'turbulence', 'safety brief'],
  },
  { id: 'voc_cabin_003', term: 'welcome aboard', termTr: 'hoş geldiniz', pronunciation: '/ˈwel.kəm əˈbɔːd/', category: 'pa_announcement', difficulty: 1,
    definitionEn: 'Standard greeting used in PA announcements when passengers board.',
    definitionTr: 'Yolcular bindiğinde PA anonslarında kullanılan standart selamlama.',
    examples: [
      { en: 'Welcome aboard flight TK1234 to Istanbul.', tr: 'TK1234 İstanbul uçuşumuza hoş geldiniz.' },
      { en: 'On behalf of Captain, welcome aboard.', tr: 'Kaptan adına, hoş geldiniz.' },
    ],
    relatedTerms: ['boarding announcement', 'PA', 'departure'],
  },
  { id: 'voc_cabin_004', term: 'seatbelt sign', termTr: 'kemer takın işareti', pronunciation: '/ˈsiːt.belt saɪn/', category: 'cabin_signage', difficulty: 1,
    definitionEn: 'Illuminated sign indicating passengers must remain seated with seatbelts fastened.',
    definitionTr: 'Yolcuların oturup kemer bağlamaları gerektiğini gösteren ışıklı işaret.',
    examples: [
      { en: 'The seatbelt sign is now off.', tr: 'Kemer işareti şimdi kapatıldı.' },
      { en: 'Captain has turned on the seatbelt sign.', tr: 'Kaptan kemer işaretini açtı.' },
    ],
    relatedTerms: ['no smoking sign', 'turbulence', 'cabin signage'],
  },
  { id: 'voc_cabin_005', term: 'tray table', termTr: 'açılır masa', pronunciation: '/treɪ ˈteɪ.bəl/', category: 'cabin_equipment', difficulty: 1,
    definitionEn: 'A small folding table at each seat used during meal service.',
    definitionTr: 'Her koltukta yemek servisinde kullanılan küçük açılır masa.',
    examples: [
      { en: 'Stow your tray table for landing.', tr: 'İniş için tepsinizi kapatın.' },
      { en: 'Tray tables in upright position.', tr: 'Tepsiler dik pozisyonda.' },
    ],
    relatedTerms: ['seat back', 'meal service', 'upright position'],
  },
  { id: 'voc_cabin_006', term: 'overhead bin', termTr: 'üst dolap', pronunciation: '/ˌəʊ.vəˈhed bɪn/', category: 'cabin_equipment', difficulty: 1,
    definitionEn: 'Storage compartment above passenger seats for carry-on luggage.',
    definitionTr: 'Yolcu koltuklarının üstünde el bagajı için depolama bölmesi.',
    examples: [
      { en: 'Place your bag in the overhead bin.', tr: 'Çantanı üst dolaba koy.' },
      { en: 'Items in overhead bins may shift.', tr: 'Üst dolaplardaki eşyalar kayabilir.' },
    ],
    relatedTerms: ['carry-on', 'compartment', 'storage'],
  },
  { id: 'voc_cabin_007', term: 'duty-free', termTr: 'gümrüksüz satış', pronunciation: '/ˌdjuː.tiˈfriː/', category: 'service', difficulty: 2,
    definitionEn: 'Goods sold on board without import duties.',
    definitionTr: 'Uçakta gümrük vergisi olmadan satılan ürünler.',
    examples: [
      { en: 'Duty-free trolley starting service.', tr: 'Duty-free arabası servise başlıyor.' },
      { en: 'Pre-order duty-free online.', tr: 'Online duty-free ön sipariş.' },
    ],
    relatedTerms: ['trolley', 'shopping', 'pre-order'],
  },
  { id: 'voc_cabin_008', term: 'transit passenger', termTr: 'aktarmalı yolcu', pronunciation: '/ˈtræn.zɪt ˈpæs.ən.dʒər/', category: 'passenger', difficulty: 2,
    definitionEn: 'A passenger continuing to another flight from the same airport.',
    definitionTr: 'Aynı havalimanından başka uçuşa devam eden yolcu.',
    examples: [
      { en: 'Transit passengers, please remain seated.', tr: 'Transit yolcular lütfen yerinde kalın.' },
      { en: 'Transit visa requirements vary by country.', tr: 'Transit vize şartları ülkeye göre değişir.' },
    ],
    relatedTerms: ['transfer', 'connecting flight', 'layover'],
  },
  { id: 'voc_cabin_009', term: 'baggage claim', termTr: 'bagaj alımı', pronunciation: '/ˈbæɡ.ɪdʒ kleɪm/', category: 'arrival', difficulty: 1,
    definitionEn: 'The area where passengers retrieve their checked baggage after a flight.',
    definitionTr: 'Yolcuların uçuştan sonra check-in bagajlarını aldığı alan.',
    examples: [
      { en: 'Baggage claim is on the lower level.', tr: 'Bagaj alımı alt katta.' },
      { en: 'Carousel 5 for flight TK1234.', tr: 'TK1234 uçuşu için bant 5.' },
    ],
    relatedTerms: ['checked baggage', 'carousel', 'arrival'],
  },
  { id: 'voc_cabin_010', term: 'arrival announcement', termTr: 'varış anonsu', pronunciation: '/əˈraɪ.vəl əˈnaʊns.mənt/', category: 'pa_announcement', difficulty: 2,
    definitionEn: 'PA broadcast informing passengers of arrival details.',
    definitionTr: 'Yolculara varış detaylarını bildiren PA yayını.',
    examples: [
      { en: 'We have started our descent into Istanbul.', tr: 'İstanbul\'a alçalmaya başladık.' },
      { en: 'Local time is 14:30.', tr: 'Yerel saat 14:30.' },
    ],
    relatedTerms: ['descent', 'local time', 'destination'],
  },
  { id: 'voc_cabin_011', term: 'PA system', termTr: 'PA (anons sistemi)', pronunciation: '/ˌpiː ˈeɪ ˈsɪs.təm/', category: 'cabin_equipment', difficulty: 2,
    definitionEn: 'Public Address system used to make announcements to passengers.',
    definitionTr: 'Yolculara anons yapmak için kullanılan Public Address sistemi.',
    examples: [
      { en: 'Test the PA before departure.', tr: 'Kalkıştan önce PA\'yı test et.' },
      { en: 'Speak slowly on the PA.', tr: 'PA\'da yavaş konuş.' },
    ],
    relatedTerms: ['announcement', 'microphone', 'broadcast'],
  },
  { id: 'voc_cabin_012', term: 'jet bridge', termTr: 'körük (jetbridge)', pronunciation: '/dʒet brɪdʒ/', category: 'arrival', difficulty: 2,
    definitionEn: 'Movable enclosed walkway connecting the airport gate to the aircraft door.',
    definitionTr: 'Havaalanı gate\'ini uçak kapısına bağlayan hareketli kapalı yürüyüş yolu.',
    examples: [
      { en: 'Jet bridge connecting to door 1L.', tr: 'Jet bridge 1L kapısına bağlandı.' },
      { en: 'Disembark via jet bridge.', tr: 'Jet bridge\'den iniş.' },
    ],
    relatedTerms: ['airbridge', 'gate', 'disembark'],
  },

  // ===== EMERGENCY & SAFETY (12) =====
  { id: 'voc_cabin_013', term: 'evacuation slide', termTr: 'tahliye kaydırağı', pronunciation: '/ɪˌvæk.juˈeɪ.ʃən slaɪd/', category: 'emergency', difficulty: 3,
    definitionEn: 'An inflatable slide deployed during emergency evacuation.',
    definitionTr: 'Acil durum tahliyesinde açılan şişme kaydırak.',
    examples: [
      { en: 'Doors armed: slides will deploy if opened.', tr: 'Kapılar kuruldu: açılırsa kaydıraklar şişer.' },
      { en: 'Inspect slide before each flight.', tr: 'Her uçuş öncesi kaydırağı kontrol et.' },
    ],
    relatedTerms: ['doors armed', 'evacuation', 'emergency exit'],
  },
  { id: 'voc_cabin_014', term: 'emergency exit', termTr: 'acil çıkış', pronunciation: '/ɪˈmɜː.dʒən.si ˈek.sɪt/', category: 'emergency', difficulty: 2,
    definitionEn: 'A door designated for emergency egress from the aircraft.',
    definitionTr: 'Uçaktan acil çıkış için tasarlanmış kapı.',
    examples: [
      { en: 'Locate your nearest emergency exit.', tr: 'En yakın acil çıkışı belirleyin.' },
      { en: 'Exit row passengers must be physically able.', tr: 'Çıkış sırası yolcular fiziksel yetkin olmalı.' },
    ],
    relatedTerms: ['exit row', 'overwing exit', 'evacuation'],
  },
  { id: 'voc_cabin_015', term: 'life vest', termTr: 'can yeleği', pronunciation: '/laɪf vest/', category: 'emergency', difficulty: 2,
    definitionEn: 'Personal flotation device worn during water landings.',
    definitionTr: 'Suya iniş sırasında giyilen kişisel yüzdürme cihazı.',
    examples: [
      { en: 'Life vests under your seat.', tr: 'Can yelekleri koltuğunuzun altında.' },
      { en: 'Pull tabs to inflate.', tr: 'Şişirmek için ipi çekin.' },
    ],
    relatedTerms: ['ditching', 'inflate', 'flotation'],
  },
  { id: 'voc_cabin_016', term: 'oxygen mask', termTr: 'oksijen maskesi', pronunciation: '/ˈɒk.sɪ.dʒən mɑːsk/', category: 'emergency', difficulty: 2,
    definitionEn: 'Breathing apparatus deployed from overhead during depressurization.',
    definitionTr: 'Basınç kaybında tavandan inen solunum cihazı.',
    examples: [
      { en: 'Pull mask towards you to start oxygen flow.', tr: 'Maskeyi kendinize çekin.' },
      { en: 'Secure your mask before assisting others.', tr: 'Önce kendi maskenizi takın.' },
    ],
    relatedTerms: ['depressurization', 'cabin pressure', 'emergency descent'],
  },
  { id: 'voc_cabin_017', term: 'brace position', termTr: 'sarılma pozisyonu', pronunciation: '/breɪs pəˈzɪʃ.ən/', category: 'emergency', difficulty: 3,
    definitionEn: 'Defensive body posture before impact or crash landing.',
    definitionTr: 'Çarpma veya acil iniş öncesi savunma pozisyonu.',
    examples: [
      { en: '"Brace! Brace! Brace!"', tr: '"Sarıl! Sarıl! Sarıl!"' },
      { en: 'Demonstrate brace in safety briefing.', tr: 'Emniyet brifinginde brace göster.' },
    ],
    icaoReference: 'ICAO Doc 9683',
    relatedTerms: ['impact', 'crash landing', 'evacuation'],
  },
  { id: 'voc_cabin_018', term: 'doors armed', termTr: 'kapılar kuruldu', pronunciation: '/dɔːrz ɑːmd/', category: 'safety', difficulty: 2,
    definitionEn: 'Cabin door state where evacuation slides will deploy automatically if opened.',
    definitionTr: 'Açılırsa tahliye kaydıraklarının otomatik şişeceği kapı durumu.',
    examples: [
      { en: '"Cabin crew, doors to automatic and cross check."', tr: '"Kabin ekibi, kapılar otomatiğe ve çapraz kontrol."' },
      { en: 'Disarm doors before disembarking.', tr: 'İniş öncesi kapıları manuele al.' },
    ],
    relatedTerms: ['cross check', 'disarm', 'evacuation slide'],
  },
  { id: 'voc_cabin_019', term: 'cross check', termTr: 'çapraz kontrol', pronunciation: '/krɒs tʃek/', category: 'safety', difficulty: 2,
    definitionEn: 'Verification that another crew member has confirmed your action.',
    definitionTr: 'Bir başka ekip üyesinin senin aksiyonunu doğrulaması.',
    examples: [
      { en: '"Cross check completed, all doors armed."', tr: '"Çapraz kontrol tamam, tüm kapılar kuruldu."' },
      { en: 'Cross check critical safety actions.', tr: 'Kritik emniyet aksiyonlarını çapraz kontrol et.' },
    ],
    relatedTerms: ['doors armed', 'verification', 'CRM'],
  },
  { id: 'voc_cabin_020', term: 'fire extinguisher', termTr: 'yangın söndürücü', pronunciation: '/faɪər ɪkˈstɪŋ.ɡwɪ.ʃər/', category: 'emergency', difficulty: 2,
    definitionEn: 'Portable device used to put out small fires on board.',
    definitionTr: 'Uçakta küçük yangınları söndürmek için kullanılan taşınabilir cihaz.',
    examples: [
      { en: 'BCF extinguisher for galley fires.', tr: 'Galley yangınları için BCF söndürücü.' },
      { en: 'Water extinguisher: combustibles only.', tr: 'Sulu söndürücü: sadece yanıcılar.' },
    ],
    relatedTerms: ['BCF', 'fire drill', 'smoke hood'],
  },
  { id: 'voc_cabin_021', term: 'AED', termTr: 'AED (defibrilatör)', pronunciation: '/ˌeɪ iː ˈdiː/', category: 'emergency', difficulty: 3,
    definitionEn: 'Automated External Defibrillator — used in cardiac emergencies.',
    definitionTr: 'Automated External Defibrillator — kalp acillerinde kullanılır.',
    examples: [
      { en: 'AED located in forward galley.', tr: 'AED ön galley\'de.' },
      { en: 'Annual AED training mandatory.', tr: 'Yıllık AED eğitimi zorunlu.' },
    ],
    relatedTerms: ['cardiac arrest', 'first aid', 'medical emergency'],
  },
  { id: 'voc_cabin_022', term: 'first aid kit', termTr: 'ilk yardım çantası', pronunciation: '/fɜːst eɪd kɪt/', category: 'emergency', difficulty: 2,
    definitionEn: 'Container with basic medical supplies for in-flight emergencies.',
    definitionTr: 'Uçuş içi aciller için temel tıbbi malzemeler içeren çanta.',
    examples: [
      { en: 'First aid kit in overhead compartment.', tr: 'İlk yardım çantası tavan bölmesinde.' },
      { en: 'Check kit contents pre-flight.', tr: 'Uçuş öncesi çanta içeriğini kontrol et.' },
    ],
    relatedTerms: ['EMK', 'AED', 'medical emergency'],
  },
  { id: 'voc_cabin_023', term: 'smoke hood', termTr: 'duman maskesi', pronunciation: '/sməʊk hʊd/', category: 'emergency', difficulty: 3,
    definitionEn: 'Protective hood worn by crew when fighting cabin fires.',
    definitionTr: 'Kabin yangınlarında ekip tarafından kullanılan koruyucu başlık.',
    examples: [
      { en: 'Don smoke hood before approaching fire.', tr: 'Yangına yaklaşmadan duman maskesi tak.' },
      { en: '15-minute oxygen supply.', tr: '15 dakikalık oksijen.' },
    ],
    relatedTerms: ['fire fighting', 'PBE', 'oxygen'],
  },
  { id: 'voc_cabin_024', term: 'emergency lighting', termTr: 'acil aydınlatma', pronunciation: '/ɪˈmɜː.dʒən.si ˈlaɪ.tɪŋ/', category: 'emergency', difficulty: 3,
    definitionEn: 'Floor-path lighting that activates during emergencies for evacuation.',
    definitionTr: 'Acillerde tahliye için aktif olan zemin aydınlatması.',
    examples: [
      { en: 'Floor path lights guide to nearest exit.', tr: 'Zemin ışıkları en yakın çıkışa yönlendirir.' },
      { en: 'Emergency lighting on backup battery.', tr: 'Acil aydınlatma yedek bataryada.' },
    ],
    relatedTerms: ['floor path', 'evacuation', 'exit sign'],
  },

  // ===== GALLEY & SERVICE (10) =====
  { id: 'voc_cabin_025', term: 'galley', termTr: 'galley (kabin mutfak)', pronunciation: '/ˈɡæl.i/', category: 'cabin_area', difficulty: 2,
    definitionEn: 'The kitchen area on an aircraft where food and drinks are prepared.',
    definitionTr: 'Uçak içi mutfak bölgesi.',
    examples: [
      { en: 'Coffee brewing in forward galley.', tr: 'Ön galley\'de kahve hazırlanıyor.' },
      { en: 'Trolleys stored in galley.', tr: 'Trolley\'ler galley\'de saklanır.' },
    ],
    relatedTerms: ['trolley', 'oven', 'jumpseat'],
  },
  { id: 'voc_cabin_026', term: 'trolley', termTr: 'trolley (servis arabası)', pronunciation: '/ˈtrɒl.i/', category: 'cabin_equipment', difficulty: 2,
    definitionEn: 'A wheeled cart used to serve food and beverages to passengers.',
    definitionTr: 'Yolculara yemek ve içecek servisi için tekerlekli araba.',
    examples: [
      { en: 'Push trolley down the aisle.', tr: 'Trolley\'i koridordan it.' },
      { en: 'Lock trolley brake before service.', tr: 'Servis öncesi trolley frenini kilitle.' },
    ],
    relatedTerms: ['galley', 'cart', 'aisle'],
  },
  { id: 'voc_cabin_027', term: 'meal service', termTr: 'yemek servisi', pronunciation: '/miːl ˈsɜː.vɪs/', category: 'service', difficulty: 1,
    definitionEn: 'The distribution of meals to passengers during a flight.',
    definitionTr: 'Uçuş sırasında yolculara yemek dağıtımı.',
    examples: [
      { en: 'Meal service starts after cruise altitude.', tr: 'Yemek servisi seyir irtifasından sonra başlar.' },
      { en: 'Special meals served first.', tr: 'Özel yemekler önce servis edilir.' },
    ],
    relatedTerms: ['galley', 'special meal', 'service'],
  },
  { id: 'voc_cabin_028', term: 'special meal', termTr: 'özel yemek', pronunciation: '/ˈspeʃ.əl miːl/', category: 'service', difficulty: 2,
    definitionEn: 'Pre-ordered meals for dietary, religious, or medical needs.',
    definitionTr: 'Diyet, dini veya tıbbi ihtiyaçlar için önceden sipariş edilen yemekler.',
    examples: [
      { en: 'VGML = vegetarian meal, KSML = kosher.', tr: 'VGML = vejetaryen, KSML = koşer.' },
      { en: 'Confirm special meals during pre-flight.', tr: 'Uçuş öncesi özel yemekleri onayla.' },
    ],
    relatedTerms: ['VGML', 'KSML', 'HNML', 'CHML'],
  },
  { id: 'voc_cabin_029', term: 'beverage service', termTr: 'içecek servisi', pronunciation: '/ˈbev.ər.ɪdʒ ˈsɜː.vɪs/', category: 'service', difficulty: 1,
    definitionEn: 'Distribution of drinks (water, juice, soft drinks, alcohol) to passengers.',
    definitionTr: 'Yolculara içecek (su, meyve suyu, alkollü) dağıtımı.',
    examples: [
      { en: 'Beverage cart in the aisle.', tr: 'İçecek arabası koridorda.' },
      { en: 'Limit alcohol per passenger.', tr: 'Yolcu başına alkolü sınırla.' },
    ],
    relatedTerms: ['cart', 'cocktail', 'water'],
  },
  { id: 'voc_cabin_030', term: 'crew rest', termTr: 'ekip dinlenme alanı', pronunciation: '/kruː rest/', category: 'cabin_area', difficulty: 3,
    definitionEn: 'Designated rest area for crew on long-haul flights.',
    definitionTr: 'Uzun mesafe uçuşlarda ekip için dinlenme alanı.',
    examples: [
      { en: 'Crew rest is mandatory after 12+ hour flights.', tr: '12+ saat uçuşlarda crew rest zorunlu.' },
      { en: 'Bunk beds in upper deck.', tr: 'Üst güvertede ranza yatak.' },
    ],
    relatedTerms: ['bunk', 'duty time', 'rest period'],
  },
  { id: 'voc_cabin_031', term: 'jumpseat', termTr: 'jumpseat (ekip koltuğu)', pronunciation: '/ˈdʒʌmp.siːt/', category: 'cabin_equipment', difficulty: 2,
    definitionEn: 'Folding seat used by cabin crew during takeoff and landing.',
    definitionTr: 'Kabin ekibinin kalkış ve inişte oturduğu katlanır koltuk.',
    examples: [
      { en: 'Take your jumpseat.', tr: 'Jumpseat\'inize geçin.' },
      { en: 'Jumpseat near each emergency exit.', tr: 'Her acil çıkış yanında jumpseat.' },
    ],
    relatedTerms: ['takeoff position', 'flight attendant', 'cabin crew'],
  },
  { id: 'voc_cabin_032', term: 'aisle', termTr: 'koridor', pronunciation: '/aɪl/', category: 'cabin_area', difficulty: 1,
    definitionEn: 'Walkway between rows of seats in the passenger cabin.',
    definitionTr: 'Yolcu kabininde koltuk sıraları arasındaki yürüyüş yolu.',
    examples: [
      { en: 'Keep aisle clear during turbulence.', tr: 'Türbülansta koridoru boş tut.' },
      { en: 'Aisle seat preferred.', tr: 'Koridor koltuğu tercih edilir.' },
    ],
    relatedTerms: ['window seat', 'middle seat', 'row'],
  },
  { id: 'voc_cabin_033', term: 'galley equipment', termTr: 'galley ekipmanı', pronunciation: '/ˈɡæl.i ɪˈkwɪp.mənt/', category: 'cabin_equipment', difficulty: 2,
    definitionEn: 'Items in galley: ovens, coffee makers, water boilers, refrigerators.',
    definitionTr: 'Galley\'deki ekipmanlar: fırın, kahve makinesi, su ısıtıcısı, buzdolabı.',
    examples: [
      { en: 'Check galley equipment before flight.', tr: 'Uçuş öncesi galley ekipmanını kontrol et.' },
      { en: 'Galley power off for landing.', tr: 'İniş için galley elektriği kesik.' },
    ],
    relatedTerms: ['oven', 'coffee maker', 'water boiler'],
  },
  { id: 'voc_cabin_034', term: 'catering', termTr: 'catering (yemek hazırlığı)', pronunciation: '/ˈkeɪ.tər.ɪŋ/', category: 'service', difficulty: 2,
    definitionEn: 'Loading prepared meals onto the aircraft before each flight.',
    definitionTr: 'Her uçuş öncesi hazırlanmış yemeklerin uçağa yüklenmesi.',
    examples: [
      { en: 'Catering loaded 1 hour before departure.', tr: 'Catering kalkıştan 1 saat önce yüklendi.' },
      { en: 'Inspect catering for completeness.', tr: 'Catering\'i eksiksiz olduğu için kontrol et.' },
    ],
    relatedTerms: ['galley loading', 'meal count', 'special meal'],
  },

  // ===== SPECIAL PASSENGERS (8) =====
  { id: 'voc_cabin_035', term: 'unruly passenger', termTr: 'uyumsuz yolcu', pronunciation: '/ʌnˈruː.li ˈpæs.ən.dʒər/', category: 'passenger', difficulty: 3,
    definitionEn: 'A passenger whose behavior threatens flight safety, order, or discipline.',
    definitionTr: 'Davranışı uçuş emniyetini tehdit eden yolcu.',
    examples: [
      { en: 'File unruly passenger report.', tr: 'Uyumsuz yolcu raporu doldur.' },
      { en: 'De-escalate before restraint.', tr: 'Müdahaleden önce yatıştır.' },
    ],
    icaoReference: 'ICAO Annex 9 + Tokyo Convention',
    relatedTerms: ['de-escalation', 'restraint', 'incident report'],
  },
  { id: 'voc_cabin_036', term: 'unaccompanied minor', termTr: 'eşliksiz çocuk (UM)', pronunciation: '/ʌn.əˈkʌm.pə.nid ˈmaɪ.nər/', category: 'passenger', difficulty: 3,
    definitionEn: 'A child traveling alone, requiring special supervision by airline staff.',
    definitionTr: 'Tek başına seyahat eden, havayolu personeli tarafından özel gözetim gerektiren çocuk.',
    examples: [
      { en: 'UM service available 5-12 years.', tr: 'UM servisi 5-12 yaş.' },
      { en: 'Hand UM to authorized adult only.', tr: 'UM\'i sadece yetkili yetişkine teslim et.' },
    ],
    relatedTerms: ['SSR', 'guardian', 'age restriction'],
  },
  { id: 'voc_cabin_037', term: 'medical case', termTr: 'tıbbi durum (MEDA)', pronunciation: '/ˈmed.ɪ.kəl keɪs/', category: 'passenger', difficulty: 3,
    definitionEn: 'A passenger requiring medical clearance or special handling.',
    definitionTr: 'Tıbbi izin veya özel işlem gerektiren yolcu.',
    examples: [
      { en: 'MEDA requires MEDIF form.', tr: 'MEDA için MEDIF formu gerekli.' },
      { en: 'Brief crew on MEDA passenger.', tr: 'MEDA yolcu için ekibi brief et.' },
    ],
    relatedTerms: ['MEDIF', 'wheelchair', 'oxygen'],
  },
  { id: 'voc_cabin_038', term: 'wheelchair', termTr: 'tekerlekli sandalye', pronunciation: '/ˈwiːl.tʃeər/', category: 'passenger', difficulty: 2,
    definitionEn: 'Special service for passengers with mobility limitations.',
    definitionTr: 'Hareket kısıtlılığı olan yolcular için özel servis.',
    examples: [
      { en: 'WCHR: walks short distance.', tr: 'WCHR: kısa mesafe yürür.' },
      { en: 'WCHC: completely immobile.', tr: 'WCHC: tamamen hareketsiz.' },
    ],
    relatedTerms: ['WCHR', 'WCHS', 'WCHC', 'PRM'],
  },
  { id: 'voc_cabin_039', term: 'inadmissible passenger', termTr: 'kabul edilmeyen yolcu (INAD)', pronunciation: '/ˌɪn.ədˈmɪs.ɪ.bəl/', category: 'passenger', difficulty: 4,
    definitionEn: 'A passenger denied entry by destination authorities, must be returned.',
    definitionTr: 'Hedef otoriteleri tarafından girişi reddedilen, geri gönderilmesi gereken yolcu.',
    examples: [
      { en: 'INAD: no valid visa.', tr: 'INAD: geçerli vize yok.' },
      { en: 'Airline must repatriate INAD.', tr: 'Havayolu INAD\'ı geri göndermeli.' },
    ],
    relatedTerms: ['DEPU', 'visa', 'repatriation'],
  },
  { id: 'voc_cabin_040', term: 'deportee', termTr: 'sınır dışı edilen (DEPU)', pronunciation: '/ˌdiː.pɔːˈtiː/', category: 'passenger', difficulty: 4,
    definitionEn: 'Person being removed from a country by official order.',
    definitionTr: 'Resmi karar ile bir ülkeden çıkarılan kişi.',
    examples: [
      { en: 'DEPU may require security escort.', tr: 'DEPU güvenlik eskortu gerektirebilir.' },
      { en: 'DEPA: accompanied; DEPU: unaccompanied.', tr: 'DEPA: eşlikli; DEPU: eşliksiz.' },
    ],
    relatedTerms: ['INAD', 'security escort', 'repatriation'],
  },
  { id: 'voc_cabin_041', term: 'special service request', termTr: 'özel servis talebi (SSR)', pronunciation: '/ˈspeʃ.əl ˈsɜː.vɪs rɪˈkwest/', category: 'passenger', difficulty: 3,
    definitionEn: 'Coded request for special needs (UM, MEDA, special meal, etc.).',
    definitionTr: 'Özel ihtiyaç için kodlu talep (UM, MEDA, özel yemek vb.).',
    examples: [
      { en: 'Check SSR list pre-flight.', tr: 'Uçuş öncesi SSR listesini kontrol et.' },
      { en: 'Today: 2 WCHR, 1 UM, 1 MEDA.', tr: 'Bugün: 2 WCHR, 1 UM, 1 MEDA.' },
    ],
    icaoReference: 'IATA SSR codes',
    relatedTerms: ['UM', 'MEDA', 'VGML', 'WCHR'],
  },
  { id: 'voc_cabin_042', term: 'vegetarian meal', termTr: 'vejetaryen yemek (VGML)', pronunciation: '/ˌvedʒ.ɪˈteər.i.ən miːl/', category: 'service', difficulty: 2,
    definitionEn: 'Pre-ordered vegetarian meal (VGML) — no meat, may include dairy/eggs.',
    definitionTr: 'Önceden sipariş vejetaryen yemek (VGML) — etsiz, süt/yumurta olabilir.',
    examples: [
      { en: 'VGML loaded for seat 12B.', tr: 'VGML koltuk 12B için yüklendi.' },
      { en: 'VGOR: strict vegan.', tr: 'VGOR: katı vegan.' },
    ],
    relatedTerms: ['special meal', 'KSML', 'HNML', 'VGOR'],
  },

  // ===== PILOT-CABIN COORDINATION (5) =====
  { id: 'voc_cabin_043', term: 'cabin secure', termTr: 'kabin emniyetli', pronunciation: '/ˈkæb.ɪn sɪˈkjʊər/', category: 'coordination', difficulty: 2,
    definitionEn: 'Confirmation that the cabin is ready and safe for takeoff or landing.',
    definitionTr: 'Kabinin kalkış veya inişe hazır ve emniyetli olduğunun teyidi.',
    examples: [
      { en: '"Captain, cabin secure."', tr: '"Kaptan, kabin emniyetli."' },
      { en: 'All seatbelts checked, doors armed.', tr: 'Tüm kemerler kontrollü, kapılar kuruldu.' },
    ],
    relatedTerms: ['ready for takeoff', 'cross check', 'doors armed'],
  },
  { id: 'voc_cabin_044', term: 'interphone', termTr: 'interphone (kabinler arası)', pronunciation: '/ˈɪn.tər.fəʊn/', category: 'coordination', difficulty: 2,
    definitionEn: 'Internal communication system between cockpit and cabin.',
    definitionTr: 'Kokpit ile kabin arasındaki iç iletişim sistemi.',
    examples: [
      { en: 'Interphone call from cabin.', tr: 'Kabinden interphone çağrısı.' },
      { en: 'Captain calling cabin manager.', tr: 'Kaptan kabin amirini arıyor.' },
    ],
    relatedTerms: ['all-call', 'PA', 'flight deck'],
  },
  { id: 'voc_cabin_045', term: 'all-call', termTr: 'all-call (tüm ekip)', pronunciation: '/ɔːl kɔːl/', category: 'coordination', difficulty: 2,
    definitionEn: 'Interphone signal that calls all flight attendants simultaneously.',
    definitionTr: 'Tüm hostesleri aynı anda çağıran interphone sinyali.',
    examples: [
      { en: 'Captain initiated all-call.', tr: 'Kaptan all-call başlattı.' },
      { en: 'All-call for emergency briefing.', tr: 'Acil brifing için all-call.' },
    ],
    relatedTerms: ['interphone', 'emergency', 'briefing'],
  },
  { id: 'voc_cabin_046', term: 'cabin manager', termTr: 'kabin amiri (purser)', pronunciation: '/ˈkæb.ɪn ˈmæn.ɪ.dʒər/', category: 'staff', difficulty: 2,
    definitionEn: 'Senior cabin crew member responsible for cabin operations.',
    definitionTr: 'Kabin operasyonlarından sorumlu kıdemli kabin ekibi üyesi.',
    examples: [
      { en: 'Purser briefs cabin crew pre-flight.', tr: 'Purser uçuş öncesi ekibi brief eder.' },
      { en: 'Cabin manager reports to captain.', tr: 'Kabin amiri kaptana rapor verir.' },
    ],
    relatedTerms: ['purser', 'lead flight attendant', 'CSM'],
  },
  { id: 'voc_cabin_047', term: 'pre-flight briefing', termTr: 'uçuş öncesi brifingi', pronunciation: '/priː flaɪt ˈbriː.fɪŋ/', category: 'coordination', difficulty: 2,
    definitionEn: 'Briefing before each flight covering safety, weather, special handling.',
    definitionTr: 'Her uçuş öncesi emniyet, hava, özel işlem konularını içeren brifing.',
    examples: [
      { en: 'Briefing 1 hour before departure.', tr: 'Brifing kalkıştan 1 saat önce.' },
      { en: 'Captain leads briefing.', tr: 'Brifingi kaptan yönetir.' },
    ],
    relatedTerms: ['safety brief', 'flight plan', 'crew brief'],
  },

  // ===== INTERVIEW & INDUSTRY (8) =====
  { id: 'voc_cabin_048', term: 'competency-based interview', termTr: 'yetkinlik bazlı mülakat', pronunciation: '/ˈkɒm.pɪ.tən.si beɪst ˈɪn.tər.vjuː/', category: 'interview', difficulty: 3,
    definitionEn: 'Interview format using behavioral questions to assess competencies.',
    definitionTr: 'Yetkinlikleri ölçmek için davranışsal sorular kullanan mülakat formatı.',
    examples: [
      { en: '"Tell me about a time you handled conflict."', tr: '"Çatışmayı yönettiğin bir zamanı anlat."' },
      { en: 'STAR method: Situation, Task, Action, Result.', tr: 'STAR yöntemi: Durum, Görev, Aksiyon, Sonuç.' },
    ],
    relatedTerms: ['STAR method', 'behavioral question', 'assessment'],
  },
  { id: 'voc_cabin_049', term: 'group exercise', termTr: 'grup egzersizi', pronunciation: '/ɡruːp ˈek.sə.saɪz/', category: 'interview', difficulty: 3,
    definitionEn: 'Assessment center activity testing teamwork and leadership.',
    definitionTr: 'Takım çalışması ve liderlik testi için değerlendirme merkezi aktivitesi.',
    examples: [
      { en: 'Group of 6 candidates solve a scenario.', tr: '6 aday bir senaryo çözer.' },
      { en: 'Show leadership without dominating.', tr: 'Baskın olmadan liderlik göster.' },
    ],
    relatedTerms: ['assessment center', 'role-play', 'teamwork'],
  },
  { id: 'voc_cabin_050', term: 'height and reach test', termTr: 'boy ve uzanma testi', pronunciation: '/haɪt ænd riːtʃ test/', category: 'interview', difficulty: 2,
    definitionEn: 'Physical test ensuring candidates can reach overhead bins.',
    definitionTr: 'Adayların üst dolaplara erişebildiğini doğrulayan fiziksel test.',
    examples: [
      { en: 'THY minimum: 165 cm without shoes.', tr: 'THY minimum: 165 cm ayakkabısız.' },
      { en: 'Reach 2.10 m on tiptoes.', tr: 'Parmak ucunda 2.10 m\'ye ulaş.' },
    ],
    relatedTerms: ['physical assessment', 'minimum height', 'BMI'],
  },
  { id: 'voc_cabin_051', term: 'customer service excellence', termTr: 'müşteri hizmet mükemmelliği', pronunciation: '/ˈkʌs.tə.mər ˈsɜː.vɪs ˈek.sə.ləns/', category: 'interview', difficulty: 2,
    definitionEn: 'Quality of service exceeding passenger expectations.',
    definitionTr: 'Yolcu beklentilerini aşan hizmet kalitesi.',
    examples: [
      { en: 'Anticipate passenger needs.', tr: 'Yolcu ihtiyaçlarını öngör.' },
      { en: 'Personalize service when possible.', tr: 'Mümkünse servisi kişiselleştir.' },
    ],
    relatedTerms: ['VIP service', 'hospitality', 'guest experience'],
  },
  { id: 'voc_cabin_052', term: 'grooming standards', termTr: 'görünüm standartları', pronunciation: '/ˈɡruː.mɪŋ ˈstæn.dədz/', category: 'interview', difficulty: 2,
    definitionEn: 'Strict appearance rules for cabin crew (uniform, hair, makeup).',
    definitionTr: 'Kabin ekibi için sıkı görünüm kuralları (üniforma, saç, makyaj).',
    examples: [
      { en: 'Hair tied, makeup natural.', tr: 'Saç toplu, makyaj doğal.' },
      { en: 'Visible tattoos not allowed.', tr: 'Görünür dövme yasak.' },
    ],
    relatedTerms: ['uniform', 'appearance', 'professional image'],
  },
  { id: 'voc_cabin_053', term: 'multilingual', termTr: 'çok dilli', pronunciation: '/ˌmʌl.tiˈlɪŋ.ɡwəl/', category: 'interview', difficulty: 2,
    definitionEn: 'Speaking multiple languages — competitive advantage for cabin crew.',
    definitionTr: 'Birden çok dil konuşma — kabin ekibi için rekabet avantajı.',
    examples: [
      { en: 'THY values multilingual candidates.', tr: 'THY çok dilli adayları değerli görür.' },
      { en: 'English required, Russian/Arabic preferred.', tr: 'İngilizce zorunlu, Rusça/Arapça tercih.' },
    ],
    relatedTerms: ['language proficiency', 'TOEIC', 'native speaker'],
  },
  { id: 'voc_cabin_054', term: 'roster', termTr: 'uçuş çizelgesi', pronunciation: '/ˈrɒs.tər/', category: 'work', difficulty: 2,
    definitionEn: 'Schedule of flights assigned to a crew member.',
    definitionTr: 'Bir ekip üyesine atanan uçuşların çizelgesi.',
    examples: [
      { en: 'Monthly roster published.', tr: 'Aylık roster yayınlandı.' },
      { en: 'Roster swap with colleague.', tr: 'Meslektaş ile roster değişimi.' },
    ],
    relatedTerms: ['duty', 'standby', 'rest period'],
  },
  { id: 'voc_cabin_055', term: 'standby duty', termTr: 'standby görevi', pronunciation: '/ˈstænd.baɪ ˈdjuː.ti/', category: 'work', difficulty: 3,
    definitionEn: 'On-call status: ready to fly within hours if assigned.',
    definitionTr: 'Çağrı üstü statü: atandığında saatler içinde uçmaya hazır.',
    examples: [
      { en: 'Standby duty: airport or home.', tr: 'Standby: havalimanında veya evde.' },
      { en: 'Maximum standby 12 hours.', tr: 'Maksimum standby 12 saat.' },
    ],
    relatedTerms: ['reserve', 'on-call', 'duty period'],
  },

  // ===== PASSENGER ANNOUNCEMENTS (5) =====
  { id: 'voc_cabin_056', term: 'safety demonstration', termTr: 'emniyet gösterimi', pronunciation: '/ˈseɪf.ti ˌdem.ənˈstreɪ.ʃən/', category: 'pa_announcement', difficulty: 2,
    definitionEn: 'Mandatory pre-flight demonstration of seatbelt, oxygen, life vest, exits.',
    definitionTr: 'Uçuş öncesi zorunlu kemer, oksijen, can yeleği, çıkış gösterimi.',
    examples: [
      { en: 'Watch the safety demonstration.', tr: 'Emniyet gösterimini izleyin.' },
      { en: 'Video or live demo accepted.', tr: 'Video veya canlı gösterim kabul edilir.' },
    ],
    relatedTerms: ['safety briefing', 'safety card', 'pre-flight'],
  },
  { id: 'voc_cabin_057', term: 'no smoking sign', termTr: 'sigara içilmez işareti', pronunciation: '/nəʊ ˈsməʊ.kɪŋ saɪn/', category: 'cabin_signage', difficulty: 1,
    definitionEn: 'Permanently illuminated sign — smoking prohibited on all flights.',
    definitionTr: 'Sürekli yanık işaret — tüm uçuşlarda sigara yasak.',
    examples: [
      { en: 'Federal law prohibits smoking.', tr: 'Federal yasa sigarayı yasaklar.' },
      { en: 'Smoking in lavatories triggers alarm.', tr: 'Tuvalette sigara alarmı tetikler.' },
    ],
    relatedTerms: ['lavatory', 'smoke detector', 'fine'],
  },
  { id: 'voc_cabin_058', term: 'electronic devices', termTr: 'elektronik cihazlar', pronunciation: '/ˌel.ekˈtrɒn.ɪk dɪˈvaɪs.ɪz/', category: 'pa_announcement', difficulty: 2,
    definitionEn: 'Phones, laptops, tablets — must be in flight mode for takeoff.',
    definitionTr: 'Telefon, laptop, tablet — kalkışta uçak modunda olmalı.',
    examples: [
      { en: 'Switch devices to airplane mode.', tr: 'Cihazları uçak moduna alın.' },
      { en: 'Larger devices stowed for takeoff.', tr: 'Büyük cihazlar kalkışta kapatılır.' },
    ],
    relatedTerms: ['airplane mode', 'PED', 'in-flight wifi'],
  },
  { id: 'voc_cabin_059', term: 'passenger manifest', termTr: 'yolcu listesi', pronunciation: '/ˈpæs.ən.dʒər ˈmæn.ɪ.fest/', category: 'documentation', difficulty: 3,
    definitionEn: 'Official document listing all passengers and crew on a flight.',
    definitionTr: 'Bir uçuştaki tüm yolcu ve ekibi listeleyen resmi belge.',
    examples: [
      { en: 'Manifest sent to authorities pre-flight.', tr: 'Manifesto uçuş öncesi yetkililere gönderilir.' },
      { en: 'Cross-check headcount with manifest.', tr: 'Sayımı manifesto ile çapraz kontrol et.' },
    ],
    relatedTerms: ['headcount', 'PNR', 'load sheet'],
  },
  { id: 'voc_cabin_060', term: 'turnaround', termTr: 'turnaround (hızlı dönüş)', pronunciation: '/ˈtɜːn.əˌraʊnd/', category: 'work', difficulty: 3,
    definitionEn: 'Process of preparing the aircraft for the next flight quickly.',
    definitionTr: 'Uçağı bir sonraki uçuş için hızla hazırlama süreci.',
    examples: [
      { en: 'Turnaround time: 30 minutes.', tr: 'Turnaround süresi: 30 dakika.' },
      { en: 'Quick turnaround on busy days.', tr: 'Yoğun günlerde hızlı turnaround.' },
    ],
    relatedTerms: ['transit', 'scheduled departure', 'block time'],
  },
];
