/**
 * Kabin Memuru vocabulary seed — Faz 1.
 * 60 terim: PA anonsları, emniyet, servis, yolcu tipi, koordinasyon, mülakat.
 */
import type { VocabularyTerm } from './pilotVocab';

export const CABIN_VOCAB_FAZ1: VocabularyTerm[] = [
  // ===== PA & PASSENGER COMMUNICATION (12) =====
  { id: 'voc_cabin_001', term: 'cabin crew', termTr: 'kabin ekibi', pronunciation: '/ˈkæb.ɪn kruː/', category: 'staff', difficulty: 1,
    definitionEn: 'The flight attendants and stewards working in the passenger cabin.',
    definitionTr: 'Yolcu kabininde çalışan hostes ve stewardlar.',
    examples: [
      { en: 'Cabin crew, prepare for departure.', tr: 'Kabin ekibi, kalkışa hazırlanın.' },
      { en: 'Our cabin crew speaks four languages.', tr: 'Kabin ekibimiz 4 dil konuşuyor.' },
    ],
    relatedTerms: ['flight attendant', 'purser', 'steward'],
  },
  { id: 'voc_cabin_002', term: 'fasten seatbelt', termTr: 'emniyet kemerini bağla', pronunciation: '/ˈfæs.ən ˈsiːt.belt/', category: 'safety', difficulty: 1,
    definitionEn: 'To secure the seatbelt across the lap before takeoff, landing, or turbulence.',
    definitionTr: 'Kalkış, iniş veya türbülans öncesi kemerin bele bağlanması.',
    examples: [
      { en: '"Please fasten your seatbelt and stow your tray table."', tr: '"Lütfen kemerinizi bağlayın ve tepsinizi kapatın."' },
      { en: 'The seatbelt sign is on.', tr: 'Kemer takın işareti yanıyor.' },
    ],
    relatedTerms: ['seatbelt sign', 'turbulence', 'safety brief'],
  },
  { id: 'voc_cabin_003', term: 'welcome aboard', termTr: 'hoş geldiniz', pronunciation: '/ˈwel.kəm əˈbɔːd/', category: 'pa_announcement', difficulty: 1,
    definitionEn: 'Standard greeting used in PA announcements when passengers board.',
    definitionTr: 'Yolcular bindiğinde PA anonslarında kullanılan standart selamlama.',
    examples: [
      { en: 'Welcome aboard flight TK1234 to Istanbul.', tr: 'TK1234 İstanbul uçuşumuza hoş geldiniz.' },
      { en: 'On behalf of Captain, welcome aboard.', tr: 'Kaptan adına, hoş geldiniz.' },
    ],
    relatedTerms: ['boarding announcement', 'PA', 'departure'],
  },
  { id: 'voc_cabin_004', term: 'seatbelt sign', termTr: 'kemer takın işareti', pronunciation: '/ˈsiːt.belt saɪn/', category: 'cabin_signage', difficulty: 1,
    definitionEn: 'Illuminated sign indicating passengers must remain seated with seatbelts fastened.',
    definitionTr: 'Yolcuların oturup kemer bağlamaları gerektiğini gösteren ışıklı işaret.',
    examples: [
      { en: 'The seatbelt sign is now off.', tr: 'Kemer işareti şimdi kapatıldı.' },
      { en: 'Captain has turned on the seatbelt sign.', tr: 'Kaptan kemer işaretini açtı.' },
    ],
    relatedTerms: ['no smoking sign', 'turbulence', 'cabin signage'],
  },
  { id: 'voc_cabin_005', term: 'tray table', termTr: 'açılır masa', pronunciation: '/treɪ ˈteɪ.bəl/', category: 'cabin_equipment', difficulty: 1,
    definitionEn: 'A small folding table at each seat used during meal service.',
    definitionTr: 'Her koltukta yemek servisinde kullanılan küçük açılır masa.',
    examples: [
      { en: 'Stow your tray table for landing.', tr: 'İniş için tepsinizi kapatın.' },
      { en: 'Tray tables in upright position.', tr: 'Tepsiler dik pozisyonda.' },
    ],
    relatedTerms: ['seat back', 'meal service', 'upright position'],
  },
  { id: 'voc_cabin_006', term: 'overhead bin', termTr: 'üst dolap', pronunciation: '/ˌəʊ.vəˈhed bɪn/', category: 'cabin_equipment', difficulty: 1,
    definitionEn: 'Storage compartment above passenger seats for carry-on luggage.',
    definitionTr: 'Yolcu koltuklarının üstünde el bagajı için depolama bölmesi.',
    examples: [
      { en: 'Place your bag in the overhead bin.', tr: 'Çantanı üst dolaba koy.' },
      { en: 'Items in overhead bins may shift.', tr: 'Üst dolaplardaki eşyalar kayabilir.' },
    ],
    relatedTerms: ['carry-on', 'compartment', 'storage'],
  },
  { id: 'voc_cabin_007', term: 'duty-free', termTr: 'gümrüksüz satış', pronunciation: '/ˌdjuː.tiˈfriː/', category: 'service', difficulty: 2,
    definitionEn: 'Goods sold on board without import duties.',
    definitionTr: 'Uçakta gümrük vergisi olmadan satılan ürünler.',
    examples: [
      { en: 'Duty-free trolley starting service.', tr: 'Duty-free arabası servise başlıyor.' },
      { en: 'Pre-order duty-free online.', tr: 'Online duty-free ön sipariş.' },
    ],
    relatedTerms: ['trolley', 'shopping', 'pre-order'],
  },
  { id: 'voc_cabin_008', term: 'transit passenger', termTr: 'aktarmalı yolcu', pronunciation: '/ˈtræn.zɪt ˈpæs.ən.dʒər/', category: 'passenger', difficulty: 2,
    definitionEn: 'A passenger continuing to another flight from the same airport.',
    definitionTr: 'Aynı havalimanından başka uçuşa devam eden yolcu.',
    examples: [
      { en: 'Transit passengers, please remain seated.', tr: 'Transit yolcular lütfen yerinde kalın.' },
      { en: 'Transit visa requirements vary by country.', tr: 'Transit vize şartları ülkeye göre değişir.' },
    ],
    relatedTerms: ['transfer', 'connecting flight', 'layover'],
  },
  { id: 'voc_cabin_009', term: 'baggage claim', termTr: 'bagaj alımı', pronunciation: '/ˈbæɡ.ɪdʒ kleɪm/', category: 'arrival', difficulty: 1,
    definitionEn: 'The area where passengers retrieve their checked baggage after a flight.',
    definitionTr: 'Yolcuların uçuştan sonra check-in bagajlarını aldığı alan.',
    examples: [
      { en: 'Baggage claim is on the lower level.', tr: 'Bagaj alımı alt katta.' },
      { en: 'Carousel 5 for flight TK1234.', tr: 'TK1234 uçuşu için bant 5.' },
    ],
    relatedTerms: ['checked baggage', 'carousel', 'arrival'],
  },
  { id: 'voc_cabin_010', term: 'arrival announcement', termTr: 'varış anonsu', pronunciation: '/əˈraɪ.vəl əˈnaʊns.mənt/', category: 'pa_announcement', difficulty: 2,
    definitionEn: 'PA broadcast informing passengers of arrival details.',
    definitionTr: 'Yolculara varış detaylarını bildiren PA yayını.',
    examples: [
      { en: 'We have started our descent into Istanbul.', tr: 'İstanbul\'a alçalmaya başladık.' },
      { en: 'Local time is 14:30.', tr: 'Yerel saat 14:30.' },
    ],
    relatedTerms: ['descent', 'local time', 'destination'],
  },
  { id: 'voc_cabin_011', term: 'PA system', termTr: 'PA (anons sistemi)', pronunciation: '/ˌpiː ˈeɪ ˈsɪs.təm/', category: 'cabin_equipment', difficulty: 2,
    definitionEn: 'Public Address system used to make announcements to passengers.',
    definitionTr: 'Yolculara anons yapmak için kullanılan Public Address sistemi.',
    examples: [
      { en: 'Test the PA before departure.', tr: 'Kalkıştan önce PA\'yı test et.' },
      { en: 'Speak slowly on the PA.', tr: 'PA\'da yavaş konuş.' },
    ],
    relatedTerms: ['announcement', 'microphone', 'broadcast'],
  },
  { id: 'voc_cabin_012', term: 'jet bridge', termTr: 'körük (jetbridge)', pronunciation: '/dʒet brɪdʒ/', category: 'arrival', difficulty: 2,
    definitionEn: 'Movable enclosed walkway connecting the airport gate to the aircraft door.',
    definitionTr: 'Havaalanı gate\'ini uçak kapısına bağlayan hareketli kapalı yürüyüş yolu.',
    examples: [
      { en: 'Jet bridge connecting to door 1L.', tr: 'Jet bridge 1L kapısına bağlandı.' },
      { en: 'Disembark via jet bridge.', tr: 'Jet bridge\'den iniş.' },
    ],
    relatedTerms: ['airbridge', 'gate', 'disembark'],
  },

  // ===== EMERGENCY & SAFETY (12) =====
  { id: 'voc_cabin_013', term: 'evacuation slide', termTr: 'tahliye kaydırağı', pronunciation: '/ɪˌvæk.juˈeɪ.ʃən slaɪd/', category: 'emergency', difficulty: 3,
    definitionEn: 'An inflatable slide deployed during emergency evacuation.',
    definitionTr: 'Acil durum tahliyesinde açılan şişme kaydırak.',
    examples: [
      { en: 'Doors armed: slides will deploy if opened.', tr: 'Kapılar kuruldu: açılırsa kaydıraklar şişer.' },
      { en: 'Inspect slide before each flight.', tr: 'Her uçuş öncesi kaydırağı kontrol et.' },
    ],
    relatedTerms: ['doors armed', 'evacuation', 'emergency exit'],
  },
  { id: 'voc_cabin_014', term: 'emergency exit', termTr: 'acil çıkış', pronunciation: '/ɪˈmɜː.dʒən.si ˈek.sɪt/', category: 'emergency', difficulty: 2,
    definitionEn: 'A door designated for emergency egress from the aircraft.',
    definitionTr: 'Uçaktan acil çıkış için tasarlanmış kapı.',
    examples: [
      { en: 'Locate your nearest emergency exit.', tr: 'En yakın acil çıkışı belirleyin.' },
      { en: 'Exit row passengers must be physically able.', tr: 'Çıkış sırası yolcular fiziksel yetkin olmalı.' },
    ],
    relatedTerms: ['exit row', 'overwing exit', 'evacuation'],
  },
  { id: 'voc_cabin_015', term: 'life vest', termTr: 'can yeleği', pronunciation: '/laɪf vest/', category: 'emergency', difficulty: 2,
    definitionEn: 'Personal flotation device worn during water landings.',
    definitionTr: 'Suya iniş sırasında giyilen kişisel yüzdürme cihazı.',
    examples: [
      { en: 'Life vests under your seat.', tr: 'Can yelekleri koltuğunuzun altında.' },
      { en: 'Pull tabs to inflate.', tr: 'Şişirmek için ipi çekin.' },
    ],
    relatedTerms: ['ditching', 'inflate', 'flotation'],
  },
  { id: 'voc_cabin_016', term: 'oxygen mask', termTr: 'oksijen maskesi', pronunciation: '/ˈɒk.sɪ.dʒən mɑːsk/', category: 'emergency', difficulty: 2,
    definitionEn: 'Breathing apparatus deployed from overhead during depressurization.',
    definitionTr: 'Basınç kaybında tavandan inen solunum cihazı.',
    examples: [
      { en: 'Pull mask towards you to start oxygen flow.', tr: 'Maskeyi kendinize çekin.' },
      { en: 'Secure your mask before assisting others.', tr: 'Önce kendi maskenizi takın.' },
    ],
    relatedTerms: ['depressurization', 'cabin pressure', 'emergency descent'],
  },
  { id: 'voc_cabin_017', term: 'brace position', termTr: 'sarılma pozisyonu', pronunciation: '/breɪs pəˈzɪʃ.ən/', category: 'emergency', difficulty: 3,
    definitionEn: 'Defensive body posture before impact or crash landing.',
    definitionTr: 'Çarpma veya acil iniş öncesi savunma pozisyonu.',
    examples: [
      { en: '"Brace! Brace! Brace!"', tr: '"Sarıl! Sarıl! Sarıl!"' },
      { en: 'Demonstrate brace in safety briefing.', tr: 'Emniyet brifinginde brace göster.' },
    ],
    icaoReference: 'ICAO Doc 9683',
    relatedTerms: ['impact', 'crash landing', 'evacuation'],
  },
  { id: 'voc_cabin_018', term: 'doors armed', termTr: 'kapılar kuruldu', pronunciation: '/dɔːrz ɑːmd/', category: 'safety', difficulty: 2,
    definitionEn: 'Cabin door state where evacuation slides will deploy automatically if opened.',
    definitionTr: 'Açılırsa tahliye kaydıraklarının otomatik şişeceği kapı durumu.',
    examples: [
      { en: '"Cabin crew, doors to automatic and cross check."', tr: '"Kabin ekibi, kapılar otomatiğe ve çapraz kontrol."' },
      { en: 'Disarm doors before disembarking.', tr: 'İniş öncesi kapıları manuele al.' },
    ],
    relatedTerms: ['cross check', 'disarm', 'evacuation slide'],
  },
  { id: 'voc_cabin_019', term: 'cross check', termTr: 'çapraz kontrol', pronunciation: '/krɒs tʃek/', category: 'safety', difficulty: 2,
    definitionEn: 'Verification that another crew member has confirmed your action.',
    definitionTr: 'Bir başka ekip üyesinin senin aksiyonunu doğrulaması.',
    examples: [
      { en: '"Cross check completed, all doors armed."', tr: '"Çapraz kontrol tamam, tüm kapılar kuruldu."' },
      { en: 'Cross check critical safety actions.', tr: 'Kritik emniyet aksiyonlarını çapraz kontrol et.' },
    ],
    relatedTerms: ['doors armed', 'verification', 'CRM'],
  },
  { id: 'voc_cabin_020', term: 'fire extinguisher', termTr: 'yangın söndürücü', pronunciation: '/faɪər ɪkˈstɪŋ.ɡwɪ.ʃər/', category: 'emergency', difficulty: 2,
    definitionEn: 'Portable device used to put out small fires on board.',
    definitionTr: 'Uçakta küçük yangınları söndürmek için kullanılan taşınabilir cihaz.',
    examples: [
      { en: 'BCF extinguisher for galley fires.', tr: 'Galley yangınları için BCF söndürücü.' },
      { en: 'Water extinguisher: combustibles only.', tr: 'Sulu söndürücü: sadece yanıcılar.' },
    ],
    relatedTerms: ['BCF', 'fire drill', 'smoke hood'],
  },
  { id: 'voc_cabin_021', term: 'AED', termTr: 'AED (defibrilatör)', pronunciation: '/ˌeɪ iː ˈdiː/', category: 'emergency', difficulty: 3,
    definitionEn: 'Automated External Defibrillator — used in cardiac emergencies.',
    definitionTr: 'Automated External Defibrillator — kalp acillerinde kullanılır.',
    examples: [
      { en: 'AED located in forward galley.', tr: 'AED ön galley\'de.' },
      { en: 'Annual AED training mandatory.', tr: 'Yıllık AED eğitimi zorunlu.' },
    ],
    relatedTerms: ['cardiac arrest', 'first aid', 'medical emergency'],
  },
  { id: 'voc_cabin_022', term: 'first aid kit', termTr: 'ilk yardım çantası', pronunciation: '/fɜːst eɪd kɪt/', category: 'emergency', difficulty: 2,
    definitionEn: 'Container with basic medical supplies for in-flight emergencies.',
    definitionTr: 'Uçuş içi aciller için temel tıbbi malzemeler içeren çanta.',
    examples: [
      { en: 'First aid kit in overhead compartment.', tr: 'İlk yardım çantası tavan bölmesinde.' },
      { en: 'Check kit contents pre-flight.', tr: 'Uçuş öncesi çanta içeriğini kontrol et.' },
    ],
    relatedTerms: ['EMK', 'AED', 'medical emergency'],
  },
  { id: 'voc_cabin_023', term: 'smoke hood', termTr: 'duman maskesi', pronunciation: '/sməʊk hʊd/', category: 'emergency', difficulty: 3,
    definitionEn: 'Protective hood worn by crew when fighting cabin fires.',
    definitionTr: 'Kabin yangınlarında ekip tarafından kullanılan koruyucu başlık.',
    examples: [
      { en: 'Don smoke hood before approaching fire.', tr: 'Yangına yaklaşmadan duman maskesi tak.' },
      { en: '15-minute oxygen supply.', tr: '15 dakikalık oksijen.' },
    ],
    relatedTerms: ['fire fighting', 'PBE', 'oxygen'],
  },
  { id: 'voc_cabin_024', term: 'emergency lighting', termTr: 'acil aydınlatma', pronunciation: '/ɪˈmɜː.dʒən.si ˈlaɪ.tɪŋ/', category: 'emergency', difficulty: 3,
    definitionEn: 'Floor-path lighting that activates during emergencies for evacuation.',
    definitionTr: 'Acillerde tahliye için aktif olan zemin aydınlatması.',
    examples: [
      { en: 'Floor path lights guide to nearest exit.', tr: 'Zemin ışıkları en yakın çıkışa yönlendirir.' },
      { en: 'Emergency lighting on backup battery.', tr: 'Acil aydınlatma yedek bataryada.' },
    ],
    relatedTerms: ['floor path', 'evacuation', 'exit sign'],
  },

  // ===== GALLEY & SERVICE (10) =====
  { id: 'voc_cabin_025', term: 'galley', termTr: 'galley (kabin mutfak)', pronunciation: '/ˈɡæl.i/', category: 'cabin_area', difficulty: 2,
    definitionEn: 'The kitchen area on an aircraft where food and drinks are prepared.',
    definitionTr: 'Uçak içi mutfak bölgesi.',
    examples: [
      { en: 'Coffee brewing in forward galley.', tr: 'Ön galley\'de kahve hazırlanıyor.' },
      { en: 'Trolleys stored in galley.', tr: 'Trolley\'ler galley\'de saklanır.' },
    ],
    relatedTerms: ['trolley', 'oven', 'jumpseat'],
  },
  { id: 'voc_cabin_026', term: 'trolley', termTr: 'trolley (servis arabası)', pronunciation: '/ˈtrɒl.i/', category: 'cabin_equipment', difficulty: 2,
    definitionEn: 'A wheeled cart used to serve food and beverages to passengers.',
    definitionTr: 'Yolculara yemek ve içecek servisi için tekerlekli araba.',
    examples: [
      { en: 'Push trolley down the aisle.', tr: 'Trolley\'i koridordan it.' },
      { en: 'Lock trolley brake before service.', tr: 'Servis öncesi trolley frenini kilitle.' },
    ],
    relatedTerms: ['galley', 'cart', 'aisle'],
  },
  { id: 'voc_cabin_027', term: 'meal service', termTr: 'yemek servisi', pronunciation: '/miːl ˈsɜː.vɪs/', category: 'service', difficulty: 1,
    definitionEn: 'The distribution of meals to passengers during a flight.',
    definitionTr: 'Uçuş sırasında yolculara yemek dağıtımı.',
    examples: [
      { en: 'Meal service starts after cruise altitude.', tr: 'Yemek servisi seyir irtifasından sonra başlar.' },
      { en: 'Special meals served first.', tr: 'Özel yemekler önce servis edilir.' },
    ],
    relatedTerms: ['galley', 'special meal', 'service'],
  },
  { id: 'voc_cabin_028', term: 'special meal', termTr: 'özel yemek', pronunciation: '/ˈspeʃ.əl miːl/', category: 'service', difficulty: 2,
    definitionEn: 'Pre-ordered meals for dietary, religious, or medical needs.',
    definitionTr: 'Diyet, dini veya tıbbi ihtiyaçlar için önceden sipariş edilen yemekler.',
    examples: [
      { en: 'VGML = vegetarian meal, KSML = kosher.', tr: 'VGML = vejetaryen, KSML = koşer.' },
      { en: 'Confirm special meals during pre-flight.', tr: 'Uçuş öncesi özel yemekleri onayla.' },
    ],
    relatedTerms: ['VGML', 'KSML', 'HNML', 'CHML'],
  },
  { id: 'voc_cabin_029', term: 'beverage service', termTr: 'içecek servisi', pronunciation: '/ˈbev.ər.ɪdʒ ˈsɜː.vɪs/', category: 'service', difficulty: 1,
    definitionEn: 'Distribution of drinks (water, juice, soft drinks, alcohol) to passengers.',
    definitionTr: 'Yolculara içecek (su, meyve suyu, alkollü) dağıtımı.',
    examples: [
      { en: 'Beverage cart in the aisle.', tr: 'İçecek arabası koridorda.' },
      { en: 'Limit alcohol per passenger.', tr: 'Yolcu başına alkolü sınırla.' },
    ],
    relatedTerms: ['cart', 'cocktail', 'water'],
  },
  { id: 'voc_cabin_030', term: 'crew rest', termTr: 'ekip dinlenme alanı', pronunciation: '/kruː rest/', category: 'cabin_area', difficulty: 3,
    definitionEn: 'Designated rest area for crew on long-haul flights.',
    definitionTr: 'Uzun mesafe uçuşlarda ekip için dinlenme alanı.',
    examples: [
      { en: 'Crew rest is mandatory after 12+ hour flights.', tr: '12+ saat uçuşlarda crew rest zorunlu.' },
      { en: 'Bunk beds in upper deck.', tr: 'Üst güvertede ranza yatak.' },
    ],
    relatedTerms: ['bunk', 'duty time', 'rest period'],
  },
  { id: 'voc_cabin_031', term: 'jumpseat', termTr: 'jumpseat (ekip koltuğu)', pronunciation: '/ˈdʒʌmp.siːt/', category: 'cabin_equipment', difficulty: 2,
    definitionEn: 'Folding seat used by cabin crew during takeoff and landing.',
    definitionTr: 'Kabin ekibinin kalkış ve inişte oturduğu katlanır koltuk.',
    examples: [
      { en: 'Take your jumpseat.', tr: 'Jumpseat\'inize geçin.' },
      { en: 'Jumpseat near each emergency exit.', tr: 'Her acil çıkış yanında jumpseat.' },
    ],
    relatedTerms: ['takeoff position', 'flight attendant', 'cabin crew'],
  },
  { id: 'voc_cabin_032', term: 'aisle', termTr: 'koridor', pronunciation: '/aɪl/', category: 'cabin_area', difficulty: 1,
    definitionEn: 'Walkway between rows of seats in the passenger cabin.',
    definitionTr: 'Yolcu kabininde koltuk sıraları arasındaki yürüyüş yolu.',
    examples: [
      { en: 'Keep aisle clear during turbulence.', tr: 'Türbülansta koridoru boş tut.' },
      { en: 'Aisle seat preferred.', tr: 'Koridor koltuğu tercih edilir.' },
    ],
    relatedTerms: ['window seat', 'middle seat', 'row'],
  },
  { id: 'voc_cabin_033', term: 'galley equipment', termTr: 'galley ekipmanı', pronunciation: '/ˈɡæl.i ɪˈkwɪp.mənt/', category: 'cabin_equipment', difficulty: 2,
    definitionEn: 'Items in galley: ovens, coffee makers, water boilers, refrigerators.',
    definitionTr: 'Galley\'deki ekipmanlar: fırın, kahve makinesi, su ısıtıcısı, buzdolabı.',
    examples: [
      { en: 'Check galley equipment before flight.', tr: 'Uçuş öncesi galley ekipmanını kontrol et.' },
      { en: 'Galley power off for landing.', tr: 'İniş için galley elektriği kesik.' },
    ],
    relatedTerms: ['oven', 'coffee maker', 'water boiler'],
  },
  { id: 'voc_cabin_034', term: 'catering', termTr: 'catering (yemek hazırlığı)', pronunciation: '/ˈkeɪ.tər.ɪŋ/', category: 'service', difficulty: 2,
    definitionEn: 'Loading prepared meals onto the aircraft before each flight.',
    definitionTr: 'Her uçuş öncesi hazırlanmış yemeklerin uçağa yüklenmesi.',
    examples: [
      { en: 'Catering loaded 1 hour before departure.', tr: 'Catering kalkıştan 1 saat önce yüklendi.' },
      { en: 'Inspect catering for completeness.', tr: 'Catering\'i eksiksiz olduğu için kontrol et.' },
    ],
    relatedTerms: ['galley loading', 'meal count', 'special meal'],
  },

  // ===== SPECIAL PASSENGERS (8) =====
  { id: 'voc_cabin_035', term: 'unruly passenger', termTr: 'uyumsuz yolcu', pronunciation: '/ʌnˈruː.li ˈpæs.ən.dʒər/', category: 'passenger', difficulty: 3,
    definitionEn: 'A passenger whose behavior threatens flight safety, order, or discipline.',
    definitionTr: 'Davranışı uçuş emniyetini tehdit eden yolcu.',
    examples: [
      { en: 'File unruly passenger report.', tr: 'Uyumsuz yolcu raporu doldur.' },
      { en: 'De-escalate before restraint.', tr: 'Müdahaleden önce yatıştır.' },
    ],
    icaoReference: 'ICAO Annex 9 + Tokyo Convention',
    relatedTerms: ['de-escalation', 'restraint', 'incident report'],
  },
  { id: 'voc_cabin_036', term: 'unaccompanied minor', termTr: 'eşliksiz çocuk (UM)', pronunciation: '/ʌn.əˈkʌm.pə.nid ˈmaɪ.nər/', category: 'passenger', difficulty: 3,
    definitionEn: 'A child traveling alone, requiring special supervision by airline staff.',
    definitionTr: 'Tek başına seyahat eden, havayolu personeli tarafından özel gözetim gerektiren çocuk.',
    examples: [
      { en: 'UM service available 5-12 years.', tr: 'UM servisi 5-12 yaş.' },
      { en: 'Hand UM to authorized adult only.', tr: 'UM\'i sadece yetkili yetişkine teslim et.' },
    ],
    relatedTerms: ['SSR', 'guardian', 'age restriction'],
  },
  { id: 'voc_cabin_037', term: 'medical case', termTr: 'tıbbi durum (MEDA)', pronunciation: '/ˈmed.ɪ.kəl keɪs/', category: 'passenger', difficulty: 3,
    definitionEn: 'A passenger requiring medical clearance or special handling.',
    definitionTr: 'Tıbbi izin veya özel işlem gerektiren yolcu.',
    examples: [
      { en: 'MEDA requires MEDIF form.', tr: 'MEDA için MEDIF formu gerekli.' },
      { en: 'Brief crew on MEDA passenger.', tr: 'MEDA yolcu için ekibi brief et.' },
    ],
    relatedTerms: ['MEDIF', 'wheelchair', 'oxygen'],
  },
  { id: 'voc_cabin_038', term: 'wheelchair', termTr: 'tekerlekli sandalye', pronunciation: '/ˈwiːl.tʃeər/', category: 'passenger', difficulty: 2,
    definitionEn: 'Special service for passengers with mobility limitations.',
    definitionTr: 'Hareket kısıtlılığı olan yolcular için özel servis.',
    examples: [
      { en: 'WCHR: walks short distance.', tr: 'WCHR: kısa mesafe yürür.' },
      { en: 'WCHC: completely immobile.', tr: 'WCHC: tamamen hareketsiz.' },
    ],
    relatedTerms: ['WCHR', 'WCHS', 'WCHC', 'PRM'],
  },
  { id: 'voc_cabin_039', term: 'inadmissible passenger', termTr: 'kabul edilmeyen yolcu (INAD)', pronunciation: '/ˌɪn.ədˈmɪs.ɪ.bəl/', category: 'passenger', difficulty: 4,
    definitionEn: 'A passenger denied entry by destination authorities, must be returned.',
    definitionTr: 'Hedef otoriteleri tarafından girişi reddedilen, geri gönderilmesi gereken yolcu.',
    examples: [
      { en: 'INAD: no valid visa.', tr: 'INAD: geçerli vize yok.' },
      { en: 'Airline must repatriate INAD.', tr: 'Havayolu INAD\'ı geri göndermeli.' },
    ],
    relatedTerms: ['DEPU', 'visa', 'repatriation'],
  },
  { id: 'voc_cabin_040', term: 'deportee', termTr: 'sınır dışı edilen (DEPU)', pronunciation: '/ˌdiː.pɔːˈtiː/', category: 'passenger', difficulty: 4,
    definitionEn: 'Person being removed from a country by official order.',
    definitionTr: 'Resmi karar ile bir ülkeden çıkarılan kişi.',
    examples: [
      { en: 'DEPU may require security escort.', tr: 'DEPU güvenlik eskortu gerektirebilir.' },
      { en: 'DEPA: accompanied; DEPU: unaccompanied.', tr: 'DEPA: eşlikli; DEPU: eşliksiz.' },
    ],
    relatedTerms: ['INAD', 'security escort', 'repatriation'],
  },
  { id: 'voc_cabin_041', term: 'special service request', termTr: 'özel servis talebi (SSR)', pronunciation: '/ˈspeʃ.əl ˈsɜː.vɪs rɪˈkwest/', category: 'passenger', difficulty: 3,
    definitionEn: 'Coded request for special needs (UM, MEDA, special meal, etc.).',
    definitionTr: 'Özel ihtiyaç için kodlu talep (UM, MEDA, özel yemek vb.).',
    examples: [
      { en: 'Check SSR list pre-flight.', tr: 'Uçuş öncesi SSR listesini kontrol et.' },
      { en: 'Today: 2 WCHR, 1 UM, 1 MEDA.', tr: 'Bugün: 2 WCHR, 1 UM, 1 MEDA.' },
    ],
    icaoReference: 'IATA SSR codes',
    relatedTerms: ['UM', 'MEDA', 'VGML', 'WCHR'],
  },
  { id: 'voc_cabin_042', term: 'vegetarian meal', termTr: 'vejetaryen yemek (VGML)', pronunciation: '/ˌvedʒ.ɪˈteər.i.ən miːl/', category: 'service', difficulty: 2,
    definitionEn: 'Pre-ordered vegetarian meal (VGML) — no meat, may include dairy/eggs.',
    definitionTr: 'Önceden sipariş vejetaryen yemek (VGML) — etsiz, süt/yumurta olabilir.',
    examples: [
      { en: 'VGML loaded for seat 12B.', tr: 'VGML koltuk 12B için yüklendi.' },
      { en: 'VGOR: strict vegan.', tr: 'VGOR: katı vegan.' },
    ],
    relatedTerms: ['special meal', 'KSML', 'HNML', 'VGOR'],
  },

  // ===== PILOT-CABIN COORDINATION (5) =====
  { id: 'voc_cabin_043', term: 'cabin secure', termTr: 'kabin emniyetli', pronunciation: '/ˈkæb.ɪn sɪˈkjʊər/', category: 'coordination', difficulty: 2,
    definitionEn: 'Confirmation that the cabin is ready and safe for takeoff or landing.',
    definitionTr: 'Kabinin kalkış veya inişe hazır ve emniyetli olduğunun teyidi.',
    examples: [
      { en: '"Captain, cabin secure."', tr: '"Kaptan, kabin emniyetli."' },
      { en: 'All seatbelts checked, doors armed.', tr: 'Tüm kemerler kontrollü, kapılar kuruldu.' },
    ],
    relatedTerms: ['ready for takeoff', 'cross check', 'doors armed'],
  },
  { id: 'voc_cabin_044', term: 'interphone', termTr: 'interphone (kabinler arası)', pronunciation: '/ˈɪn.tər.fəʊn/', category: 'coordination', difficulty: 2,
    definitionEn: 'Internal communication system between cockpit and cabin.',
    definitionTr: 'Kokpit ile kabin arasındaki iç iletişim sistemi.',
    examples: [
      { en: 'Interphone call from cabin.', tr: 'Kabinden interphone çağrısı.' },
      { en: 'Captain calling cabin manager.', tr: 'Kaptan kabin amirini arıyor.' },
    ],
    relatedTerms: ['all-call', 'PA', 'flight deck'],
  },
  { id: 'voc_cabin_045', term: 'all-call', termTr: 'all-call (tüm ekip)', pronunciation: '/ɔːl kɔːl/', category: 'coordination', difficulty: 2,
    definitionEn: 'Interphone signal that calls all flight attendants simultaneously.',
    definitionTr: 'Tüm hostesleri aynı anda çağıran interphone sinyali.',
    examples: [
      { en: 'Captain initiated all-call.', tr: 'Kaptan all-call başlattı.' },
      { en: 'All-call for emergency briefing.', tr: 'Acil brifing için all-call.' },
    ],
    relatedTerms: ['interphone', 'emergency', 'briefing'],
  },
  { id: 'voc_cabin_046', term: 'cabin manager', termTr: 'kabin amiri (purser)', pronunciation: '/ˈkæb.ɪn ˈmæn.ɪ.dʒər/', category: 'staff', difficulty: 2,
    definitionEn: 'Senior cabin crew member responsible for cabin operations.',
    definitionTr: 'Kabin operasyonlarından sorumlu kıdemli kabin ekibi üyesi.',
    examples: [
      { en: 'Purser briefs cabin crew pre-flight.', tr: 'Purser uçuş öncesi ekibi brief eder.' },
      { en: 'Cabin manager reports to captain.', tr: 'Kabin amiri kaptana rapor verir.' },
    ],
    relatedTerms: ['purser', 'lead flight attendant', 'CSM'],
  },
  { id: 'voc_cabin_047', term: 'pre-flight briefing', termTr: 'uçuş öncesi brifingi', pronunciation: '/priː flaɪt ˈbriː.fɪŋ/', category: 'coordination', difficulty: 2,
    definitionEn: 'Briefing before each flight covering safety, weather, special handling.',
    definitionTr: 'Her uçuş öncesi emniyet, hava, özel işlem konularını içeren brifing.',
    examples: [
      { en: 'Briefing 1 hour before departure.', tr: 'Brifing kalkıştan 1 saat önce.' },
      { en: 'Captain leads briefing.', tr: 'Brifingi kaptan yönetir.' },
    ],
    relatedTerms: ['safety brief', 'flight plan', 'crew brief'],
  },

  // ===== INTERVIEW & INDUSTRY (8) =====
  { id: 'voc_cabin_048', term: 'competency-based interview', termTr: 'yetkinlik bazlı mülakat', pronunciation: '/ˈkɒm.pɪ.tən.si beɪst ˈɪn.tər.vjuː/', category: 'interview', difficulty: 3,
    definitionEn: 'Interview format using behavioral questions to assess competencies.',
    definitionTr: 'Yetkinlikleri ölçmek için davranışsal sorular kullanan mülakat formatı.',
    examples: [
      { en: '"Tell me about a time you handled conflict."', tr: '"Çatışmayı yönettiğin bir zamanı anlat."' },
      { en: 'STAR method: Situation, Task, Action, Result.', tr: 'STAR yöntemi: Durum, Görev, Aksiyon, Sonuç.' },
    ],
    relatedTerms: ['STAR method', 'behavioral question', 'assessment'],
  },
  { id: 'voc_cabin_049', term: 'group exercise', termTr: 'grup egzersizi', pronunciation: '/ɡruːp ˈek.sə.saɪz/', category: 'interview', difficulty: 3,
    definitionEn: 'Assessment center activity testing teamwork and leadership.',
    definitionTr: 'Takım çalışması ve liderlik testi için değerlendirme merkezi aktivitesi.',
    examples: [
      { en: 'Group of 6 candidates solve a scenario.', tr: '6 aday bir senaryo çözer.' },
      { en: 'Show leadership without dominating.', tr: 'Baskın olmadan liderlik göster.' },
    ],
    relatedTerms: ['assessment center', 'role-play', 'teamwork'],
  },
  { id: 'voc_cabin_050', term: 'height and reach test', termTr: 'boy ve uzanma testi', pronunciation: '/haɪt ænd riːtʃ test/', category: 'interview', difficulty: 2,
    definitionEn: 'Physical test ensuring candidates can reach overhead bins.',
    definitionTr: 'Adayların üst dolaplara erişebildiğini doğrulayan fiziksel test.',
    examples: [
      { en: 'THY minimum: 165 cm without shoes.', tr: 'THY minimum: 165 cm ayakkabısız.' },
      { en: 'Reach 2.10 m on tiptoes.', tr: 'Parmak ucunda 2.10 m\'ye ulaş.' },
    ],
    relatedTerms: ['physical assessment', 'minimum height', 'BMI'],
  },
  { id: 'voc_cabin_051', term: 'customer service excellence', termTr: 'müşteri hizmet mükemmelliği', pronunciation: '/ˈkʌs.tə.mər ˈsɜː.vɪs ˈek.sə.ləns/', category: 'interview', difficulty: 2,
    definitionEn: 'Quality of service exceeding passenger expectations.',
    definitionTr: 'Yolcu beklentilerini aşan hizmet kalitesi.',
    examples: [
      { en: 'Anticipate passenger needs.', tr: 'Yolcu ihtiyaçlarını öngör.' },
      { en: 'Personalize service when possible.', tr: 'Mümkünse servisi kişiselleştir.' },
    ],
    relatedTerms: ['VIP service', 'hospitality', 'guest experience'],
  },
  { id: 'voc_cabin_052', term: 'grooming standards', termTr: 'görünüm standartları', pronunciation: '/ˈɡruː.mɪŋ ˈstæn.dədz/', category: 'interview', difficulty: 2,
    definitionEn: 'Strict appearance rules for cabin crew (uniform, hair, makeup).',
    definitionTr: 'Kabin ekibi için sıkı görünüm kuralları (üniforma, saç, makyaj).',
    examples: [
      { en: 'Hair tied, makeup natural.', tr: 'Saç toplu, makyaj doğal.' },
      { en: 'Visible tattoos not allowed.', tr: 'Görünür dövme yasak.' },
    ],
    relatedTerms: ['uniform', 'appearance', 'professional image'],
  },
  { id: 'voc_cabin_053', term: 'multilingual', termTr: 'çok dilli', pronunciation: '/ˌmʌl.tiˈlɪŋ.ɡwəl/', category: 'interview', difficulty: 2,
    definitionEn: 'Speaking multiple languages — competitive advantage for cabin crew.',
    definitionTr: 'Birden çok dil konuşma — kabin ekibi için rekabet avantajı.',
    examples: [
      { en: 'THY values multilingual candidates.', tr: 'THY çok dilli adayları değerli görür.' },
      { en: 'English required, Russian/Arabic preferred.', tr: 'İngilizce zorunlu, Rusça/Arapça tercih.' },
    ],
    relatedTerms: ['language proficiency', 'TOEIC', 'native speaker'],
  },
  { id: 'voc_cabin_054', term: 'roster', termTr: 'uçuş çizelgesi', pronunciation: '/ˈrɒs.tər/', category: 'work', difficulty: 2,
    definitionEn: 'Schedule of flights assigned to a crew member.',
    definitionTr: 'Bir ekip üyesine atanan uçuşların çizelgesi.',
    examples: [
      { en: 'Monthly roster published.', tr: 'Aylık roster yayınlandı.' },
      { en: 'Roster swap with colleague.', tr: 'Meslektaş ile roster değişimi.' },
    ],
    relatedTerms: ['duty', 'standby', 'rest period'],
  },
  { id: 'voc_cabin_055', term: 'standby duty', termTr: 'standby görevi', pronunciation: '/ˈstænd.baɪ ˈdjuː.ti/', category: 'work', difficulty: 3,
    definitionEn: 'On-call status: ready to fly within hours if assigned.',
    definitionTr: 'Çağrı üstü statü: atandığında saatler içinde uçmaya hazır.',
    examples: [
      { en: 'Standby duty: airport or home.', tr: 'Standby: havalimanında veya evde.' },
      { en: 'Maximum standby 12 hours.', tr: 'Maksimum standby 12 saat.' },
    ],
    relatedTerms: ['reserve', 'on-call', 'duty period'],
  },

  // ===== PASSENGER ANNOUNCEMENTS (5) =====
  { id: 'voc_cabin_056', term: 'safety demonstration', termTr: 'emniyet gösterimi', pronunciation: '/ˈseɪf.ti ˌdem.ənˈstreɪ.ʃən/', category: 'pa_announcement', difficulty: 2,
    definitionEn: 'Mandatory pre-flight demonstration of seatbelt, oxygen, life vest, exits.',
    definitionTr: 'Uçuş öncesi zorunlu kemer, oksijen, can yeleği, çıkış gösterimi.',
    examples: [
      { en: 'Watch the safety demonstration.', tr: 'Emniyet gösterimini izleyin.' },
      { en: 'Video or live demo accepted.', tr: 'Video veya canlı gösterim kabul edilir.' },
    ],
    relatedTerms: ['safety briefing', 'safety card', 'pre-flight'],
  },
  { id: 'voc_cabin_057', term: 'no smoking sign', termTr: 'sigara içilmez işareti', pronunciation: '/nəʊ ˈsməʊ.kɪŋ saɪn/', category: 'cabin_signage', difficulty: 1,
    definitionEn: 'Permanently illuminated sign — smoking prohibited on all flights.',
    definitionTr: 'Sürekli yanık işaret — tüm uçuşlarda sigara yasak.',
    examples: [
      { en: 'Federal law prohibits smoking.', tr: 'Federal yasa sigarayı yasaklar.' },
      { en: 'Smoking in lavatories triggers alarm.', tr: 'Tuvalette sigara alarmı tetikler.' },
    ],
    relatedTerms: ['lavatory', 'smoke detector', 'fine'],
  },
  { id: 'voc_cabin_058', term: 'electronic devices', termTr: 'elektronik cihazlar', pronunciation: '/ˌel.ekˈtrɒn.ɪk dɪˈvaɪs.ɪz/', category: 'pa_announcement', difficulty: 2,
    definitionEn: 'Phones, laptops, tablets — must be in flight mode for takeoff.',
    definitionTr: 'Telefon, laptop, tablet — kalkışta uçak modunda olmalı.',
    examples: [
      { en: 'Switch devices to airplane mode.', tr: 'Cihazları uçak moduna alın.' },
      { en: 'Larger devices stowed for takeoff.', tr: 'Büyük cihazlar kalkışta kapatılır.' },
    ],
    relatedTerms: ['airplane mode', 'PED', 'in-flight wifi'],
  },
  { id: 'voc_cabin_059', term: 'passenger manifest', termTr: 'yolcu listesi', pronunciation: '/ˈpæs.ən.dʒər ˈmæn.ɪ.fest/', category: 'documentation', difficulty: 3,
    definitionEn: 'Official document listing all passengers and crew on a flight.',
    definitionTr: 'Bir uçuştaki tüm yolcu ve ekibi listeleyen resmi belge.',
    examples: [
      { en: 'Manifest sent to authorities pre-flight.', tr: 'Manifesto uçuş öncesi yetkililere gönderilir.' },
      { en: 'Cross-check headcount with manifest.', tr: 'Sayımı manifesto ile çapraz kontrol et.' },
    ],
    relatedTerms: ['headcount', 'PNR', 'load sheet'],
  },
  { id: 'voc_cabin_060', term: 'turnaround', termTr: 'turnaround (hızlı dönüş)', pronunciation: '/ˈtɜːn.əˌraʊnd/', category: 'work', difficulty: 3,
    definitionEn: 'Process of preparing the aircraft for the next flight quickly.',
    definitionTr: 'Uçağı bir sonraki uçuş için hızla hazırlama süreci.',
    examples: [
      { en: 'Turnaround time: 30 minutes.', tr: 'Turnaround süresi: 30 dakika.' },
    ],
    relatedTerms: ['transit', 'scheduled departure', 'block time'],
  },
  // ===== CABIN CLASSES (8) =====
  { id: 'voc_cabin_061', term: 'business class', termTr: 'business class', pronunciation: '/ˈbɪz.nəs klɑːs/', category: 'cabin_class', difficulty: 1,
    definitionEn: 'Premium cabin with lie-flat seats, gourmet meals, priority service.',
    definitionTr: 'Yatabilen koltuk, gurme yemek, öncelikli servis premium kabin.',
    examples: [{ en: 'Welcome to business class, Mr. Smith.', tr: 'Business class\'a hoş geldiniz Bay Smith.' }],
    relatedTerms: ['first class', 'economy', 'premium'],
  },
  { id: 'voc_cabin_062', term: 'first class', termTr: 'first class', pronunciation: '/fɜːst klɑːs/', category: 'cabin_class', difficulty: 1,
    definitionEn: 'Top-tier cabin with private suites, fine dining, exclusive service.',
    definitionTr: 'Özel süitler, fine dining, ayrıcalıklı servisli en üst kabin.',
    examples: [{ en: 'First class on long-haul A380.', tr: 'Uzun mesafe A380\'de first class.' }],
    relatedTerms: ['business class', 'suite', 'premium'],
  },
  { id: 'voc_cabin_063', term: 'economy class', termTr: 'economy class', pronunciation: '/ɪˈkɒn.ə.mi klɑːs/', category: 'cabin_class', difficulty: 1,
    definitionEn: 'Standard cabin with most seats, basic service.',
    definitionTr: 'Çoğu koltuğun bulunduğu, temel servisli standart kabin.',
    examples: [{ en: 'Economy class boarding now.', tr: 'Economy class boarding başladı.' }],
    relatedTerms: ['premium economy', 'standard', 'coach'],
  },
  { id: 'voc_cabin_064', term: 'premium economy', termTr: 'premium economy', pronunciation: '/ˈpriː.mi.əm ɪˈkɒn.ə.mi/', category: 'cabin_class', difficulty: 2,
    definitionEn: 'Mid-tier cabin with extra legroom and improved service.',
    definitionTr: 'Ekstra ayak boşluğu ve iyileştirilmiş servisli orta seviye kabin.',
    examples: [{ en: 'Premium economy: 38" pitch.', tr: 'Premium economy: 38" pitch.' }],
    relatedTerms: ['economy', 'business', 'pitch'],
  },
  { id: 'voc_cabin_065', term: 'lie-flat seat', termTr: 'yatabilen koltuk', pronunciation: '/ˌlaɪˈflæt siːt/', category: 'cabin_equipment', difficulty: 2,
    definitionEn: 'Seat that reclines fully horizontal for sleeping.',
    definitionTr: 'Uyumak için tamamen yatay olan koltuk.',
    examples: [{ en: 'Lie-flat seats in business class.', tr: 'Business class\'ta yatabilen koltuklar.' }],
    relatedTerms: ['recliner', 'suite', 'sleep'],
  },
  { id: 'voc_cabin_066', term: 'pitch', termTr: 'pitch (koltuk arası mesafe)', pronunciation: '/pɪtʃ/', category: 'cabin_equipment', difficulty: 3,
    definitionEn: 'Distance between rows of seats, measured in inches.',
    definitionTr: 'Koltuk sıraları arası mesafe, inç olarak ölçülür.',
    examples: [{ en: 'Economy pitch 31", premium 38".', tr: 'Economy pitch 31", premium 38".' }],
    relatedTerms: ['legroom', 'seat row', 'configuration'],
  },
  { id: 'voc_cabin_067', term: 'configuration', termTr: 'konfigürasyon', pronunciation: '/kənˌfɪɡ.əˈreɪ.ʃən/', category: 'cabin', difficulty: 3,
    definitionEn: 'Seat layout in cabin (e.g., 3-3, 2-4-2, 1-2-1).',
    definitionTr: 'Kabindeki koltuk düzeni (3-3, 2-4-2, 1-2-1 gibi).',
    examples: [{ en: 'A350 economy config 3-3-3.', tr: 'A350 economy konfigürasyon 3-3-3.' }],
    relatedTerms: ['layout', 'pitch', 'seat map'],
  },
  { id: 'voc_cabin_068', term: 'curtain', termTr: 'perde (sınıf ayrımı)', pronunciation: '/ˈkɜː.tən/', category: 'cabin_equipment', difficulty: 1,
    definitionEn: 'Cloth divider between cabin classes for privacy.',
    definitionTr: 'Kabin sınıfları arası gizlilik için kumaş bölücü.',
    examples: [{ en: 'Close curtain after meal service.', tr: 'Yemek servisi sonrası perdeyi kapat.' }],
    relatedTerms: ['divider', 'privacy', 'class boundary'],
  },

  // ===== PASSENGER ISSUES (10) =====
  { id: 'voc_cabin_069', term: 'passenger illness', termTr: 'yolcu hastalığı', pronunciation: '/ˈpæs.ən.dʒər ˈɪl.nəs/', category: 'medical', difficulty: 2,
    definitionEn: 'Passenger experiencing health problem during flight.',
    definitionTr: 'Uçuş sırasında sağlık sorunu yaşayan yolcu.',
    examples: [{ en: 'Notify captain immediately.', tr: 'Kaptanı derhal bilgilendir.' }],
    relatedTerms: ['medical emergency', 'first aid', 'doctor on board'],
  },
  { id: 'voc_cabin_070', term: 'doctor on board', termTr: 'uçakta doktor var mı', pronunciation: '/ˈdɒk.tər ɒn bɔːd/', category: 'medical', difficulty: 2,
    definitionEn: 'PA call requesting medical professional assistance.',
    definitionTr: 'Tıbbi profesyonel yardımı isteyen PA çağrısı.',
    examples: [{ en: '"Is there a doctor on board?"', tr: '"Uçakta doktor var mı?"' }],
    relatedTerms: ['medical emergency', 'EMK', 'AED'],
  },
  { id: 'voc_cabin_071', term: 'EMK', termTr: 'EMK (Acil Tıbbi Çanta)', pronunciation: '/iː em keɪ/', category: 'medical', difficulty: 3,
    definitionEn: 'Emergency Medical Kit — medications used by qualified medical personnel.',
    definitionTr: 'Acil Tıbbi Çanta — nitelikli tıbbi personel tarafından kullanılan ilaçlar.',
    examples: [{ en: 'EMK access requires doctor.', tr: 'EMK erişimi doktor gerektirir.' }],
    relatedTerms: ['first aid kit', 'AED', 'medical emergency'],
  },
  { id: 'voc_cabin_072', term: 'intoxicated passenger', termTr: 'sarhoş yolcu', pronunciation: '/ɪnˈtɒk.sɪ.keɪ.tɪd/', category: 'passenger', difficulty: 3,
    definitionEn: 'Passenger under the influence of alcohol or drugs.',
    definitionTr: 'Alkol veya uyuşturucu etkisinde yolcu.',
    examples: [{ en: 'Refuse alcohol service to intoxicated.', tr: 'Sarhoşa alkol servisini reddet.' }],
    relatedTerms: ['unruly passenger', 'alcohol', 'restraint'],
  },
  { id: 'voc_cabin_073', term: 'restraint', termTr: 'fiziksel müdahale', pronunciation: '/rɪˈstreɪnt/', category: 'security', difficulty: 4,
    definitionEn: 'Last-resort use of physical force to control unruly passenger.',
    definitionTr: 'Uyumsuz yolcuyu kontrol etmek için son çare fiziksel güç kullanımı.',
    examples: [{ en: 'Use restraint kit if necessary.', tr: 'Gerekirse restraint kit kullan.' }],
    relatedTerms: ['unruly', 'security', 'air marshal'],
  },
  { id: 'voc_cabin_074', term: 'air marshal', termTr: 'gökyüzü polisi', pronunciation: '/eər ˈmɑː.ʃəl/', category: 'security', difficulty: 4,
    definitionEn: 'Armed law enforcement officer flying undercover.',
    definitionTr: 'Sivil giyimli, silahlı kolluk görevlisi.',
    examples: [{ en: 'Air marshal identity confidential.', tr: 'Air marshal kimliği gizli.' }],
    relatedTerms: ['security', 'undercover', 'restraint'],
  },
  { id: 'voc_cabin_075', term: 'complaint', termTr: 'şikayet', pronunciation: '/kəmˈpleɪnt/', category: 'service', difficulty: 1,
    definitionEn: 'Passenger\'s expression of dissatisfaction with service.',
    definitionTr: 'Yolcunun servisten memnuniyetsizlik ifadesi.',
    examples: [{ en: 'Document complaint in flight log.', tr: 'Şikayeti uçuş log\'una not et.' }],
    relatedTerms: ['feedback', 'apology', 'service recovery'],
  },
  { id: 'voc_cabin_076', term: 'service recovery', termTr: 'servis düzeltme', pronunciation: '/ˈsɜː.vɪs rɪˈkʌv.ər.i/', category: 'service', difficulty: 3,
    definitionEn: 'Actions taken to fix a service failure and regain passenger satisfaction.',
    definitionTr: 'Servis hatasını düzeltmek ve yolcu memnuniyetini geri kazanmak için aksiyonlar.',
    examples: [{ en: 'Offer free upgrade as recovery.', tr: 'Düzeltme olarak ücretsiz upgrade öner.' }],
    relatedTerms: ['complaint', 'apology', 'compensation'],
  },
  { id: 'voc_cabin_077', term: 'lap child', termTr: 'kucak çocuğu', pronunciation: '/læp tʃaɪld/', category: 'passenger', difficulty: 2,
    definitionEn: 'Infant under 2 years old who travels on parent\'s lap.',
    definitionTr: 'Ebeveyn kucağında seyahat eden 2 yaş altı bebek.',
    examples: [{ en: 'Lap child requires extender belt.', tr: 'Lap child uzatmalı kemer gerektirir.' }],
    relatedTerms: ['infant', 'extender belt', 'bassinet'],
  },
  { id: 'voc_cabin_078', term: 'bassinet', termTr: 'bebek beşiği', pronunciation: '/ˌbæs.ɪˈnet/', category: 'cabin_equipment', difficulty: 2,
    definitionEn: 'Wall-mounted infant bed available on long-haul flights.',
    definitionTr: 'Uzun mesafe uçuşlarda mevcut, duvara monteli bebek yatağı.',
    examples: [{ en: 'Bassinet attaches to bulkhead.', tr: 'Bassinet bulkhead\'e bağlanır.' }],
    relatedTerms: ['infant', 'bulkhead', 'lap child'],
  },

  // ===== SERVICE FLOW & MEALS (12) =====
  { id: 'voc_cabin_079', term: 'pre-flight check', termTr: 'uçuş öncesi kontrol', pronunciation: '/priː flaɪt tʃek/', category: 'preflight', difficulty: 2,
    definitionEn: 'Cabin crew\'s inspection of safety equipment, galley, and cabin.',
    definitionTr: 'Kabin ekibinin emniyet ekipmanı, galley ve kabin muayenesi.',
    examples: [{ en: 'Pre-flight check 30 min before departure.', tr: 'Pre-flight check kalkıştan 30 dk önce.' }],
    relatedTerms: ['safety equipment check', 'briefing', 'cabin secure'],
  },
  { id: 'voc_cabin_080', term: 'safety equipment check', termTr: 'emniyet ekipmanı kontrolü', pronunciation: '/ˈseɪf.ti ɪˈkwɪp.mənt tʃek/', category: 'preflight', difficulty: 2,
    definitionEn: 'Verifying life vests, oxygen, fire extinguishers, AED, slides.',
    definitionTr: 'Can yeleği, oksijen, söndürücü, AED, slide doğrulama.',
    examples: [{ en: 'Use SEP card to check.', tr: 'SEP kartı ile kontrol et.' }],
    relatedTerms: ['SEP', 'pre-flight check', 'emergency equipment'],
  },
  { id: 'voc_cabin_081', term: 'SEP', termTr: 'SEP (Emniyet & Acil Prosedürler)', pronunciation: '/es iː piː/', category: 'safety', difficulty: 3,
    definitionEn: 'Safety & Emergency Procedures — annual recurrent training.',
    definitionTr: 'Emniyet ve Acil Prosedürler — yıllık recurrent eğitimi.',
    examples: [{ en: 'SEP recurrent training annually.', tr: 'Yıllık SEP recurrent eğitimi.' }],
    relatedTerms: ['recurrent training', 'safety equipment', 'evacuation'],
  },
  { id: 'voc_cabin_082', term: 'KSML', termTr: 'KSML (kosher yemek)', pronunciation: '/keɪ es em el/', category: 'special_meal', difficulty: 3,
    definitionEn: 'Kosher meal — prepared per Jewish dietary laws.',
    definitionTr: 'Yahudi diyet yasalarına göre hazırlanan kosher yemek.',
    examples: [{ en: 'KSML loaded for seat 12B.', tr: 'KSML koltuk 12B için yüklendi.' }],
    relatedTerms: ['VGML', 'HNML', 'special meal'],
  },
  { id: 'voc_cabin_083', term: 'HNML', termTr: 'HNML (hindu yemek)', pronunciation: '/eɪtʃ en em el/', category: 'special_meal', difficulty: 3,
    definitionEn: 'Hindu meal — no beef, no pork, vegetarian options.',
    definitionTr: 'Hindu yemeği — sığır eti yok, domuz yok, vejetaryen seçenekler.',
    examples: [{ en: 'HNML respects Hindu traditions.', tr: 'HNML Hindu geleneklerine saygı gösterir.' }],
    relatedTerms: ['VGML', 'KSML', 'special meal'],
  },
  { id: 'voc_cabin_084', term: 'CHML', termTr: 'CHML (çocuk yemek)', pronunciation: '/siː eɪtʃ em el/', category: 'special_meal', difficulty: 3,
    definitionEn: 'Child meal — kid-friendly portions and food.',
    definitionTr: 'Çocuk yemeği — çocuk dostu porsiyon ve yiyecek.',
    examples: [{ en: 'CHML for ages 2-12.', tr: 'CHML 2-12 yaş için.' }],
    relatedTerms: ['BBML', 'special meal', 'kid'],
  },
  { id: 'voc_cabin_085', term: 'BBML', termTr: 'BBML (bebek yemek)', pronunciation: '/biː biː em el/', category: 'special_meal', difficulty: 3,
    definitionEn: 'Baby meal — pureed food for infants under 2.',
    definitionTr: 'Bebek yemeği — 2 yaş altı için ezilmiş yiyecek.',
    examples: [{ en: 'BBML jars + bottle warmer.', tr: 'BBML kavanoz + biberon ısıtıcı.' }],
    relatedTerms: ['CHML', 'infant', 'bottle'],
  },
  { id: 'voc_cabin_086', term: 'pre-order meal', termTr: 'önceden sipariş yemek', pronunciation: '/priː ˈɔː.dər miːl/', category: 'service', difficulty: 2,
    definitionEn: 'Meal selected by passenger before flight via website or app.',
    definitionTr: 'Yolcunun web/app üzerinden uçuş öncesi seçtiği yemek.',
    examples: [{ en: 'Pre-order meal in business class.', tr: 'Business class\'ta önceden sipariş yemek.' }],
    relatedTerms: ['catering', 'special meal', 'menu'],
  },
  { id: 'voc_cabin_087', term: 'amenity kit', termTr: 'amenity kit (konfor seti)', pronunciation: '/əˈmen.ə.ti kɪt/', category: 'service', difficulty: 2,
    definitionEn: 'Toiletry pack with eye mask, socks, dental kit on long-haul.',
    definitionTr: 'Uzun mesafede göz maskesi, çorap, diş seti içeren tuvalet seti.',
    examples: [{ en: 'Distribute amenity kits in business.', tr: 'Business\'ta amenity kit dağıt.' }],
    relatedTerms: ['long-haul', 'comfort', 'business class'],
  },
  { id: 'voc_cabin_088', term: 'in-flight entertainment', termTr: 'uçuş içi eğlence (IFE)', pronunciation: '/ˌɪn.flaɪt ˌen.təˈteɪn.mənt/', category: 'service', difficulty: 2,
    definitionEn: 'Movies, TV, music, games available at each seat.',
    definitionTr: 'Her koltukta film, TV, müzik, oyun.',
    examples: [{ en: 'IFE includes 200+ movies.', tr: 'IFE 200+ film içerir.' }],
    relatedTerms: ['IFE', 'screen', 'headphones'],
  },
  { id: 'voc_cabin_089', term: 'lavatory', termTr: 'tuvalet', pronunciation: '/ˈlæv.ə.tər.i/', category: 'cabin_area', difficulty: 1,
    definitionEn: 'Aircraft toilet/restroom.',
    definitionTr: 'Uçak tuvaleti.',
    examples: [{ en: 'Lavatory occupied sign.', tr: 'Tuvalet meşgul işareti.' }],
    relatedTerms: ['toilet', 'restroom', 'occupied'],
  },
  { id: 'voc_cabin_090', term: 'galley curtain', termTr: 'galley perdesi', pronunciation: '/ˈɡæl.i ˈkɜː.tən/', category: 'cabin_equipment', difficulty: 1,
    definitionEn: 'Curtain separating galley from cabin during service prep.',
    definitionTr: 'Servis hazırlığında galley\'i kabinden ayıran perde.',
    examples: [{ en: 'Close galley curtain during prep.', tr: 'Hazırlıkta galley perdesini kapat.' }],
    relatedTerms: ['galley', 'curtain', 'service'],
  },

  // ===== INTERVIEW & CAREER ADVANCED (10) =====
  { id: 'voc_cabin_091', term: 'recruitment', termTr: 'işe alım', pronunciation: '/rɪˈkruːt.mənt/', category: 'career', difficulty: 2,
    definitionEn: 'Process of finding and hiring new cabin crew.',
    definitionTr: 'Yeni kabin ekibi bulma ve işe alma süreci.',
    examples: [{ en: 'THY recruitment opens annually.', tr: 'THY recruitment yıllık açılır.' }],
    relatedTerms: ['hiring', 'application', 'CV'],
  },
  { id: 'voc_cabin_092', term: 'application form', termTr: 'başvuru formu', pronunciation: '/ˌæp.lɪˈkeɪ.ʃən fɔːm/', category: 'career', difficulty: 1,
    definitionEn: 'Online or paper form to apply for cabin crew position.',
    definitionTr: 'Kabin ekibi pozisyonuna başvuru için online/kağıt form.',
    examples: [{ en: 'Submit application via career portal.', tr: 'Career portal üzerinden başvuru.' }],
    relatedTerms: ['CV', 'cover letter', 'recruitment'],
  },
  { id: 'voc_cabin_093', term: 'training', termTr: 'eğitim', pronunciation: '/ˈtreɪ.nɪŋ/', category: 'career', difficulty: 1,
    definitionEn: 'Initial 6-week course covering safety, service, customer skills.',
    definitionTr: 'Emniyet, servis, müşteri becerileri kapsayan 6 haftalık ilk eğitim.',
    examples: [{ en: 'Training pass mark 80%.', tr: 'Eğitim geçme notu %80.' }],
    relatedTerms: ['initial training', 'recurrent', 'SEP'],
  },
  { id: 'voc_cabin_094', term: 'recurrent training', termTr: 'periyodik eğitim', pronunciation: '/rɪˈkʌr.ənt ˈtreɪ.nɪŋ/', category: 'career', difficulty: 3,
    definitionEn: 'Annual mandatory refresher training for cabin crew.',
    definitionTr: 'Kabin ekibi için yıllık zorunlu refresher eğitim.',
    examples: [{ en: 'Recurrent training: SEP + service.', tr: 'Recurrent: SEP + servis.' }],
    relatedTerms: ['SEP', 'training', 'refresher'],
  },
  { id: 'voc_cabin_095', term: 'probation', termTr: 'deneme süresi', pronunciation: '/prəˈbeɪ.ʃən/', category: 'career', difficulty: 3,
    definitionEn: 'Initial period (3-6 months) where new crew\'s performance is evaluated.',
    definitionTr: 'Yeni ekibin performansının değerlendirildiği ilk dönem (3-6 ay).',
    examples: [{ en: 'Probation 3 months at THY.', tr: 'THY\'de probation 3 ay.' }],
    relatedTerms: ['evaluation', 'permanent', 'contract'],
  },
  { id: 'voc_cabin_096', term: 'seniority', termTr: 'kıdem', pronunciation: '/ˌsiː.niˈɒr.ə.ti/', category: 'career', difficulty: 3,
    definitionEn: 'Length of service determining roster preferences and promotions.',
    definitionTr: 'Roster tercihleri ve terfileri belirleyen hizmet süresi.',
    examples: [{ en: 'Senior crew choose roster first.', tr: 'Kıdemli ekip roster\'ı önce seçer.' }],
    relatedTerms: ['roster', 'promotion', 'tenure'],
  },
  { id: 'voc_cabin_097', term: 'promotion', termTr: 'terfi', pronunciation: '/prəˈməʊ.ʃən/', category: 'career', difficulty: 2,
    definitionEn: 'Advancement to a higher position (e.g., flight attendant to purser).',
    definitionTr: 'Daha yüksek pozisyona ilerleme (örn: hostesten purser\'a).',
    examples: [{ en: 'Promotion to purser after 5 years.', tr: '5 yıl sonra purser\'a terfi.' }],
    relatedTerms: ['seniority', 'purser', 'career path'],
  },
  { id: 'voc_cabin_098', term: 'duty time', termTr: 'görev süresi', pronunciation: '/ˈdjuː.ti taɪm/', category: 'work', difficulty: 3,
    definitionEn: 'Hours from sign-on to sign-off, regulated by EASA/SHGM.',
    definitionTr: 'Sign-on\'dan sign-off\'a kadar saatler, EASA/SHGM tarafından düzenlenir.',
    examples: [{ en: 'Max duty time: 14 hours.', tr: 'Maksimum görev süresi: 14 saat.' }],
    relatedTerms: ['rest period', 'flight time', 'FTL'],
  },
  { id: 'voc_cabin_099', term: 'rest period', termTr: 'dinlenme süresi', pronunciation: '/rest ˈpɪə.ri.əd/', category: 'work', difficulty: 2,
    definitionEn: 'Mandatory time off between duty periods (min 12 hours).',
    definitionTr: 'Görev dönemleri arasındaki zorunlu dinlenme (min 12 saat).',
    examples: [{ en: 'Minimum rest 12 hours.', tr: 'Minimum dinlenme 12 saat.' }],
    relatedTerms: ['duty time', 'FTL', 'fatigue'],
  },
  { id: 'voc_cabin_100', term: 'fatigue', termTr: 'yorgunluk', pronunciation: '/fəˈtiːɡ/', category: 'safety', difficulty: 3,
    definitionEn: 'Tiredness affecting performance; key safety concern in aviation.',
    definitionTr: 'Performansı etkileyen yorgunluk; havacılıkta önemli emniyet sorunu.',
    examples: [{ en: 'Report fatigue if unfit to fly.', tr: 'Uçamayacak kadar yorgunsan bildir.' }],
    relatedTerms: ['rest period', 'duty time', 'fitness'],
  },

  // ===== FAZ 2 ADVANCED (40) =====
  // Premium service (10)
  { id: 'voc_cabin_101', term: 'wine pairing', termTr: 'şarap eşleştirme', pronunciation: '/waɪn ˈpeə.rɪŋ/', category: 'service', difficulty: 4,
    definitionEn: 'Matching wines with food courses for enhanced dining.', definitionTr: 'Yemek kurslarıyla şarapları eşleştirme.',
    examples: [{ en: 'Red wine with steak.', tr: 'Bonfile ile kırmızı şarap.' }],
    relatedTerms: ['fine dining', 'sommelier', 'champagne'],
  },
  { id: 'voc_cabin_102', term: 'sommelier', termTr: 'somelye', pronunciation: '/ˈsɒm.əl.jeɪ/', category: 'service', difficulty: 5,
    definitionEn: 'Wine expert; senior cabin crew may train as flying sommelier.', definitionTr: 'Şarap uzmanı; kıdemli kabin ekibi flying sommelier eğitimi alabilir.',
    examples: [{ en: 'Sommelier-trained on Asia routes.', tr: 'Asya rotalarında sommelier eğitimli.' }],
    relatedTerms: ['wine pairing', 'fine dining', 'training'],
  },
  { id: 'voc_cabin_103', term: 'gourmet meal', termTr: 'gurme yemek', pronunciation: '/ˈɡʊə.meɪ miːl/', category: 'service', difficulty: 3,
    definitionEn: 'High-quality, chef-prepared meal in business/first class.', definitionTr: 'Business/first class\'ta yüksek kaliteli, şef tarafından hazırlanmış yemek.',
    examples: [{ en: 'Michelin-star chef partnership.', tr: 'Michelin yıldızlı şef ortaklığı.' }],
    relatedTerms: ['fine dining', 'business class', 'first class'],
  },
  { id: 'voc_cabin_104', term: 'champagne service', termTr: 'şampanya servisi', pronunciation: '/ʃæmˈpeɪn ˈsɜː.vɪs/', category: 'service', difficulty: 3,
    definitionEn: 'Welcome drink ritual in premium cabins.', definitionTr: 'Premium kabinlerde karşılama içeceği ritueli.',
    examples: [{ en: 'Pre-departure champagne welcome.', tr: 'Kalkış öncesi şampanya karşılama.' }],
    relatedTerms: ['welcome drink', 'business class', 'pre-departure'],
  },
  { id: 'voc_cabin_105', term: 'turn-down service', termTr: 'turn-down servisi', pronunciation: '/ˈtɜːn.daʊn ˈsɜː.vɪs/', category: 'service', difficulty: 5,
    definitionEn: 'Preparing first class suite for sleep with bedding, pajamas.', definitionTr: 'First class süitini uyku için yatak, pijama ile hazırlama.',
    examples: [{ en: 'Turn-down service post-meal.', tr: 'Yemek sonrası turn-down servisi.' }],
    relatedTerms: ['first class', 'suite', 'pajamas'],
  },
  { id: 'voc_cabin_106', term: 'pajamas', termTr: 'pijama', pronunciation: '/pəˈdʒɑː.məz/', category: 'service', difficulty: 2,
    definitionEn: 'Sleepwear provided in first class on long-haul.', definitionTr: 'Uzun mesafe first class\'ta verilen uyku kıyafeti.',
    examples: [{ en: 'Etihad first class pajamas.', tr: 'Etihad first class pijaması.' }],
    relatedTerms: ['amenity kit', 'sleepwear', 'long-haul'],
  },
  { id: 'voc_cabin_107', term: 'caviar service', termTr: 'havyar servisi', pronunciation: '/ˈkæv.i.ɑː ˈsɜː.vɪs/', category: 'service', difficulty: 5,
    definitionEn: 'Premium luxury offering on top airlines.', definitionTr: 'Üst düzey havayollarında premium lüks sunum.',
    examples: [{ en: 'Caviar with mother-of-pearl spoon.', tr: 'Sedef kaşık ile havyar.' }],
    relatedTerms: ['fine dining', 'luxury', 'first class'],
  },
  { id: 'voc_cabin_108', term: 'tea service', termTr: 'çay servisi', pronunciation: '/tiː ˈsɜː.vɪs/', category: 'service', difficulty: 2,
    definitionEn: 'Afternoon tea in premium cabins, especially British carriers.', definitionTr: 'Premium kabinde öğleden sonra çayı, özellikle British carrierlarda.',
    examples: [{ en: 'BA afternoon tea.', tr: 'BA afternoon tea.' }],
    relatedTerms: ['afternoon tea', 'British Airways', 'scones'],
  },
  { id: 'voc_cabin_109', term: 'cocktail bar', termTr: 'kokteyl barı', pronunciation: '/ˈkɒk.teɪl bɑːr/', category: 'service', difficulty: 3,
    definitionEn: 'Onboard bar in premium cabins (e.g., A380 Emirates).', definitionTr: 'Premium kabinde uçak içi bar (Emirates A380).',
    examples: [{ en: 'Sky bar A380 Emirates.', tr: 'Sky bar A380 Emirates.' }],
    relatedTerms: ['lounge', 'A380', 'social area'],
  },
  { id: 'voc_cabin_110', term: 'allergen', termTr: 'alerjen', pronunciation: '/ˈæl.ə.dʒən/', category: 'medical', difficulty: 3,
    definitionEn: 'Substance causing allergic reaction (nuts, shellfish, gluten).', definitionTr: 'Alerjik reaksiyona neden olan madde (fındık, deniz ürünü, gluten).',
    examples: [{ en: 'Allergen-free meal request.', tr: 'Alerjensiz yemek talebi.' }],
    relatedTerms: ['nuts', 'gluten-free', 'special meal'],
  },

  // Crisis management (10)
  { id: 'voc_cabin_111', term: 'de-escalation', termTr: 'gerginliği azaltma', pronunciation: '/diːˌes.kəˈleɪ.ʃən/', category: 'security', difficulty: 4,
    definitionEn: 'Verbal techniques to calm an angry passenger.', definitionTr: 'Kızgın yolcuyu sakinleştirmek için sözel teknikler.',
    examples: [{ en: 'De-escalate before restraint.', tr: 'Restraint öncesi de-escalate.' }],
    relatedTerms: ['unruly passenger', 'verbal', 'calming'],
  },
  { id: 'voc_cabin_112', term: 'bomb threat', termTr: 'bomba tehdidi', pronunciation: '/bɒm θret/', category: 'security', difficulty: 4,
    definitionEn: 'Reported threat of explosive device on aircraft.', definitionTr: 'Uçakta patlayıcı cihaz raporu.',
    examples: [{ en: 'Bomb threat: divert immediately.', tr: 'Bomba tehdidi: derhal divert.' }],
    relatedTerms: ['hijacking', 'security threat', 'evacuation'],
  },
  { id: 'voc_cabin_113', term: 'hijacking', termTr: 'hijacking (uçak kaçırma)', pronunciation: '/ˈhaɪ.dʒæk.ɪŋ/', category: 'security', difficulty: 5,
    definitionEn: 'Illegal seizure of aircraft by force or threat.', definitionTr: 'Uçağın güç veya tehditle yasadışı el konulması.',
    examples: [{ en: 'Hijack code 7500.', tr: 'Hijack kodu 7500.' }],
    relatedTerms: ['squawk 7500', 'air marshal', 'security'],
  },
  { id: 'voc_cabin_114', term: 'evacuation', termTr: 'tahliye', pronunciation: '/ɪˌvæk.juˈeɪ.ʃən/', category: 'emergency', difficulty: 3,
    definitionEn: 'Rapid removal of all passengers from aircraft.', definitionTr: 'Tüm yolcuların uçaktan hızlı çıkarılması.',
    examples: [{ en: '90-second evacuation requirement.', tr: '90 saniye tahliye gereksinimi.' }],
    relatedTerms: ['evacuation slide', 'emergency exit', '90-second'],
  },
  { id: 'voc_cabin_115', term: 'rapid decompression', termTr: 'ani basınç kaybı', pronunciation: '/ˈræp.ɪd ˌdiː.kəmˈpreʃ.ən/', category: 'emergency', difficulty: 5,
    definitionEn: 'Sudden loss of cabin pressure requiring oxygen masks.', definitionTr: 'Oksijen maskesi gerektiren ani kabin basıncı kaybı.',
    examples: [{ en: 'Rapid decompression: don oxygen mask.', tr: 'Rapid decompression: oksijen maskesi tak.' }],
    relatedTerms: ['oxygen mask', 'cabin pressure', 'emergency descent'],
  },
  { id: 'voc_cabin_116', term: 'turbulent encounter', termTr: 'türbülans karşılaşması', pronunciation: '/ˈtɜː.bjə.lənt ɪnˈkaʊn.tər/', category: 'safety', difficulty: 3,
    definitionEn: 'Aircraft entering turbulent air, requiring crew/passenger safety.', definitionTr: 'Uçağın türbülanslı havaya girmesi, ekip/yolcu güvenliği gerektirir.',
    examples: [{ en: 'Crew secure cabin.', tr: 'Ekip kabini sabitler.' }],
    relatedTerms: ['turbulence', 'cabin secure', 'injury'],
  },
  { id: 'voc_cabin_117', term: 'crew member assault', termTr: 'ekibe saldırı', pronunciation: '/kruː ˈmem.bər əˈsɔːlt/', category: 'security', difficulty: 4,
    definitionEn: 'Physical or verbal attack on cabin crew, illegal under Tokyo Convention.', definitionTr: 'Kabin ekibine fiziksel veya sözel saldırı, Tokyo Sözleşmesi\'nce yasadışı.',
    examples: [{ en: 'Report assault to captain.', tr: 'Saldırıyı kaptana bildir.' }],
    relatedTerms: ['unruly passenger', 'Tokyo Convention', 'restraint'],
  },
  { id: 'voc_cabin_118', term: 'medical kit', termTr: 'tıbbi çanta', pronunciation: '/ˈmed.ɪ.kəl kɪt/', category: 'medical', difficulty: 2,
    definitionEn: 'On-board first aid and emergency medical supplies.', definitionTr: 'Uçak içi ilk yardım ve acil tıbbi malzeme.',
    examples: [{ en: 'Locate medical kit before flight.', tr: 'Uçuş öncesi tıbbi çantanın yerini öğren.' }],
    relatedTerms: ['EMK', 'first aid kit', 'AED'],
  },
  { id: 'voc_cabin_119', term: 'CPR', termTr: 'kalp masajı (CPR)', pronunciation: '/siː piː ɑːr/', category: 'medical', difficulty: 3,
    definitionEn: 'Cardiopulmonary Resuscitation — emergency cardiac procedure.', definitionTr: 'Kardiyopulmoner Resüsitasyon — acil kardiyak prosedür.',
    examples: [{ en: 'CPR training annually.', tr: 'CPR eğitimi yıllık.' }],
    relatedTerms: ['AED', 'cardiac arrest', 'first aid'],
  },
  { id: 'voc_cabin_120', term: 'incapacitation', termTr: 'aciz hale gelme', pronunciation: '/ɪnˌkæp.ə.sɪˈteɪ.ʃən/', category: 'medical', difficulty: 5,
    definitionEn: 'Pilot or crew unable to perform duties due to illness/incident.', definitionTr: 'Pilot veya ekibin hastalık/olay nedeniyle görev yapamaması.',
    examples: [{ en: 'Pilot incapacitation procedure.', tr: 'Pilot incapacitation prosedürü.' }],
    relatedTerms: ['pilot incapacitation', 'medical emergency', 'CRM'],
  },

  // Cultural awareness (10)
  { id: 'voc_cabin_121', term: 'cultural awareness', termTr: 'kültürel farkındalık', pronunciation: '/ˈkʌl.tʃər.əl əˈweə.nəs/', category: 'cultural', difficulty: 3,
    definitionEn: 'Understanding diverse cultural backgrounds of passengers.', definitionTr: 'Yolcuların çeşitli kültürel arka planlarını anlama.',
    examples: [{ en: 'Cultural awareness training.', tr: 'Kültürel farkındalık eğitimi.' }],
    relatedTerms: ['multilingual', 'sensitivity', 'protocol'],
  },
  { id: 'voc_cabin_122', term: 'religious considerations', termTr: 'dini hassasiyetler', pronunciation: '/rɪˈlɪdʒ.əs kənˌsɪd.əˈreɪ.ʃənz/', category: 'cultural', difficulty: 3,
    definitionEn: 'Respecting passenger religious requirements (prayer, food, dress).', definitionTr: 'Yolcunun dini gereksinimlerine saygı (dua, yemek, kıyafet).',
    examples: [{ en: 'Mecca direction indicator.', tr: 'Mekke yönü göstergesi.' }],
    relatedTerms: ['halal', 'kosher', 'qibla'],
  },
  { id: 'voc_cabin_123', term: 'halal', termTr: 'helal', pronunciation: '/həˈlɑːl/', category: 'cultural', difficulty: 2,
    definitionEn: 'Permissible food per Islamic law; HNML special meal code.', definitionTr: 'İslam hukukunca izin verilen yemek; HNML özel kod.',
    examples: [{ en: 'Halal certified meal.', tr: 'Helal sertifikalı yemek.' }],
    relatedTerms: ['kosher', 'special meal', 'religious'],
  },
  { id: 'voc_cabin_124', term: 'kosher', termTr: 'koşer', pronunciation: '/ˈkəʊ.ʃər/', category: 'cultural', difficulty: 2,
    definitionEn: 'Permissible food per Jewish law; KSML special meal code.', definitionTr: 'Yahudi hukukunca izin verilen yemek; KSML özel kod.',
    examples: [{ en: 'Kosher meal sealed.', tr: 'Koşer yemek mühürlü.' }],
    relatedTerms: ['halal', 'special meal', 'religious'],
  },
  { id: 'voc_cabin_125', term: 'qibla', termTr: 'kıble (Mekke yönü)', pronunciation: '/ˈkɪb.lə/', category: 'cultural', difficulty: 4,
    definitionEn: 'Direction of Mecca — shown on screens for Muslim passengers.', definitionTr: 'Mekke yönü — Müslüman yolcular için ekranda gösterilir.',
    examples: [{ en: 'Qibla indicator on IFE.', tr: 'IFE\'de kıble göstergesi.' }],
    relatedTerms: ['Mecca', 'prayer', 'religious'],
  },
  { id: 'voc_cabin_126', term: 'Ramadan', termTr: 'Ramazan', pronunciation: '/ˌræm.əˈdɑːn/', category: 'cultural', difficulty: 3,
    definitionEn: 'Islamic month of fasting; some passengers fast during daytime flights.', definitionTr: 'İslami oruç ayı; bazı yolcular gündüz uçuşlarda oruç tutar.',
    examples: [{ en: 'Iftar meal during Ramadan.', tr: 'Ramazan\'da iftar yemeği.' }],
    relatedTerms: ['fasting', 'iftar', 'religious'],
  },
  { id: 'voc_cabin_127', term: 'VIP service', termTr: 'VIP servisi', pronunciation: '/ˌviː.aɪˈpiː ˈsɜː.vɪs/', category: 'service', difficulty: 3,
    definitionEn: 'Highest-tier service for very important persons (heads of state, celebrities).', definitionTr: 'Çok önemli kişiler için en üst tier servis (devlet başkanları, ünlüler).',
    examples: [{ en: 'VIP discreet handling.', tr: 'VIP gizli işlem.' }],
    relatedTerms: ['VVIP', 'CIP', 'protocol'],
  },
  { id: 'voc_cabin_128', term: 'diplomatic passenger', termTr: 'diplomatik yolcu', pronunciation: '/ˌdɪp.ləˈmæt.ɪk ˈpæs.ən.dʒər/', category: 'special', difficulty: 4,
    definitionEn: 'Government diplomat with diplomatic passport and immunity.', definitionTr: 'Diplomatik pasaport ve dokunulmazlığı olan hükümet diplomatı.',
    examples: [{ en: 'Diplomatic passport priority.', tr: 'Diplomatik pasaport önceliği.' }],
    relatedTerms: ['VIP', 'protocol', 'immunity'],
  },
  { id: 'voc_cabin_129', term: 'protocol', termTr: 'protokol', pronunciation: '/ˈprəʊ.tə.kɒl/', category: 'service', difficulty: 3,
    definitionEn: 'Formal procedures and etiquette for diplomatic/VIP handling.', definitionTr: 'Diplomatik/VIP işlem için resmi prosedür ve etiket.',
    examples: [{ en: 'Follow protocol strictly.', tr: 'Protokolü sıkı takip et.' }],
    relatedTerms: ['etiquette', 'VIP', 'diplomatic'],
  },
  { id: 'voc_cabin_130', term: 'discreet handling', termTr: 'gizli işlem', pronunciation: '/dɪˈskriːt ˈhæn.dlɪŋ/', category: 'service', difficulty: 4,
    definitionEn: 'Handling celebrities/VIPs without drawing attention.', definitionTr: 'Ünlüler/VIP\'leri dikkat çekmeden işlem.',
    examples: [{ en: 'Discreet handling for celebrities.', tr: 'Ünlüler için gizli işlem.' }],
    relatedTerms: ['VIP', 'celebrity', 'privacy'],
  },

  // Senior crew & wellness (10)
  { id: 'voc_cabin_131', term: 'crew briefing', termTr: 'ekip brifingi', pronunciation: '/kruː ˈbriː.fɪŋ/', category: 'coordination', difficulty: 2,
    definitionEn: 'Pre-flight meeting led by purser covering safety, service, special pax.', definitionTr: 'Purser tarafından yönetilen, emniyet/servis/özel yolcuyu kapsayan brifing.',
    examples: [{ en: 'Briefing 1 hour before departure.', tr: 'Brifing kalkıştan 1 saat önce.' }],
    relatedTerms: ['purser', 'pre-flight', 'briefing'],
  },
  { id: 'voc_cabin_132', term: 'time management', termTr: 'zaman yönetimi', pronunciation: '/taɪm ˈmæn.ɪdʒ.mənt/', category: 'leadership', difficulty: 3,
    definitionEn: 'Skill of planning service flow within tight schedules.', definitionTr: 'Sıkı programda servis akışı planlama becerisi.',
    examples: [{ en: 'Tight turnaround needs time mgmt.', tr: 'Sıkı turnaround zaman yönetimi gerektirir.' }],
    relatedTerms: ['turnaround', 'efficiency', 'planning'],
  },
  { id: 'voc_cabin_133', term: 'conflict resolution', termTr: 'çatışma çözümü', pronunciation: '/ˈkɒn.flɪkt ˌrez.əˈluː.ʃən/', category: 'leadership', difficulty: 4,
    definitionEn: 'Managing disagreements between crew or with passengers.', definitionTr: 'Ekip içi veya yolcu ile anlaşmazlıkların yönetimi.',
    examples: [{ en: 'Resolve cabin disputes diplomatically.', tr: 'Kabin tartışmalarını diplomatik çöz.' }],
    relatedTerms: ['mediation', 'communication', 'diplomacy'],
  },
  { id: 'voc_cabin_134', term: 'performance review', termTr: 'performans değerlendirme', pronunciation: '/pəˈfɔː.məns rɪˈvjuː/', category: 'career', difficulty: 3,
    definitionEn: 'Annual evaluation of crew member by purser/manager.', definitionTr: 'Purser/yönetici tarafından yıllık ekip üyesi değerlendirmesi.',
    examples: [{ en: 'Annual performance review.', tr: 'Yıllık performans değerlendirme.' }],
    relatedTerms: ['promotion', 'feedback', 'KPI'],
  },
  { id: 'voc_cabin_135', term: 'mentor', termTr: 'mentor', pronunciation: '/ˈmen.tɔː/', category: 'career', difficulty: 2,
    definitionEn: 'Senior crew guiding junior development.', definitionTr: 'Junior gelişimini yönlendiren kıdemli ekip.',
    examples: [{ en: 'Senior crew mentor new hires.', tr: 'Kıdemli ekip yeni alınanları mentor eder.' }],
    relatedTerms: ['training', 'mentoring', 'junior'],
  },
  { id: 'voc_cabin_136', term: 'jet lag', termTr: 'jet lag', pronunciation: '/dʒet læɡ/', category: 'wellness', difficulty: 2,
    definitionEn: 'Temporary disorder from crossing time zones quickly.', definitionTr: 'Hızla saat dilimi geçmekten kaynaklı geçici bozukluk.',
    examples: [{ en: 'Manage jet lag with sleep schedule.', tr: 'Jet lag\'ı uyku planıyla yönet.' }],
    relatedTerms: ['fatigue', 'time zone', 'circadian'],
  },
  { id: 'voc_cabin_137', term: 'circadian rhythm', termTr: 'sirkadiyen ritim', pronunciation: '/sɜːˈkeɪ.di.ən ˈrɪð.əm/', category: 'wellness', difficulty: 4,
    definitionEn: '24-hour body cycle disrupted by long-haul flying.', definitionTr: 'Long-haul uçuşla bozulan 24 saatlik vücut döngüsü.',
    examples: [{ en: 'Circadian rhythm out of sync.', tr: 'Sirkadiyen ritim senkronsuz.' }],
    relatedTerms: ['jet lag', 'sleep', 'fatigue'],
  },
  { id: 'voc_cabin_138', term: 'mental health', termTr: 'ruh sağlığı', pronunciation: '/ˈmen.təl helθ/', category: 'wellness', difficulty: 3,
    definitionEn: 'Psychological well-being of crew members.', definitionTr: 'Ekip üyelerinin psikolojik refahı.',
    examples: [{ en: 'EAP for mental health support.', tr: 'Ruh sağlığı desteği için EAP.' }],
    relatedTerms: ['EAP', 'well-being', 'support'],
  },
  { id: 'voc_cabin_139', term: 'EAP', termTr: 'EAP (Çalışan Yardım Programı)', pronunciation: '/iː eɪ piː/', category: 'wellness', difficulty: 4,
    definitionEn: 'Employee Assistance Program — counseling and support services.', definitionTr: 'Çalışan Yardım Programı — danışmanlık ve destek.',
    examples: [{ en: 'EAP confidential counseling.', tr: 'EAP gizli danışmanlık.' }],
    relatedTerms: ['mental health', 'support', 'counseling'],
  },
  { id: 'voc_cabin_140', term: 'roster bidding', termTr: 'roster bidding', pronunciation: '/ˈrɒs.tər ˈbɪd.ɪŋ/', category: 'work', difficulty: 4,
    definitionEn: 'System where crew bids for preferred routes/dates by seniority.', definitionTr: 'Ekibin kıdeme göre tercih ettiği rota/tarihi seçtiği sistem.',
    examples: [{ en: 'Senior crew bid first.', tr: 'Kıdemli ekip önce bid eder.' }],
    relatedTerms: ['seniority', 'roster', 'preference'],
  },
];
