/**
 * Kabin Memuru Faz 1 — İlk 10 vocabulary term seed verisi.
 */
import type { VocabularyTerm } from './pilotVocab';

export const CABIN_VOCAB_FAZ1: VocabularyTerm[] = [
  {
    id: 'voc_cabin_001',
    term: 'cabin crew',
    termTr: 'kabin ekibi',
    pronunciation: '/ˈkæb.ɪn kruː/',
    category: 'staff',
    difficulty: 1,
    definitionEn: 'The flight attendants and stewards working in the passenger cabin.',
    definitionTr: 'Yolcu kabininde çalışan hostes ve stewardlar.',
    examples: [
      { en: 'Cabin crew, prepare for departure.', tr: 'Kabin ekibi, kalkışa hazırlanın.' },
      { en: 'Our cabin crew speaks four languages.', tr: 'Kabin ekibimiz 4 dil konuşuyor.' },
    ],
    relatedTerms: ['flight attendant', 'purser', 'steward'],
  },
  {
    id: 'voc_cabin_002',
    term: 'fasten seatbelt',
    termTr: 'emniyet kemerini bağla',
    pronunciation: '/ˈfæs.ən ˈsiːt.belt/',
    category: 'safety',
    difficulty: 1,
    definitionEn: 'To secure the seatbelt across the lap before takeoff, landing, or turbulence.',
    definitionTr: 'Kalkış, iniş veya türbülans öncesi kemerin bele bağlanması.',
    examples: [
      { en: '"Please fasten your seatbelt and stow your tray table."', tr: '"Lütfen kemerinizi bağlayın ve tepsinizi kapatın."' },
      { en: 'The seatbelt sign is on.', tr: 'Kemer takın işareti yanıyor.' },
    ],
    relatedTerms: ['seatbelt sign', 'turbulence', 'safety brief'],
  },
  {
    id: 'voc_cabin_003',
    term: 'galley',
    termTr: 'galley (kabin mutfak)',
    pronunciation: '/ˈɡæl.i/',
    category: 'cabin_area',
    difficulty: 2,
    definitionEn: 'The kitchen area on an aircraft where food and drinks are prepared.',
    definitionTr: 'Yiyecek ve içeceklerin hazırlandığı uçak içi mutfak bölgesi.',
    examples: [
      { en: 'Coffee is brewing in the forward galley.', tr: 'Ön galley\'de kahve hazırlanıyor.' },
      { en: 'Trolleys are stored in the galley between services.', tr: 'Trolley\'ler servisler arasında galley\'de durur.' },
    ],
    relatedTerms: ['trolley', 'cart', 'jumpseat'],
  },
  {
    id: 'voc_cabin_004',
    term: 'evacuation slide',
    termTr: 'tahliye kaydırağı',
    pronunciation: '/ɪˌvæk.juˈeɪ.ʃən slaɪd/',
    category: 'emergency',
    difficulty: 3,
    definitionEn: 'An inflatable slide deployed during emergency evacuation to help passengers exit safely.',
    definitionTr: 'Acil durum tahliyesinde yolcuların güvenli inişi için açılan şişme kaydırak.',
    examples: [
      { en: 'Doors armed: slides will deploy if opened.', tr: 'Kapılar kuruldu: açılırsa kaydıraklar şişer.' },
      { en: 'Inspect the evacuation slide before each flight.', tr: 'Her uçuş öncesi tahliye kaydırağını kontrol et.' },
    ],
    relatedTerms: ['doors armed', 'evacuation', 'emergency exit'],
  },
  {
    id: 'voc_cabin_005',
    term: 'unruly passenger',
    termTr: 'uyumsuz yolcu',
    pronunciation: '/ʌnˈruː.li ˈpæs.ən.dʒər/',
    category: 'passenger',
    difficulty: 3,
    definitionEn: 'A passenger whose behavior threatens flight safety, order, or discipline.',
    definitionTr: 'Davranışı uçuş emniyetini, düzenini veya disiplinini tehdit eden yolcu.',
    examples: [
      { en: 'File an unruly passenger report after the incident.', tr: 'Olay sonrası uyumsuz yolcu raporu doldur.' },
      { en: 'De-escalate verbally before physical restraint.', tr: 'Fiziksel müdahaleden önce sözlü olarak yatıştır.' },
    ],
    icaoReference: 'ICAO Annex 9 + Tokyo Convention',
    relatedTerms: ['de-escalation', 'restraint', 'incident report'],
  },
  {
    id: 'voc_cabin_006',
    term: 'brace position',
    termTr: 'sarılma pozisyonu',
    pronunciation: '/breɪs pəˈzɪʃ.ən/',
    category: 'emergency',
    difficulty: 3,
    definitionEn: 'A defensive body posture to minimize injury before impact or crash landing.',
    definitionTr: 'Çarpma veya acil iniş öncesi yaralanmayı en aza indiren savunma pozisyonu.',
    examples: [
      { en: '"Brace! Brace! Brace!"', tr: '"Sarıl! Sarıl! Sarıl!"' },
      { en: 'Demonstrate brace position during pre-flight briefing.', tr: 'Uçuş öncesi brifinginde sarılma pozisyonunu göster.' },
    ],
    icaoReference: 'ICAO Doc 9683',
    relatedTerms: ['emergency briefing', 'impact', 'crash landing'],
  },
  {
    id: 'voc_cabin_007',
    term: 'special service request',
    termTr: 'özel servis talebi (SSR)',
    pronunciation: '/ˈspeʃ.əl ˈsɜː.vɪs rɪˈkwest/',
    category: 'passenger',
    difficulty: 3,
    definitionEn: 'A coded request for special needs: wheelchair, unaccompanied minor, medical case, special meal.',
    definitionTr: 'Özel ihtiyaç bildiren kodlu talep: tekerlekli sandalye, eşliksiz çocuk, tıbbi durum, özel yemek.',
    examples: [
      { en: 'Check the SSR list during pre-flight briefing.', tr: 'Uçuş öncesi brifinginde SSR listesini kontrol et.' },
      { en: 'Today: 2 WCHR, 1 UM, 1 MEDA.', tr: 'Bugün: 2 tekerlekli, 1 UM, 1 MEDA.' },
    ],
    icaoReference: 'IATA SSR codes',
    relatedTerms: ['UM', 'MEDA', 'VGML', 'WCHR'],
  },
  {
    id: 'voc_cabin_008',
    term: 'doors armed',
    termTr: 'kapılar kuruldu',
    pronunciation: '/dɔːrz ɑːmd/',
    category: 'safety',
    difficulty: 2,
    definitionEn: 'Cabin door state: evacuation slide will deploy automatically if opened.',
    definitionTr: 'Kapı kurulu durumda: açılırsa tahliye kaydırağı otomatik şişer.',
    examples: [
      { en: '"Cabin crew, doors to automatic and cross check."', tr: '"Kabin ekibi, kapılar otomatiğe ve çapraz kontrol."' },
      { en: 'Disarm doors before disembarking.', tr: 'Yolcu indirmeden önce kapıları manuele al.' },
    ],
    relatedTerms: ['cross check', 'disarm', 'evacuation slide'],
  },
  {
    id: 'voc_cabin_009',
    term: 'turbulence',
    termTr: 'türbülans',
    pronunciation: '/ˈtɜː.bjə.ləns/',
    category: 'flight',
    difficulty: 2,
    definitionEn: 'Irregular motion of air causing the aircraft to shake.',
    definitionTr: 'Uçağın sallanmasına neden olan düzensiz hava hareketi.',
    examples: [
      { en: 'Captain announces moderate turbulence ahead.', tr: 'Kaptan ileride orta türbülans olduğunu duyurur.' },
      { en: 'Cabin crew, take your seats — severe turbulence.', tr: 'Kabin ekibi, koltuklara — şiddetli türbülans.' },
    ],
    relatedTerms: ['light', 'moderate', 'severe', 'wind shear'],
  },
  {
    id: 'voc_cabin_010',
    term: 'oxygen mask',
    termTr: 'oksijen maskesi',
    pronunciation: '/ˈɒk.sɪ.dʒən mɑːsk/',
    category: 'emergency',
    difficulty: 2,
    definitionEn: 'A breathing apparatus deployed from the overhead panel during cabin depressurization.',
    definitionTr: 'Kabin basınç kaybında tavandan inen solunum cihazı.',
    examples: [
      { en: '"Pull the mask towards you to start the flow of oxygen."', tr: '"Maskeyi kendinize doğru çekin, oksijen akışı başlasın."' },
      { en: 'Secure your own mask before assisting others.', tr: 'Önce kendi maskenizi takın, sonra başkalarına yardım edin.' },
    ],
    relatedTerms: ['depressurization', 'emergency descent', 'cabin pressure'],
  },
];
