/**
 * Yer Hizmetleri vocabulary seed — Faz 1.
 * 60 terim: pushback, marshalling, baggage, fuel, de-icing, ramp safety.
 */
import type { VocabularyTerm } from './pilotVocab';

export const GROUND_VOCAB_FAZ1: VocabularyTerm[] = [
  // ===== RAMP & MARSHALLING (10) =====
  { id: 'voc_ground_001', term: 'ramp', termTr: 'apron / ramp', pronunciation: '/ræmp/', category: 'ramp', difficulty: 1,
    definitionEn: 'The paved area where aircraft park, load, fuel, and undergo ground handling.',
    definitionTr: 'Uçakların park ettiği, yüklendiği, yakıtlandığı asfalt alan.',
    examples: [
      { en: 'Aircraft taxiing on the ramp.', tr: 'Uçak rampta taksi yapıyor.' },
      { en: 'Ramp safety briefing daily.', tr: 'Günlük ramp emniyet brifingi.' },
    ],
    relatedTerms: ['apron', 'taxiway', 'tarmac'],
  },
  { id: 'voc_ground_002', term: 'marshalling', termTr: 'yer yönlendirme', pronunciation: '/ˈmɑː.ʃəl.ɪŋ/', category: 'ramp', difficulty: 2,
    definitionEn: 'Visual signaling to guide aircraft on the ramp using hand gestures or wands.',
    definitionTr: 'El işareti veya wand ile uçağı rampada yönlendirme.',
    examples: [
      { en: 'Marshaller signals "stop".', tr: 'Marshaller "stop" işareti veriyor.' },
      { en: 'Use illuminated wands at night.', tr: 'Geceleri ışıklı wand kullan.' },
    ],
    relatedTerms: ['marshaller', 'wand', 'hand signal'],
  },
  { id: 'voc_ground_003', term: 'wand', termTr: 'wand (ışıklı çubuk)', pronunciation: '/wɒnd/', category: 'equipment', difficulty: 1,
    definitionEn: 'Illuminated stick used by marshallers to signal aircraft.',
    definitionTr: 'Marshaller\'ın uçağa işaret vermek için kullandığı ışıklı çubuk.',
    examples: [
      { en: 'Battery-powered wands.', tr: 'Pille çalışan wand\'lar.' },
      { en: 'Cross wands = stop.', tr: 'Çapraz wand = dur.' },
    ],
    relatedTerms: ['marshaller', 'signal', 'hand signal'],
  },
  { id: 'voc_ground_004', term: 'chock', termTr: 'takoz', pronunciation: '/tʃɒk/', category: 'equipment', difficulty: 1,
    definitionEn: 'Wedge placed in front of and behind aircraft wheels to prevent rolling.',
    definitionTr: 'Uçak tekerleklerinin önüne ve arkasına konulan, kaymayı önleyen takoz.',
    examples: [
      { en: 'Chock wheels before brake release.', tr: 'Fren bırakmadan önce takozları yerleştir.' },
      { en: '"Chocks in" — aircraft secured.', tr: '"Chocks in" — uçak emniyetli.' },
    ],
    relatedTerms: ['wheel', 'parking brake', 'block time'],
  },
  { id: 'voc_ground_005', term: 'tug', termTr: 'tug (çekici)', pronunciation: '/tʌɡ/', category: 'equipment', difficulty: 2,
    definitionEn: 'Specialized vehicle used to push or tow aircraft on the ramp.',
    definitionTr: 'Uçağı rampada itmek veya çekmek için özel araç.',
    examples: [
      { en: 'Tug attached for pushback.', tr: 'Pushback için tug bağlandı.' },
      { en: 'Towbarless tug.', tr: 'Towbarsız tug.' },
    ],
    relatedTerms: ['pushback', 'towbar', 'GSE'],
  },
  { id: 'voc_ground_006', term: 'towbar', termTr: 'çekme barı', pronunciation: '/ˈtəʊ.bɑːr/', category: 'equipment', difficulty: 2,
    definitionEn: 'Steel bar connecting tug to nose gear for pushback or towing.',
    definitionTr: 'Pushback veya çekme için tug\'ı nose gear\'a bağlayan çelik bar.',
    examples: [
      { en: 'Connect towbar to nose gear.', tr: 'Towbar\'ı nose gear\'a bağla.' },
      { en: 'Aircraft-specific towbar.', tr: 'Uçağa özel towbar.' },
    ],
    relatedTerms: ['tug', 'nose gear', 'pushback'],
  },
  { id: 'voc_ground_007', term: 'GSE', termTr: 'GSE (Yer Servis Ekipmanı)', pronunciation: '/dʒiː es iː/', category: 'equipment', difficulty: 2,
    definitionEn: 'Ground Support Equipment — all vehicles used in ground handling.',
    definitionTr: 'Yer Servis Ekipmanı — yer hizmetlerinde kullanılan tüm araçlar.',
    examples: [
      { en: 'GSE includes tugs, belt loaders, GPU.', tr: 'GSE\'ye tug, belt loader, GPU dahil.' },
      { en: 'GSE training certification.', tr: 'GSE eğitim sertifikası.' },
    ],
    relatedTerms: ['tug', 'GPU', 'belt loader', 'catering truck'],
  },
  { id: 'voc_ground_008', term: 'GPU', termTr: 'GPU (Yer Güç Ünitesi)', pronunciation: '/dʒiː piː juː/', category: 'equipment', difficulty: 2,
    definitionEn: 'Ground Power Unit — provides electrical power when engines are off.',
    definitionTr: 'Yer Güç Ünitesi — motorlar kapalıyken elektrik sağlar.',
    examples: [
      { en: 'Connect GPU to forward power port.', tr: 'GPU\'yu ön güç portuna bağla.' },
      { en: '400 Hz, 115 V AC standard.', tr: '400 Hz, 115 V AC standart.' },
    ],
    relatedTerms: ['external power', 'APU', 'GSE'],
  },
  { id: 'voc_ground_009', term: 'jet bridge', termTr: 'körük (jet bridge)', pronunciation: '/dʒet brɪdʒ/', category: 'equipment', difficulty: 2,
    definitionEn: 'Movable enclosed walkway connecting gate to aircraft door.',
    definitionTr: 'Gate\'i uçak kapısına bağlayan hareketli kapalı yürüyüş yolu.',
    examples: [
      { en: 'Position jet bridge to door 1L.', tr: 'Jet bridge\'i 1L kapısına yerleştir.' },
      { en: 'Operator certified for jet bridge.', tr: 'Jet bridge için sertifikalı operatör.' },
    ],
    relatedTerms: ['airbridge', 'gate', 'boarding'],
  },
  { id: 'voc_ground_010', term: 'air stair', termTr: 'merdiven', pronunciation: '/eər steər/', category: 'equipment', difficulty: 1,
    definitionEn: 'Mobile staircase used for boarding/disembarking when no jet bridge.',
    definitionTr: 'Jet bridge olmadığında boarding/iniş için hareketli merdiven.',
    examples: [
      { en: 'Position air stair at door 2L.', tr: 'Air stair\'ı 2L kapısına yerleştir.' },
      { en: 'Self-propelled air stair.', tr: 'Kendi tahrikli air stair.' },
    ],
    relatedTerms: ['boarding', 'remote stand', 'mobile stairs'],
  },

  // ===== PUSHBACK & TAXI (8) =====
  { id: 'voc_ground_011', term: 'pushback', termTr: 'geri itme', pronunciation: '/ˈpʊʃ.bæk/', category: 'pushback', difficulty: 2,
    definitionEn: 'Procedure of pushing aircraft backwards from gate using a tug.',
    definitionTr: 'Tug kullanılarak uçağın gate\'ten geri itilmesi.',
    examples: [
      { en: '"Brakes set, ready for pushback."', tr: '"Frenler kilitli, pushback için hazır."' },
      { en: 'Push approved, face north.', tr: 'Push onaylı, kuzeye dön.' },
    ],
    relatedTerms: ['tug', 'towbar', 'gate'],
  },
  { id: 'voc_ground_012', term: 'brakes set', termTr: 'frenler kilitli', pronunciation: '/breɪks set/', category: 'pushback', difficulty: 2,
    definitionEn: 'Confirmation by pilot that parking brakes are engaged.',
    definitionTr: 'Pilotun park frenlerinin devrede olduğunu teyit etmesi.',
    examples: [
      { en: 'Pilot: "Brakes set, ready for tow."', tr: 'Pilot: "Frenler kilitli, tow için hazır."' },
      { en: 'Headset ground crew confirms.', tr: 'Headset\'teki yer ekibi teyit eder.' },
    ],
    relatedTerms: ['parking brake', 'pushback', 'headset'],
  },
  { id: 'voc_ground_013', term: 'headset', termTr: 'kulaklık (haberleşme)', pronunciation: '/ˈhed.set/', category: 'communication', difficulty: 1,
    definitionEn: 'Wired or wireless intercom used between ground crew and pilots during pushback.',
    definitionTr: 'Pushback sırasında yer ekibi ile pilot arasında kullanılan kablolu/kablosuz intercom.',
    examples: [
      { en: 'Plug headset to nose port.', tr: 'Kulaklığı burun portuna tak.' },
      { en: '"Cleared to disconnect headset."', tr: '"Kulaklık çıkarmaya izin."' },
    ],
    relatedTerms: ['interphone', 'ground crew', 'pushback'],
  },
  { id: 'voc_ground_014', term: 'taxi', termTr: 'taksi (yer hareketi)', pronunciation: '/ˈtæk.si/', category: 'movement', difficulty: 1,
    definitionEn: 'Movement of an aircraft on the ground under its own power.',
    definitionTr: 'Bir uçağın yerde kendi gücüyle hareket etmesi.',
    examples: [
      { en: 'Tower: "Taxi to runway 27 via Alpha."', tr: 'Kule: "Alpha üzerinden pist 27\'ye taksi."' },
      { en: 'Follow-me car leads taxi.', tr: 'Follow-me arabası taksi yönlendirir.' },
    ],
    relatedTerms: ['taxiway', 'follow-me', 'pushback'],
  },
  { id: 'voc_ground_015', term: 'follow-me car', termTr: 'beni takip et arabası', pronunciation: '/ˈfɒl.əʊ miː kɑːr/', category: 'movement', difficulty: 2,
    definitionEn: 'Vehicle leading an aircraft to its parking position.',
    definitionTr: 'Uçağı park yerine yönlendiren araç.',
    examples: [
      { en: '"FOLLOW ME" sign on top.', tr: 'Üstte "FOLLOW ME" tabelası.' },
      { en: 'Used at large airports.', tr: 'Büyük havalimanlarında kullanılır.' },
    ],
    relatedTerms: ['marshaller', 'taxi', 'apron'],
  },
  { id: 'voc_ground_016', term: 'parking position', termTr: 'park yeri', pronunciation: '/ˈpɑː.kɪŋ pəˈzɪʃ.ən/', category: 'ramp', difficulty: 1,
    definitionEn: 'Designated location on the ramp where aircraft parks.',
    definitionTr: 'Uçağın park ettiği rampada belirlenmiş konum.',
    examples: [
      { en: 'Parking position B14.', tr: 'Park yeri B14.' },
      { en: 'Stop bar marks final position.', tr: 'Stop bar son konumu işaretler.' },
    ],
    relatedTerms: ['gate', 'stand', 'apron'],
  },
  { id: 'voc_ground_017', term: 'stand', termTr: 'stand (uçak park alanı)', pronunciation: '/stænd/', category: 'ramp', difficulty: 2,
    definitionEn: 'Specific aircraft parking spot, may be contact (jet bridge) or remote.',
    definitionTr: 'Belirli uçak park yeri, contact (jet bridge\'li) veya remote olabilir.',
    examples: [
      { en: 'Contact stand: jet bridge available.', tr: 'Contact stand: jet bridge var.' },
      { en: 'Remote stand: bus + air stairs.', tr: 'Remote stand: otobüs + merdiven.' },
    ],
    relatedTerms: ['gate', 'remote stand', 'contact stand'],
  },
  { id: 'voc_ground_018', term: 'gate', termTr: 'gate (kapı)', pronunciation: '/ɡeɪt/', category: 'ramp', difficulty: 1,
    definitionEn: 'Specific gate/door where passengers board or disembark.',
    definitionTr: 'Yolcuların binip indiği belirli gate/kapı.',
    examples: [
      { en: 'Gate A14 for flight TK1234.', tr: 'TK1234 için gate A14.' },
      { en: 'Gate change announcement.', tr: 'Gate değişikliği anonsu.' },
    ],
    relatedTerms: ['stand', 'jet bridge', 'boarding'],
  },

  // ===== BAGGAGE (10) =====
  { id: 'voc_ground_019', term: 'baggage handler', termTr: 'bagaj görevlisi', pronunciation: '/ˈbæɡ.ɪdʒ ˈhæn.dlər/', category: 'baggage', difficulty: 1,
    definitionEn: 'Ground crew member who loads/unloads baggage.',
    definitionTr: 'Bagaj yükleyen/boşaltan yer ekibi üyesi.',
    examples: [
      { en: 'Baggage handlers wear hi-vis vests.', tr: 'Bagaj görevlileri hi-vis yelek giyer.' },
      { en: 'Lift safely: bend knees.', tr: 'Güvenli kaldır: dizleri bük.' },
    ],
    relatedTerms: ['ramp agent', 'loader', 'belt loader'],
  },
  { id: 'voc_ground_020', term: 'belt loader', termTr: 'bant yükleyici', pronunciation: '/belt ˈləʊ.dər/', category: 'equipment', difficulty: 2,
    definitionEn: 'Vehicle with a conveyor belt for loading baggage into cargo hold.',
    definitionTr: 'Bagajı kargo bölmesine yüklemek için konveyör bantlı araç.',
    examples: [
      { en: 'Position belt loader at cargo door.', tr: 'Belt loader\'ı kargo kapısına yerleştir.' },
      { en: 'Maintain 30° belt angle.', tr: '30° bant açısı koru.' },
    ],
    relatedTerms: ['conveyor', 'cargo hold', 'loader'],
  },
  { id: 'voc_ground_021', term: 'cargo hold', termTr: 'kargo bölmesi', pronunciation: '/ˈkɑː.ɡəʊ həʊld/', category: 'baggage', difficulty: 2,
    definitionEn: 'Lower compartment of aircraft for baggage and cargo.',
    definitionTr: 'Bagaj ve kargo için uçağın alt bölmesi.',
    examples: [
      { en: 'Forward and aft cargo holds.', tr: 'Ön ve arka kargo bölmeleri.' },
      { en: 'ULDs loaded into cargo hold.', tr: 'ULD\'ler kargo bölmesine yüklenir.' },
    ],
    relatedTerms: ['ULD', 'cargo door', 'baggage'],
  },
  { id: 'voc_ground_022', term: 'ULD', termTr: 'ULD (Birim Yük Cihazı)', pronunciation: '/juː el diː/', category: 'baggage', difficulty: 3,
    definitionEn: 'Unit Load Device — container or pallet used to load cargo.',
    definitionTr: 'Birim Yük Cihazı — kargo yüklemek için kullanılan konteyner veya palet.',
    examples: [
      { en: 'AKE container is a common ULD.', tr: 'AKE konteyneri yaygın ULD.' },
      { en: 'ULD weight checked at scale.', tr: 'ULD ağırlığı tartıda kontrol.' },
    ],
    relatedTerms: ['container', 'pallet', 'AKE'],
  },
  { id: 'voc_ground_023', term: 'baggage tag', termTr: 'bagaj etiketi', pronunciation: '/ˈbæɡ.ɪdʒ tæɡ/', category: 'baggage', difficulty: 1,
    definitionEn: 'Identification tag attached to checked baggage.',
    definitionTr: 'Check-in bagajına takılan kimlik etiketi.',
    examples: [
      { en: '3-letter destination code on tag.', tr: 'Etikette 3 harfli destinasyon kodu.' },
      { en: 'Priority tag for VIP.', tr: 'VIP için priority tag.' },
    ],
    relatedTerms: ['checked baggage', 'IATA code', 'priority'],
  },
  { id: 'voc_ground_024', term: 'oversized baggage', termTr: 'büyük boy bagaj', pronunciation: '/ˌəʊ.vəˈsaɪzd ˈbæɡ.ɪdʒ/', category: 'baggage', difficulty: 2,
    definitionEn: 'Bags exceeding standard size, requiring special handling.',
    definitionTr: 'Standart boyutu aşan, özel işlem gerektiren bagaj.',
    examples: [
      { en: 'Skis: oversized baggage.', tr: 'Kayak takımı: büyük boy bagaj.' },
      { en: 'Separate counter for oversized.', tr: 'Büyük boy için ayrı kontuar.' },
    ],
    relatedTerms: ['fragile', 'sports equipment', 'OOG'],
  },
  { id: 'voc_ground_025', term: 'fragile', termTr: 'kırılır (fragile)', pronunciation: '/ˈfrædʒ.aɪl/', category: 'baggage', difficulty: 2,
    definitionEn: 'Tag indicating delicate items requiring careful handling.',
    definitionTr: 'Dikkatli işlem gerektiren hassas eşyaları belirten etiket.',
    examples: [
      { en: 'Fragile sticker on top.', tr: 'Üstte fragile etiketi.' },
      { en: 'Hand-carry to cargo hold.', tr: 'Elle kargo bölmesine taşı.' },
    ],
    relatedTerms: ['handle with care', 'special handling', 'breakable'],
  },
  { id: 'voc_ground_026', term: 'baggage claim', termTr: 'bagaj alımı', pronunciation: '/ˈbæɡ.ɪdʒ kleɪm/', category: 'baggage', difficulty: 1,
    definitionEn: 'Area where passengers retrieve checked baggage after a flight.',
    definitionTr: 'Yolcuların uçuştan sonra check-in bagajlarını aldığı alan.',
    examples: [
      { en: 'Baggage claim carousel 5.', tr: 'Bagaj alımı bant 5.' },
      { en: 'Lost baggage report at desk.', tr: 'Kayıp bagaj raporu kontuarda.' },
    ],
    relatedTerms: ['carousel', 'checked baggage', 'lost baggage'],
  },
  { id: 'voc_ground_027', term: 'carousel', termTr: 'bagaj bandı', pronunciation: '/ˌkær.əˈsel/', category: 'baggage', difficulty: 1,
    definitionEn: 'Conveyor belt where checked baggage is delivered to passengers.',
    definitionTr: 'Check-in bagajının yolculara teslim edildiği konveyör bant.',
    examples: [
      { en: 'Carousel 5 for flight TK1234.', tr: 'TK1234 için bant 5.' },
      { en: 'Wait for your bag at carousel.', tr: 'Bagajınızı bantta bekleyin.' },
    ],
    relatedTerms: ['baggage claim', 'belt', 'conveyor'],
  },
  { id: 'voc_ground_028', term: 'lost baggage', termTr: 'kayıp bagaj', pronunciation: '/lɒst ˈbæɡ.ɪdʒ/', category: 'baggage', difficulty: 2,
    definitionEn: 'Baggage that did not arrive with the passenger; subject of report.',
    definitionTr: 'Yolcuyla birlikte gelmeyen, raporlanan bagaj.',
    examples: [
      { en: 'File PIR (Property Irregularity Report).', tr: 'PIR (Property Irregularity Report) doldur.' },
      { en: 'Compensation per Montreal Convention.', tr: 'Montreal Sözleşmesi\'ne göre tazminat.' },
    ],
    relatedTerms: ['PIR', 'delayed baggage', 'compensation'],
  },

  // ===== FUEL (5) =====
  { id: 'voc_ground_029', term: 'refueler', termTr: 'yakıt aracı', pronunciation: '/ˌriːˈfjuːə.lər/', category: 'fuel', difficulty: 2,
    definitionEn: 'Truck or hydrant cart that delivers fuel to aircraft.',
    definitionTr: 'Uçağa yakıt sağlayan tanker veya hidrant arabası.',
    examples: [
      { en: 'Refueler arrives 30 min before departure.', tr: 'Refueler kalkıştan 30 dk önce gelir.' },
      { en: 'Hydrant pit access.', tr: 'Hidrant pit erişimi.' },
    ],
    relatedTerms: ['fuel truck', 'hydrant', 'fuel'],
  },
  { id: 'voc_ground_030', term: 'fuel truck', termTr: 'yakıt tankeri', pronunciation: '/fjuːəl trʌk/', category: 'equipment', difficulty: 1,
    definitionEn: 'Mobile tank truck delivering fuel to remote stands.',
    definitionTr: 'Remote stand\'lara yakıt sağlayan hareketli tanker.',
    examples: [
      { en: 'Capacity: 30,000 liters.', tr: 'Kapasite: 30.000 litre.' },
      { en: 'Bonding cable to aircraft.', tr: 'Uçağa bonding kablosu.' },
    ],
    relatedTerms: ['refueler', 'bonding cable', 'fuel hose'],
  },
  { id: 'voc_ground_031', term: 'bonding cable', termTr: 'topraklama kablosu', pronunciation: '/ˈbɒn.dɪŋ ˈkeɪ.bəl/', category: 'safety', difficulty: 3,
    definitionEn: 'Cable connecting fuel truck to aircraft, equalizing electrical potential.',
    definitionTr: 'Yakıt aracını uçağa bağlayan, elektrik potansiyelini dengeleyen kablo.',
    examples: [
      { en: 'Connect bonding before fueling.', tr: 'Yakıttan önce bonding bağla.' },
      { en: 'Prevents static spark.', tr: 'Statik kıvılcımı önler.' },
    ],
    relatedTerms: ['static electricity', 'fueling safety', 'ground'],
  },
  { id: 'voc_ground_032', term: 'fuel hose', termTr: 'yakıt hortumu', pronunciation: '/fjuːəl həʊz/', category: 'fuel', difficulty: 2,
    definitionEn: 'Hose carrying fuel from truck to aircraft fueling port.',
    definitionTr: 'Tankerden uçak yakıt portuna yakıt taşıyan hortum.',
    examples: [
      { en: 'Inspect hose for leaks.', tr: 'Hortumu kaçak için kontrol.' },
      { en: 'Replace damaged hose.', tr: 'Hasarlı hortumu değiştir.' },
    ],
    relatedTerms: ['nozzle', 'fueling port', 'leak'],
  },
  { id: 'voc_ground_033', term: 'Jet A', termTr: 'Jet A (havacılık yakıtı)', pronunciation: '/dʒet eɪ/', category: 'fuel', difficulty: 2,
    definitionEn: 'Standard kerosene-based fuel for turbine engines.',
    definitionTr: 'Türbin motorları için standart kerosen bazlı yakıt.',
    examples: [
      { en: 'Jet A flash point 38°C.', tr: 'Jet A parlama noktası 38°C.' },
      { en: 'Jet A-1 for international ops.', tr: 'Uluslararası için Jet A-1.' },
    ],
    relatedTerms: ['Jet A-1', 'AVGAS', 'kerosene'],
  },

  // ===== DE-ICING (5) =====
  { id: 'voc_ground_034', term: 'de-icing', termTr: 'buz çözme', pronunciation: '/diːˈaɪ.sɪŋ/', category: 'winter_ops', difficulty: 3,
    definitionEn: 'Removing ice/snow from aircraft surfaces using heated fluid.',
    definitionTr: 'Isıtılmış akışkan ile uçak yüzeylerinden buz/kar temizleme.',
    examples: [
      { en: 'De-ice before takeoff.', tr: 'Kalkıştan önce de-ice.' },
      { en: 'Type I fluid for de-icing.', tr: 'De-icing için Type I akışkan.' },
    ],
    relatedTerms: ['anti-icing', 'Type I fluid', 'holdover time'],
  },
  { id: 'voc_ground_035', term: 'anti-icing', termTr: 'buz önleme', pronunciation: '/ˌæn.tiˈaɪ.sɪŋ/', category: 'winter_ops', difficulty: 3,
    definitionEn: 'Applying fluid to prevent ice formation during taxi to runway.',
    definitionTr: 'Piste taksi sırasında buzlanmayı önlemek için akışkan uygulamak.',
    examples: [
      { en: 'Type IV fluid for anti-icing.', tr: 'Anti-icing için Type IV akışkan.' },
      { en: 'Holdover time: 30-90 min.', tr: 'Holdover süresi: 30-90 dakika.' },
    ],
    relatedTerms: ['Type IV fluid', 'holdover time', 'de-icing'],
  },
  { id: 'voc_ground_036', term: 'holdover time', termTr: 'holdover süresi', pronunciation: '/ˈhəʊld.əʊ.vər taɪm/', category: 'winter_ops', difficulty: 4,
    definitionEn: 'Time anti-icing fluid remains effective before takeoff.',
    definitionTr: 'Anti-icing akışkanının kalkışa kadar etkili kaldığı süre.',
    examples: [
      { en: 'Check holdover time chart.', tr: 'Holdover süresi tablosuna bak.' },
      { en: 'Recheck if holdover expired.', tr: 'Holdover dolduysa tekrar kontrol.' },
    ],
    relatedTerms: ['anti-icing', 'Type IV', 'recheck'],
  },
  { id: 'voc_ground_037', term: 'Type I fluid', termTr: 'Type I akışkan', pronunciation: '/taɪp wʌn ˈfluː.ɪd/', category: 'winter_ops', difficulty: 3,
    definitionEn: 'Heated, low-viscosity fluid for de-icing.',
    definitionTr: 'De-icing için ısıtılmış, düşük viskoziteli akışkan.',
    examples: [
      { en: 'Orange/red color.', tr: 'Turuncu/kırmızı renk.' },
      { en: 'Mixed with water.', tr: 'Suyla karıştırılır.' },
    ],
    relatedTerms: ['Type IV', 'de-icing', 'glycol'],
  },
  { id: 'voc_ground_038', term: 'Type IV fluid', termTr: 'Type IV akışkan', pronunciation: '/taɪp fɔː ˈfluː.ɪd/', category: 'winter_ops', difficulty: 3,
    definitionEn: 'High-viscosity fluid for anti-icing — clings to surfaces.',
    definitionTr: 'Yüksek viskoziteli anti-icing akışkanı — yüzeylere yapışır.',
    examples: [
      { en: 'Green color.', tr: 'Yeşil renk.' },
      { en: 'Sheds during takeoff roll.', tr: 'Kalkış koşusunda dökülür.' },
    ],
    relatedTerms: ['Type I', 'anti-icing', 'holdover time'],
  },

  // ===== SAFETY (8) =====
  { id: 'voc_ground_039', term: 'hi-vis vest', termTr: 'reflektörlü yelek', pronunciation: '/ˈhaɪ vɪz vest/', category: 'safety', difficulty: 1,
    definitionEn: 'High-visibility vest worn on the ramp for safety.',
    definitionTr: 'Rampada güvenlik için giyilen yüksek görünürlüklü yelek.',
    examples: [
      { en: 'Hi-vis required on ramp at all times.', tr: 'Rampada her zaman hi-vis zorunlu.' },
      { en: 'Reflective strips for night.', tr: 'Gece için yansıtıcı şeritler.' },
    ],
    relatedTerms: ['PPE', 'safety', 'ramp'],
  },
  { id: 'voc_ground_040', term: 'PPE', termTr: 'PPE (kişisel koruyucu)', pronunciation: '/piː piː iː/', category: 'safety', difficulty: 2,
    definitionEn: 'Personal Protective Equipment — vest, helmet, ear protection, gloves, shoes.',
    definitionTr: 'Kişisel Koruyucu Ekipman — yelek, baret, kulaklık, eldiven, ayakkabı.',
    examples: [
      { en: 'PPE inspection daily.', tr: 'Günlük PPE muayenesi.' },
      { en: 'No PPE = no ramp access.', tr: 'PPE yok = ramp erişimi yok.' },
    ],
    relatedTerms: ['hi-vis vest', 'safety shoes', 'ear protection'],
  },
  { id: 'voc_ground_041', term: 'ear protection', termTr: 'kulaklık (gürültü)', pronunciation: '/ɪər prəˈtek.ʃən/', category: 'safety', difficulty: 1,
    definitionEn: 'Earmuffs or earplugs protecting against high noise on ramp.',
    definitionTr: 'Rampadaki yüksek gürültüye karşı koruyan kulaklık veya tıkaç.',
    examples: [
      { en: 'Engine run: ear protection mandatory.', tr: 'Engine run: kulaklık zorunlu.' },
      { en: 'NRR 25+ dB rating.', tr: 'NRR 25+ dB derecelendirme.' },
    ],
    relatedTerms: ['PPE', 'noise', 'engine run'],
  },
  { id: 'voc_ground_042', term: 'safety shoes', termTr: 'çelik burunlu ayakkabı', pronunciation: '/ˈseɪf.ti ʃuːz/', category: 'safety', difficulty: 1,
    definitionEn: 'Steel-toe shoes protecting feet from impact and crushing.',
    definitionTr: 'Çelik burunlu, çarpma ve ezilmeye karşı ayağı koruyan ayakkabı.',
    examples: [
      { en: 'Steel toe + slip-resistant.', tr: 'Çelik burun + kaymaz taban.' },
      { en: 'Replace if compromised.', tr: 'Hasarlıysa değiştir.' },
    ],
    relatedTerms: ['PPE', 'steel toe', 'work boots'],
  },
  { id: 'voc_ground_043', term: 'jet blast', termTr: 'jet patlaması', pronunciation: '/dʒet blɑːst/', category: 'safety', difficulty: 3,
    definitionEn: 'High-velocity exhaust from jet engines, hazardous on ramp.',
    definitionTr: 'Jet motorlarından yüksek hızlı egzoz, rampada tehlikeli.',
    examples: [
      { en: 'Stay clear of jet blast zone.', tr: 'Jet blast bölgesinden uzak dur.' },
      { en: 'Can blow vehicles over.', tr: 'Araçları devirebilir.' },
    ],
    relatedTerms: ['exhaust', 'safety zone', 'ramp safety'],
  },
  { id: 'voc_ground_044', term: 'engine intake', termTr: 'motor emiş', pronunciation: '/ˈen.dʒɪn ˈɪn.teɪk/', category: 'safety', difficulty: 3,
    definitionEn: 'Front of engine that sucks in air; deadly suction zone.',
    definitionTr: 'Hava emen motor önü; ölümcül emiş bölgesi.',
    examples: [
      { en: 'Stay 5 m away from intake.', tr: 'Emişten 5 m uzak dur.' },
      { en: 'Engine running = forbidden zone.', tr: 'Motor çalışıyor = yasak bölge.' },
    ],
    relatedTerms: ['intake hazard', 'fan', 'safety zone'],
  },
  { id: 'voc_ground_045', term: 'FOD', termTr: 'FOD (yabancı cisim)', pronunciation: '/fɒd/', category: 'safety', difficulty: 2,
    definitionEn: 'Foreign Object Debris — anything that can damage aircraft.',
    definitionTr: 'Yabancı Cisim Atıkları — uçağa zarar verebilecek herhangi bir şey.',
    examples: [
      { en: 'FOD walk before pushback.', tr: 'Pushback öncesi FOD walk.' },
      { en: 'Pick up FOD on ramp.', tr: 'Rampadaki FOD\'u topla.' },
    ],
    relatedTerms: ['FOD walk', 'ramp inspection', 'damage'],
  },
  { id: 'voc_ground_046', term: 'spill', termTr: 'sızıntı (dökülme)', pronunciation: '/spɪl/', category: 'safety', difficulty: 2,
    definitionEn: 'Fuel, oil, or hydraulic fluid leak on the ramp.',
    definitionTr: 'Rampada yakıt, yağ veya hidrolik akışkan kaçağı.',
    examples: [
      { en: 'Report fuel spill immediately.', tr: 'Yakıt sızıntısını derhal bildir.' },
      { en: 'Use absorbent for cleanup.', tr: 'Temizlik için absorban kullan.' },
    ],
    relatedTerms: ['leak', 'fuel spill', 'cleanup'],
  },

  // ===== COMMUNICATION & SHIFT (8) =====
  { id: 'voc_ground_047', term: 'ramp agent', termTr: 'ramp ajanı', pronunciation: '/ræmp ˈeɪ.dʒənt/', category: 'staff', difficulty: 2,
    definitionEn: 'Ground crew member coordinating turnaround activities.',
    definitionTr: 'Turnaround aktivitelerini koordine eden yer ekibi üyesi.',
    examples: [
      { en: 'Ramp agent supervises loading.', tr: 'Ramp ajanı yüklemeyi denetler.' },
      { en: 'Coordinate with cabin crew.', tr: 'Kabin ekibi ile koordine.' },
    ],
    relatedTerms: ['turnaround coordinator', 'load master', 'GHA'],
  },
  { id: 'voc_ground_048', term: 'turnaround', termTr: 'turnaround (hızlı dönüş)', pronunciation: '/ˈtɜːn.əˌraʊnd/', category: 'operations', difficulty: 3,
    definitionEn: 'Process of preparing aircraft for next flight quickly.',
    definitionTr: 'Uçağı sonraki uçuş için hızla hazırlama süreci.',
    examples: [
      { en: 'Turnaround time 30 min.', tr: 'Turnaround 30 dk.' },
      { en: 'Quick turn requires coordination.', tr: 'Quick turn koordinasyon gerekir.' },
    ],
    relatedTerms: ['transit', 'block time', 'departure'],
  },
  { id: 'voc_ground_049', term: 'load sheet', termTr: 'yük dökümanı', pronunciation: '/ləʊd ʃiːt/', category: 'documentation', difficulty: 3,
    definitionEn: 'Document showing aircraft weight, balance, and load distribution.',
    definitionTr: 'Uçak ağırlığı, dengesi ve yük dağılımını gösteren belge.',
    examples: [
      { en: 'Load sheet signed by captain.', tr: 'Load sheet kaptan imzalı.' },
      { en: 'CG within limits.', tr: 'CG limitler içinde.' },
    ],
    relatedTerms: ['weight and balance', 'CG', 'manifest'],
  },
  { id: 'voc_ground_050', term: 'block time', termTr: 'block time (kapı-kapı)', pronunciation: '/blɒk taɪm/', category: 'operations', difficulty: 3,
    definitionEn: 'Time from chocks-off (departure gate) to chocks-on (arrival gate).',
    definitionTr: 'Chocks-off (kalkış kapısı) ile chocks-on (varış kapısı) arası süre.',
    examples: [
      { en: 'Block time differs from flight time.', tr: 'Block time uçuş süresinden farklı.' },
      { en: 'OFF/ON times in TLB.', tr: 'OFF/ON zamanları TLB\'de.' },
    ],
    relatedTerms: ['chocks-off', 'chocks-on', 'flight time'],
  },
  { id: 'voc_ground_051', term: 'OFF time', termTr: 'OFF zamanı (kalkış başlangıç)', pronunciation: '/ɒf taɪm/', category: 'operations', difficulty: 2,
    definitionEn: 'Time when chocks are removed and aircraft starts taxi.',
    definitionTr: 'Chocks kaldırıldığı ve uçağın taksiye başladığı zaman.',
    examples: [
      { en: 'OFF time 14:30 local.', tr: 'OFF zamanı 14:30 yerel.' },
      { en: 'Recorded by ground crew.', tr: 'Yer ekibi tarafından kaydedilir.' },
    ],
    relatedTerms: ['ON time', 'block time', 'chocks'],
  },
  { id: 'voc_ground_052', term: 'shift handover', termTr: 'vardiya devri', pronunciation: '/ʃɪft ˈhæn.dəʊ.vər/', category: 'shift', difficulty: 2,
    definitionEn: 'Briefing from outgoing to incoming shift on ongoing tasks.',
    definitionTr: 'Devam eden işler hakkında çıkan vardiyadan giren vardiyaya brifing.',
    examples: [
      { en: 'Handover briefing 15 min.', tr: 'Handover brifingi 15 dk.' },
      { en: 'Document ongoing issues.', tr: 'Devam eden sorunları belgele.' },
    ],
    relatedTerms: ['shift', 'briefing', 'handoff'],
  },
  { id: 'voc_ground_053', term: 'walkie-talkie', termTr: 'el telsizi', pronunciation: '/ˌwɔː.kiˈtɔː.ki/', category: 'communication', difficulty: 1,
    definitionEn: 'Portable two-way radio for ramp communication.',
    definitionTr: 'Ramp iletişimi için taşınabilir çift yönlü telsiz.',
    examples: [
      { en: 'Channel 5 for ramp ops.', tr: 'Ramp ops için kanal 5.' },
      { en: 'Replace battery between shifts.', tr: 'Vardiyalar arası bataryayı değiştir.' },
    ],
    relatedTerms: ['radio', 'channel', 'ground frequency'],
  },
  { id: 'voc_ground_054', term: 'TWR', termTr: 'TWR (kule)', pronunciation: '/taʊ.ər/', category: 'communication', difficulty: 2,
    definitionEn: 'Tower — air traffic control facility for aircraft on or near runway.',
    definitionTr: 'Kule — pist üzerinde veya yakınında uçaklar için ATC tesisi.',
    examples: [
      { en: 'Tower frequency 118.1.', tr: 'Tower frekansı 118.1.' },
      { en: 'Coordinate with tower for crossing.', tr: 'Geçiş için kule ile koordine.' },
    ],
    relatedTerms: ['ground', 'ATC', 'frequency'],
  },

  // ===== EMERGENCY & SECURITY (6) =====
  { id: 'voc_ground_055', term: 'emergency procedure', termTr: 'acil prosedür', pronunciation: '/ɪˈmɜː.dʒən.si prəˈsiː.dʒər/', category: 'emergency', difficulty: 2,
    definitionEn: 'Standard actions during fire, fuel spill, or medical emergency.',
    definitionTr: 'Yangın, yakıt sızıntısı veya tıbbi acilde standart aksiyonlar.',
    examples: [
      { en: 'Fire drill quarterly.', tr: 'Çeyrek dönemlik yangın tatbikatı.' },
      { en: 'Emergency contacts posted.', tr: 'Acil telefon numaraları asılı.' },
    ],
    relatedTerms: ['fire drill', 'evacuation', 'first aid'],
  },
  { id: 'voc_ground_056', term: 'fire drill', termTr: 'yangın tatbikatı', pronunciation: '/faɪər drɪl/', category: 'emergency', difficulty: 1,
    definitionEn: 'Practice exercise for fire response on the ramp.',
    definitionTr: 'Rampada yangın müdahale tatbikatı.',
    examples: [
      { en: 'Annual fire drill mandatory.', tr: 'Yıllık fire drill zorunlu.' },
      { en: 'All crew participate.', tr: 'Tüm ekip katılır.' },
    ],
    relatedTerms: ['evacuation', 'fire extinguisher', 'emergency'],
  },
  { id: 'voc_ground_057', term: 'security check', termTr: 'güvenlik kontrolü', pronunciation: '/sɪˈkjʊə.rə.ti tʃek/', category: 'security', difficulty: 2,
    definitionEn: 'Inspection of cargo/baggage for prohibited items.',
    definitionTr: 'Kargo/bagajın yasaklı eşya için muayenesi.',
    examples: [
      { en: 'X-ray + manual check.', tr: 'X-ray + elle kontrol.' },
      { en: 'No access to secure area without ID.', tr: 'ID olmadan güvenli bölgeye giriş yok.' },
    ],
    relatedTerms: ['screening', 'X-ray', 'restricted area'],
  },
  { id: 'voc_ground_058', term: 'restricted area', termTr: 'kısıtlı alan', pronunciation: '/rɪˈstrɪk.tɪd ˈeə.ri.ə/', category: 'security', difficulty: 2,
    definitionEn: 'Area requiring special access/credentials (airside, ramp, gate).',
    definitionTr: 'Özel erişim/kimlik gerektiren alan (airside, ramp, gate).',
    examples: [
      { en: 'Show ID badge for entry.', tr: 'Giriş için ID badge göster.' },
      { en: 'Tailgating prohibited.', tr: 'Tailgating yasak.' },
    ],
    relatedTerms: ['airside', 'badge', 'access control'],
  },
  { id: 'voc_ground_059', term: 'badge', termTr: 'kimlik kartı (badge)', pronunciation: '/bædʒ/', category: 'security', difficulty: 1,
    definitionEn: 'Identification card showing access privileges.',
    definitionTr: 'Erişim yetkisini gösteren kimlik kartı.',
    examples: [
      { en: 'Always wear badge visibly.', tr: 'Badge\'i her zaman görünür tak.' },
      { en: 'Renew badge annually.', tr: 'Badge yıllık yenile.' },
    ],
    relatedTerms: ['ID', 'access control', 'security'],
  },
  { id: 'voc_ground_060', term: 'incident report', termTr: 'olay raporu', pronunciation: '/ˈɪn.sɪ.dənt rɪˈpɔːt/', category: 'documentation', difficulty: 2,
    definitionEn: 'Written record of an unusual event (damage, injury, near-miss).',
    definitionTr: 'Olağandışı olayın yazılı kaydı (hasar, yaralanma, near-miss).',
    examples: [{ en: 'File incident report within 24h.', tr: '24 saat içinde olay raporu doldur.' }],
    relatedTerms: ['near-miss', 'safety report', 'investigation'],
  },
  // ===== CARGO OPERATIONS (10) =====
  { id: 'voc_ground_061', term: 'cargo manifest', termTr: 'kargo manifestosu', pronunciation: '/ˈkɑː.ɡəʊ ˈmæn.ɪ.fest/', category: 'cargo', difficulty: 3,
    definitionEn: 'Document listing all cargo items, weights, and destinations.',
    definitionTr: 'Tüm kargo öğelerini, ağırlıkları ve hedefleri listeleyen belge.',
    examples: [{ en: 'Verify cargo against manifest.', tr: 'Kargoyu manifestoya göre doğrula.' }],
    relatedTerms: ['load sheet', 'cargo', 'documentation'],
  },
  { id: 'voc_ground_062', term: 'dangerous goods', termTr: 'tehlikeli madde', pronunciation: '/ˈdeɪn.dʒər.əs ɡʊdz/', category: 'cargo', difficulty: 3,
    definitionEn: 'Items that pose risk during transport — DG class 1-9.',
    definitionTr: 'Taşımada risk oluşturan eşyalar — DG sınıf 1-9.',
    examples: [{ en: 'DG declaration form required.', tr: 'DG beyan formu gerekli.' }],
    relatedTerms: ['DG', 'IATA DGR', 'hazardous materials'],
  },
  { id: 'voc_ground_063', term: 'IATA DGR', termTr: 'IATA Tehlikeli Madde Düzenlemesi', pronunciation: '/aɪ.ɑː.tə diː dʒiː ɑːr/', category: 'cargo', difficulty: 4,
    definitionEn: 'IATA Dangerous Goods Regulations — international standard for hazmat air transport.',
    definitionTr: 'IATA Tehlikeli Madde Düzenlemeleri — hava taşımacılığında uluslararası standart.',
    examples: [{ en: 'IATA DGR updated annually.', tr: 'IATA DGR yıllık güncellenir.' }],
    relatedTerms: ['dangerous goods', 'hazmat', 'compliance'],
  },
  { id: 'voc_ground_064', term: 'AKE container', termTr: 'AKE konteyneri', pronunciation: '/eɪ keɪ iː/', category: 'cargo', difficulty: 3,
    definitionEn: 'Standard ULD container for narrow-body aircraft cargo holds.',
    definitionTr: 'Dar gövde uçak kargo bölmeleri için standart ULD konteyneri.',
    examples: [{ en: 'AKE volume 4.5 m³.', tr: 'AKE hacmi 4.5 m³.' }],
    relatedTerms: ['ULD', 'pallet', 'container'],
  },
  { id: 'voc_ground_065', term: 'pallet', termTr: 'palet', pronunciation: '/ˈpæl.ɪt/', category: 'cargo', difficulty: 1,
    definitionEn: 'Flat structure supporting goods, secured with nets for transport.',
    definitionTr: 'Eşyaları destekleyen, taşıma için ağlarla sabitlenen düz yapı.',
    examples: [{ en: 'PMC pallet 96"x125".', tr: 'PMC palet 96"x125".' }],
    relatedTerms: ['ULD', 'cargo net', 'forklift'],
  },
  { id: 'voc_ground_066', term: 'cargo net', termTr: 'kargo ağı', pronunciation: '/ˈkɑː.ɡəʊ net/', category: 'cargo', difficulty: 1,
    definitionEn: 'Heavy-duty net securing cargo on pallets.',
    definitionTr: 'Paletteki kargoyu sabitleyen ağır hizmet ağı.',
    examples: [{ en: 'Tighten cargo net before takeoff.', tr: 'Kalkıştan önce kargo ağını sık.' }],
    relatedTerms: ['pallet', 'tie-down', 'restraint'],
  },
  { id: 'voc_ground_067', term: 'forklift', termTr: 'forklift', pronunciation: '/ˈfɔːk.lɪft/', category: 'equipment', difficulty: 1,
    definitionEn: 'Vehicle for lifting and moving heavy cargo.',
    definitionTr: 'Ağır kargoyu kaldırıp taşıyan araç.',
    examples: [{ en: 'Forklift certification required.', tr: 'Forklift sertifikası gerekli.' }],
    relatedTerms: ['pallet', 'cargo', 'GSE'],
  },
  { id: 'voc_ground_068', term: 'high loader', termTr: 'high loader (yüksek yükleyici)', pronunciation: '/haɪ ˈləʊ.dər/', category: 'equipment', difficulty: 3,
    definitionEn: 'Vehicle that elevates ULDs to wide-body cargo door height.',
    definitionTr: 'ULD\'leri geniş gövde kargo kapısı yüksekliğine kaldıran araç.',
    examples: [{ en: 'High loader for 747 main deck.', tr: '747 ana güverte için high loader.' }],
    relatedTerms: ['ULD', 'cargo door', 'wide-body'],
  },
  { id: 'voc_ground_069', term: 'live animal cargo', termTr: 'canlı hayvan kargo', pronunciation: '/laɪv ˈæn.ɪ.məl ˈkɑː.ɡəʊ/', category: 'cargo', difficulty: 3,
    definitionEn: 'Animals transported as cargo, requiring special handling.',
    definitionTr: 'Kargo olarak taşınan, özel işlem gerektiren hayvanlar.',
    examples: [{ en: 'AVIH = animal in hold.', tr: 'AVIH = kargoda hayvan.' }],
    relatedTerms: ['AVIH', 'PETC', 'special cargo'],
  },
  { id: 'voc_ground_070', term: 'perishable cargo', termTr: 'bozulabilir kargo', pronunciation: '/ˈper.ɪ.ʃə.bəl ˈkɑː.ɡəʊ/', category: 'cargo', difficulty: 2,
    definitionEn: 'Cargo requiring temperature control (food, flowers, vaccines).',
    definitionTr: 'Sıcaklık kontrolü gerektiren kargo (gıda, çiçek, aşı).',
    examples: [{ en: 'Perishable: cool chamber storage.', tr: 'Perishable: soğuk oda depolama.' }],
    relatedTerms: ['cool chain', 'pharma', 'temperature'],
  },

  // ===== AIRCRAFT SERVICING (10) =====
  { id: 'voc_ground_071', term: 'lavatory service', termTr: 'tuvalet servisi', pronunciation: '/ˈlæv.ə.tər.i ˈsɜː.vɪs/', category: 'servicing', difficulty: 2,
    definitionEn: 'Emptying and cleaning aircraft lavatory tanks.',
    definitionTr: 'Uçak tuvalet tanklarını boşaltma ve temizleme.',
    examples: [{ en: 'Lavatory truck connects to drain port.', tr: 'Lavatory truck drain portuna bağlanır.' }],
    relatedTerms: ['lav truck', 'blue water', 'drain'],
  },
  { id: 'voc_ground_072', term: 'water service', termTr: 'su servisi', pronunciation: '/ˈwɔː.tər ˈsɜː.vɪs/', category: 'servicing', difficulty: 2,
    definitionEn: 'Refilling potable water tanks for galley and lavatories.',
    definitionTr: 'Galley ve tuvaletler için içme suyu tanklarını yeniden doldurma.',
    examples: [{ en: 'Water truck delivers potable water.', tr: 'Su tankeri içme suyu sağlar.' }],
    relatedTerms: ['potable water', 'tank', 'galley'],
  },
  { id: 'voc_ground_073', term: 'cleaning crew', termTr: 'temizlik ekibi', pronunciation: '/ˈkliː.nɪŋ kruː/', category: 'staff', difficulty: 1,
    definitionEn: 'Personnel cleaning the cabin between flights.',
    definitionTr: 'Uçuşlar arası kabini temizleyen personel.',
    examples: [{ en: 'Cleaning crew enters after disembark.', tr: 'Cleaning crew yolcu indikten sonra girer.' }],
    relatedTerms: ['turnaround', 'disembark', 'cabin'],
  },
  { id: 'voc_ground_074', term: 'catering loading', termTr: 'catering yükleme', pronunciation: '/ˈkeɪ.tər.ɪŋ ˈləʊ.dɪŋ/', category: 'servicing', difficulty: 2,
    definitionEn: 'Loading prepared meals and beverages onto aircraft.',
    definitionTr: 'Hazırlanan yemek ve içeceklerin uçağa yüklenmesi.',
    examples: [{ en: 'Catering 1 hour before departure.', tr: 'Catering kalkıştan 1 saat önce.' }],
    relatedTerms: ['catering truck', 'galley', 'meal count'],
  },
  { id: 'voc_ground_075', term: 'catering truck', termTr: 'catering aracı', pronunciation: '/ˈkeɪ.tər.ɪŋ trʌk/', category: 'equipment', difficulty: 2,
    definitionEn: 'Truck with elevating platform to deliver meals to aircraft galley door.',
    definitionTr: 'Yemekleri galley kapısına ulaştırmak için yükselen platformlu araç.',
    examples: [{ en: 'Catering truck elevates to L2 door.', tr: 'Catering truck L2 kapısına yükselir.' }],
    relatedTerms: ['catering loading', 'galley', 'GSE'],
  },
  { id: 'voc_ground_076', term: 'air conditioning unit', termTr: 'klima ünitesi', pronunciation: '/eər kənˈdɪʃ.ən.ɪŋ ˈjuː.nɪt/', category: 'equipment', difficulty: 2,
    definitionEn: 'Pre-conditioned air supplied to aircraft cabin during ground stop.',
    definitionTr: 'Yerde uçak kabinine sağlanan ön koşullandırılmış hava.',
    examples: [{ en: 'PCA before passengers board.', tr: 'Yolcular bindiğinde PCA.' }],
    relatedTerms: ['PCA', 'cabin air', 'GSE'],
  },
  { id: 'voc_ground_077', term: 'compressed air', termTr: 'sıkıştırılmış hava', pronunciation: '/kəmˈprest eər/', category: 'equipment', difficulty: 2,
    definitionEn: 'High-pressure air for engine starting (cross-bleed) without APU.',
    definitionTr: 'APU olmadan motor çalıştırma için yüksek basınçlı hava.',
    examples: [{ en: 'Air start unit (ASU).', tr: 'Air start unit (ASU).' }],
    relatedTerms: ['ASU', 'engine start', 'APU'],
  },
  { id: 'voc_ground_078', term: 'tow', termTr: 'çekme', pronunciation: '/təʊ/', category: 'movement', difficulty: 1,
    definitionEn: 'Pulling aircraft from one location to another using a tug.',
    definitionTr: 'Bir uçağı tug kullanarak bir konumdan diğerine çekme.',
    examples: [{ en: 'Tow to maintenance hangar.', tr: 'Bakım hangarına çekme.' }],
    relatedTerms: ['tug', 'pushback', 'aircraft movement'],
  },
  { id: 'voc_ground_079', term: 'parking brake', termTr: 'park freni', pronunciation: '/ˈpɑː.kɪŋ breɪk/', category: 'aircraft', difficulty: 2,
    definitionEn: 'Brake holding aircraft stationary on parking position.',
    definitionTr: 'Uçağı park yerinde sabit tutan fren.',
    examples: [{ en: 'Parking brake set before chocks.', tr: 'Chocks öncesi park freni kilitli.' }],
    relatedTerms: ['chocks', 'brakes set', 'pushback'],
  },
  { id: 'voc_ground_080', term: 'wheel chock', termTr: 'tekerlek takozu', pronunciation: '/wiːl tʃɒk/', category: 'equipment', difficulty: 1,
    definitionEn: 'Wedge placed against aircraft wheels to prevent rolling.',
    definitionTr: 'Uçak tekerleklerinin önüne konan, kaymayı önleyen takoz.',
    examples: [{ en: 'Place chocks before disconnecting tug.', tr: 'Tug ayrılmadan önce takoz yerleştir.' }],
    relatedTerms: ['chock', 'parking brake', 'safety'],
  },

  // ===== WEATHER & WINTER OPS (10) =====
  { id: 'voc_ground_081', term: 'snow removal', termTr: 'kar temizleme', pronunciation: '/snəʊ rɪˈmuː.vəl/', category: 'winter_ops', difficulty: 2,
    definitionEn: 'Clearing snow from runways, taxiways, and ramps.',
    definitionTr: 'Pist, taxiway ve ramplardan kar temizleme.',
    examples: [{ en: 'Snow plow on runway.', tr: 'Pistte kar küreyici.' }],
    relatedTerms: ['runway clear', 'plow', 'sweeper'],
  },
  { id: 'voc_ground_082', term: 'runway sweeper', termTr: 'pist süpürgesi', pronunciation: '/ˈrʌn.weɪ ˈswiː.pər/', category: 'equipment', difficulty: 2,
    definitionEn: 'Vehicle clearing debris and slush from runway surface.',
    definitionTr: 'Pist yüzeyinden atık ve sulu karı temizleyen araç.',
    examples: [{ en: 'Sweeper after snowfall.', tr: 'Kar yağışı sonrası süpürge.' }],
    relatedTerms: ['runway clear', 'snow removal', 'FOD'],
  },
  { id: 'voc_ground_083', term: 'runway condition', termTr: 'pist durumu', pronunciation: '/ˈrʌn.weɪ kənˈdɪʃ.ən/', category: 'winter_ops', difficulty: 3,
    definitionEn: 'Surface condition (dry, wet, snow, ice) reported to pilots.',
    definitionTr: 'Pilotlara raporlanan yüzey durumu (kuru, ıslak, kar, buz).',
    examples: [{ en: 'RCAM matrix code.', tr: 'RCAM matriks kodu.' }],
    relatedTerms: ['RCAM', 'braking action', 'NOTAM'],
  },
  { id: 'voc_ground_084', term: 'braking action', termTr: 'fren etkisi', pronunciation: '/ˈbreɪ.kɪŋ ˈæk.ʃən/', category: 'winter_ops', difficulty: 3,
    definitionEn: 'Friction available between tire and runway surface.',
    definitionTr: 'Lastik ve pist yüzeyi arasındaki sürtünme.',
    examples: [{ en: 'Braking action: medium to good.', tr: 'Braking action: orta-iyi.' }],
    relatedTerms: ['runway condition', 'mu meter', 'RCAM'],
  },
  { id: 'voc_ground_085', term: 'low visibility procedure', termTr: 'düşük görüş prosedürü', pronunciation: '/ləʊ ˌvɪz.əˈbɪl.ə.ti prəˈsiː.dʒər/', category: 'weather', difficulty: 4,
    definitionEn: 'Operations during fog or low ceiling — LVP active.',
    definitionTr: 'Sis veya düşük tavan sırasında operasyonlar — LVP aktif.',
    examples: [{ en: 'LVP: extra spacing on runway.', tr: 'LVP: pistte ekstra mesafe.' }],
    relatedTerms: ['CAT III', 'fog', 'RVR'],
  },
  { id: 'voc_ground_086', term: 'fog', termTr: 'sis', pronunciation: '/fɒɡ/', category: 'weather', difficulty: 1,
    definitionEn: 'Cloud at ground level, reducing visibility below 1 km.',
    definitionTr: 'Yer seviyesinde bulut, görüşü 1 km altına düşürür.',
    examples: [{ en: 'Fog delays operations.', tr: 'Sis operasyonları geciktirir.' }],
    relatedTerms: ['mist', 'low visibility', 'CAT III'],
  },
  { id: 'voc_ground_087', term: 'thunderstorm', termTr: 'fırtına', pronunciation: '/ˈθʌn.də.stɔːm/', category: 'weather', difficulty: 2,
    definitionEn: 'Severe weather with lightning, heavy rain, hail, possibly tornadoes.',
    definitionTr: 'Şimşek, yağış, dolu, muhtemel hortum içeren şiddetli hava.',
    examples: [{ en: 'Halt fueling during thunderstorm.', tr: 'Fırtına sırasında yakıt durdur.' }],
    relatedTerms: ['lightning', 'CB', 'severe weather'],
  },
  { id: 'voc_ground_088', term: 'lightning', termTr: 'şimşek', pronunciation: '/ˈlaɪt.nɪŋ/', category: 'weather', difficulty: 1,
    definitionEn: 'Electrical discharge during thunderstorms — halt all ramp ops.',
    definitionTr: 'Fırtına sırasında elektrik deşarjı — tüm ramp ops durdurulur.',
    examples: [{ en: 'Lightning within 5 NM = stop ops.', tr: '5 NM içinde şimşek = ops durdur.' }],
    relatedTerms: ['thunderstorm', 'red weather', 'shelter'],
  },
  { id: 'voc_ground_089', term: 'high winds', termTr: 'şiddetli rüzgar', pronunciation: '/haɪ wɪndz/', category: 'weather', difficulty: 1,
    definitionEn: 'Wind speeds threatening aircraft on ground or operations.',
    definitionTr: 'Yerdeki uçağı veya operasyonu tehdit eden rüzgar hızları.',
    examples: [{ en: 'High winds: secure GSE.', tr: 'Şiddetli rüzgar: GSE\'yi sabitle.' }],
    relatedTerms: ['gusts', 'wind limits', 'GSE securing'],
  },
  { id: 'voc_ground_090', term: 'wind limits', termTr: 'rüzgar limitleri', pronunciation: '/wɪnd ˈlɪm.ɪts/', category: 'weather', difficulty: 3,
    definitionEn: 'Maximum wind speeds for various ground operations.',
    definitionTr: 'Çeşitli yer operasyonları için maksimum rüzgar hızları.',
    examples: [{ en: 'Stair limit 50 knots.', tr: 'Merdiven limiti 50 knot.' }],
    relatedTerms: ['high winds', 'gust', 'operational limit'],
  },

  // ===== CREW COORD & ADVANCED (10) =====
  { id: 'voc_ground_091', term: 'crew briefing', termTr: 'ekip brifingi', pronunciation: '/kruː ˈbriː.fɪŋ/', category: 'shift', difficulty: 2,
    definitionEn: 'Pre-shift meeting covering tasks, weather, special considerations.',
    definitionTr: 'Vardiya öncesi görev, hava, özel hususları kapsayan toplantı.',
    examples: [{ en: 'Daily crew briefing 06:00.', tr: 'Günlük ekip brifingi 06:00.' }],
    relatedTerms: ['shift', 'briefing', 'planning'],
  },
  { id: 'voc_ground_092', term: 'load master', termTr: 'load master', pronunciation: '/ləʊd ˈmɑː.stər/', category: 'staff', difficulty: 3,
    definitionEn: 'Specialist responsible for cargo loading and weight balance.',
    definitionTr: 'Kargo yüklemeden ve ağırlık dengesinden sorumlu uzman.',
    examples: [{ en: 'Load master signs load sheet.', tr: 'Load master load sheet imzalar.' }],
    relatedTerms: ['weight and balance', 'cargo', 'load sheet'],
  },
  { id: 'voc_ground_093', term: 'weight and balance', termTr: 'ağırlık ve denge', pronunciation: '/weɪt ænd ˈbæl.əns/', category: 'operations', difficulty: 3,
    definitionEn: 'Calculations ensuring aircraft is within weight and CG limits.',
    definitionTr: 'Uçağın ağırlık ve CG limitleri içinde olduğunu sağlayan hesaplar.',
    examples: [{ en: 'W&B verified before pushback.', tr: 'Pushback öncesi W&B doğrulanır.' }],
    relatedTerms: ['load sheet', 'CG', 'load master'],
  },
  { id: 'voc_ground_094', term: 'PCA', termTr: 'PCA (ön koşullu hava)', pronunciation: '/piː siː eɪ/', category: 'equipment', difficulty: 3,
    definitionEn: 'Pre-Conditioned Air — temperature-controlled air for cabin during ground stop.',
    definitionTr: 'Ön Koşullandırılmış Hava — yer durağında kabin için sıcaklık kontrollü hava.',
    examples: [{ en: 'PCA reduces APU usage.', tr: 'PCA APU kullanımını azaltır.' }],
    relatedTerms: ['air conditioning', 'APU', 'GPU'],
  },
  { id: 'voc_ground_095', term: 'ASU', termTr: 'ASU (hava çalıştırma ünitesi)', pronunciation: '/eɪ es juː/', category: 'equipment', difficulty: 4,
    definitionEn: 'Air Start Unit — supplies compressed air for engine start.',
    definitionTr: 'Hava Çalıştırma Ünitesi — motor çalıştırma için sıkıştırılmış hava sağlar.',
    examples: [{ en: 'ASU at remote stand.', tr: 'Remote stand\'da ASU.' }],
    relatedTerms: ['compressed air', 'engine start', 'APU'],
  },
  { id: 'voc_ground_096', term: 'walk-around inspection', termTr: 'walk-around muayenesi', pronunciation: '/wɔːk əˈraʊnd ɪnˈspek.ʃən/', category: 'inspection', difficulty: 2,
    definitionEn: 'Visual external check before/after flight.',
    definitionTr: 'Uçuş öncesi/sonrası görsel dış kontrol.',
    examples: [{ en: 'Walk-around 15 min before pushback.', tr: 'Pushback\'den 15 dk önce walk-around.' }],
    relatedTerms: ['pre-flight', 'visual', 'damage'],
  },
  { id: 'voc_ground_097', term: 'aircraft damage', termTr: 'uçak hasarı', pronunciation: '/ˈeə.krɑːft ˈdæm.ɪdʒ/', category: 'safety', difficulty: 2,
    definitionEn: 'Damage to aircraft structure during ground operations.',
    definitionTr: 'Yer operasyonları sırasında uçak yapısına hasar.',
    examples: [{ en: 'GSE strike caused damage.', tr: 'GSE çarpması hasara yol açtı.' }],
    relatedTerms: ['ground damage', 'incident report', 'GSE strike'],
  },
  { id: 'voc_ground_098', term: 'GSE strike', termTr: 'GSE çarpması', pronunciation: '/dʒiː es iː straɪk/', category: 'safety', difficulty: 3,
    definitionEn: 'Ground equipment hitting aircraft, causing damage.',
    definitionTr: 'Yer ekipmanının uçağa çarpması, hasara yol açması.',
    examples: [{ en: 'GSE strike: report immediately.', tr: 'GSE strike: derhal raporla.' }],
    relatedTerms: ['aircraft damage', 'safety violation', 'incident'],
  },
  { id: 'voc_ground_099', term: 'safety zone', termTr: 'emniyet bölgesi', pronunciation: '/ˈseɪf.ti zəʊn/', category: 'safety', difficulty: 2,
    definitionEn: 'Area around aircraft where GSE/personnel must follow specific rules.',
    definitionTr: 'GSE/personelin özel kurallar izlemesi gereken uçak çevresi alanı.',
    examples: [{ en: 'Equipment Restricted Area (ERA).', tr: 'Ekipman Kısıtlı Alan (ERA).' }],
    relatedTerms: ['ERA', 'jet blast', 'engine intake'],
  },
  { id: 'voc_ground_100', term: 'service report', termTr: 'servis raporu', pronunciation: '/ˈsɜː.vɪs rɪˈpɔːt/', category: 'documentation', difficulty: 2,
    definitionEn: 'Document detailing all ground services provided to aircraft.',
    definitionTr: 'Uçağa sağlanan tüm yer hizmetlerini detaylandıran belge.',
    examples: [{ en: 'Service report signed by captain.', tr: 'Servis raporu kaptan imzalı.' }],
    relatedTerms: ['turnaround', 'documentation', 'sign-off'],
  },

  // ===== FAZ 2 ADVANCED (40) =====
  // Wide-body operations (10)
  { id: 'voc_ground_101', term: 'wide-body operations', termTr: 'geniş gövde operasyonları', pronunciation: '/waɪd ˈbɒd.i ˌɒp.əˈreɪ.ʃənz/', category: 'operations', difficulty: 3,
    definitionEn: 'Servicing twin-aisle aircraft (B777, A350) requiring more equipment.', definitionTr: 'Daha fazla ekipman gerektiren çift koridorlu uçak (B777, A350) servisi.',
    examples: [{ en: 'Wide-body needs 6+ baggage handlers.', tr: 'Wide-body 6+ bagaj görevlisi ister.' }],
    relatedTerms: ['narrow-body', 'high loader', 'main deck'],
  },
  { id: 'voc_ground_102', term: 'main deck cargo', termTr: 'ana güverte kargo', pronunciation: '/meɪn dek ˈkɑː.ɡəʊ/', category: 'cargo', difficulty: 4,
    definitionEn: 'Cargo loaded above passenger floor in freighter aircraft.', definitionTr: 'Freighter uçakta yolcu zemininin üstüne yüklenen kargo.',
    examples: [{ en: 'B747F main deck access.', tr: 'B747F ana güverte erişimi.' }],
    relatedTerms: ['lower deck', 'freighter', 'high loader'],
  },
  { id: 'voc_ground_103', term: 'narrow-body operations', termTr: 'dar gövde operasyonları', pronunciation: '/ˈnær.əʊ ˈbɒd.i/', category: 'operations', difficulty: 2,
    definitionEn: 'Servicing single-aisle aircraft (B737, A320) — quicker turnaround.', definitionTr: 'Tek koridorlu uçak (B737, A320) servisi — hızlı turnaround.',
    examples: [{ en: 'Narrow-body 25 min turnaround.', tr: 'Narrow-body 25 dk turnaround.' }],
    relatedTerms: ['wide-body', 'turnaround', 'low-cost'],
  },
  { id: 'voc_ground_104', term: 'tight turnaround', termTr: 'sıkı turnaround', pronunciation: '/taɪt ˈtɜːn.əˌraʊnd/', category: 'operations', difficulty: 3,
    definitionEn: 'Compressed schedule (15-25 min) for low-cost carriers.', definitionTr: 'Low-cost havayolu için sıkıştırılmış program (15-25 dk).',
    examples: [{ en: 'Tight turnaround needs coordination.', tr: 'Sıkı turnaround koordinasyon ister.' }],
    relatedTerms: ['turnaround', 'low-cost', 'efficiency'],
  },
  { id: 'voc_ground_105', term: 'night operations', termTr: 'gece operasyonları', pronunciation: '/naɪt ˌɒp.əˈreɪ.ʃənz/', category: 'operations', difficulty: 3,
    definitionEn: 'Ramp work during nighttime requiring extra lighting and care.', definitionTr: 'Ekstra aydınlatma ve dikkat gerektiren gece ramp işi.',
    examples: [{ en: 'Night ops: floodlights mandatory.', tr: 'Gece ops: floodlight zorunlu.' }],
    relatedTerms: ['floodlight', 'visibility', 'fatigue'],
  },
  { id: 'voc_ground_106', term: 'VIP handling', termTr: 'VIP işlem', pronunciation: '/ˌviː.aɪˈpiː ˈhæn.dlɪŋ/', category: 'operations', difficulty: 3,
    definitionEn: 'Special service for high-profile passengers — discreet, secure.', definitionTr: 'Yüksek profilli yolcu için özel servis — gizli, güvenli.',
    examples: [{ en: 'VIP handling: separate gate.', tr: 'VIP handling: ayrı gate.' }],
    relatedTerms: ['CIP', 'protocol', 'security'],
  },
  { id: 'voc_ground_107', term: 'charter flight', termTr: 'charter uçuşu', pronunciation: '/ˈtʃɑː.tər flaɪt/', category: 'operations', difficulty: 2,
    definitionEn: 'Non-scheduled flight booked privately.', definitionTr: 'Özel olarak rezerve edilen tarifesiz uçuş.',
    examples: [{ en: 'Charter for football team.', tr: 'Futbol takımı için charter.' }],
    relatedTerms: ['scheduled', 'private', 'business jet'],
  },
  { id: 'voc_ground_108', term: 'diplomatic cargo', termTr: 'diplomatik kargo', pronunciation: '/ˌdɪp.ləˈmæt.ɪk ˈkɑː.ɡəʊ/', category: 'cargo', difficulty: 4,
    definitionEn: 'Government cargo with diplomatic immunity from inspection.', definitionTr: 'Muayeneden diplomatik dokunulmazlığı olan hükümet kargosu.',
    examples: [{ en: 'Diplomatic pouch sealed.', tr: 'Diplomatik kese mühürlü.' }],
    relatedTerms: ['diplomatic pouch', 'customs', 'protocol'],
  },
  { id: 'voc_ground_109', term: 'multi-aircraft coordination', termTr: 'çoklu uçak koordinasyonu', pronunciation: '/ˌmʌl.tiˈeə.krɑːft kəʊˌɔː.dɪˈneɪ.ʃən/', category: 'operations', difficulty: 4,
    definitionEn: 'Managing multiple aircraft simultaneously on busy ramps.', definitionTr: 'Yoğun ramplarda aynı anda birden çok uçağı yönetme.',
    examples: [{ en: 'Multi-aircraft coord during peak.', tr: 'Yoğun saatte multi-aircraft coord.' }],
    relatedTerms: ['ramp control', 'scheduling', 'efficiency'],
  },
  { id: 'voc_ground_110', term: 'adverse weather', termTr: 'olumsuz hava', pronunciation: '/ˈæd.vɜːs ˈweð.ər/', category: 'weather', difficulty: 3,
    definitionEn: 'Weather conditions that complicate ground operations.', definitionTr: 'Yer operasyonlarını zorlaştıran hava koşulları.',
    examples: [{ en: 'Adverse weather: extra precautions.', tr: 'Olumsuz hava: ekstra önlem.' }],
    relatedTerms: ['high winds', 'thunderstorm', 'low visibility'],
  },

  // Specialized cargo (10)
  { id: 'voc_ground_111', term: 'lithium battery', termTr: 'lityum pil', pronunciation: '/ˈlɪθ.i.əm ˈbæt.ər.i/', category: 'cargo', difficulty: 4,
    definitionEn: 'High-risk cargo subject to strict IATA DGR rules.', definitionTr: 'Sıkı IATA DGR kurallarına tabi yüksek riskli kargo.',
    examples: [{ en: 'Lithium battery UN3480.', tr: 'Lityum pil UN3480.' }],
    relatedTerms: ['IATA DGR', 'class 9', 'fire risk'],
  },
  { id: 'voc_ground_112', term: 'cool chain', termTr: 'soğuk zincir', pronunciation: '/kuːl tʃeɪn/', category: 'cargo', difficulty: 4,
    definitionEn: 'Temperature-controlled logistics for pharma, food, vaccines.', definitionTr: 'İlaç, gıda, aşı için sıcaklık kontrollü lojistik.',
    examples: [{ en: 'Cool chain 2-8°C maintained.', tr: 'Cool chain 2-8°C tutulur.' }],
    relatedTerms: ['perishable', 'pharma', 'temperature'],
  },
  { id: 'voc_ground_113', term: 'pharma logistics', termTr: 'ilaç lojistiği', pronunciation: '/ˈfɑː.mə ləˈdʒɪs.tɪks/', category: 'cargo', difficulty: 4,
    definitionEn: 'Specialized handling of medicines and vaccines.', definitionTr: 'İlaç ve aşıların özel işlemi.',
    examples: [{ en: 'IATA CEIV Pharma certified.', tr: 'IATA CEIV Pharma sertifikalı.' }],
    relatedTerms: ['cool chain', 'vaccine', 'CEIV'],
  },
  { id: 'voc_ground_114', term: 'CEIV', termTr: 'CEIV (IATA özel kargo sertifikası)', pronunciation: '/siː iː aɪ viː/', category: 'cargo', difficulty: 5,
    definitionEn: 'Center of Excellence for Independent Validators — pharma, perishable, live animal.', definitionTr: 'Bağımsız Doğrulayıcılar Mükemmellik Merkezi — pharma, perishable, canlı hayvan.',
    examples: [{ en: 'CEIV Pharma certification.', tr: 'CEIV Pharma sertifikası.' }],
    relatedTerms: ['IATA', 'pharma', 'certification'],
  },
  { id: 'voc_ground_115', term: 'live animal transport', termTr: 'canlı hayvan taşımacılığı', pronunciation: '/laɪv ˈæn.ɪ.məl ˈtræn.spɔːt/', category: 'cargo', difficulty: 4,
    definitionEn: 'Air transport of pets, racehorses, livestock with special handling.', definitionTr: 'Evcil hayvan, yarış atı, çiftlik hayvanı hava taşımacılığı.',
    examples: [{ en: 'IATA Live Animal Regulations.', tr: 'IATA Live Animal Regulations.' }],
    relatedTerms: ['AVIH', 'PETC', 'IATA LAR'],
  },
  { id: 'voc_ground_116', term: 'heavy freight', termTr: 'ağır yük', pronunciation: '/ˈhev.i freɪt/', category: 'cargo', difficulty: 3,
    definitionEn: 'Cargo over 150kg requiring special equipment.', definitionTr: '150 kg üzerinde özel ekipman gerektiren kargo.',
    examples: [{ en: 'Heavy freight: high loader.', tr: 'Heavy freight: high loader.' }],
    relatedTerms: ['high loader', 'forklift', 'oversize'],
  },
  { id: 'voc_ground_117', term: 'customs clearance', termTr: 'gümrük geçişi', pronunciation: '/ˈkʌs.təmz ˈklɪər.əns/', category: 'cargo', difficulty: 3,
    definitionEn: 'Process of getting cargo approved by customs authority.', definitionTr: 'Kargonun gümrük otoritesi tarafından onaylanma süreci.',
    examples: [{ en: 'Customs clearance 24h.', tr: 'Gümrük geçişi 24 saat.' }],
    relatedTerms: ['import', 'export', 'documentation'],
  },
  { id: 'voc_ground_118', term: 'AWB', termTr: 'AWB (hava konşimentosu)', pronunciation: '/eɪ ˌdʌb.əl.juː ˈbiː/', category: 'cargo', difficulty: 4,
    definitionEn: 'Air Waybill — contract document for air cargo.', definitionTr: 'Hava Konşimentosu — hava kargosu sözleşme belgesi.',
    examples: [{ en: 'AWB tracks shipment.', tr: 'AWB sevkiyatı izler.' }],
    relatedTerms: ['cargo manifest', 'IATA', 'shipment'],
  },
  { id: 'voc_ground_119', term: 'shipper', termTr: 'gönderici', pronunciation: '/ˈʃɪp.ər/', category: 'cargo', difficulty: 2,
    definitionEn: 'Person/company sending cargo via airline.', definitionTr: 'Havayolu ile kargo gönderen kişi/şirket.',
    examples: [{ en: 'Shipper declares contents.', tr: 'Gönderici içeriği beyan eder.' }],
    relatedTerms: ['consignee', 'AWB', 'sender'],
  },
  { id: 'voc_ground_120', term: 'consignee', termTr: 'alıcı', pronunciation: '/ˌkɒn.saɪˈniː/', category: 'cargo', difficulty: 3,
    definitionEn: 'Person/company receiving cargo at destination.', definitionTr: 'Hedefte kargoyu alan kişi/şirket.',
    examples: [{ en: 'Consignee notified on arrival.', tr: 'Varışta consignee bilgilendirilir.' }],
    relatedTerms: ['shipper', 'AWB', 'recipient'],
  },

  // De-icing & emergency (10)
  { id: 'voc_ground_121', term: 'CCAR', termTr: 'CCAR (de-ice prosedürü)', pronunciation: '/siː siː ɑːr/', category: 'winter_ops', difficulty: 5,
    definitionEn: 'Clean, Confirm, Anti-ice, Report — de-icing process.', definitionTr: 'Clean, Confirm, Anti-ice, Report — de-icing süreci.',
    examples: [{ en: 'CCAR for full de-ice/anti-ice.', tr: 'Tam de-ice/anti-ice için CCAR.' }],
    relatedTerms: ['de-icing', 'anti-icing', 'holdover'],
  },
  { id: 'voc_ground_122', term: 'fluid mixture', termTr: 'akışkan karışımı', pronunciation: '/ˈfluː.ɪd ˈmɪks.tʃər/', category: 'winter_ops', difficulty: 4,
    definitionEn: 'Glycol+water ratio for de-icing depending on temperature.', definitionTr: 'Sıcaklığa göre de-icing için glikol+su oranı.',
    examples: [{ en: '50/50 mixture for moderate cold.', tr: 'Orta soğukta 50/50 karışım.' }],
    relatedTerms: ['Type I fluid', 'glycol', 'concentration'],
  },
  { id: 'voc_ground_123', term: 'anti-icing application', termTr: 'anti-icing uygulama', pronunciation: '/ˌæn.tiˈaɪ.sɪŋ ˌæp.lɪˈkeɪ.ʃən/', category: 'winter_ops', difficulty: 4,
    definitionEn: 'Spraying Type IV fluid to prevent ice during taxi.', definitionTr: 'Taksi sırasında buzlanmayı önlemek için Type IV akışkan püskürtme.',
    examples: [{ en: 'Anti-icing post de-icing.', tr: 'De-icing sonrası anti-icing.' }],
    relatedTerms: ['Type IV fluid', 'holdover time', 'spray pattern'],
  },
  { id: 'voc_ground_124', term: 'spray pattern', termTr: 'püskürtme deseni', pronunciation: '/spreɪ ˈpæt.ən/', category: 'winter_ops', difficulty: 4,
    definitionEn: 'Coverage method for de-ice/anti-ice fluid on aircraft.', definitionTr: 'Uçakta de-ice/anti-ice akışkanı için kaplama yöntemi.',
    examples: [{ en: 'Spray pattern includes wings, tail.', tr: 'Spray pattern kanat, kuyruk içerir.' }],
    relatedTerms: ['de-icing', 'anti-icing', 'coverage'],
  },
  { id: 'voc_ground_125', term: 'recheck', termTr: 'tekrar kontrol', pronunciation: '/riːˈtʃek/', category: 'winter_ops', difficulty: 3,
    definitionEn: 'Re-inspection after anti-ice if holdover time approaches limit.', definitionTr: 'Holdover süresi limite yaklaşırsa anti-ice sonrası tekrar muayene.',
    examples: [{ en: 'Recheck if delay before takeoff.', tr: 'Kalkış öncesi gecikme varsa recheck.' }],
    relatedTerms: ['holdover time', 'anti-icing', 'delay'],
  },
  { id: 'voc_ground_126', term: 'aircraft fire', termTr: 'uçak yangını', pronunciation: '/ˈeə.krɑːft faɪər/', category: 'emergency', difficulty: 4,
    definitionEn: 'Fire on aircraft requiring immediate evacuation and ARFF.', definitionTr: 'Acil tahliye ve ARFF gerektiren uçak yangını.',
    examples: [{ en: 'Aircraft fire: notify ARFF.', tr: 'Uçak yangını: ARFF\'a bildir.' }],
    relatedTerms: ['ARFF', 'evacuation', 'fire'],
  },
  { id: 'voc_ground_127', term: 'ARFF', termTr: 'ARFF (Havalimanı İtfaiye)', pronunciation: '/ɑːr ɑːr ef ef/', category: 'emergency', difficulty: 4,
    definitionEn: 'Aircraft Rescue and Fire Fighting — airport fire department.', definitionTr: 'Uçak Kurtarma ve Yangın Söndürme — havalimanı itfaiyesi.',
    examples: [{ en: 'ARFF response time 3 min.', tr: 'ARFF yanıt süresi 3 dk.' }],
    relatedTerms: ['fire truck', 'rescue', 'emergency'],
  },
  { id: 'voc_ground_128', term: 'fuel spill response', termTr: 'yakıt sızıntı müdahalesi', pronunciation: '/fjuːəl spɪl rɪˈspɒns/', category: 'emergency', difficulty: 3,
    definitionEn: 'Procedures for cleaning up fuel leaks safely.', definitionTr: 'Yakıt kaçaklarını güvenle temizleme prosedürleri.',
    examples: [{ en: 'Fuel spill: stop ops, contain, report.', tr: 'Yakıt sızıntı: ops dur, kontrol, raporla.' }],
    relatedTerms: ['absorbent', 'environmental', 'containment'],
  },
  { id: 'voc_ground_129', term: 'evacuation support', termTr: 'tahliye desteği', pronunciation: '/ɪˌvæk.juˈeɪ.ʃən səˈpɔːt/', category: 'emergency', difficulty: 3,
    definitionEn: 'Ground crew assisting passenger evacuation from aircraft.', definitionTr: 'Yolcu uçaktan tahliye edilirken yer ekibi yardımı.',
    examples: [{ en: 'Position stairs for evacuation.', tr: 'Tahliye için merdiven konumla.' }],
    relatedTerms: ['evacuation', 'emergency stairs', 'rescue'],
  },
  { id: 'voc_ground_130', term: 'first responders', termTr: 'ilk müdahale ekipleri', pronunciation: '/fɜːst rɪˈspɒn.dərz/', category: 'emergency', difficulty: 3,
    definitionEn: 'Fire, medical, security teams arriving first at incident.', definitionTr: 'Olaya ilk varan yangın, tıbbi, güvenlik ekipleri.',
    examples: [{ en: 'Coordinate with first responders.', tr: 'First responders ile koordine.' }],
    relatedTerms: ['ARFF', 'ambulance', 'police'],
  },

  // Leadership (10)
  { id: 'voc_ground_131', term: 'team leadership', termTr: 'takım liderliği', pronunciation: '/tiːm ˈliː.də.ʃɪp/', category: 'leadership', difficulty: 3,
    definitionEn: 'Guiding ramp crew to achieve operational goals.', definitionTr: 'Operasyonel hedefe ulaşmak için ramp ekibini yönlendirme.',
    examples: [{ en: 'Team lead during peak hours.', tr: 'Yoğun saatte team lead.' }],
    relatedTerms: ['supervisor', 'crew chief', 'ramp coordinator'],
  },
  { id: 'voc_ground_132', term: 'daily briefing', termTr: 'günlük brifing', pronunciation: '/ˈdeɪ.li ˈbriː.fɪŋ/', category: 'leadership', difficulty: 2,
    definitionEn: 'Pre-shift meeting covering schedule, safety, special tasks.', definitionTr: 'Vardiya öncesi program, emniyet, özel görev brifingi.',
    examples: [{ en: 'Daily briefing 6:00 AM.', tr: 'Daily briefing 06:00.' }],
    relatedTerms: ['shift handover', 'team lead', 'safety brief'],
  },
  { id: 'voc_ground_133', term: 'KPI', termTr: 'KPI (Anahtar Performans Göstergesi)', pronunciation: '/keɪ piː aɪ/', category: 'operations', difficulty: 4,
    definitionEn: 'Key Performance Indicator — measurable goals (turnaround time, OTP).', definitionTr: 'Anahtar Performans Göstergesi — ölçülebilir hedefler (turnaround, OTP).',
    examples: [{ en: 'OTP KPI 90%.', tr: 'OTP KPI %90.' }],
    relatedTerms: ['OTP', 'metric', 'performance'],
  },
  { id: 'voc_ground_134', term: 'OTP', termTr: 'OTP (Zamanında Performans)', pronunciation: '/əʊ tiː piː/', category: 'operations', difficulty: 4,
    definitionEn: 'On-Time Performance — % of flights departing/arriving on schedule.', definitionTr: 'Zamanında Performans — programa uyan uçuş yüzdesi.',
    examples: [{ en: 'OTP 90% target.', tr: 'OTP %90 hedef.' }],
    relatedTerms: ['KPI', 'punctuality', 'delay'],
  },
  { id: 'voc_ground_135', term: 'delay code', termTr: 'gecikme kodu', pronunciation: '/dɪˈleɪ kəʊd/', category: 'operations', difficulty: 4,
    definitionEn: 'IATA codes (3-digit) categorizing delay reasons.', definitionTr: 'Gecikme nedenlerini kategorize eden IATA kodları (3 haneli).',
    examples: [{ en: 'Delay code 86 = ATC.', tr: 'Gecikme kodu 86 = ATC.' }],
    relatedTerms: ['IATA', 'delay reason', 'reporting'],
  },
  { id: 'voc_ground_136', term: 'audit', termTr: 'denetim', pronunciation: '/ˈɔː.dɪt/', category: 'operations', difficulty: 3,
    definitionEn: 'Inspection by airline/regulator to verify standards compliance.', definitionTr: 'Standart uyumunu doğrulamak için havayolu/regülatör muayenesi.',
    examples: [{ en: 'IATA ISAGO audit.', tr: 'IATA ISAGO denetimi.' }],
    relatedTerms: ['ISAGO', 'compliance', 'standards'],
  },
  { id: 'voc_ground_137', term: 'ISAGO', termTr: 'ISAGO (IATA yer ops denetimi)', pronunciation: '/ˈaɪ.sə.ɡəʊ/', category: 'operations', difficulty: 5,
    definitionEn: 'IATA Safety Audit for Ground Operations — global standard.', definitionTr: 'Yer Operasyonları için IATA Emniyet Denetimi — global standart.',
    examples: [{ en: 'ISAGO certified GHA.', tr: 'ISAGO sertifikalı GHA.' }],
    relatedTerms: ['IATA', 'audit', 'GHA'],
  },
  { id: 'voc_ground_138', term: 'GHA', termTr: 'GHA (Yer Hizmetleri Şirketi)', pronunciation: '/dʒiː eɪtʃ eɪ/', category: 'industry', difficulty: 3,
    definitionEn: 'Ground Handling Agent — third-party company providing services.', definitionTr: 'Yer Hizmetleri Şirketi — hizmet sağlayan üçüncü taraf şirket.',
    examples: [{ en: 'Çelebi, TGS, Havaş major GHA.', tr: 'Çelebi, TGS, Havaş büyük GHA.' }],
    relatedTerms: ['third-party', 'outsourcing', 'service contract'],
  },
  { id: 'voc_ground_139', term: 'SLA', termTr: 'SLA (Servis Seviyesi Anlaşması)', pronunciation: '/es el eɪ/', category: 'operations', difficulty: 4,
    definitionEn: 'Service Level Agreement — contract defining service quality metrics.', definitionTr: 'Servis Seviyesi Anlaşması — servis kalite metriklerini tanımlayan sözleşme.',
    examples: [{ en: 'SLA 25-min turnaround.', tr: 'SLA 25 dk turnaround.' }],
    relatedTerms: ['contract', 'KPI', 'penalty'],
  },
  { id: 'voc_ground_140', term: 'training new crew', termTr: 'yeni ekip eğitimi', pronunciation: '/ˈtreɪ.nɪŋ njuː kruː/', category: 'leadership', difficulty: 2,
    definitionEn: 'Onboarding and skill development for new ground staff.', definitionTr: 'Yeni yer ekibi için onboarding ve beceri gelişimi.',
    examples: [{ en: 'Training new crew 2 weeks.', tr: 'Yeni ekip eğitimi 2 hafta.' }],
    relatedTerms: ['onboarding', 'mentor', 'skill development'],
  },
];
