/**
 * Lesson tree — her rol için 4 modül × 10 ünite × 5 ders = 200 ders yapısı.
 *
 * Bu yapı SLOT (boş ders kabukları) içerir; gerçek egzersizler
 * lessonGenerator tarafından runtime'da seed vocab'tan üretilir.
 *
 * Tekrarsızlık: kullanıcı her ders için yeni egzersizler görür
 * (60 terim × 8 egzersiz tipi = 480 unique egzersiz/rol).
 */
import type { UserRole } from '@/types/profile';

export interface LessonNode {
  id: string;
  title: string;
  type: 'vocabulary' | 'dialogue' | 'listening' | 'pronunciation' | 'quiz';
  xp: number;
  estimatedMinutes: number;
  isPremium: boolean;
}

export interface UnitNode {
  id: string;
  number: number;
  title: string;
  description: string;
  lessons: LessonNode[];
  badge?: string;
}

export interface ModuleNode {
  id: string;
  number: number;
  title: string;
  description: string;
  units: UnitNode[];
  badge: string;
  rewardXp: number;
}

interface ModuleTemplate {
  number: number;
  title: string;
  description: string;
  badge: string;
  rewardXp: number;
  unitTitles: string[];
}

const PILOT_MODULES: ModuleTemplate[] = [
  // ===== FAZ 1 (A1) — Modul 1-4 =====
  {
    number: 1,
    title: 'Cockpit & Aircraft Basics',
    description: 'Uçak temel parçaları ve kokpit bileşenleri',
    badge: '🛩️',
    rewardXp: 1000,
    unitTitles: [
      'Aircraft Anatomy',
      'Cockpit Components',
      'Engine Basics',
      'Landing Gear & Brakes',
      'Wings & Control Surfaces',
      'Mid-Module Quiz',
      'Fuel System Basics',
      'Electrical System Basics',
      'Hydraulic System Basics',
      'Cockpit Master Final',
    ],
  },
  {
    number: 2,
    title: 'Basic ATC Communication',
    description: 'NATO alfabe, sayılar, frazeoloji',
    badge: '📻',
    rewardXp: 1500,
    unitTitles: [
      'NATO Phonetic Alphabet',
      'Numbers Pronunciation',
      'Call Signs',
      'Roger / Wilco',
      'Frequency Reading',
      'ATC Quiz Checkpoint',
      'Time Reading',
      'Basic Greetings',
      'First Contact Phrases',
      'Radio Operator Final',
    ],
  },
  {
    number: 3,
    title: 'Pre-Flight Procedures',
    description: 'Uçuş öncesi tüm hazırlıklar',
    badge: '✈️',
    rewardXp: 2000,
    unitTitles: [
      'Flight Plan Basics',
      'Weather Briefing',
      'NOTAM Vocabulary',
      'Walk-around Inspection',
      'Cabin Briefing',
      'Pre-Flight Quiz',
      'Pushback Communication',
      'Engine Start',
      'Taxi Phrases',
      'Pre-Flight Pro Final',
    ],
  },
  {
    number: 4,
    title: 'Numbers & Time in Aviation',
    description: 'Heading, altitude, hız, mesafe',
    badge: '🎯',
    rewardXp: 2500,
    unitTitles: [
      'Heading',
      'Altitude',
      'Speed',
      'Distance',
      'Frequency Advanced',
      'Numbers Quiz',
      'Time Conversion',
      'Date Format',
      'Quantity & Volume',
      'A1 Graduate Final',
    ],
  },
  // ===== FAZ 2 (A2 Building) — Modul 5-9 =====
  {
    number: 5,
    title: 'Routine ATC Phraseology',
    description: 'Departure → cruise → arrival tam dialog',
    badge: '📡',
    rewardXp: 3000,
    unitTitles: [
      'Departure Phraseology',
      'Climb Phraseology',
      'Cruise & En-Route',
      'Descent Phraseology',
      'Approach Phraseology',
      'ATC Pro Quiz',
      'Landing Phraseology',
      'Vector Instructions',
      'Speed/Altitude Restrictions',
      'ATC Master Final',
    ],
  },
  {
    number: 6,
    title: 'Aircraft Systems Operational',
    description: 'APU, FMS, autopilot, ECAM',
    badge: '⚙️',
    rewardXp: 3500,
    unitTitles: [
      'APU Operations',
      'FMS Programming',
      'Autopilot Modes',
      'ECAM/EICAS',
      'Pressurization',
      'Systems Pro Quiz',
      'Anti-icing',
      'Hydraulic Failures',
      'Electrical Failures',
      'Systems Pro Final',
    ],
  },
  {
    number: 7,
    title: 'Approach & Landing Basics',
    description: 'ILS, VOR, GPS, RNAV',
    badge: '🛬',
    rewardXp: 4000,
    unitTitles: [
      'ILS Approach',
      'VOR Approach',
      'GPS/RNAV Approach',
      'Glide Slope',
      'Localizer Capture',
      'Approach Quiz',
      'Crosswind Landing',
      'Go-Around Procedures',
      'Missed Approach',
      'Approach Master Final',
    ],
  },
  {
    number: 8,
    title: 'Weather Vocabulary Advanced',
    description: 'METAR full decode, TAF, SIGMET',
    badge: '🌩️',
    rewardXp: 4500,
    unitTitles: [
      'METAR Full Decode',
      'TAF Reading',
      'SIGMET / AIRMET',
      'Wind Shear',
      'Volcanic Ash',
      'Weather Quiz',
      'Icing Conditions',
      'Thunderstorm Avoidance',
      'Fog & Visibility',
      'Weather Pro Final',
    ],
  },
  {
    number: 9,
    title: 'Cabin Coordination',
    description: 'Pilot↔kabin iletişimi',
    badge: '🤝',
    rewardXp: 5000,
    unitTitles: [
      'Pre-Flight Brief',
      'Cabin Crew Calls',
      'Cabin Secure',
      'Turbulence Coordination',
      'Medical Emergency',
      'Coordination Quiz',
      'Security Threats',
      'Disruptive Passengers',
      'Post-Flight Debrief',
      'A2 Graduate Final',
    ],
  },
  // ===== FAZ 3 (B1 Operational) — Modul 10-14 =====
  {
    number: 10,
    title: 'Non-Routine ATC',
    description: 'Standart-dışı durumlar',
    badge: '🚧',
    rewardXp: 6000,
    unitTitles: [
      'Vector Requests',
      'Speed/Altitude Restrictions',
      'Holding Patterns',
      'Re-routing',
      'Conflict Resolution',
      'Non-Routine Quiz',
      'Weather Deviation',
      'Equipment Failures',
      'Lost Communication',
      'Non-Routine Final',
    ],
  },
  {
    number: 11,
    title: 'Emergency Communication',
    description: 'MAYDAY, PAN-PAN, squawk codes',
    badge: '🚨',
    rewardXp: 7000,
    unitTitles: [
      'MAYDAY Procedure',
      'PAN-PAN Procedure',
      'Squawk 7700',
      'Squawk 7600',
      'Squawk 7500',
      'Emergency Quiz',
      'Engine Failure',
      'Fuel Emergency',
      'Medical Emergency Pilot',
      'Emergency Final',
    ],
  },
  {
    number: 12,
    title: 'NOTAM & Weather Advanced',
    description: 'Q-code, TAF probability, SIGMET',
    badge: '🌪️',
    rewardXp: 8000,
    unitTitles: [
      'NOTAM Q-Code Reading',
      'TAF Probability',
      'SIGMET Interpretation',
      'Windshear Advisory',
      'Volcanic Ash',
      'Advanced Weather Quiz',
      'Microburst',
      'Mountain Wave',
      'Decision Making',
      'Weather Master Final',
    ],
  },
  {
    number: 13,
    title: 'International Operations',
    description: 'Aksanlar, kültür, uluslararası ops',
    badge: '🌐',
    rewardXp: 9000,
    unitTitles: [
      'Different ATC Accents',
      'Standard Phraseology Variants',
      'Cultural Awareness Cockpit',
      'Foreign Country Procedures',
      'Datalink Operations',
      'International Quiz',
      'Time Zone Operations',
      'Customs Coordination',
      'Diversion to Foreign',
      'International Final',
    ],
  },
  {
    number: 14,
    title: 'Critical Thinking Aviation',
    description: 'Senaryo analizi, çoklu adım problem çözme',
    badge: '🧠',
    rewardXp: 10000,
    unitTitles: [
      'Scenario Analysis',
      'Multi-step Problem Solving',
      'CRM English Basics',
      'Threat Recognition',
      'Decision Frameworks',
      'CT Quiz',
      'Time-Critical Decisions',
      'Risk Mitigation',
      'Post-Event Reflection',
      'B1 Graduate Final',
    ],
  },
  // ===== FAZ 4 (B2 Professional / ICAO 4) — Modul 15-19 =====
  {
    number: 15,
    title: 'ICAO 4 Mock Exam Series',
    description: '10 set ICAO 4 sözlü sınav simülasyonu',
    badge: '🎯',
    rewardXp: 12000,
    unitTitles: [
      'Picture Description',
      'Story Telling',
      'Problem Solving',
      'Common Topics',
      'Mock Set 1',
      'Mock Quiz Mid',
      'Mock Set 2',
      'Mock Set 3',
      'Mock Set 4',
      'Mock Master Final',
    ],
  },
  {
    number: 16,
    title: 'Airline Interview Prep',
    description: 'THY/Pegasus/Emirates/Qatar mülakat hazırlık',
    badge: '💼',
    rewardXp: 14000,
    unitTitles: [
      'THY Interview',
      'Pegasus Interview',
      'AnadoluJet Interview',
      'Emirates Interview',
      'Qatar Interview',
      'Interview Quiz',
      'Behavioral Interview',
      'Technical Questions',
      'Group Exercises',
      'Interview Master Final',
    ],
  },
  {
    number: 17,
    title: 'Real-World Scenarios',
    description: 'Bird strike, engine failure, medical emergency',
    badge: '⚡',
    rewardXp: 16000,
    unitTitles: [
      'Bird Strike Response',
      'Engine Failure Single',
      'Medical Emergency Diversion',
      'Weather Diversion',
      'Fuel Emergency',
      'Scenarios Quiz',
      'Hijacking Procedure',
      'Bomb Threat',
      'Smoke/Fire Cockpit',
      'Scenarios Master Final',
    ],
  },
  {
    number: 18,
    title: 'Multi-Aircraft Coordination',
    description: 'TCAS RA, formation, helicopter coord',
    badge: '🛫',
    rewardXp: 18000,
    unitTitles: [
      'TCAS RA Scenarios',
      'TA-RA Distinction',
      'Formation Comm',
      'Helicopter Coord',
      'Military Aviation',
      'Coord Quiz',
      'Air Defense',
      'Civil-Military Interface',
      'NORDO Communications',
      'Coord Master Final',
    ],
  },
  {
    number: 19,
    title: 'ICAO 4 Final Prep',
    description: 'Sertifika sınavı son hazırlık',
    badge: '🏆',
    rewardXp: 20000,
    unitTitles: [
      'Diagnostic Test',
      'Weakness Analysis',
      'AI Examiner Practice',
      'Mentor Session',
      'Final Mock Exam',
      'Final Quiz',
      'Pronunciation Polish',
      'Fluency Drill',
      'Comprehension Master',
      'B2 Graduate / ICAO 4 Ready',
    ],
  },
  {
    number: 20,
    title: 'Type Rating English',
    description: 'B737/A320/A330/B777 tip eğitimi',
    badge: '🛩️',
    rewardXp: 22000,
    unitTitles: [
      'B737 Systems Deep',
      'A320 FBW Philosophy',
      'A330 Long-Haul',
      'B777 Heavy Ops',
      'Memory Items C1',
      'Type Rating Quiz',
      'QRH Mastery',
      'FCOM Navigation',
      'Differences Training',
      'Type Rating Final',
    ],
  },
  {
    number: 21,
    title: 'International Operations',
    description: 'ETOPS, Polar, Trans-oceanic, CPDLC',
    badge: '🌍',
    rewardXp: 22000,
    unitTitles: [
      'ETOPS Procedures',
      'Polar Operations',
      'Trans-Oceanic Crossing',
      'CPDLC Datalink',
      'Track Systems NAT/PAC',
      'International Quiz',
      'RVSM Airspace',
      'PBN/RNP Operations',
      'Time Zone Management',
      'International Master',
    ],
  },
  {
    number: 22,
    title: 'CRM & Leadership English',
    description: 'Çoklu mürettebat liderliği',
    badge: '👥',
    rewardXp: 22000,
    unitTitles: [
      'Threat & Error Management',
      'Captain Authority',
      'Co-pilot Assertiveness',
      'Crew Briefings Advanced',
      'Conflict Resolution Cockpit',
      'CRM Quiz',
      'Workload Management',
      'Decision Making C1',
      'Leadership Styles Pilot',
      'CRM Master Final',
    ],
  },
  {
    number: 23,
    title: 'Incident Investigation',
    description: 'Olay bildirimi ve dokümantasyon',
    badge: '📋',
    rewardXp: 22000,
    unitTitles: [
      'ASR Filing',
      'NASA Reports',
      'Witness Statement',
      'Incident Interview',
      'Root Cause Analysis',
      'Investigation Quiz',
      'Just Culture',
      'Confidential Reporting',
      'Lessons Learned Sharing',
      'Investigation Final',
    ],
  },
  {
    number: 24,
    title: 'Aviation Law & C1 Graduation',
    description: 'Hukuk, regülasyon ve C1 sertifika',
    badge: '🎓',
    rewardXp: 30000,
    unitTitles: [
      'ICAO Annexes',
      'EASA Part-FCL',
      'FAR Part 121',
      'Liability & Insurance',
      'Crew Rights & Duties',
      'Law Quiz',
      'C1 Diagnostic',
      'C1 Mock Oral Exam',
      'C1 Pronunciation Polish',
      'C1 Captain Graduate',
    ],
  },
];

const CABIN_MODULES: ModuleTemplate[] = [
  {
    number: 1,
    title: 'Cabin Fundamentals',
    description: 'Kabin ekibi temelleri ve donanım',
    badge: '👨‍✈️',
    rewardXp: 1000,
    unitTitles: [
      'Cabin Crew Roles',
      'Cabin Equipment',
      'Seatbelt & Safety Signs',
      'Galley Basics',
      'Aisle & Seats',
      'Mid-Module Quiz',
      'Tray Tables & Bins',
      'Crew Rest Areas',
      'Jumpseat',
      'Cabin Specialist Final',
    ],
  },
  {
    number: 2,
    title: 'Passenger Communication',
    description: 'PA anonsları ve yolcu etkileşimi',
    badge: '🎙️',
    rewardXp: 1500,
    unitTitles: [
      'Welcome Aboard',
      'Boarding Announcements',
      'Safety Demonstration',
      'During Flight Service',
      'Arrival Announcements',
      'PA Quiz',
      'Special Passengers',
      'Unruly Passenger Handling',
      'Multilingual Service',
      'Communication Pro Final',
    ],
  },
  {
    number: 3,
    title: 'Emergency Procedures',
    description: 'Acil durum prosedürleri ve ekipman',
    badge: '🚨',
    rewardXp: 2000,
    unitTitles: [
      'Doors Armed & Cross Check',
      'Evacuation Slides',
      'Life Vests & Oxygen',
      'Fire Fighting',
      'AED & First Aid',
      'Emergency Quiz',
      'Brace Position',
      'Ditching',
      'Smoke Hood',
      'Safety Pro Final',
    ],
  },
  {
    number: 4,
    title: 'Service & Coordination',
    description: 'Servis akışı ve ekip koordinasyonu',
    badge: '🤝',
    rewardXp: 2500,
    unitTitles: [
      'Meal Service Flow',
      'Special Meals (SSR)',
      'Beverage Service',
      'Duty-Free',
      'Pilot-Cabin Coordination',
      'Service Quiz',
      'Cabin Manager Duties',
      'Pre-Flight Briefing',
      'Interview Preparation',
      'A1 Graduate Final',
    ],
  },
  // ===== FAZ 2 (A2 Building) — Modul 5-9 =====
  {
    number: 5,
    title: 'Advanced Service & Catering',
    description: 'Fine dining, premium hizmet',
    badge: '🍽️',
    rewardXp: 3000,
    unitTitles: [
      'Business Class Service',
      'First Class Standards',
      'Wine & Beverage Pairing',
      'Fine Dining Etiquette',
      'Galley Management',
      'Service Quiz',
      'Pre-order System',
      'Allergen Management',
      'Service Recovery',
      'Service Pro Final',
    ],
  },
  {
    number: 6,
    title: 'Special Situations',
    description: 'İhlal, tıbbi acil, güvenlik',
    badge: '🚨',
    rewardXp: 3500,
    unitTitles: [
      'Medical Emergency',
      'Doctor on Board',
      'Intoxicated Passenger',
      'De-escalation',
      'Restraint Procedures',
      'Special Quiz',
      'Air Marshal Coordination',
      'Bomb Threat',
      'Hijacking Procedures',
      'Special Pro Final',
    ],
  },
  {
    number: 7,
    title: 'Multi-cultural Service',
    description: 'Kültürel farkındalık ve hassasiyet',
    badge: '🌍',
    rewardXp: 4000,
    unitTitles: [
      'Cultural Awareness',
      'Religious Considerations',
      'Halal/Kosher Service',
      'Body Language Cross-culture',
      'Greeting Protocols',
      'Cultural Quiz',
      'VIP Handling',
      'Diplomatic Passengers',
      'Foreign Languages',
      'Cultural Pro Final',
    ],
  },
  {
    number: 8,
    title: 'Senior Crew Duties',
    description: 'Purser ve cabin manager rolleri',
    badge: '👔',
    rewardXp: 4500,
    unitTitles: [
      'Purser Briefing',
      'Crew Coordination',
      'Time Management',
      'Conflict Resolution',
      'Performance Review',
      'Senior Quiz',
      'Captain Reports',
      'Incident Reporting',
      'Mentoring Junior',
      'Senior Pro Final',
    ],
  },
  {
    number: 9,
    title: 'Wellness & Career',
    description: 'Yorgunluk, sağlık, kariyer',
    badge: '💼',
    rewardXp: 5000,
    unitTitles: [
      'Fatigue Management',
      'Jet Lag',
      'Healthy Eating Onboard',
      'Mental Health',
      'Roster Bidding',
      'Wellness Quiz',
      'Career Path',
      'Promotion Strategy',
      'Industry Trends',
      'A2 Graduate Final',
    ],
  },
  // ===== FAZ 3 (B1 Operational) — Modul 10-14 =====
  {
    number: 10,
    title: 'In-Flight Emergencies',
    description: 'Tıbbi, yangın, basınç kaybı',
    badge: '🚨',
    rewardXp: 6000,
    unitTitles: [
      'Medical Emergency Response',
      'Fire Fighting Cabin',
      'Smoke Detection',
      'Decompression Procedures',
      'Emergency Evacuation',
      'Emergency Quiz',
      'Ditching Preparation',
      'Brace Position Coaching',
      'Door Operation Emergency',
      'Emergency Master Final',
    ],
  },
  {
    number: 11,
    title: 'Customer Conflict Resolution',
    description: 'Şikayet, taciz, alkol sorunları',
    badge: '🤝',
    rewardXp: 7000,
    unitTitles: [
      'Active Listening',
      'Empathy Techniques',
      'Apology Strategy',
      'Compensation Authority',
      'Documentation',
      'Conflict Quiz',
      'Discrimination Cases',
      'Harassment Response',
      'Refusal of Service',
      'Resolution Pro Final',
    ],
  },
  {
    number: 12,
    title: 'Catering Crisis Management',
    description: 'Eksik catering, kalite, alerji',
    badge: '🍱',
    rewardXp: 8000,
    unitTitles: [
      'Missing Meals',
      'Quality Issues',
      'Allergy Incidents',
      'Religious Meal Errors',
      'Dietary Restrictions',
      'Catering Quiz',
      'VIP Catering Issues',
      'Beverage Shortages',
      'Hot Meal Cold Issues',
      'Catering Pro Final',
    ],
  },
  {
    number: 13,
    title: 'Long-haul Specialization',
    description: 'Uzun mesafe operasyonel beceriler',
    badge: '✈️',
    rewardXp: 9000,
    unitTitles: [
      'Long-haul Service Flow',
      'Crew Rest Management',
      'Sleep Cycle Coordination',
      'Light Management',
      'Mid-flight Service',
      'Long-haul Quiz',
      'Connection Information',
      'Time Zone Crossing',
      'Pre-arrival Service',
      'Long-haul Pro Final',
    ],
  },
  {
    number: 14,
    title: 'Cabin Manager Skills',
    description: 'Purser sorumlulukları',
    badge: '👨‍💼',
    rewardXp: 10000,
    unitTitles: [
      'Pre-flight Briefing Lead',
      'Crew Resource Allocation',
      'Performance Coaching',
      'Captain Liaison',
      'Inflight Decisions',
      'Manager Quiz',
      'Incident Reporting Detail',
      'Audit Compliance',
      'Crew Mentoring',
      'B1 Graduate Final',
    ],
  },
  // ===== FAZ 4 (B2 Professional / ICAO 4) — Modul 15-19 =====
  {
    number: 15,
    title: 'THY/Pegasus Interview Mastery',
    description: 'Türk havayolları kabin mülakat hazırlığı',
    badge: '🇹🇷',
    rewardXp: 12000,
    unitTitles: [
      'THY Interview Format',
      'Pegasus Interview',
      'AnadoluJet/SunExpress',
      'Group Exercise Mastery',
      'Role-play Scenarios',
      'Interview Quiz',
      'Behavioral Questions Advanced',
      'STAR Method Practice',
      'Salary Negotiation',
      'Interview Master Final',
    ],
  },
  {
    number: 16,
    title: 'Senior Cabin Manager',
    description: 'Kıdemli purser ve süpervizörlük',
    badge: '👔',
    rewardXp: 14000,
    unitTitles: [
      'Leadership Foundations',
      'Decision Making Cabin',
      'Team Building',
      'Conflict Mediation',
      'Performance Management',
      'Senior Quiz',
      'Strategic Communication',
      'Customer Excellence Leadership',
      'CRM in Cabin',
      'Senior Master Final',
    ],
  },
  {
    number: 17,
    title: 'Multilingual Service',
    description: 'Çok dilli premium servis',
    badge: '🌍',
    rewardXp: 16000,
    unitTitles: [
      'English Mastery',
      'Aviation French Basics',
      'Aviation German',
      'Aviation Russian',
      'Aviation Arabic',
      'Multilingual Quiz',
      'Cultural Etiquette',
      'Translation Skills',
      'Sign Language Basics',
      'Language Master Final',
    ],
  },
  {
    number: 18,
    title: 'Crisis Leadership',
    description: 'Acil durumda liderlik',
    badge: '🚨',
    rewardXp: 18000,
    unitTitles: [
      'Crisis Decision Making',
      'Evacuation Leadership',
      'Medical Crisis Mgmt',
      'Security Threat Lead',
      'Communication Under Stress',
      'Crisis Quiz',
      'Post-Crisis Debrief',
      'Crew Mental Health',
      'Family Liaison',
      'Crisis Master Final',
    ],
  },
  {
    number: 19,
    title: 'Career Specialization',
    description: 'Purser/inflight manager yolu',
    badge: '🎯',
    rewardXp: 20000,
    unitTitles: [
      'Purser Path',
      'Inflight Manager',
      'Trainer Path',
      'Aviation HR',
      'International Roles',
      'Career Quiz',
      'Personal Brand Senior',
      'Mentorship Program',
      'Industry Networking',
      'B2 Graduate Final',
    ],
  },
  {
    number: 20,
    title: 'Premium Cabin Service',
    description: 'First/Business class servisi',
    badge: '🥂',
    rewardXp: 22000,
    unitTitles: [
      'First Class Standards',
      'Business Class Service',
      'Wine & Dine Service',
      'Caviar & Champagne',
      'Personalized Service',
      'Premium Quiz',
      'Suite Configuration',
      'Turnaround Premium',
      'Loyalty Program Talk',
      'Premium Master',
    ],
  },
  {
    number: 21,
    title: 'VIP & Charter Operations',
    description: 'VVIP, Head of State, charter',
    badge: '👑',
    rewardXp: 22000,
    unitTitles: [
      'Head of State Protocol',
      'Royal Family Service',
      'Celebrity Privacy',
      'Charter Briefings',
      'Special Catering VIP',
      'VIP Quiz',
      'Confidentiality NDA',
      'Bodyguard Coordination',
      'Custom Itinerary',
      'VIP Master Final',
    ],
  },
  {
    number: 22,
    title: 'Cabin Trainer Mastery',
    description: 'Eğitmen liderliği ve standardizasyon',
    badge: '🎓',
    rewardXp: 22000,
    unitTitles: [
      'Adult Learning Theory',
      'Curriculum Design',
      'Assessment Methods',
      'OPC Conduct',
      'Standardization Meet',
      'Trainer Quiz',
      'Feedback Frameworks',
      'Difficult Trainees',
      'Train the Trainer',
      'Master Trainer Final',
    ],
  },
  {
    number: 23,
    title: 'Safety Investigation Lead',
    description: 'Kabin güvenlik soruşturma liderliği',
    badge: '🔍',
    rewardXp: 22000,
    unitTitles: [
      'Safety Report Lead',
      'Witness Coordination',
      'CVR Cabin Analysis',
      'Smoke/Fire Investigation',
      'Decompression Analysis',
      'Investigation Quiz',
      'Trend Analysis',
      'Safety Recommendation',
      'Board Presentation',
      'Investigation Master',
    ],
  },
  {
    number: 24,
    title: 'Industry Future & C1 Grad',
    description: 'Gelecek ve C1 sertifikası',
    badge: '🌟',
    rewardXp: 30000,
    unitTitles: [
      'Sustainable Aviation Cabin',
      'Robotics in Cabin',
      'AR/VR Crew Training',
      'Diversity & Inclusion',
      'Mental Health Crew',
      'Future Quiz',
      'C1 Diagnostic',
      'C1 Mock Exam',
      'C1 Polish',
      'C1 Senior Graduate',
    ],
  },
];

const TECHNICIAN_MODULES: ModuleTemplate[] = [
  {
    number: 1,
    title: 'Tools & Workshop Basics',
    description: 'Atelye aletleri ve FOD önlemi',
    badge: '🔧',
    rewardXp: 1000,
    unitTitles: [
      'Hand Tools',
      'Measuring Tools',
      'Power Tools',
      'Safety Equipment (PPE)',
      'Workshop Layout',
      'Tools Quiz',
      'Tool Storage & FOD',
      'Tool Calibration',
      'Tool Requisition',
      'Tools Specialist Final',
    ],
  },
  {
    number: 2,
    title: 'AMM & Documentation',
    description: 'Bakım el kitabı ve ATA chapter',
    badge: '📚',
    rewardXp: 1500,
    unitTitles: [
      'What is AMM',
      'ATA Chapter System',
      'Job Cards',
      'IPC',
      'WDM Basics',
      'Doc Quiz',
      'Service Bulletins',
      'Airworthiness Directives',
      'Document Revisions',
      'Documentation Pro Final',
    ],
  },
  {
    number: 3,
    title: 'Aircraft Systems Overview',
    description: 'Uçak sistemleri genel bakış',
    badge: '⚙️',
    rewardXp: 2000,
    unitTitles: [
      'Powerplant Basics',
      'Hydraulic System',
      'Electrical System',
      'Pneumatic / Bleed',
      'Fuel System',
      'Systems Quiz',
      'Flight Controls',
      'Landing Gear Systems',
      'Avionics Intro',
      'Systems Aware Final',
    ],
  },
  {
    number: 4,
    title: 'Inspection & Hardware',
    description: 'NDT, hardware ve kalite',
    badge: '🔍',
    rewardXp: 2500,
    unitTitles: [
      'Visual Inspection',
      'Common Defects',
      'Fasteners',
      'Lockwire & Torque Seal',
      'Cotter Pins',
      'Inspection Quiz',
      'NDT Introduction',
      'Quality Control',
      'Defect Reporting',
      'A1 Apprentice Final',
    ],
  },
  // ===== FAZ 2 (A2 Building) — Modul 5-9 =====
  {
    number: 5,
    title: 'Routine Maintenance Tasks',
    description: 'Hat bakımı ve günlük operasyonlar',
    badge: '🛠️',
    rewardXp: 3000,
    unitTitles: [
      'Daily Inspection',
      'Pre-Flight Checks',
      'Post-Flight Checks',
      'Tire Pressure',
      'Oil Service',
      'Maintenance Quiz',
      'Hydraulic Service',
      'Brake Wear Check',
      'Light Maintenance',
      'Routine Pro Final',
    ],
  },
  {
    number: 6,
    title: 'Defect Investigation',
    description: 'Arıza tespit ve troubleshoot',
    badge: '🔬',
    rewardXp: 3500,
    unitTitles: [
      'TSM Methodology',
      'Fault Codes',
      'BITE System',
      'Component Test',
      'Wiring Trace',
      'Defect Quiz',
      'Intermittent Faults',
      'Cabin Defects',
      'Customer Reports',
      'Defect Pro Final',
    ],
  },
  {
    number: 7,
    title: 'Component Removal/Install',
    description: 'Komponent değişimi prosedürleri',
    badge: '🔄',
    rewardXp: 4000,
    unitTitles: [
      'Removal Procedures',
      'Storage & Handling',
      'Installation Steps',
      'Torque Procedures',
      'Functional Test',
      'R&I Quiz',
      'Calibration Post-Install',
      'Sign-off Process',
      'Documentation',
      'R&I Pro Final',
    ],
  },
  {
    number: 8,
    title: 'Engine Maintenance',
    description: 'Motor bakım ve overhaul',
    badge: '🚀',
    rewardXp: 4500,
    unitTitles: [
      'Engine Inspection',
      'Borescope Inspection',
      'Hot Start Recovery',
      'EGT Trend Monitoring',
      'Compressor Wash',
      'Engine Quiz',
      'On-Wing Repair',
      'Module Change',
      'Engine Run-up',
      'Engine Pro Final',
    ],
  },
  {
    number: 9,
    title: 'Hydraulic Maintenance',
    description: 'Hidrolik sistem bakımı',
    badge: '💧',
    rewardXp: 5000,
    unitTitles: [
      'Hydraulic Fluid',
      'Pump Testing',
      'Leak Detection',
      'Pressure Testing',
      'Filter Change',
      'Hydraulic Quiz',
      'EDP Replacement',
      'Reservoir Service',
      'Accumulator Charge',
      'A2 Graduate Final',
    ],
  },
  // ===== FAZ 3 (B1 Operational) — Modul 10-14 =====
  {
    number: 10,
    title: 'Heavy Maintenance Procedures',
    description: 'C/D-check yoğun çalışmalar',
    badge: '🏗️',
    rewardXp: 6000,
    unitTitles: [
      'Heavy Check Planning',
      'Disassembly Procedures',
      'Deep Inspection',
      'Repair Schemes',
      'Re-assembly',
      'Heavy Quiz',
      'Modification Embodiment',
      'Test Flight Prep',
      'Return to Service',
      'Heavy Pro Final',
    ],
  },
  {
    number: 11,
    title: 'Avionics Troubleshooting',
    description: 'Avionik arıza tanı',
    badge: '🔌',
    rewardXp: 7000,
    unitTitles: [
      'BITE Diagnostics',
      'Connector Testing',
      'Wire Continuity',
      'LRU Replacement',
      'System Reconfiguration',
      'Avionics Quiz',
      'EFIS Issues',
      'FMS Reprogramming',
      'Datalink Faults',
      'Avionics Pro Final',
    ],
  },
  {
    number: 12,
    title: 'Composite Repair',
    description: 'Kompozit hasar tamiri',
    badge: '🧬',
    rewardXp: 8000,
    unitTitles: [
      'Composite Inspection',
      'Damage Categorization',
      'Repair Materials',
      'Wet Layup',
      'Curing Procedures',
      'Composite Quiz',
      'Surface Preparation',
      'Bonding Repair',
      'Quality Verification',
      'Composite Pro Final',
    ],
  },
  {
    number: 13,
    title: 'Engine Performance Analysis',
    description: 'Motor performansı izleme',
    badge: '📊',
    rewardXp: 9000,
    unitTitles: [
      'Trend Monitoring',
      'EGT Margin',
      'Vibration Analysis',
      'Oil Consumption',
      'Power Assurance',
      'Performance Quiz',
      'Hot Section Health',
      'Compressor Health',
      'Predictive Maintenance',
      'Performance Pro Final',
    ],
  },
  {
    number: 14,
    title: 'Maintenance Planning',
    description: 'Bakım planlaması ve yönetim',
    badge: '📅',
    rewardXp: 10000,
    unitTitles: [
      'MEL Application',
      'Deferred Items',
      'Scheduled Tasks',
      'AD/SB Tracking',
      'Resource Allocation',
      'Planning Quiz',
      'Tool Inventory',
      'Spare Parts Planning',
      'Continuing Airworthiness',
      'B1 Graduate Final',
    ],
  },
  // ===== FAZ 4 (B2 Professional / ICAO 4) — Modul 15-19 =====
  {
    number: 15,
    title: 'B1/B2 License Prep',
    description: 'EASA Part-66 B1/B2 lisans hazırlığı',
    badge: '📜',
    rewardXp: 12000,
    unitTitles: [
      'Part-66 Modules',
      'Module 9 Human Factors',
      'Module 10 Aviation Legislation',
      'Type Rating Theory',
      'Practical Experience',
      'License Quiz',
      'OJT (On-Job Training)',
      'Examination Strategy',
      'Logbook Maintenance',
      'License Master Final',
    ],
  },
  {
    number: 16,
    title: 'Advanced NDT',
    description: 'İleri NDT yöntemleri',
    badge: '🔬',
    rewardXp: 14000,
    unitTitles: [
      'Phased Array UT',
      'Computed Radiography',
      'Thermography',
      'Acoustic Emission',
      'Shearography',
      'NDT Quiz',
      'NDT Level 3 Path',
      'Composite NDT',
      'Special Process Qualification',
      'NDT Master Final',
    ],
  },
  {
    number: 17,
    title: 'Engine Heavy Maintenance',
    description: 'Motor genel revizyon',
    badge: '🚀',
    rewardXp: 16000,
    unitTitles: [
      'Engine Removal',
      'Module Disassembly',
      'Hot Section Repair',
      'Cold Section Refurb',
      'Engine Test Cell',
      'Engine HM Quiz',
      'Performance Tuning',
      'Build & Reassembly',
      'Final Engine Test',
      'Engine HM Master Final',
    ],
  },
  {
    number: 18,
    title: 'Avionics Mastery',
    description: 'Avionik uzmanlık',
    badge: '⚡',
    rewardXp: 18000,
    unitTitles: [
      'Digital Bus Systems',
      'ARINC Standards',
      'Software Loading',
      'Datalink Systems',
      'GPS/GNSS Systems',
      'Avionics Quiz',
      'Cabin Systems',
      'Cybersecurity Avionics',
      'Future Avionics',
      'Avionics Master Final',
    ],
  },
  {
    number: 19,
    title: 'Certifying Staff Path',
    description: 'CRS yetkili teknisyen yolu',
    badge: '✅',
    rewardXp: 20000,
    unitTitles: [
      'Authorization Process',
      'Type-specific Authorization',
      'B1 vs B2 vs C',
      'Quality Audits',
      'Continuation Training',
      'CRS Quiz',
      'Documentation Mastery',
      'Audit Defense',
      'Career Roadmap',
      'B2 Graduate Final',
    ],
  },
  {
    number: 20,
    title: 'Type Rating Mastery',
    description: 'Boeing/Airbus tip yetkisi C1',
    badge: '🛠️',
    rewardXp: 22000,
    unitTitles: [
      'B737NG/MAX Differences',
      'A320neo Family',
      'B787 Composite Heavy',
      'A350 XWB Tech',
      'Heavy Maintenance Check',
      'Type Quiz',
      'C-Check Planning',
      'D-Check Overhaul',
      'AD/SB Compliance Mass',
      'Type Master Final',
    ],
  },
  {
    number: 21,
    title: 'MRO Management',
    description: 'Bakım operasyon yönetimi',
    badge: '🏭',
    rewardXp: 22000,
    unitTitles: [
      'Hangar Planning',
      'Manpower Allocation',
      'TAT Optimization',
      'MRO Customer Mgmt',
      'Subcontracting',
      'MRO Quiz',
      'Cost Estimation',
      'Quality KPI',
      'Lean Maintenance',
      'MRO Manager Final',
    ],
  },
  {
    number: 22,
    title: 'Engineering Authority',
    description: 'DOA/POA mühendislik yetki',
    badge: '🛡️',
    rewardXp: 22000,
    unitTitles: [
      'Design Org Approval',
      'Production Org Approval',
      'Major vs Minor Repair',
      'EO Engineering Order',
      'STC Process',
      'Authority Quiz',
      'CVE Compliance Verif',
      'Stress Analysis',
      'Repair Approval',
      'DOA Master Final',
    ],
  },
  {
    number: 23,
    title: 'Reliability Engineering',
    description: 'Güvenilirlik analizi',
    badge: '📈',
    rewardXp: 22000,
    unitTitles: [
      'MTBF/MTBUR',
      'Component Reliability',
      'Trend Monitoring',
      'Reliability Programs',
      'Predictive Maintenance',
      'Reliability Quiz',
      'Big Data Aviation',
      'IoT Sensor Fleet',
      'AI Predictive',
      'Reliability Master',
    ],
  },
  {
    number: 24,
    title: 'Regulations Mastery & C1 Grad',
    description: 'EASA/FAA/CAA derinlik + C1',
    badge: '🎓',
    rewardXp: 30000,
    unitTitles: [
      'EASA Part-145 Deep',
      'EASA Part-M Deep',
      'FAR Part 145',
      'CAA Differences',
      'Audit Defense Mastery',
      'Regs Quiz',
      'C1 Diagnostic',
      'C1 Technical Speech',
      'C1 Polish',
      'C1 Engineer Graduate',
    ],
  },
];

const GROUND_MODULES: ModuleTemplate[] = [
  {
    number: 1,
    title: 'Ramp & Marshalling',
    description: 'Apron operasyonları',
    badge: '🛬',
    rewardXp: 1000,
    unitTitles: [
      'Ramp Basics',
      'Marshalling Signals',
      'Wands & Chocks',
      'Tug & Towbar',
      'Jet Bridge & Stairs',
      'Ramp Quiz',
      'Parking Position',
      'Stand Types',
      'Gate Coordination',
      'Ramp Specialist Final',
    ],
  },
  {
    number: 2,
    title: 'Pushback & Taxi',
    description: 'Pushback ve taksi prosedürleri',
    badge: '⬅️',
    rewardXp: 1500,
    unitTitles: [
      'Pushback Procedure',
      'Brakes Set Communication',
      'Headset Operations',
      'Taxi Coordination',
      'Follow-me Car',
      'Pushback Quiz',
      'Aircraft Movement',
      'GSE Operation',
      'GPU Connection',
      'Pushback Pro Final',
    ],
  },
  {
    number: 3,
    title: 'Baggage & Fuel',
    description: 'Bagaj ve yakıt operasyonları',
    badge: '🧳',
    rewardXp: 2000,
    unitTitles: [
      'Baggage Handling',
      'Belt Loaders',
      'Cargo Hold & ULDs',
      'Baggage Tags',
      'Lost Baggage',
      'Baggage Quiz',
      'Fuel Operations',
      'Bonding Cable',
      'Spill Response',
      'Baggage & Fuel Final',
    ],
  },
  {
    number: 4,
    title: 'Safety & Operations',
    description: 'Emniyet ve operasyon',
    badge: '🦺',
    rewardXp: 2500,
    unitTitles: [
      'PPE Standards',
      'Hi-Vis & Ear Protection',
      'Jet Blast Hazards',
      'Engine Intake Safety',
      'FOD Prevention',
      'Safety Quiz',
      'De-icing / Anti-icing',
      'Shift Handover',
      'Incident Reporting',
      'A1 Graduate Final',
    ],
  },
  // ===== FAZ 2 (A2 Building) — Modul 5-9 =====
  {
    number: 5,
    title: 'Advanced Ramp Operations',
    description: 'Karmaşık ramp senaryoları',
    badge: '🛫',
    rewardXp: 3000,
    unitTitles: [
      'Multi-aircraft Coordination',
      'Wide-body Operations',
      'VIP Handling',
      'Charter Flights',
      'Diplomatic Cargo',
      'Ramp Quiz',
      'Night Operations',
      'Adverse Weather',
      'Tight Turnaround',
      'Ramp Pro Final',
    ],
  },
  {
    number: 6,
    title: 'Cargo Handling Specialized',
    description: 'Tehlikeli madde, canlı hayvan, perishable',
    badge: '📦',
    rewardXp: 3500,
    unitTitles: [
      'IATA DGR Compliance',
      'Lithium Battery Cargo',
      'Live Animal Transport',
      'Perishable Cool Chain',
      'Heavy Freight',
      'Cargo Quiz',
      'Pharma Logistics',
      'Diplomatic Pouches',
      'Customs Clearance',
      'Cargo Pro Final',
    ],
  },
  {
    number: 7,
    title: 'De-icing Procedures',
    description: 'Buz çözme detaylı',
    badge: '❄️',
    rewardXp: 4000,
    unitTitles: [
      'Type I/II/III/IV Fluids',
      'Holdover Time Charts',
      'CCAR Procedures',
      'Pre-deicing Checks',
      'Communication Protocols',
      'De-icing Quiz',
      'Anti-icing Application',
      'Recheck Procedures',
      'Environmental Concerns',
      'De-icing Pro Final',
    ],
  },
  {
    number: 8,
    title: 'Emergency Response',
    description: 'Yangın, sızıntı, tıbbi',
    badge: '🚒',
    rewardXp: 4500,
    unitTitles: [
      'Fuel Spill Response',
      'Aircraft Fire',
      'Medical Emergency',
      'Bomb Threat',
      'Security Breach',
      'Emergency Quiz',
      'Evacuation Support',
      'First Responders Coord',
      'Aftermath Investigation',
      'Emergency Pro Final',
    ],
  },
  {
    number: 9,
    title: 'Crew Leadership',
    description: 'Süpervizör ve yönetim',
    badge: '👷',
    rewardXp: 5000,
    unitTitles: [
      'Team Leadership',
      'Daily Briefing',
      'Performance Coaching',
      'Conflict Resolution',
      'KPI Monitoring',
      'Leadership Quiz',
      'Training New Crew',
      'Audit Preparation',
      'Customer Reporting',
      'A2 Graduate Final',
    ],
  },
  // ===== FAZ 3 (B1 Operational) — Modul 10-14 =====
  {
    number: 10,
    title: 'Disruption Management',
    description: 'Gecikme, iptal, kriz yönetimi',
    badge: '⚠️',
    rewardXp: 6000,
    unitTitles: [
      'Delay Codes',
      'Cancellation Procedures',
      'Diversion Operations',
      'Aircraft Swap',
      'Crew Reassignment',
      'Disruption Quiz',
      'Passenger Care',
      'Hotel Vouchers',
      'Recovery Operations',
      'Disruption Pro Final',
    ],
  },
  {
    number: 11,
    title: 'Special Cargo Operations',
    description: 'Tehlikeli, canlı, sıcaklık kontrollü',
    badge: '📦',
    rewardXp: 7000,
    unitTitles: [
      'IATA DGR Compliance',
      'Lithium Battery Loading',
      'Live Animal Cargo',
      'Pharma Logistics',
      'Diplomatic Pouches',
      'Cargo Quiz',
      'Heavy Freight',
      'Oversize Cargo',
      'Customs Coordination',
      'Special Cargo Final',
    ],
  },
  {
    number: 12,
    title: 'Multi-Carrier Coordination',
    description: 'Çok havayolu hub yönetimi',
    badge: '🌐',
    rewardXp: 8000,
    unitTitles: [
      'Hub Operations',
      'Inter-airline Communication',
      'Codeshare Operations',
      'Alliance Procedures',
      'Connection Management',
      'Multi-Carrier Quiz',
      'Resource Sharing',
      'Time Slot Coordination',
      'Mutual Support Agreements',
      'Multi-Carrier Final',
    ],
  },
  {
    number: 13,
    title: 'Operations Performance',
    description: 'KPI, OTP, verimlilik analizi',
    badge: '📈',
    rewardXp: 9000,
    unitTitles: [
      'KPI Definition',
      'OTP Measurement',
      'Turnaround Analytics',
      'Cost Control',
      'Productivity Metrics',
      'Performance Quiz',
      'Benchmarking',
      'Continuous Improvement',
      'Reporting to Customers',
      'Performance Pro Final',
    ],
  },
  {
    number: 14,
    title: 'Safety Auditing',
    description: 'IATA ISAGO, denetim hazırlığı',
    badge: '✅',
    rewardXp: 10000,
    unitTitles: [
      'ISAGO Standards',
      'IOSA Audit',
      'Internal Audits',
      'Audit Preparation',
      'Non-Conformance Handling',
      'Audit Quiz',
      'CAPA Process',
      'Safety Risk Assessment',
      'Continuous Compliance',
      'B1 Graduate Final',
    ],
  },
  // ===== FAZ 4 (B2 Professional / ICAO 4) — Modul 15-19 =====
  {
    number: 15,
    title: 'Senior Ramp Manager',
    description: 'Kıdemli ramp yöneticisi',
    badge: '👔',
    rewardXp: 12000,
    unitTitles: [
      'Strategic Planning',
      'Resource Optimization',
      'Multi-team Leadership',
      'Vendor Management',
      'Customer Relations',
      'Senior Quiz',
      'Crisis Management',
      'Performance Reviews',
      'Hiring & Development',
      'Senior Master Final',
    ],
  },
  {
    number: 16,
    title: 'Multi-Carrier Lead',
    description: 'Çoklu havayolu yönetimi',
    badge: '🌐',
    rewardXp: 14000,
    unitTitles: [
      'Hub Coordination',
      'Inter-airline Disputes',
      'Resource Sharing',
      'SLA Management',
      'Codeshare Logistics',
      'Multi-Carrier Quiz',
      'Alliance Operations',
      'Joint Ventures',
      'Strategic Partnerships',
      'Multi-Carrier Master Final',
    ],
  },
  {
    number: 17,
    title: 'Audit Lead Preparation',
    description: 'IOSA/ISAGO baş denetçi yolu',
    badge: '🔍',
    rewardXp: 16000,
    unitTitles: [
      'Audit Methodology',
      'Evidence Collection',
      'Auditor Communication',
      'Finding Analysis',
      'CAPA Mentoring',
      'Audit Quiz',
      'Compliance Strategy',
      'Continuous Audit',
      'Lead Auditor Cert',
      'Audit Master Final',
    ],
  },
  {
    number: 18,
    title: 'Disruption Crisis Leadership',
    description: 'Aksaklık krizi yönetimi',
    badge: '⚡',
    rewardXp: 18000,
    unitTitles: [
      'IRROPS Strategy',
      'Recovery Planning',
      'Customer Communication',
      'Crew Coordination',
      'Media Management',
      'Crisis Quiz',
      'Stakeholder Mgmt',
      'Lessons Learned',
      'Resilience Building',
      'Crisis Master Final',
    ],
  },
  {
    number: 19,
    title: 'Industry Career Advanced',
    description: 'İleri kariyer yolu',
    badge: '🎯',
    rewardXp: 20000,
    unitTitles: [
      'Director Path',
      'GHA Operations Manager',
      'Airline Ops VP',
      'Consultancy',
      'Aviation Education',
      'Career Quiz',
      'Industry Conferences',
      'Thought Leadership',
      'Mentor Network',
      'B2 Graduate Final',
    ],
  },
  {
    number: 20,
    title: 'Hub Operations Director',
    description: 'Hub direktörü stratejik liderlik',
    badge: '🏢',
    rewardXp: 22000,
    unitTitles: [
      'Hub Strategy',
      'Connecting Banks Design',
      'MCT Optimization',
      'Slot Coordination',
      'Hub Crisis Lead',
      'Hub Quiz',
      'Capacity Planning',
      'Stakeholder Govt',
      'Board Reporting',
      'Hub Director Final',
    ],
  },
  {
    number: 21,
    title: 'Network Planning',
    description: 'Network ve slot koordinasyonu',
    badge: '🌐',
    rewardXp: 22000,
    unitTitles: [
      'Slot Allocation IATA',
      'WSG Worldwide Slot',
      'Network Strategy',
      'Code-share Planning',
      'Joint Venture',
      'Network Quiz',
      'Bilateral Agreements',
      'Open Skies Treaty',
      'Slot Trading',
      'Network Master',
    ],
  },
  {
    number: 22,
    title: 'GHA Industry Leadership',
    description: 'Yer hizmetleri liderliği',
    badge: '🏆',
    rewardXp: 22000,
    unitTitles: [
      'GHA Market Dynamics',
      'Tender Strategy',
      'Pricing Models GHA',
      'Multi-Airport Lead',
      'GHA Innovation',
      'GHA Quiz',
      'Industry Associations',
      'IATA AHM Standards',
      'GHA Future Tech',
      'GHA Leader Final',
    ],
  },
  {
    number: 23,
    title: 'Compliance Director',
    description: 'Regülasyon direktörlüğü',
    badge: '⚖️',
    rewardXp: 22000,
    unitTitles: [
      'IATA ISAGO Audit',
      'IOSA Lead',
      'Civil Aviation Authority',
      'Compliance Framework',
      'Risk Register',
      'Compliance Quiz',
      'Internal Audit Mgmt',
      'Whistleblower Policy',
      'Ethics & Integrity',
      'Compliance Director Final',
    ],
  },
  {
    number: 24,
    title: 'Industry Future & C1 Grad',
    description: 'Endüstri geleceği + C1',
    badge: '🚀',
    rewardXp: 30000,
    unitTitles: [
      'Sustainable Ground Ops',
      'Electric Ground Vehicles',
      'Autonomous Tugs',
      'Biometrics Boarding',
      'Touchless Travel',
      'Future Quiz',
      'C1 Diagnostic',
      'C1 Executive Speech',
      'C1 Polish',
      'C1 Director Graduate',
    ],
  },
];

const STUDENT_MODULES: ModuleTemplate[] = [
  {
    number: 1,
    title: 'Aviation Fundamentals',
    description: 'Havacılık temelleri',
    badge: '🎓',
    rewardXp: 1000,
    unitTitles: [
      'What is Aviation',
      'Types of Aircraft',
      'Airlines & Hubs',
      'Airports',
      'Runways & Taxiways',
      'Fundamentals Quiz',
      'Pilot Career',
      'Cabin Crew Career',
      'Other Careers',
      'Fundamentals Final',
    ],
  },
  {
    number: 2,
    title: 'University & Education',
    description: 'Üniversite ve eğitim',
    badge: '📖',
    rewardXp: 1500,
    unitTitles: [
      'YKS Basics',
      'Aviation Faculty',
      'Pilotage Programs',
      'PPL / CPL / ATPL',
      'Flight Schools',
      'Education Quiz',
      'Simulator Training',
      'Theoretical Exams',
      'Practical Training',
      'Education Pro Final',
    ],
  },
  {
    number: 3,
    title: 'Exams & Certifications',
    description: 'Sınavlar ve sertifikalar',
    badge: '📝',
    rewardXp: 2000,
    unitTitles: [
      'ICAO Level 4',
      'ICAO Level 5+',
      'SHGM Authority',
      'EASA Standards',
      'TOEFL / IELTS',
      'Exam Quiz',
      'YDS Aviation',
      'Medical Certificate',
      'Background Check',
      'Cert Pro Final',
    ],
  },
  {
    number: 4,
    title: 'Career Preparation',
    description: 'Kariyer hazırlığı',
    badge: '🚀',
    rewardXp: 2500,
    unitTitles: [
      'CV & Cover Letter',
      'Internships',
      'Interview Basics',
      'STAR Method',
      'Behavioral Questions',
      'Career Quiz',
      'Group Exercises',
      'Salary Negotiation',
      'Industry Networking',
      'A1 Graduate Final',
    ],
  },
  // ===== FAZ 2 (A2 Building) — Modul 5-9 =====
  {
    number: 5,
    title: 'Aviation English Comprehension',
    description: 'Havacılık İngilizcesi anlama',
    badge: '👂',
    rewardXp: 3000,
    unitTitles: [
      'ATC Listening',
      'Cockpit Voice Recordings',
      'Pilot-ATC Dialogues',
      'Multi-accent Practice',
      'Background Noise Training',
      'Listening Quiz',
      'Speech Patterns',
      'Stressed Speech',
      'Emergency Calls',
      'Listening Pro Final',
    ],
  },
  {
    number: 6,
    title: 'Industry Vocabulary Deep',
    description: 'Sektör terminolojisi',
    badge: '📚',
    rewardXp: 3500,
    unitTitles: [
      'Airline Operations Lingo',
      'Maintenance Terms',
      'Manufacturing Terms',
      'Regulatory Terms',
      'Insurance & Legal',
      'Industry Quiz',
      'Finance Terms',
      'IT & Avionics Crossover',
      'Marketing & Sales',
      'Industry Pro Final',
    ],
  },
  {
    number: 7,
    title: 'Aviation Math & Physics',
    description: 'Hesaplama ve fizik',
    badge: '🧮',
    rewardXp: 4000,
    unitTitles: [
      'Speed Calculations',
      'Fuel Burn Math',
      'Weight & Balance Math',
      'Time-Distance-Speed',
      'Conversion Practice',
      'Math Quiz',
      'Trigonometry Basic',
      'Physics of Flight',
      'Performance Charts',
      'Math Pro Final',
    ],
  },
  {
    number: 8,
    title: 'Crisis Management Concepts',
    description: 'Kriz yönetimi kavramları',
    badge: '⚠️',
    rewardXp: 4500,
    unitTitles: [
      'Decision Making',
      'CRM Principles',
      'Threat Recognition',
      'Error Management',
      'Recovery Strategies',
      'Crisis Quiz',
      'Communication Under Stress',
      'Leadership in Crisis',
      'Post-Event Analysis',
      'Crisis Pro Final',
    ],
  },
  {
    number: 9,
    title: 'Career Advanced',
    description: 'İleri kariyer planlama',
    badge: '💼',
    rewardXp: 5000,
    unitTitles: [
      'Long-term Planning',
      'Specialization Paths',
      'International Career',
      'Network Building',
      'Mentorship',
      'Career Quiz',
      'Personal Branding',
      'LinkedIn Optimization',
      'Conference Networking',
      'A2 Graduate Final',
    ],
  },
  // ===== FAZ 3 (B1 Operational) — Modul 10-14 =====
  {
    number: 10,
    title: 'Aviation Documents Reading',
    description: 'Belge ve doküman okuma',
    badge: '📜',
    rewardXp: 6000,
    unitTitles: [
      'AIP Reading',
      'Charts Interpretation',
      'NOTAM Decoding',
      'Tech Log Reading',
      'Maintenance Records',
      'Documents Quiz',
      'AD/SB Reading',
      'Logbook Entries',
      'Audit Reports',
      'Documents Pro Final',
    ],
  },
  {
    number: 11,
    title: 'International Standards',
    description: 'ICAO, EASA, FAA standartları',
    badge: '🌐',
    rewardXp: 7000,
    unitTitles: [
      'ICAO Annexes Overview',
      'EASA Regulations',
      'FAA Regulations',
      'Country Variations',
      'SARPs Differences',
      'Standards Quiz',
      'Type Certification',
      'Operations Spec',
      'Compliance Reporting',
      'Standards Pro Final',
    ],
  },
  {
    number: 12,
    title: 'Aviation Law Basics',
    description: 'Hukuk ve düzenleyici çerçeve',
    badge: '⚖️',
    rewardXp: 8000,
    unitTitles: [
      'Chicago Convention',
      'Tokyo Convention',
      'Montreal Convention',
      'Liability Concepts',
      'Insurance Basics',
      'Law Quiz',
      'Passenger Rights (EU261)',
      'Privacy & Data',
      'Cyber Security Law',
      'Aviation Law Pro Final',
    ],
  },
  {
    number: 13,
    title: 'Sustainability & Future',
    description: 'SAF, elektrikli uçak, otonom',
    badge: '🌱',
    rewardXp: 9000,
    unitTitles: [
      'CORSIA Carbon Offset',
      'SAF Production',
      'Electric Aircraft',
      'eVTOL & UAM',
      'Autonomous Systems',
      'Sustainability Quiz',
      'Net Zero 2050',
      'Hydrogen Aviation',
      'Recycling Aircraft',
      'Future Pro Final',
    ],
  },
  {
    number: 14,
    title: 'Advanced Career Planning',
    description: 'Stratejik kariyer yönetimi',
    badge: '🎯',
    rewardXp: 10000,
    unitTitles: [
      'Career Strategy',
      'International Mobility',
      'Personal Branding',
      'Industry Conferences',
      'Thought Leadership',
      'Career Quiz',
      'Salary Negotiation Advanced',
      'Side Projects',
      'Aviation Influencer',
      'B1 Graduate Final',
    ],
  },
  // ===== FAZ 4 (B2 Professional / ICAO 4) — Modul 15-19 =====
  {
    number: 15,
    title: 'ICAO 4 Sertifika Hazırlık',
    description: 'B2 sınavına yönelik kapsamlı hazırlık',
    badge: '🏅',
    rewardXp: 12000,
    unitTitles: [
      'Sınav Format Detayı',
      'Picture Description Practice',
      'Story Telling Practice',
      'Problem Solving Practice',
      'Common Topics Practice',
      'ICAO 4 Quiz',
      'Pronunciation Mastery',
      'Fluency Drill',
      'Comprehension Master',
      'ICAO 4 Master Final',
    ],
  },
  {
    number: 16,
    title: 'Advanced Aviation Concepts',
    description: 'İleri havacılık kavramları',
    badge: '🎓',
    rewardXp: 14000,
    unitTitles: [
      'Performance Engineering',
      'Avionics Systems Deep',
      'Air Traffic Management',
      'Airport Engineering',
      'Aerodynamics Advanced',
      'Concepts Quiz',
      'Composite Tech',
      'Propulsion Future',
      'Cybersecurity Aviation',
      'Concepts Master Final',
    ],
  },
  {
    number: 17,
    title: 'Industry Specialization',
    description: 'Sektör uzmanlaşma yolları',
    badge: '🎯',
    rewardXp: 16000,
    unitTitles: [
      'Cargo Specialization',
      'Helicopter Operations',
      'Business Aviation',
      'Drone Operations',
      'Aviation Insurance',
      'Specialization Quiz',
      'Aviation Law Career',
      'Aviation Finance',
      'Aviation Marketing',
      'Specialization Master Final',
    ],
  },
  {
    number: 18,
    title: 'International Career Path',
    description: 'Uluslararası kariyer planlama',
    badge: '🌐',
    rewardXp: 18000,
    unitTitles: [
      'Country Selection',
      'Visa & Work Permits',
      'License Conversion',
      'Cultural Adaptation',
      'Global Mobility',
      'International Quiz',
      'Tax Implications',
      'Family Considerations',
      'Networking Abroad',
      'International Master Final',
    ],
  },
  {
    number: 19,
    title: 'Aviation Leadership',
    description: 'Liderlik becerileri',
    badge: '👑',
    rewardXp: 20000,
    unitTitles: [
      'Leadership Foundations',
      'Strategic Thinking',
      'Decision Making',
      'Communication Mastery',
      'Change Management',
      'Leadership Quiz',
      'Mentor & Be Mentored',
      'Cross-cultural Leadership',
      'Future of Leadership',
      'B2 Graduate Final',
    ],
  },
  {
    number: 20,
    title: 'Aviation Research & Academia',
    description: 'Akademik araştırma yolu',
    badge: '🔬',
    rewardXp: 22000,
    unitTitles: [
      'Research Methods',
      'Literature Review',
      'Conference Paper',
      'Peer Review',
      'PhD Application',
      'Academia Quiz',
      'Grant Writing',
      'Lab Collaboration',
      'Teaching Assistant',
      'Researcher Final',
    ],
  },
  {
    number: 21,
    title: 'Aviation Innovation',
    description: 'İnovasyon ve start-up dünyası',
    badge: '💡',
    rewardXp: 22000,
    unitTitles: [
      'eVTOL Industry',
      'UAM Urban Air',
      'Hydrogen Aviation',
      'Sustainable Fuels SAF',
      'Space Tourism',
      'Innovation Quiz',
      'Aerospace Startup',
      'Patent Process',
      'VC Pitch',
      'Innovator Final',
    ],
  },
  {
    number: 22,
    title: 'Aviation Entrepreneurship',
    description: 'Havacılık girişimciliği',
    badge: '🚀',
    rewardXp: 22000,
    unitTitles: [
      'Business Plan Aviation',
      'Funding Sources',
      'Aviation MBA',
      'Lean Startup Aero',
      'Market Validation',
      'Entre Quiz',
      'Co-founder Pitch',
      'Investor Deck',
      'Scaling Aviation Biz',
      'Founder Final',
    ],
  },
  {
    number: 23,
    title: 'Global Aviation Policy',
    description: 'Uluslararası politika ve yönetişim',
    badge: '🌐',
    rewardXp: 22000,
    unitTitles: [
      'ICAO Governance',
      'Bilateral Treaties',
      'Open Skies',
      'Carbon Schemes CORSIA',
      'Aviation Diplomacy',
      'Policy Quiz',
      'Sanctions Impact',
      'Geopolitics Aviation',
      'Industry Lobbying',
      'Policy Master',
    ],
  },
  {
    number: 24,
    title: 'Master Track & C1 Grad',
    description: 'Yüksek lisans / Doktora + C1',
    badge: '🎓',
    rewardXp: 30000,
    unitTitles: [
      'Masters Application',
      'Thesis Proposal',
      'Specialization Track',
      'Industry-Academia Bridge',
      'Lifelong Learning C1',
      'Master Quiz',
      'C1 Diagnostic',
      'C1 Academic Talk',
      'C1 Polish',
      'C1 Scholar Graduate',
    ],
  },
];

function buildModule(template: ModuleTemplate, rolePrefix: string): ModuleNode {
  const moduleId = `${rolePrefix}_m${template.number}`;
  const units: UnitNode[] = template.unitTitles.map((title, idx) => {
    const unitNum = (template.number - 1) * 10 + idx + 1;
    const unitId = `${moduleId}_u${idx + 1}`;
    const isCheckpoint = idx === 5; // 6th unit
    const isFinal = idx === 9; // 10th unit
    const allPremium = idx >= 5; // After unit 6 = premium gate

    const lessons: LessonNode[] = Array.from({ length: 5 }, (_, lIdx) => ({
      id: `${unitId}_l${lIdx + 1}`,
      title: lessonTitleForIdx(title, lIdx, isCheckpoint, isFinal),
      type: lessonTypeForIdx(lIdx, isCheckpoint, isFinal),
      xp: lessonXpForIdx(lIdx, isCheckpoint, isFinal),
      estimatedMinutes: 5 + lIdx,
      isPremium: allPremium,
    }));

    return {
      id: unitId,
      number: unitNum,
      title,
      description: `${template.title} — ${title}`,
      lessons,
      badge: isFinal ? '🏆' : isCheckpoint ? '🎯' : undefined,
    };
  });

  return {
    id: moduleId,
    number: template.number,
    title: template.title,
    description: template.description,
    units,
    badge: template.badge,
    rewardXp: template.rewardXp,
  };
}

function lessonTitleForIdx(unitTitle: string, idx: number, isCheckpoint: boolean, isFinal: boolean): string {
  if (isCheckpoint) {
    const titles = ['Recap Pt 1', 'Recap Pt 2', 'Recap Pt 3', 'Recap Pt 4', 'Big Quiz'];
    return titles[idx] ?? `Lesson ${idx + 1}`;
  }
  if (isFinal) {
    const titles = ['All Recap', 'Voice Roleplay', 'Story Comprehension', 'Pronunciation Master', 'Final Test'];
    return titles[idx] ?? `Lesson ${idx + 1}`;
  }
  return `${unitTitle} ${idx + 1}`;
}

function lessonTypeForIdx(idx: number, isCheckpoint: boolean, isFinal: boolean): LessonNode['type'] {
  if (isCheckpoint || isFinal) return idx === 4 ? 'quiz' : idx === 1 ? 'dialogue' : 'vocabulary';
  if (idx === 4) return 'quiz';
  if (idx === 3) return 'dialogue';
  return 'vocabulary';
}

function lessonXpForIdx(idx: number, isCheckpoint: boolean, isFinal: boolean): number {
  if (isFinal && idx === 4) return 500; // Faz 1 final test
  if (isFinal) return 200;
  if (isCheckpoint) return idx === 4 ? 200 : 100;
  if (idx === 4) return 100; // Quiz
  if (idx === 3) return 60; // Dialog
  return 50; // Standard vocab
}

function buildModulesForRole(templates: ModuleTemplate[], rolePrefix: string): ModuleNode[] {
  return templates.map((t) => buildModule(t, rolePrefix));
}

export const PILOT_MODULES_FAZ1 = buildModulesForRole(PILOT_MODULES, 'pilot');
export const CABIN_MODULES_FAZ1 = buildModulesForRole(CABIN_MODULES, 'cabin');
export const TECHNICIAN_MODULES_FAZ1 = buildModulesForRole(TECHNICIAN_MODULES, 'technician');
export const GROUND_MODULES_FAZ1 = buildModulesForRole(GROUND_MODULES, 'ground');
export const STUDENT_MODULES_FAZ1 = buildModulesForRole(STUDENT_MODULES, 'student');

export function getModulesForRole(role: UserRole | null | undefined): ModuleNode[] {
  switch (role) {
    case 'cabin':
      return CABIN_MODULES_FAZ1;
    case 'technician':
      return TECHNICIAN_MODULES_FAZ1;
    case 'ground':
      return GROUND_MODULES_FAZ1;
    case 'student':
      return STUDENT_MODULES_FAZ1;
    case 'pilot':
    default:
      return PILOT_MODULES_FAZ1;
  }
}

// Backwards compatibility — eski ekranlar PILOT_MODULE_1 expect ediyor
export const PILOT_MODULE_1 = PILOT_MODULES_FAZ1[0]!;

export function isUnitUnlocked(
  module: ModuleNode,
  unitIndex: number,
  completedLessons: Set<string>,
): boolean {
  if (unitIndex === 0) return true;
  const previousUnit = module.units[unitIndex - 1];
  if (!previousUnit) return true;
  return previousUnit.lessons.every((l) => completedLessons.has(l.id));
}

export function getUnitProgress(
  unit: UnitNode,
  completedLessons: Set<string>,
): { completed: number; total: number; percent: number } {
  const total = unit.lessons.length;
  const completed = unit.lessons.filter((l) => completedLessons.has(l.id)).length;
  return {
    completed,
    total,
    percent: total === 0 ? 0 : Math.round((completed / total) * 100),
  };
}

export function isModuleUnlocked(
  modules: ModuleNode[],
  moduleIdx: number,
  completedLessons: Set<string>,
): boolean {
  if (moduleIdx === 0) return true;
  const previous = modules[moduleIdx - 1];
  if (!previous) return true;
  // Önceki modülün ilk 5 ünitesi tamam mı? (premium dışı)
  return previous.units.slice(0, 5).every((u) =>
    u.lessons.every((l) => completedLessons.has(l.id)),
  );
}

/**
 * "Kaldığın yerden devam et" — ilk açık ve tamamlanmamış dersi bul.
 * Premium gating varsa onu atlamaz; sadece kullanıcının erişebildiği derslerden seçer.
 *
 * @returns Ders bilgisi + bağlam (modül/ünite); hiç açık ders yoksa null
 */
export interface NextLessonInfo {
  lesson: LessonNode;
  unit: UnitNode;
  module: ModuleNode;
  moduleIdx: number;
  unitIdx: number;
  lessonIdx: number;
  isFirstEver: boolean; // hiç ders yapılmadı mı
}

export function getNextLesson(
  role: UserRole | null | undefined,
  completedLessons: Set<string>,
  isPremium = false,
): NextLessonInfo | null {
  const modules = getModulesForRole(role);
  const isFirstEver = completedLessons.size === 0;

  for (let mIdx = 0; mIdx < modules.length; mIdx++) {
    if (!isModuleUnlocked(modules, mIdx, completedLessons)) continue;
    const module = modules[mIdx]!;

    for (let uIdx = 0; uIdx < module.units.length; uIdx++) {
      if (!isUnitUnlocked(module, uIdx, completedLessons)) continue;
      const unit = module.units[uIdx]!;

      for (let lIdx = 0; lIdx < unit.lessons.length; lIdx++) {
        const lesson = unit.lessons[lIdx]!;
        if (completedLessons.has(lesson.id)) continue;
        // Premium dersi free kullanıcıya gösterme — paywall yerine bir sonrakine geç
        if (lesson.isPremium && !isPremium) continue;
        return { lesson, unit, module, moduleIdx: mIdx, unitIdx: uIdx, lessonIdx: lIdx, isFirstEver };
      }
    }
  }

  return null; // tüm açık içerik tamamlandı
}

/**
 * Toplam ilerleme yüzdesi (rol bazlı, premium dahil).
 */
export function getOverallProgress(
  role: UserRole | null | undefined,
  completedLessons: Set<string>,
): { completed: number; total: number; percent: number } {
  const modules = getModulesForRole(role);
  let completed = 0;
  let total = 0;
  for (const m of modules) {
    for (const u of m.units) {
      for (const l of u.lessons) {
        total++;
        if (completedLessons.has(l.id)) completed++;
      }
    }
  }
  return { completed, total, percent: total === 0 ? 0 : Math.round((completed / total) * 100) };
}
