/**
 * Pilot vocabulary seed — Faz 1.
 * 60 terim: kokpit, navigasyon, hava, acil, frazeoloji, aletler.
 * Sprint 9'da 300'e çıkarılacak.
 */

export interface VocabularyTerm {
  id: string;
  term: string;
  termTr: string;
  pronunciation: string;
  category: string;
  difficulty: 1 | 2 | 3 | 4 | 5;
  definitionEn: string;
  definitionTr: string;
  examples: { en: string; tr: string }[];
  icaoReference?: string;
  relatedTerms: string[];
}

export const PILOT_VOCAB_FAZ1: VocabularyTerm[] = [
  // ===== COCKPIT & AIRCRAFT PARTS (15) =====
  { id: 'voc_pilot_001', term: 'cockpit', termTr: 'kokpit', pronunciation: '/ˈkɒk.pɪt/', category: 'cockpit', difficulty: 1,
    definitionEn: 'The compartment of an aircraft where the pilot and co-pilot sit and operate the controls.',
    definitionTr: 'Pilotun ve yardımcı pilotun oturduğu, kontrolleri kullandığı uçak bölmesi.',
    examples: [
      { en: 'The captain entered the cockpit before the flight.', tr: 'Kaptan uçuştan önce kokpite girdi.' },
      { en: 'Cockpit voice recorders capture all conversations.', tr: 'Kokpit ses kayıt cihazları tüm konuşmaları kaydeder.' },
    ],
    icaoReference: 'ICAO Annex 6, Part I',
    relatedTerms: ['flight deck', 'captain', 'first officer'],
  },
  { id: 'voc_pilot_002', term: 'fuselage', termTr: 'gövde', pronunciation: '/ˈfjuː.zəˌlɑːʒ/', category: 'aircraft_parts', difficulty: 2,
    definitionEn: 'The main body of an aircraft that holds passengers, crew, and cargo.',
    definitionTr: 'Yolcu, ekip ve yükü taşıyan uçağın ana gövdesi.',
    examples: [
      { en: 'The fuselage is made of aluminum alloy.', tr: 'Gövde alüminyum alaşımdan yapılmıştır.' },
      { en: 'A crack on the fuselage was repaired.', tr: 'Gövdedeki çatlak onarıldı.' },
    ],
    relatedTerms: ['airframe', 'skin', 'frame'],
  },
  { id: 'voc_pilot_003', term: 'wing', termTr: 'kanat', pronunciation: '/wɪŋ/', category: 'aircraft_parts', difficulty: 1,
    definitionEn: 'The horizontal surfaces extending from the fuselage that generate lift.',
    definitionTr: 'Gövdeden yana uzanan, kaldırma kuvveti üreten yatay yüzeyler.',
    examples: [
      { en: 'The wings have flaps and ailerons.', tr: 'Kanatlarda flap ve eleron vardır.' },
      { en: 'Anti-ice systems protect the wings.', tr: 'Anti-ice sistemleri kanatları korur.' },
    ],
    relatedTerms: ['flap', 'aileron', 'winglet'],
  },
  { id: 'voc_pilot_004', term: 'tail', termTr: 'kuyruk', pronunciation: '/teɪl/', category: 'aircraft_parts', difficulty: 1,
    definitionEn: 'The rear part of an aircraft, including vertical and horizontal stabilizers.',
    definitionTr: 'Uçağın arka kısmı; dikey ve yatay stabilizörleri içerir.',
    examples: [
      { en: 'The tail provides directional stability.', tr: 'Kuyruk yön stabilitesi sağlar.' },
      { en: 'A tail strike occurred during landing.', tr: 'İniş sırasında tail strike yaşandı.' },
    ],
    relatedTerms: ['empennage', 'rudder', 'elevator'],
  },
  { id: 'voc_pilot_005', term: 'engine', termTr: 'motor', pronunciation: '/ˈen.dʒɪn/', category: 'aircraft_parts', difficulty: 1,
    definitionEn: 'A device that produces thrust to propel the aircraft.',
    definitionTr: 'Uçağı ileri itmek için itki üreten cihaz.',
    examples: [
      { en: 'The aircraft has two jet engines.', tr: 'Uçakta iki jet motoru var.' },
      { en: 'Engine N1 indicates fan speed.', tr: 'Motor N1 fan hızını gösterir.' },
    ],
    relatedTerms: ['jet', 'turboprop', 'thrust'],
  },
  { id: 'voc_pilot_006', term: 'flap', termTr: 'flap', pronunciation: '/flæp/', category: 'aircraft_parts', difficulty: 2,
    definitionEn: 'A movable surface on the wing trailing edge that increases lift during takeoff and landing.',
    definitionTr: 'Kanat arka kenarındaki, kalkış ve inişte kaldırma kuvvetini artıran hareketli yüzey.',
    examples: [
      { en: 'Set flaps to position 15 for takeoff.', tr: 'Kalkış için flap\'ları pozisyon 15\'e al.' },
      { en: 'Retract flaps after takeoff.', tr: 'Kalkış sonrası flap\'ları topla.' },
    ],
    relatedTerms: ['slat', 'aileron', 'leading edge'],
  },
  { id: 'voc_pilot_007', term: 'aileron', termTr: 'eleron', pronunciation: '/ˈeɪ.lə.rɒn/', category: 'aircraft_parts', difficulty: 2,
    definitionEn: 'A movable wing surface that controls roll (banking left or right).',
    definitionTr: 'Yatış kontrolünü (sağa-sola yatma) sağlayan hareketli kanat yüzeyi.',
    examples: [
      { en: 'Right aileron up, left aileron down for right bank.', tr: 'Sağa yatış için sağ eleron yukarı, sol aşağı.' },
      { en: 'Ailerons connect via cables and rods.', tr: 'Eleronlar kablolar ve çubuklarla bağlıdır.' },
    ],
    relatedTerms: ['flap', 'spoiler', 'roll'],
  },
  { id: 'voc_pilot_008', term: 'rudder', termTr: 'dümen', pronunciation: '/ˈrʌd.ər/', category: 'aircraft_parts', difficulty: 2,
    definitionEn: 'A movable vertical surface on the tail that controls yaw (nose left or right).',
    definitionTr: 'Burun yön kontrolünü (sağa-sola dönüş) sağlayan dikey kuyruk yüzeyi.',
    examples: [
      { en: 'Use rudder for crosswind landings.', tr: 'Yan rüzgar inişlerinde dümen kullan.' },
      { en: 'Rudder pedals control the rudder.', tr: 'Dümen pedalları dümeni kontrol eder.' },
    ],
    relatedTerms: ['yaw', 'vertical stabilizer', 'pedal'],
  },
  { id: 'voc_pilot_009', term: 'elevator', termTr: 'irtifa kontrol', pronunciation: '/ˈel.ɪˌveɪ.tər/', category: 'aircraft_parts', difficulty: 2,
    definitionEn: 'A movable horizontal surface on the tail that controls pitch (nose up or down).',
    definitionTr: 'Burun yukarı-aşağı hareketini kontrol eden yatay kuyruk yüzeyi.',
    examples: [
      { en: 'Pull yoke aft: elevator up, nose up.', tr: 'Yoke geri: elevator yukarı, burun yukarı.' },
      { en: 'Elevator trim reduces pilot effort.', tr: 'Elevator trim pilot eforunu azaltır.' },
    ],
    relatedTerms: ['pitch', 'horizontal stabilizer', 'trim'],
  },
  { id: 'voc_pilot_010', term: 'landing gear', termTr: 'iniş takımı', pronunciation: '/ˈlæn.dɪŋ ɡɪər/', category: 'aircraft_parts', difficulty: 1,
    definitionEn: 'The wheels and supporting structure used for takeoff, landing, and ground operations.',
    definitionTr: 'Kalkış, iniş ve yer operasyonları için kullanılan tekerlekler ve destek yapısı.',
    examples: [
      { en: 'Landing gear up after takeoff.', tr: 'Kalkıştan sonra iniş takımı toplandı.' },
      { en: 'Three greens: gear is down and locked.', tr: 'Üç yeşil: takım inik ve kilitli.' },
    ],
    relatedTerms: ['nose gear', 'main gear', 'tire', 'brake'],
  },
  { id: 'voc_pilot_011', term: 'throttle', termTr: 'gaz kolu', pronunciation: '/ˈθrɒt.əl/', category: 'cockpit', difficulty: 2,
    definitionEn: 'A lever that controls engine power output.',
    definitionTr: 'Motor güç çıkışını kontrol eden kol.',
    examples: [
      { en: 'Push the throttle forward to increase thrust.', tr: 'İtki için gaz kolunu ileri it.' },
      { en: 'Throttle idle for descent.', tr: 'Alçalma için gaz kolu rölantide.' },
    ],
    relatedTerms: ['power lever', 'thrust', 'idle'],
  },
  { id: 'voc_pilot_012', term: 'yoke', termTr: 'yoke (direksiyon)', pronunciation: '/jəʊk/', category: 'cockpit', difficulty: 2,
    definitionEn: 'The control wheel used to maneuver the aircraft via ailerons and elevators.',
    definitionTr: 'Eleron ve elevator ile uçağı manevra ettirmek için kullanılan kontrol direksiyonu.',
    examples: [
      { en: 'Yoke left: roll left.', tr: 'Yoke sola: sola yatış.' },
      { en: 'Captain\'s yoke vibrates during stick shaker.', tr: 'Stick shaker\'da kaptan yoke\'u titrer.' },
    ],
    relatedTerms: ['control column', 'sidestick', 'rudder pedal'],
  },
  { id: 'voc_pilot_013', term: 'altimeter', termTr: 'altimetre', pronunciation: '/ælˈtɪm.ə.tər/', category: 'instruments', difficulty: 2,
    definitionEn: 'An instrument that displays the aircraft\'s altitude above a reference point.',
    definitionTr: 'Uçağın bir referans noktasının üzerindeki irtifasını gösteren alet.',
    examples: [
      { en: 'Set the altimeter to QNH 1015.', tr: 'Altimetreyi QNH 1015\'e ayarla.' },
      { en: 'Altimeter reads 5,000 feet.', tr: 'Altimetre 5.000 feet gösteriyor.' },
    ],
    icaoReference: 'ICAO Annex 6',
    relatedTerms: ['altitude', 'flight level', 'QNH'],
  },
  { id: 'voc_pilot_014', term: 'transponder', termTr: 'transponder', pronunciation: '/trænˈspɒn.dər/', category: 'instruments', difficulty: 3,
    definitionEn: 'A radio device that transmits the aircraft\'s identification and altitude to ATC radar.',
    definitionTr: 'Uçağın kimliğini ve irtifasını ATC radarına ileten radyo cihazı.',
    examples: [
      { en: 'Squawk transponder code 1234.', tr: 'Transponder kodu 1234\'e ayarla.' },
      { en: 'Mode C transponder reports altitude.', tr: 'Mode C transponder irtifa bildirir.' },
    ],
    relatedTerms: ['squawk', 'radar', 'mode C', 'ADS-B'],
  },
  { id: 'voc_pilot_015', term: 'autopilot', termTr: 'otopilot', pronunciation: '/ˈɔː.təʊˌpaɪ.lət/', category: 'cockpit', difficulty: 2,
    definitionEn: 'An automated system that controls the aircraft without manual pilot input.',
    definitionTr: 'Manuel pilot müdahalesi olmadan uçağı kontrol eden otomatik sistem.',
    examples: [
      { en: 'Engaging autopilot at 1,000 feet.', tr: '1.000 feette otopilot devrede.' },
      { en: 'Autopilot disengage warning sounds.', tr: 'Otopilot devre dışı uyarısı çalar.' },
    ],
    relatedTerms: ['flight director', 'FMS', 'autoland'],
  },

  // ===== ATC PHRASEOLOGY (12) =====
  { id: 'voc_pilot_016', term: 'cleared for takeoff', termTr: 'kalkış izni verildi', pronunciation: '/klɪərd fɔːr ˈteɪk.ɒf/', category: 'phraseology', difficulty: 2,
    definitionEn: 'ATC authorization for an aircraft to begin its takeoff roll.',
    definitionTr: 'Bir uçağın kalkış koşusuna başlaması için ATC izni.',
    examples: [
      { en: 'Tower: "Turkish 1234, runway 27, cleared for takeoff."', tr: 'Kule: "Turkish 1234, pist 27, kalkış izni."' },
      { en: 'Read back: "Cleared for takeoff runway 27, Turkish 1234."', tr: 'Read back: "Kalkış izni pist 27, Turkish 1234."' },
    ],
    icaoReference: 'ICAO Doc 9432',
    relatedTerms: ['takeoff', 'departure', 'hold short'],
  },
  { id: 'voc_pilot_017', term: 'cleared to land', termTr: 'iniş izni verildi', pronunciation: '/klɪərd tə lænd/', category: 'phraseology', difficulty: 2,
    definitionEn: 'ATC authorization for an aircraft to land on a specified runway.',
    definitionTr: 'Belirtilen piste iniş için ATC izni.',
    examples: [
      { en: 'Tower: "Turkish 1234, runway 27, cleared to land. Wind 270 at 15."', tr: 'Kule: "Turkish 1234, pist 27, iniş izni. Rüzgar 270, 15."' },
      { en: 'Always read back the runway in landing clearance.', tr: 'İniş izninde mutlaka pisti tekrarla.' },
    ],
    icaoReference: 'ICAO Doc 9432',
    relatedTerms: ['final approach', 'go-around', 'wind check'],
  },
  { id: 'voc_pilot_018', term: 'taxi', termTr: 'taksi (yer hareketi)', pronunciation: '/ˈtæk.si/', category: 'phraseology', difficulty: 1,
    definitionEn: 'Movement of an aircraft on the ground under its own power.',
    definitionTr: 'Bir uçağın yerde kendi gücüyle hareket etmesi.',
    examples: [
      { en: 'Tower: "Taxi to runway 27 via Alpha."', tr: 'Kule: "Alpha üzerinden pist 27\'ye taksi."' },
      { en: 'Maintain taxi speed below 30 knots.', tr: 'Taksi hızını 30 knot altında tut.' },
    ],
    icaoReference: 'ICAO Doc 9432',
    relatedTerms: ['taxiway', 'pushback', 'ground control'],
  },
  { id: 'voc_pilot_019', term: 'pushback', termTr: 'geri itme', pronunciation: '/ˈpʊʃ.bæk/', category: 'phraseology', difficulty: 2,
    definitionEn: 'Procedure of pushing the aircraft backwards from the gate using a tug.',
    definitionTr: 'Uçağın gate\'ten tug kullanılarak geri itilmesi prosedürü.',
    examples: [
      { en: 'Pilot: "Request push and start, gate A14."', tr: 'Pilot: "Push ve start talep, gate A14."' },
      { en: 'Push approved, face north.', tr: 'Push onaylı, kuzeye dön.' },
    ],
    relatedTerms: ['tug', 'gate', 'ground crew'],
  },
  { id: 'voc_pilot_020', term: 'roger', termTr: 'roger (anlaşıldı)', pronunciation: '/ˈrɒdʒ.ər/', category: 'phraseology', difficulty: 1,
    definitionEn: 'Standard ATC term meaning "I have received your last transmission."',
    definitionTr: '"Son iletini aldım" anlamına gelen standart ATC terimi.',
    examples: [
      { en: 'ATC: "Climb to FL250." Pilot: "Roger."', tr: 'ATC: "FL250\'ye tırman." Pilot: "Roger."' },
      { en: 'Roger ≠ "I will comply" (= wilco).', tr: 'Roger "uygulayacağım" değil (= wilco).' },
    ],
    icaoReference: 'ICAO Doc 9432',
    relatedTerms: ['wilco', 'affirmative', 'standby'],
  },
  { id: 'voc_pilot_021', term: 'wilco', termTr: 'wilco (uygulayacağım)', pronunciation: '/ˈwɪl.koʊ/', category: 'phraseology', difficulty: 2,
    definitionEn: '"Will Comply" — pilot acknowledgment that an instruction will be followed.',
    definitionTr: '"Will Comply" — pilotun talimatı uygulayacağını bildiren cevabı.',
    examples: [
      { en: 'ATC: "Reduce speed to 250." Pilot: "Wilco."', tr: 'ATC: "Hızı 250\'ye düşür." Pilot: "Wilco."' },
      { en: 'Wilco = anlayış + uygulama.', tr: 'Wilco = anlayış + uygulama.' },
    ],
    icaoReference: 'ICAO Doc 9432',
    relatedTerms: ['roger', 'affirmative', 'unable'],
  },
  { id: 'voc_pilot_022', term: 'standby', termTr: 'standby (bekle)', pronunciation: '/ˈstænd.baɪ/', category: 'phraseology', difficulty: 1,
    definitionEn: '"Wait" — used to instruct the other party to hold their request briefly.',
    definitionTr: '"Bekle" — karşı tarafın talebini kısa süre tutmasını istemek.',
    examples: [
      { en: 'ATC: "Standby, traffic on final."', tr: 'ATC: "Standby, finalde trafik var."' },
      { en: 'Standby is not approval; it\'s a delay.', tr: 'Standby onay değil; gecikmedir.' },
    ],
    icaoReference: 'ICAO Doc 9432',
    relatedTerms: ['hold', 'wait', 'disregard'],
  },
  { id: 'voc_pilot_023', term: 'unable', termTr: 'unable (yapamam)', pronunciation: '/ʌnˈeɪ.bəl/', category: 'phraseology', difficulty: 3,
    definitionEn: 'Pilot response indicating an instruction cannot be followed safely or operationally.',
    definitionTr: 'Bir talimatın güvenli veya operasyonel olarak uygulanamayacağını bildiren pilot cevabı.',
    examples: [
      { en: 'ATC: "Climb to FL410." Pilot: "Unable due to weight, request FL370."', tr: 'ATC: "FL410\'a tırman." Pilot: "Ağırlık nedeniyle unable, FL370 talep."' },
      { en: 'Always provide reason after "unable".', tr: '"Unable" sonrası mutlaka sebep belirt.' },
    ],
    icaoReference: 'ICAO Doc 9432',
    relatedTerms: ['negative', 'request', 'alternate'],
  },
  { id: 'voc_pilot_024', term: 'say again', termTr: 'tekrar et', pronunciation: '/seɪ əˈɡen/', category: 'phraseology', difficulty: 1,
    definitionEn: 'Standard ICAO phraseology to request a repetition of the last transmission.',
    definitionTr: 'Son iletinin tekrarını istemek için standart ICAO frazeolojisi.',
    examples: [
      { en: 'Pilot: "Say again last message."', tr: 'Pilot: "Son mesajı tekrar et."' },
      { en: 'Don\'t use "repeat" — that\'s artillery jargon!', tr: '"Repeat" kullanma — o topçu jargonu!' },
    ],
    icaoReference: 'ICAO Doc 9432',
    relatedTerms: ['confirm', 'verify', 'how do you read'],
  },
  { id: 'voc_pilot_025', term: 'hold short', termTr: 'kısa bekle', pronunciation: '/həʊld ʃɔːt/', category: 'phraseology', difficulty: 2,
    definitionEn: 'Instruction to stop before crossing or entering a runway.',
    definitionTr: 'Bir piste girmeden veya geçmeden önce durma talimatı.',
    examples: [
      { en: 'Tower: "Turkish 1234, hold short of runway 27."', tr: 'Kule: "Turkish 1234, pist 27\'nin önünde bekle."' },
      { en: 'Read back: "Hold short of runway 27, Turkish 1234."', tr: 'Read back: "Pist 27\'nin önünde bekle, Turkish 1234."' },
    ],
    icaoReference: 'ICAO Doc 9432',
    relatedTerms: ['line up', 'runway boundary', 'stop bar'],
  },
  { id: 'voc_pilot_026', term: 'line up and wait', termTr: 'sıralan ve bekle', pronunciation: '/laɪn ʌp ænd weɪt/', category: 'phraseology', difficulty: 2,
    definitionEn: 'Instruction to enter the runway and align for takeoff, but wait for further clearance.',
    definitionTr: 'Piste girip kalkış için sıralanma, ancak yeni izne kadar bekleme talimatı.',
    examples: [
      { en: 'Tower: "Turkish 1234, line up and wait runway 27."', tr: 'Kule: "Turkish 1234, pist 27\'ye sıralan ve bekle."' },
      { en: 'Line up and wait ≠ cleared for takeoff!', tr: 'Line up and wait kalkış izni demek değil!' },
    ],
    icaoReference: 'ICAO Doc 9432',
    relatedTerms: ['takeoff', 'hold short', 'runway'],
  },
  { id: 'voc_pilot_027', term: 'go-around', termTr: 'pas geç (go-around)', pronunciation: '/ˈɡəʊ.əˌraʊnd/', category: 'phraseology', difficulty: 3,
    definitionEn: 'Aborted landing, climbing back to pattern altitude for another approach.',
    definitionTr: 'İptal edilen iniş, başka bir yaklaşma için pattern irtifasına yeniden tırmanma.',
    examples: [
      { en: 'Pilot: "Going around, Turkish 1234."', tr: 'Pilot: "Going around, Turkish 1234."' },
      { en: 'Tower: "Go-around approved, climb to 3,000."', tr: 'Kule: "Go-around onaylı, 3.000\'e tırman."' },
    ],
    icaoReference: 'ICAO Doc 9432',
    relatedTerms: ['missed approach', 'pattern', 'final'],
  },

  // ===== NAVIGATION (10) =====
  { id: 'voc_pilot_028', term: 'altitude', termTr: 'irtifa', pronunciation: '/ˈæl.tɪ.tjuːd/', category: 'navigation', difficulty: 2,
    definitionEn: 'The vertical distance of an aircraft above a reference (sea level).',
    definitionTr: 'Bir uçağın referansa (deniz seviyesi) göre dikey mesafesi.',
    examples: [
      { en: 'Cruise altitude is FL350.', tr: 'Seyir irtifası FL350.' },
      { en: 'Maintain altitude 5,000 feet.', tr: '5.000 feet irtifayı koru.' },
    ],
    relatedTerms: ['flight level', 'altimeter', 'climb'],
  },
  { id: 'voc_pilot_029', term: 'flight level', termTr: 'uçuş seviyesi', pronunciation: '/flaɪt ˈlev.əl/', category: 'navigation', difficulty: 2,
    definitionEn: 'A standard pressure altitude above the transition altitude (e.g. FL350 = 35,000 ft).',
    definitionTr: 'Geçiş irtifasının üzerindeki standart basınç irtifası (FL350 = 35.000 ft).',
    examples: [
      { en: 'Climb and maintain flight level three five zero.', tr: 'FL350\'ye tırman ve koru.' },
      { en: 'Below transition altitude, use feet.', tr: 'Geçiş irtifasının altında feet kullan.' },
    ],
    icaoReference: 'ICAO Annex 2',
    relatedTerms: ['altitude', 'transition altitude', 'QNE'],
  },
  { id: 'voc_pilot_030', term: 'heading', termTr: 'rota başı', pronunciation: '/ˈhed.ɪŋ/', category: 'navigation', difficulty: 2,
    definitionEn: 'The direction the aircraft\'s nose is pointing, in degrees (0-360).',
    definitionTr: 'Uçağın burnunun gösterdiği yön, derece olarak (0-360).',
    examples: [
      { en: 'Fly heading two seven zero.', tr: 'Heading 270\'i tut.' },
      { en: 'Turn right heading 360.', tr: 'Sağa dön heading 360.' },
    ],
    relatedTerms: ['course', 'track', 'bearing'],
  },
  { id: 'voc_pilot_031', term: 'waypoint', termTr: 'yol noktası', pronunciation: '/ˈweɪ.pɔɪnt/', category: 'navigation', difficulty: 2,
    definitionEn: 'A specific geographic point used in navigation, defined by coordinates.',
    definitionTr: 'Navigasyonda kullanılan, koordinatlarla tanımlı belirli coğrafi nokta.',
    examples: [
      { en: 'Direct to waypoint ABCDE.', tr: 'ABCDE waypoint\'ine direkt.' },
      { en: 'Passing waypoint, estimating next at 12:30Z.', tr: 'Waypoint\'i geçtim, sonraki tahmini 12:30Z.' },
    ],
    relatedTerms: ['fix', 'intersection', 'navaid'],
  },
  { id: 'voc_pilot_032', term: 'VOR', termTr: 'VOR (radyo seyrüsefer)', pronunciation: '/ˌviː əʊ ˈɑːr/', category: 'navigation', difficulty: 3,
    definitionEn: 'VHF Omnidirectional Range — ground-based radio navigation system.',
    definitionTr: 'VHF Omnidirectional Range — yer tabanlı radyo navigasyon sistemi.',
    examples: [
      { en: 'Tune VOR to 113.5.', tr: 'VOR\'u 113.5\'e ayarla.' },
      { en: 'VOR/DME provides bearing and distance.', tr: 'VOR/DME yön ve mesafe verir.' },
    ],
    relatedTerms: ['DME', 'NDB', 'RNAV'],
  },
  { id: 'voc_pilot_033', term: 'ILS', termTr: 'ILS (alet iniş sistemi)', pronunciation: '/ˌaɪ el ˈes/', category: 'navigation', difficulty: 3,
    definitionEn: 'Instrument Landing System — provides precision approach guidance.',
    definitionTr: 'Instrument Landing System — hassas yaklaşma kılavuzluğu sağlar.',
    examples: [
      { en: 'Cleared ILS approach runway 27.', tr: 'ILS yaklaşma izni pist 27.' },
      { en: 'Established on the ILS.', tr: 'ILS\'te established.' },
    ],
    icaoReference: 'ICAO Annex 10',
    relatedTerms: ['localizer', 'glide slope', 'approach'],
  },
  { id: 'voc_pilot_034', term: 'localizer', termTr: 'localizer', pronunciation: '/ˈloʊ.kə.laɪ.zər/', category: 'navigation', difficulty: 3,
    definitionEn: 'The horizontal guidance component of an ILS.',
    definitionTr: 'ILS\'in yatay kılavuzluk bileşeni.',
    examples: [
      { en: 'Intercepting localizer.', tr: 'Localizer\'ı yakalıyorum.' },
      { en: 'Localizer needle centered.', tr: 'Localizer iğnesi merkezde.' },
    ],
    relatedTerms: ['ILS', 'glide slope', 'CAT III'],
  },
  { id: 'voc_pilot_035', term: 'glide slope', termTr: 'iniş eğimi', pronunciation: '/ɡlaɪd sləʊp/', category: 'navigation', difficulty: 3,
    definitionEn: 'The vertical guidance component of an ILS, typically 3 degrees.',
    definitionTr: 'ILS\'in dikey kılavuzluk bileşeni, genelde 3 derece.',
    examples: [
      { en: 'Above glide slope.', tr: 'Glide slope üstündeyim.' },
      { en: 'Capturing glide slope.', tr: 'Glide slope yakalandı.' },
    ],
    relatedTerms: ['localizer', 'ILS', 'descent'],
  },
  { id: 'voc_pilot_036', term: 'holding pattern', termTr: 'bekleme deseni', pronunciation: '/ˈhəʊl.dɪŋ ˈpæt.ərn/', category: 'navigation', difficulty: 3,
    definitionEn: 'A racetrack-shaped pattern flown to wait for clearance or sequencing.',
    definitionTr: 'İzin veya sıralama beklemek için uçulan oval desen.',
    examples: [
      { en: 'Hold over ABCDE, expect further clearance 12:30.', tr: 'ABCDE üzerinde hold, EFC 12:30.' },
      { en: 'Standard right-hand holding pattern.', tr: 'Standart sağ-dönüşlü holding pattern.' },
    ],
    relatedTerms: ['EFC', 'fix', 'inbound leg'],
  },
  { id: 'voc_pilot_037', term: 'TCAS', termTr: 'TCAS (çakışma önleme)', pronunciation: '/ˈtiːˌkæs/', category: 'instruments', difficulty: 3,
    definitionEn: 'Traffic Collision Avoidance System — alerts pilots of potential mid-air conflicts.',
    definitionTr: 'Traffic Collision Avoidance System — havada çakışma riskini bildirir.',
    examples: [
      { en: 'TCAS RA: climb, climb!', tr: 'TCAS RA: tırman, tırman!' },
      { en: 'Follow TCAS resolution advisory immediately.', tr: 'TCAS RA\'sını derhal uygula.' },
    ],
    relatedTerms: ['traffic advisory', 'resolution advisory', 'transponder'],
  },

  // ===== WEATHER (10) =====
  { id: 'voc_pilot_038', term: 'METAR', termTr: 'METAR', pronunciation: '/ˈmiː.tɑːr/', category: 'weather', difficulty: 3,
    definitionEn: 'Meteorological Aerodrome Report — routine airport weather observation.',
    definitionTr: 'Havaalanı Meteoroloji Raporu — rutin hava gözlem raporu.',
    examples: [
      { en: 'Always check METAR before departure.', tr: 'Kalkıştan önce METAR kontrol et.' },
      { en: 'METAR LTBA 261150Z 27015KT 10SM.', tr: 'LTBA 26\'sı 11:50Z, rüzgar 270/15, görüş 10 mil.' },
    ],
    icaoReference: 'ICAO Annex 3',
    relatedTerms: ['TAF', 'ATIS', 'SIGMET'],
  },
  { id: 'voc_pilot_039', term: 'TAF', termTr: 'TAF (havaalanı tahmini)', pronunciation: '/tæf/', category: 'weather', difficulty: 3,
    definitionEn: 'Terminal Aerodrome Forecast — weather forecast for an airport area.',
    definitionTr: 'Terminal Aerodrome Forecast — havaalanı bölgesi için hava tahmini.',
    examples: [
      { en: 'TAF valid 24 hours.', tr: 'TAF 24 saat geçerli.' },
      { en: 'BECMG 1500Z: changes expected.', tr: 'BECMG 1500Z: değişim bekleniyor.' },
    ],
    icaoReference: 'ICAO Annex 3',
    relatedTerms: ['METAR', 'TEMPO', 'BECMG'],
  },
  { id: 'voc_pilot_040', term: 'turbulence', termTr: 'türbülans', pronunciation: '/ˈtɜː.bjə.ləns/', category: 'weather', difficulty: 2,
    definitionEn: 'Irregular motion of air causing the aircraft to shake.',
    definitionTr: 'Uçağın sallanmasına neden olan düzensiz hava hareketi.',
    examples: [
      { en: 'Light turbulence ahead.', tr: 'İleride hafif türbülans.' },
      { en: 'Cabin crew, take your seats — severe turbulence.', tr: 'Kabin ekibi, koltuklara — şiddetli türbülans.' },
    ],
    relatedTerms: ['light', 'moderate', 'severe', 'wind shear'],
  },
  { id: 'voc_pilot_041', term: 'wind shear', termTr: 'rüzgar makası', pronunciation: '/wɪnd ʃɪər/', category: 'weather', difficulty: 3,
    definitionEn: 'A sudden change in wind speed or direction over a short distance.',
    definitionTr: 'Kısa mesafede rüzgar hız veya yönünde ani değişim.',
    examples: [
      { en: 'Wind shear alert on final approach.', tr: 'Final yaklaşmada wind shear uyarısı.' },
      { en: 'Microburst causes severe wind shear.', tr: 'Microburst şiddetli wind shear yaratır.' },
    ],
    relatedTerms: ['microburst', 'gust', 'turbulence'],
  },
  { id: 'voc_pilot_042', term: 'icing', termTr: 'buzlanma', pronunciation: '/ˈaɪ.sɪŋ/', category: 'weather', difficulty: 2,
    definitionEn: 'Accumulation of ice on aircraft surfaces, affecting performance.',
    definitionTr: 'Uçak yüzeylerinde buz birikimi; performansı etkiler.',
    examples: [
      { en: 'Icing conditions: anti-ice on.', tr: 'Buzlanma koşulları: anti-ice açık.' },
      { en: 'Severe icing reported at FL180.', tr: 'FL180\'de şiddetli icing bildirildi.' },
    ],
    relatedTerms: ['anti-ice', 'de-ice', 'rime ice'],
  },
  { id: 'voc_pilot_043', term: 'cumulonimbus', termTr: 'kümülonimbus (CB)', pronunciation: '/ˌkjuː.mjə.ləʊˈnɪm.bəs/', category: 'weather', difficulty: 3,
    definitionEn: 'Towering thunderstorm cloud, dangerous for aircraft.',
    definitionTr: 'Uçaklar için tehlikeli yüksek fırtına bulutu.',
    examples: [
      { en: 'Avoid CB by 20 NM.', tr: 'CB\'yi 20 NM\'den geçme.' },
      { en: 'CB tops at FL450.', tr: 'CB tepeleri FL450\'de.' },
    ],
    relatedTerms: ['thunderstorm', 'lightning', 'hail'],
  },
  { id: 'voc_pilot_044', term: 'visibility', termTr: 'görüş mesafesi', pronunciation: '/ˌvɪz.əˈbɪl.ə.ti/', category: 'weather', difficulty: 2,
    definitionEn: 'The greatest distance at which objects can be clearly seen.',
    definitionTr: 'Nesnelerin net görülebildiği en büyük mesafe.',
    examples: [
      { en: 'Visibility 10 statute miles.', tr: 'Görüş 10 statute mil.' },
      { en: 'Low visibility procedures in effect.', tr: 'Düşük görüş prosedürleri devrede.' },
    ],
    relatedTerms: ['RVR', 'fog', 'minima'],
  },
  { id: 'voc_pilot_045', term: 'ceiling', termTr: 'tavan (bulut tabanı)', pronunciation: '/ˈsiː.lɪŋ/', category: 'weather', difficulty: 2,
    definitionEn: 'The height of the lowest broken or overcast cloud layer.',
    definitionTr: 'En alt broken veya overcast bulut katmanının yüksekliği.',
    examples: [
      { en: 'Ceiling 800 feet broken.', tr: 'Tavan 800 feet broken.' },
      { en: 'Ceiling and visibility OK (CAVOK).', tr: 'Tavan ve görüş OK (CAVOK).' },
    ],
    relatedTerms: ['CAVOK', 'broken', 'overcast'],
  },
  { id: 'voc_pilot_046', term: 'NOTAM', termTr: 'NOTAM (havacı uyarısı)', pronunciation: '/ˈnəʊ.tæm/', category: 'documentation', difficulty: 3,
    definitionEn: 'Notice to Airmen — time-critical aeronautical information.',
    definitionTr: 'Notice to Airmen — zamana duyarlı havacılık bildirimi.',
    examples: [
      { en: 'NOTAM: RWY 27 CLSD UFN.', tr: 'NOTAM: Pist 27 kapalı, yeni bildirime kadar.' },
      { en: 'Review NOTAMs before every flight.', tr: 'Her uçuştan önce NOTAM\'ları gözden geçir.' },
    ],
    icaoReference: 'ICAO Annex 15',
    relatedTerms: ['Q-code', 'CLSD', 'WIP'],
  },
  { id: 'voc_pilot_047', term: 'ATIS', termTr: 'ATIS (havaalanı bilgisi)', pronunciation: '/ˈeɪ.tɪs/', category: 'weather', difficulty: 2,
    definitionEn: 'Automatic Terminal Information Service — broadcast airport info.',
    definitionTr: 'Automatic Terminal Information Service — yayımlanan havaalanı bilgisi.',
    examples: [
      { en: 'Information Charlie received.', tr: 'Information Charlie alındı.' },
      { en: 'ATIS on 121.0.', tr: 'ATIS 121.0\'da.' },
    ],
    relatedTerms: ['METAR', 'D-ATIS', 'broadcast'],
  },

  // ===== EMERGENCY (8) =====
  { id: 'voc_pilot_048', term: 'mayday', termTr: 'mayday (acil)', pronunciation: '/ˈmeɪ.deɪ/', category: 'emergency', difficulty: 3,
    definitionEn: 'International distress call indicating life-threatening emergency, repeated three times.',
    definitionTr: 'Hayati tehlike içeren uluslararası acil durum çağrısı, üç kez tekrarlanır.',
    examples: [
      { en: '"Mayday, mayday, mayday, Turkish 1234, engine failure."', tr: '"Mayday, mayday, mayday, Turkish 1234, motor arızası."' },
      { en: 'Mayday claims absolute priority.', tr: 'Mayday mutlak öncelik talep eder.' },
    ],
    icaoReference: 'ICAO Annex 10',
    relatedTerms: ['pan-pan', 'emergency', 'squawk 7700'],
  },
  { id: 'voc_pilot_049', term: 'pan-pan', termTr: 'pan-pan (acil değil ama önemli)', pronunciation: '/pɑːn pɑːn/', category: 'emergency', difficulty: 3,
    definitionEn: 'Urgency call indicating a non-life-threatening but serious situation.',
    definitionTr: 'Hayati tehlike olmayan ama ciddi durum bildiren aciliyet çağrısı.',
    examples: [
      { en: '"Pan-pan, pan-pan, pan-pan, medical emergency."', tr: '"Pan-pan, pan-pan, pan-pan, tıbbi acil."' },
      { en: 'Pan-pan less critical than mayday.', tr: 'Pan-pan, mayday\'den daha az kritiktir.' },
    ],
    icaoReference: 'ICAO Annex 10',
    relatedTerms: ['mayday', 'urgency', 'priority'],
  },
  { id: 'voc_pilot_050', term: 'squawk 7700', termTr: 'squawk 7700 (acil kod)', pronunciation: '/skwɒk ˈsev.ən ˈsev.ən ˈzɪər.əʊ ˈzɪər.əʊ/', category: 'emergency', difficulty: 3,
    definitionEn: 'Transponder code indicating general aviation emergency.',
    definitionTr: 'Genel havacılık acil durumunu bildiren transponder kodu.',
    examples: [
      { en: 'Squawk seven seven zero zero.', tr: 'Squawk 7700.' },
      { en: '7600 = comm failure, 7500 = hijack.', tr: '7600 = iletişim arızası, 7500 = hijack.' },
    ],
    relatedTerms: ['transponder', 'emergency', '7600', '7500'],
  },
  { id: 'voc_pilot_051', term: 'engine failure', termTr: 'motor arızası', pronunciation: '/ˈen.dʒɪn ˈfeɪl.jər/', category: 'emergency', difficulty: 2,
    definitionEn: 'Loss of power from one or more engines during flight.',
    definitionTr: 'Uçuş sırasında bir veya daha fazla motorda güç kaybı.',
    examples: [
      { en: 'Engine 2 failure on takeoff.', tr: 'Kalkışta motor 2 arızası.' },
      { en: 'Single engine ops require careful handling.', tr: 'Tek motorlu operasyon dikkatli yönetim ister.' },
    ],
    relatedTerms: ['flame out', 'restart', 'V1 cut'],
  },
  { id: 'voc_pilot_052', term: 'emergency descent', termTr: 'acil alçalma', pronunciation: '/ɪˈmɜː.dʒən.si dɪˈsent/', category: 'emergency', difficulty: 3,
    definitionEn: 'Rapid descent due to depressurization or fire, typically to FL100.',
    definitionTr: 'Basınç kaybı veya yangın nedeniyle hızlı alçalma, genelde FL100\'e.',
    examples: [
      { en: 'Emergency descent due to depressurization.', tr: 'Basınç kaybı nedeniyle acil alçalma.' },
      { en: 'Mask on, deploy speed brakes.', tr: 'Maske takıldı, speed brake açıldı.' },
    ],
    relatedTerms: ['depressurization', 'oxygen mask', 'speed brakes'],
  },
  { id: 'voc_pilot_053', term: 'ditching', termTr: 'suya iniş', pronunciation: '/ˈdɪtʃ.ɪŋ/', category: 'emergency', difficulty: 3,
    definitionEn: 'Controlled emergency landing on water.',
    definitionTr: 'Su üzerinde kontrollü acil iniş.',
    examples: [
      { en: 'Ditching: brace position, life vests on.', tr: 'Ditching: brace pozisyonu, can yelekleri takılı.' },
      { en: 'Hudson River ditching, 2009.', tr: '2009 Hudson Nehri ditching\'i.' },
    ],
    relatedTerms: ['life vest', 'evacuation slide', 'brace'],
  },
  { id: 'voc_pilot_054', term: 'fuel emergency', termTr: 'yakıt acili', pronunciation: '/fjuːəl ɪˈmɜː.dʒən.si/', category: 'emergency', difficulty: 3,
    definitionEn: 'Critical low fuel state requiring priority handling by ATC.',
    definitionTr: 'ATC tarafından öncelikli işleme alınması gereken kritik düşük yakıt durumu.',
    examples: [
      { en: 'Declare fuel emergency: minimum fuel.', tr: 'Yakıt acili bildir: minimum fuel.' },
      { en: 'Fuel emergency = mayday-level priority.', tr: 'Fuel emergency = mayday seviyesinde öncelik.' },
    ],
    relatedTerms: ['minimum fuel', 'divert', 'mayday'],
  },
  { id: 'voc_pilot_055', term: 'brace position', termTr: 'sarılma pozisyonu', pronunciation: '/breɪs pəˈzɪʃ.ən/', category: 'emergency', difficulty: 3,
    definitionEn: 'Defensive body posture before impact or crash landing.',
    definitionTr: 'Çarpma veya acil iniş öncesi savunma pozisyonu.',
    examples: [
      { en: '"Brace! Brace! Brace!"', tr: '"Sarıl! Sarıl! Sarıl!"' },
      { en: 'Demonstrate brace in safety briefing.', tr: 'Emniyet brifinginde brace göster.' },
    ],
    icaoReference: 'ICAO Doc 9683',
    relatedTerms: ['crash landing', 'impact', 'evacuation'],
  },

  // ===== FLIGHT OPERATIONS (5) =====
  { id: 'voc_pilot_056', term: 'V1', termTr: 'V1 (karar hızı)', pronunciation: '/ˌviː ˈwʌn/', category: 'flight_ops', difficulty: 3,
    definitionEn: 'Decision speed during takeoff: above V1, takeoff must continue.',
    definitionTr: 'Kalkışta karar hızı: V1 üzerinde kalkış sürdürülmeli.',
    examples: [
      { en: 'V1 cut: engine fail above V1, continue takeoff.', tr: 'V1 cut: V1 üstünde motor arızası, kalkışı sürdür.' },
      { en: 'Calculated V1 for this weight: 145 knots.', tr: 'Bu ağırlık için hesaplanan V1: 145 knot.' },
    ],
    relatedTerms: ['VR', 'V2', 'rejected takeoff'],
  },
  { id: 'voc_pilot_057', term: 'VR', termTr: 'VR (rotation hızı)', pronunciation: '/ˌviː ˈɑːr/', category: 'flight_ops', difficulty: 3,
    definitionEn: 'Rotation speed: pilot pulls back on yoke to lift the nose.',
    definitionTr: 'Rotation hızı: pilot yoke\'u geri çekip burnu kaldırır.',
    examples: [
      { en: 'Rotate at VR.', tr: 'VR\'de rotate et.' },
      { en: 'VR slightly above V1.', tr: 'VR, V1\'in biraz üstünde.' },
    ],
    relatedTerms: ['V1', 'V2', 'rotate'],
  },
  { id: 'voc_pilot_058', term: 'minimum fuel', termTr: 'minimum yakıt', pronunciation: '/ˈmɪn.ɪ.məm fjuːəl/', category: 'flight_ops', difficulty: 3,
    definitionEn: 'Notification to ATC that the aircraft can accept little additional delay.',
    definitionTr: 'Uçağın ek gecikme kabul edemeyeceğini ATC\'ye bildirme.',
    examples: [
      { en: 'Pilot: "Minimum fuel."', tr: 'Pilot: "Minimum fuel."' },
      { en: 'Minimum fuel ≠ fuel emergency.', tr: 'Minimum fuel, fuel emergency demek değil.' },
    ],
    relatedTerms: ['fuel emergency', 'reserve fuel', 'divert'],
  },
  { id: 'voc_pilot_059', term: 'divert', termTr: 'divert (alternatif havalimanı)', pronunciation: '/daɪˈvɜːt/', category: 'flight_ops', difficulty: 2,
    definitionEn: 'To proceed to an alternate airport instead of the planned destination.',
    definitionTr: 'Planlanan hedef yerine alternatif havalimanına gitmek.',
    examples: [
      { en: 'Diverting to alternate due to weather.', tr: 'Hava nedeniyle alternatif divert.' },
      { en: 'Divert decision: 30 minutes from destination.', tr: 'Divert kararı: hedeften 30 dakika.' },
    ],
    relatedTerms: ['alternate', 'ETOPS', 'fuel'],
  },
  { id: 'voc_pilot_060', term: 'flight plan', termTr: 'uçuş planı', pronunciation: '/flaɪt plæn/', category: 'flight_ops', difficulty: 2,
    definitionEn: 'Document filed with ATC describing the planned route and details of the flight.',
    definitionTr: 'Uçuşun rota ve detaylarını anlatan, ATC\'ye dosyalanan belge.',
    examples: [
      { en: 'File flight plan via EFB.', tr: 'EFB üzerinden uçuş planı dosyala.' },
      { en: 'Flight plan ICAO format.', tr: 'ICAO formatında uçuş planı.' },
    ],
    icaoReference: 'ICAO Doc 4444',
    relatedTerms: ['IFR', 'VFR', 'route', 'alternate'],
  },
  // ===== ADVANCED PHRASEOLOGY (10) =====
  { id: 'voc_pilot_061', term: 'expect further clearance', termTr: 'expect further clearance (EFC)', pronunciation: '/ɪkˈspekt ˈfɜː.ðər ˈklɪər.əns/', category: 'phraseology', difficulty: 3,
    definitionEn: 'ATC time when you can expect to get further routing instructions.',
    definitionTr: 'ATC\'nin yeni yönlendirme talimatları vereceği tahmini saat.',
    examples: [{ en: 'Hold over ABCDE, EFC time 12:30.', tr: 'ABCDE üzerinde hold, EFC 12:30.' }],
    icaoReference: 'ICAO Doc 9432',
    relatedTerms: ['holding', 'fuel', 'EFC'],
  },
  { id: 'voc_pilot_062', term: 'request direct', termTr: 'doğrudan talep', pronunciation: '/rɪˈkwest dɪˈrekt/', category: 'phraseology', difficulty: 2,
    definitionEn: 'Pilot request to fly directly to a waypoint, skipping airway segments.',
    definitionTr: 'Hava yolu segmentlerini atlayarak doğrudan bir waypoint\'e uçma talebi.',
    examples: [{ en: 'Pilot: "Request direct ABCDE."', tr: 'Pilot: "ABCDE\'ye direkt talep."' }],
    relatedTerms: ['waypoint', 'cleared direct', 'route'],
  },
  { id: 'voc_pilot_063', term: 'cleared direct', termTr: 'doğrudan izin verildi', pronunciation: '/klɪərd dɪˈrekt/', category: 'phraseology', difficulty: 2,
    definitionEn: 'ATC authorization to fly directly to a specified waypoint.',
    definitionTr: 'Belirtilen waypoint\'e doğrudan uçma için ATC izni.',
    examples: [{ en: 'ATC: "Cleared direct WHISKEY, resume own navigation."', tr: 'ATC: "WHISKEY\'ye direkt izin, kendi navigasyona dön."' }],
    relatedTerms: ['request direct', 'resume own nav', 'waypoint'],
  },
  { id: 'voc_pilot_064', term: 'resume own navigation', termTr: 'kendi navigasyona dön', pronunciation: '/rɪˈzjuːm əʊn ˌnæv.ɪˈɡeɪ.ʃən/', category: 'phraseology', difficulty: 3,
    definitionEn: 'ATC instruction to end vectoring and use own published navigation.',
    definitionTr: 'Vector\'ü bitirip kendi yayımlı navigasyonu kullanma ATC talimatı.',
    examples: [{ en: 'ATC: "Resume own navigation, contact center 124.5."', tr: 'ATC: "Kendi nav\'a dön, center 124.5."' }],
    relatedTerms: ['vector', 'cleared direct', 'route'],
  },
  { id: 'voc_pilot_065', term: 'expedite', termTr: 'expedite (hızlandır)', pronunciation: '/ˈek.spə.daɪt/', category: 'phraseology', difficulty: 3,
    definitionEn: 'Instruction to perform a maneuver more quickly than normal.',
    definitionTr: 'Bir manevranın normalden daha hızlı yapılması talimatı.',
    examples: [{ en: 'ATC: "Expedite climb to FL250."', tr: 'ATC: "FL250\'ye expedite climb."' }],
    relatedTerms: ['unable', 'maintain', 'increase'],
  },
  { id: 'voc_pilot_066', term: 'maintain', termTr: 'maintain (sürdür)', pronunciation: '/meɪnˈteɪn/', category: 'phraseology', difficulty: 1,
    definitionEn: 'Instruction to keep altitude, heading, or speed unchanged.',
    definitionTr: 'İrtifa, heading veya hızı değiştirmeden tutma talimatı.',
    examples: [{ en: 'ATC: "Maintain FL350."', tr: 'ATC: "FL350\'yi sürdür."' }],
    relatedTerms: ['climb', 'descend', 'altitude'],
  },
  { id: 'voc_pilot_067', term: 'cross at', termTr: 'cross at (X\'te geç)', pronunciation: '/krɒs æt/', category: 'phraseology', difficulty: 3,
    definitionEn: 'ATC instruction specifying altitude/speed restriction at a waypoint.',
    definitionTr: 'Bir waypoint\'te irtifa/hız kısıtlaması belirten ATC talimatı.',
    examples: [{ en: 'Cross XYZ at or above FL150.', tr: 'XYZ\'yi FL150 ya da üstünde geç.' }],
    relatedTerms: ['restriction', 'altitude', 'waypoint'],
  },
  { id: 'voc_pilot_068', term: 'pilot\'s discretion', termTr: 'pilotun takdirinde', pronunciation: '/ˈpaɪ.ləts dɪˈskreʃ.ən/', category: 'phraseology', difficulty: 4,
    definitionEn: 'ATC clearance allowing pilot to choose timing of altitude change.',
    definitionTr: 'İrtifa değişiminin zamanını pilota bırakan ATC izni.',
    examples: [{ en: 'Descend to FL250 at pilot\'s discretion.', tr: 'FL250\'ye pilot takdirinde alçalma.' }],
    relatedTerms: ['cleared', 'descent', 'altitude'],
  },
  { id: 'voc_pilot_069', term: 'short final', termTr: 'kısa final', pronunciation: '/ʃɔːt ˈfaɪ.nəl/', category: 'phraseology', difficulty: 2,
    definitionEn: 'Final approach phase very close to runway threshold (1-2 NM).',
    definitionTr: 'Pist eşiğine çok yakın final yaklaşma fazı (1-2 NM).',
    examples: [{ en: 'Pilot: "Short final, runway 27."', tr: 'Pilot: "Kısa final, pist 27."' }],
    relatedTerms: ['final', 'threshold', 'cleared to land'],
  },
  { id: 'voc_pilot_070', term: 'minimums', termTr: 'minimums (minimum karar)', pronunciation: '/ˈmɪn.ɪ.məmz/', category: 'phraseology', difficulty: 4,
    definitionEn: 'Decision altitude — the height at which pilot must decide to land or go-around.',
    definitionTr: 'Karar irtifası — pilotun inmek ya da go-around yapmak için karar verdiği yükseklik.',
    examples: [{ en: 'Pilot: "Minimums, runway in sight, landing."', tr: 'Pilot: "Minimums, pist görüldü, iniş."' }],
    relatedTerms: ['decision altitude', 'go-around', 'CAT III'],
  },

  // ===== AIRCRAFT SYSTEMS (10) =====
  { id: 'voc_pilot_071', term: 'FMS', termTr: 'FMS (Uçuş Yönetim Sistemi)', pronunciation: '/ef em es/', category: 'systems', difficulty: 3,
    definitionEn: 'Flight Management System — onboard computer for navigation, performance, fuel.',
    definitionTr: 'Uçuş Yönetim Sistemi — navigasyon, performans, yakıt için uçak içi bilgisayar.',
    examples: [{ en: 'Program FMS with route.', tr: 'FMS\'i rotayla programla.' }],
    relatedTerms: ['CDU', 'autopilot', 'EFIS'],
  },
  { id: 'voc_pilot_072', term: 'EFIS', termTr: 'EFIS (Elektronik Uçuş Aletleri)', pronunciation: '/iː fis/', category: 'systems', difficulty: 4,
    definitionEn: 'Electronic Flight Instrument System — glass cockpit displays.',
    definitionTr: 'Elektronik Uçuş Aleti Sistemi — cam kokpit ekranları.',
    examples: [{ en: 'PFD and ND are part of EFIS.', tr: 'PFD ve ND EFIS\'in parçası.' }],
    relatedTerms: ['PFD', 'ND', 'glass cockpit'],
  },
  { id: 'voc_pilot_073', term: 'PFD', termTr: 'PFD (Birincil Uçuş Ekranı)', pronunciation: '/piː ef diː/', category: 'systems', difficulty: 3,
    definitionEn: 'Primary Flight Display — shows attitude, airspeed, altitude, heading.',
    definitionTr: 'Birincil Uçuş Ekranı — duruş, hız, irtifa, heading gösterir.',
    examples: [{ en: 'PFD failure: revert to standby instruments.', tr: 'PFD arızası: standby aletlerine dön.' }],
    relatedTerms: ['EFIS', 'ND', 'attitude indicator'],
  },
  { id: 'voc_pilot_074', term: 'ND', termTr: 'ND (Navigasyon Ekranı)', pronunciation: '/en diː/', category: 'systems', difficulty: 3,
    definitionEn: 'Navigation Display — shows route, weather, traffic, terrain.',
    definitionTr: 'Navigasyon Ekranı — rota, hava, trafik, arazi gösterir.',
    examples: [{ en: 'Switch ND to MAP mode.', tr: 'ND\'yi MAP moduna al.' }],
    relatedTerms: ['EFIS', 'PFD', 'EHSI'],
  },
  { id: 'voc_pilot_075', term: 'spoiler', termTr: 'spoiler', pronunciation: '/ˈspɔɪ.lər/', category: 'aircraft_parts', difficulty: 2,
    definitionEn: 'Wing surface that disrupts lift and increases drag, used for descent and braking.',
    definitionTr: 'Lift\'i bozup drag\'i artıran kanat yüzeyi; alçalma ve fren için kullanılır.',
    examples: [{ en: 'Speed brakes deploy spoilers.', tr: 'Speed brake spoiler\'ları açar.' }],
    relatedTerms: ['speed brake', 'flap', 'drag'],
  },
  { id: 'voc_pilot_076', term: 'slat', termTr: 'slat', pronunciation: '/slæt/', category: 'aircraft_parts', difficulty: 3,
    definitionEn: 'Leading edge device that increases lift at low speed (takeoff/landing).',
    definitionTr: 'Düşük hızda (kalkış/iniş) lift artıran ön kenar cihazı.',
    examples: [{ en: 'Slats extend with flaps.', tr: 'Slat\'lar flap ile uzar.' }],
    relatedTerms: ['flap', 'leading edge', 'lift'],
  },
  { id: 'voc_pilot_077', term: 'winglet', termTr: 'winglet (kanatçık)', pronunciation: '/ˈwɪŋ.lət/', category: 'aircraft_parts', difficulty: 2,
    definitionEn: 'Vertical extension at wingtip reducing induced drag and saving fuel.',
    definitionTr: 'Kanat ucundaki dikey uzantı; induced drag\'i azaltır, yakıt tasarrufu sağlar.',
    examples: [{ en: '737 MAX has Advanced Technology winglets.', tr: '737 MAX Advanced Technology winglet\'lere sahip.' }],
    relatedTerms: ['drag', 'fuel efficiency', 'wing'],
  },
  { id: 'voc_pilot_078', term: 'pitot tube', termTr: 'pitot tüpü', pronunciation: '/ˈpiː.təʊ tjuːb/', category: 'instruments', difficulty: 3,
    definitionEn: 'Forward-facing tube measuring airspeed via dynamic pressure.',
    definitionTr: 'Dinamik basınçla airspeed ölçen, ileri bakan tüp.',
    examples: [{ en: 'Pitot heat on for icing conditions.', tr: 'Buzlanmada pitot heat açık.' }],
    relatedTerms: ['airspeed', 'static port', 'pitot heat'],
  },
  { id: 'voc_pilot_079', term: 'ECAM', termTr: 'ECAM (Airbus uyarı sistemi)', pronunciation: '/ˈiː.kæm/', category: 'systems', difficulty: 4,
    definitionEn: 'Electronic Centralized Aircraft Monitor — Airbus alert/checklist system.',
    definitionTr: 'Electronic Centralized Aircraft Monitor — Airbus uyarı/kontrol listesi sistemi.',
    examples: [{ en: 'Follow ECAM procedure.', tr: 'ECAM prosedürünü izle.' }],
    relatedTerms: ['EICAS', 'caution', 'warning'],
  },
  { id: 'voc_pilot_080', term: 'EICAS', termTr: 'EICAS (Boeing uyarı sistemi)', pronunciation: '/ˈaɪ.kæs/', category: 'systems', difficulty: 4,
    definitionEn: 'Engine Indicating and Crew Alerting System — Boeing alert system.',
    definitionTr: 'Engine Indicating and Crew Alerting System — Boeing uyarı sistemi.',
    examples: [{ en: 'EICAS shows engine parameters.', tr: 'EICAS motor parametrelerini gösterir.' }],
    relatedTerms: ['ECAM', 'master warning', 'master caution'],
  },

  // ===== APPROACH & LANDING (10) =====
  { id: 'voc_pilot_081', term: 'final approach', termTr: 'final yaklaşma', pronunciation: '/ˈfaɪ.nəl əˈprəʊtʃ/', category: 'navigation', difficulty: 2,
    definitionEn: 'Last segment of approach, aligned with runway centerline.',
    definitionTr: 'Pist merkez hattıyla hizalı, yaklaşmanın son segmenti.',
    examples: [{ en: 'On final, runway 27.', tr: 'Final\'de, pist 27.' }],
    relatedTerms: ['short final', 'base leg', 'localizer'],
  },
  { id: 'voc_pilot_082', term: 'base leg', termTr: 'base leg', pronunciation: '/beɪs leɡ/', category: 'navigation', difficulty: 3,
    definitionEn: 'Pattern segment perpendicular to runway, before final.',
    definitionTr: 'Pattern\'da pite dik, final öncesi segment.',
    examples: [{ en: 'Turning base, runway 27.', tr: 'Base\'e dönüyorum, pist 27.' }],
    relatedTerms: ['downwind', 'final', 'crosswind'],
  },
  { id: 'voc_pilot_083', term: 'downwind', termTr: 'downwind', pronunciation: '/ˌdaʊnˈwɪnd/', category: 'navigation', difficulty: 3,
    definitionEn: 'Pattern segment parallel to runway, opposite direction of landing.',
    definitionTr: 'Pite paralel, iniş yönüne ters pattern segmenti.',
    examples: [{ en: 'On downwind for runway 27.', tr: 'Pist 27 için downwind\'deyim.' }],
    relatedTerms: ['base', 'final', 'pattern'],
  },
  { id: 'voc_pilot_084', term: 'missed approach', termTr: 'pas geçme', pronunciation: '/mɪst əˈprəʊtʃ/', category: 'navigation', difficulty: 3,
    definitionEn: 'Procedure when landing cannot be completed; climb and re-approach.',
    definitionTr: 'İnişin tamamlanamadığında; yükselip yeniden yaklaşma prosedürü.',
    examples: [{ en: 'Going missed, climbing to 3,000.', tr: 'Missed yapıyoruz, 3.000\'e tırmanıyoruz.' }],
    relatedTerms: ['go-around', 'minimums', 'approach'],
  },
  { id: 'voc_pilot_085', term: 'touchdown', termTr: 'yere temas', pronunciation: '/ˈtʌtʃ.daʊn/', category: 'flight_ops', difficulty: 1,
    definitionEn: 'Moment when aircraft wheels first contact the runway.',
    definitionTr: 'Uçak tekerleklerinin piste ilk temas anı.',
    examples: [{ en: 'Smooth touchdown.', tr: 'Yumuşak touchdown.' }],
    relatedTerms: ['landing', 'flare', 'rollout'],
  },
  { id: 'voc_pilot_086', term: 'flare', termTr: 'flare (iniş öncesi burun yukarı)', pronunciation: '/fleər/', category: 'flight_ops', difficulty: 3,
    definitionEn: 'Brief nose-up maneuver just before touchdown to reduce descent rate.',
    definitionTr: 'Touchdown öncesi alçalma hızını azaltmak için kısa burun yukarı manevra.',
    examples: [{ en: 'Begin flare at 30 feet.', tr: '30 feet\'te flare başla.' }],
    relatedTerms: ['touchdown', 'rotate', 'idle'],
  },
  { id: 'voc_pilot_087', term: 'crosswind', termTr: 'yan rüzgar', pronunciation: '/ˈkrɒs.wɪnd/', category: 'weather', difficulty: 2,
    definitionEn: 'Wind blowing perpendicular to the runway direction.',
    definitionTr: 'Pist yönüne dik esen rüzgar.',
    examples: [{ en: 'Crosswind component 20 knots.', tr: 'Yan rüzgar bileşeni 20 knot.' }],
    relatedTerms: ['headwind', 'tailwind', 'wind component'],
  },
  { id: 'voc_pilot_088', term: 'headwind', termTr: 'baş rüzgarı', pronunciation: '/ˈhed.wɪnd/', category: 'weather', difficulty: 1,
    definitionEn: 'Wind blowing against the direction of flight.',
    definitionTr: 'Uçuş yönüne karşı esen rüzgar.',
    examples: [{ en: 'Headwind extends flight time.', tr: 'Baş rüzgarı uçuş süresini uzatır.' }],
    relatedTerms: ['tailwind', 'crosswind', 'wind'],
  },
  { id: 'voc_pilot_089', term: 'tailwind', termTr: 'arka rüzgar', pronunciation: '/ˈteɪl.wɪnd/', category: 'weather', difficulty: 1,
    definitionEn: 'Wind blowing in the direction of flight.',
    definitionTr: 'Uçuş yönünde esen rüzgar.',
    examples: [{ en: 'Tailwind reduces flight time.', tr: 'Arka rüzgar uçuş süresini azaltır.' }],
    relatedTerms: ['headwind', 'crosswind', 'jet stream'],
  },
  { id: 'voc_pilot_090', term: 'go-around', termTr: 'go-around (pas geç)', pronunciation: '/ˈɡəʊ.əˌraʊnd/', category: 'phraseology', difficulty: 3,
    definitionEn: 'Decision to abort landing and climb back to pattern altitude.',
    definitionTr: 'İnişi iptal edip pattern irtifasına geri tırmanma kararı.',
    examples: [{ en: 'Pilot: "Going around, Turkish 1234."', tr: 'Pilot: "Going around, Turkish 1234."' }],
    relatedTerms: ['missed approach', 'pattern', 'climb'],
  },

  // ===== ICAO 4 EXAM TERMS (10) =====
  { id: 'voc_pilot_091', term: 'ICAO Level 4', termTr: 'ICAO Seviye 4', pronunciation: '/ˌaɪ.keɪ.eɪ.əʊ ˈlev.əl fɔː/', category: 'exam', difficulty: 3,
    definitionEn: 'Operational level English proficiency required for international pilots.',
    definitionTr: 'Uluslararası pilotlar için gerekli operasyonel seviye İngilizce yeterliliği.',
    examples: [{ en: 'ICAO 4 = minimum operational.', tr: 'ICAO 4 = minimum operasyonel.' }],
    icaoReference: 'ICAO Annex 1, Doc 9835',
    relatedTerms: ['ICAO 5', 'ICAO 6', 'language proficiency'],
  },
  { id: 'voc_pilot_092', term: 'rubric', termTr: 'rubric (değerlendirme kriteri)', pronunciation: '/ˈruː.brɪk/', category: 'exam', difficulty: 4,
    definitionEn: 'Standardized scoring criteria used to evaluate language proficiency.',
    definitionTr: 'Dil yeterliliğini değerlendirmek için standart puanlama kriteri.',
    examples: [{ en: 'ICAO rubric has 6 areas.', tr: 'ICAO rubric 6 alana sahip.' }],
    relatedTerms: ['ICAO Level', 'pronunciation', 'fluency'],
  },
  { id: 'voc_pilot_093', term: 'fluency', termTr: 'akıcılık', pronunciation: '/ˈfluː.ən.si/', category: 'exam', difficulty: 2,
    definitionEn: 'Ability to speak smoothly without unnatural pauses.',
    definitionTr: 'Doğal olmayan duraksamalar olmadan akıcı konuşma yeteneği.',
    examples: [{ en: 'ICAO 4 requires acceptable fluency.', tr: 'ICAO 4 kabul edilebilir akıcılık ister.' }],
    relatedTerms: ['rhythm', 'natural', 'pace'],
  },
  { id: 'voc_pilot_094', term: 'comprehension', termTr: 'anlama', pronunciation: '/ˌkɒm.prɪˈhen.ʃən/', category: 'exam', difficulty: 2,
    definitionEn: 'Ability to understand spoken English in operational context.',
    definitionTr: 'Operasyonel bağlamda konuşulan İngilizceyi anlama yeteneği.',
    examples: [{ en: 'Multi-accent comprehension critical.', tr: 'Çok aksanlı anlama kritik.' }],
    relatedTerms: ['listening', 'understanding', 'accent'],
  },
  { id: 'voc_pilot_095', term: 'paraphrasing', termTr: 'farklı ifade etme', pronunciation: '/ˈpær.ə.freɪ.zɪŋ/', category: 'exam', difficulty: 4,
    definitionEn: 'Restating something in different words; ICAO 4 skill when stuck.',
    definitionTr: 'Bir şeyi farklı kelimelerle yeniden ifade etme; tıkandığında ICAO 4 becerisi.',
    examples: [{ en: 'Use paraphrasing if vocabulary fails.', tr: 'Kelime bulamazsan paraphrasing kullan.' }],
    relatedTerms: ['rephrase', 'explain', 'clarify'],
  },
  { id: 'voc_pilot_096', term: 'circumlocution', termTr: 'dolaylı anlatma', pronunciation: '/ˌsɜː.kəm.ləˈkjuː.ʃən/', category: 'exam', difficulty: 5,
    definitionEn: 'Describing something using more words when the exact term is unknown.',
    definitionTr: 'Tam terimi bilmediğinde daha fazla kelimeyle anlatma.',
    examples: [{ en: 'Use circumlocution: "the thing that holds the wheel" = strut.', tr: 'Circumlocution: "tekerleği tutan şey" = strut.' }],
    relatedTerms: ['paraphrasing', 'description', 'fluency'],
  },
  { id: 'voc_pilot_097', term: 'register', termTr: 'register (resmiyet seviyesi)', pronunciation: '/ˈredʒ.ɪ.stər/', category: 'exam', difficulty: 4,
    definitionEn: 'Level of formality in language — ICAO 4 expects formal/professional register.',
    definitionTr: 'Dilde resmiyet seviyesi — ICAO 4 resmi/profesyonel register bekler.',
    examples: [{ en: 'Use formal register with ATC.', tr: 'ATC ile resmi register kullan.' }],
    relatedTerms: ['formal', 'colloquial', 'professional'],
  },
  { id: 'voc_pilot_098', term: 'collocations', termTr: 'kelime birleşimleri', pronunciation: '/ˌkɒl.əˈkeɪ.ʃənz/', category: 'exam', difficulty: 5,
    definitionEn: 'Words that naturally go together (e.g., "make a decision", not "do a decision").',
    definitionTr: 'Doğal birlikte kullanılan kelimeler (örn: "make a decision", "do a decision" değil).',
    examples: [{ en: 'Aviation collocations: "fly a route".', tr: 'Havacılık kollokasyonu: "fly a route".' }],
    relatedTerms: ['vocabulary', 'natural English', 'idioms'],
  },
  { id: 'voc_pilot_099', term: 'mitigation', termTr: 'mitigasyon (azaltma)', pronunciation: '/ˌmɪt.ɪˈɡeɪ.ʃən/', category: 'exam', difficulty: 4,
    definitionEn: 'Reducing severity of a problem; key in problem-solving exam tasks.',
    definitionTr: 'Bir sorunun şiddetini azaltma; problem çözme görevlerinde önemli.',
    examples: [{ en: 'Mitigation strategies for engine failure.', tr: 'Motor arızası için mitigasyon stratejileri.' }],
    relatedTerms: ['risk', 'solution', 'response'],
  },
  { id: 'voc_pilot_100', term: 'situational awareness', termTr: 'durum farkındalığı', pronunciation: '/ˌsɪtʃ.uˈeɪ.ʃə.nəl əˈweə.nəs/', category: 'exam', difficulty: 4,
    definitionEn: 'Perception of environment and ability to project status; key CRM skill.',
    definitionTr: 'Çevreyi algılama ve durum öngörme yeteneği; ana CRM becerisi.',
    examples: [{ en: 'Loss of SA contributes to accidents.', tr: 'Durum farkındalığı kaybı kazaya yol açar.' }],
    relatedTerms: ['CRM', 'awareness', 'perception'],
  },

  // ===== FAZ 2 ADVANCED (40) =====
  // Advanced ATC (10)
  { id: 'voc_pilot_101', term: 'speedbird', termTr: 'British Airways çağrı işareti', pronunciation: '/ˈspiːd.bɜːd/', category: 'phraseology', difficulty: 3,
    definitionEn: 'Call sign for British Airways flights.', definitionTr: 'British Airways uçuşları için çağrı işareti.',
    examples: [{ en: 'Speedbird 123, contact tower.', tr: 'Speedbird 123, kuleyle iletişim.' }],
    relatedTerms: ['call sign', 'BA', 'British Airways'],
  },
  { id: 'voc_pilot_102', term: 'heavy', termTr: 'heavy (geniş gövde)', pronunciation: '/ˈhev.i/', category: 'phraseology', difficulty: 3,
    definitionEn: 'Suffix for wide-body aircraft (B747, A330+) for wake turbulence separation.', definitionTr: 'Wake turbulence ayrımı için geniş gövde ekleme (B747, A330+).',
    examples: [{ en: 'Turkish 1234 Heavy.', tr: 'Turkish 1234 Heavy.' }],
    relatedTerms: ['wake turbulence', 'super', 'wide-body'],
  },
  { id: 'voc_pilot_103', term: 'wake turbulence', termTr: 'wake türbülansı', pronunciation: '/weɪk ˈtɜː.bjə.ləns/', category: 'weather', difficulty: 3,
    definitionEn: 'Disturbed air behind aircraft, dangerous for following aircraft.', definitionTr: 'Uçak arkasındaki bozuk hava, takip eden için tehlikeli.',
    examples: [{ en: 'Cleared for takeoff, caution wake turbulence.', tr: 'Kalkış izni, wake turbulence dikkat.' }],
    relatedTerms: ['heavy', 'separation', 'vortex'],
  },
  { id: 'voc_pilot_104', term: 'separation', termTr: 'ayrım (mesafe)', pronunciation: '/ˌsep.əˈreɪ.ʃən/', category: 'navigation', difficulty: 3,
    definitionEn: 'Required distance between aircraft for safe operations.', definitionTr: 'Güvenli operasyon için uçaklar arası gerekli mesafe.',
    examples: [{ en: '5 NM lateral separation.', tr: '5 NM yanal ayrım.' }],
    relatedTerms: ['wake turbulence', 'vertical', 'lateral'],
  },
  { id: 'voc_pilot_105', term: 'vector', termTr: 'vector (yön talimatı)', pronunciation: '/ˈvek.tər/', category: 'navigation', difficulty: 3,
    definitionEn: 'ATC heading instruction guiding aircraft for sequencing.', definitionTr: 'Sıralama için heading talimatı veren ATC yönlendirmesi.',
    examples: [{ en: 'Vector for ILS approach.', tr: 'ILS yaklaşma için vector.' }],
    relatedTerms: ['heading', 'radar', 'sequencing'],
  },
  { id: 'voc_pilot_106', term: 'radar contact', termTr: 'radar teması', pronunciation: '/ˈreɪ.dɑːr ˈkɒn.tækt/', category: 'phraseology', difficulty: 3,
    definitionEn: 'ATC confirms aircraft is identified on radar.', definitionTr: 'ATC uçağın radarda tanımlandığını bildirir.',
    examples: [{ en: 'ATC: "Radar contact, descend FL250."', tr: 'ATC: "Radar contact, FL250\'ye al."' }],
    relatedTerms: ['radar identified', 'transponder', 'squawk'],
  },
  { id: 'voc_pilot_107', term: 'frequency change', termTr: 'frekans değişimi', pronunciation: '/ˈfriː.kwən.si tʃeɪndʒ/', category: 'phraseology', difficulty: 2,
    definitionEn: 'Switching to another ATC frequency.', definitionTr: 'Başka bir ATC frekansına geçiş.',
    examples: [{ en: 'Contact center 124.5.', tr: 'Center 124.5\'e bağlan.' }],
    relatedTerms: ['contact', 'monitor', 'switch'],
  },
  { id: 'voc_pilot_108', term: 'monitor', termTr: 'monitor (izle)', pronunciation: '/ˈmɒn.ɪ.tər/', category: 'phraseology', difficulty: 3,
    definitionEn: 'Listen to a frequency without making calls until needed.', definitionTr: 'Gerekene kadar çağrı yapmadan frekansı dinle.',
    examples: [{ en: 'Monitor 121.5 emergency.', tr: '121.5 acil frekansı dinle.' }],
    relatedTerms: ['guard', 'frequency', '121.5'],
  },
  { id: 'voc_pilot_109', term: 'altitude restriction', termTr: 'irtifa kısıtlaması', pronunciation: '/ˈæl.tɪ.tjuːd rɪˈstrɪk.ʃən/', category: 'phraseology', difficulty: 3,
    definitionEn: 'Specific altitude required at a waypoint.', definitionTr: 'Bir waypoint\'te gerekli özel irtifa.',
    examples: [{ en: 'Cross XYZ at FL150.', tr: 'XYZ\'yi FL150\'de geç.' }],
    relatedTerms: ['cross at', 'mandatory', 'crossing'],
  },
  { id: 'voc_pilot_110', term: 'speed restriction', termTr: 'hız kısıtlaması', pronunciation: '/spiːd rɪˈstrɪk.ʃən/', category: 'phraseology', difficulty: 3,
    definitionEn: 'Required speed limit at a phase or waypoint.', definitionTr: 'Bir fazda veya waypoint\'te gerekli hız limiti.',
    examples: [{ en: 'Maintain 250 knots below FL100.', tr: 'FL100 altında 250 knot tut.' }],
    relatedTerms: ['Mach', 'IAS', 'reduction'],
  },

  // Advanced Systems (10)
  { id: 'voc_pilot_111', term: 'autoland', termTr: 'autoland (otomatik iniş)', pronunciation: '/ˈɔː.təʊ.lænd/', category: 'systems', difficulty: 4,
    definitionEn: 'Fully automatic landing using ILS Cat IIIa/b/c.', definitionTr: 'ILS Cat IIIa/b/c kullanarak tam otomatik iniş.',
    examples: [{ en: 'Autoland armed.', tr: 'Autoland armed.' }],
    relatedTerms: ['CAT III', 'ILS', 'low visibility'],
  },
  { id: 'voc_pilot_112', term: 'CAT III', termTr: 'CAT III (düşük görüş yaklaşma)', pronunciation: '/kæt θriː/', category: 'systems', difficulty: 5,
    definitionEn: 'Lowest minima ILS approach category for fog operations.', definitionTr: 'Sis operasyonları için en düşük minima ILS yaklaşma kategorisi.',
    examples: [{ en: 'CAT IIIb: RVR 50m.', tr: 'CAT IIIb: RVR 50m.' }],
    relatedTerms: ['autoland', 'RVR', 'minima'],
  },
  { id: 'voc_pilot_113', term: 'TCAS RA', termTr: 'TCAS RA (çakışma çözüm uyarısı)', pronunciation: '/ˈtiː.kæs ɑːr eɪ/', category: 'emergency', difficulty: 5,
    definitionEn: 'Resolution Advisory — TCAS commands climb or descend to avoid collision.', definitionTr: 'Çözüm Uyarısı — çakışmayı önlemek için TCAS climb/descend emri.',
    examples: [{ en: 'TCAS RA: climb, climb!', tr: 'TCAS RA: tırman, tırman!' }],
    relatedTerms: ['TCAS', 'TA', 'collision'],
  },
  { id: 'voc_pilot_114', term: 'EGPWS', termTr: 'EGPWS (gelişmiş yer yakınlığı)', pronunciation: '/iː dʒiː piː dʌb.əl.juː es/', category: 'systems', difficulty: 5,
    definitionEn: 'Enhanced Ground Proximity Warning System — alerts terrain conflicts.', definitionTr: 'Gelişmiş Yer Yakınlığı Uyarı Sistemi — arazi çakışması uyarır.',
    examples: [{ en: 'EGPWS: pull up!', tr: 'EGPWS: yukarı çek!' }],
    relatedTerms: ['terrain', 'pull up', 'GPWS'],
  },
  { id: 'voc_pilot_115', term: 'CPDLC', termTr: 'CPDLC (datalink iletişim)', pronunciation: '/siː piː diː el siː/', category: 'systems', difficulty: 5,
    definitionEn: 'Controller-Pilot Data Link Communications — text-based ATC messages.', definitionTr: 'Controller-Pilot Data Link — metin tabanlı ATC mesajları.',
    examples: [{ en: 'CPDLC clearance received.', tr: 'CPDLC izni alındı.' }],
    relatedTerms: ['datalink', 'FANS', 'oceanic'],
  },
  { id: 'voc_pilot_116', term: 'FANS', termTr: 'FANS (gelecek nesil seyrüsefer)', pronunciation: '/fænz/', category: 'systems', difficulty: 5,
    definitionEn: 'Future Air Navigation System — datalink for oceanic ops.', definitionTr: 'Gelecek Hava Seyrüsefer Sistemi — okyanus operasyonları için datalink.',
    examples: [{ en: 'FANS-1/A oceanic clearance.', tr: 'FANS-1/A okyanus izni.' }],
    relatedTerms: ['CPDLC', 'oceanic', 'ADS-C'],
  },
  { id: 'voc_pilot_117', term: 'ADS-B', termTr: 'ADS-B (otomatik bağımlı izleme)', pronunciation: '/eɪ diː es biː/', category: 'systems', difficulty: 5,
    definitionEn: 'Automatic Dependent Surveillance-Broadcast — broadcasts position via GPS.', definitionTr: 'Otomatik Bağımlı İzleme-Yayın — GPS ile pozisyon yayını.',
    examples: [{ en: 'ADS-B mandate 2025 EU.', tr: 'ADS-B zorunluluğu 2025 AB.' }],
    relatedTerms: ['transponder', 'ATC', 'surveillance'],
  },
  { id: 'voc_pilot_118', term: 'RNAV', termTr: 'RNAV (alan seyrüseferi)', pronunciation: '/ˈɑːr.næv/', category: 'navigation', difficulty: 4,
    definitionEn: 'Area Navigation — GPS-based flying without ground beacons.', definitionTr: 'Alan Seyrüseferi — yer beaconları olmadan GPS tabanlı uçuş.',
    examples: [{ en: 'RNAV approach runway 27.', tr: 'RNAV yaklaşma pist 27.' }],
    relatedTerms: ['GPS', 'GNSS', 'PBN'],
  },
  { id: 'voc_pilot_119', term: 'PBN', termTr: 'PBN (performans bazlı seyrüsefer)', pronunciation: '/piː biː en/', category: 'navigation', difficulty: 5,
    definitionEn: 'Performance-Based Navigation — RNP and RNAV combined standards.', definitionTr: 'Performans Bazlı Seyrüsefer — RNP ve RNAV birleşik standartları.',
    examples: [{ en: 'PBN approach RNP 0.3.', tr: 'PBN yaklaşma RNP 0.3.' }],
    relatedTerms: ['RNAV', 'RNP', 'GNSS'],
  },
  { id: 'voc_pilot_120', term: 'RNP', termTr: 'RNP (gerekli seyrüsefer performansı)', pronunciation: '/ɑːr en piː/', category: 'navigation', difficulty: 5,
    definitionEn: 'Required Navigation Performance — accuracy spec (e.g., RNP 0.3).', definitionTr: 'Gerekli Seyrüsefer Performansı — hassasiyet spec\'i (örn: RNP 0.3).',
    examples: [{ en: 'RNP 0.3: ±0.3 NM accuracy.', tr: 'RNP 0.3: ±0.3 NM hassasiyet.' }],
    relatedTerms: ['PBN', 'RNAV', 'AR'],
  },

  // Advanced Operations (10)
  { id: 'voc_pilot_121', term: 'ETOPS', termTr: 'ETOPS (genişletilmiş çift motorlu ops)', pronunciation: '/ˈiː.tɒps/', category: 'flight_ops', difficulty: 5,
    definitionEn: 'Extended-range Twin-engine Operations — long routes over water/remote areas.', definitionTr: 'Genişletilmiş Çift Motorlu Operasyonlar — su/uzak bölge uzun rotalar.',
    examples: [{ en: 'ETOPS 180 minute capability.', tr: 'ETOPS 180 dakika yetkinlik.' }],
    relatedTerms: ['twin engine', 'oceanic', 'alternate'],
  },
  { id: 'voc_pilot_122', term: 'oceanic', termTr: 'okyanus uçuşu', pronunciation: '/ˌəʊ.ʃiˈæn.ɪk/', category: 'flight_ops', difficulty: 4,
    definitionEn: 'Operations over oceans — typically requires datalink and ETOPS.', definitionTr: 'Okyanus üzeri operasyonlar — genelde datalink ve ETOPS gerektirir.',
    examples: [{ en: 'North Atlantic Track System (NATS).', tr: 'North Atlantic Track System (NATS).' }],
    relatedTerms: ['ETOPS', 'NATS', 'CPDLC'],
  },
  { id: 'voc_pilot_123', term: 'jet stream', termTr: 'jet stream', pronunciation: '/dʒet striːm/', category: 'weather', difficulty: 3,
    definitionEn: 'High-altitude wind belt with strong west-east flow.', definitionTr: 'Güçlü batı-doğu akışlı yüksek irtifa rüzgar kuşağı.',
    examples: [{ en: 'Riding jet stream saves fuel.', tr: 'Jet stream\'i takip yakıt tasarrufu sağlar.' }],
    relatedTerms: ['tailwind', 'headwind', 'cruise altitude'],
  },
  { id: 'voc_pilot_124', term: 'optimum altitude', termTr: 'optimum irtifa', pronunciation: '/ˈɒp.tɪ.məm ˈæl.tɪ.tjuːd/', category: 'flight_ops', difficulty: 4,
    definitionEn: 'Most fuel-efficient altitude for current weight and conditions.', definitionTr: 'Mevcut ağırlık ve koşullar için en yakıt verimli irtifa.',
    examples: [{ en: 'Step climb to optimum.', tr: 'Optimum\'a step climb.' }],
    relatedTerms: ['step climb', 'cruise', 'fuel'],
  },
  { id: 'voc_pilot_125', term: 'step climb', termTr: 'step climb (kademeli tırmanış)', pronunciation: '/step klaɪm/', category: 'flight_ops', difficulty: 4,
    definitionEn: 'Climbing to higher altitude as weight decreases for efficiency.', definitionTr: 'Verimlilik için ağırlık azaldıkça daha yüksek irtifaya tırmanma.',
    examples: [{ en: 'Step climb FL370 → FL390.', tr: 'Step climb FL370 → FL390.' }],
    relatedTerms: ['optimum altitude', 'cruise', 'fuel'],
  },
  { id: 'voc_pilot_126', term: 'cost index', termTr: 'cost index', pronunciation: '/kɒst ˈɪn.deks/', category: 'flight_ops', difficulty: 5,
    definitionEn: 'FMS parameter balancing fuel cost vs time cost (CI 0-999).', definitionTr: 'FMS\'te yakıt maliyeti ile zaman maliyeti dengesi (CI 0-999).',
    examples: [{ en: 'CI 50: balanced economy.', tr: 'CI 50: dengeli ekonomi.' }],
    relatedTerms: ['FMS', 'fuel', 'speed'],
  },
  { id: 'voc_pilot_127', term: 'fuel reserve', termTr: 'yakıt rezervi', pronunciation: '/fjuːəl rɪˈzɜːv/', category: 'flight_ops', difficulty: 3,
    definitionEn: 'Required additional fuel for emergencies (typically 30-45 min).', definitionTr: 'Aciller için gerekli ek yakıt (genelde 30-45 dk).',
    examples: [{ en: 'Final reserve fuel 30 minutes.', tr: 'Final reserve fuel 30 dakika.' }],
    relatedTerms: ['minimum fuel', 'fuel emergency', 'final reserve'],
  },
  { id: 'voc_pilot_128', term: 'alternate airport', termTr: 'alternatif havalimanı', pronunciation: '/ˈɔːl.tə.nət ˈeə.pɔːt/', category: 'flight_ops', difficulty: 3,
    definitionEn: 'Backup airport if landing at destination is not possible.', definitionTr: 'Hedefe inilemezse yedek havalimanı.',
    examples: [{ en: 'Alternate: SAW (Sabiha Gökçen).', tr: 'Alternatif: SAW (Sabiha Gökçen).' }],
    relatedTerms: ['divert', 'fuel', 'flight plan'],
  },
  { id: 'voc_pilot_129', term: 'NOTAM', termTr: 'NOTAM (havacı uyarısı)', pronunciation: '/ˈnəʊ.tæm/', category: 'documentation', difficulty: 3,
    definitionEn: 'Notice to Airmen — time-critical aeronautical information.', definitionTr: 'Notice to Airmen — zamana duyarlı havacılık bildirimi.',
    examples: [{ en: 'Review NOTAMs pre-flight.', tr: 'Uçuş öncesi NOTAM\'ları gözden geçir.' }],
    icaoReference: 'ICAO Annex 15',
    relatedTerms: ['Q-code', 'CLSD', 'WIP'],
  },
  { id: 'voc_pilot_130', term: 'briefing', termTr: 'brifing', pronunciation: '/ˈbriː.fɪŋ/', category: 'flight_ops', difficulty: 2,
    definitionEn: 'Pre-flight discussion of route, weather, threats, contingencies.', definitionTr: 'Rota, hava, tehdit, contingency uçuş öncesi tartışma.',
    examples: [{ en: 'Captain leads departure briefing.', tr: 'Kaptan kalkış brifingini yönetir.' }],
    relatedTerms: ['flight plan', 'crew briefing', 'TEM'],
  },

  // Approach/Landing Advanced (10)
  { id: 'voc_pilot_131', term: 'localizer', termTr: 'localizer', pronunciation: '/ˈloʊ.kə.laɪ.zər/', category: 'navigation', difficulty: 3,
    definitionEn: 'Horizontal guidance of ILS aligning with runway centerline.', definitionTr: 'Pist merkez hattıyla hizalayan ILS yatay kılavuzluk.',
    examples: [{ en: 'Established on localizer.', tr: 'Localizer\'da established.' }],
    relatedTerms: ['ILS', 'glide slope', 'CAT III'],
  },
  { id: 'voc_pilot_132', term: 'glideslope', termTr: 'iniş eğimi', pronunciation: '/ɡlaɪd sləʊp/', category: 'navigation', difficulty: 3,
    definitionEn: 'Vertical guidance component of ILS, typically 3°.', definitionTr: 'ILS dikey kılavuzluk bileşeni, genelde 3°.',
    examples: [{ en: 'Above glide slope: descend.', tr: 'Glide slope üstünde: alçal.' }],
    relatedTerms: ['localizer', 'ILS', 'descent'],
  },
  { id: 'voc_pilot_133', term: 'decision height', termTr: 'karar yüksekliği (DH)', pronunciation: '/dɪˈsɪʒ.ən haɪt/', category: 'navigation', difficulty: 4,
    definitionEn: 'Height at which pilot decides to land or go-around (precision approach).', definitionTr: 'Pilotun inmek veya go-around yapmak için karar verdiği yükseklik (hassas yaklaşma).',
    examples: [{ en: 'DH 200 ft on ILS.', tr: 'ILS\'te DH 200 ft.' }],
    relatedTerms: ['minima', 'MDA', 'autoland'],
  },
  { id: 'voc_pilot_134', term: 'MDA', termTr: 'MDA (Minimum İniş İrtifası)', pronunciation: '/em diː eɪ/', category: 'navigation', difficulty: 4,
    definitionEn: 'Minimum Descent Altitude — non-precision approach minima.', definitionTr: 'Minimum İniş İrtifası — non-precision yaklaşma minimum.',
    examples: [{ en: 'VOR approach MDA 600 ft.', tr: 'VOR yaklaşma MDA 600 ft.' }],
    relatedTerms: ['DH', 'non-precision', 'minima'],
  },
  { id: 'voc_pilot_135', term: 'RVR', termTr: 'RVR (pist görüş mesafesi)', pronunciation: '/ɑːr viː ɑːr/', category: 'weather', difficulty: 4,
    definitionEn: 'Runway Visual Range — visibility along runway, in meters.', definitionTr: 'Pist Görüş Mesafesi — pist boyu görüş, metre olarak.',
    examples: [{ en: 'RVR 550m, CAT II minima.', tr: 'RVR 550m, CAT II minima.' }],
    relatedTerms: ['visibility', 'minima', 'CAT III'],
  },
  { id: 'voc_pilot_136', term: 'flare', termTr: 'flare (iniş öncesi burun yukarı)', pronunciation: '/fleər/', category: 'flight_ops', difficulty: 3,
    definitionEn: 'Brief nose-up before touchdown to reduce descent rate.', definitionTr: 'Touchdown öncesi alçalma hızını azaltmak için kısa burun yukarı.',
    examples: [{ en: 'Begin flare at 30 feet.', tr: '30 feet\'te flare başla.' }],
    relatedTerms: ['touchdown', 'rotate', 'idle'],
  },
  { id: 'voc_pilot_137', term: 'go-around procedure', termTr: 'go-around prosedürü', pronunciation: '/ˈɡəʊ.əˌraʊnd prəˈsiː.dʒər/', category: 'flight_ops', difficulty: 4,
    definitionEn: 'Steps for aborted landing: TOGA, flaps, gear up, climb.', definitionTr: 'İptal iniş adımları: TOGA, flap, gear up, climb.',
    examples: [{ en: 'GA: TOGA push, positive climb.', tr: 'GA: TOGA bas, pozitif climb.' }],
    relatedTerms: ['TOGA', 'missed approach', 'climb'],
  },
  { id: 'voc_pilot_138', term: 'TOGA', termTr: 'TOGA (kalkış/go-around itki)', pronunciation: '/ˈtəʊ.ɡə/', category: 'systems', difficulty: 4,
    definitionEn: 'Takeoff/Go-Around — full thrust button on throttle.', definitionTr: 'Takeoff/Go-Around — gaz kolundaki tam itki butonu.',
    examples: [{ en: 'Push TOGA for go-around.', tr: 'Go-around için TOGA bas.' }],
    relatedTerms: ['go-around', 'takeoff thrust', 'climb'],
  },
  { id: 'voc_pilot_139', term: 'stabilized approach', termTr: 'stabilize yaklaşma', pronunciation: '/ˈsteɪ.bə.laɪzd əˈprəʊtʃ/', category: 'flight_ops', difficulty: 4,
    definitionEn: 'Approach within parameters (speed, vertical path, configuration) by 1000 ft.', definitionTr: '1000 ft\'te parametre içinde (hız, dikey yol, konfigürasyon) yaklaşma.',
    examples: [{ en: 'Unstabilized at 500 ft: go-around.', tr: '500 ft\'te unstabilized: go-around.' }],
    relatedTerms: ['gate', 'go-around', 'minimums'],
  },
  { id: 'voc_pilot_140', term: 'long landing', termTr: 'uzun iniş', pronunciation: '/lɒŋ ˈlæn.dɪŋ/', category: 'flight_ops', difficulty: 4,
    definitionEn: 'Touchdown beyond ideal point (typically 1000 ft from threshold).', definitionTr: 'İdeal noktanın ötesinde touchdown (genelde threshold\'dan 1000 ft).',
    examples: [{ en: 'Long landing risks runway excursion.', tr: 'Uzun iniş runway excursion riski.' }],
    relatedTerms: ['touchdown zone', 'overrun', 'short landing'],
  },

  // ===== FAZ 3 B1 OPERATIONAL (40) =====
  // Non-routine ATC (10)
  { id: 'voc_pilot_141', term: 'deviation', termTr: 'sapma', pronunciation: '/ˌdiː.viˈeɪ.ʃən/', category: 'phraseology', difficulty: 3,
    definitionEn: 'Deliberate departure from cleared route, usually for weather.', definitionTr: 'İzinli rotadan kasıtlı sapma, genelde hava nedeniyle.',
    examples: [{ en: 'Request deviation 20 NM right.', tr: '20 NM sağa deviation talep.' }],
    relatedTerms: ['weather deviation', 'rerouting', 'detour'],
  },
  { id: 'voc_pilot_142', term: 'rerouting', termTr: 'yeniden rotalama', pronunciation: '/ˌriːˈruː.tɪŋ/', category: 'phraseology', difficulty: 3,
    definitionEn: 'New flight path issued by ATC due to traffic, weather, restrictions.', definitionTr: 'Trafik, hava, kısıt nedeniyle ATC tarafından yeni rota.',
    examples: [{ en: 'Rerouting via VIE due to traffic.', tr: 'Trafik nedeniyle VIE üzerinden rerouting.' }],
    relatedTerms: ['amended clearance', 'deviation', 'route'],
  },
  { id: 'voc_pilot_143', term: 'amended clearance', termTr: 'değiştirilmiş izin', pronunciation: '/əˈmen.dɪd ˈklɪər.əns/', category: 'phraseology', difficulty: 4,
    definitionEn: 'New clearance modifying previous instructions.', definitionTr: 'Önceki talimatları değiştiren yeni izin.',
    examples: [{ en: 'Amended clearance: route changed.', tr: 'Amended clearance: rota değişti.' }],
    relatedTerms: ['rerouting', 'clearance', 'amendment'],
  },
  { id: 'voc_pilot_144', term: 'expect', termTr: 'expect (bekle, planla)', pronunciation: '/ɪkˈspekt/', category: 'phraseology', difficulty: 3,
    definitionEn: 'ATC indication of likely future clearance for planning.', definitionTr: 'Planlama için ATC\'nin olası gelecek izin bildirimi.',
    examples: [{ en: 'Expect FL350 at TIME.', tr: 'TIME\'da FL350 expect.' }],
    relatedTerms: ['expect further', 'EFC', 'planning'],
  },
  { id: 'voc_pilot_145', term: 'unable to comply', termTr: 'uygulayamıyorum', pronunciation: '/ʌnˈeɪ.bəl tə kəmˈplaɪ/', category: 'phraseology', difficulty: 3,
    definitionEn: 'Pilot informs ATC instruction cannot be carried out.', definitionTr: 'Pilot, ATC talimatının uygulanamayacağını bildirir.',
    examples: [{ en: 'Unable to comply, request alternate.', tr: 'Uygulayamıyorum, alternatif talep.' }],
    relatedTerms: ['unable', 'request', 'reason'],
  },
  { id: 'voc_pilot_146', term: 'request lower', termTr: 'daha alçak talep', pronunciation: '/rɪˈkwest ˈləʊ.ər/', category: 'phraseology', difficulty: 2,
    definitionEn: 'Pilot requests descent to lower altitude.', definitionTr: 'Pilot daha alçak irtifaya alçalma talep eder.',
    examples: [{ en: 'Request lower due to icing.', tr: 'Buzlanma nedeniyle daha alçak talep.' }],
    relatedTerms: ['descend', 'ride better', 'lower altitude'],
  },
  { id: 'voc_pilot_147', term: 'request higher', termTr: 'daha yüksek talep', pronunciation: '/rɪˈkwest ˈhaɪ.ər/', category: 'phraseology', difficulty: 2,
    definitionEn: 'Pilot requests climb to higher altitude.', definitionTr: 'Pilot daha yüksek irtifaya tırmanma talep eder.',
    examples: [{ en: 'Request higher for fuel.', tr: 'Yakıt için daha yüksek talep.' }],
    relatedTerms: ['climb', 'optimum', 'higher altitude'],
  },
  { id: 'voc_pilot_148', term: 'traffic in sight', termTr: 'trafiği görüyorum', pronunciation: '/ˈtræf.ɪk ɪn saɪt/', category: 'phraseology', difficulty: 3,
    definitionEn: 'Pilot acknowledges visual contact with traffic ATC reported.', definitionTr: 'ATC\'nin bildirdiği trafiği görsel teyit.',
    examples: [{ en: 'Traffic 12 o\'clock, in sight.', tr: 'Saat 12\'de trafik, görüyorum.' }],
    relatedTerms: ['visual', 'traffic alert', 'TCAS'],
  },
  { id: 'voc_pilot_149', term: 'pass behind', termTr: 'arkadan geç', pronunciation: '/pɑːs bɪˈhaɪnd/', category: 'phraseology', difficulty: 4,
    definitionEn: 'ATC instruction to pass behind another aircraft.', definitionTr: 'Başka bir uçağın arkasından geçme ATC talimatı.',
    examples: [{ en: 'Pass behind Turkish 1234.', tr: 'Turkish 1234\'ün arkasından geç.' }],
    relatedTerms: ['traffic', 'separation', 'visual'],
  },
  { id: 'voc_pilot_150', term: 'maintain visual separation', termTr: 'görsel ayrım koru', pronunciation: '/meɪnˈteɪn ˈvɪʒ.u.əl ˌsep.əˈreɪ.ʃən/', category: 'phraseology', difficulty: 4,
    definitionEn: 'Pilot maintains visual separation from another aircraft.', definitionTr: 'Pilot diğer uçaktan görsel ayrım korur.',
    examples: [{ en: 'Maintain visual separation, traffic 12 o\'clock.', tr: 'Görsel ayrım koru, saat 12 trafik.' }],
    relatedTerms: ['visual', 'separation', 'see and avoid'],
  },

  // Emergency communication (10)
  { id: 'voc_pilot_151', term: 'declare emergency', termTr: 'acil durum bildir', pronunciation: '/dɪˈkleər ɪˈmɜː.dʒən.si/', category: 'emergency', difficulty: 3,
    definitionEn: 'Formally announce emergency to ATC for priority handling.', definitionTr: 'Öncelik için ATC\'ye resmi acil durum bildirimi.',
    examples: [{ en: 'Declaring emergency, fuel critical.', tr: 'Acil bildiriyorum, yakıt kritik.' }],
    relatedTerms: ['mayday', 'pan-pan', 'priority'],
  },
  { id: 'voc_pilot_152', term: 'priority handling', termTr: 'öncelikli işlem', pronunciation: '/praɪˈɒr.ə.ti ˈhæn.dlɪŋ/', category: 'emergency', difficulty: 3,
    definitionEn: 'ATC gives the aircraft preference over other traffic.', definitionTr: 'ATC uçağa diğer trafiğe göre tercih verir.',
    examples: [{ en: 'Mayday: priority handling assured.', tr: 'Mayday: priority handling garanti.' }],
    relatedTerms: ['mayday', 'declare', 'emergency'],
  },
  { id: 'voc_pilot_153', term: 'lost communication', termTr: 'iletişim kaybı', pronunciation: '/lɒst kəˌmjuː.nɪˈkeɪ.ʃən/', category: 'emergency', difficulty: 3,
    definitionEn: 'Loss of radio contact with ATC — squawk 7600.', definitionTr: 'ATC ile radyo bağlantısı kaybı — squawk 7600.',
    examples: [{ en: 'Squawk 7600, last assigned route.', tr: 'Squawk 7600, son atanan rota.' }],
    relatedTerms: ['squawk 7600', 'radio failure', 'guard frequency'],
  },
  { id: 'voc_pilot_154', term: 'radio failure', termTr: 'radyo arızası', pronunciation: '/ˈreɪ.di.əʊ ˈfeɪl.jər/', category: 'emergency', difficulty: 3,
    definitionEn: 'Communication equipment malfunction.', definitionTr: 'İletişim ekipmanı arızası.',
    examples: [{ en: 'Radio failure: standard procedure.', tr: 'Radyo arızası: standart prosedür.' }],
    relatedTerms: ['lost comm', 'standby radio', 'transponder'],
  },
  { id: 'voc_pilot_155', term: 'guard frequency', termTr: 'guard frekansı (121.5)', pronunciation: '/ɡɑːd ˈfriː.kwən.si/', category: 'phraseology', difficulty: 3,
    definitionEn: 'Emergency frequency 121.5 MHz monitored worldwide.', definitionTr: 'Dünya çapında izlenen 121.5 MHz acil frekansı.',
    examples: [{ en: 'Monitor 121.5 always.', tr: 'Daima 121.5\'i izle.' }],
    relatedTerms: ['121.5', 'emergency frequency', 'distress'],
  },
  { id: 'voc_pilot_156', term: 'engine fire', termTr: 'motor yangını', pronunciation: '/ˈen.dʒɪn faɪər/', category: 'emergency', difficulty: 3,
    definitionEn: 'Fire detected in engine, requiring immediate shutdown.', definitionTr: 'Motorda yangın tespit, derhal kapatma gerekir.',
    examples: [{ en: 'Engine 1 fire, shut down.', tr: 'Motor 1 yangın, kapat.' }],
    relatedTerms: ['fire warning', 'shutdown', 'extinguisher'],
  },
  { id: 'voc_pilot_157', term: 'smoke in cockpit', termTr: 'kokpitte duman', pronunciation: '/sməʊk ɪn ˈkɒk.pɪt/', category: 'emergency', difficulty: 4,
    definitionEn: 'Smoke detected in cockpit — life-threatening.', definitionTr: 'Kokpitte duman — hayati tehlike.',
    examples: [{ en: 'Smoke in cockpit, oxygen masks on.', tr: 'Kokpitte duman, oksijen maskeleri tak.' }],
    relatedTerms: ['oxygen mask', 'emergency descent', 'land ASAP'],
  },
  { id: 'voc_pilot_158', term: 'land as soon as possible', termTr: 'mümkün olduğunca çabuk in', pronunciation: '/lænd əz suːn əz ˈpɒs.ə.bəl/', category: 'emergency', difficulty: 4,
    definitionEn: 'Critical situation requiring nearest suitable airport landing.', definitionTr: 'En yakın uygun havalimanına iniş gerektiren kritik durum.',
    examples: [{ en: 'Smoke: land as soon as possible.', tr: 'Duman: mümkün olduğunca çabuk in.' }],
    relatedTerms: ['nearest suitable', 'emergency', 'divert'],
  },
  { id: 'voc_pilot_159', term: 'land as soon as practical', termTr: 'pratik olur olmaz in', pronunciation: '/lænd əz suːn əz ˈpræk.tɪ.kəl/', category: 'emergency', difficulty: 4,
    definitionEn: 'Less urgent than ASAP — land at suitable but not necessarily nearest airport.', definitionTr: 'ASAP\'tan daha az acil — uygun ama mutlaka en yakın olmayan havalimanına in.',
    examples: [{ en: 'Engine vibration: land as soon as practical.', tr: 'Motor titreşim: pratik olur olmaz in.' }],
    relatedTerms: ['land ASAP', 'priority', 'divert'],
  },
  { id: 'voc_pilot_160', term: 'distress signal', termTr: 'tehlike sinyali', pronunciation: '/dɪˈstres ˈsɪɡ.nəl/', category: 'emergency', difficulty: 3,
    definitionEn: 'Mayday call — highest level emergency communication.', definitionTr: 'Mayday çağrısı — en yüksek seviye acil iletişim.',
    examples: [{ en: 'Distress signal Mayday × 3.', tr: 'Mayday × 3 distress sinyali.' }],
    relatedTerms: ['mayday', 'urgency', 'priority'],
  },

  // International ops & critical thinking (20)
  { id: 'voc_pilot_161', term: 'standard phraseology', termTr: 'standart frazeoloji', pronunciation: '/ˈstæn.dəd ˌfreɪ.zi.ˈɒl.ə.dʒi/', category: 'phraseology', difficulty: 3,
    definitionEn: 'ICAO-approved language for ATC communication, reduces errors.', definitionTr: 'ATC iletişimi için ICAO onaylı dil, hataları azaltır.',
    examples: [{ en: 'Use standard phraseology only.', tr: 'Sadece standart frazeoloji kullan.' }],
    icaoReference: 'ICAO Doc 9432',
    relatedTerms: ['ICAO', 'plain English', 'phraseology'],
  },
  { id: 'voc_pilot_162', term: 'plain English', termTr: 'düz İngilizce', pronunciation: '/pleɪn ˈɪŋ.ɡlɪʃ/', category: 'phraseology', difficulty: 3,
    definitionEn: 'Used when standard phraseology insufficient (emergencies, complex situations).', definitionTr: 'Standart frazeoloji yetersizse (acil, karmaşık durumlar).',
    examples: [{ en: 'Switch to plain English in emergency.', tr: 'Acilde düz İngilizceye geç.' }],
    relatedTerms: ['standard phraseology', 'ICAO 4', 'emergency'],
  },
  { id: 'voc_pilot_163', term: 'oceanic clearance', termTr: 'okyanus izni', pronunciation: '/ˌəʊ.ʃiˈæn.ɪk ˈklɪər.əns/', category: 'phraseology', difficulty: 4,
    definitionEn: 'Special clearance for trans-oceanic flight, often via CPDLC.', definitionTr: 'Okyanus aşırı uçuş için özel izin, genelde CPDLC ile.',
    examples: [{ en: 'Oceanic clearance via NAT track.', tr: 'NAT track üzerinden okyanus izni.' }],
    relatedTerms: ['NAT', 'CPDLC', 'oceanic'],
  },
  { id: 'voc_pilot_164', term: 'NAT', termTr: 'NAT (Kuzey Atlantik İzleri)', pronunciation: '/næt/', category: 'navigation', difficulty: 5,
    definitionEn: 'North Atlantic Tracks — predefined oceanic routes.', definitionTr: 'Kuzey Atlantik İzleri — önceden tanımlı okyanus rotaları.',
    examples: [{ en: 'NAT track Charlie at FL370.', tr: 'NAT track Charlie FL370\'te.' }],
    relatedTerms: ['oceanic', 'track', 'westbound'],
  },
  { id: 'voc_pilot_165', term: 'jet upset', termTr: 'jet upset (kontrol kaybı)', pronunciation: '/dʒet ˈʌp.set/', category: 'emergency', difficulty: 5,
    definitionEn: 'Unintended airplane attitude beyond normal limits.', definitionTr: 'Normal limitler ötesi istem dışı uçak duruşu.',
    examples: [{ en: 'UPRT: upset prevention recovery training.', tr: 'UPRT: jet upset önleme kurtarma eğitimi.' }],
    relatedTerms: ['UPRT', 'recovery', 'unusual attitude'],
  },
  { id: 'voc_pilot_166', term: 'UPRT', termTr: 'UPRT (kurtarma eğitimi)', pronunciation: '/juː piː ɑːr tiː/', category: 'training', difficulty: 5,
    definitionEn: 'Upset Prevention and Recovery Training — mandatory for ATPL.', definitionTr: 'Upset Önleme ve Kurtarma Eğitimi — ATPL için zorunlu.',
    examples: [{ en: 'UPRT in simulator.', tr: 'Simülatörde UPRT.' }],
    relatedTerms: ['jet upset', 'recovery', 'simulator'],
  },
  { id: 'voc_pilot_167', term: 'CRM English', termTr: 'CRM İngilizcesi', pronunciation: '/siː ɑːr em ˈɪŋ.ɡlɪʃ/', category: 'crm', difficulty: 4,
    definitionEn: 'Specific phrasing for crew coordination, leadership, briefings.', definitionTr: 'Ekip koordinasyonu, liderlik, brifing için özel ifadeler.',
    examples: [{ en: 'CRM English in crew briefings.', tr: 'Ekip brifinginde CRM İngilizcesi.' }],
    relatedTerms: ['CRM', 'leadership', 'communication'],
  },
  { id: 'voc_pilot_168', term: 'assertive communication', termTr: 'iddialı iletişim', pronunciation: '/əˈsɜː.tɪv kəˌmjuː.nɪˈkeɪ.ʃən/', category: 'crm', difficulty: 4,
    definitionEn: 'Confident, clear expression of concerns or proposals.', definitionTr: 'Kaygı veya önerinin güvenli, net ifadesi.',
    examples: [{ en: 'F/O assertive: "I have concern about..."', tr: 'F/O iddialı: "...endişem var."' }],
    relatedTerms: ['CRM', 'speak up', 'authority gradient'],
  },
  { id: 'voc_pilot_169', term: 'authority gradient', termTr: 'otorite eğimi', pronunciation: '/əˈθɒr.ə.ti ˈɡreɪ.di.ənt/', category: 'crm', difficulty: 5,
    definitionEn: 'Power difference between captain and FO — too steep blocks input.', definitionTr: 'Kaptan-FO güç farkı — çok dik girdi engeller.',
    examples: [{ en: 'Steep authority gradient = risk.', tr: 'Dik authority gradient = risk.' }],
    relatedTerms: ['CRM', 'hierarchy', 'speak up'],
  },
  { id: 'voc_pilot_170', term: 'sterile cockpit', termTr: 'sterile kokpit', pronunciation: '/ˈster.aɪl ˈkɒk.pɪt/', category: 'crm', difficulty: 4,
    definitionEn: 'Below 10,000 ft — only essential conversation allowed.', definitionTr: '10,000 ft altı — sadece kritik konuşma izinli.',
    examples: [{ en: 'Sterile cockpit, focus on flying.', tr: 'Sterile kokpit, uçmaya odaklan.' }],
    relatedTerms: ['CRM', 'concentration', 'critical phase'],
  },
  { id: 'voc_pilot_171', term: 'briefing', termTr: 'brifing', pronunciation: '/ˈbriː.fɪŋ/', category: 'crm', difficulty: 2,
    definitionEn: 'Pre-flight or pre-phase discussion of plan, threats, contingencies.', definitionTr: 'Plan, tehdit, contingency uçuş öncesi/faz öncesi tartışma.',
    examples: [{ en: 'Approach briefing 30 min before.', tr: 'Yaklaşma brifingi 30 dk önce.' }],
    relatedTerms: ['departure briefing', 'approach briefing', 'TEM'],
  },
  { id: 'voc_pilot_172', term: 'callout', termTr: 'callout (sesli bildirim)', pronunciation: '/ˈkɔːl.aʊt/', category: 'crm', difficulty: 3,
    definitionEn: 'Standard verbal announcement (e.g., "1000 to go", "minimums").', definitionTr: 'Standart sözlü duyuru (örn: "1000\'e kaldı", "minimums").',
    examples: [{ en: 'Captain callouts during approach.', tr: 'Yaklaşmada kaptan callout\'ları.' }],
    relatedTerms: ['SOP', 'standard call', 'monitoring'],
  },
  { id: 'voc_pilot_173', term: 'PNF', termTr: 'PNF (Uçmayan Pilot)', pronunciation: '/piː en ef/', category: 'crm', difficulty: 3,
    definitionEn: 'Pilot Not Flying — handles radio, monitoring, checklists.', definitionTr: 'Uçmayan Pilot — radyo, izleme, checklist.',
    examples: [{ en: 'PNF reads checklist.', tr: 'PNF checklist okur.' }],
    relatedTerms: ['PF', 'pilot monitoring', 'CRM'],
  },
  { id: 'voc_pilot_174', term: 'PF', termTr: 'PF (Uçan Pilot)', pronunciation: '/piː ef/', category: 'crm', difficulty: 3,
    definitionEn: 'Pilot Flying — handles controls.', definitionTr: 'Uçan Pilot — kontrolleri kullanır.',
    examples: [{ en: 'PF maintains heading.', tr: 'PF heading\'i korur.' }],
    relatedTerms: ['PNF', 'pilot monitoring', 'CRM'],
  },
  { id: 'voc_pilot_175', term: 'pilot monitoring', termTr: 'izleyen pilot (PM)', pronunciation: '/ˈpaɪ.lət ˈmɒn.ɪ.tər.ɪŋ/', category: 'crm', difficulty: 4,
    definitionEn: 'Modern term for PNF — emphasizes active monitoring role.', definitionTr: 'PNF\'nin modern terimi — aktif izleme rolünü vurgular.',
    examples: [{ en: 'PM verifies PF actions.', tr: 'PM, PF eylemlerini doğrular.' }],
    relatedTerms: ['PNF', 'PF', 'cross-check'],
  },
  { id: 'voc_pilot_176', term: 'cross-check', termTr: 'çapraz kontrol', pronunciation: '/krɒs tʃek/', category: 'crm', difficulty: 3,
    definitionEn: 'PM verifies PF\'s actions — critical for error catching.', definitionTr: 'PM, PF\'nin eylemlerini doğrular — hata yakalamada kritik.',
    examples: [{ en: 'Cross-check altitude setting.', tr: 'İrtifa setini cross-check et.' }],
    relatedTerms: ['monitoring', 'verification', 'CRM'],
  },
  { id: 'voc_pilot_177', term: 'go/no-go decision', termTr: 'git/gitme kararı', pronunciation: '/ɡəʊ nəʊ ɡəʊ dɪˈsɪʒ.ən/', category: 'flight_ops', difficulty: 4,
    definitionEn: 'Final decision to depart or hold based on weather, MEL, fuel.', definitionTr: 'Hava, MEL, yakıt bazlı son kalkış/bekle kararı.',
    examples: [{ en: 'Go/no-go: weather marginal.', tr: 'Go/no-go: hava marjinal.' }],
    relatedTerms: ['dispatch', 'decision', 'dispatch reliability'],
  },
  { id: 'voc_pilot_178', term: 'dispatch', termTr: 'dispatch (sevk)', pronunciation: '/dɪˈspætʃ/', category: 'flight_ops', difficulty: 3,
    definitionEn: 'Authorization to depart based on flight planning.', definitionTr: 'Uçuş planlamasına göre kalkış izni.',
    examples: [{ en: 'Dispatcher releases flight.', tr: 'Dispatcher uçuşu serbest bırakır.' }],
    relatedTerms: ['dispatch release', 'flight planning', 'OCC'],
  },
  { id: 'voc_pilot_179', term: 'minimum equipment list', termTr: 'asgari ekipman listesi (MEL)', pronunciation: '/ˈmɪn.ɪ.məm ɪˈkwɪp.mənt lɪst/', category: 'documentation', difficulty: 4,
    definitionEn: 'Items that may be inoperative for limited dispatch.', definitionTr: 'Sınırlı dispatch için inoperative olabilecek öğeler.',
    examples: [{ en: 'MEL allows 1 generator inop.', tr: 'MEL 1 jeneratör inop\'a izin verir.' }],
    relatedTerms: ['MEL', 'CDL', 'dispatch'],
  },
  { id: 'voc_pilot_180', term: 'fuel critical', termTr: 'yakıt kritik', pronunciation: '/fjuːəl ˈkrɪt.ɪ.kəl/', category: 'emergency', difficulty: 3,
    definitionEn: 'Fuel state requiring immediate landing — beyond minimum fuel.', definitionTr: 'Derhal iniş gerektiren yakıt durumu — minimum fuel ötesi.',
    examples: [{ en: 'Fuel critical, declare emergency.', tr: 'Yakıt kritik, acil bildir.' }],
    relatedTerms: ['minimum fuel', 'fuel emergency', 'mayday'],
  },
];

export function getVocabByCategory(category: string): VocabularyTerm[] {
  return PILOT_VOCAB_FAZ1.filter((v) => v.category === category);
}

export function getVocabByDifficulty(difficulty: 1 | 2 | 3 | 4 | 5): VocabularyTerm[] {
  return PILOT_VOCAB_FAZ1.filter((v) => v.difficulty === difficulty);
}
