/**
 * Havacılık Öğrencisi vocabulary seed — Faz 1.
 * 60 terim: temel havacılık, sektör genel, kariyer, üniversite, sınavlar.
 */
import type { VocabularyTerm } from './pilotVocab';

export const STUDENT_VOCAB_FAZ1: VocabularyTerm[] = [
  // ===== AVIATION FUNDAMENTALS (12) =====
  { id: 'voc_student_001', term: 'aviation', termTr: 'havacılık', pronunciation: '/ˌeɪ.viˈeɪ.ʃən/', category: 'fundamentals', difficulty: 1,
    definitionEn: 'The practice and industry of designing, producing, operating aircraft.',
    definitionTr: 'Uçak tasarlama, üretme ve işletme pratiği ve endüstrisi.',
    examples: [
      { en: 'Aviation industry employs millions.', tr: 'Havacılık sektörü milyonları istihdam eder.' },
      { en: 'Civil and military aviation.', tr: 'Sivil ve askeri havacılık.' },
    ],
    relatedTerms: ['aircraft', 'industry', 'civil aviation'],
  },
  { id: 'voc_student_002', term: 'aircraft', termTr: 'uçak / hava aracı', pronunciation: '/ˈeə.krɑːft/', category: 'fundamentals', difficulty: 1,
    definitionEn: 'A vehicle capable of flight, including airplanes, helicopters, gliders.',
    definitionTr: 'Uçabilen araç — uçak, helikopter, planör dahil.',
    examples: [
      { en: 'Fixed-wing vs rotary-wing aircraft.', tr: 'Sabit kanatlı ve döner kanatlı uçaklar.' },
      { en: 'Aircraft inspected pre-flight.', tr: 'Uçak uçuş öncesi muayene.' },
    ],
    relatedTerms: ['airplane', 'helicopter', 'glider'],
  },
  { id: 'voc_student_003', term: 'airline', termTr: 'havayolu şirketi', pronunciation: '/ˈeə.laɪn/', category: 'industry', difficulty: 1,
    definitionEn: 'A company that provides air transport services.',
    definitionTr: 'Hava taşımacılık hizmeti sunan şirket.',
    examples: [
      { en: 'Turkish Airlines is a flag carrier.', tr: 'Türk Hava Yolları bayrak taşıyıcısı.' },
      { en: 'Low-cost vs full-service airline.', tr: 'Low-cost ve full-service havayolu.' },
    ],
    relatedTerms: ['flag carrier', 'low-cost', 'fleet'],
  },
  { id: 'voc_student_004', term: 'airport', termTr: 'havalimanı', pronunciation: '/ˈeə.pɔːt/', category: 'fundamentals', difficulty: 1,
    definitionEn: 'A facility where aircraft take off, land, and undergo ground operations.',
    definitionTr: 'Uçakların kalktığı, indiği ve yer hizmeti gördüğü tesis.',
    examples: [
      { en: 'Istanbul Airport (IST) is a hub.', tr: 'İstanbul Havalimanı (IST) bir hub.' },
      { en: 'International airport with customs.', tr: 'Gümrüklü uluslararası havalimanı.' },
    ],
    relatedTerms: ['terminal', 'runway', 'apron'],
  },
  { id: 'voc_student_005', term: 'runway', termTr: 'pist', pronunciation: '/ˈrʌn.weɪ/', category: 'fundamentals', difficulty: 1,
    definitionEn: 'A long strip of paved surface where aircraft take off and land.',
    definitionTr: 'Uçakların kalkıp indiği uzun asfalt alan.',
    examples: [
      { en: 'Runway 27 means 270° heading.', tr: 'Pist 27 = 270° heading.' },
      { en: 'Runway lights for night ops.', tr: 'Gece operasyonu için pist ışıkları.' },
    ],
    relatedTerms: ['taxiway', 'threshold', 'apron'],
  },
  { id: 'voc_student_006', term: 'pilot', termTr: 'pilot', pronunciation: '/ˈpaɪ.lət/', category: 'careers', difficulty: 1,
    definitionEn: 'A person trained and licensed to fly an aircraft.',
    definitionTr: 'Uçak uçurmak için eğitimli ve lisanslı kişi.',
    examples: [
      { en: 'Captain (PIC) and first officer.', tr: 'Kaptan (PIC) ve yardımcı pilot.' },
      { en: 'Type rating required for jets.', tr: 'Jetler için type rating gerekli.' },
    ],
    relatedTerms: ['captain', 'first officer', 'PIC', 'type rating'],
  },
  { id: 'voc_student_007', term: 'cabin crew', termTr: 'kabin ekibi', pronunciation: '/ˈkæb.ɪn kruː/', category: 'careers', difficulty: 1,
    definitionEn: 'Flight attendants who serve passengers and ensure safety on board.',
    definitionTr: 'Yolculara hizmet eden ve kabin emniyetini sağlayan hostes/stewardlar.',
    examples: [
      { en: 'Cabin crew prepares for departure.', tr: 'Kabin ekibi kalkışa hazırlanır.' },
      { en: 'Multi-lingual cabin crew preferred.', tr: 'Çok dilli kabin ekibi tercih.' },
    ],
    relatedTerms: ['flight attendant', 'purser', 'steward'],
  },
  { id: 'voc_student_008', term: 'maintenance technician', termTr: 'bakım teknisyeni', pronunciation: '/ˈmeɪn.tən.əns tekˈnɪʃ.ən/', category: 'careers', difficulty: 2,
    definitionEn: 'Engineer who maintains, inspects, and repairs aircraft.',
    definitionTr: 'Uçakları bakım, muayene ve tamir eden mühendis.',
    examples: [
      { en: 'B1 license: mechanical work.', tr: 'B1 lisansı: mekanik iş.' },
      { en: 'B2 license: avionics.', tr: 'B2 lisansı: avionik.' },
    ],
    relatedTerms: ['mechanic', 'engineer', 'B1', 'B2'],
  },
  { id: 'voc_student_009', term: 'air traffic control', termTr: 'hava trafik kontrol (ATC)', pronunciation: '/eər ˈtræf.ɪk kənˈtrəʊl/', category: 'industry', difficulty: 2,
    definitionEn: 'Service guiding aircraft on the ground and in the air for safe operations.',
    definitionTr: 'Yerde ve havada uçakları güvenli operasyon için yönlendiren hizmet.',
    examples: [
      { en: 'ATC tower controls airport traffic.', tr: 'ATC kulesi havalimanı trafiğini kontrol.' },
      { en: 'En-route control at FL350.', tr: 'FL350\'de en-route kontrol.' },
    ],
    relatedTerms: ['ATC', 'tower', 'controller', 'radar'],
  },
  { id: 'voc_student_010', term: 'flight attendant', termTr: 'hostes / steward', pronunciation: '/flaɪt əˈten.dənt/', category: 'careers', difficulty: 1,
    definitionEn: 'Cabin crew member trained in safety and customer service.',
    definitionTr: 'Emniyet ve müşteri hizmeti eğitimli kabin ekibi üyesi.',
    examples: [
      { en: 'Apply for flight attendant position.', tr: 'Hostes pozisyonuna başvur.' },
      { en: '6-week training program.', tr: '6 haftalık eğitim programı.' },
    ],
    relatedTerms: ['cabin crew', 'steward', 'purser'],
  },
  { id: 'voc_student_011', term: 'fleet', termTr: 'filo', pronunciation: '/fliːt/', category: 'industry', difficulty: 2,
    definitionEn: 'All aircraft owned/operated by an airline.',
    definitionTr: 'Bir havayolunun sahip olduğu/işlettiği tüm uçaklar.',
    examples: [
      { en: 'THY fleet 400+ aircraft.', tr: 'THY filosu 400+ uçak.' },
      { en: 'Mixed fleet: Airbus + Boeing.', tr: 'Karma filo: Airbus + Boeing.' },
    ],
    relatedTerms: ['airline', 'aircraft', 'capacity'],
  },
  { id: 'voc_student_012', term: 'hub', termTr: 'hub (merkez havalimanı)', pronunciation: '/hʌb/', category: 'industry', difficulty: 2,
    definitionEn: 'Major connection airport for an airline\'s network.',
    definitionTr: 'Bir havayolu ağının ana bağlantı havalimanı.',
    examples: [
      { en: 'Istanbul (IST) is THY\'s hub.', tr: 'İstanbul (IST) THY\'nin hub\'ı.' },
      { en: 'Hub-and-spoke model.', tr: 'Hub-and-spoke modeli.' },
    ],
    relatedTerms: ['flag carrier', 'connection', 'network'],
  },

  // ===== UNIVERSITY & EDUCATION (10) =====
  { id: 'voc_student_013', term: 'university', termTr: 'üniversite', pronunciation: '/ˌjuː.nɪˈvɜː.sə.ti/', category: 'education', difficulty: 1,
    definitionEn: 'Higher education institution offering bachelor\'s/master\'s degrees.',
    definitionTr: 'Lisans/yüksek lisans veren yükseköğretim kurumu.',
    examples: [
      { en: 'THK University offers aviation programs.', tr: 'THK Üniversitesi havacılık programları sunar.' },
      { en: 'Apply via YKS exam.', tr: 'YKS sınavıyla başvur.' },
    ],
    relatedTerms: ['college', 'YKS', 'bachelor\'s degree'],
  },
  { id: 'voc_student_014', term: 'YKS', termTr: 'YKS (üniversite sınavı)', pronunciation: '/waɪ keɪ es/', category: 'exams', difficulty: 2,
    definitionEn: 'Turkish university entrance exam.',
    definitionTr: 'Türkiye üniversite giriş sınavı.',
    examples: [
      { en: 'YKS held annually in June.', tr: 'YKS her Haziran düzenlenir.' },
      { en: 'YKS score determines placement.', tr: 'YKS puanı yerleştirmeyi belirler.' },
    ],
    relatedTerms: ['TYT', 'AYT', 'university'],
  },
  { id: 'voc_student_015', term: 'aviation faculty', termTr: 'havacılık fakültesi', pronunciation: '/ˌeɪ.viˈeɪ.ʃən ˈfæk.əl.ti/', category: 'education', difficulty: 2,
    definitionEn: 'University department dedicated to aviation programs.',
    definitionTr: 'Havacılık programlarına ayrılmış üniversite bölümü.',
    examples: [
      { en: 'Aviation faculty has 4-year programs.', tr: 'Havacılık fakültesi 4 yıllık programlar.' },
      { en: 'Pilotage, ATC, management majors.', tr: 'Pilotaj, ATC, yönetim bölümleri.' },
    ],
    relatedTerms: ['pilotage', 'aviation management', 'ATC'],
  },
  { id: 'voc_student_016', term: 'pilotage', termTr: 'pilotaj', pronunciation: '/ˈpaɪ.lə.tɪdʒ/', category: 'education', difficulty: 2,
    definitionEn: 'University program training future commercial pilots.',
    definitionTr: 'Geleceğin ticari pilotlarını yetiştiren üniversite programı.',
    examples: [
      { en: 'Pilotage: 4-year theoretical + practical.', tr: 'Pilotaj: 4 yıl teorik + pratik.' },
      { en: 'PPL during program.', tr: 'Program boyunca PPL.' },
    ],
    relatedTerms: ['pilot training', 'PPL', 'CPL', 'ATPL'],
  },
  { id: 'voc_student_017', term: 'PPL', termTr: 'PPL (özel pilot lisansı)', pronunciation: '/piː piː el/', category: 'licenses', difficulty: 2,
    definitionEn: 'Private Pilot License — first level pilot license.',
    definitionTr: 'Özel Pilot Lisansı — ilk seviye pilot lisansı.',
    examples: [
      { en: 'PPL minimum 45 flight hours.', tr: 'PPL minimum 45 uçuş saati.' },
      { en: 'PPL only for non-commercial.', tr: 'PPL sadece ticari olmayan.' },
    ],
    relatedTerms: ['CPL', 'ATPL', 'flight training'],
  },
  { id: 'voc_student_018', term: 'CPL', termTr: 'CPL (ticari pilot lisansı)', pronunciation: '/siː piː el/', category: 'licenses', difficulty: 2,
    definitionEn: 'Commercial Pilot License — allows paid pilot work.',
    definitionTr: 'Ticari Pilot Lisansı — ücretli pilot çalışmaya izin verir.',
    examples: [
      { en: 'CPL minimum 200 flight hours.', tr: 'CPL minimum 200 uçuş saati.' },
      { en: 'CPL with IR for IFR ops.', tr: 'IFR ops için CPL+IR.' },
    ],
    relatedTerms: ['PPL', 'ATPL', 'IR', 'commercial'],
  },
  { id: 'voc_student_019', term: 'ATPL', termTr: 'ATPL (havayolu pilot lisansı)', pronunciation: '/eɪ tiː piː el/', category: 'licenses', difficulty: 3,
    definitionEn: 'Airline Transport Pilot License — required to be captain on commercial flights.',
    definitionTr: 'Havayolu Taşımacılık Pilot Lisansı — ticari uçuşlarda kaptan olmak için gerekli.',
    examples: [
      { en: 'ATPL minimum 1500 hours.', tr: 'ATPL minimum 1500 saat.' },
      { en: 'Frozen ATPL: theory only.', tr: 'Frozen ATPL: sadece teori.' },
    ],
    relatedTerms: ['CPL', 'frozen ATPL', 'captain'],
  },
  { id: 'voc_student_020', term: 'flight school', termTr: 'uçuş okulu', pronunciation: '/flaɪt skuːl/', category: 'education', difficulty: 2,
    definitionEn: 'Institution offering practical pilot training.',
    definitionTr: 'Pratik pilot eğitimi sunan kurum.',
    examples: [
      { en: 'Approved Training Organization (ATO).', tr: 'Onaylı Eğitim Organizasyonu (ATO).' },
      { en: 'Flight school + university combo.', tr: 'Uçuş okulu + üniversite kombo.' },
    ],
    relatedTerms: ['ATO', 'instructor', 'flight hours'],
  },
  { id: 'voc_student_021', term: 'simulator', termTr: 'simülatör', pronunciation: '/ˈsɪm.jə.leɪ.tər/', category: 'training', difficulty: 2,
    definitionEn: 'Ground-based training device replicating aircraft systems.',
    definitionTr: 'Uçak sistemlerini taklit eden yer eğitim cihazı.',
    examples: [
      { en: 'Full motion simulator.', tr: 'Tam hareketli simülatör.' },
      { en: 'Sim training mandatory before line.', tr: 'Hat öncesi sim eğitimi zorunlu.' },
    ],
    relatedTerms: ['FFS', 'FNPT', 'training device'],
  },
  { id: 'voc_student_022', term: 'theoretical exam', termTr: 'teorik sınav', pronunciation: '/ˌθɪə.rəˈtɪ.kəl ɪɡˈzæm/', category: 'exams', difficulty: 2,
    definitionEn: 'Written test on aviation theory subjects (meteorology, navigation, etc.).',
    definitionTr: 'Havacılık teori konularında yazılı sınav (meteoroloji, navigasyon vb.).',
    examples: [
      { en: '14 ATPL theory subjects.', tr: '14 ATPL teori konusu.' },
      { en: 'Pass mark: 75%.', tr: 'Geçme notu: %75.' },
    ],
    relatedTerms: ['SHGM exam', 'EASA Part-FCL', 'multiple choice'],
  },

  // ===== EXAMS & CERTIFICATIONS (10) =====
  { id: 'voc_student_023', term: 'ICAO Level 4', termTr: 'ICAO Seviye 4', pronunciation: '/ˌaɪ.keɪ.eɪ.əʊ ˈlev.əl fɔː/', category: 'exams', difficulty: 3,
    definitionEn: 'Operational level English proficiency required for international pilots/ATC.',
    definitionTr: 'Uluslararası pilot/ATC için gerekli operasyonel seviye İngilizce yeterliliği.',
    examples: [
      { en: 'ICAO 4 = minimum operational.', tr: 'ICAO 4 = minimum operasyonel.' },
      { en: 'Renewable every 3-6 years.', tr: '3-6 yılda bir yenilenir.' },
    ],
    icaoReference: 'ICAO Annex 1, Doc 9835',
    relatedTerms: ['English proficiency', 'ICAO 5', 'ICAO 6'],
  },
  { id: 'voc_student_024', term: 'ICAO Level 5', termTr: 'ICAO Seviye 5 (Extended)', pronunciation: '/ˌaɪ.keɪ.eɪ.əʊ ˈlev.əl faɪv/', category: 'exams', difficulty: 4,
    definitionEn: 'Extended level English — advanced fluency and complex topic discussion.',
    definitionTr: 'İleri seviye İngilizce — akıcılık ve karmaşık konu tartışması.',
    examples: [
      { en: 'ICAO 5 valid for 6 years.', tr: 'ICAO 5 6 yıl geçerli.' },
      { en: 'Higher pay grades require ICAO 5+.', tr: 'Yüksek ücret grupları ICAO 5+ gerektirir.' },
    ],
    relatedTerms: ['ICAO 4', 'ICAO 6', 'extended'],
  },
  { id: 'voc_student_025', term: 'SHGM', termTr: 'SHGM (Sivil Havacılık Genel Müdürlüğü)', pronunciation: '/es eɪtʃ dʒiː em/', category: 'authority', difficulty: 3,
    definitionEn: 'Turkish Directorate General of Civil Aviation — regulatory authority.',
    definitionTr: 'Türkiye Sivil Havacılık Genel Müdürlüğü — düzenleyici otorite.',
    examples: [
      { en: 'SHGM issues licenses.', tr: 'SHGM lisansları düzenler.' },
      { en: 'SHGM English exam.', tr: 'SHGM İngilizce sınavı.' },
    ],
    relatedTerms: ['DGCA', 'EASA', 'FAA'],
  },
  { id: 'voc_student_026', term: 'EASA', termTr: 'EASA (Avrupa Havacılık Emniyet Ajansı)', pronunciation: '/ˈiː.zə/', category: 'authority', difficulty: 3,
    definitionEn: 'European Union Aviation Safety Agency — regulator.',
    definitionTr: 'Avrupa Birliği Havacılık Emniyet Ajansı — düzenleyici.',
    examples: [
      { en: 'EASA Part-FCL covers pilot licensing.', tr: 'EASA Part-FCL pilot lisanslama.' },
      { en: 'Turkey aligned with EASA standards.', tr: 'Türkiye EASA standartlarıyla uyumlu.' },
    ],
    relatedTerms: ['FAA', 'ICAO', 'SHGM'],
  },
  { id: 'voc_student_027', term: 'FAA', termTr: 'FAA (ABD Federal Havacılık İdaresi)', pronunciation: '/ef eɪ eɪ/', category: 'authority', difficulty: 3,
    definitionEn: 'Federal Aviation Administration — US regulator.',
    definitionTr: 'Federal Havacılık İdaresi — ABD düzenleyicisi.',
    examples: [
      { en: 'FAA regulates US aviation.', tr: 'FAA ABD havacılığını düzenler.' },
      { en: 'FAA Form 8130-3.', tr: 'FAA Form 8130-3.' },
    ],
    relatedTerms: ['EASA', 'ICAO', 'CAA'],
  },
  { id: 'voc_student_028', term: 'TOEFL', termTr: 'TOEFL (İngilizce sınavı)', pronunciation: '/ˈtəʊ.fəl/', category: 'exams', difficulty: 2,
    definitionEn: 'Test of English as a Foreign Language — international English exam.',
    definitionTr: 'Test of English as a Foreign Language — uluslararası İngilizce sınavı.',
    examples: [
      { en: 'TOEFL iBT max 120.', tr: 'TOEFL iBT maksimum 120.' },
      { en: 'Score 80+ for university.', tr: 'Üniversite için 80+.' },
    ],
    relatedTerms: ['IELTS', 'YDS', 'English proficiency'],
  },
  { id: 'voc_student_029', term: 'IELTS', termTr: 'IELTS', pronunciation: '/ˈaɪ.elts/', category: 'exams', difficulty: 2,
    definitionEn: 'International English Language Testing System.',
    definitionTr: 'Uluslararası İngilizce Dil Test Sistemi.',
    examples: [
      { en: 'IELTS Academic vs General.', tr: 'IELTS Academic ve General.' },
      { en: 'Score 6.5+ for most universities.', tr: 'Çoğu üniversite için 6.5+.' },
    ],
    relatedTerms: ['TOEFL', 'YDS', 'English proficiency'],
  },
  { id: 'voc_student_030', term: 'YDS', termTr: 'YDS (Yabancı Dil Sınavı)', pronunciation: '/waɪ diː es/', category: 'exams', difficulty: 2,
    definitionEn: 'Turkish Foreign Language Exam — required for academic positions.',
    definitionTr: 'Yabancı Dil Sınavı — akademik pozisyonlar için gerekli.',
    examples: [
      { en: 'YDS Aviation specialty exam.', tr: 'YDS Havacılık branş sınavı.' },
      { en: 'Score 70+ for proficiency.', tr: 'Yeterlilik için 70+.' },
    ],
    relatedTerms: ['e-YDS', 'YÖKDİL', 'TOEFL'],
  },
  { id: 'voc_student_031', term: 'medical certificate', termTr: 'tıbbi sertifika', pronunciation: '/ˈmed.ɪ.kəl səˈtɪf.ɪ.kət/', category: 'certifications', difficulty: 2,
    definitionEn: 'Medical fitness document required for pilots and ATC.',
    definitionTr: 'Pilot ve ATC için gerekli tıbbi uygunluk belgesi.',
    examples: [
      { en: 'Class 1 medical for ATPL.', tr: 'ATPL için Class 1 medical.' },
      { en: 'Annual medical exam.', tr: 'Yıllık tıbbi muayene.' },
    ],
    relatedTerms: ['Class 1', 'Class 2', 'aeromedical'],
  },
  { id: 'voc_student_032', term: 'background check', termTr: 'sicil kontrolü', pronunciation: '/ˈbæk.ɡraʊnd tʃek/', category: 'requirements', difficulty: 2,
    definitionEn: 'Investigation of an applicant\'s criminal/work history.',
    definitionTr: 'Bir adayın suç/iş geçmişinin araştırılması.',
    examples: [
      { en: 'Clean background required.', tr: 'Temiz sicil gerekli.' },
      { en: 'Aviation security check.', tr: 'Havacılık güvenlik kontrolü.' },
    ],
    relatedTerms: ['security clearance', 'clean record', 'aviation security'],
  },

  // ===== CAREER (10) =====
  { id: 'voc_student_033', term: 'internship', termTr: 'staj', pronunciation: '/ˈɪn.tɜːn.ʃɪp/', category: 'career', difficulty: 1,
    definitionEn: 'Temporary work program providing practical experience.',
    definitionTr: 'Pratik deneyim sağlayan geçici çalışma programı.',
    examples: [
      { en: 'THY Tech summer internship.', tr: 'THY Tech yaz stajı.' },
      { en: 'Apply with CV + transcript.', tr: 'CV + transkript ile başvur.' },
    ],
    relatedTerms: ['placement', 'practical training', 'CV'],
  },
  { id: 'voc_student_034', term: 'CV', termTr: 'CV / özgeçmiş', pronunciation: '/siː viː/', category: 'career', difficulty: 1,
    definitionEn: 'Curriculum Vitae — document summarizing education and experience.',
    definitionTr: 'Eğitim ve deneyim özeti belgesi.',
    examples: [
      { en: '1-page CV preferred for fresh grads.', tr: 'Yeni mezunlar için 1 sayfa CV tercih.' },
      { en: 'Tailor CV to each application.', tr: 'CV\'yi her başvuruya uyarla.' },
    ],
    relatedTerms: ['resume', 'cover letter', 'application'],
  },
  { id: 'voc_student_035', term: 'cover letter', termTr: 'ön yazı', pronunciation: '/ˈkʌv.ər ˈlet.ər/', category: 'career', difficulty: 2,
    definitionEn: 'Letter accompanying CV explaining motivation and fit.',
    definitionTr: 'CV ile birlikte gönderilen, motivasyon ve uyumu açıklayan mektup.',
    examples: [
      { en: 'Personalize cover letter.', tr: 'Ön yazıyı kişiselleştir.' },
      { en: 'Show passion for aviation.', tr: 'Havacılığa tutkunu göster.' },
    ],
    relatedTerms: ['CV', 'application', 'motivation'],
  },
  { id: 'voc_student_036', term: 'interview', termTr: 'mülakat', pronunciation: '/ˈɪn.tə.vjuː/', category: 'career', difficulty: 1,
    definitionEn: 'Formal meeting evaluating a candidate for a position.',
    definitionTr: 'Bir aday için pozisyon değerlendirme resmi görüşmesi.',
    examples: [
      { en: 'THY 3-stage interview.', tr: 'THY 3 aşamalı mülakat.' },
      { en: 'English interview common.', tr: 'İngilizce mülakat yaygın.' },
    ],
    relatedTerms: ['HR interview', 'technical interview', 'group interview'],
  },
  { id: 'voc_student_037', term: 'assessment center', termTr: 'değerlendirme merkezi', pronunciation: '/əˈses.mənt ˈsen.tər/', category: 'career', difficulty: 3,
    definitionEn: 'Day-long evaluation with multiple exercises.',
    definitionTr: 'Birden çok egzersizli gün boyu değerlendirme.',
    examples: [
      { en: 'Group exercise + role-play + interview.', tr: 'Grup egzersizi + rol-play + mülakat.' },
      { en: 'Common for cabin crew.', tr: 'Kabin ekibi için yaygın.' },
    ],
    relatedTerms: ['group exercise', 'role-play', 'final interview'],
  },
  { id: 'voc_student_038', term: 'group exercise', termTr: 'grup egzersizi', pronunciation: '/ɡruːp ˈek.sə.saɪz/', category: 'career', difficulty: 3,
    definitionEn: 'Team activity testing leadership and collaboration.',
    definitionTr: 'Liderlik ve işbirliğini test eden takım aktivitesi.',
    examples: [
      { en: '6 candidates solve a scenario.', tr: '6 aday bir senaryo çözer.' },
      { en: 'Show leadership without dominating.', tr: 'Baskın olmadan liderlik göster.' },
    ],
    relatedTerms: ['assessment center', 'role-play', 'teamwork'],
  },
  { id: 'voc_student_039', term: 'STAR method', termTr: 'STAR yöntemi', pronunciation: '/stɑː ˈmeθ.əd/', category: 'career', difficulty: 3,
    definitionEn: 'Interview technique: Situation, Task, Action, Result.',
    definitionTr: 'Mülakat tekniği: Durum, Görev, Aksiyon, Sonuç.',
    examples: [
      { en: 'Use STAR for behavioral questions.', tr: 'Davranışsal sorular için STAR kullan.' },
      { en: '"Tell me about a conflict..."', tr: '"Bir çatışmadan bahset..."' },
    ],
    relatedTerms: ['behavioral question', 'interview', 'competency'],
  },
  { id: 'voc_student_040', term: 'behavioral question', termTr: 'davranışsal soru', pronunciation: '/bɪˈheɪ.vjə.rəl ˈkwes.tʃən/', category: 'career', difficulty: 3,
    definitionEn: 'Question asking about past experiences to predict future behavior.',
    definitionTr: 'Geleceği tahmin için geçmiş deneyim soran soru.',
    examples: [
      { en: '"Tell me when you handled conflict."', tr: '"Çatışmayı yönettiğin zamanı anlat."' },
      { en: 'Answer with STAR.', tr: 'STAR ile cevap ver.' },
    ],
    relatedTerms: ['STAR', 'competency', 'past experience'],
  },
  { id: 'voc_student_041', term: 'competency', termTr: 'yetkinlik', pronunciation: '/ˈkɒm.pɪ.tən.si/', category: 'career', difficulty: 3,
    definitionEn: 'Skill or behavior required for successful job performance.',
    definitionTr: 'Başarılı iş performansı için gerekli beceri/davranış.',
    examples: [
      { en: 'Teamwork and adaptability competencies.', tr: 'Takım çalışması ve uyum yetkinlikleri.' },
      { en: 'Competency-based interview.', tr: 'Yetkinlik bazlı mülakat.' },
    ],
    relatedTerms: ['skill', 'soft skill', 'hard skill'],
  },
  { id: 'voc_student_042', term: 'salary expectation', termTr: 'beklenen maaş', pronunciation: '/ˈsæl.ər.i ˌek.spekˈteɪ.ʃən/', category: 'career', difficulty: 2,
    definitionEn: 'The amount candidate expects to earn.',
    definitionTr: 'Adayın kazanmayı beklediği tutar.',
    examples: [
      { en: 'Research industry standards first.', tr: 'Önce sektör standartlarını araştır.' },
      { en: 'Provide a range, not a fixed number.', tr: 'Sabit sayı değil aralık ver.' },
    ],
    relatedTerms: ['negotiation', 'benefits', 'package'],
  },

  // ===== SECTOR & ECOSYSTEM (8) =====
  { id: 'voc_student_043', term: 'flag carrier', termTr: 'bayrak taşıyıcı', pronunciation: '/flæɡ ˈkær.i.ər/', category: 'industry', difficulty: 2,
    definitionEn: 'National airline representing a country internationally.',
    definitionTr: 'Bir ülkeyi uluslararası temsil eden ulusal havayolu.',
    examples: [
      { en: 'Turkish Airlines is Turkey\'s flag carrier.', tr: 'Türk Hava Yolları Türkiye\'nin bayrak taşıyıcısı.' },
      { en: 'Lufthansa, Air France are flag carriers.', tr: 'Lufthansa, Air France bayrak taşıyıcı.' },
    ],
    relatedTerms: ['national airline', 'state-owned', 'major carrier'],
  },
  { id: 'voc_student_044', term: 'low-cost carrier', termTr: 'low-cost havayolu', pronunciation: '/ləʊ kɒst ˈkær.i.ər/', category: 'industry', difficulty: 2,
    definitionEn: 'Airline offering low fares with limited services.',
    definitionTr: 'Sınırlı hizmetle düşük ücret sunan havayolu.',
    examples: [
      { en: 'Pegasus, AnadoluJet are low-cost.', tr: 'Pegasus, AnadoluJet low-cost.' },
      { en: 'Ryanair, Wizz Air in Europe.', tr: 'Avrupa\'da Ryanair, Wizz Air.' },
    ],
    relatedTerms: ['LCC', 'point-to-point', 'no-frills'],
  },
  { id: 'voc_student_045', term: 'cargo airline', termTr: 'kargo havayolu', pronunciation: '/ˈkɑː.ɡəʊ ˈeə.laɪn/', category: 'industry', difficulty: 2,
    definitionEn: 'Airline specialized in air freight transport.',
    definitionTr: 'Hava yük taşımacılığında uzmanlaşmış havayolu.',
    examples: [
      { en: 'MNG Cargo, Turkish Cargo.', tr: 'MNG Kargo, Turkish Cargo.' },
      { en: 'FedEx, UPS, DHL global cargo.', tr: 'Global kargo: FedEx, UPS, DHL.' },
    ],
    relatedTerms: ['freight', 'cargo hold', 'logistics'],
  },
  { id: 'voc_student_046', term: 'general aviation', termTr: 'genel havacılık', pronunciation: '/ˈdʒen.ər.əl ˌeɪ.viˈeɪ.ʃən/', category: 'industry', difficulty: 3,
    definitionEn: 'Non-commercial, non-scheduled flying — private, business, training.',
    definitionTr: 'Ticari ve tarifeli olmayan uçuşlar — özel, iş, eğitim.',
    examples: [
      { en: 'GA includes flight schools, charter.', tr: 'GA: uçuş okulları, charter dahil.' },
      { en: 'Single-engine private aircraft.', tr: 'Tek motorlu özel uçaklar.' },
    ],
    relatedTerms: ['private flying', 'charter', 'business jet'],
  },
  { id: 'voc_student_047', term: 'business aviation', termTr: 'iş havacılığı', pronunciation: '/ˈbɪz.nəs ˌeɪ.viˈeɪ.ʃən/', category: 'industry', difficulty: 3,
    definitionEn: 'Aviation for business purposes — corporate jets, private charter.',
    definitionTr: 'İş amaçlı havacılık — kurumsal jetler, özel charter.',
    examples: [
      { en: 'NetJets, VistaJet major operators.', tr: 'Büyük operatörler: NetJets, VistaJet.' },
      { en: 'Bombardier, Gulfstream business jets.', tr: 'Bombardier, Gulfstream iş jetleri.' },
    ],
    relatedTerms: ['corporate jet', 'fractional ownership', 'private charter'],
  },
  { id: 'voc_student_048', term: 'military aviation', termTr: 'askeri havacılık', pronunciation: '/ˈmɪl.ɪ.tər.i ˌeɪ.viˈeɪ.ʃən/', category: 'industry', difficulty: 2,
    definitionEn: 'Aviation operations for military and defense purposes.',
    definitionTr: 'Askeri ve savunma amaçlı havacılık operasyonları.',
    examples: [
      { en: 'Turkish Air Force operates F-16.', tr: 'Türk Hava Kuvvetleri F-16 işletir.' },
      { en: 'TAI: military aircraft manufacturer.', tr: 'TAI: askeri uçak üreticisi.' },
    ],
    relatedTerms: ['fighter jet', 'TAI', 'defense'],
  },
  { id: 'voc_student_049', term: 'manufacturer', termTr: 'üretici', pronunciation: '/ˌmæn.jəˈfæk.tʃər.ər/', category: 'industry', difficulty: 2,
    definitionEn: 'Company producing aircraft (Boeing, Airbus, Embraer).',
    definitionTr: 'Uçak üreten şirket (Boeing, Airbus, Embraer).',
    examples: [
      { en: 'Boeing 737 MAX, Airbus A320neo.', tr: 'Boeing 737 MAX, Airbus A320neo.' },
      { en: 'TUSAŞ Turkish manufacturer.', tr: 'TUSAŞ Türk üretici.' },
    ],
    relatedTerms: ['OEM', 'aircraft maker', 'TUSAŞ'],
  },
  { id: 'voc_student_050', term: 'MRO', termTr: 'MRO (Bakım, Tamir, Overhaul)', pronunciation: '/em ɑːr əʊ/', category: 'industry', difficulty: 3,
    definitionEn: 'Maintenance, Repair, Overhaul — aircraft service industry.',
    definitionTr: 'Bakım, Tamir, Overhaul — uçak servis endüstrisi.',
    examples: [
      { en: 'THY Tech is a major MRO.', tr: 'THY Teknik büyük bir MRO.' },
      { en: 'MNG Technic, Lufthansa Technik.', tr: 'MNG Technic, Lufthansa Technik.' },
    ],
    relatedTerms: ['maintenance', 'overhaul', 'EASA Part-145'],
  },

  // ===== ENGLISH PROFICIENCY GENERAL (10) =====
  { id: 'voc_student_051', term: 'fluency', termTr: 'akıcılık', pronunciation: '/ˈfluː.ən.si/', category: 'language', difficulty: 2,
    definitionEn: 'Ability to speak smoothly and rapidly without unnatural pauses.',
    definitionTr: 'Doğal olmayan duraksamalar olmadan akıcı ve hızlı konuşma yeteneği.',
    examples: [
      { en: 'ICAO 4 requires acceptable fluency.', tr: 'ICAO 4 kabul edilebilir akıcılık ister.' },
      { en: 'Practice daily for fluency.', tr: 'Akıcılık için günlük pratik.' },
    ],
    relatedTerms: ['speaking', 'natural', 'rhythm'],
  },
  { id: 'voc_student_052', term: 'pronunciation', termTr: 'telaffuz', pronunciation: '/prəˌnʌn.siˈeɪ.ʃən/', category: 'language', difficulty: 2,
    definitionEn: 'Way in which a word is articulated.',
    definitionTr: 'Bir kelimenin söyleniş şekli.',
    examples: [
      { en: 'Clear pronunciation crucial for ATC.', tr: 'ATC için net telaffuz kritik.' },
      { en: 'Phonemic transcription helps.', tr: 'Fonemik transkripsiyon yardımcı.' },
    ],
    relatedTerms: ['accent', 'phoneme', 'articulation'],
  },
  { id: 'voc_student_053', term: 'comprehension', termTr: 'anlama', pronunciation: '/ˌkɒm.prɪˈhen.ʃən/', category: 'language', difficulty: 2,
    definitionEn: 'Ability to understand spoken or written language.',
    definitionTr: 'Sözlü veya yazılı dili anlama yeteneği.',
    examples: [
      { en: 'Listening comprehension test.', tr: 'Dinleme anlama testi.' },
      { en: 'Multi-accent listening practice.', tr: 'Çok aksanlı dinleme pratiği.' },
    ],
    relatedTerms: ['listening', 'reading', 'understanding'],
  },
  { id: 'voc_student_054', term: 'vocabulary', termTr: 'kelime hazinesi', pronunciation: '/vəʊˈkæb.jə.lər.i/', category: 'language', difficulty: 1,
    definitionEn: 'Words known by a person; word stock of a language.',
    definitionTr: 'Bir kişinin bildiği kelimeler; bir dilin kelime hazinesi.',
    examples: [
      { en: 'Aviation vocabulary 2000+ terms.', tr: 'Havacılık kelimesi 2000+.' },
      { en: 'SRS for vocabulary retention.', tr: 'Kelime tutma için SRS.' },
    ],
    relatedTerms: ['word list', 'lexicon', 'terminology'],
  },
  { id: 'voc_student_055', term: 'grammar', termTr: 'gramer', pronunciation: '/ˈɡræm.ər/', category: 'language', difficulty: 1,
    definitionEn: 'Rules governing the structure of language.',
    definitionTr: 'Dilin yapısını yöneten kurallar.',
    examples: [
      { en: 'Conditional sentences in aviation.', tr: 'Havacılıkta şart cümleleri.' },
      { en: 'Tense errors common.', tr: 'Zaman hataları yaygın.' },
    ],
    relatedTerms: ['syntax', 'tense', 'structure'],
  },
  { id: 'voc_student_056', term: 'idiom', termTr: 'deyim', pronunciation: '/ˈɪd.i.əm/', category: 'language', difficulty: 3,
    definitionEn: 'Phrase whose meaning is not literal.',
    definitionTr: 'Anlamı kelimelerin gerçek anlamından farklı olan ifade.',
    examples: [
      { en: '"Bite the bullet" = endure pain.', tr: '"Bite the bullet" = acıya katlan.' },
      { en: 'Avoid idioms in ATC communication.', tr: 'ATC iletişiminde deyimlerden kaçın.' },
    ],
    relatedTerms: ['expression', 'phrase', 'colloquial'],
  },
  { id: 'voc_student_057', term: 'phonetic alphabet', termTr: 'fonetik alfabe', pronunciation: '/fəˈnet.ɪk ˈæl.fə.bet/', category: 'language', difficulty: 2,
    definitionEn: 'NATO alphabet used to spell letters in radio communication.',
    definitionTr: 'Radyo iletişiminde harfleri hecelemek için NATO alfabesi.',
    examples: [
      { en: 'Alpha, Bravo, Charlie...', tr: 'Alpha, Bravo, Charlie...' },
      { en: 'TC = Tango Charlie.', tr: 'TC = Tango Charlie.' },
    ],
    relatedTerms: ['NATO alphabet', 'spelling', 'radio'],
  },
  { id: 'voc_student_058', term: 'jargon', termTr: 'jargon (uzmanlık dili)', pronunciation: '/ˈdʒɑː.ɡən/', category: 'language', difficulty: 2,
    definitionEn: 'Specialized vocabulary used by a specific group or profession.',
    definitionTr: 'Belirli grup veya meslek tarafından kullanılan uzmanlık kelimeleri.',
    examples: [
      { en: 'Aviation jargon: cleared, roger, wilco.', tr: 'Havacılık jargonu: cleared, roger, wilco.' },
      { en: 'Avoid jargon with passengers.', tr: 'Yolcularla jargon kullanma.' },
    ],
    relatedTerms: ['terminology', 'specialized language', 'phraseology'],
  },
  { id: 'voc_student_059', term: 'accent', termTr: 'aksan', pronunciation: '/ˈæk.sənt/', category: 'language', difficulty: 1,
    definitionEn: 'Distinctive way of pronouncing a language by a region or group.',
    definitionTr: 'Bir bölge veya grup tarafından bir dilin ayırt edici söyleniş şekli.',
    examples: [
      { en: 'British vs American accent.', tr: 'İngiliz ve Amerikan aksanı.' },
      { en: 'Asian accent challenge for ATC.', tr: 'ATC için Asya aksanı zorluğu.' },
    ],
    relatedTerms: ['pronunciation', 'dialect', 'native accent'],
  },
  { id: 'voc_student_060', term: 'language proficiency', termTr: 'dil yeterliliği', pronunciation: '/ˈlæŋ.ɡwɪdʒ prəˈfɪʃ.ən.si/', category: 'language', difficulty: 2,
    definitionEn: 'Level of skill in using a language.',
    definitionTr: 'Bir dili kullanma beceri seviyesi.',
    examples: [{ en: 'CEFR scale: A1-C2.', tr: 'CEFR skalası: A1-C2.' }],
    relatedTerms: ['CEFR', 'fluency', 'level'],
  },
  // ===== AERODYNAMICS BASICS (10) =====
  { id: 'voc_student_061', term: 'lift', termTr: 'lift (kaldırma kuvveti)', pronunciation: '/lɪft/', category: 'aerodynamics', difficulty: 2,
    definitionEn: 'Upward force generated by wings, opposing gravity.',
    definitionTr: 'Kanatlar tarafından üretilen, yerçekimine karşı yukarı kuvvet.',
    examples: [{ en: 'Bernoulli\'s principle creates lift.', tr: 'Bernoulli prensibi lift üretir.' }],
    relatedTerms: ['drag', 'angle of attack', 'wing'],
  },
  { id: 'voc_student_062', term: 'drag', termTr: 'drag (sürtünme kuvveti)', pronunciation: '/dræɡ/', category: 'aerodynamics', difficulty: 2,
    definitionEn: 'Force opposing aircraft motion through air.',
    definitionTr: 'Uçağın havadaki hareketine karşı duran kuvvet.',
    examples: [{ en: 'Drag increases with speed squared.', tr: 'Drag hız karesiyle artar.' }],
    relatedTerms: ['lift', 'thrust', 'parasite drag'],
  },
  { id: 'voc_student_063', term: 'thrust', termTr: 'thrust (itki)', pronunciation: '/θrʌst/', category: 'aerodynamics', difficulty: 2,
    definitionEn: 'Forward force from engines that propels the aircraft.',
    definitionTr: 'Uçağı ileri iten motorlardan gelen kuvvet.',
    examples: [{ en: 'Full thrust for takeoff.', tr: 'Kalkış için tam thrust.' }],
    relatedTerms: ['drag', 'engine', 'propulsion'],
  },
  { id: 'voc_student_064', term: 'weight', termTr: 'ağırlık', pronunciation: '/weɪt/', category: 'aerodynamics', difficulty: 1,
    definitionEn: 'Gravitational force pulling aircraft down.',
    definitionTr: 'Uçağı aşağı çeken yerçekimi kuvveti.',
    examples: [{ en: 'Weight balanced by lift.', tr: 'Ağırlık lift ile dengelenir.' }],
    relatedTerms: ['lift', 'gravity', 'mass'],
  },
  { id: 'voc_student_065', term: 'angle of attack', termTr: 'saldırı açısı', pronunciation: '/ˈæŋ.ɡəl əv əˈtæk/', category: 'aerodynamics', difficulty: 3,
    definitionEn: 'Angle between wing chord line and oncoming airflow.',
    definitionTr: 'Kanat kiriş hattı ile gelen hava akışı arası açı.',
    examples: [{ en: 'Stall at high angle of attack.', tr: 'Yüksek saldırı açısında stall.' }],
    relatedTerms: ['stall', 'lift', 'AoA'],
  },
  { id: 'voc_student_066', term: 'stall', termTr: 'stall (kanat tutuklanması)', pronunciation: '/stɔːl/', category: 'aerodynamics', difficulty: 3,
    definitionEn: 'Sudden loss of lift when wing exceeds critical angle of attack.',
    definitionTr: 'Kanat kritik saldırı açısını aştığında ani lift kaybı.',
    examples: [{ en: 'Recover from stall: nose down.', tr: 'Stall\'dan kurtul: burun aşağı.' }],
    relatedTerms: ['angle of attack', 'spin', 'recovery'],
  },
  { id: 'voc_student_067', term: 'pitch', termTr: 'pitch (burun yukarı/aşağı)', pronunciation: '/pɪtʃ/', category: 'aerodynamics', difficulty: 2,
    definitionEn: 'Rotation around lateral axis — nose up or down.',
    definitionTr: 'Yan eksen etrafında dönüş — burun yukarı veya aşağı.',
    examples: [{ en: 'Pitch up to climb.', tr: 'Tırmanmak için pitch yukarı.' }],
    relatedTerms: ['roll', 'yaw', 'elevator'],
  },
  { id: 'voc_student_068', term: 'roll', termTr: 'roll (yatış)', pronunciation: '/rəʊl/', category: 'aerodynamics', difficulty: 2,
    definitionEn: 'Rotation around longitudinal axis — banking left or right.',
    definitionTr: 'Boyuna eksen etrafında dönüş — sağa-sola yatış.',
    examples: [{ en: 'Roll left to turn left.', tr: 'Sola dönmek için roll sola.' }],
    relatedTerms: ['pitch', 'yaw', 'aileron'],
  },
  { id: 'voc_student_069', term: 'yaw', termTr: 'yaw (yön değişimi)', pronunciation: '/jɔː/', category: 'aerodynamics', difficulty: 3,
    definitionEn: 'Rotation around vertical axis — nose left or right.',
    definitionTr: 'Dikey eksen etrafında dönüş — burun sağa-sola.',
    examples: [{ en: 'Yaw controlled by rudder.', tr: 'Yaw rudder ile kontrol edilir.' }],
    relatedTerms: ['pitch', 'roll', 'rudder'],
  },
  { id: 'voc_student_070', term: 'four forces of flight', termTr: 'uçuşun dört kuvveti', pronunciation: '/fɔːr ˈfɔː.sɪz əv flaɪt/', category: 'aerodynamics', difficulty: 2,
    definitionEn: 'Lift, weight, thrust, drag — fundamental forces in aviation.',
    definitionTr: 'Lift, weight, thrust, drag — havacılığın temel kuvvetleri.',
    examples: [{ en: 'In level flight, forces balance.', tr: 'Düz uçuşta kuvvetler dengededir.' }],
    relatedTerms: ['lift', 'drag', 'thrust', 'weight'],
  },

  // ===== AVIATION HISTORY & ICONS (8) =====
  { id: 'voc_student_071', term: 'Wright Brothers', termTr: 'Wright Kardeşler', pronunciation: '/raɪt ˈbrʌð.ərz/', category: 'history', difficulty: 1,
    definitionEn: 'Orville and Wilbur Wright — first powered flight in 1903.',
    definitionTr: 'Orville ve Wilbur Wright — 1903\'te ilk motorlu uçuş.',
    examples: [{ en: 'Kitty Hawk, North Carolina, 1903.', tr: 'Kitty Hawk, Kuzey Carolina, 1903.' }],
    relatedTerms: ['first flight', 'aviation history', 'Kitty Hawk'],
  },
  { id: 'voc_student_072', term: 'Boeing', termTr: 'Boeing', pronunciation: '/ˈbəʊ.ɪŋ/', category: 'manufacturer', difficulty: 1,
    definitionEn: 'American aerospace manufacturer — 737, 747, 777, 787 models.',
    definitionTr: 'Amerikan havacılık üreticisi — 737, 747, 777, 787 modelleri.',
    examples: [{ en: 'Boeing 737 most popular jet.', tr: 'Boeing 737 en popüler jet.' }],
    relatedTerms: ['Airbus', 'Embraer', 'manufacturer'],
  },
  { id: 'voc_student_073', term: 'Airbus', termTr: 'Airbus', pronunciation: '/ˈeə.bʌs/', category: 'manufacturer', difficulty: 1,
    definitionEn: 'European aerospace manufacturer — A320, A330, A350, A380 models.',
    definitionTr: 'Avrupa havacılık üreticisi — A320, A330, A350, A380 modelleri.',
    examples: [{ en: 'Airbus A380 largest passenger jet.', tr: 'Airbus A380 en büyük yolcu jeti.' }],
    relatedTerms: ['Boeing', 'manufacturer', 'wide-body'],
  },
  { id: 'voc_student_074', term: 'Embraer', termTr: 'Embraer', pronunciation: '/embrəˈeər/', category: 'manufacturer', difficulty: 2,
    definitionEn: 'Brazilian aerospace manufacturer — regional jets (E170-E195).',
    definitionTr: 'Brezilyalı havacılık üreticisi — bölgesel jetler (E170-E195).',
    examples: [{ en: 'Embraer E190 popular regional.', tr: 'Embraer E190 popüler bölgesel.' }],
    relatedTerms: ['Boeing', 'Airbus', 'regional jet'],
  },
  { id: 'voc_student_075', term: 'TUSAŞ', termTr: 'TUSAŞ (Türk Havacılık)', pronunciation: '/tuː.sɑːʃ/', category: 'manufacturer', difficulty: 2,
    definitionEn: 'Turkish Aerospace Industries — produces military and civil aircraft.',
    definitionTr: 'Türk Havacılık ve Uzay Sanayii — askeri ve sivil uçak üretir.',
    examples: [{ en: 'TUSAŞ makes Hürjet.', tr: 'TUSAŞ Hürjet yapar.' }],
    relatedTerms: ['TAI', 'Hürkuş', 'Turkish defense'],
  },
  { id: 'voc_student_076', term: 'IATA', termTr: 'IATA (Uluslararası Hava Taşımacılığı)', pronunciation: '/aɪˈɑː.tə/', category: 'organization', difficulty: 3,
    definitionEn: 'International Air Transport Association — airlines\' trade organization.',
    definitionTr: 'Uluslararası Hava Taşımacılığı Birliği — havayollarının ticaret örgütü.',
    examples: [{ en: 'IATA airport codes (3 letters).', tr: 'IATA havalimanı kodları (3 harf).' }],
    relatedTerms: ['ICAO', 'airport code', 'airline'],
  },
  { id: 'voc_student_077', term: 'ICAO', termTr: 'ICAO (Uluslararası Sivil Havacılık)', pronunciation: '/ˌaɪ.keɪ.eɪ.əʊ/', category: 'organization', difficulty: 2,
    definitionEn: 'International Civil Aviation Organization — UN agency for civil aviation.',
    definitionTr: 'Uluslararası Sivil Havacılık Örgütü — sivil havacılık BM ajansı.',
    examples: [{ en: 'ICAO sets global standards.', tr: 'ICAO global standartları belirler.' }],
    relatedTerms: ['IATA', 'standards', 'UN'],
  },
  { id: 'voc_student_078', term: 'aviation pioneer', termTr: 'havacılık öncüsü', pronunciation: '/ˌeɪ.viˈeɪ.ʃən ˌpaɪ.əˈnɪər/', category: 'history', difficulty: 3,
    definitionEn: 'Early figure who advanced aviation (Lindbergh, Earhart, Vecihi Hürkuş).',
    definitionTr: 'Havacılığı ilerleten erken dönem figür (Lindbergh, Earhart, Vecihi Hürkuş).',
    examples: [{ en: 'Vecihi Hürkuş: Turkish aviation pioneer.', tr: 'Vecihi Hürkuş: Türk havacılık öncüsü.' }],
    relatedTerms: ['Wright Brothers', 'aviation history', 'Lindbergh'],
  },

  // ===== MODERN AVIATION (8) =====
  { id: 'voc_student_079', term: 'sustainable aviation', termTr: 'sürdürülebilir havacılık', pronunciation: '/səˈsteɪ.nə.bəl ˌeɪ.viˈeɪ.ʃən/', category: 'modern', difficulty: 4,
    definitionEn: 'Aviation reducing environmental impact via SAF, electric/hybrid aircraft.',
    definitionTr: 'SAF, elektrikli/hibrit uçaklarla çevre etkisini azaltan havacılık.',
    examples: [{ en: 'SAF: 80% lower emissions.', tr: 'SAF: %80 daha az emisyon.' }],
    relatedTerms: ['SAF', 'net zero', 'electric aircraft'],
  },
  { id: 'voc_student_080', term: 'SAF', termTr: 'SAF (sürdürülebilir havacılık yakıtı)', pronunciation: '/sæf/', category: 'modern', difficulty: 4,
    definitionEn: 'Sustainable Aviation Fuel — biofuel reducing carbon emissions.',
    definitionTr: 'Sürdürülebilir Havacılık Yakıtı — karbon emisyonunu azaltan biyoyakıt.',
    examples: [{ en: 'SAF blend up to 50%.', tr: 'SAF karışımı %50\'ye kadar.' }],
    relatedTerms: ['biofuel', 'sustainable', 'emissions'],
  },
  { id: 'voc_student_081', term: 'eVTOL', termTr: 'eVTOL (elektrikli dikey kalkış)', pronunciation: '/iː viː tiː əʊ el/', category: 'modern', difficulty: 5,
    definitionEn: 'Electric Vertical Takeoff and Landing aircraft — urban air mobility.',
    definitionTr: 'Elektrikli Dikey Kalkış ve İniş uçağı — kentsel hava mobilitesi.',
    examples: [{ en: 'eVTOL air taxi by 2025.', tr: '2025\'e kadar eVTOL air taxi.' }],
    relatedTerms: ['UAM', 'electric aircraft', 'air taxi'],
  },
  { id: 'voc_student_082', term: 'autonomous aircraft', termTr: 'otonom uçak', pronunciation: '/ɔːˈtɒn.ə.məs ˈeə.krɑːft/', category: 'modern', difficulty: 4,
    definitionEn: 'Aircraft capable of flying without human pilot.',
    definitionTr: 'İnsan pilot olmadan uçabilen uçak.',
    examples: [{ en: 'Cargo drones already autonomous.', tr: 'Kargo drone\'ları zaten otonom.' }],
    relatedTerms: ['UAV', 'drone', 'AI'],
  },
  { id: 'voc_student_083', term: 'CRM', termTr: 'CRM (Mürettebat Kaynak Yönetimi)', pronunciation: '/siː ɑːr em/', category: 'safety', difficulty: 4,
    definitionEn: 'Crew Resource Management — non-technical skills (communication, leadership).',
    definitionTr: 'Mürettebat Kaynak Yönetimi — teknik dışı beceriler (iletişim, liderlik).',
    examples: [{ en: 'CRM training annually.', tr: 'CRM eğitimi yıllık.' }],
    relatedTerms: ['human factors', 'leadership', 'communication'],
  },
  { id: 'voc_student_084', term: 'human factors', termTr: 'insan faktörleri', pronunciation: '/ˈhjuː.mən ˈfæk.təz/', category: 'safety', difficulty: 4,
    definitionEn: 'Study of human performance and limitations in aviation.',
    definitionTr: 'Havacılıkta insan performansı ve sınırlarının çalışılması.',
    examples: [{ en: '70% of accidents involve human factors.', tr: 'Kazaların %70\'i insan faktörüne bağlı.' }],
    relatedTerms: ['CRM', 'fatigue', 'situational awareness'],
  },
  { id: 'voc_student_085', term: 'safety management system', termTr: 'emniyet yönetim sistemi (SMS)', pronunciation: '/ˈseɪf.ti ˈmæn.ɪdʒ.mənt ˈsɪs.təm/', category: 'safety', difficulty: 4,
    definitionEn: 'Systematic approach to managing safety in aviation organizations.',
    definitionTr: 'Havacılık organizasyonlarında emniyet yönetimi için sistematik yaklaşım.',
    examples: [{ en: 'SMS mandatory for airlines.', tr: 'SMS havayolları için zorunlu.' }],
    relatedTerms: ['safety culture', 'risk management', 'audit'],
  },
  { id: 'voc_student_086', term: 'safety culture', termTr: 'emniyet kültürü', pronunciation: '/ˈseɪf.ti ˈkʌl.tʃər/', category: 'safety', difficulty: 3,
    definitionEn: 'Shared values and attitudes prioritizing safety in an organization.',
    definitionTr: 'Bir organizasyonda emniyeti önceliklendiren paylaşılan değerler.',
    examples: [{ en: 'Just culture: no blame for errors.', tr: 'Adil kültür: hatalar için suçlama yok.' }],
    relatedTerms: ['SMS', 'just culture', 'reporting'],
  },

  // ===== AIRPORT CODES & GEOGRAPHY (6) =====
  { id: 'voc_student_087', term: 'IATA code', termTr: 'IATA kodu', pronunciation: '/aɪ.ɑː.tə kəʊd/', category: 'airport', difficulty: 2,
    definitionEn: '3-letter airport identifier (e.g., IST for Istanbul).',
    definitionTr: '3 harfli havalimanı tanımlayıcısı (IST = İstanbul).',
    examples: [{ en: 'IST = Istanbul Airport.', tr: 'IST = İstanbul Havalimanı.' }],
    relatedTerms: ['ICAO code', 'airport code', 'destination'],
  },
  { id: 'voc_student_088', term: 'ICAO code', termTr: 'ICAO kodu', pronunciation: '/aɪ.keɪ.eɪ.əʊ kəʊd/', category: 'airport', difficulty: 2,
    definitionEn: '4-letter airport identifier used by ATC (e.g., LTBA for Istanbul Atatürk).',
    definitionTr: 'ATC tarafından kullanılan 4 harfli havalimanı tanımlayıcısı.',
    examples: [{ en: 'LTBA = Istanbul (old).', tr: 'LTBA = Eski İstanbul.' }],
    relatedTerms: ['IATA code', 'METAR', 'ATC'],
  },
  { id: 'voc_student_089', term: 'destination', termTr: 'destinasyon', pronunciation: '/ˌdes.tɪˈneɪ.ʃən/', category: 'airport', difficulty: 1,
    definitionEn: 'Final airport where the flight ends.',
    definitionTr: 'Uçuşun sona erdiği son havalimanı.',
    examples: [{ en: 'Destination: Istanbul (IST).', tr: 'Destinasyon: İstanbul (IST).' }],
    relatedTerms: ['origin', 'route', 'arrival'],
  },
  { id: 'voc_student_090', term: 'origin', termTr: 'çıkış (origin)', pronunciation: '/ˈɒr.ɪ.dʒɪn/', category: 'airport', difficulty: 1,
    definitionEn: 'Starting airport where the flight begins.',
    definitionTr: 'Uçuşun başladığı havalimanı.',
    examples: [{ en: 'Origin: Berlin (BER).', tr: 'Origin: Berlin (BER).' }],
    relatedTerms: ['destination', 'departure', 'route'],
  },
  { id: 'voc_student_091', term: 'route', termTr: 'rota', pronunciation: '/ruːt/', category: 'airport', difficulty: 1,
    definitionEn: 'Path between origin and destination, including waypoints.',
    definitionTr: 'Origin ve destinasyon arası, waypoint\'leri içeren yol.',
    examples: [{ en: 'Route: BER-IST via VIE.', tr: 'Rota: BER-IST, VIE üzerinden.' }],
    relatedTerms: ['flight plan', 'waypoint', 'airway'],
  },
  { id: 'voc_student_092', term: 'time zone', termTr: 'saat dilimi', pronunciation: '/taɪm zəʊn/', category: 'navigation', difficulty: 1,
    definitionEn: 'Geographic region with same standard time (e.g., UTC+3 for Turkey).',
    definitionTr: 'Aynı standart saate sahip coğrafi bölge (Türkiye UTC+3).',
    examples: [{ en: 'Cross 3 time zones BER-IST.', tr: 'BER-IST 3 saat dilimi geçer.' }],
    relatedTerms: ['UTC', 'jet lag', 'circadian'],
  },

  // ===== CAREER PATH ADVANCED (6) =====
  { id: 'voc_student_093', term: 'first officer', termTr: 'yardımcı pilot (first officer)', pronunciation: '/fɜːst ˈɒf.ɪ.sər/', category: 'career', difficulty: 2,
    definitionEn: 'Co-pilot — second in command, sits in right seat.',
    definitionTr: 'Yardımcı pilot — komutada ikinci, sağ koltukta oturur.',
    examples: [{ en: 'F/O works under captain.', tr: 'F/O kaptan altında çalışır.' }],
    relatedTerms: ['captain', 'cockpit', 'PIC'],
  },
  { id: 'voc_student_094', term: 'captain (PIC)', termTr: 'kaptan (PIC)', pronunciation: '/ˈkæp.tɪn/', category: 'career', difficulty: 2,
    definitionEn: 'Pilot In Command — most senior pilot, sits in left seat.',
    definitionTr: 'Komuta Pilotu — en kıdemli pilot, sol koltukta oturur.',
    examples: [{ en: 'Captain has final authority.', tr: 'Kaptan son yetkiye sahip.' }],
    relatedTerms: ['first officer', 'PIC', 'left seat'],
  },
  { id: 'voc_student_095', term: 'type rating', termTr: 'type rating (uçak tipi yetki)', pronunciation: '/taɪp ˈreɪ.tɪŋ/', category: 'licenses', difficulty: 4,
    definitionEn: 'Authorization to fly a specific aircraft type (e.g., B737, A320).',
    definitionTr: 'Belirli bir uçak tipini uçma yetkisi (B737, A320 gibi).',
    examples: [{ en: 'Type rating B737: 6 weeks training.', tr: 'B737 type rating: 6 hafta eğitim.' }],
    relatedTerms: ['ATPL', 'simulator', 'transition'],
  },
  { id: 'voc_student_096', term: 'cadet program', termTr: 'cadet programı', pronunciation: '/kəˈdet ˈprəʊ.ɡræm/', category: 'career', difficulty: 3,
    definitionEn: 'Airline-sponsored pilot training from zero to first officer.',
    definitionTr: 'Havayolu sponsorlu sıfırdan yardımcı pilota pilot eğitimi.',
    examples: [{ en: 'THY cadet: 18 months ab initio.', tr: 'THY cadet: 18 ay ab initio.' }],
    relatedTerms: ['ab initio', 'training', 'sponsorship'],
  },
  { id: 'voc_student_097', term: 'ab initio', termTr: 'ab initio (sıfırdan)', pronunciation: '/æb ɪˈnɪʃ.i.əʊ/', category: 'training', difficulty: 4,
    definitionEn: 'From the beginning — full pilot training program from zero experience.',
    definitionTr: 'Baştan — sıfır deneyimden başlayan tam pilot eğitim programı.',
    examples: [{ en: 'Ab initio: PPL → CPL → ATPL.', tr: 'Ab initio: PPL → CPL → ATPL.' }],
    relatedTerms: ['cadet program', 'flight training', 'integrated'],
  },
  { id: 'voc_student_098', term: 'logbook', termTr: 'uçuş kayıt defteri', pronunciation: '/ˈlɒɡ.bʊk/', category: 'career', difficulty: 2,
    definitionEn: 'Pilot\'s record of flight hours and experience.',
    definitionTr: 'Pilotun uçuş saatleri ve deneyim kaydı.',
    examples: [{ en: 'Logbook required for hiring.', tr: 'İşe alım için logbook gerekli.' }],
    relatedTerms: ['flight hours', 'experience', 'audit'],
  },

  // ===== AVIATION ENGLISH FOR INTERVIEW (2) =====
  { id: 'voc_student_099', term: 'mock interview', termTr: 'deneme mülakatı', pronunciation: '/mɒk ˈɪn.tə.vjuː/', category: 'career', difficulty: 2,
    definitionEn: 'Practice interview to prepare for real airline assessment.',
    definitionTr: 'Gerçek havayolu değerlendirmesine hazırlık için deneme mülakatı.',
    examples: [{ en: 'Mock interview before THY.', tr: 'THY öncesi mock interview.' }],
    relatedTerms: ['practice', 'STAR method', 'assessment'],
  },
  { id: 'voc_student_100', term: 'aviation industry', termTr: 'havacılık sektörü', pronunciation: '/ˌeɪ.viˈeɪ.ʃən ˈɪn.də.stri/', category: 'industry', difficulty: 1,
    definitionEn: 'Global business of designing, building, operating aircraft.',
    definitionTr: 'Uçak tasarlama, yapma, işletme küresel işi.',
    examples: [{ en: 'Aviation industry employs 88M globally.', tr: 'Havacılık sektörü globalde 88M kişi istihdam eder.' }],
    relatedTerms: ['aviation', 'aerospace', 'employment'],
  },

  // ===== FAZ 2 ADVANCED (40) =====
  // Listening & Comprehension (10)
  { id: 'voc_student_101', term: 'ATC chatter', termTr: 'ATC konuşması', pronunciation: '/ˌeɪ.tiː.siː ˈtʃæt.ər/', category: 'listening', difficulty: 3,
    definitionEn: 'Continuous radio communication between ATC and pilots.', definitionTr: 'ATC ve pilotlar arasındaki sürekli radyo iletişimi.',
    examples: [{ en: 'Listen to ATC chatter via LiveATC.', tr: 'LiveATC ile ATC chatter dinle.' }],
    relatedTerms: ['radio', 'phraseology', 'frequency'],
  },
  { id: 'voc_student_102', term: 'cockpit voice recording', termTr: 'kokpit ses kaydı', pronunciation: '/ˈkɒk.pɪt vɔɪs rɪˈkɔː.dɪŋ/', category: 'listening', difficulty: 4,
    definitionEn: 'Audio captured by CVR — useful for understanding real conversations.', definitionTr: 'CVR tarafından yakalanan ses — gerçek konuşmaları anlamak için yararlı.',
    examples: [{ en: 'CVR data analyzed post-incident.', tr: 'Olay sonrası CVR analizi.' }],
    relatedTerms: ['CVR', 'flight recorder', 'investigation'],
  },
  { id: 'voc_student_103', term: 'multi-accent practice', termTr: 'çok aksanlı pratik', pronunciation: '/ˈmʌl.ti ˈæk.sənt ˈpræk.tɪs/', category: 'listening', difficulty: 4,
    definitionEn: 'Training with various English accents (US, UK, Asian, Middle East).', definitionTr: 'Farklı İngilizce aksanlarla eğitim (ABD, İngiliz, Asya, Orta Doğu).',
    examples: [{ en: 'Multi-accent for ICAO 4 prep.', tr: 'ICAO 4 hazırlığı için multi-accent.' }],
    relatedTerms: ['ICAO 4', 'comprehension', 'accent'],
  },
  { id: 'voc_student_104', term: 'background noise', termTr: 'arka plan gürültüsü', pronunciation: '/ˈbæk.ɡraʊnd nɔɪz/', category: 'listening', difficulty: 3,
    definitionEn: 'Engine, radio static, cabin noise during real flight.', definitionTr: 'Gerçek uçuşta motor, radyo paraziti, kabin gürültüsü.',
    examples: [{ en: 'Practice with background noise.', tr: 'Background noise ile pratik.' }],
    relatedTerms: ['noise reduction', 'comprehension', 'real-world'],
  },
  { id: 'voc_student_105', term: 'speech pattern', termTr: 'konuşma deseni', pronunciation: '/spiːtʃ ˈpæt.ən/', category: 'listening', difficulty: 4,
    definitionEn: 'Way someone speaks — rhythm, pace, intonation.', definitionTr: 'Birinin konuşma biçimi — ritim, tempo, tonlama.',
    examples: [{ en: 'Recognize stressed speech patterns.', tr: 'Stresli konuşma desenlerini tanı.' }],
    relatedTerms: ['intonation', 'rhythm', 'pace'],
  },
  { id: 'voc_student_106', term: 'stressed speech', termTr: 'stresli konuşma', pronunciation: '/strest spiːtʃ/', category: 'listening', difficulty: 4,
    definitionEn: 'Faster, broken speech during emergencies — harder to understand.', definitionTr: 'Acillerde hızlı, kesik konuşma — anlaması zor.',
    examples: [{ en: 'Stressed speech in mayday calls.', tr: 'Mayday çağrılarında stresli konuşma.' }],
    relatedTerms: ['emergency', 'comprehension', 'mayday'],
  },
  { id: 'voc_student_107', term: 'intonation', termTr: 'tonlama', pronunciation: '/ˌɪn.təˈneɪ.ʃən/', category: 'language', difficulty: 3,
    definitionEn: 'Rise and fall of voice — affects meaning.', definitionTr: 'Sesin yükselip alçalması — anlamı etkiler.',
    examples: [{ en: 'Rising intonation for questions.', tr: 'Sorularda yükselen tonlama.' }],
    relatedTerms: ['pronunciation', 'stress', 'rhythm'],
  },
  { id: 'voc_student_108', term: 'word stress', termTr: 'kelime vurgusu', pronunciation: '/wɜːd stres/', category: 'language', difficulty: 3,
    definitionEn: 'Emphasis on specific syllable in a word (DEparture, not deparTURE).', definitionTr: 'Bir kelimedeki belirli heceye vurgu (DEparture, deparTURE değil).',
    examples: [{ en: 'Wrong stress hinders comprehension.', tr: 'Yanlış vurgu anlamayı engeller.' }],
    relatedTerms: ['pronunciation', 'syllable', 'intonation'],
  },
  { id: 'voc_student_109', term: 'minimal pair', termTr: 'minimal çift', pronunciation: '/ˈmɪn.ɪ.məl peər/', category: 'language', difficulty: 4,
    definitionEn: 'Two words differing in one sound (sheep/ship, climb/clime).', definitionTr: 'Tek seste farklılaşan iki kelime (sheep/ship, climb/clime).',
    examples: [{ en: 'Practice minimal pairs.', tr: 'Minimal pair pratiği.' }],
    relatedTerms: ['phoneme', 'pronunciation', 'sound'],
  },
  { id: 'voc_student_110', term: 'phoneme', termTr: 'ses birimi (fonem)', pronunciation: '/ˈfəʊ.niːm/', category: 'language', difficulty: 4,
    definitionEn: 'Smallest distinguishable unit of sound (e.g., /θ/ vs /t/).', definitionTr: 'En küçük ayırt edilebilir ses birimi (örn: /θ/ vs /t/).',
    examples: [{ en: 'Turkish speakers struggle with /θ/.', tr: 'Türkçe konuşanlar /θ/ ile zorlanır.' }],
    relatedTerms: ['minimal pair', 'pronunciation', 'IPA'],
  },

  // Industry vocabulary deep (10)
  { id: 'voc_student_111', term: 'codeshare', termTr: 'codeshare (kod paylaşımı)', pronunciation: '/ˈkəʊd.ʃeər/', category: 'industry', difficulty: 4,
    definitionEn: 'Agreement where one airline sells seats on another\'s flight.', definitionTr: 'Bir havayolunun başkasının uçuşunda koltuk satması anlaşması.',
    examples: [{ en: 'TK/UA codeshare.', tr: 'TK/UA codeshare.' }],
    relatedTerms: ['alliance', 'partnership', 'interline'],
  },
  { id: 'voc_student_112', term: 'alliance', termTr: 'havayolu ittifakı', pronunciation: '/əˈlaɪ.əns/', category: 'industry', difficulty: 3,
    definitionEn: 'Group of airlines (Star Alliance, Oneworld, SkyTeam) cooperating.', definitionTr: 'İşbirliği yapan havayolları grubu (Star Alliance, Oneworld, SkyTeam).',
    examples: [{ en: 'Turkish Airlines: Star Alliance.', tr: 'THY: Star Alliance.' }],
    relatedTerms: ['Star Alliance', 'codeshare', 'frequent flyer'],
  },
  { id: 'voc_student_113', term: 'Star Alliance', termTr: 'Star Alliance', pronunciation: '/stɑːr əˈlaɪ.əns/', category: 'industry', difficulty: 3,
    definitionEn: 'Largest airline alliance — 26 airlines including TK, UA, Lufthansa.', definitionTr: 'En büyük havayolu ittifakı — TK, UA, Lufthansa dahil 26 üye.',
    examples: [{ en: 'Star Alliance Gold benefits.', tr: 'Star Alliance Gold avantajları.' }],
    relatedTerms: ['alliance', 'codeshare', 'Oneworld'],
  },
  { id: 'voc_student_114', term: 'frequent flyer', termTr: 'sık uçan yolcu programı', pronunciation: '/ˈfriː.kwənt ˈflaɪ.ər/', category: 'industry', difficulty: 2,
    definitionEn: 'Loyalty program rewarding repeat passengers (Miles & Smiles).', definitionTr: 'Tekrar eden yolculara puan veren sadakat programı (Miles & Smiles).',
    examples: [{ en: 'Earn miles per flight.', tr: 'Uçuş başına mil kazan.' }],
    relatedTerms: ['Miles & Smiles', 'tier status', 'redemption'],
  },
  { id: 'voc_student_115', term: 'load factor', termTr: 'doluluk oranı', pronunciation: '/ləʊd ˈfæk.tər/', category: 'industry', difficulty: 4,
    definitionEn: 'Percentage of seats filled — key airline profitability metric.', definitionTr: 'Doldurulan koltuk yüzdesi — anahtar karlılık metriği.',
    examples: [{ en: 'TK load factor 82%.', tr: 'TK doluluk %82.' }],
    relatedTerms: ['RPK', 'ASK', 'yield'],
  },
  { id: 'voc_student_116', term: 'yield', termTr: 'getiri (yield)', pronunciation: '/jiːld/', category: 'industry', difficulty: 4,
    definitionEn: 'Revenue per passenger-mile — pricing performance indicator.', definitionTr: 'Yolcu-mil başına gelir — fiyatlama performans göstergesi.',
    examples: [{ en: 'Premium routes higher yield.', tr: 'Premium rotalar yüksek yield.' }],
    relatedTerms: ['RASM', 'revenue', 'pricing'],
  },
  { id: 'voc_student_117', term: 'RPK', termTr: 'RPK (gelir yolcu km)', pronunciation: '/ɑːr piː keɪ/', category: 'industry', difficulty: 5,
    definitionEn: 'Revenue Passenger Kilometers — passengers × distance flown.', definitionTr: 'Gelir Yolcu Kilometresi — yolcu × uçulan mesafe.',
    examples: [{ en: 'RPK measures airline output.', tr: 'RPK havayolu çıktısını ölçer.' }],
    relatedTerms: ['ASK', 'load factor', 'capacity'],
  },
  { id: 'voc_student_118', term: 'ASK', termTr: 'ASK (mevcut koltuk km)', pronunciation: '/eɪ es keɪ/', category: 'industry', difficulty: 5,
    definitionEn: 'Available Seat Kilometers — total seats × distance.', definitionTr: 'Mevcut Koltuk Kilometresi — toplam koltuk × mesafe.',
    examples: [{ en: 'ASK measures airline capacity.', tr: 'ASK havayolu kapasitesini ölçer.' }],
    relatedTerms: ['RPK', 'load factor', 'capacity'],
  },
  { id: 'voc_student_119', term: 'leasing', termTr: 'leasing (kiralama)', pronunciation: '/ˈliː.sɪŋ/', category: 'industry', difficulty: 3,
    definitionEn: 'Renting aircraft instead of buying — operating or finance lease.', definitionTr: 'Satın almak yerine uçak kiralamak — operating veya finance lease.',
    examples: [{ en: 'Aircraft leasing common.', tr: 'Uçak leasing yaygın.' }],
    relatedTerms: ['operating lease', 'finance lease', 'lessor'],
  },
  { id: 'voc_student_120', term: 'lessor', termTr: 'kiraya veren', pronunciation: '/ˈles.ɔː/', category: 'industry', difficulty: 4,
    definitionEn: 'Company owning aircraft and leasing them to airlines.', definitionTr: 'Uçak sahibi olup havayollarına kiralayan şirket.',
    examples: [{ en: 'AerCap, GECAS major lessors.', tr: 'AerCap, GECAS büyük lessor.' }],
    relatedTerms: ['leasing', 'lessee', 'aircraft finance'],
  },

  // Aviation math (10)
  { id: 'voc_student_121', term: 'mach number', termTr: 'mach sayısı', pronunciation: '/mɑːk ˈnʌm.bər/', category: 'physics', difficulty: 3,
    definitionEn: 'Aircraft speed as ratio of speed of sound (Mach 0.85 = 85% sonic).', definitionTr: 'Uçak hızının ses hızına oranı (Mach 0.85 = sesin %85\'i).',
    examples: [{ en: 'Cruise Mach 0.78.', tr: 'Cruise Mach 0.78.' }],
    relatedTerms: ['speed of sound', 'IAS', 'TAS'],
  },
  { id: 'voc_student_122', term: 'true airspeed', termTr: 'gerçek hava hızı (TAS)', pronunciation: '/truː ˈeə.spiːd/', category: 'physics', difficulty: 4,
    definitionEn: 'Actual aircraft speed through air mass.', definitionTr: 'Uçağın hava kütlesi içindeki gerçek hızı.',
    examples: [{ en: 'TAS at altitude > IAS.', tr: 'İrtifada TAS > IAS.' }],
    relatedTerms: ['IAS', 'mach', 'ground speed'],
  },
  { id: 'voc_student_123', term: 'indicated airspeed', termTr: 'gösterge hava hızı (IAS)', pronunciation: '/ˈɪn.dɪ.keɪ.tɪd ˈeə.spiːd/', category: 'physics', difficulty: 4,
    definitionEn: 'Speed shown on cockpit instrument — based on dynamic pressure.', definitionTr: 'Kokpit aletinde gösterilen hız — dinamik basınca dayalı.',
    examples: [{ en: 'IAS for V-speeds.', tr: 'V-speed\'ler için IAS.' }],
    relatedTerms: ['TAS', 'pitot tube', 'V1'],
  },
  { id: 'voc_student_124', term: 'ground speed', termTr: 'yer hızı', pronunciation: '/ɡraʊnd spiːd/', category: 'physics', difficulty: 3,
    definitionEn: 'Speed relative to ground — TAS ± wind component.', definitionTr: 'Yere göre hız — TAS ± rüzgar bileşeni.',
    examples: [{ en: 'GS = TAS + tailwind.', tr: 'GS = TAS + tailwind.' }],
    relatedTerms: ['TAS', 'wind', 'GPS'],
  },
  { id: 'voc_student_125', term: 'fuel burn', termTr: 'yakıt tüketimi', pronunciation: '/fjuːəl bɜːn/', category: 'physics', difficulty: 3,
    definitionEn: 'Rate of fuel consumption — typically lbs/hr or kg/hr.', definitionTr: 'Yakıt tüketim oranı — genelde lbs/saat veya kg/saat.',
    examples: [{ en: 'B737 burns 5000 lbs/hr.', tr: 'B737 saatte 5000 lbs yakar.' }],
    relatedTerms: ['fuel flow', 'specific range', 'efficiency'],
  },
  { id: 'voc_student_126', term: 'MTOW', termTr: 'MTOW (Maksimum Kalkış Ağırlığı)', pronunciation: '/em tiː əʊ ˈdʌb.əl.juː/', category: 'physics', difficulty: 4,
    definitionEn: 'Maximum Takeoff Weight — limit certified for takeoff.', definitionTr: 'Maksimum Kalkış Ağırlığı — kalkış için sertifikalı limit.',
    examples: [{ en: 'B737-800 MTOW 79T.', tr: 'B737-800 MTOW 79 ton.' }],
    relatedTerms: ['MLW', 'ZFW', 'payload'],
  },
  { id: 'voc_student_127', term: 'ZFW', termTr: 'ZFW (Sıfır Yakıt Ağırlığı)', pronunciation: '/ˈzɪər.əʊ fjuːəl weɪt/', category: 'physics', difficulty: 4,
    definitionEn: 'Zero Fuel Weight — aircraft + payload, no fuel.', definitionTr: 'Sıfır Yakıt Ağırlığı — uçak + yük, yakıtsız.',
    examples: [{ en: 'ZFW + fuel = takeoff weight.', tr: 'ZFW + yakıt = kalkış ağırlığı.' }],
    relatedTerms: ['MTOW', 'payload', 'OEW'],
  },
  { id: 'voc_student_128', term: 'OEW', termTr: 'OEW (Boş İşletme Ağırlığı)', pronunciation: '/əʊ iː ˈdʌb.əl.juː/', category: 'physics', difficulty: 5,
    definitionEn: 'Operating Empty Weight — aircraft with crew, no payload, no fuel.', definitionTr: 'İşletme Boş Ağırlığı — ekiple, yüksüz, yakıtsız uçak.',
    examples: [{ en: 'OEW B737 ~41T.', tr: 'B737 OEW ~41 ton.' }],
    relatedTerms: ['ZFW', 'payload', 'BEW'],
  },
  { id: 'voc_student_129', term: 'payload', termTr: 'yük (payload)', pronunciation: '/ˈpeɪ.ləʊd/', category: 'physics', difficulty: 3,
    definitionEn: 'Revenue load — passengers + baggage + cargo.', definitionTr: 'Gelir yükü — yolcu + bagaj + kargo.',
    examples: [{ en: 'Payload 20T B737.', tr: 'B737 payload 20 ton.' }],
    relatedTerms: ['revenue', 'ZFW', 'cargo'],
  },
  { id: 'voc_student_130', term: 'center of gravity', termTr: 'ağırlık merkezi (CG)', pronunciation: '/ˈsen.tər əv ˈɡræv.ə.ti/', category: 'physics', difficulty: 4,
    definitionEn: 'Point where aircraft weight balances — must stay within limits.', definitionTr: 'Uçak ağırlığının dengelendiği nokta — limit içinde kalmalı.',
    examples: [{ en: 'CG forward limit.', tr: 'CG ön limit.' }],
    relatedTerms: ['weight and balance', 'MAC', 'trim'],
  },

  // Crisis & advanced career (10)
  { id: 'voc_student_131', term: 'crew resource management', termTr: 'mürettebat kaynak yönetimi (CRM)', pronunciation: '/kruː rɪˈsɔːs ˈmæn.ɪdʒ.mənt/', category: 'crisis', difficulty: 4,
    definitionEn: 'Non-technical skills (communication, leadership) for safety.', definitionTr: 'Emniyet için teknik dışı beceriler (iletişim, liderlik).',
    examples: [{ en: 'CRM training annual.', tr: 'CRM eğitimi yıllık.' }],
    relatedTerms: ['CRM', 'human factors', 'leadership'],
  },
  { id: 'voc_student_132', term: 'threat and error management', termTr: 'tehdit ve hata yönetimi (TEM)', pronunciation: '/θret ænd ˈer.ər ˈmæn.ɪdʒ.mənt/', category: 'crisis', difficulty: 5,
    definitionEn: 'Framework recognizing threats, managing errors, recovering safely.', definitionTr: 'Tehditleri tanı, hataları yönet, güvenle kurtul çerçevesi.',
    examples: [{ en: 'TEM core CRM concept.', tr: 'TEM ana CRM kavramı.' }],
    relatedTerms: ['CRM', 'error chain', 'recovery'],
  },
  { id: 'voc_student_133', term: 'error chain', termTr: 'hata zinciri', pronunciation: '/ˈer.ər tʃeɪn/', category: 'crisis', difficulty: 4,
    definitionEn: 'Sequence of errors that, uncorrected, leads to accident.', definitionTr: 'Düzeltilmezse kazaya yol açan hata dizisi.',
    examples: [{ en: 'Break error chain early.', tr: 'Hata zincirini erken kır.' }],
    relatedTerms: ['Swiss cheese model', 'accident chain', 'TEM'],
  },
  { id: 'voc_student_134', term: 'Swiss cheese model', termTr: 'İsviçre peyniri modeli', pronunciation: '/swɪs tʃiːz ˈmɒd.əl/', category: 'crisis', difficulty: 5,
    definitionEn: 'Reason\'s accident model — multiple defenses align to allow accident.', definitionTr: 'Reason\'ın kaza modeli — birden çok savunma kazaya izin verir.',
    examples: [{ en: 'Swiss cheese: holes align.', tr: 'İsviçre peyniri: delikler hizalanır.' }],
    relatedTerms: ['error chain', 'defenses', 'accident'],
  },
  { id: 'voc_student_135', term: 'just culture', termTr: 'adil kültür', pronunciation: '/dʒʌst ˈkʌl.tʃər/', category: 'safety', difficulty: 4,
    definitionEn: 'Safety culture treating honest errors without blame, only sanctioning recklessness.', definitionTr: 'Dürüst hataları suçlamadan ele alan, sadece umursamazlığı cezalandıran emniyet kültürü.',
    examples: [{ en: 'Just culture promotes reporting.', tr: 'Adil kültür raporlamayı teşvik eder.' }],
    relatedTerms: ['safety culture', 'blame-free', 'reporting'],
  },
  { id: 'voc_student_136', term: 'safety reporting', termTr: 'emniyet raporlama', pronunciation: '/ˈseɪf.ti rɪˈpɔːt.ɪŋ/', category: 'safety', difficulty: 3,
    definitionEn: 'Anonymous reporting of hazards/errors for organizational learning.', definitionTr: 'Organizasyonel öğrenme için tehlike/hata anonim raporlama.',
    examples: [{ en: 'Safety report confidential.', tr: 'Emniyet raporu gizli.' }],
    relatedTerms: ['just culture', 'ASRS', 'voluntary'],
  },
  { id: 'voc_student_137', term: 'investigation', termTr: 'kaza soruşturması', pronunciation: '/ɪnˌves.tɪˈɡeɪ.ʃən/', category: 'safety', difficulty: 3,
    definitionEn: 'Process of determining accident causes for prevention.', definitionTr: 'Önleme için kaza sebeplerini belirleme süreci.',
    examples: [{ en: 'NTSB investigates US accidents.', tr: 'NTSB ABD kazalarını soruşturur.' }],
    relatedTerms: ['NTSB', 'AAIB', 'cause analysis'],
  },
  { id: 'voc_student_138', term: 'flight data recorder', termTr: 'uçuş veri kayıt cihazı (FDR)', pronunciation: '/flaɪt ˈdeɪ.tə rɪˈkɔː.dər/', category: 'safety', difficulty: 4,
    definitionEn: 'Black box recording flight parameters for investigation.', definitionTr: 'Soruşturma için uçuş parametrelerini kaydeden kara kutu.',
    examples: [{ en: 'FDR records 25+ hours.', tr: 'FDR 25+ saat kaydeder.' }],
    relatedTerms: ['CVR', 'black box', 'investigation'],
  },
  { id: 'voc_student_139', term: 'specialization', termTr: 'uzmanlaşma', pronunciation: '/ˌspeʃ.əl.aɪˈzeɪ.ʃən/', category: 'career', difficulty: 3,
    definitionEn: 'Focusing career in specific area (cargo, training, simulator).', definitionTr: 'Belirli alanda kariyere odaklanma (kargo, eğitim, simülatör).',
    examples: [{ en: 'Specialization: training pilot.', tr: 'Uzmanlaşma: eğitim pilotu.' }],
    relatedTerms: ['career path', 'instructor', 'expert'],
  },
  { id: 'voc_student_140', term: 'mentorship', termTr: 'mentorluk', pronunciation: '/ˈmen.tə.ʃɪp/', category: 'career', difficulty: 3,
    definitionEn: 'Guidance from experienced professional for career development.', definitionTr: 'Kariyer gelişimi için deneyimli profesyonelden rehberlik.',
    examples: [{ en: 'Find a mentor in industry.', tr: 'Sektörde mentor bul.' }],
    relatedTerms: ['mentor', 'career', 'networking'],
  },
];
