/**
 * Havacılık Öğrencisi vocabulary seed — Faz 1.
 * 60 terim: temel havacılık, sektör genel, kariyer, üniversite, sınavlar.
 */
import type { VocabularyTerm } from './pilotVocab';

export const STUDENT_VOCAB_FAZ1: VocabularyTerm[] = [
  // ===== AVIATION FUNDAMENTALS (12) =====
  { id: 'voc_student_001', term: 'aviation', termTr: 'havacılık', pronunciation: '/ˌeɪ.viˈeɪ.ʃən/', category: 'fundamentals', difficulty: 1,
    definitionEn: 'The practice and industry of designing, producing, operating aircraft.',
    definitionTr: 'Uçak tasarlama, üretme ve işletme pratiği ve endüstrisi.',
    examples: [
      { en: 'Aviation industry employs millions.', tr: 'Havacılık sektörü milyonları istihdam eder.' },
      { en: 'Civil and military aviation.', tr: 'Sivil ve askeri havacılık.' },
    ],
    relatedTerms: ['aircraft', 'industry', 'civil aviation'],
  },
  { id: 'voc_student_002', term: 'aircraft', termTr: 'uçak / hava aracı', pronunciation: '/ˈeə.krɑːft/', category: 'fundamentals', difficulty: 1,
    definitionEn: 'A vehicle capable of flight, including airplanes, helicopters, gliders.',
    definitionTr: 'Uçabilen araç — uçak, helikopter, planör dahil.',
    examples: [
      { en: 'Fixed-wing vs rotary-wing aircraft.', tr: 'Sabit kanatlı ve döner kanatlı uçaklar.' },
      { en: 'Aircraft inspected pre-flight.', tr: 'Uçak uçuş öncesi muayene.' },
    ],
    relatedTerms: ['airplane', 'helicopter', 'glider'],
  },
  { id: 'voc_student_003', term: 'airline', termTr: 'havayolu şirketi', pronunciation: '/ˈeə.laɪn/', category: 'industry', difficulty: 1,
    definitionEn: 'A company that provides air transport services.',
    definitionTr: 'Hava taşımacılık hizmeti sunan şirket.',
    examples: [
      { en: 'Turkish Airlines is a flag carrier.', tr: 'Türk Hava Yolları bayrak taşıyıcısı.' },
      { en: 'Low-cost vs full-service airline.', tr: 'Low-cost ve full-service havayolu.' },
    ],
    relatedTerms: ['flag carrier', 'low-cost', 'fleet'],
  },
  { id: 'voc_student_004', term: 'airport', termTr: 'havalimanı', pronunciation: '/ˈeə.pɔːt/', category: 'fundamentals', difficulty: 1,
    definitionEn: 'A facility where aircraft take off, land, and undergo ground operations.',
    definitionTr: 'Uçakların kalktığı, indiği ve yer hizmeti gördüğü tesis.',
    examples: [
      { en: 'Istanbul Airport (IST) is a hub.', tr: 'İstanbul Havalimanı (IST) bir hub.' },
      { en: 'International airport with customs.', tr: 'Gümrüklü uluslararası havalimanı.' },
    ],
    relatedTerms: ['terminal', 'runway', 'apron'],
  },
  { id: 'voc_student_005', term: 'runway', termTr: 'pist', pronunciation: '/ˈrʌn.weɪ/', category: 'fundamentals', difficulty: 1,
    definitionEn: 'A long strip of paved surface where aircraft take off and land.',
    definitionTr: 'Uçakların kalkıp indiği uzun asfalt alan.',
    examples: [
      { en: 'Runway 27 means 270° heading.', tr: 'Pist 27 = 270° heading.' },
      { en: 'Runway lights for night ops.', tr: 'Gece operasyonu için pist ışıkları.' },
    ],
    relatedTerms: ['taxiway', 'threshold', 'apron'],
  },
  { id: 'voc_student_006', term: 'pilot', termTr: 'pilot', pronunciation: '/ˈpaɪ.lət/', category: 'careers', difficulty: 1,
    definitionEn: 'A person trained and licensed to fly an aircraft.',
    definitionTr: 'Uçak uçurmak için eğitimli ve lisanslı kişi.',
    examples: [
      { en: 'Captain (PIC) and first officer.', tr: 'Kaptan (PIC) ve yardımcı pilot.' },
      { en: 'Type rating required for jets.', tr: 'Jetler için type rating gerekli.' },
    ],
    relatedTerms: ['captain', 'first officer', 'PIC', 'type rating'],
  },
  { id: 'voc_student_007', term: 'cabin crew', termTr: 'kabin ekibi', pronunciation: '/ˈkæb.ɪn kruː/', category: 'careers', difficulty: 1,
    definitionEn: 'Flight attendants who serve passengers and ensure safety on board.',
    definitionTr: 'Yolculara hizmet eden ve kabin emniyetini sağlayan hostes/stewardlar.',
    examples: [
      { en: 'Cabin crew prepares for departure.', tr: 'Kabin ekibi kalkışa hazırlanır.' },
      { en: 'Multi-lingual cabin crew preferred.', tr: 'Çok dilli kabin ekibi tercih.' },
    ],
    relatedTerms: ['flight attendant', 'purser', 'steward'],
  },
  { id: 'voc_student_008', term: 'maintenance technician', termTr: 'bakım teknisyeni', pronunciation: '/ˈmeɪn.tən.əns tekˈnɪʃ.ən/', category: 'careers', difficulty: 2,
    definitionEn: 'Engineer who maintains, inspects, and repairs aircraft.',
    definitionTr: 'Uçakları bakım, muayene ve tamir eden mühendis.',
    examples: [
      { en: 'B1 license: mechanical work.', tr: 'B1 lisansı: mekanik iş.' },
      { en: 'B2 license: avionics.', tr: 'B2 lisansı: avionik.' },
    ],
    relatedTerms: ['mechanic', 'engineer', 'B1', 'B2'],
  },
  { id: 'voc_student_009', term: 'air traffic control', termTr: 'hava trafik kontrol (ATC)', pronunciation: '/eər ˈtræf.ɪk kənˈtrəʊl/', category: 'industry', difficulty: 2,
    definitionEn: 'Service guiding aircraft on the ground and in the air for safe operations.',
    definitionTr: 'Yerde ve havada uçakları güvenli operasyon için yönlendiren hizmet.',
    examples: [
      { en: 'ATC tower controls airport traffic.', tr: 'ATC kulesi havalimanı trafiğini kontrol.' },
      { en: 'En-route control at FL350.', tr: 'FL350\'de en-route kontrol.' },
    ],
    relatedTerms: ['ATC', 'tower', 'controller', 'radar'],
  },
  { id: 'voc_student_010', term: 'flight attendant', termTr: 'hostes / steward', pronunciation: '/flaɪt əˈten.dənt/', category: 'careers', difficulty: 1,
    definitionEn: 'Cabin crew member trained in safety and customer service.',
    definitionTr: 'Emniyet ve müşteri hizmeti eğitimli kabin ekibi üyesi.',
    examples: [
      { en: 'Apply for flight attendant position.', tr: 'Hostes pozisyonuna başvur.' },
      { en: '6-week training program.', tr: '6 haftalık eğitim programı.' },
    ],
    relatedTerms: ['cabin crew', 'steward', 'purser'],
  },
  { id: 'voc_student_011', term: 'fleet', termTr: 'filo', pronunciation: '/fliːt/', category: 'industry', difficulty: 2,
    definitionEn: 'All aircraft owned/operated by an airline.',
    definitionTr: 'Bir havayolunun sahip olduğu/işlettiği tüm uçaklar.',
    examples: [
      { en: 'THY fleet 400+ aircraft.', tr: 'THY filosu 400+ uçak.' },
      { en: 'Mixed fleet: Airbus + Boeing.', tr: 'Karma filo: Airbus + Boeing.' },
    ],
    relatedTerms: ['airline', 'aircraft', 'capacity'],
  },
  { id: 'voc_student_012', term: 'hub', termTr: 'hub (merkez havalimanı)', pronunciation: '/hʌb/', category: 'industry', difficulty: 2,
    definitionEn: 'Major connection airport for an airline\'s network.',
    definitionTr: 'Bir havayolu ağının ana bağlantı havalimanı.',
    examples: [
      { en: 'Istanbul (IST) is THY\'s hub.', tr: 'İstanbul (IST) THY\'nin hub\'ı.' },
      { en: 'Hub-and-spoke model.', tr: 'Hub-and-spoke modeli.' },
    ],
    relatedTerms: ['flag carrier', 'connection', 'network'],
  },

  // ===== UNIVERSITY & EDUCATION (10) =====
  { id: 'voc_student_013', term: 'university', termTr: 'üniversite', pronunciation: '/ˌjuː.nɪˈvɜː.sə.ti/', category: 'education', difficulty: 1,
    definitionEn: 'Higher education institution offering bachelor\'s/master\'s degrees.',
    definitionTr: 'Lisans/yüksek lisans veren yükseköğretim kurumu.',
    examples: [
      { en: 'THK University offers aviation programs.', tr: 'THK Üniversitesi havacılık programları sunar.' },
      { en: 'Apply via YKS exam.', tr: 'YKS sınavıyla başvur.' },
    ],
    relatedTerms: ['college', 'YKS', 'bachelor\'s degree'],
  },
  { id: 'voc_student_014', term: 'YKS', termTr: 'YKS (üniversite sınavı)', pronunciation: '/waɪ keɪ es/', category: 'exams', difficulty: 2,
    definitionEn: 'Turkish university entrance exam.',
    definitionTr: 'Türkiye üniversite giriş sınavı.',
    examples: [
      { en: 'YKS held annually in June.', tr: 'YKS her Haziran düzenlenir.' },
      { en: 'YKS score determines placement.', tr: 'YKS puanı yerleştirmeyi belirler.' },
    ],
    relatedTerms: ['TYT', 'AYT', 'university'],
  },
  { id: 'voc_student_015', term: 'aviation faculty', termTr: 'havacılık fakültesi', pronunciation: '/ˌeɪ.viˈeɪ.ʃən ˈfæk.əl.ti/', category: 'education', difficulty: 2,
    definitionEn: 'University department dedicated to aviation programs.',
    definitionTr: 'Havacılık programlarına ayrılmış üniversite bölümü.',
    examples: [
      { en: 'Aviation faculty has 4-year programs.', tr: 'Havacılık fakültesi 4 yıllık programlar.' },
      { en: 'Pilotage, ATC, management majors.', tr: 'Pilotaj, ATC, yönetim bölümleri.' },
    ],
    relatedTerms: ['pilotage', 'aviation management', 'ATC'],
  },
  { id: 'voc_student_016', term: 'pilotage', termTr: 'pilotaj', pronunciation: '/ˈpaɪ.lə.tɪdʒ/', category: 'education', difficulty: 2,
    definitionEn: 'University program training future commercial pilots.',
    definitionTr: 'Geleceğin ticari pilotlarını yetiştiren üniversite programı.',
    examples: [
      { en: 'Pilotage: 4-year theoretical + practical.', tr: 'Pilotaj: 4 yıl teorik + pratik.' },
      { en: 'PPL during program.', tr: 'Program boyunca PPL.' },
    ],
    relatedTerms: ['pilot training', 'PPL', 'CPL', 'ATPL'],
  },
  { id: 'voc_student_017', term: 'PPL', termTr: 'PPL (özel pilot lisansı)', pronunciation: '/piː piː el/', category: 'licenses', difficulty: 2,
    definitionEn: 'Private Pilot License — first level pilot license.',
    definitionTr: 'Özel Pilot Lisansı — ilk seviye pilot lisansı.',
    examples: [
      { en: 'PPL minimum 45 flight hours.', tr: 'PPL minimum 45 uçuş saati.' },
      { en: 'PPL only for non-commercial.', tr: 'PPL sadece ticari olmayan.' },
    ],
    relatedTerms: ['CPL', 'ATPL', 'flight training'],
  },
  { id: 'voc_student_018', term: 'CPL', termTr: 'CPL (ticari pilot lisansı)', pronunciation: '/siː piː el/', category: 'licenses', difficulty: 2,
    definitionEn: 'Commercial Pilot License — allows paid pilot work.',
    definitionTr: 'Ticari Pilot Lisansı — ücretli pilot çalışmaya izin verir.',
    examples: [
      { en: 'CPL minimum 200 flight hours.', tr: 'CPL minimum 200 uçuş saati.' },
      { en: 'CPL with IR for IFR ops.', tr: 'IFR ops için CPL+IR.' },
    ],
    relatedTerms: ['PPL', 'ATPL', 'IR', 'commercial'],
  },
  { id: 'voc_student_019', term: 'ATPL', termTr: 'ATPL (havayolu pilot lisansı)', pronunciation: '/eɪ tiː piː el/', category: 'licenses', difficulty: 3,
    definitionEn: 'Airline Transport Pilot License — required to be captain on commercial flights.',
    definitionTr: 'Havayolu Taşımacılık Pilot Lisansı — ticari uçuşlarda kaptan olmak için gerekli.',
    examples: [
      { en: 'ATPL minimum 1500 hours.', tr: 'ATPL minimum 1500 saat.' },
      { en: 'Frozen ATPL: theory only.', tr: 'Frozen ATPL: sadece teori.' },
    ],
    relatedTerms: ['CPL', 'frozen ATPL', 'captain'],
  },
  { id: 'voc_student_020', term: 'flight school', termTr: 'uçuş okulu', pronunciation: '/flaɪt skuːl/', category: 'education', difficulty: 2,
    definitionEn: 'Institution offering practical pilot training.',
    definitionTr: 'Pratik pilot eğitimi sunan kurum.',
    examples: [
      { en: 'Approved Training Organization (ATO).', tr: 'Onaylı Eğitim Organizasyonu (ATO).' },
      { en: 'Flight school + university combo.', tr: 'Uçuş okulu + üniversite kombo.' },
    ],
    relatedTerms: ['ATO', 'instructor', 'flight hours'],
  },
  { id: 'voc_student_021', term: 'simulator', termTr: 'simülatör', pronunciation: '/ˈsɪm.jə.leɪ.tər/', category: 'training', difficulty: 2,
    definitionEn: 'Ground-based training device replicating aircraft systems.',
    definitionTr: 'Uçak sistemlerini taklit eden yer eğitim cihazı.',
    examples: [
      { en: 'Full motion simulator.', tr: 'Tam hareketli simülatör.' },
      { en: 'Sim training mandatory before line.', tr: 'Hat öncesi sim eğitimi zorunlu.' },
    ],
    relatedTerms: ['FFS', 'FNPT', 'training device'],
  },
  { id: 'voc_student_022', term: 'theoretical exam', termTr: 'teorik sınav', pronunciation: '/ˌθɪə.rəˈtɪ.kəl ɪɡˈzæm/', category: 'exams', difficulty: 2,
    definitionEn: 'Written test on aviation theory subjects (meteorology, navigation, etc.).',
    definitionTr: 'Havacılık teori konularında yazılı sınav (meteoroloji, navigasyon vb.).',
    examples: [
      { en: '14 ATPL theory subjects.', tr: '14 ATPL teori konusu.' },
      { en: 'Pass mark: 75%.', tr: 'Geçme notu: %75.' },
    ],
    relatedTerms: ['SHGM exam', 'EASA Part-FCL', 'multiple choice'],
  },

  // ===== EXAMS & CERTIFICATIONS (10) =====
  { id: 'voc_student_023', term: 'ICAO Level 4', termTr: 'ICAO Seviye 4', pronunciation: '/ˌaɪ.keɪ.eɪ.əʊ ˈlev.əl fɔː/', category: 'exams', difficulty: 3,
    definitionEn: 'Operational level English proficiency required for international pilots/ATC.',
    definitionTr: 'Uluslararası pilot/ATC için gerekli operasyonel seviye İngilizce yeterliliği.',
    examples: [
      { en: 'ICAO 4 = minimum operational.', tr: 'ICAO 4 = minimum operasyonel.' },
      { en: 'Renewable every 3-6 years.', tr: '3-6 yılda bir yenilenir.' },
    ],
    icaoReference: 'ICAO Annex 1, Doc 9835',
    relatedTerms: ['English proficiency', 'ICAO 5', 'ICAO 6'],
  },
  { id: 'voc_student_024', term: 'ICAO Level 5', termTr: 'ICAO Seviye 5 (Extended)', pronunciation: '/ˌaɪ.keɪ.eɪ.əʊ ˈlev.əl faɪv/', category: 'exams', difficulty: 4,
    definitionEn: 'Extended level English — advanced fluency and complex topic discussion.',
    definitionTr: 'İleri seviye İngilizce — akıcılık ve karmaşık konu tartışması.',
    examples: [
      { en: 'ICAO 5 valid for 6 years.', tr: 'ICAO 5 6 yıl geçerli.' },
      { en: 'Higher pay grades require ICAO 5+.', tr: 'Yüksek ücret grupları ICAO 5+ gerektirir.' },
    ],
    relatedTerms: ['ICAO 4', 'ICAO 6', 'extended'],
  },
  { id: 'voc_student_025', term: 'SHGM', termTr: 'SHGM (Sivil Havacılık Genel Müdürlüğü)', pronunciation: '/es eɪtʃ dʒiː em/', category: 'authority', difficulty: 3,
    definitionEn: 'Turkish Directorate General of Civil Aviation — regulatory authority.',
    definitionTr: 'Türkiye Sivil Havacılık Genel Müdürlüğü — düzenleyici otorite.',
    examples: [
      { en: 'SHGM issues licenses.', tr: 'SHGM lisansları düzenler.' },
      { en: 'SHGM English exam.', tr: 'SHGM İngilizce sınavı.' },
    ],
    relatedTerms: ['DGCA', 'EASA', 'FAA'],
  },
  { id: 'voc_student_026', term: 'EASA', termTr: 'EASA (Avrupa Havacılık Emniyet Ajansı)', pronunciation: '/ˈiː.zə/', category: 'authority', difficulty: 3,
    definitionEn: 'European Union Aviation Safety Agency — regulator.',
    definitionTr: 'Avrupa Birliği Havacılık Emniyet Ajansı — düzenleyici.',
    examples: [
      { en: 'EASA Part-FCL covers pilot licensing.', tr: 'EASA Part-FCL pilot lisanslama.' },
      { en: 'Turkey aligned with EASA standards.', tr: 'Türkiye EASA standartlarıyla uyumlu.' },
    ],
    relatedTerms: ['FAA', 'ICAO', 'SHGM'],
  },
  { id: 'voc_student_027', term: 'FAA', termTr: 'FAA (ABD Federal Havacılık İdaresi)', pronunciation: '/ef eɪ eɪ/', category: 'authority', difficulty: 3,
    definitionEn: 'Federal Aviation Administration — US regulator.',
    definitionTr: 'Federal Havacılık İdaresi — ABD düzenleyicisi.',
    examples: [
      { en: 'FAA regulates US aviation.', tr: 'FAA ABD havacılığını düzenler.' },
      { en: 'FAA Form 8130-3.', tr: 'FAA Form 8130-3.' },
    ],
    relatedTerms: ['EASA', 'ICAO', 'CAA'],
  },
  { id: 'voc_student_028', term: 'TOEFL', termTr: 'TOEFL (İngilizce sınavı)', pronunciation: '/ˈtəʊ.fəl/', category: 'exams', difficulty: 2,
    definitionEn: 'Test of English as a Foreign Language — international English exam.',
    definitionTr: 'Test of English as a Foreign Language — uluslararası İngilizce sınavı.',
    examples: [
      { en: 'TOEFL iBT max 120.', tr: 'TOEFL iBT maksimum 120.' },
      { en: 'Score 80+ for university.', tr: 'Üniversite için 80+.' },
    ],
    relatedTerms: ['IELTS', 'YDS', 'English proficiency'],
  },
  { id: 'voc_student_029', term: 'IELTS', termTr: 'IELTS', pronunciation: '/ˈaɪ.elts/', category: 'exams', difficulty: 2,
    definitionEn: 'International English Language Testing System.',
    definitionTr: 'Uluslararası İngilizce Dil Test Sistemi.',
    examples: [
      { en: 'IELTS Academic vs General.', tr: 'IELTS Academic ve General.' },
      { en: 'Score 6.5+ for most universities.', tr: 'Çoğu üniversite için 6.5+.' },
    ],
    relatedTerms: ['TOEFL', 'YDS', 'English proficiency'],
  },
  { id: 'voc_student_030', term: 'YDS', termTr: 'YDS (Yabancı Dil Sınavı)', pronunciation: '/waɪ diː es/', category: 'exams', difficulty: 2,
    definitionEn: 'Turkish Foreign Language Exam — required for academic positions.',
    definitionTr: 'Yabancı Dil Sınavı — akademik pozisyonlar için gerekli.',
    examples: [
      { en: 'YDS Aviation specialty exam.', tr: 'YDS Havacılık branş sınavı.' },
      { en: 'Score 70+ for proficiency.', tr: 'Yeterlilik için 70+.' },
    ],
    relatedTerms: ['e-YDS', 'YÖKDİL', 'TOEFL'],
  },
  { id: 'voc_student_031', term: 'medical certificate', termTr: 'tıbbi sertifika', pronunciation: '/ˈmed.ɪ.kəl səˈtɪf.ɪ.kət/', category: 'certifications', difficulty: 2,
    definitionEn: 'Medical fitness document required for pilots and ATC.',
    definitionTr: 'Pilot ve ATC için gerekli tıbbi uygunluk belgesi.',
    examples: [
      { en: 'Class 1 medical for ATPL.', tr: 'ATPL için Class 1 medical.' },
      { en: 'Annual medical exam.', tr: 'Yıllık tıbbi muayene.' },
    ],
    relatedTerms: ['Class 1', 'Class 2', 'aeromedical'],
  },
  { id: 'voc_student_032', term: 'background check', termTr: 'sicil kontrolü', pronunciation: '/ˈbæk.ɡraʊnd tʃek/', category: 'requirements', difficulty: 2,
    definitionEn: 'Investigation of an applicant\'s criminal/work history.',
    definitionTr: 'Bir adayın suç/iş geçmişinin araştırılması.',
    examples: [
      { en: 'Clean background required.', tr: 'Temiz sicil gerekli.' },
      { en: 'Aviation security check.', tr: 'Havacılık güvenlik kontrolü.' },
    ],
    relatedTerms: ['security clearance', 'clean record', 'aviation security'],
  },

  // ===== CAREER (10) =====
  { id: 'voc_student_033', term: 'internship', termTr: 'staj', pronunciation: '/ˈɪn.tɜːn.ʃɪp/', category: 'career', difficulty: 1,
    definitionEn: 'Temporary work program providing practical experience.',
    definitionTr: 'Pratik deneyim sağlayan geçici çalışma programı.',
    examples: [
      { en: 'THY Tech summer internship.', tr: 'THY Tech yaz stajı.' },
      { en: 'Apply with CV + transcript.', tr: 'CV + transkript ile başvur.' },
    ],
    relatedTerms: ['placement', 'practical training', 'CV'],
  },
  { id: 'voc_student_034', term: 'CV', termTr: 'CV / özgeçmiş', pronunciation: '/siː viː/', category: 'career', difficulty: 1,
    definitionEn: 'Curriculum Vitae — document summarizing education and experience.',
    definitionTr: 'Eğitim ve deneyim özeti belgesi.',
    examples: [
      { en: '1-page CV preferred for fresh grads.', tr: 'Yeni mezunlar için 1 sayfa CV tercih.' },
      { en: 'Tailor CV to each application.', tr: 'CV\'yi her başvuruya uyarla.' },
    ],
    relatedTerms: ['resume', 'cover letter', 'application'],
  },
  { id: 'voc_student_035', term: 'cover letter', termTr: 'ön yazı', pronunciation: '/ˈkʌv.ər ˈlet.ər/', category: 'career', difficulty: 2,
    definitionEn: 'Letter accompanying CV explaining motivation and fit.',
    definitionTr: 'CV ile birlikte gönderilen, motivasyon ve uyumu açıklayan mektup.',
    examples: [
      { en: 'Personalize cover letter.', tr: 'Ön yazıyı kişiselleştir.' },
      { en: 'Show passion for aviation.', tr: 'Havacılığa tutkunu göster.' },
    ],
    relatedTerms: ['CV', 'application', 'motivation'],
  },
  { id: 'voc_student_036', term: 'interview', termTr: 'mülakat', pronunciation: '/ˈɪn.tə.vjuː/', category: 'career', difficulty: 1,
    definitionEn: 'Formal meeting evaluating a candidate for a position.',
    definitionTr: 'Bir aday için pozisyon değerlendirme resmi görüşmesi.',
    examples: [
      { en: 'THY 3-stage interview.', tr: 'THY 3 aşamalı mülakat.' },
      { en: 'English interview common.', tr: 'İngilizce mülakat yaygın.' },
    ],
    relatedTerms: ['HR interview', 'technical interview', 'group interview'],
  },
  { id: 'voc_student_037', term: 'assessment center', termTr: 'değerlendirme merkezi', pronunciation: '/əˈses.mənt ˈsen.tər/', category: 'career', difficulty: 3,
    definitionEn: 'Day-long evaluation with multiple exercises.',
    definitionTr: 'Birden çok egzersizli gün boyu değerlendirme.',
    examples: [
      { en: 'Group exercise + role-play + interview.', tr: 'Grup egzersizi + rol-play + mülakat.' },
      { en: 'Common for cabin crew.', tr: 'Kabin ekibi için yaygın.' },
    ],
    relatedTerms: ['group exercise', 'role-play', 'final interview'],
  },
  { id: 'voc_student_038', term: 'group exercise', termTr: 'grup egzersizi', pronunciation: '/ɡruːp ˈek.sə.saɪz/', category: 'career', difficulty: 3,
    definitionEn: 'Team activity testing leadership and collaboration.',
    definitionTr: 'Liderlik ve işbirliğini test eden takım aktivitesi.',
    examples: [
      { en: '6 candidates solve a scenario.', tr: '6 aday bir senaryo çözer.' },
      { en: 'Show leadership without dominating.', tr: 'Baskın olmadan liderlik göster.' },
    ],
    relatedTerms: ['assessment center', 'role-play', 'teamwork'],
  },
  { id: 'voc_student_039', term: 'STAR method', termTr: 'STAR yöntemi', pronunciation: '/stɑː ˈmeθ.əd/', category: 'career', difficulty: 3,
    definitionEn: 'Interview technique: Situation, Task, Action, Result.',
    definitionTr: 'Mülakat tekniği: Durum, Görev, Aksiyon, Sonuç.',
    examples: [
      { en: 'Use STAR for behavioral questions.', tr: 'Davranışsal sorular için STAR kullan.' },
      { en: '"Tell me about a conflict..."', tr: '"Bir çatışmadan bahset..."' },
    ],
    relatedTerms: ['behavioral question', 'interview', 'competency'],
  },
  { id: 'voc_student_040', term: 'behavioral question', termTr: 'davranışsal soru', pronunciation: '/bɪˈheɪ.vjə.rəl ˈkwes.tʃən/', category: 'career', difficulty: 3,
    definitionEn: 'Question asking about past experiences to predict future behavior.',
    definitionTr: 'Geleceği tahmin için geçmiş deneyim soran soru.',
    examples: [
      { en: '"Tell me when you handled conflict."', tr: '"Çatışmayı yönettiğin zamanı anlat."' },
      { en: 'Answer with STAR.', tr: 'STAR ile cevap ver.' },
    ],
    relatedTerms: ['STAR', 'competency', 'past experience'],
  },
  { id: 'voc_student_041', term: 'competency', termTr: 'yetkinlik', pronunciation: '/ˈkɒm.pɪ.tən.si/', category: 'career', difficulty: 3,
    definitionEn: 'Skill or behavior required for successful job performance.',
    definitionTr: 'Başarılı iş performansı için gerekli beceri/davranış.',
    examples: [
      { en: 'Teamwork and adaptability competencies.', tr: 'Takım çalışması ve uyum yetkinlikleri.' },
      { en: 'Competency-based interview.', tr: 'Yetkinlik bazlı mülakat.' },
    ],
    relatedTerms: ['skill', 'soft skill', 'hard skill'],
  },
  { id: 'voc_student_042', term: 'salary expectation', termTr: 'beklenen maaş', pronunciation: '/ˈsæl.ər.i ˌek.spekˈteɪ.ʃən/', category: 'career', difficulty: 2,
    definitionEn: 'The amount candidate expects to earn.',
    definitionTr: 'Adayın kazanmayı beklediği tutar.',
    examples: [
      { en: 'Research industry standards first.', tr: 'Önce sektör standartlarını araştır.' },
      { en: 'Provide a range, not a fixed number.', tr: 'Sabit sayı değil aralık ver.' },
    ],
    relatedTerms: ['negotiation', 'benefits', 'package'],
  },

  // ===== SECTOR & ECOSYSTEM (8) =====
  { id: 'voc_student_043', term: 'flag carrier', termTr: 'bayrak taşıyıcı', pronunciation: '/flæɡ ˈkær.i.ər/', category: 'industry', difficulty: 2,
    definitionEn: 'National airline representing a country internationally.',
    definitionTr: 'Bir ülkeyi uluslararası temsil eden ulusal havayolu.',
    examples: [
      { en: 'Turkish Airlines is Turkey\'s flag carrier.', tr: 'Türk Hava Yolları Türkiye\'nin bayrak taşıyıcısı.' },
      { en: 'Lufthansa, Air France are flag carriers.', tr: 'Lufthansa, Air France bayrak taşıyıcı.' },
    ],
    relatedTerms: ['national airline', 'state-owned', 'major carrier'],
  },
  { id: 'voc_student_044', term: 'low-cost carrier', termTr: 'low-cost havayolu', pronunciation: '/ləʊ kɒst ˈkær.i.ər/', category: 'industry', difficulty: 2,
    definitionEn: 'Airline offering low fares with limited services.',
    definitionTr: 'Sınırlı hizmetle düşük ücret sunan havayolu.',
    examples: [
      { en: 'Pegasus, AnadoluJet are low-cost.', tr: 'Pegasus, AnadoluJet low-cost.' },
      { en: 'Ryanair, Wizz Air in Europe.', tr: 'Avrupa\'da Ryanair, Wizz Air.' },
    ],
    relatedTerms: ['LCC', 'point-to-point', 'no-frills'],
  },
  { id: 'voc_student_045', term: 'cargo airline', termTr: 'kargo havayolu', pronunciation: '/ˈkɑː.ɡəʊ ˈeə.laɪn/', category: 'industry', difficulty: 2,
    definitionEn: 'Airline specialized in air freight transport.',
    definitionTr: 'Hava yük taşımacılığında uzmanlaşmış havayolu.',
    examples: [
      { en: 'MNG Cargo, Turkish Cargo.', tr: 'MNG Kargo, Turkish Cargo.' },
      { en: 'FedEx, UPS, DHL global cargo.', tr: 'Global kargo: FedEx, UPS, DHL.' },
    ],
    relatedTerms: ['freight', 'cargo hold', 'logistics'],
  },
  { id: 'voc_student_046', term: 'general aviation', termTr: 'genel havacılık', pronunciation: '/ˈdʒen.ər.əl ˌeɪ.viˈeɪ.ʃən/', category: 'industry', difficulty: 3,
    definitionEn: 'Non-commercial, non-scheduled flying — private, business, training.',
    definitionTr: 'Ticari ve tarifeli olmayan uçuşlar — özel, iş, eğitim.',
    examples: [
      { en: 'GA includes flight schools, charter.', tr: 'GA: uçuş okulları, charter dahil.' },
      { en: 'Single-engine private aircraft.', tr: 'Tek motorlu özel uçaklar.' },
    ],
    relatedTerms: ['private flying', 'charter', 'business jet'],
  },
  { id: 'voc_student_047', term: 'business aviation', termTr: 'iş havacılığı', pronunciation: '/ˈbɪz.nəs ˌeɪ.viˈeɪ.ʃən/', category: 'industry', difficulty: 3,
    definitionEn: 'Aviation for business purposes — corporate jets, private charter.',
    definitionTr: 'İş amaçlı havacılık — kurumsal jetler, özel charter.',
    examples: [
      { en: 'NetJets, VistaJet major operators.', tr: 'Büyük operatörler: NetJets, VistaJet.' },
      { en: 'Bombardier, Gulfstream business jets.', tr: 'Bombardier, Gulfstream iş jetleri.' },
    ],
    relatedTerms: ['corporate jet', 'fractional ownership', 'private charter'],
  },
  { id: 'voc_student_048', term: 'military aviation', termTr: 'askeri havacılık', pronunciation: '/ˈmɪl.ɪ.tər.i ˌeɪ.viˈeɪ.ʃən/', category: 'industry', difficulty: 2,
    definitionEn: 'Aviation operations for military and defense purposes.',
    definitionTr: 'Askeri ve savunma amaçlı havacılık operasyonları.',
    examples: [
      { en: 'Turkish Air Force operates F-16.', tr: 'Türk Hava Kuvvetleri F-16 işletir.' },
      { en: 'TAI: military aircraft manufacturer.', tr: 'TAI: askeri uçak üreticisi.' },
    ],
    relatedTerms: ['fighter jet', 'TAI', 'defense'],
  },
  { id: 'voc_student_049', term: 'manufacturer', termTr: 'üretici', pronunciation: '/ˌmæn.jəˈfæk.tʃər.ər/', category: 'industry', difficulty: 2,
    definitionEn: 'Company producing aircraft (Boeing, Airbus, Embraer).',
    definitionTr: 'Uçak üreten şirket (Boeing, Airbus, Embraer).',
    examples: [
      { en: 'Boeing 737 MAX, Airbus A320neo.', tr: 'Boeing 737 MAX, Airbus A320neo.' },
      { en: 'TUSAŞ Turkish manufacturer.', tr: 'TUSAŞ Türk üretici.' },
    ],
    relatedTerms: ['OEM', 'aircraft maker', 'TUSAŞ'],
  },
  { id: 'voc_student_050', term: 'MRO', termTr: 'MRO (Bakım, Tamir, Overhaul)', pronunciation: '/em ɑːr əʊ/', category: 'industry', difficulty: 3,
    definitionEn: 'Maintenance, Repair, Overhaul — aircraft service industry.',
    definitionTr: 'Bakım, Tamir, Overhaul — uçak servis endüstrisi.',
    examples: [
      { en: 'THY Tech is a major MRO.', tr: 'THY Teknik büyük bir MRO.' },
      { en: 'MNG Technic, Lufthansa Technik.', tr: 'MNG Technic, Lufthansa Technik.' },
    ],
    relatedTerms: ['maintenance', 'overhaul', 'EASA Part-145'],
  },

  // ===== ENGLISH PROFICIENCY GENERAL (10) =====
  { id: 'voc_student_051', term: 'fluency', termTr: 'akıcılık', pronunciation: '/ˈfluː.ən.si/', category: 'language', difficulty: 2,
    definitionEn: 'Ability to speak smoothly and rapidly without unnatural pauses.',
    definitionTr: 'Doğal olmayan duraksamalar olmadan akıcı ve hızlı konuşma yeteneği.',
    examples: [
      { en: 'ICAO 4 requires acceptable fluency.', tr: 'ICAO 4 kabul edilebilir akıcılık ister.' },
      { en: 'Practice daily for fluency.', tr: 'Akıcılık için günlük pratik.' },
    ],
    relatedTerms: ['speaking', 'natural', 'rhythm'],
  },
  { id: 'voc_student_052', term: 'pronunciation', termTr: 'telaffuz', pronunciation: '/prəˌnʌn.siˈeɪ.ʃən/', category: 'language', difficulty: 2,
    definitionEn: 'Way in which a word is articulated.',
    definitionTr: 'Bir kelimenin söyleniş şekli.',
    examples: [
      { en: 'Clear pronunciation crucial for ATC.', tr: 'ATC için net telaffuz kritik.' },
      { en: 'Phonemic transcription helps.', tr: 'Fonemik transkripsiyon yardımcı.' },
    ],
    relatedTerms: ['accent', 'phoneme', 'articulation'],
  },
  { id: 'voc_student_053', term: 'comprehension', termTr: 'anlama', pronunciation: '/ˌkɒm.prɪˈhen.ʃən/', category: 'language', difficulty: 2,
    definitionEn: 'Ability to understand spoken or written language.',
    definitionTr: 'Sözlü veya yazılı dili anlama yeteneği.',
    examples: [
      { en: 'Listening comprehension test.', tr: 'Dinleme anlama testi.' },
      { en: 'Multi-accent listening practice.', tr: 'Çok aksanlı dinleme pratiği.' },
    ],
    relatedTerms: ['listening', 'reading', 'understanding'],
  },
  { id: 'voc_student_054', term: 'vocabulary', termTr: 'kelime hazinesi', pronunciation: '/vəʊˈkæb.jə.lər.i/', category: 'language', difficulty: 1,
    definitionEn: 'Words known by a person; word stock of a language.',
    definitionTr: 'Bir kişinin bildiği kelimeler; bir dilin kelime hazinesi.',
    examples: [
      { en: 'Aviation vocabulary 2000+ terms.', tr: 'Havacılık kelimesi 2000+.' },
      { en: 'SRS for vocabulary retention.', tr: 'Kelime tutma için SRS.' },
    ],
    relatedTerms: ['word list', 'lexicon', 'terminology'],
  },
  { id: 'voc_student_055', term: 'grammar', termTr: 'gramer', pronunciation: '/ˈɡræm.ər/', category: 'language', difficulty: 1,
    definitionEn: 'Rules governing the structure of language.',
    definitionTr: 'Dilin yapısını yöneten kurallar.',
    examples: [
      { en: 'Conditional sentences in aviation.', tr: 'Havacılıkta şart cümleleri.' },
      { en: 'Tense errors common.', tr: 'Zaman hataları yaygın.' },
    ],
    relatedTerms: ['syntax', 'tense', 'structure'],
  },
  { id: 'voc_student_056', term: 'idiom', termTr: 'deyim', pronunciation: '/ˈɪd.i.əm/', category: 'language', difficulty: 3,
    definitionEn: 'Phrase whose meaning is not literal.',
    definitionTr: 'Anlamı kelimelerin gerçek anlamından farklı olan ifade.',
    examples: [
      { en: '"Bite the bullet" = endure pain.', tr: '"Bite the bullet" = acıya katlan.' },
      { en: 'Avoid idioms in ATC communication.', tr: 'ATC iletişiminde deyimlerden kaçın.' },
    ],
    relatedTerms: ['expression', 'phrase', 'colloquial'],
  },
  { id: 'voc_student_057', term: 'phonetic alphabet', termTr: 'fonetik alfabe', pronunciation: '/fəˈnet.ɪk ˈæl.fə.bet/', category: 'language', difficulty: 2,
    definitionEn: 'NATO alphabet used to spell letters in radio communication.',
    definitionTr: 'Radyo iletişiminde harfleri hecelemek için NATO alfabesi.',
    examples: [
      { en: 'Alpha, Bravo, Charlie...', tr: 'Alpha, Bravo, Charlie...' },
      { en: 'TC = Tango Charlie.', tr: 'TC = Tango Charlie.' },
    ],
    relatedTerms: ['NATO alphabet', 'spelling', 'radio'],
  },
  { id: 'voc_student_058', term: 'jargon', termTr: 'jargon (uzmanlık dili)', pronunciation: '/ˈdʒɑː.ɡən/', category: 'language', difficulty: 2,
    definitionEn: 'Specialized vocabulary used by a specific group or profession.',
    definitionTr: 'Belirli grup veya meslek tarafından kullanılan uzmanlık kelimeleri.',
    examples: [
      { en: 'Aviation jargon: cleared, roger, wilco.', tr: 'Havacılık jargonu: cleared, roger, wilco.' },
      { en: 'Avoid jargon with passengers.', tr: 'Yolcularla jargon kullanma.' },
    ],
    relatedTerms: ['terminology', 'specialized language', 'phraseology'],
  },
  { id: 'voc_student_059', term: 'accent', termTr: 'aksan', pronunciation: '/ˈæk.sənt/', category: 'language', difficulty: 1,
    definitionEn: 'Distinctive way of pronouncing a language by a region or group.',
    definitionTr: 'Bir bölge veya grup tarafından bir dilin ayırt edici söyleniş şekli.',
    examples: [
      { en: 'British vs American accent.', tr: 'İngiliz ve Amerikan aksanı.' },
      { en: 'Asian accent challenge for ATC.', tr: 'ATC için Asya aksanı zorluğu.' },
    ],
    relatedTerms: ['pronunciation', 'dialect', 'native accent'],
  },
  { id: 'voc_student_060', term: 'language proficiency', termTr: 'dil yeterliliği', pronunciation: '/ˈlæŋ.ɡwɪdʒ prəˈfɪʃ.ən.si/', category: 'language', difficulty: 2,
    definitionEn: 'Level of skill in using a language.',
    definitionTr: 'Bir dili kullanma beceri seviyesi.',
    examples: [
      { en: 'CEFR scale: A1-C2.', tr: 'CEFR skalası: A1-C2.' },
      { en: 'ICAO 4 = B2-C1 equivalent.', tr: 'ICAO 4 = B2-C1 muadili.' },
    ],
    relatedTerms: ['CEFR', 'fluency', 'level'],
  },
];
