/**
 * Teknisyen vocabulary seed — Faz 1.
 * 60 terim: dokümantasyon, ATA chapters, aletler, NDT, hardware, sertifikasyon.
 */
import type { VocabularyTerm } from './pilotVocab';

export const TECHNICIAN_VOCAB_FAZ1: VocabularyTerm[] = [
  // ===== DOCUMENTATION (10) =====
  { id: 'voc_tech_001', term: 'AMM', termTr: 'AMM (Bakım El Kitabı)', pronunciation: '/eɪ em em/', category: 'documentation', difficulty: 2,
    definitionEn: 'Aircraft Maintenance Manual — OEM document with all maintenance instructions.',
    definitionTr: 'Uçak Bakım El Kitabı — OEM\'in tüm bakım talimatlarını içeren belge.',
    examples: [
      { en: 'Reference latest AMM revision.', tr: 'Son AMM revizyonuna başvur.' },
      { en: 'AMM 32-11-00 covers main landing gear.', tr: 'AMM 32-11-00 ana iniş takımını kapsar.' },
    ],
    icaoReference: 'EASA Part-M / FAA 14 CFR Part 43',
    relatedTerms: ['CMM', 'IPC', 'WDM', 'TSM'],
  },
  { id: 'voc_tech_002', term: 'CMM', termTr: 'CMM (Komponent Bakım El Kitabı)', pronunciation: '/siː em em/', category: 'documentation', difficulty: 3,
    definitionEn: 'Component Maintenance Manual — overhaul instructions for specific components.',
    definitionTr: 'Komponent Bakım El Kitabı — belirli komponentlerin overhaul talimatları.',
    examples: [
      { en: 'CMM provides limits and fits.', tr: 'CMM limitleri ve fitleri verir.' },
      { en: 'CMM 32-30-15: brake assembly overhaul.', tr: 'CMM 32-30-15: fren overhaul.' },
    ],
    relatedTerms: ['overhaul', 'AMM', 'limits'],
  },
  { id: 'voc_tech_003', term: 'IPC', termTr: 'IPC (Parça Kataloğu)', pronunciation: '/aɪ piː siː/', category: 'documentation', difficulty: 3,
    definitionEn: 'Illustrated Parts Catalog — visual identification of aircraft parts.',
    definitionTr: 'Resimli Parça Kataloğu — uçak parçalarının görsel tanımı.',
    examples: [
      { en: 'Look up part number in IPC.', tr: 'IPC\'de parça numarasını ara.' },
      { en: 'IPC figure 32-11-01-01.', tr: 'IPC şekil 32-11-01-01.' },
    ],
    relatedTerms: ['part number', 'effectivity', 'figure'],
  },
  { id: 'voc_tech_004', term: 'WDM', termTr: 'WDM (Kablo Şeması)', pronunciation: '/dʌb.əl.juː diː em/', category: 'documentation', difficulty: 3,
    definitionEn: 'Wiring Diagram Manual — schematics of aircraft electrical systems.',
    definitionTr: 'Kablo Diyagramı Kılavuzu — uçak elektrik sistemleri şemaları.',
    examples: [
      { en: 'WDM 24-21: AC bus wiring.', tr: 'WDM 24-21: AC bus kabloları.' },
      { en: 'Trace wire using WDM.', tr: 'Kabloyu WDM ile takip et.' },
    ],
    relatedTerms: ['schematic', 'pin assignment', 'connector'],
  },
  { id: 'voc_tech_005', term: 'TSM', termTr: 'TSM (Sorun Giderme)', pronunciation: '/tiː es em/', category: 'documentation', difficulty: 3,
    definitionEn: 'Trouble Shooting Manual — diagnostic procedures for system faults.',
    definitionTr: 'Sorun Giderme Kılavuzu — sistem arızaları için tanı prosedürleri.',
    examples: [
      { en: 'Use TSM for fault isolation.', tr: 'Arıza izolasyonu için TSM kullan.' },
      { en: 'TSM decision tree guides repair.', tr: 'TSM karar ağacı tamiri yönlendirir.' },
    ],
    relatedTerms: ['fault code', 'AMM', 'diagnostic'],
  },
  { id: 'voc_tech_006', term: 'service bulletin', termTr: 'Servis Bülteni (SB)', pronunciation: '/ˈsɜː.vɪs ˈbʊl.ə.tɪn/', category: 'documentation', difficulty: 3,
    definitionEn: 'OEM document recommending modifications, inspections, or procedure updates.',
    definitionTr: 'OEM tarafından modifikasyon, muayene veya prosedür güncellemesi öneren belge.',
    examples: [
      { en: 'SB 737-32-1234 recommends inspection.', tr: 'SB 737-32-1234 muayene önerir.' },
      { en: 'SB Alert vs Recommended.', tr: 'SB Alert ve Recommended farkı.' },
    ],
    relatedTerms: ['AD', 'modification', 'compliance'],
  },
  { id: 'voc_tech_007', term: 'airworthiness directive', termTr: 'Hava Seyrüsefer Direktifi (AD)', pronunciation: '/ˈeə.wɜː.ðɪ.nəs daɪˈrek.tɪv/', category: 'documentation', difficulty: 4,
    definitionEn: 'Mandatory regulation requiring corrective action by aviation authority.',
    definitionTr: 'Havacılık otoritesi tarafından düzeltici aksiyon gerektiren zorunlu düzenleme.',
    examples: [
      { en: 'AD compliance is mandatory.', tr: 'AD uyumu zorunludur.' },
      { en: 'EASA AD 2024-0123.', tr: 'EASA AD 2024-0123.' },
    ],
    icaoReference: 'EASA / FAA continuing airworthiness',
    relatedTerms: ['SB', 'compliance', 'mandatory'],
  },
  { id: 'voc_tech_008', term: 'job card', termTr: 'iş kartı', pronunciation: '/dʒɒb kɑːd/', category: 'documentation', difficulty: 2,
    definitionEn: 'Document describing a specific maintenance task with sign-off blocks.',
    definitionTr: 'Belirli bir bakım görevini ve imza bloklarını açıklayan belge.',
    examples: [
      { en: 'Sign job card after task complete.', tr: 'Görev sonrası iş kartını imzala.' },
      { en: 'Job card cross-references AMM.', tr: 'İş kartı AMM ile çapraz referansla.' },
    ],
    relatedTerms: ['routing card', 'sign-off', 'work order'],
  },
  { id: 'voc_tech_009', term: 'EASA Form 1', termTr: 'EASA Form 1', pronunciation: '/ˈiː.zə fɔːm wʌn/', category: 'certification', difficulty: 4,
    definitionEn: 'European authorized release certificate — confirms part is airworthy.',
    definitionTr: 'Avrupa yetkili yayın sertifikası — parçanın airworthy olduğunu onaylar.',
    examples: [
      { en: 'Every overhauled part has EASA Form 1.', tr: 'Her overhaul parça EASA Form 1\'le çıkar.' },
      { en: 'FAA equivalent: Form 8130-3.', tr: 'FAA muadili: Form 8130-3.' },
    ],
    icaoReference: 'EASA Part-145',
    relatedTerms: ['Form 8130-3', 'CRS', 'airworthy'],
  },
  { id: 'voc_tech_010', term: 'CRS', termTr: 'CRS (Servis Yayın Sertifikası)', pronunciation: '/siː ɑːr es/', category: 'certification', difficulty: 4,
    definitionEn: 'Certificate of Release to Service — confirms aircraft is airworthy after maintenance.',
    definitionTr: 'Servis Yayın Sertifikası — bakım sonrası uçağın airworthy olduğunu onaylar.',
    examples: [
      { en: 'Only certifying staff can issue CRS.', tr: 'CRS\'yi sadece sertifikalı personel düzenler.' },
      { en: 'B1/B2 license required for CRS.', tr: 'CRS için B1/B2 lisansı gerekli.' },
    ],
    relatedTerms: ['certifying staff', 'B1', 'B2', 'airworthy'],
  },

  // ===== ATA CHAPTERS (10) =====
  { id: 'voc_tech_011', term: 'ATA chapter', termTr: 'ATA bölüm sistemi', pronunciation: '/eɪ tiː eɪ ˈtʃæp.tər/', category: 'documentation', difficulty: 3,
    definitionEn: 'Air Transport Association numbering for aircraft systems.',
    definitionTr: 'Uçak sistemleri için Air Transport Association numaralandırması.',
    examples: [
      { en: 'ATA 32 = Landing Gear.', tr: 'ATA 32 = İniş Takımı.' },
      { en: 'ATA 49 = APU.', tr: 'ATA 49 = APU.' },
    ],
    relatedTerms: ['AMM', 'IPC', 'WDM'],
  },
  { id: 'voc_tech_012', term: 'ATA 21', termTr: 'ATA 21 (Klima)', pronunciation: '/eɪ tiː eɪ ˈtwen.ti wʌn/', category: 'systems', difficulty: 3,
    definitionEn: 'Air Conditioning system — cabin temperature, pressurization, ventilation.',
    definitionTr: 'Klima sistemi — kabin sıcaklığı, basınçlandırma, havalandırma.',
    examples: [
      { en: 'Pack failure: ATA 21-50.', tr: 'Pack arızası: ATA 21-50.' },
      { en: 'Mix manifold balances temperature.', tr: 'Mix manifold sıcaklık dengeler.' },
    ],
    relatedTerms: ['pack', 'pressurization', 'bleed air'],
  },
  { id: 'voc_tech_013', term: 'ATA 24', termTr: 'ATA 24 (Elektrik)', pronunciation: '/eɪ tiː eɪ ˈtwen.ti fɔːr/', category: 'systems', difficulty: 3,
    definitionEn: 'Electrical Power system — generators, batteries, distribution.',
    definitionTr: 'Elektrik Güç sistemi — jeneratörler, bataryalar, dağıtım.',
    examples: [
      { en: 'AC bus failure: ATA 24-21.', tr: 'AC bus arıza: ATA 24-21.' },
      { en: 'TR (Transformer Rectifier) supplies DC.', tr: 'TR (Transformer Rectifier) DC sağlar.' },
    ],
    relatedTerms: ['generator', 'battery', 'bus', 'GPU'],
  },
  { id: 'voc_tech_014', term: 'ATA 27', termTr: 'ATA 27 (Uçuş Kontrolleri)', pronunciation: '/eɪ tiː eɪ ˈtwen.ti ˈsev.ən/', category: 'systems', difficulty: 3,
    definitionEn: 'Flight Controls — ailerons, elevators, rudder, flaps, slats.',
    definitionTr: 'Uçuş Kontrolleri — eleron, elevator, dümen, flap, slat.',
    examples: [
      { en: 'Aileron actuator: ATA 27-10.', tr: 'Eleron actuator: ATA 27-10.' },
      { en: 'Manual reversion test post-maintenance.', tr: 'Bakım sonrası manuel reversion testi.' },
    ],
    relatedTerms: ['actuator', 'cable', 'PCU'],
  },
  { id: 'voc_tech_015', term: 'ATA 28', termTr: 'ATA 28 (Yakıt)', pronunciation: '/eɪ tiː eɪ ˈtwen.ti eɪt/', category: 'systems', difficulty: 3,
    definitionEn: 'Fuel system — tanks, pumps, transfer, quantity indication.',
    definitionTr: 'Yakıt sistemi — tanklar, pompalar, transfer, miktar göstergesi.',
    examples: [
      { en: 'Fuel pump replacement: ATA 28-20.', tr: 'Yakıt pompası değişimi: ATA 28-20.' },
      { en: 'FQI: fuel quantity indication.', tr: 'FQI: yakıt miktarı göstergesi.' },
    ],
    relatedTerms: ['fuel pump', 'tank', 'FQI'],
  },
  { id: 'voc_tech_016', term: 'ATA 29', termTr: 'ATA 29 (Hidrolik)', pronunciation: '/eɪ tiː eɪ ˈtwen.ti naɪn/', category: 'systems', difficulty: 3,
    definitionEn: 'Hydraulic Power — pumps, reservoirs, accumulators, fluid distribution.',
    definitionTr: 'Hidrolik Güç — pompalar, rezervuarlar, akümülatörler, akışkan dağıtımı.',
    examples: [
      { en: 'EDP failure: ATA 29-10.', tr: 'EDP arızası: ATA 29-10.' },
      { en: '3000 PSI standard.', tr: '3000 PSI standart.' },
    ],
    relatedTerms: ['EDP', 'EMP', 'reservoir', 'PSI'],
  },
  { id: 'voc_tech_017', term: 'ATA 32', termTr: 'ATA 32 (İniş Takımı)', pronunciation: '/eɪ tiː eɪ ˈθɜː.ti tuː/', category: 'systems', difficulty: 2,
    definitionEn: 'Landing Gear — wheels, brakes, tires, retraction, steering.',
    definitionTr: 'İniş Takımı — tekerlek, fren, lastik, toplama, yönlendirme.',
    examples: [
      { en: 'MLG retraction test: ATA 32-30.', tr: 'MLG toplama testi: ATA 32-30.' },
      { en: 'Anti-skid system.', tr: 'Anti-skid sistemi.' },
    ],
    relatedTerms: ['MLG', 'NLG', 'anti-skid', 'tire'],
  },
  { id: 'voc_tech_018', term: 'ATA 49', termTr: 'ATA 49 (APU)', pronunciation: '/eɪ tiː eɪ ˈfɔː.ti naɪn/', category: 'systems', difficulty: 3,
    definitionEn: 'Auxiliary Power Unit — small turbine engine for ground/emergency power.',
    definitionTr: 'Yardımcı Güç Ünitesi — yer/acil güç için küçük türbin motoru.',
    examples: [
      { en: 'APU start sequence: ATA 49-11.', tr: 'APU çalıştırma sırası: ATA 49-11.' },
      { en: 'EGT high during start.', tr: 'Çalıştırmada EGT yüksek.' },
    ],
    relatedTerms: ['APU start', 'bleed air', 'EGT'],
  },
  { id: 'voc_tech_019', term: 'ATA 71', termTr: 'ATA 71 (Motor Genel)', pronunciation: '/eɪ tiː eɪ ˈsev.ən.ti wʌn/', category: 'systems', difficulty: 3,
    definitionEn: 'Powerplant general — engine installation, mounts, cowling.',
    definitionTr: 'Motor genel — motor montajı, bağlantılar, kaporta.',
    examples: [
      { en: 'Engine mount inspection: ATA 71-20.', tr: 'Motor mount muayenesi: ATA 71-20.' },
      { en: 'Cowling latches secured.', tr: 'Kaporta kilitleri sıkı.' },
    ],
    relatedTerms: ['engine mount', 'cowling', 'pylon'],
  },
  { id: 'voc_tech_020', term: 'ATA 79', termTr: 'ATA 79 (Yağ)', pronunciation: '/eɪ tiː eɪ ˈsev.ən.ti naɪn/', category: 'systems', difficulty: 3,
    definitionEn: 'Engine oil system — tanks, pumps, filtration, indication.',
    definitionTr: 'Motor yağ sistemi — tanklar, pompalar, filtre, gösterge.',
    examples: [
      { en: 'Oil filter change: ATA 79-21.', tr: 'Yağ filtresi değişimi: ATA 79-21.' },
      { en: 'Oil pressure low warning.', tr: 'Yağ basıncı düşük uyarısı.' },
    ],
    relatedTerms: ['oil filter', 'oil pressure', 'oil temperature'],
  },

  // ===== TOOLS (10) =====
  { id: 'voc_tech_021', term: 'torque wrench', termTr: 'tork anahtarı', pronunciation: '/tɔːk rentʃ/', category: 'tools', difficulty: 1,
    definitionEn: 'Precision tool that applies a specific rotational force to a fastener.',
    definitionTr: 'Bir bağlantı elemanına belirli dönme kuvveti uygulayan hassas alet.',
    examples: [
      { en: 'Calibration sticker must be valid.', tr: 'Kalibrasyon etiketi geçerli olmalı.' },
      { en: 'Apply torque in 3 passes.', tr: '3 paste tork uygula.' },
    ],
    relatedTerms: ['torque seal', 'calibration', 'wrench'],
  },
  { id: 'voc_tech_022', term: 'micrometer', termTr: 'mikrometre', pronunciation: '/ˌmaɪˈkrɒm.ɪ.tər/', category: 'tools', difficulty: 2,
    definitionEn: 'Precision instrument for measuring small dimensions.',
    definitionTr: 'Küçük boyutları ölçen hassas alet.',
    examples: [
      { en: 'Micrometer reads 25.36 mm.', tr: 'Mikrometre 25.36 mm gösteriyor.' },
      { en: 'Inside, outside, depth micrometer.', tr: 'İç, dış, derinlik mikrometre.' },
    ],
    relatedTerms: ['caliper', 'gauge', 'measurement'],
  },
  { id: 'voc_tech_023', term: 'caliper', termTr: 'kumpas', pronunciation: '/ˈkæl.ɪ.pər/', category: 'tools', difficulty: 2,
    definitionEn: 'Measuring instrument for outer/inner dimensions and depth.',
    definitionTr: 'Dış/iç boyutlar ve derinlik ölçen alet.',
    examples: [
      { en: 'Vernier caliper: 0.02 mm precision.', tr: 'Vernier kumpas: 0.02 mm hassasiyet.' },
      { en: 'Digital caliper for quick reads.', tr: 'Hızlı okuma için dijital kumpas.' },
    ],
    relatedTerms: ['micrometer', 'vernier', 'digital'],
  },
  { id: 'voc_tech_024', term: 'borescope', termTr: 'borescope (iç görüş)', pronunciation: '/ˈbɔː.skəʊp/', category: 'tools', difficulty: 3,
    definitionEn: 'Flexible camera for inspecting internal aircraft components.',
    definitionTr: 'Uçak iç komponentlerini muayene eden esnek kamera.',
    examples: [
      { en: 'Borescope inspect after engine overhaul.', tr: 'Motor overhaul sonrası borescope.' },
      { en: 'Document with photo capture.', tr: 'Foto kaydıyla belgele.' },
    ],
    relatedTerms: ['compressor blade', 'turbine', 'visual inspection'],
  },
  { id: 'voc_tech_025', term: 'multimeter', termTr: 'multimetre', pronunciation: '/ˈmʌl.tɪˌmiː.tər/', category: 'tools', difficulty: 2,
    definitionEn: 'Electronic instrument measuring voltage, current, and resistance.',
    definitionTr: 'Voltaj, akım ve direnç ölçen elektronik alet.',
    examples: [
      { en: 'Test continuity with multimeter.', tr: 'Süreklilik testi multimetre ile.' },
      { en: 'Calibrated multimeter required.', tr: 'Kalibre multimetre gerekli.' },
    ],
    relatedTerms: ['voltage', 'current', 'resistance', 'continuity'],
  },
  { id: 'voc_tech_026', term: 'lockwire pliers', termTr: 'lockwire pensesi', pronunciation: '/ˈlɒk.waɪər ˈplaɪ.əz/', category: 'tools', difficulty: 2,
    definitionEn: 'Specialized pliers for twisting safety wire.',
    definitionTr: 'Emniyet teli bükmek için özel pense.',
    examples: [
      { en: 'Twist wire in pull direction.', tr: 'Teli çekme yönünde bük.' },
      { en: 'Cut excess — no FOD.', tr: 'Fazlayı kes — FOD yok.' },
    ],
    relatedTerms: ['lockwire', 'safety wire', 'FOD'],
  },
  { id: 'voc_tech_027', term: 'jack', termTr: 'kriko (jack)', pronunciation: '/dʒæk/', category: 'tools', difficulty: 2,
    definitionEn: 'Hydraulic device used to lift the aircraft for maintenance.',
    definitionTr: 'Bakım için uçağı kaldırmaya yarayan hidrolik cihaz.',
    examples: [
      { en: 'Lift on tripod jack.', tr: 'Tripod kriko ile kaldır.' },
      { en: 'Annual load test required.', tr: 'Yıllık yük testi gerekli.' },
    ],
    relatedTerms: ['axle jack', 'tripod', 'load test'],
  },
  { id: 'voc_tech_028', term: 'rivet gun', termTr: 'perçin tabancası', pronunciation: '/ˈrɪv.ɪt ɡʌn/', category: 'tools', difficulty: 2,
    definitionEn: 'Pneumatic tool used to install rivets in sheet metal.',
    definitionTr: 'Sac metale perçin takmak için pnömatik alet.',
    examples: [
      { en: 'Rivet gun pressure 90 PSI.', tr: 'Perçin tabancası basıncı 90 PSI.' },
      { en: 'Bucking bar opposite side.', tr: 'Karşı tarafta bucking bar.' },
    ],
    relatedTerms: ['rivet', 'bucking bar', 'sheet metal'],
  },
  { id: 'voc_tech_029', term: 'feeler gauge', termTr: 'sentil çakısı', pronunciation: '/ˈfiː.lər ɡeɪdʒ/', category: 'tools', difficulty: 2,
    definitionEn: 'Thin metal strips used to measure small gaps.',
    definitionTr: 'Küçük boşlukları ölçen ince metal şeritler.',
    examples: [
      { en: 'Check spark plug gap.', tr: 'Buji boşluğu kontrol.' },
      { en: '0.05 mm increments.', tr: '0.05 mm artımlı.' },
    ],
    relatedTerms: ['gap', 'clearance', 'thickness'],
  },
  { id: 'voc_tech_030', term: 'workbench', termTr: 'tezgah', pronunciation: '/ˈwɜːk.bentʃ/', category: 'tools', difficulty: 1,
    definitionEn: 'Sturdy table where mechanics perform detailed work.',
    definitionTr: 'Mekaniklerin detaylı iş yaptığı sağlam masa.',
    examples: [
      { en: 'Component inspection on workbench.', tr: 'Tezgahta komponent muayenesi.' },
      { en: 'Workbench with vise and lighting.', tr: 'Mengeneli ve ışıklı tezgah.' },
    ],
    relatedTerms: ['vise', 'tool board', 'shop'],
  },

  // ===== INSPECTION & NDT (10) =====
  { id: 'voc_tech_031', term: 'NDT', termTr: 'NDT (Tahribatsız Muayene)', pronunciation: '/en diː tiː/', category: 'inspection', difficulty: 3,
    definitionEn: 'Non-Destructive Testing — defect detection without damaging the part.',
    definitionTr: 'Tahribatsız Muayene — parçaya zarar vermeden hata tespiti.',
    examples: [
      { en: 'NDT Level 2 certified for MPI.', tr: 'NDT Level 2 MPI sertifikalı.' },
      { en: 'Eddy current finds subsurface defects.', tr: 'Eddy current yüzey altı bulur.' },
    ],
    icaoReference: 'EN 4179 / NAS 410',
    relatedTerms: ['MPI', 'FPI', 'ultrasonic'],
  },
  { id: 'voc_tech_032', term: 'MPI', termTr: 'MPI (Manyetik Parçacık)', pronunciation: '/em piː aɪ/', category: 'inspection', difficulty: 3,
    definitionEn: 'Magnetic Particle Inspection — finds surface/subsurface cracks in ferrous parts.',
    definitionTr: 'Manyetik Parçacık Muayenesi — demir esaslı parçalarda yüzey/alt yüzey çatlak bulur.',
    examples: [
      { en: 'MPI ferrous parts only.', tr: 'MPI sadece demir esaslı.' },
      { en: 'Yoke or coil method.', tr: 'Yoke veya bobin yöntemi.' },
    ],
    relatedTerms: ['NDT', 'ferrous', 'crack'],
  },
  { id: 'voc_tech_033', term: 'FPI', termTr: 'FPI (Fluoresan Penetrant)', pronunciation: '/ef piː aɪ/', category: 'inspection', difficulty: 3,
    definitionEn: 'Fluorescent Penetrant Inspection — surface crack detection on non-ferrous.',
    definitionTr: 'Fluoresan Penetrant Muayenesi — demir dışı parçalarda yüzey çatlak.',
    examples: [
      { en: 'FPI for aluminum components.', tr: 'Alüminyum komponentler için FPI.' },
      { en: 'UV light reveals indications.', tr: 'UV ışık göstergeleri açığa çıkarır.' },
    ],
    relatedTerms: ['NDT', 'penetrant', 'UV light'],
  },
  { id: 'voc_tech_034', term: 'eddy current', termTr: 'eddy current', pronunciation: '/ˈed.i ˈkʌr.ənt/', category: 'inspection', difficulty: 4,
    definitionEn: 'Electromagnetic NDT method for detecting subsurface defects.',
    definitionTr: 'Yüzey altı hata tespiti için elektromanyetik NDT yöntemi.',
    examples: [
      { en: 'Eddy current scans rivet holes.', tr: 'Eddy current perçin deliklerini tarar.' },
      { en: 'Hidden corrosion detection.', tr: 'Gizli korozyon tespiti.' },
    ],
    relatedTerms: ['NDT', 'subsurface', 'electromagnetic'],
  },
  { id: 'voc_tech_035', term: 'ultrasonic testing', termTr: 'ultrasonik test (UT)', pronunciation: '/ˌʌl.trəˈsɒn.ɪk ˈtest.ɪŋ/', category: 'inspection', difficulty: 4,
    definitionEn: 'Sound wave NDT for thickness measurement and internal flaws.',
    definitionTr: 'Kalınlık ölçümü ve iç hata için ses dalgası NDT yöntemi.',
    examples: [
      { en: 'UT measures wall thickness.', tr: 'UT duvar kalınlığı ölçer.' },
      { en: 'Couplant gel applied.', tr: 'Couplant jel uygulanır.' },
    ],
    relatedTerms: ['UT', 'thickness', 'flaw'],
  },
  { id: 'voc_tech_036', term: 'visual inspection', termTr: 'görsel muayene', pronunciation: '/ˈvɪʒ.u.əl ɪnˈspek.ʃən/', category: 'inspection', difficulty: 1,
    definitionEn: 'First-line inspection using eyes, mirrors, and lighting.',
    definitionTr: 'Göz, ayna ve ışıkla yapılan ilk hat muayene.',
    examples: [
      { en: 'Walk-around includes visual inspection.', tr: 'Walk-around görsel muayene içerir.' },
      { en: 'Document with photos.', tr: 'Fotoğrafla belgele.' },
    ],
    relatedTerms: ['walk-around', 'inspection mirror', 'flashlight'],
  },
  { id: 'voc_tech_037', term: 'corrosion', termTr: 'korozyon', pronunciation: '/kəˈrəʊ.ʒən/', category: 'defect', difficulty: 2,
    definitionEn: 'Chemical degradation of metal — pitting, intergranular, exfoliation.',
    definitionTr: 'Metalin kimyasal bozulması — pitting, intergranular, exfoliation.',
    examples: [
      { en: 'Pitting on lower wing skin.', tr: 'Alt kanat skin\'inde pitting.' },
      { en: 'Apply corrosion inhibitor.', tr: 'Korozyon önleyici uygula.' },
    ],
    relatedTerms: ['pitting', 'fatigue', 'inhibitor'],
  },
  { id: 'voc_tech_038', term: 'fatigue crack', termTr: 'yorulma çatlağı', pronunciation: '/fəˈtiːɡ kræk/', category: 'defect', difficulty: 3,
    definitionEn: 'Crack from repeated stress cycles, common in high-stress components.',
    definitionTr: 'Tekrarlanan stres döngülerinden çatlak, yüksek stresli komponentlerde yaygın.',
    examples: [
      { en: 'Fatigue crack in wing spar.', tr: 'Kanat sparında yorulma çatlağı.' },
      { en: 'Cycle limit reached.', tr: 'Döngü limiti doldu.' },
    ],
    relatedTerms: ['stress', 'cycle', 'fracture'],
  },
  { id: 'voc_tech_039', term: 'dent', termTr: 'göçük', pronunciation: '/dent/', category: 'defect', difficulty: 1,
    definitionEn: 'Localized indentation in aircraft skin from impact.',
    definitionTr: 'Çarpmadan uçak skin\'inde lokal göçme.',
    examples: [
      { en: 'Dent map records location/depth.', tr: 'Dent map yer ve derinliği kaydeder.' },
      { en: 'Within AMM acceptable damage limits.', tr: 'AMM kabul limitleri dahilinde.' },
    ],
    relatedTerms: ['damage limit', 'skin', 'impact'],
  },
  { id: 'voc_tech_040', term: 'scratch', termTr: 'çizik', pronunciation: '/skrætʃ/', category: 'defect', difficulty: 1,
    definitionEn: 'Linear surface mark, typically shallow.',
    definitionTr: 'Doğrusal yüzey izi, genelde sığ.',
    examples: [
      { en: 'Light scratch within limits.', tr: 'Hafif çizik limit dahilinde.' },
      { en: 'Polish out minor scratches.', tr: 'Hafif çizikleri parlat.' },
    ],
    relatedTerms: ['defect', 'damage limit', 'polish'],
  },

  // ===== HARDWARE (10) =====
  { id: 'voc_tech_041', term: 'lockwire', termTr: 'kilit teli (safety wire)', pronunciation: '/ˈlɒk.waɪər/', category: 'hardware', difficulty: 2,
    definitionEn: 'Stainless steel wire securing fasteners against vibration.',
    definitionTr: 'Bağlantı elemanlarını titreşime karşı kilitleyen paslanmaz çelik tel.',
    examples: [
      { en: 'Twist wire in pull direction.', tr: 'Teli çekme yönünde bük.' },
      { en: 'Cut excess — no FOD.', tr: 'Fazlayı kes — FOD yok.' },
    ],
    relatedTerms: ['cotter pin', 'torque seal', 'fastener'],
  },
  { id: 'voc_tech_042', term: 'cotter pin', termTr: 'gupilya (cotter pin)', pronunciation: '/ˈkɒt.ər pɪn/', category: 'hardware', difficulty: 2,
    definitionEn: 'Split metal pin used to secure nuts on castle bolts.',
    definitionTr: 'Castle cıvatalarındaki somunları sabitleyen yarık metal pin.',
    examples: [
      { en: 'New cotter pin every install.', tr: 'Her takmada yeni cotter pin.' },
      { en: 'Spread legs after insertion.', tr: 'Taktıktan sonra bacakları aç.' },
    ],
    relatedTerms: ['castle nut', 'split pin', 'lockwire'],
  },
  { id: 'voc_tech_043', term: 'torque seal', termTr: 'tork mührü', pronunciation: '/tɔːk siːl/', category: 'hardware', difficulty: 2,
    definitionEn: 'Colored paint applied across fastener and joint as visual evidence of torque.',
    definitionTr: 'Tork uygulandığını gösteren bağlantı ve birleşim üzerine sürülen renkli boya.',
    examples: [
      { en: 'Apply torque seal post-torque.', tr: 'Tork sonrası torque seal.' },
      { en: 'Broken seal: re-inspect torque.', tr: 'Kırık seal: tork tekrar muayene.' },
    ],
    relatedTerms: ['witness mark', 'torque wrench', 'inspection'],
  },
  { id: 'voc_tech_044', term: 'self-locking nut', termTr: 'kendiliğinden kilitli somun', pronunciation: '/self ˈlɒk.ɪŋ nʌt/', category: 'hardware', difficulty: 2,
    definitionEn: 'Nut with built-in locking feature (nylon insert or distorted thread).',
    definitionTr: 'Yerleşik kilitleme özelliği olan somun (naylon insert veya distorted thread).',
    examples: [
      { en: 'One-time use only.', tr: 'Tek kullanımlık.' },
      { en: 'Replace after each removal.', tr: 'Her sökümden sonra değiştir.' },
    ],
    relatedTerms: ['nyloc', 'one-time use', 'castle nut'],
  },
  { id: 'voc_tech_045', term: 'castle nut', termTr: 'taç somun', pronunciation: '/ˈkɑː.səl nʌt/', category: 'hardware', difficulty: 2,
    definitionEn: 'Slotted nut allowing insertion of a cotter pin for safety.',
    definitionTr: 'Emniyet için cotter pin takılmasına izin veren yarık somun.',
    examples: [
      { en: 'Castle nut + cotter pin combo.', tr: 'Castle nut + cotter pin kombinasyonu.' },
      { en: 'Hand tighten then torque to slot.', tr: 'Elle sık, sonra slot\'a kadar tork.' },
    ],
    relatedTerms: ['cotter pin', 'self-locking nut', 'torque'],
  },
  { id: 'voc_tech_046', term: 'shim', termTr: 'şim (ayar plakası)', pronunciation: '/ʃɪm/', category: 'hardware', difficulty: 2,
    definitionEn: 'Thin spacer used to fill gaps or adjust alignment.',
    definitionTr: 'Boşluk doldurmak veya hizalamayı ayarlamak için ince ara plaka.',
    examples: [
      { en: 'Shim 0.005 inch.', tr: 'Shim 0.005 inç.' },
      { en: 'Stack shims to required thickness.', tr: 'Gerekli kalınlığa kadar shim üst üste.' },
    ],
    relatedTerms: ['gap', 'alignment', 'spacer'],
  },
  { id: 'voc_tech_047', term: 'bushing', termTr: 'burç (bushing)', pronunciation: '/ˈbʊʃ.ɪŋ/', category: 'hardware', difficulty: 2,
    definitionEn: 'Sleeve or insert reducing friction or wear at a bearing surface.',
    definitionTr: 'Yatak yüzeyinde sürtünme veya aşınmayı azaltan kovan veya insert.',
    examples: [
      { en: 'Bushing replacement during overhaul.', tr: 'Overhaul sırasında bushing değişimi.' },
      { en: 'Press-fit bushing.', tr: 'Sıkı geçme bushing.' },
    ],
    relatedTerms: ['bearing', 'sleeve', 'wear'],
  },
  { id: 'voc_tech_048', term: 'rivet', termTr: 'perçin', pronunciation: '/ˈrɪv.ɪt/', category: 'hardware', difficulty: 2,
    definitionEn: 'Permanent fastener formed by deforming the shank.',
    definitionTr: 'Şaftın deforme edilmesiyle oluşan kalıcı bağlantı elemanı.',
    examples: [
      { en: 'Solid rivet for high-stress areas.', tr: 'Yüksek stresli alanlar için solid rivet.' },
      { en: 'Blind rivet (Cherry) for one-side access.', tr: 'Tek taraflı erişim için blind rivet.' },
    ],
    relatedTerms: ['solid rivet', 'blind rivet', 'rivet gun'],
  },
  { id: 'voc_tech_049', term: 'fastener', termTr: 'bağlantı elemanı', pronunciation: '/ˈfɑː.sən.ər/', category: 'hardware', difficulty: 1,
    definitionEn: 'Generic term for bolts, screws, nuts, rivets, and similar.',
    definitionTr: 'Cıvata, vida, somun, perçin ve benzer için genel terim.',
    examples: [
      { en: 'Critical fasteners require torque.', tr: 'Kritik bağlantı elemanları tork gerektirir.' },
      { en: 'Fastener inventory before close-up.', tr: 'Kapatmadan önce fastener envanteri.' },
    ],
    relatedTerms: ['bolt', 'nut', 'rivet', 'screw'],
  },
  { id: 'voc_tech_050', term: 'shop towel', termTr: 'atelye bezi', pronunciation: '/ʃɒp ˈtaʊ.əl/', category: 'consumables', difficulty: 1,
    definitionEn: 'Disposable cloth for cleaning and FOD-prevention.',
    definitionTr: 'Temizlik ve FOD önleme için tek kullanımlık bez.',
    examples: [
      { en: 'Account for every shop towel.', tr: 'Her shop towel\'ı say.' },
      { en: 'FOD source if left behind.', tr: 'Bırakılırsa FOD kaynağı.' },
    ],
    relatedTerms: ['FOD', 'cleaning', 'consumables'],
  },

  // ===== OPERATIONS (10) =====
  { id: 'voc_tech_051', term: 'AOG', termTr: 'AOG (Aircraft on Ground)', pronunciation: '/eɪ əʊ dʒiː/', category: 'operations', difficulty: 4,
    definitionEn: 'Critical maintenance situation — aircraft cannot fly until fixed.',
    definitionTr: 'Kritik bakım durumu — uçak tamir edilmeden uçamaz.',
    examples: [
      { en: 'AOG: 737 stuck due to hydraulic leak.', tr: 'AOG: 737 hidrolik kaçaktan kalkamıyor.' },
      { en: 'AOG parts: charter shipping.', tr: 'AOG parçalar: charter taşıma.' },
    ],
    relatedTerms: ['MEL', 'defect', 'urgent'],
  },
  { id: 'voc_tech_052', term: 'MEL', termTr: 'MEL (Asgari Ekipman Listesi)', pronunciation: '/em iː el/', category: 'operations', difficulty: 4,
    definitionEn: 'Minimum Equipment List — items that may be inoperative for limited dispatch.',
    definitionTr: 'Asgari Ekipman Listesi — sınırlı dispatch için inoperative olabilecek öğeler.',
    examples: [
      { en: 'Defer item per MEL.', tr: 'Öğeyi MEL\'e göre ertele.' },
      { en: 'MEL category B: 3 days.', tr: 'MEL kategori B: 3 gün.' },
    ],
    relatedTerms: ['CDL', 'deferral', 'dispatch'],
  },
  { id: 'voc_tech_053', term: 'walk-around', termTr: 'walk-around (uçuş öncesi tur)', pronunciation: '/wɔːk əˈraʊnd/', category: 'operations', difficulty: 1,
    definitionEn: 'External pre-flight visual inspection of the aircraft.',
    definitionTr: 'Uçuş öncesi uçağın dış görsel muayenesi.',
    examples: [
      { en: 'Walk-around takes 15 minutes.', tr: 'Walk-around 15 dakika.' },
      { en: 'Check tires, panels, lights.', tr: 'Lastik, panel, ışık kontrol.' },
    ],
    relatedTerms: ['preflight', 'visual inspection', 'pilot inspection'],
  },
  { id: 'voc_tech_054', term: 'defect entry', termTr: 'arıza kaydı', pronunciation: '/ˈdiː.fekt ˈen.tri/', category: 'documentation', difficulty: 3,
    definitionEn: 'Written record of a discovered fault in the technical log.',
    definitionTr: 'Teknik log\'a yapılan keşfedilen arıza yazılı kaydı.',
    examples: [
      { en: 'Pilot reports: "Right brake intermittent."', tr: 'Pilot raporu: "Sağ fren aralıklı."' },
      { en: 'Defect entry triggers maintenance action.', tr: 'Defect entry bakım aksiyonu tetikler.' },
    ],
    relatedTerms: ['tech log', 'TLB', 'write-up'],
  },
  { id: 'voc_tech_055', term: 'tech log', termTr: 'teknik log', pronunciation: '/tek lɒɡ/', category: 'documentation', difficulty: 3,
    definitionEn: 'Technical Log — onboard record of defects, deferrals, and maintenance.',
    definitionTr: 'Teknik Log — uçaktaki arıza, erteleme ve bakım kaydı.',
    examples: [
      { en: 'Sign tech log after each repair.', tr: 'Her tamir sonrası tech log imzala.' },
      { en: 'Tech log accompanies aircraft.', tr: 'Tech log uçakla birlikte taşınır.' },
    ],
    relatedTerms: ['TLB', 'defect entry', 'sign-off'],
  },
  { id: 'voc_tech_056', term: 'sign-off', termTr: 'onay imzası', pronunciation: '/saɪn ɒf/', category: 'certification', difficulty: 2,
    definitionEn: 'Certification by qualified person that work was performed correctly.',
    definitionTr: 'İşin doğru yapıldığının nitelikli kişi tarafından sertifikalandırılması.',
    examples: [
      { en: 'Mechanic sign-off + inspector verification.', tr: 'Mekanik sign-off + müfettiş doğrulama.' },
      { en: 'Stamp ID on sign-off.', tr: 'Sign-off\'ta stamp ID.' },
    ],
    relatedTerms: ['CRS', 'inspector', 'stamp'],
  },
  { id: 'voc_tech_057', term: 'inspector', termTr: 'müfettiş (QC)', pronunciation: '/ɪnˈspek.tər/', category: 'staff', difficulty: 2,
    definitionEn: 'QC personnel who verifies maintenance work meets standards.',
    definitionTr: 'Bakım işinin standartlara uyduğunu doğrulayan QC personeli.',
    examples: [
      { en: 'Independent inspection required for critical work.', tr: 'Kritik iş için bağımsız muayene gerekli.' },
      { en: 'Inspector stamp ID: QC-247.', tr: 'Müfettiş stamp ID: QC-247.' },
    ],
    relatedTerms: ['QC', 'independent inspection', 'stamp'],
  },
  { id: 'voc_tech_058', term: 'hold tag', termTr: 'bekleme etiketi', pronunciation: '/həʊld tæɡ/', category: 'operations', difficulty: 3,
    definitionEn: 'Color-coded label indicating part status: yellow=under inspection, red=scrap, green=serviceable.',
    definitionTr: 'Parça durumunu gösteren renkli etiket: sarı=muayenede, kırmızı=hurda, yeşil=kullanılabilir.',
    examples: [
      { en: 'Yellow hold tag pending inspection.', tr: 'Sarı hold tag muayene bekliyor.' },
      { en: 'Red tag = scrap area.', tr: 'Kırmızı tag = hurda alanı.' },
    ],
    relatedTerms: ['serviceable', 'unserviceable', 'scrap'],
  },
  { id: 'voc_tech_059', term: 'FOD', termTr: 'FOD (Yabancı Cisim Hasarı)', pronunciation: '/fɒd/', category: 'safety', difficulty: 2,
    definitionEn: 'Foreign Object Damage/Debris — any object that can damage aircraft.',
    definitionTr: 'Yabancı Cisim Hasarı/Atıkları — uçağa zarar verebilecek herhangi bir cisim.',
    examples: [
      { en: 'FOD walk before closing engine.', tr: 'Motor kapatmadan FOD walk.' },
      { en: 'Tool inventory prevents FOD.', tr: 'Tool inventory FOD\'u önler.' },
    ],
    relatedTerms: ['FOD walk', 'tool inventory', 'magnetic pickup'],
  },
  { id: 'voc_tech_060', term: 'overhaul', termTr: 'overhaul (genel revizyon)', pronunciation: '/ˌəʊ.vəˈhɔːl/', category: 'operations', difficulty: 3,
    definitionEn: 'Complete disassembly, inspection, repair, and reassembly of a component.',
    definitionTr: 'Bir komponentin tam söküm, muayene, tamir ve yeniden montajı.',
    examples: [
      { en: 'Engine overhaul every 10,000 hours.', tr: 'Motor overhaul her 10.000 saatte.' },
    ],
    relatedTerms: ['CMM', 'TBO', 'rebuild'],
  },
  // ===== ENGINE & POWERPLANT (10) =====
  { id: 'voc_tech_061', term: 'TBO', termTr: 'TBO (Overhaul Aralığı)', pronunciation: '/tiː biː əʊ/', category: 'operations', difficulty: 3,
    definitionEn: 'Time Between Overhauls — operating hours between scheduled overhauls.',
    definitionTr: 'Overhaul Aralığı — planlanmış overhaul\'lar arası çalışma saatleri.',
    examples: [{ en: 'Engine TBO 10,000 hours.', tr: 'Motor TBO 10.000 saat.' }],
    relatedTerms: ['overhaul', 'cycle limit', 'lifetime'],
  },
  { id: 'voc_tech_062', term: 'compressor', termTr: 'kompresör', pronunciation: '/kəmˈpres.ər/', category: 'engine', difficulty: 3,
    definitionEn: 'Section of jet engine that compresses incoming air.',
    definitionTr: 'Jet motorun gelen havayı sıkıştıran bölümü.',
    examples: [{ en: 'Low pressure compressor (LPC).', tr: 'Düşük basınç kompresörü (LPC).' }],
    relatedTerms: ['fan', 'turbine', 'combustion'],
  },
  { id: 'voc_tech_063', term: 'turbine', termTr: 'türbin', pronunciation: '/ˈtɜː.baɪn/', category: 'engine', difficulty: 3,
    definitionEn: 'Section that extracts energy from hot gas to drive compressor and fan.',
    definitionTr: 'Sıcak gazdan enerji alıp kompresör ve fanı çeviren bölüm.',
    examples: [{ en: 'High pressure turbine (HPT).', tr: 'Yüksek basınç türbini (HPT).' }],
    relatedTerms: ['compressor', 'combustion chamber', 'nozzle'],
  },
  { id: 'voc_tech_064', term: 'combustion chamber', termTr: 'yanma odası', pronunciation: '/kəmˈbʌs.tʃən ˈtʃeɪm.bər/', category: 'engine', difficulty: 3,
    definitionEn: 'Section where fuel is burned with compressed air to produce hot gas.',
    definitionTr: 'Yakıtın sıkıştırılmış hava ile yakıldığı sıcak gaz üretilen bölüm.',
    examples: [{ en: 'Combustion chamber operates at 1,500°C.', tr: 'Yanma odası 1.500°C\'de çalışır.' }],
    relatedTerms: ['compressor', 'turbine', 'fuel injection'],
  },
  { id: 'voc_tech_065', term: 'EGT', termTr: 'EGT (Egzoz Gaz Sıcaklığı)', pronunciation: '/iː dʒiː tiː/', category: 'engine', difficulty: 3,
    definitionEn: 'Exhaust Gas Temperature — critical engine performance indicator.',
    definitionTr: 'Egzoz Gaz Sıcaklığı — kritik motor performans göstergesi.',
    examples: [{ en: 'EGT redline: 950°C.', tr: 'EGT kırmızı çizgi: 950°C.' }],
    relatedTerms: ['hot start', 'thermocouple', 'engine indication'],
  },
  { id: 'voc_tech_066', term: 'N1', termTr: 'N1 (fan hızı)', pronunciation: '/en wʌn/', category: 'engine', difficulty: 3,
    definitionEn: 'Low pressure spool speed — typically the fan rotation speed.',
    definitionTr: 'Düşük basınç spool hızı — genellikle fan dönüş hızı.',
    examples: [{ en: 'Takeoff N1 92%.', tr: 'Kalkış N1 %92.' }],
    relatedTerms: ['N2', 'fan', 'thrust'],
  },
  { id: 'voc_tech_067', term: 'N2', termTr: 'N2 (yüksek basınç hızı)', pronunciation: '/en tuː/', category: 'engine', difficulty: 3,
    definitionEn: 'High pressure spool speed.',
    definitionTr: 'Yüksek basınç spool hızı.',
    examples: [{ en: 'N2 reaches 100% at full thrust.', tr: 'Tam itkide N2 %100\'e ulaşır.' }],
    relatedTerms: ['N1', 'compressor', 'turbine'],
  },
  { id: 'voc_tech_068', term: 'hot start', termTr: 'hot start (sıcak çalıştırma)', pronunciation: '/hɒt stɑːt/', category: 'engine', difficulty: 4,
    definitionEn: 'Engine start with EGT exceeding limits — abnormal condition.',
    definitionTr: 'EGT limitleri aşan motor çalıştırma — anormal durum.',
    examples: [{ en: 'Abort hot start, investigate.', tr: 'Hot start\'ı iptal, araştır.' }],
    relatedTerms: ['EGT', 'engine start', 'aborted start'],
  },
  { id: 'voc_tech_069', term: 'flame out', termTr: 'flame out (alev sönmesi)', pronunciation: '/fleɪm aʊt/', category: 'engine', difficulty: 4,
    definitionEn: 'Unintended extinction of combustion in jet engine.',
    definitionTr: 'Jet motorda istem dışı yanma sönmesi.',
    examples: [{ en: 'Flame out at high altitude.', tr: 'Yüksek irtifada flame out.' }],
    relatedTerms: ['relight', 'engine restart', 'fuel control'],
  },
  { id: 'voc_tech_070', term: 'thrust reverser', termTr: 'thrust reverser (ters itki)', pronunciation: '/θrʌst rɪˈvɜː.sər/', category: 'engine', difficulty: 4,
    definitionEn: 'Mechanism redirecting engine exhaust forward to slow aircraft after landing.',
    definitionTr: 'İniş sonrası uçağı yavaşlatmak için egzozu öne yönlendiren mekanizma.',
    examples: [{ en: 'Deploy reversers on touchdown.', tr: 'Touchdown\'da reverser aç.' }],
    relatedTerms: ['landing', 'rollout', 'exhaust'],
  },

  // ===== AVIONICS & ELECTRICAL (10) =====
  { id: 'voc_tech_071', term: 'avionics', termTr: 'avionik', pronunciation: '/ˌeɪ.viˈɒn.ɪks/', category: 'avionics', difficulty: 3,
    definitionEn: 'Aviation electronics — navigation, communication, and flight control systems.',
    definitionTr: 'Havacılık elektroniği — navigasyon, iletişim, uçuş kontrol sistemleri.',
    examples: [{ en: 'Avionics technician (B2 license).', tr: 'Avionik teknisyeni (B2 lisansı).' }],
    relatedTerms: ['B2', 'navigation', 'communication'],
  },
  { id: 'voc_tech_072', term: 'B1 license', termTr: 'B1 lisansı (mekanik)', pronunciation: '/biː wʌn ˈlaɪ.səns/', category: 'certification', difficulty: 4,
    definitionEn: 'EASA Part-66 license for mechanical maintenance.',
    definitionTr: 'Mekanik bakım için EASA Part-66 lisansı.',
    examples: [{ en: 'B1.1 = aeroplanes turbine.', tr: 'B1.1 = uçak türbin.' }],
    relatedTerms: ['B2', 'EASA Part-66', 'CRS'],
  },
  { id: 'voc_tech_073', term: 'B2 license', termTr: 'B2 lisansı (avionik)', pronunciation: '/biː tuː ˈlaɪ.səns/', category: 'certification', difficulty: 4,
    definitionEn: 'EASA Part-66 license for avionics maintenance.',
    definitionTr: 'Avionik bakım için EASA Part-66 lisansı.',
    examples: [{ en: 'B2 covers electrical and instruments.', tr: 'B2 elektrik ve aletleri kapsar.' }],
    relatedTerms: ['B1', 'avionics', 'EASA Part-66'],
  },
  { id: 'voc_tech_074', term: 'circuit breaker', termTr: 'devre kesici (sigorta)', pronunciation: '/ˈsɜː.kɪt ˈbreɪ.kər/', category: 'electrical', difficulty: 2,
    definitionEn: 'Switch that automatically interrupts current to protect circuit.',
    definitionTr: 'Devreyi korumak için akımı otomatik kesen anahtar.',
    examples: [{ en: 'Reset CB once if popped.', tr: 'CB attıysa bir kez resetle.' }],
    relatedTerms: ['CB', 'fuse', 'overload'],
  },
  { id: 'voc_tech_075', term: 'connector', termTr: 'konnektör', pronunciation: '/kəˈnek.tər/', category: 'electrical', difficulty: 2,
    definitionEn: 'Plug joining electrical wires to components.',
    definitionTr: 'Elektrik kablolarını komponentlere bağlayan fiş.',
    examples: [{ en: 'Inspect connector for corrosion.', tr: 'Konnektörü korozyon için kontrol.' }],
    relatedTerms: ['pin assignment', 'wiring', 'WDM'],
  },
  { id: 'voc_tech_076', term: 'pin assignment', termTr: 'pin atama', pronunciation: '/pɪn əˈsaɪn.mənt/', category: 'electrical', difficulty: 4,
    definitionEn: 'Specification of which signal goes to which pin in a connector.',
    definitionTr: 'Bir konnektörde hangi sinyalin hangi pine gittiğinin spesifikasyonu.',
    examples: [{ en: 'WDM shows pin assignment.', tr: 'WDM pin atamasını gösterir.' }],
    relatedTerms: ['connector', 'WDM', 'schematic'],
  },
  { id: 'voc_tech_077', term: 'wire bundle', termTr: 'kablo demeti', pronunciation: '/waɪər ˈbʌn.dəl/', category: 'electrical', difficulty: 3,
    definitionEn: 'Group of wires bundled together with ties or sleeves.',
    definitionTr: 'Bağ veya kılıfla birlikte demet edilmiş kablo grubu.',
    examples: [{ en: 'Wire bundle protected by sleeve.', tr: 'Kablo demeti kılıfla korunur.' }],
    relatedTerms: ['harness', 'sleeve', 'tie'],
  },
  { id: 'voc_tech_078', term: 'TR', termTr: 'TR (Transformatör Doğrultucu)', pronunciation: '/tiː ɑːr/', category: 'electrical', difficulty: 4,
    definitionEn: 'Transformer Rectifier — converts AC to DC for aircraft DC systems.',
    definitionTr: 'Transformatör Doğrultucu — AC\'yi DC\'ye çevirir.',
    examples: [{ en: 'TR feeds essential DC bus.', tr: 'TR essential DC bus\'ı besler.' }],
    relatedTerms: ['inverter', 'AC', 'DC bus'],
  },
  { id: 'voc_tech_079', term: 'inverter', termTr: 'invertör', pronunciation: '/ɪnˈvɜː.tər/', category: 'electrical', difficulty: 3,
    definitionEn: 'Converts DC to AC.',
    definitionTr: 'DC\'yi AC\'ye çevirir.',
    examples: [{ en: 'Static inverter for AC essential.', tr: 'AC essential için statik invertör.' }],
    relatedTerms: ['TR', 'AC', 'DC'],
  },
  { id: 'voc_tech_080', term: 'GPU', termTr: 'GPU (Yer Güç Ünitesi)', pronunciation: '/dʒiː piː juː/', category: 'electrical', difficulty: 2,
    definitionEn: 'Ground Power Unit — provides electrical power when engines are off.',
    definitionTr: 'Yer Güç Ünitesi — motorlar kapalıyken elektrik sağlar.',
    examples: [{ en: 'Connect GPU at gate.', tr: 'Gate\'te GPU bağla.' }],
    relatedTerms: ['external power', 'APU', 'GSE'],
  },

  // ===== STRUCTURE & SHEET METAL (10) =====
  { id: 'voc_tech_081', term: 'sheet metal', termTr: 'sac metal', pronunciation: '/ʃiːt ˈmet.əl/', category: 'structure', difficulty: 2,
    definitionEn: 'Aluminum or composite panels forming aircraft skin and structure.',
    definitionTr: 'Uçak skin ve yapısını oluşturan alüminyum veya kompozit paneller.',
    examples: [{ en: 'Sheet metal repair.', tr: 'Sac metal tamiri.' }],
    relatedTerms: ['skin', 'panel', 'structural repair'],
  },
  { id: 'voc_tech_082', term: 'skin', termTr: 'skin (dış kabuk)', pronunciation: '/skɪn/', category: 'structure', difficulty: 2,
    definitionEn: 'Outer surface of aircraft fuselage and wings.',
    definitionTr: 'Uçak gövdesi ve kanatlarının dış yüzeyi.',
    examples: [{ en: 'Skin crack found.', tr: 'Skin\'de çatlak bulundu.' }],
    relatedTerms: ['sheet metal', 'fuselage', 'wing'],
  },
  { id: 'voc_tech_083', term: 'frame', termTr: 'frame (gövde çerçevesi)', pronunciation: '/freɪm/', category: 'structure', difficulty: 3,
    definitionEn: 'Circular structural element forming the fuselage cross-section.',
    definitionTr: 'Gövde kesitini oluşturan dairesel yapısal eleman.',
    examples: [{ en: 'Frame inspection between sections.', tr: 'Bölümler arası frame muayenesi.' }],
    relatedTerms: ['stringer', 'fuselage', 'spar'],
  },
  { id: 'voc_tech_084', term: 'stringer', termTr: 'stringer (boyuna eleman)', pronunciation: '/ˈstrɪŋ.ər/', category: 'structure', difficulty: 3,
    definitionEn: 'Longitudinal structural element supporting the skin.',
    definitionTr: 'Skin\'i destekleyen boyuna yapısal eleman.',
    examples: [{ en: 'Stringer crack: SRM repair.', tr: 'Stringer çatlağı: SRM tamir.' }],
    relatedTerms: ['frame', 'skin', 'longeron'],
  },
  { id: 'voc_tech_085', term: 'spar', termTr: 'spar (kanat ana kirişi)', pronunciation: '/spɑːr/', category: 'structure', difficulty: 3,
    definitionEn: 'Main longitudinal structural member of the wing.',
    definitionTr: 'Kanadın ana boyuna yapısal elemanı.',
    examples: [{ en: 'Front spar carries main load.', tr: 'Ön spar ana yükü taşır.' }],
    relatedTerms: ['rib', 'wing structure', 'load'],
  },
  { id: 'voc_tech_086', term: 'rib', termTr: 'rib (kanat enine kiriş)', pronunciation: '/rɪb/', category: 'structure', difficulty: 3,
    definitionEn: 'Cross-sectional structural member of the wing maintaining its shape.',
    definitionTr: 'Kanadın enine kesit yapısal elemanı; şeklini korur.',
    examples: [{ en: 'Wing ribs every 15 inches.', tr: 'Her 15 inçte kanat rib\'i.' }],
    relatedTerms: ['spar', 'wing structure', 'airfoil'],
  },
  { id: 'voc_tech_087', term: 'composite', termTr: 'kompozit', pronunciation: '/ˈkɒm.pə.zɪt/', category: 'structure', difficulty: 3,
    definitionEn: 'Material made of fibers (carbon/glass) bonded with resin.',
    definitionTr: 'Reçineyle birleşmiş fiber (karbon/cam) malzeme.',
    examples: [{ en: '787 fuselage 50% composite.', tr: '787 gövdesi %50 kompozit.' }],
    relatedTerms: ['CFRP', 'carbon fiber', 'resin'],
  },
  { id: 'voc_tech_088', term: 'patch repair', termTr: 'yama tamiri', pronunciation: '/pætʃ rɪˈpeər/', category: 'repair', difficulty: 3,
    definitionEn: 'Sheet metal repair using a patch over damaged area per SRM.',
    definitionTr: 'SRM\'e göre hasarlı alana yama uygulayan sac metal tamiri.',
    examples: [{ en: 'Doubler patch + flush rivets.', tr: 'Doubler yama + flush rivet.' }],
    relatedTerms: ['SRM', 'doubler', 'rivet'],
  },
  { id: 'voc_tech_089', term: 'SRM', termTr: 'SRM (Yapısal Tamir El Kitabı)', pronunciation: '/es ɑːr em/', category: 'documentation', difficulty: 3,
    definitionEn: 'Structural Repair Manual — repair instructions for aircraft structure.',
    definitionTr: 'Yapısal Tamir El Kitabı — uçak yapısı için tamir talimatları.',
    examples: [{ en: 'SRM allowable damage limits.', tr: 'SRM kabul edilebilir hasar limitleri.' }],
    relatedTerms: ['AMM', 'allowable damage', 'repair scheme'],
  },
  { id: 'voc_tech_090', term: 'allowable damage', termTr: 'kabul edilebilir hasar', pronunciation: '/əˈlaʊ.ə.bəl ˈdæm.ɪdʒ/', category: 'inspection', difficulty: 3,
    definitionEn: 'Damage limits within which a part remains airworthy without repair.',
    definitionTr: 'Tamir gerektirmeden parçanın airworthy kaldığı hasar limitleri.',
    examples: [{ en: 'Dent within allowable: monitor.', tr: 'Dent kabul limit içinde: izle.' }],
    relatedTerms: ['SRM', 'damage limit', 'monitoring'],
  },

  // ===== HYDRAULIC & SPECIFIC (10) =====
  { id: 'voc_tech_091', term: 'EDP', termTr: 'EDP (motor tahrikli pompa)', pronunciation: '/iː diː piː/', category: 'hydraulic', difficulty: 3,
    definitionEn: 'Engine-Driven Pump — primary hydraulic pump powered by engine.',
    definitionTr: 'Motor Tahrikli Pompa — motorla beslenen ana hidrolik pompa.',
    examples: [{ en: 'EDP failure: switch to EMP.', tr: 'EDP arızası: EMP\'ye geç.' }],
    relatedTerms: ['EMP', 'hydraulic system', 'reservoir'],
  },
  { id: 'voc_tech_092', term: 'EMP', termTr: 'EMP (elektrik tahrikli pompa)', pronunciation: '/iː em piː/', category: 'hydraulic', difficulty: 3,
    definitionEn: 'Electric Motor Pump — backup hydraulic pump.',
    definitionTr: 'Elektrik Motor Pompası — yedek hidrolik pompa.',
    examples: [{ en: 'EMP runs on standby AC.', tr: 'EMP standby AC\'de çalışır.' }],
    relatedTerms: ['EDP', 'hydraulic', 'backup'],
  },
  { id: 'voc_tech_093', term: 'hydraulic reservoir', termTr: 'hidrolik rezervuar', pronunciation: '/haɪˈdrɔː.lɪk ˌrez.əˈvwɑːr/', category: 'hydraulic', difficulty: 3,
    definitionEn: 'Tank holding hydraulic fluid for the system.',
    definitionTr: 'Sistem için hidrolik akışkanı tutan tank.',
    examples: [{ en: 'Check fluid level on sight glass.', tr: 'Sight glass\'ta seviyeyi kontrol.' }],
    relatedTerms: ['hydraulic fluid', 'pressure', 'pump'],
  },
  { id: 'voc_tech_094', term: 'accumulator', termTr: 'akümülatör', pronunciation: '/əˈkjuː.mjə.leɪ.tər/', category: 'hydraulic', difficulty: 4,
    definitionEn: 'Hydraulic device storing pressurized fluid for emergency use.',
    definitionTr: 'Acil durum için basınçlı akışkan depolayan hidrolik cihaz.',
    examples: [{ en: 'Brake accumulator pre-charge 1500 PSI.', tr: 'Fren akümülatörü ön doluş 1500 PSI.' }],
    relatedTerms: ['hydraulic', 'emergency brake', 'pressure'],
  },
  { id: 'voc_tech_095', term: 'manual reversion', termTr: 'manuel reversion', pronunciation: '/ˈmæn.ju.əl rɪˈvɜː.ʒən/', category: 'flight_controls', difficulty: 4,
    definitionEn: 'Backup mode where pilot directly controls surfaces via cables.',
    definitionTr: 'Pilotun yüzeyleri kablolarla doğrudan kontrol ettiği yedek mod.',
    examples: [{ en: 'Manual reversion if hydraulic fails.', tr: 'Hidrolik arızasında manuel reversion.' }],
    relatedTerms: ['hydraulic failure', 'cable', 'backup'],
  },
  { id: 'voc_tech_096', term: 'inspection mirror', termTr: 'muayene aynası', pronunciation: '/ɪnˈspek.ʃən ˈmɪr.ər/', category: 'tools', difficulty: 1,
    definitionEn: 'Telescoping mirror for inspecting hard-to-see areas.',
    definitionTr: 'Görmesi zor alanları muayene için teleskopik ayna.',
    examples: [{ en: 'Inspection mirror under wing.', tr: 'Kanat altında muayene aynası.' }],
    relatedTerms: ['flashlight', 'visual inspection', 'borescope'],
  },
  { id: 'voc_tech_097', term: 'flashlight', termTr: 'el feneri', pronunciation: '/ˈflæʃ.laɪt/', category: 'tools', difficulty: 1,
    definitionEn: 'Portable light source for inspection in low-light areas.',
    definitionTr: 'Düşük ışıklı alanlarda muayene için taşınabilir ışık kaynağı.',
    examples: [{ en: 'LED flashlight preferred.', tr: 'LED el feneri tercih.' }],
    relatedTerms: ['inspection mirror', 'visual inspection'],
  },
  { id: 'voc_tech_098', term: 'thrust bearing', termTr: 'tork rulmanı', pronunciation: '/θrʌst ˈbeə.rɪŋ/', category: 'engine', difficulty: 4,
    definitionEn: 'Bearing absorbing thrust loads in engine or component.',
    definitionTr: 'Motor veya komponentte itki yüklerini emen rulman.',
    examples: [{ en: 'Thrust bearing wear monitored.', tr: 'Tork rulman aşınması izlenir.' }],
    relatedTerms: ['bearing', 'shaft', 'wear'],
  },
  { id: 'voc_tech_099', term: 'spectrometric oil analysis', termTr: 'yağ analizi (spektrometri)', pronunciation: '/spek.trəˈmet.rɪk ɔɪl əˈnæl.ə.sɪs/', category: 'inspection', difficulty: 5,
    definitionEn: 'SOAP — analyzes engine oil for metal particles indicating wear.',
    definitionTr: 'SOAP — aşınma gösteren metal parçacıkları için motor yağı analizi.',
    examples: [{ en: 'SOAP detects bearing wear early.', tr: 'SOAP rulman aşınmasını erken tespit eder.' }],
    relatedTerms: ['SOAP', 'engine health', 'oil sample'],
  },
  { id: 'voc_tech_100', term: 'maintenance error', termTr: 'bakım hatası', pronunciation: '/ˈmeɪn.tən.əns ˈer.ər/', category: 'safety', difficulty: 3,
    definitionEn: 'Mistake during maintenance contributing to accidents or incidents.',
    definitionTr: 'Kazaya/olaya yol açan bakım sırasındaki hata.',
    examples: [{ en: '15% of accidents linked to maintenance error.', tr: 'Kazaların %15\'i bakım hatasına bağlı.' }],
    relatedTerms: ['human factors', 'safety culture', 'investigation'],
  },

  // ===== FAZ 2 ADVANCED (40) =====
  // Routine Maintenance (10)
  { id: 'voc_tech_101', term: 'line maintenance', termTr: 'hat bakımı', pronunciation: '/laɪn ˈmeɪn.tən.əns/', category: 'operations', difficulty: 3,
    definitionEn: 'Routine work between flights at the gate or apron.', definitionTr: 'Gate veya apron\'da uçuşlar arası rutin iş.',
    examples: [{ en: 'Line maintenance between flights.', tr: 'Uçuşlar arası line maintenance.' }],
    relatedTerms: ['turnaround', 'transit check', 'apron'],
  },
  { id: 'voc_tech_102', term: 'base maintenance', termTr: 'üs bakımı', pronunciation: '/beɪs ˈmeɪn.tən.əns/', category: 'operations', difficulty: 3,
    definitionEn: 'Heavy maintenance in hangar — A-check, C-check, D-check.', definitionTr: 'Hangarda ağır bakım — A-check, C-check, D-check.',
    examples: [{ en: 'D-check every 6-10 years.', tr: 'D-check her 6-10 yılda.' }],
    relatedTerms: ['hangar', 'A-check', 'overhaul'],
  },
  { id: 'voc_tech_103', term: 'A-check', termTr: 'A-check (hafif bakım)', pronunciation: '/eɪ tʃek/', category: 'operations', difficulty: 3,
    definitionEn: 'Light scheduled maintenance every 500-800 flight hours.', definitionTr: 'Her 500-800 uçuş saatinde hafif planlı bakım.',
    examples: [{ en: 'A-check overnight.', tr: 'Gece A-check.' }],
    relatedTerms: ['B-check', 'C-check', 'scheduled'],
  },
  { id: 'voc_tech_104', term: 'C-check', termTr: 'C-check (orta bakım)', pronunciation: '/siː tʃek/', category: 'operations', difficulty: 3,
    definitionEn: 'Heavy scheduled maintenance every 18-24 months.', definitionTr: 'Her 18-24 ayda ağır planlı bakım.',
    examples: [{ en: 'C-check 1-2 weeks downtime.', tr: 'C-check 1-2 hafta downtime.' }],
    relatedTerms: ['A-check', 'D-check', 'hangar'],
  },
  { id: 'voc_tech_105', term: 'D-check', termTr: 'D-check (büyük bakım)', pronunciation: '/diː tʃek/', category: 'operations', difficulty: 3,
    definitionEn: 'Most extensive scheduled maintenance — disassembly + inspection.', definitionTr: 'En kapsamlı planlı bakım — söküm + muayene.',
    examples: [{ en: 'D-check 1 month, $1M+ cost.', tr: 'D-check 1 ay, $1M+ maliyet.' }],
    relatedTerms: ['heavy maintenance', 'C-check', 'overhaul'],
  },
  { id: 'voc_tech_106', term: 'transit check', termTr: 'transit kontrolü', pronunciation: '/ˈtræn.zɪt tʃek/', category: 'inspection', difficulty: 2,
    definitionEn: 'Quick check between turnaround flights — fluid levels, tire pressure.', definitionTr: 'Turnaround uçuşları arası hızlı kontrol — sıvı seviyeleri, lastik basıncı.',
    examples: [{ en: 'Transit check 30 min.', tr: 'Transit check 30 dk.' }],
    relatedTerms: ['line maintenance', 'turnaround', 'walk-around'],
  },
  { id: 'voc_tech_107', term: 'daily check', termTr: 'günlük kontrol', pronunciation: '/ˈdeɪ.li tʃek/', category: 'inspection', difficulty: 2,
    definitionEn: 'Inspection performed once per 24 hours, regardless of flights.', definitionTr: 'Uçuş bağımsız 24 saatte bir yapılan muayene.',
    examples: [{ en: 'Daily check before first flight.', tr: 'İlk uçuştan önce daily check.' }],
    relatedTerms: ['transit check', 'line maintenance', 'inspection'],
  },
  { id: 'voc_tech_108', term: 'tire pressure', termTr: 'lastik basıncı', pronunciation: '/taɪər ˈpreʃ.ər/', category: 'inspection', difficulty: 1,
    definitionEn: 'Air pressure inside aircraft tires — critical for safe operations.', definitionTr: 'Uçak lastiklerindeki hava basıncı — güvenli operasyon için kritik.',
    examples: [{ en: 'Check tire pressure daily.', tr: 'Günlük lastik basıncı kontrolü.' }],
    relatedTerms: ['tire wear', 'daily check', 'PSI'],
  },
  { id: 'voc_tech_109', term: 'oil service', termTr: 'yağ servisi', pronunciation: '/ɔɪl ˈsɜː.vɪs/', category: 'engine', difficulty: 2,
    definitionEn: 'Adding/changing engine oil to maintain proper levels.', definitionTr: 'Doğru seviyeleri korumak için motor yağı ekleme/değiştirme.',
    examples: [{ en: 'Oil service per AMM.', tr: 'AMM\'e göre oil service.' }],
    relatedTerms: ['oil filter', 'oil pressure', 'engine'],
  },
  { id: 'voc_tech_110', term: 'brake wear', termTr: 'fren aşınması', pronunciation: '/breɪk weər/', category: 'inspection', difficulty: 3,
    definitionEn: 'Decrease in brake disc thickness from use.', definitionTr: 'Kullanımla fren disk kalınlığında azalma.',
    examples: [{ en: 'Brake wear indicator.', tr: 'Fren aşınma göstergesi.' }],
    relatedTerms: ['brake', 'wear limit', 'replacement'],
  },

  // Defect investigation (10)
  { id: 'voc_tech_111', term: 'troubleshooting', termTr: 'sorun giderme', pronunciation: '/ˈtrʌb.əlˌʃuː.tɪŋ/', category: 'inspection', difficulty: 2,
    definitionEn: 'Systematic process of identifying root cause of fault.', definitionTr: 'Arızanın kök sebebini sistematik tanımlama süreci.',
    examples: [{ en: 'Use TSM for troubleshooting.', tr: 'Troubleshooting için TSM kullan.' }],
    relatedTerms: ['TSM', 'fault isolation', 'diagnosis'],
  },
  { id: 'voc_tech_112', term: 'fault code', termTr: 'arıza kodu', pronunciation: '/fɔːlt kəʊd/', category: 'inspection', difficulty: 3,
    definitionEn: 'Numeric code from BITE indicating specific failure.', definitionTr: 'Belirli arızayı bildiren BITE\'tan sayısal kod.',
    examples: [{ en: 'Fault code 24-21-002.', tr: 'Arıza kodu 24-21-002.' }],
    relatedTerms: ['BITE', 'CFDS', 'diagnostic'],
  },
  { id: 'voc_tech_113', term: 'BITE', termTr: 'BITE (yerleşik test ekipmanı)', pronunciation: '/baɪt/', category: 'systems', difficulty: 4,
    definitionEn: 'Built-In Test Equipment — onboard diagnostic system.', definitionTr: 'Yerleşik Test Ekipmanı — uçak içi tanı sistemi.',
    examples: [{ en: 'BITE menu in cockpit.', tr: 'Kokpitte BITE menüsü.' }],
    relatedTerms: ['CFDS', 'fault code', 'diagnostic'],
  },
  { id: 'voc_tech_114', term: 'CFDS', termTr: 'CFDS (merkezi arıza ekran sistemi)', pronunciation: '/siː ef diː es/', category: 'systems', difficulty: 5,
    definitionEn: 'Centralized Fault Display System — Airbus equivalent of BITE.', definitionTr: 'Merkezi Arıza Ekran Sistemi — BITE\'ın Airbus muadili.',
    examples: [{ en: 'CFDS shows post-flight report.', tr: 'CFDS uçuş sonrası rapor gösterir.' }],
    relatedTerms: ['BITE', 'PFR', 'fault code'],
  },
  { id: 'voc_tech_115', term: 'intermittent fault', termTr: 'aralıklı arıza', pronunciation: '/ˌɪn.təˈmɪt.ənt fɔːlt/', category: 'inspection', difficulty: 4,
    definitionEn: 'Fault appearing and disappearing — hardest to diagnose.', definitionTr: 'Beliren ve kaybolan arıza — tanısı en zor.',
    examples: [{ en: 'Intermittent fault: trace wiring.', tr: 'Aralıklı arıza: kabloyu izle.' }],
    relatedTerms: ['troubleshooting', 'wiring', 'NFF'],
  },
  { id: 'voc_tech_116', term: 'NFF', termTr: 'NFF (arıza bulunamadı)', pronunciation: '/en ef ef/', category: 'inspection', difficulty: 4,
    definitionEn: 'No Fault Found — when reported issue cannot be reproduced.', definitionTr: 'Arıza Bulunamadı — raporlanan sorun tekrarlanmazsa.',
    examples: [{ en: 'NFF after extended test.', tr: 'Uzun test sonrası NFF.' }],
    relatedTerms: ['intermittent', 'reproducibility', 'NTF'],
  },
  { id: 'voc_tech_117', term: 'wiring trace', termTr: 'kablo izleme', pronunciation: '/ˈwaɪə.rɪŋ treɪs/', category: 'electrical', difficulty: 4,
    definitionEn: 'Following wires through aircraft to find break or short.', definitionTr: 'Kopukluk veya kısa devre bulmak için kabloları izleme.',
    examples: [{ en: 'Wiring trace via WDM.', tr: 'WDM ile wiring trace.' }],
    relatedTerms: ['WDM', 'continuity', 'troubleshooting'],
  },
  { id: 'voc_tech_118', term: 'continuity check', termTr: 'süreklilik testi', pronunciation: '/ˌkɒn.tɪˈnjuː.ə.ti tʃek/', category: 'electrical', difficulty: 3,
    definitionEn: 'Verifying complete electrical path with multimeter.', definitionTr: 'Multimetre ile tam elektrik yolunu doğrulama.',
    examples: [{ en: 'Continuity check passed.', tr: 'Süreklilik testi geçti.' }],
    relatedTerms: ['multimeter', 'wire trace', 'open circuit'],
  },
  { id: 'voc_tech_119', term: 'short circuit', termTr: 'kısa devre', pronunciation: '/ʃɔːt ˈsɜː.kɪt/', category: 'electrical', difficulty: 3,
    definitionEn: 'Unintended low-resistance path causing excess current.', definitionTr: 'Aşırı akıma yol açan istem dışı düşük dirençli yol.',
    examples: [{ en: 'Short circuit trips CB.', tr: 'Kısa devre CB attırır.' }],
    relatedTerms: ['CB', 'wiring', 'overcurrent'],
  },
  { id: 'voc_tech_120', term: 'open circuit', termTr: 'açık devre', pronunciation: '/ˈəʊ.pən ˈsɜː.kɪt/', category: 'electrical', difficulty: 3,
    definitionEn: 'Broken electrical path preventing current flow.', definitionTr: 'Akım akışını engelleyen kopuk elektrik yolu.',
    examples: [{ en: 'Open circuit at connector.', tr: 'Konnektörde açık devre.' }],
    relatedTerms: ['continuity', 'wire break', 'connector'],
  },

  // Engine maintenance (10)
  { id: 'voc_tech_121', term: 'borescope inspection', termTr: 'borescope muayenesi', pronunciation: '/ˈbɔː.skəʊp ɪnˈspek.ʃən/', category: 'engine', difficulty: 4,
    definitionEn: 'Internal engine inspection without disassembly.', definitionTr: 'Söküm olmadan iç motor muayenesi.',
    examples: [{ en: 'Borescope every 600 cycles.', tr: 'Her 600 cycle\'da borescope.' }],
    relatedTerms: ['compressor blade', 'turbine', 'on-wing'],
  },
  { id: 'voc_tech_122', term: 'compressor blade', termTr: 'kompresör palesi', pronunciation: '/kəmˈpres.ər bleɪd/', category: 'engine', difficulty: 4,
    definitionEn: 'Rotating airfoil in compressor — vulnerable to FOD damage.', definitionTr: 'Kompresördeki dönen airfoil — FOD hasarına açık.',
    examples: [{ en: 'Blade dent within limits.', tr: 'Pale göçüğü limit dahilinde.' }],
    relatedTerms: ['FOD', 'turbine blade', 'borescope'],
  },
  { id: 'voc_tech_123', term: 'turbine blade', termTr: 'türbin palesi', pronunciation: '/ˈtɜː.baɪn bleɪd/', category: 'engine', difficulty: 4,
    definitionEn: 'Hot section blade exposed to extreme temperatures.', definitionTr: 'Aşırı sıcaklığa maruz sıcak bölüm palesi.',
    examples: [{ en: 'Hot section TBO 5000 hours.', tr: 'Sıcak bölüm TBO 5000 saat.' }],
    relatedTerms: ['hot section', 'cooling', 'cycle limit'],
  },
  { id: 'voc_tech_124', term: 'compressor wash', termTr: 'kompresör yıkama', pronunciation: '/kəmˈpres.ər wɒʃ/', category: 'engine', difficulty: 4,
    definitionEn: 'Cleaning compressor blades with water/cleaner to restore performance.', definitionTr: 'Performansı geri kazanmak için kompresör palelerini su/temizleyici ile temizleme.',
    examples: [{ en: 'Compressor wash improves EGT.', tr: 'Compressor wash EGT\'yi iyileştirir.' }],
    relatedTerms: ['engine performance', 'EGT', 'on-wing'],
  },
  { id: 'voc_tech_125', term: 'on-wing maintenance', termTr: 'on-wing bakım', pronunciation: '/ɒn wɪŋ ˈmeɪn.tən.əns/', category: 'engine', difficulty: 4,
    definitionEn: 'Maintenance with engine still attached to aircraft.', definitionTr: 'Motor uçağa bağlı haldeyken yapılan bakım.',
    examples: [{ en: 'On-wing borescope.', tr: 'On-wing borescope.' }],
    relatedTerms: ['off-wing', 'engine change', 'AOG'],
  },
  { id: 'voc_tech_126', term: 'engine change', termTr: 'motor değişimi', pronunciation: '/ˈen.dʒɪn tʃeɪndʒ/', category: 'engine', difficulty: 4,
    definitionEn: 'Removing and installing a different engine.', definitionTr: 'Bir motoru sökme ve farklısını takma.',
    examples: [{ en: 'Engine change 24-48h.', tr: 'Engine change 24-48 saat.' }],
    relatedTerms: ['QEC', 'pylon', 'engine mount'],
  },
  { id: 'voc_tech_127', term: 'QEC', termTr: 'QEC (Hızlı Motor Değişim Kiti)', pronunciation: '/kjuː iː siː/', category: 'engine', difficulty: 5,
    definitionEn: 'Quick Engine Change kit — accessories for rapid engine swap.', definitionTr: 'Hızlı Motor Değişim kiti — hızlı motor takas için aksesuarlar.',
    examples: [{ en: 'QEC includes thrust reverser.', tr: 'QEC thrust reverser içerir.' }],
    relatedTerms: ['engine change', 'thrust reverser', 'cowling'],
  },
  { id: 'voc_tech_128', term: 'engine run-up', termTr: 'motor çalıştırma testi', pronunciation: '/ˈen.dʒɪn ˈrʌn.ʌp/', category: 'engine', difficulty: 4,
    definitionEn: 'Ground test of engine performance after maintenance.', definitionTr: 'Bakım sonrası motor performansının yer testi.',
    examples: [{ en: 'Run-up after engine change.', tr: 'Engine change sonrası run-up.' }],
    relatedTerms: ['ground run', 'leak check', 'engine test'],
  },
  { id: 'voc_tech_129', term: 'EGT trend monitoring', termTr: 'EGT trend izleme', pronunciation: '/iː dʒiː tiː trend ˈmɒn.ɪ.tər.ɪŋ/', category: 'engine', difficulty: 5,
    definitionEn: 'Tracking EGT over time to detect engine degradation early.', definitionTr: 'Motor bozulmasını erken tespit için EGT trendini izleme.',
    examples: [{ en: 'EGT margin decreases over time.', tr: 'EGT margin zamanla azalır.' }],
    relatedTerms: ['EGT', 'engine health', 'CBM'],
  },
  { id: 'voc_tech_130', term: 'pylon', termTr: 'pylon (motor desteği)', pronunciation: '/ˈpaɪ.lɒn/', category: 'engine', difficulty: 4,
    definitionEn: 'Structure attaching engine to wing or fuselage.', definitionTr: 'Motoru kanada veya gövdeye bağlayan yapı.',
    examples: [{ en: 'Pylon inspection during C-check.', tr: 'C-check\'te pylon muayenesi.' }],
    relatedTerms: ['engine mount', 'cowling', 'wing'],
  },

  // Hydraulic & advanced (10)
  { id: 'voc_tech_131', term: 'hydraulic fluid', termTr: 'hidrolik akışkan', pronunciation: '/haɪˈdrɔː.lɪk ˈfluː.ɪd/', category: 'hydraulic', difficulty: 3,
    definitionEn: 'Specialized fluid (Skydrol/HyJet) for aircraft hydraulic systems.', definitionTr: 'Uçak hidrolik sistemleri için özel akışkan (Skydrol/HyJet).',
    examples: [{ en: 'Skydrol fire-resistant.', tr: 'Skydrol yangına dayanıklı.' }],
    relatedTerms: ['Skydrol', 'reservoir', 'pressure'],
  },
  { id: 'voc_tech_132', term: 'Skydrol', termTr: 'Skydrol (hidrolik akışkan markası)', pronunciation: '/ˈskaɪ.drɒl/', category: 'hydraulic', difficulty: 3,
    definitionEn: 'Brand of phosphate-ester hydraulic fluid, fire-resistant.', definitionTr: 'Yangına dayanıklı fosfat-ester hidrolik akışkan markası.',
    examples: [{ en: 'Skydrol LD-4.', tr: 'Skydrol LD-4.' }],
    relatedTerms: ['hydraulic fluid', 'fire-resistant', 'phosphate'],
  },
  { id: 'voc_tech_133', term: 'hydraulic leak', termTr: 'hidrolik kaçağı', pronunciation: '/haɪˈdrɔː.lɪk liːk/', category: 'hydraulic', difficulty: 3,
    definitionEn: 'Loss of hydraulic fluid through fitting or seal.', definitionTr: 'Bağlantı veya seal\'dan hidrolik akışkan kaybı.',
    examples: [{ en: 'Trace leak with UV light.', tr: 'UV ışıkla kaçağı izle.' }],
    relatedTerms: ['leak detection', 'seal', 'fitting'],
  },
  { id: 'voc_tech_134', term: 'pressure test', termTr: 'basınç testi', pronunciation: '/ˈpreʃ.ər test/', category: 'hydraulic', difficulty: 3,
    definitionEn: 'Verifying hydraulic system holds pressure without leak.', definitionTr: 'Hidrolik sistemin sızıntısız basınç tuttuğunu doğrulama.',
    examples: [{ en: 'Pressure test post-repair.', tr: 'Tamir sonrası pressure test.' }],
    relatedTerms: ['leak check', 'hydraulic', 'system test'],
  },
  { id: 'voc_tech_135', term: 'filter change', termTr: 'filtre değişimi', pronunciation: '/ˈfɪl.tər tʃeɪndʒ/', category: 'inspection', difficulty: 2,
    definitionEn: 'Replacing system filter to remove contaminants.', definitionTr: 'Kirleticiyi kaldırmak için sistem filtresini değiştirme.',
    examples: [{ en: 'Hydraulic filter every 600 hours.', tr: 'Hidrolik filtre her 600 saatte.' }],
    relatedTerms: ['hydraulic', 'fuel filter', 'oil filter'],
  },
  { id: 'voc_tech_136', term: 'particle count', termTr: 'parçacık sayımı', pronunciation: '/ˈpɑː.tɪ.kəl kaʊnt/', category: 'inspection', difficulty: 5,
    definitionEn: 'Cleanliness measure of hydraulic fluid via NAS 1638 code.', definitionTr: 'NAS 1638 koduyla hidrolik akışkan temizlik ölçümü.',
    examples: [{ en: 'NAS class 9 acceptable.', tr: 'NAS sınıf 9 kabul.' }],
    relatedTerms: ['contamination', 'NAS', 'hydraulic fluid'],
  },
  { id: 'voc_tech_137', term: 'CBM', termTr: 'CBM (Durum Bazlı Bakım)', pronunciation: '/siː biː em/', category: 'operations', difficulty: 5,
    definitionEn: 'Condition-Based Maintenance — predictive vs scheduled.', definitionTr: 'Durum Bazlı Bakım — planlı yerine kestirimsel.',
    examples: [{ en: 'CBM uses sensor data.', tr: 'CBM sensör verisi kullanır.' }],
    relatedTerms: ['predictive', 'scheduled', 'health monitoring'],
  },
  { id: 'voc_tech_138', term: 'reliability', termTr: 'güvenilirlik', pronunciation: '/rɪˌlaɪ.əˈbɪl.ə.ti/', category: 'operations', difficulty: 3,
    definitionEn: 'Probability that a component will perform without failure.', definitionTr: 'Bir komponentin arıza olmadan çalışma olasılığı.',
    examples: [{ en: 'MTBF: Mean Time Between Failures.', tr: 'MTBF: Arızalar Arası Ortalama Süre.' }],
    relatedTerms: ['MTBF', 'dispatch reliability', 'redundancy'],
  },
  { id: 'voc_tech_139', term: 'redundancy', termTr: 'yedeklilik', pronunciation: '/rɪˈdʌn.dən.si/', category: 'systems', difficulty: 4,
    definitionEn: 'Backup systems ensuring safety if primary fails.', definitionTr: 'Birincil arızalanırsa güvenliği sağlayan yedek sistemler.',
    examples: [{ en: 'Triple redundancy in flight controls.', tr: 'Uçuş kontrollerinde üçlü redundancy.' }],
    relatedTerms: ['backup', 'fail-safe', 'system architecture'],
  },
  { id: 'voc_tech_140', term: 'continuing airworthiness', termTr: 'sürekli airworthiness', pronunciation: '/kənˈtɪn.juː.ɪŋ ˈeə.wɜː.ðɪ.nəs/', category: 'certification', difficulty: 5,
    definitionEn: 'Ensuring aircraft remains airworthy throughout its service life.', definitionTr: 'Uçağın hizmet ömrü boyunca airworthy kalmasını sağlama.',
    examples: [{ en: 'CAMO oversees continuing airworthiness.', tr: 'CAMO continuing airworthiness gözetir.' }],
    relatedTerms: ['CAMO', 'EASA Part-M', 'maintenance program'],
  },
];
