/**
 * Teknisyen Faz 1 — İlk 10 vocabulary term seed verisi.
 */
import type { VocabularyTerm } from './pilotVocab';

export const TECHNICIAN_VOCAB_FAZ1: VocabularyTerm[] = [
  {
    id: 'voc_tech_001',
    term: 'AMM',
    termTr: 'AMM (Bakım El Kitabı)',
    pronunciation: '/eɪ em em/',
    category: 'documentation',
    difficulty: 2,
    definitionEn: 'Aircraft Maintenance Manual — OEM-issued document with all maintenance instructions per ATA chapter.',
    definitionTr: 'Uçak Bakım El Kitabı — OEM tarafından yayımlanan, ATA bölümüne göre tüm bakım talimatları.',
    examples: [
      { en: 'Always reference the latest AMM revision.', tr: 'Daima son AMM revizyonuna başvur.' },
      { en: 'AMM 32-11-00 covers main landing gear.', tr: 'AMM 32-11-00 ana iniş takımını kapsar.' },
    ],
    icaoReference: 'EASA Part-M / FAA 14 CFR Part 43',
    relatedTerms: ['CMM', 'IPC', 'WDM', 'TSM'],
  },
  {
    id: 'voc_tech_002',
    term: 'torque wrench',
    termTr: 'tork anahtarı',
    pronunciation: '/tɔːk rentʃ/',
    category: 'tools',
    difficulty: 1,
    definitionEn: 'Precision tool that applies a specific rotational force (torque) to a fastener.',
    definitionTr: 'Bir bağlantı elemanına belirli dönme kuvveti uygulayan hassas alet.',
    examples: [
      { en: 'Calibration sticker must be valid before use.', tr: 'Kullanmadan önce kalibrasyon etiketi geçerli olmalı.' },
      { en: 'Apply torque per AMM in 3 passes: 30%, 70%, 100%.', tr: 'AMM\'e göre 3 paste tork: %30, %70, %100.' },
    ],
    relatedTerms: ['torque seal', 'calibration', 'wrench'],
  },
  {
    id: 'voc_tech_003',
    term: 'NDT',
    termTr: 'NDT (Tahribatsız Muayene)',
    pronunciation: '/en diː tiː/',
    category: 'inspection',
    difficulty: 3,
    definitionEn: 'Non-Destructive Testing — methods to detect defects without damaging the part: MPI, FPI, eddy current, ultrasonic.',
    definitionTr: 'Tahribatsız Muayene — parçaya zarar vermeden hata tespiti: MPI, FPI, eddy current, ultrasonic.',
    examples: [
      { en: 'NDT Level 2 inspector certified for MPI.', tr: 'NDT Level 2 müfettiş MPI için sertifikalı.' },
      { en: 'Eddy current detects subsurface defects.', tr: 'Eddy current yüzey altı hataları tespit eder.' },
    ],
    icaoReference: 'EN 4179 / NAS 410',
    relatedTerms: ['MPI', 'FPI', 'ultrasonic', 'inspector'],
  },
  {
    id: 'voc_tech_004',
    term: 'service bulletin',
    termTr: 'servis bülteni (SB)',
    pronunciation: '/ˈsɜː.vɪs ˈbʊl.ə.tɪn/',
    category: 'documentation',
    difficulty: 3,
    definitionEn: 'Manufacturer-issued document recommending modifications, inspections, or procedure updates.',
    definitionTr: 'Üretici tarafından yayımlanan modifikasyon, muayene veya prosedür güncellemesi öneren belge.',
    examples: [
      { en: 'SB 737-32-1234 recommends MLG inspection.', tr: 'SB 737-32-1234 MLG muayenesini önerir.' },
      { en: 'If AD references SB, compliance becomes mandatory.', tr: 'AD bu SB\'ye atıf yaparsa uyum zorunlu olur.' },
    ],
    relatedTerms: ['AD', 'modification', 'compliance'],
  },
  {
    id: 'voc_tech_005',
    term: 'EASA Form 1',
    termTr: 'EASA Form 1',
    pronunciation: '/ˈiː.zə fɔːm wʌn/',
    category: 'certification',
    difficulty: 4,
    definitionEn: 'European authorized release certificate confirming a part is airworthy after manufacture, repair, or overhaul.',
    definitionTr: 'Bir parçanın üretim, tamir veya overhaul sonrası airworthy olduğunu onaylayan Avrupa sertifikası.',
    examples: [
      { en: 'Every overhauled component leaves with EASA Form 1.', tr: 'Her overhaul edilmiş parça EASA Form 1 ile çıkar.' },
      { en: 'FAA equivalent is Form 8130-3.', tr: 'FAA muadili Form 8130-3.' },
    ],
    icaoReference: 'EASA Part-145',
    relatedTerms: ['Form 8130-3', 'CRS', 'airworthy'],
  },
  {
    id: 'voc_tech_006',
    term: 'lockwire',
    termTr: 'kilit teli (safety wire)',
    pronunciation: '/ˈlɒk.waɪər/',
    category: 'hardware',
    difficulty: 2,
    definitionEn: 'Stainless steel wire used to secure fasteners against vibration loosening.',
    definitionTr: 'Bağlantı elemanlarını titreşimle gevşemeye karşı kilitlemek için kullanılan paslanmaz çelik tel.',
    examples: [
      { en: 'Lockwire pliers twist the wire in pull direction.', tr: 'Lockwire pensesi teli çekme yönünde bükmeli.' },
      { en: 'Cut excess lockwire — no FOD allowed.', tr: 'Fazla teli kes — FOD yasak.' },
    ],
    relatedTerms: ['cotter pin', 'torque seal', 'fastener'],
  },
  {
    id: 'voc_tech_007',
    term: 'borescope',
    termTr: 'borescope (iç görüş cihazı)',
    pronunciation: '/ˈbɔːr.skəʊp/',
    category: 'tools',
    difficulty: 3,
    definitionEn: 'Flexible camera used to inspect internal aircraft components without disassembly.',
    definitionTr: 'Demonte etmeden uçak iç parçalarını görsel muayene için kullanılan esnek kamera.',
    examples: [
      { en: 'Borescope inspect after engine overhaul.', tr: 'Motor overhaul sonrası borescope muayene.' },
      { en: 'Document findings with photo capture.', tr: 'Bulguları foto kaydıyla belgele.' },
    ],
    relatedTerms: ['compressor blade', 'turbine', 'visual inspection'],
  },
  {
    id: 'voc_tech_008',
    term: 'ATA chapter',
    termTr: 'ATA bölüm sistemi',
    pronunciation: '/eɪ tiː eɪ ˈtʃæp.tər/',
    category: 'documentation',
    difficulty: 3,
    definitionEn: 'Air Transport Association numbering system for aircraft systems (ATA 21=A/C, 24=Electrical, 32=Gear, etc.)',
    definitionTr: 'Uçak sistemleri için Air Transport Association numaralandırması (ATA 21=Klima, 24=Elektrik, 32=İniş takımı...)',
    examples: [
      { en: 'Look up ATA 49 for APU procedures.', tr: 'APU prosedürleri için ATA 49\'a bak.' },
      { en: 'AMM 32-11-00: chapter 32, section 11.', tr: 'AMM 32-11-00: bölüm 32, kısım 11.' },
    ],
    relatedTerms: ['AMM', 'IPC', 'WDM'],
  },
  {
    id: 'voc_tech_009',
    term: 'corrosion',
    termTr: 'korozyon',
    pronunciation: '/kəˈrəʊ.ʒən/',
    category: 'defect',
    difficulty: 2,
    definitionEn: 'Chemical degradation of metal — pitting, intergranular, exfoliation types.',
    definitionTr: 'Metalin kimyasal bozulması — pitting (delik), intergranular, exfoliation türleri.',
    examples: [
      { en: 'Pitting corrosion found on lower wing skin.', tr: 'Alt kanat skin\'inde pitting korozyon bulundu.' },
      { en: 'Apply corrosion inhibitor after cleaning.', tr: 'Temizleme sonrası korozyon önleyici uygula.' },
    ],
    relatedTerms: ['pitting', 'fatigue', 'inspection'],
  },
  {
    id: 'voc_tech_010',
    term: 'AOG',
    termTr: 'AOG (Aircraft on Ground)',
    pronunciation: '/eɪ əʊ dʒiː/',
    category: 'operations',
    difficulty: 4,
    definitionEn: 'Aircraft on Ground — critical maintenance situation where the aircraft cannot fly until fixed.',
    definitionTr: 'Aircraft on Ground — uçağın tamir edilmeden uçamayacağı kritik bakım durumu.',
    examples: [
      { en: 'AOG: Boeing 737 stuck due to hydraulic leak.', tr: 'AOG: Boeing 737 hidrolik kaçaktan dolayı kalkamıyor.' },
      { en: 'AOG parts shipped via charter, premium cost.', tr: 'AOG parçaları charter ile taşınır, yüksek maliyet.' },
    ],
    relatedTerms: ['MEL', 'defect', 'urgent repair'],
  },
];
