/**
 * Teknisyen vocabulary seed — Faz 1.
 * 60 terim: dokümantasyon, ATA chapters, aletler, NDT, hardware, sertifikasyon.
 */
import type { VocabularyTerm } from './pilotVocab';

export const TECHNICIAN_VOCAB_FAZ1: VocabularyTerm[] = [
  // ===== DOCUMENTATION (10) =====
  { id: 'voc_tech_001', term: 'AMM', termTr: 'AMM (Bakım El Kitabı)', pronunciation: '/eɪ em em/', category: 'documentation', difficulty: 2,
    definitionEn: 'Aircraft Maintenance Manual — OEM document with all maintenance instructions.',
    definitionTr: 'Uçak Bakım El Kitabı — OEM\'in tüm bakım talimatlarını içeren belge.',
    examples: [
      { en: 'Reference latest AMM revision.', tr: 'Son AMM revizyonuna başvur.' },
      { en: 'AMM 32-11-00 covers main landing gear.', tr: 'AMM 32-11-00 ana iniş takımını kapsar.' },
    ],
    icaoReference: 'EASA Part-M / FAA 14 CFR Part 43',
    relatedTerms: ['CMM', 'IPC', 'WDM', 'TSM'],
  },
  { id: 'voc_tech_002', term: 'CMM', termTr: 'CMM (Komponent Bakım El Kitabı)', pronunciation: '/siː em em/', category: 'documentation', difficulty: 3,
    definitionEn: 'Component Maintenance Manual — overhaul instructions for specific components.',
    definitionTr: 'Komponent Bakım El Kitabı — belirli komponentlerin overhaul talimatları.',
    examples: [
      { en: 'CMM provides limits and fits.', tr: 'CMM limitleri ve fitleri verir.' },
      { en: 'CMM 32-30-15: brake assembly overhaul.', tr: 'CMM 32-30-15: fren overhaul.' },
    ],
    relatedTerms: ['overhaul', 'AMM', 'limits'],
  },
  { id: 'voc_tech_003', term: 'IPC', termTr: 'IPC (Parça Kataloğu)', pronunciation: '/aɪ piː siː/', category: 'documentation', difficulty: 3,
    definitionEn: 'Illustrated Parts Catalog — visual identification of aircraft parts.',
    definitionTr: 'Resimli Parça Kataloğu — uçak parçalarının görsel tanımı.',
    examples: [
      { en: 'Look up part number in IPC.', tr: 'IPC\'de parça numarasını ara.' },
      { en: 'IPC figure 32-11-01-01.', tr: 'IPC şekil 32-11-01-01.' },
    ],
    relatedTerms: ['part number', 'effectivity', 'figure'],
  },
  { id: 'voc_tech_004', term: 'WDM', termTr: 'WDM (Kablo Şeması)', pronunciation: '/dʌb.əl.juː diː em/', category: 'documentation', difficulty: 3,
    definitionEn: 'Wiring Diagram Manual — schematics of aircraft electrical systems.',
    definitionTr: 'Kablo Diyagramı Kılavuzu — uçak elektrik sistemleri şemaları.',
    examples: [
      { en: 'WDM 24-21: AC bus wiring.', tr: 'WDM 24-21: AC bus kabloları.' },
      { en: 'Trace wire using WDM.', tr: 'Kabloyu WDM ile takip et.' },
    ],
    relatedTerms: ['schematic', 'pin assignment', 'connector'],
  },
  { id: 'voc_tech_005', term: 'TSM', termTr: 'TSM (Sorun Giderme)', pronunciation: '/tiː es em/', category: 'documentation', difficulty: 3,
    definitionEn: 'Trouble Shooting Manual — diagnostic procedures for system faults.',
    definitionTr: 'Sorun Giderme Kılavuzu — sistem arızaları için tanı prosedürleri.',
    examples: [
      { en: 'Use TSM for fault isolation.', tr: 'Arıza izolasyonu için TSM kullan.' },
      { en: 'TSM decision tree guides repair.', tr: 'TSM karar ağacı tamiri yönlendirir.' },
    ],
    relatedTerms: ['fault code', 'AMM', 'diagnostic'],
  },
  { id: 'voc_tech_006', term: 'service bulletin', termTr: 'Servis Bülteni (SB)', pronunciation: '/ˈsɜː.vɪs ˈbʊl.ə.tɪn/', category: 'documentation', difficulty: 3,
    definitionEn: 'OEM document recommending modifications, inspections, or procedure updates.',
    definitionTr: 'OEM tarafından modifikasyon, muayene veya prosedür güncellemesi öneren belge.',
    examples: [
      { en: 'SB 737-32-1234 recommends inspection.', tr: 'SB 737-32-1234 muayene önerir.' },
      { en: 'SB Alert vs Recommended.', tr: 'SB Alert ve Recommended farkı.' },
    ],
    relatedTerms: ['AD', 'modification', 'compliance'],
  },
  { id: 'voc_tech_007', term: 'airworthiness directive', termTr: 'Hava Seyrüsefer Direktifi (AD)', pronunciation: '/ˈeə.wɜː.ðɪ.nəs daɪˈrek.tɪv/', category: 'documentation', difficulty: 4,
    definitionEn: 'Mandatory regulation requiring corrective action by aviation authority.',
    definitionTr: 'Havacılık otoritesi tarafından düzeltici aksiyon gerektiren zorunlu düzenleme.',
    examples: [
      { en: 'AD compliance is mandatory.', tr: 'AD uyumu zorunludur.' },
      { en: 'EASA AD 2024-0123.', tr: 'EASA AD 2024-0123.' },
    ],
    icaoReference: 'EASA / FAA continuing airworthiness',
    relatedTerms: ['SB', 'compliance', 'mandatory'],
  },
  { id: 'voc_tech_008', term: 'job card', termTr: 'iş kartı', pronunciation: '/dʒɒb kɑːd/', category: 'documentation', difficulty: 2,
    definitionEn: 'Document describing a specific maintenance task with sign-off blocks.',
    definitionTr: 'Belirli bir bakım görevini ve imza bloklarını açıklayan belge.',
    examples: [
      { en: 'Sign job card after task complete.', tr: 'Görev sonrası iş kartını imzala.' },
      { en: 'Job card cross-references AMM.', tr: 'İş kartı AMM ile çapraz referansla.' },
    ],
    relatedTerms: ['routing card', 'sign-off', 'work order'],
  },
  { id: 'voc_tech_009', term: 'EASA Form 1', termTr: 'EASA Form 1', pronunciation: '/ˈiː.zə fɔːm wʌn/', category: 'certification', difficulty: 4,
    definitionEn: 'European authorized release certificate — confirms part is airworthy.',
    definitionTr: 'Avrupa yetkili yayın sertifikası — parçanın airworthy olduğunu onaylar.',
    examples: [
      { en: 'Every overhauled part has EASA Form 1.', tr: 'Her overhaul parça EASA Form 1\'le çıkar.' },
      { en: 'FAA equivalent: Form 8130-3.', tr: 'FAA muadili: Form 8130-3.' },
    ],
    icaoReference: 'EASA Part-145',
    relatedTerms: ['Form 8130-3', 'CRS', 'airworthy'],
  },
  { id: 'voc_tech_010', term: 'CRS', termTr: 'CRS (Servis Yayın Sertifikası)', pronunciation: '/siː ɑːr es/', category: 'certification', difficulty: 4,
    definitionEn: 'Certificate of Release to Service — confirms aircraft is airworthy after maintenance.',
    definitionTr: 'Servis Yayın Sertifikası — bakım sonrası uçağın airworthy olduğunu onaylar.',
    examples: [
      { en: 'Only certifying staff can issue CRS.', tr: 'CRS\'yi sadece sertifikalı personel düzenler.' },
      { en: 'B1/B2 license required for CRS.', tr: 'CRS için B1/B2 lisansı gerekli.' },
    ],
    relatedTerms: ['certifying staff', 'B1', 'B2', 'airworthy'],
  },

  // ===== ATA CHAPTERS (10) =====
  { id: 'voc_tech_011', term: 'ATA chapter', termTr: 'ATA bölüm sistemi', pronunciation: '/eɪ tiː eɪ ˈtʃæp.tər/', category: 'documentation', difficulty: 3,
    definitionEn: 'Air Transport Association numbering for aircraft systems.',
    definitionTr: 'Uçak sistemleri için Air Transport Association numaralandırması.',
    examples: [
      { en: 'ATA 32 = Landing Gear.', tr: 'ATA 32 = İniş Takımı.' },
      { en: 'ATA 49 = APU.', tr: 'ATA 49 = APU.' },
    ],
    relatedTerms: ['AMM', 'IPC', 'WDM'],
  },
  { id: 'voc_tech_012', term: 'ATA 21', termTr: 'ATA 21 (Klima)', pronunciation: '/eɪ tiː eɪ ˈtwen.ti wʌn/', category: 'systems', difficulty: 3,
    definitionEn: 'Air Conditioning system — cabin temperature, pressurization, ventilation.',
    definitionTr: 'Klima sistemi — kabin sıcaklığı, basınçlandırma, havalandırma.',
    examples: [
      { en: 'Pack failure: ATA 21-50.', tr: 'Pack arızası: ATA 21-50.' },
      { en: 'Mix manifold balances temperature.', tr: 'Mix manifold sıcaklık dengeler.' },
    ],
    relatedTerms: ['pack', 'pressurization', 'bleed air'],
  },
  { id: 'voc_tech_013', term: 'ATA 24', termTr: 'ATA 24 (Elektrik)', pronunciation: '/eɪ tiː eɪ ˈtwen.ti fɔːr/', category: 'systems', difficulty: 3,
    definitionEn: 'Electrical Power system — generators, batteries, distribution.',
    definitionTr: 'Elektrik Güç sistemi — jeneratörler, bataryalar, dağıtım.',
    examples: [
      { en: 'AC bus failure: ATA 24-21.', tr: 'AC bus arıza: ATA 24-21.' },
      { en: 'TR (Transformer Rectifier) supplies DC.', tr: 'TR (Transformer Rectifier) DC sağlar.' },
    ],
    relatedTerms: ['generator', 'battery', 'bus', 'GPU'],
  },
  { id: 'voc_tech_014', term: 'ATA 27', termTr: 'ATA 27 (Uçuş Kontrolleri)', pronunciation: '/eɪ tiː eɪ ˈtwen.ti ˈsev.ən/', category: 'systems', difficulty: 3,
    definitionEn: 'Flight Controls — ailerons, elevators, rudder, flaps, slats.',
    definitionTr: 'Uçuş Kontrolleri — eleron, elevator, dümen, flap, slat.',
    examples: [
      { en: 'Aileron actuator: ATA 27-10.', tr: 'Eleron actuator: ATA 27-10.' },
      { en: 'Manual reversion test post-maintenance.', tr: 'Bakım sonrası manuel reversion testi.' },
    ],
    relatedTerms: ['actuator', 'cable', 'PCU'],
  },
  { id: 'voc_tech_015', term: 'ATA 28', termTr: 'ATA 28 (Yakıt)', pronunciation: '/eɪ tiː eɪ ˈtwen.ti eɪt/', category: 'systems', difficulty: 3,
    definitionEn: 'Fuel system — tanks, pumps, transfer, quantity indication.',
    definitionTr: 'Yakıt sistemi — tanklar, pompalar, transfer, miktar göstergesi.',
    examples: [
      { en: 'Fuel pump replacement: ATA 28-20.', tr: 'Yakıt pompası değişimi: ATA 28-20.' },
      { en: 'FQI: fuel quantity indication.', tr: 'FQI: yakıt miktarı göstergesi.' },
    ],
    relatedTerms: ['fuel pump', 'tank', 'FQI'],
  },
  { id: 'voc_tech_016', term: 'ATA 29', termTr: 'ATA 29 (Hidrolik)', pronunciation: '/eɪ tiː eɪ ˈtwen.ti naɪn/', category: 'systems', difficulty: 3,
    definitionEn: 'Hydraulic Power — pumps, reservoirs, accumulators, fluid distribution.',
    definitionTr: 'Hidrolik Güç — pompalar, rezervuarlar, akümülatörler, akışkan dağıtımı.',
    examples: [
      { en: 'EDP failure: ATA 29-10.', tr: 'EDP arızası: ATA 29-10.' },
      { en: '3000 PSI standard.', tr: '3000 PSI standart.' },
    ],
    relatedTerms: ['EDP', 'EMP', 'reservoir', 'PSI'],
  },
  { id: 'voc_tech_017', term: 'ATA 32', termTr: 'ATA 32 (İniş Takımı)', pronunciation: '/eɪ tiː eɪ ˈθɜː.ti tuː/', category: 'systems', difficulty: 2,
    definitionEn: 'Landing Gear — wheels, brakes, tires, retraction, steering.',
    definitionTr: 'İniş Takımı — tekerlek, fren, lastik, toplama, yönlendirme.',
    examples: [
      { en: 'MLG retraction test: ATA 32-30.', tr: 'MLG toplama testi: ATA 32-30.' },
      { en: 'Anti-skid system.', tr: 'Anti-skid sistemi.' },
    ],
    relatedTerms: ['MLG', 'NLG', 'anti-skid', 'tire'],
  },
  { id: 'voc_tech_018', term: 'ATA 49', termTr: 'ATA 49 (APU)', pronunciation: '/eɪ tiː eɪ ˈfɔː.ti naɪn/', category: 'systems', difficulty: 3,
    definitionEn: 'Auxiliary Power Unit — small turbine engine for ground/emergency power.',
    definitionTr: 'Yardımcı Güç Ünitesi — yer/acil güç için küçük türbin motoru.',
    examples: [
      { en: 'APU start sequence: ATA 49-11.', tr: 'APU çalıştırma sırası: ATA 49-11.' },
      { en: 'EGT high during start.', tr: 'Çalıştırmada EGT yüksek.' },
    ],
    relatedTerms: ['APU start', 'bleed air', 'EGT'],
  },
  { id: 'voc_tech_019', term: 'ATA 71', termTr: 'ATA 71 (Motor Genel)', pronunciation: '/eɪ tiː eɪ ˈsev.ən.ti wʌn/', category: 'systems', difficulty: 3,
    definitionEn: 'Powerplant general — engine installation, mounts, cowling.',
    definitionTr: 'Motor genel — motor montajı, bağlantılar, kaporta.',
    examples: [
      { en: 'Engine mount inspection: ATA 71-20.', tr: 'Motor mount muayenesi: ATA 71-20.' },
      { en: 'Cowling latches secured.', tr: 'Kaporta kilitleri sıkı.' },
    ],
    relatedTerms: ['engine mount', 'cowling', 'pylon'],
  },
  { id: 'voc_tech_020', term: 'ATA 79', termTr: 'ATA 79 (Yağ)', pronunciation: '/eɪ tiː eɪ ˈsev.ən.ti naɪn/', category: 'systems', difficulty: 3,
    definitionEn: 'Engine oil system — tanks, pumps, filtration, indication.',
    definitionTr: 'Motor yağ sistemi — tanklar, pompalar, filtre, gösterge.',
    examples: [
      { en: 'Oil filter change: ATA 79-21.', tr: 'Yağ filtresi değişimi: ATA 79-21.' },
      { en: 'Oil pressure low warning.', tr: 'Yağ basıncı düşük uyarısı.' },
    ],
    relatedTerms: ['oil filter', 'oil pressure', 'oil temperature'],
  },

  // ===== TOOLS (10) =====
  { id: 'voc_tech_021', term: 'torque wrench', termTr: 'tork anahtarı', pronunciation: '/tɔːk rentʃ/', category: 'tools', difficulty: 1,
    definitionEn: 'Precision tool that applies a specific rotational force to a fastener.',
    definitionTr: 'Bir bağlantı elemanına belirli dönme kuvveti uygulayan hassas alet.',
    examples: [
      { en: 'Calibration sticker must be valid.', tr: 'Kalibrasyon etiketi geçerli olmalı.' },
      { en: 'Apply torque in 3 passes.', tr: '3 paste tork uygula.' },
    ],
    relatedTerms: ['torque seal', 'calibration', 'wrench'],
  },
  { id: 'voc_tech_022', term: 'micrometer', termTr: 'mikrometre', pronunciation: '/ˌmaɪˈkrɒm.ɪ.tər/', category: 'tools', difficulty: 2,
    definitionEn: 'Precision instrument for measuring small dimensions.',
    definitionTr: 'Küçük boyutları ölçen hassas alet.',
    examples: [
      { en: 'Micrometer reads 25.36 mm.', tr: 'Mikrometre 25.36 mm gösteriyor.' },
      { en: 'Inside, outside, depth micrometer.', tr: 'İç, dış, derinlik mikrometre.' },
    ],
    relatedTerms: ['caliper', 'gauge', 'measurement'],
  },
  { id: 'voc_tech_023', term: 'caliper', termTr: 'kumpas', pronunciation: '/ˈkæl.ɪ.pər/', category: 'tools', difficulty: 2,
    definitionEn: 'Measuring instrument for outer/inner dimensions and depth.',
    definitionTr: 'Dış/iç boyutlar ve derinlik ölçen alet.',
    examples: [
      { en: 'Vernier caliper: 0.02 mm precision.', tr: 'Vernier kumpas: 0.02 mm hassasiyet.' },
      { en: 'Digital caliper for quick reads.', tr: 'Hızlı okuma için dijital kumpas.' },
    ],
    relatedTerms: ['micrometer', 'vernier', 'digital'],
  },
  { id: 'voc_tech_024', term: 'borescope', termTr: 'borescope (iç görüş)', pronunciation: '/ˈbɔː.skəʊp/', category: 'tools', difficulty: 3,
    definitionEn: 'Flexible camera for inspecting internal aircraft components.',
    definitionTr: 'Uçak iç komponentlerini muayene eden esnek kamera.',
    examples: [
      { en: 'Borescope inspect after engine overhaul.', tr: 'Motor overhaul sonrası borescope.' },
      { en: 'Document with photo capture.', tr: 'Foto kaydıyla belgele.' },
    ],
    relatedTerms: ['compressor blade', 'turbine', 'visual inspection'],
  },
  { id: 'voc_tech_025', term: 'multimeter', termTr: 'multimetre', pronunciation: '/ˈmʌl.tɪˌmiː.tər/', category: 'tools', difficulty: 2,
    definitionEn: 'Electronic instrument measuring voltage, current, and resistance.',
    definitionTr: 'Voltaj, akım ve direnç ölçen elektronik alet.',
    examples: [
      { en: 'Test continuity with multimeter.', tr: 'Süreklilik testi multimetre ile.' },
      { en: 'Calibrated multimeter required.', tr: 'Kalibre multimetre gerekli.' },
    ],
    relatedTerms: ['voltage', 'current', 'resistance', 'continuity'],
  },
  { id: 'voc_tech_026', term: 'lockwire pliers', termTr: 'lockwire pensesi', pronunciation: '/ˈlɒk.waɪər ˈplaɪ.əz/', category: 'tools', difficulty: 2,
    definitionEn: 'Specialized pliers for twisting safety wire.',
    definitionTr: 'Emniyet teli bükmek için özel pense.',
    examples: [
      { en: 'Twist wire in pull direction.', tr: 'Teli çekme yönünde bük.' },
      { en: 'Cut excess — no FOD.', tr: 'Fazlayı kes — FOD yok.' },
    ],
    relatedTerms: ['lockwire', 'safety wire', 'FOD'],
  },
  { id: 'voc_tech_027', term: 'jack', termTr: 'kriko (jack)', pronunciation: '/dʒæk/', category: 'tools', difficulty: 2,
    definitionEn: 'Hydraulic device used to lift the aircraft for maintenance.',
    definitionTr: 'Bakım için uçağı kaldırmaya yarayan hidrolik cihaz.',
    examples: [
      { en: 'Lift on tripod jack.', tr: 'Tripod kriko ile kaldır.' },
      { en: 'Annual load test required.', tr: 'Yıllık yük testi gerekli.' },
    ],
    relatedTerms: ['axle jack', 'tripod', 'load test'],
  },
  { id: 'voc_tech_028', term: 'rivet gun', termTr: 'perçin tabancası', pronunciation: '/ˈrɪv.ɪt ɡʌn/', category: 'tools', difficulty: 2,
    definitionEn: 'Pneumatic tool used to install rivets in sheet metal.',
    definitionTr: 'Sac metale perçin takmak için pnömatik alet.',
    examples: [
      { en: 'Rivet gun pressure 90 PSI.', tr: 'Perçin tabancası basıncı 90 PSI.' },
      { en: 'Bucking bar opposite side.', tr: 'Karşı tarafta bucking bar.' },
    ],
    relatedTerms: ['rivet', 'bucking bar', 'sheet metal'],
  },
  { id: 'voc_tech_029', term: 'feeler gauge', termTr: 'sentil çakısı', pronunciation: '/ˈfiː.lər ɡeɪdʒ/', category: 'tools', difficulty: 2,
    definitionEn: 'Thin metal strips used to measure small gaps.',
    definitionTr: 'Küçük boşlukları ölçen ince metal şeritler.',
    examples: [
      { en: 'Check spark plug gap.', tr: 'Buji boşluğu kontrol.' },
      { en: '0.05 mm increments.', tr: '0.05 mm artımlı.' },
    ],
    relatedTerms: ['gap', 'clearance', 'thickness'],
  },
  { id: 'voc_tech_030', term: 'workbench', termTr: 'tezgah', pronunciation: '/ˈwɜːk.bentʃ/', category: 'tools', difficulty: 1,
    definitionEn: 'Sturdy table where mechanics perform detailed work.',
    definitionTr: 'Mekaniklerin detaylı iş yaptığı sağlam masa.',
    examples: [
      { en: 'Component inspection on workbench.', tr: 'Tezgahta komponent muayenesi.' },
      { en: 'Workbench with vise and lighting.', tr: 'Mengeneli ve ışıklı tezgah.' },
    ],
    relatedTerms: ['vise', 'tool board', 'shop'],
  },

  // ===== INSPECTION & NDT (10) =====
  { id: 'voc_tech_031', term: 'NDT', termTr: 'NDT (Tahribatsız Muayene)', pronunciation: '/en diː tiː/', category: 'inspection', difficulty: 3,
    definitionEn: 'Non-Destructive Testing — defect detection without damaging the part.',
    definitionTr: 'Tahribatsız Muayene — parçaya zarar vermeden hata tespiti.',
    examples: [
      { en: 'NDT Level 2 certified for MPI.', tr: 'NDT Level 2 MPI sertifikalı.' },
      { en: 'Eddy current finds subsurface defects.', tr: 'Eddy current yüzey altı bulur.' },
    ],
    icaoReference: 'EN 4179 / NAS 410',
    relatedTerms: ['MPI', 'FPI', 'ultrasonic'],
  },
  { id: 'voc_tech_032', term: 'MPI', termTr: 'MPI (Manyetik Parçacık)', pronunciation: '/em piː aɪ/', category: 'inspection', difficulty: 3,
    definitionEn: 'Magnetic Particle Inspection — finds surface/subsurface cracks in ferrous parts.',
    definitionTr: 'Manyetik Parçacık Muayenesi — demir esaslı parçalarda yüzey/alt yüzey çatlak bulur.',
    examples: [
      { en: 'MPI ferrous parts only.', tr: 'MPI sadece demir esaslı.' },
      { en: 'Yoke or coil method.', tr: 'Yoke veya bobin yöntemi.' },
    ],
    relatedTerms: ['NDT', 'ferrous', 'crack'],
  },
  { id: 'voc_tech_033', term: 'FPI', termTr: 'FPI (Fluoresan Penetrant)', pronunciation: '/ef piː aɪ/', category: 'inspection', difficulty: 3,
    definitionEn: 'Fluorescent Penetrant Inspection — surface crack detection on non-ferrous.',
    definitionTr: 'Fluoresan Penetrant Muayenesi — demir dışı parçalarda yüzey çatlak.',
    examples: [
      { en: 'FPI for aluminum components.', tr: 'Alüminyum komponentler için FPI.' },
      { en: 'UV light reveals indications.', tr: 'UV ışık göstergeleri açığa çıkarır.' },
    ],
    relatedTerms: ['NDT', 'penetrant', 'UV light'],
  },
  { id: 'voc_tech_034', term: 'eddy current', termTr: 'eddy current', pronunciation: '/ˈed.i ˈkʌr.ənt/', category: 'inspection', difficulty: 4,
    definitionEn: 'Electromagnetic NDT method for detecting subsurface defects.',
    definitionTr: 'Yüzey altı hata tespiti için elektromanyetik NDT yöntemi.',
    examples: [
      { en: 'Eddy current scans rivet holes.', tr: 'Eddy current perçin deliklerini tarar.' },
      { en: 'Hidden corrosion detection.', tr: 'Gizli korozyon tespiti.' },
    ],
    relatedTerms: ['NDT', 'subsurface', 'electromagnetic'],
  },
  { id: 'voc_tech_035', term: 'ultrasonic testing', termTr: 'ultrasonik test (UT)', pronunciation: '/ˌʌl.trəˈsɒn.ɪk ˈtest.ɪŋ/', category: 'inspection', difficulty: 4,
    definitionEn: 'Sound wave NDT for thickness measurement and internal flaws.',
    definitionTr: 'Kalınlık ölçümü ve iç hata için ses dalgası NDT yöntemi.',
    examples: [
      { en: 'UT measures wall thickness.', tr: 'UT duvar kalınlığı ölçer.' },
      { en: 'Couplant gel applied.', tr: 'Couplant jel uygulanır.' },
    ],
    relatedTerms: ['UT', 'thickness', 'flaw'],
  },
  { id: 'voc_tech_036', term: 'visual inspection', termTr: 'görsel muayene', pronunciation: '/ˈvɪʒ.u.əl ɪnˈspek.ʃən/', category: 'inspection', difficulty: 1,
    definitionEn: 'First-line inspection using eyes, mirrors, and lighting.',
    definitionTr: 'Göz, ayna ve ışıkla yapılan ilk hat muayene.',
    examples: [
      { en: 'Walk-around includes visual inspection.', tr: 'Walk-around görsel muayene içerir.' },
      { en: 'Document with photos.', tr: 'Fotoğrafla belgele.' },
    ],
    relatedTerms: ['walk-around', 'inspection mirror', 'flashlight'],
  },
  { id: 'voc_tech_037', term: 'corrosion', termTr: 'korozyon', pronunciation: '/kəˈrəʊ.ʒən/', category: 'defect', difficulty: 2,
    definitionEn: 'Chemical degradation of metal — pitting, intergranular, exfoliation.',
    definitionTr: 'Metalin kimyasal bozulması — pitting, intergranular, exfoliation.',
    examples: [
      { en: 'Pitting on lower wing skin.', tr: 'Alt kanat skin\'inde pitting.' },
      { en: 'Apply corrosion inhibitor.', tr: 'Korozyon önleyici uygula.' },
    ],
    relatedTerms: ['pitting', 'fatigue', 'inhibitor'],
  },
  { id: 'voc_tech_038', term: 'fatigue crack', termTr: 'yorulma çatlağı', pronunciation: '/fəˈtiːɡ kræk/', category: 'defect', difficulty: 3,
    definitionEn: 'Crack from repeated stress cycles, common in high-stress components.',
    definitionTr: 'Tekrarlanan stres döngülerinden çatlak, yüksek stresli komponentlerde yaygın.',
    examples: [
      { en: 'Fatigue crack in wing spar.', tr: 'Kanat sparında yorulma çatlağı.' },
      { en: 'Cycle limit reached.', tr: 'Döngü limiti doldu.' },
    ],
    relatedTerms: ['stress', 'cycle', 'fracture'],
  },
  { id: 'voc_tech_039', term: 'dent', termTr: 'göçük', pronunciation: '/dent/', category: 'defect', difficulty: 1,
    definitionEn: 'Localized indentation in aircraft skin from impact.',
    definitionTr: 'Çarpmadan uçak skin\'inde lokal göçme.',
    examples: [
      { en: 'Dent map records location/depth.', tr: 'Dent map yer ve derinliği kaydeder.' },
      { en: 'Within AMM acceptable damage limits.', tr: 'AMM kabul limitleri dahilinde.' },
    ],
    relatedTerms: ['damage limit', 'skin', 'impact'],
  },
  { id: 'voc_tech_040', term: 'scratch', termTr: 'çizik', pronunciation: '/skrætʃ/', category: 'defect', difficulty: 1,
    definitionEn: 'Linear surface mark, typically shallow.',
    definitionTr: 'Doğrusal yüzey izi, genelde sığ.',
    examples: [
      { en: 'Light scratch within limits.', tr: 'Hafif çizik limit dahilinde.' },
      { en: 'Polish out minor scratches.', tr: 'Hafif çizikleri parlat.' },
    ],
    relatedTerms: ['defect', 'damage limit', 'polish'],
  },

  // ===== HARDWARE (10) =====
  { id: 'voc_tech_041', term: 'lockwire', termTr: 'kilit teli (safety wire)', pronunciation: '/ˈlɒk.waɪər/', category: 'hardware', difficulty: 2,
    definitionEn: 'Stainless steel wire securing fasteners against vibration.',
    definitionTr: 'Bağlantı elemanlarını titreşime karşı kilitleyen paslanmaz çelik tel.',
    examples: [
      { en: 'Twist wire in pull direction.', tr: 'Teli çekme yönünde bük.' },
      { en: 'Cut excess — no FOD.', tr: 'Fazlayı kes — FOD yok.' },
    ],
    relatedTerms: ['cotter pin', 'torque seal', 'fastener'],
  },
  { id: 'voc_tech_042', term: 'cotter pin', termTr: 'gupilya (cotter pin)', pronunciation: '/ˈkɒt.ər pɪn/', category: 'hardware', difficulty: 2,
    definitionEn: 'Split metal pin used to secure nuts on castle bolts.',
    definitionTr: 'Castle cıvatalarındaki somunları sabitleyen yarık metal pin.',
    examples: [
      { en: 'New cotter pin every install.', tr: 'Her takmada yeni cotter pin.' },
      { en: 'Spread legs after insertion.', tr: 'Taktıktan sonra bacakları aç.' },
    ],
    relatedTerms: ['castle nut', 'split pin', 'lockwire'],
  },
  { id: 'voc_tech_043', term: 'torque seal', termTr: 'tork mührü', pronunciation: '/tɔːk siːl/', category: 'hardware', difficulty: 2,
    definitionEn: 'Colored paint applied across fastener and joint as visual evidence of torque.',
    definitionTr: 'Tork uygulandığını gösteren bağlantı ve birleşim üzerine sürülen renkli boya.',
    examples: [
      { en: 'Apply torque seal post-torque.', tr: 'Tork sonrası torque seal.' },
      { en: 'Broken seal: re-inspect torque.', tr: 'Kırık seal: tork tekrar muayene.' },
    ],
    relatedTerms: ['witness mark', 'torque wrench', 'inspection'],
  },
  { id: 'voc_tech_044', term: 'self-locking nut', termTr: 'kendiliğinden kilitli somun', pronunciation: '/self ˈlɒk.ɪŋ nʌt/', category: 'hardware', difficulty: 2,
    definitionEn: 'Nut with built-in locking feature (nylon insert or distorted thread).',
    definitionTr: 'Yerleşik kilitleme özelliği olan somun (naylon insert veya distorted thread).',
    examples: [
      { en: 'One-time use only.', tr: 'Tek kullanımlık.' },
      { en: 'Replace after each removal.', tr: 'Her sökümden sonra değiştir.' },
    ],
    relatedTerms: ['nyloc', 'one-time use', 'castle nut'],
  },
  { id: 'voc_tech_045', term: 'castle nut', termTr: 'taç somun', pronunciation: '/ˈkɑː.səl nʌt/', category: 'hardware', difficulty: 2,
    definitionEn: 'Slotted nut allowing insertion of a cotter pin for safety.',
    definitionTr: 'Emniyet için cotter pin takılmasına izin veren yarık somun.',
    examples: [
      { en: 'Castle nut + cotter pin combo.', tr: 'Castle nut + cotter pin kombinasyonu.' },
      { en: 'Hand tighten then torque to slot.', tr: 'Elle sık, sonra slot\'a kadar tork.' },
    ],
    relatedTerms: ['cotter pin', 'self-locking nut', 'torque'],
  },
  { id: 'voc_tech_046', term: 'shim', termTr: 'şim (ayar plakası)', pronunciation: '/ʃɪm/', category: 'hardware', difficulty: 2,
    definitionEn: 'Thin spacer used to fill gaps or adjust alignment.',
    definitionTr: 'Boşluk doldurmak veya hizalamayı ayarlamak için ince ara plaka.',
    examples: [
      { en: 'Shim 0.005 inch.', tr: 'Shim 0.005 inç.' },
      { en: 'Stack shims to required thickness.', tr: 'Gerekli kalınlığa kadar shim üst üste.' },
    ],
    relatedTerms: ['gap', 'alignment', 'spacer'],
  },
  { id: 'voc_tech_047', term: 'bushing', termTr: 'burç (bushing)', pronunciation: '/ˈbʊʃ.ɪŋ/', category: 'hardware', difficulty: 2,
    definitionEn: 'Sleeve or insert reducing friction or wear at a bearing surface.',
    definitionTr: 'Yatak yüzeyinde sürtünme veya aşınmayı azaltan kovan veya insert.',
    examples: [
      { en: 'Bushing replacement during overhaul.', tr: 'Overhaul sırasında bushing değişimi.' },
      { en: 'Press-fit bushing.', tr: 'Sıkı geçme bushing.' },
    ],
    relatedTerms: ['bearing', 'sleeve', 'wear'],
  },
  { id: 'voc_tech_048', term: 'rivet', termTr: 'perçin', pronunciation: '/ˈrɪv.ɪt/', category: 'hardware', difficulty: 2,
    definitionEn: 'Permanent fastener formed by deforming the shank.',
    definitionTr: 'Şaftın deforme edilmesiyle oluşan kalıcı bağlantı elemanı.',
    examples: [
      { en: 'Solid rivet for high-stress areas.', tr: 'Yüksek stresli alanlar için solid rivet.' },
      { en: 'Blind rivet (Cherry) for one-side access.', tr: 'Tek taraflı erişim için blind rivet.' },
    ],
    relatedTerms: ['solid rivet', 'blind rivet', 'rivet gun'],
  },
  { id: 'voc_tech_049', term: 'fastener', termTr: 'bağlantı elemanı', pronunciation: '/ˈfɑː.sən.ər/', category: 'hardware', difficulty: 1,
    definitionEn: 'Generic term for bolts, screws, nuts, rivets, and similar.',
    definitionTr: 'Cıvata, vida, somun, perçin ve benzer için genel terim.',
    examples: [
      { en: 'Critical fasteners require torque.', tr: 'Kritik bağlantı elemanları tork gerektirir.' },
      { en: 'Fastener inventory before close-up.', tr: 'Kapatmadan önce fastener envanteri.' },
    ],
    relatedTerms: ['bolt', 'nut', 'rivet', 'screw'],
  },
  { id: 'voc_tech_050', term: 'shop towel', termTr: 'atelye bezi', pronunciation: '/ʃɒp ˈtaʊ.əl/', category: 'consumables', difficulty: 1,
    definitionEn: 'Disposable cloth for cleaning and FOD-prevention.',
    definitionTr: 'Temizlik ve FOD önleme için tek kullanımlık bez.',
    examples: [
      { en: 'Account for every shop towel.', tr: 'Her shop towel\'ı say.' },
      { en: 'FOD source if left behind.', tr: 'Bırakılırsa FOD kaynağı.' },
    ],
    relatedTerms: ['FOD', 'cleaning', 'consumables'],
  },

  // ===== OPERATIONS (10) =====
  { id: 'voc_tech_051', term: 'AOG', termTr: 'AOG (Aircraft on Ground)', pronunciation: '/eɪ əʊ dʒiː/', category: 'operations', difficulty: 4,
    definitionEn: 'Critical maintenance situation — aircraft cannot fly until fixed.',
    definitionTr: 'Kritik bakım durumu — uçak tamir edilmeden uçamaz.',
    examples: [
      { en: 'AOG: 737 stuck due to hydraulic leak.', tr: 'AOG: 737 hidrolik kaçaktan kalkamıyor.' },
      { en: 'AOG parts: charter shipping.', tr: 'AOG parçalar: charter taşıma.' },
    ],
    relatedTerms: ['MEL', 'defect', 'urgent'],
  },
  { id: 'voc_tech_052', term: 'MEL', termTr: 'MEL (Asgari Ekipman Listesi)', pronunciation: '/em iː el/', category: 'operations', difficulty: 4,
    definitionEn: 'Minimum Equipment List — items that may be inoperative for limited dispatch.',
    definitionTr: 'Asgari Ekipman Listesi — sınırlı dispatch için inoperative olabilecek öğeler.',
    examples: [
      { en: 'Defer item per MEL.', tr: 'Öğeyi MEL\'e göre ertele.' },
      { en: 'MEL category B: 3 days.', tr: 'MEL kategori B: 3 gün.' },
    ],
    relatedTerms: ['CDL', 'deferral', 'dispatch'],
  },
  { id: 'voc_tech_053', term: 'walk-around', termTr: 'walk-around (uçuş öncesi tur)', pronunciation: '/wɔːk əˈraʊnd/', category: 'operations', difficulty: 1,
    definitionEn: 'External pre-flight visual inspection of the aircraft.',
    definitionTr: 'Uçuş öncesi uçağın dış görsel muayenesi.',
    examples: [
      { en: 'Walk-around takes 15 minutes.', tr: 'Walk-around 15 dakika.' },
      { en: 'Check tires, panels, lights.', tr: 'Lastik, panel, ışık kontrol.' },
    ],
    relatedTerms: ['preflight', 'visual inspection', 'pilot inspection'],
  },
  { id: 'voc_tech_054', term: 'defect entry', termTr: 'arıza kaydı', pronunciation: '/ˈdiː.fekt ˈen.tri/', category: 'documentation', difficulty: 3,
    definitionEn: 'Written record of a discovered fault in the technical log.',
    definitionTr: 'Teknik log\'a yapılan keşfedilen arıza yazılı kaydı.',
    examples: [
      { en: 'Pilot reports: "Right brake intermittent."', tr: 'Pilot raporu: "Sağ fren aralıklı."' },
      { en: 'Defect entry triggers maintenance action.', tr: 'Defect entry bakım aksiyonu tetikler.' },
    ],
    relatedTerms: ['tech log', 'TLB', 'write-up'],
  },
  { id: 'voc_tech_055', term: 'tech log', termTr: 'teknik log', pronunciation: '/tek lɒɡ/', category: 'documentation', difficulty: 3,
    definitionEn: 'Technical Log — onboard record of defects, deferrals, and maintenance.',
    definitionTr: 'Teknik Log — uçaktaki arıza, erteleme ve bakım kaydı.',
    examples: [
      { en: 'Sign tech log after each repair.', tr: 'Her tamir sonrası tech log imzala.' },
      { en: 'Tech log accompanies aircraft.', tr: 'Tech log uçakla birlikte taşınır.' },
    ],
    relatedTerms: ['TLB', 'defect entry', 'sign-off'],
  },
  { id: 'voc_tech_056', term: 'sign-off', termTr: 'onay imzası', pronunciation: '/saɪn ɒf/', category: 'certification', difficulty: 2,
    definitionEn: 'Certification by qualified person that work was performed correctly.',
    definitionTr: 'İşin doğru yapıldığının nitelikli kişi tarafından sertifikalandırılması.',
    examples: [
      { en: 'Mechanic sign-off + inspector verification.', tr: 'Mekanik sign-off + müfettiş doğrulama.' },
      { en: 'Stamp ID on sign-off.', tr: 'Sign-off\'ta stamp ID.' },
    ],
    relatedTerms: ['CRS', 'inspector', 'stamp'],
  },
  { id: 'voc_tech_057', term: 'inspector', termTr: 'müfettiş (QC)', pronunciation: '/ɪnˈspek.tər/', category: 'staff', difficulty: 2,
    definitionEn: 'QC personnel who verifies maintenance work meets standards.',
    definitionTr: 'Bakım işinin standartlara uyduğunu doğrulayan QC personeli.',
    examples: [
      { en: 'Independent inspection required for critical work.', tr: 'Kritik iş için bağımsız muayene gerekli.' },
      { en: 'Inspector stamp ID: QC-247.', tr: 'Müfettiş stamp ID: QC-247.' },
    ],
    relatedTerms: ['QC', 'independent inspection', 'stamp'],
  },
  { id: 'voc_tech_058', term: 'hold tag', termTr: 'bekleme etiketi', pronunciation: '/həʊld tæɡ/', category: 'operations', difficulty: 3,
    definitionEn: 'Color-coded label indicating part status: yellow=under inspection, red=scrap, green=serviceable.',
    definitionTr: 'Parça durumunu gösteren renkli etiket: sarı=muayenede, kırmızı=hurda, yeşil=kullanılabilir.',
    examples: [
      { en: 'Yellow hold tag pending inspection.', tr: 'Sarı hold tag muayene bekliyor.' },
      { en: 'Red tag = scrap area.', tr: 'Kırmızı tag = hurda alanı.' },
    ],
    relatedTerms: ['serviceable', 'unserviceable', 'scrap'],
  },
  { id: 'voc_tech_059', term: 'FOD', termTr: 'FOD (Yabancı Cisim Hasarı)', pronunciation: '/fɒd/', category: 'safety', difficulty: 2,
    definitionEn: 'Foreign Object Damage/Debris — any object that can damage aircraft.',
    definitionTr: 'Yabancı Cisim Hasarı/Atıkları — uçağa zarar verebilecek herhangi bir cisim.',
    examples: [
      { en: 'FOD walk before closing engine.', tr: 'Motor kapatmadan FOD walk.' },
      { en: 'Tool inventory prevents FOD.', tr: 'Tool inventory FOD\'u önler.' },
    ],
    relatedTerms: ['FOD walk', 'tool inventory', 'magnetic pickup'],
  },
  { id: 'voc_tech_060', term: 'overhaul', termTr: 'overhaul (genel revizyon)', pronunciation: '/ˌəʊ.vəˈhɔːl/', category: 'operations', difficulty: 3,
    definitionEn: 'Complete disassembly, inspection, repair, and reassembly of a component.',
    definitionTr: 'Bir komponentin tam söküm, muayene, tamir ve yeniden montajı.',
    examples: [
      { en: 'Engine overhaul every 10,000 hours.', tr: 'Motor overhaul her 10.000 saatte.' },
      { en: 'CMM provides overhaul instructions.', tr: 'CMM overhaul talimatları verir.' },
    ],
    relatedTerms: ['CMM', 'TBO', 'rebuild'],
  },
];
