-- sub_roles.names JSONB — Argos Translate (offline, 16 dil)
-- Migration `scripts/i18n/translate-sub-roles.mjs` ile üretildi.
-- DeepL Free kotası dolu olduğu için Argos kullanıldı (DE/FR/ES/IT/PT/NL/PL/EL/ZH/JA/KO/ID/RU/AR/FA/HI).
-- TR/EN dokunulmadı, TH/MS Argos'ta yok → EN fallback'te kaldı.
-- Idempotent: jsonb_set sadece eski "EN fallback" değerlerini günceller.
BEGIN;
UPDATE public.sub_roles SET names = jsonb_set(names, '{de}', '"Über uns"'::jsonb) WHERE id = 'atc_tower';
UPDATE public.sub_roles SET names = jsonb_set(names, '{de}', '"Prüfer"'::jsonb) WHERE id = 'atc_approach';
UPDATE public.sub_roles SET names = jsonb_set(names, '{de}', '"Bodenkontrolle"'::jsonb) WHERE id = 'atc_ground';
UPDATE public.sub_roles SET names = jsonb_set(names, '{de}', '"En-Route Controller"'::jsonb) WHERE id = 'atc_enroute';
UPDATE public.sub_roles SET names = jsonb_set(names, '{de}', '"Business Class Crew"'::jsonb) WHERE id = 'cabin_business';
UPDATE public.sub_roles SET names = jsonb_set(names, '{de}', '"Wirtschaftsklasse Crew"'::jsonb) WHERE id = 'cabin_economy';
UPDATE public.sub_roles SET names = jsonb_set(names, '{de}', '"Purser"'::jsonb) WHERE id = 'cabin_purser';
UPDATE public.sub_roles SET names = jsonb_set(names, '{de}', '"In den Warenkorb"'::jsonb) WHERE id = 'cabin_trainer';
UPDATE public.sub_roles SET names = jsonb_set(names, '{de}', '"Erstklassige Crew"'::jsonb) WHERE id = 'cabin_first';
UPDATE public.sub_roles SET names = jsonb_set(names, '{de}', '"Major Airline Dispatcher"'::jsonb) WHERE id = 'dispatcher_major';
UPDATE public.sub_roles SET names = jsonb_set(names, '{de}', '"Charter Versand"'::jsonb) WHERE id = 'dispatcher_charter';
UPDATE public.sub_roles SET names = jsonb_set(names, '{de}', '"VIP Versand"'::jsonb) WHERE id = 'dispatcher_vip';
UPDATE public.sub_roles SET names = jsonb_set(names, '{de}', '"Frachtbrief"'::jsonb) WHERE id = 'dispatcher_cargo';
UPDATE public.sub_roles SET names = jsonb_set(names, '{de}', '"Zurück zur Übersicht"'::jsonb) WHERE id = 'ground_pushback';
UPDATE public.sub_roles SET names = jsonb_set(names, '{de}', '"Gepäckhandler"'::jsonb) WHERE id = 'ground_baggage';
UPDATE public.sub_roles SET names = jsonb_set(names, '{de}', '"Gruppe"'::jsonb) WHERE id = 'ground_catering';
UPDATE public.sub_roles SET names = jsonb_set(names, '{de}', '"Betankungspersonal"'::jsonb) WHERE id = 'ground_refueling';
UPDATE public.sub_roles SET names = jsonb_set(names, '{de}', '"Deicing Crew"'::jsonb) WHERE id = 'ground_deicing';
UPDATE public.sub_roles SET names = jsonb_set(names, '{de}', '"A320 Pilot"'::jsonb) WHERE id = 'pilot_a320';
UPDATE public.sub_roles SET names = jsonb_set(names, '{de}', '"A321 Pilot"'::jsonb) WHERE id = 'pilot_a321';
UPDATE public.sub_roles SET names = jsonb_set(names, '{de}', '"A350 Pilot"'::jsonb) WHERE id = 'pilot_a350';
UPDATE public.sub_roles SET names = jsonb_set(names, '{de}', '"B737-800 Pilot"'::jsonb) WHERE id = 'pilot_b737_800';
UPDATE public.sub_roles SET names = jsonb_set(names, '{de}', '"B737-900 Pilot"'::jsonb) WHERE id = 'pilot_b737_900';
UPDATE public.sub_roles SET names = jsonb_set(names, '{de}', '"B737 MAX Pilot"'::jsonb) WHERE id = 'pilot_b737_max';
UPDATE public.sub_roles SET names = jsonb_set(names, '{de}', '"B777 Pilot"'::jsonb) WHERE id = 'pilot_b777';
UPDATE public.sub_roles SET names = jsonb_set(names, '{de}', '"B787 Pilot"'::jsonb) WHERE id = 'pilot_b787';
UPDATE public.sub_roles SET names = jsonb_set(names, '{de}', '"Cessna Pilot"'::jsonb) WHERE id = 'pilot_cessna';
UPDATE public.sub_roles SET names = jsonb_set(names, '{de}', '"Hubschrauber"'::jsonb) WHERE id = 'pilot_helicopter';
UPDATE public.sub_roles SET names = jsonb_set(names, '{de}', '"ATR Pilot"'::jsonb) WHERE id = 'pilot_atr';
UPDATE public.sub_roles SET names = jsonb_set(names, '{de}', '"ICAO 4 Prep"'::jsonb) WHERE id = 'student_icao4';
UPDATE public.sub_roles SET names = jsonb_set(names, '{de}', '"Interview Prep"'::jsonb) WHERE id = 'student_pilot_interview';
UPDATE public.sub_roles SET names = jsonb_set(names, '{de}', '"Interview Prep"'::jsonb) WHERE id = 'student_cabin_interview';
UPDATE public.sub_roles SET names = jsonb_set(names, '{de}', '"ATC Interview Prep"'::jsonb) WHERE id = 'student_atc_interview';
UPDATE public.sub_roles SET names = jsonb_set(names, '{de}', '"Wartung der Linien"'::jsonb) WHERE id = 'tech_line';
UPDATE public.sub_roles SET names = jsonb_set(names, '{de}', '"A-Check Techniker"'::jsonb) WHERE id = 'tech_a_check';
UPDATE public.sub_roles SET names = jsonb_set(names, '{de}', '"C-Check Techniker"'::jsonb) WHERE id = 'tech_c_check';
UPDATE public.sub_roles SET names = jsonb_set(names, '{de}', '"Landing Getriebetechniker"'::jsonb) WHERE id = 'tech_landing_gear';
UPDATE public.sub_roles SET names = jsonb_set(names, '{de}', '"Motortechnik"'::jsonb) WHERE id = 'tech_engine';
UPDATE public.sub_roles SET names = jsonb_set(names, '{de}', '"Räder & Bremsen Techniker"'::jsonb) WHERE id = 'tech_wheels';
UPDATE public.sub_roles SET names = jsonb_set(names, '{de}', '"Avionics Technician"'::jsonb) WHERE id = 'tech_avionics';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fr}', '"Contrôleur de tour"'::jsonb) WHERE id = 'atc_tower';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fr}', '"Contrôleur d''approche"'::jsonb) WHERE id = 'atc_approach';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fr}', '"Contrôleur au sol"'::jsonb) WHERE id = 'atc_ground';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fr}', '"Contrôleur en route"'::jsonb) WHERE id = 'atc_enroute';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fr}', '"Équipage en classe affaires"'::jsonb) WHERE id = 'cabin_business';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fr}', '"Équipage de classe économique"'::jsonb) WHERE id = 'cabin_economy';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fr}', '"Pourpre"'::jsonb) WHERE id = 'cabin_purser';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fr}', '"Entraîneur de cabine"'::jsonb) WHERE id = 'cabin_trainer';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fr}', '"Équipage de première classe"'::jsonb) WHERE id = 'cabin_first';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fr}', '"Régulateur de ligne principal"'::jsonb) WHERE id = 'dispatcher_major';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fr}', '"Expéditeur Charter"'::jsonb) WHERE id = 'dispatcher_charter';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fr}', '"Expéditeur VIP"'::jsonb) WHERE id = 'dispatcher_vip';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fr}', '"Expéditeur de fret"'::jsonb) WHERE id = 'dispatcher_cargo';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fr}', '"Équipage de secours"'::jsonb) WHERE id = 'ground_pushback';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fr}', '"Manipulation des bagages"'::jsonb) WHERE id = 'ground_baggage';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fr}', '"Équipe de restauration"'::jsonb) WHERE id = 'ground_catering';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fr}', '"Équipe de ravitaillement"'::jsonb) WHERE id = 'ground_refueling';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fr}', '"Équipe de dégivrage"'::jsonb) WHERE id = 'ground_deicing';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fr}', '"A320 Pilote"'::jsonb) WHERE id = 'pilot_a320';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fr}', '"A321 Pilote"'::jsonb) WHERE id = 'pilot_a321';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fr}', '"A350 Pilote"'::jsonb) WHERE id = 'pilot_a350';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fr}', '"B737-800 Pilote"'::jsonb) WHERE id = 'pilot_b737_800';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fr}', '"B737-900 Pilote"'::jsonb) WHERE id = 'pilot_b737_900';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fr}', '"B737 MAX Pilote"'::jsonb) WHERE id = 'pilot_b737_max';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fr}', '"B777 Pilote"'::jsonb) WHERE id = 'pilot_b777';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fr}', '"B787 Pilote"'::jsonb) WHERE id = 'pilot_b787';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fr}', '"Cessna Pilot"'::jsonb) WHERE id = 'pilot_cessna';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fr}', '"Hélicoptère pilote"'::jsonb) WHERE id = 'pilot_helicopter';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fr}', '"Pilote ATR"'::jsonb) WHERE id = 'pilot_atr';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fr}', '"OACI 4 Préparation"'::jsonb) WHERE id = 'student_icao4';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fr}', '"Préparation de l''entrevue pilote"'::jsonb) WHERE id = 'student_pilot_interview';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fr}', '"Préparation de l''entrevue de cabine"'::jsonb) WHERE id = 'student_cabin_interview';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fr}', '"Prép. d''entrevue de l''ATC"'::jsonb) WHERE id = 'student_atc_interview';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fr}', '"Entretien des lignes"'::jsonb) WHERE id = 'tech_line';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fr}', '"Technicien de contrôle A"'::jsonb) WHERE id = 'tech_a_check';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fr}', '"Technicien de contrôle C"'::jsonb) WHERE id = 'tech_c_check';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fr}', '"Technicien en équipement d''atterrissage"'::jsonb) WHERE id = 'tech_landing_gear';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fr}', '"Technicien en moteur"'::jsonb) WHERE id = 'tech_engine';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fr}', '"Technicien des roues et des freins"'::jsonb) WHERE id = 'tech_wheels';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fr}', '"Technicien en avionique"'::jsonb) WHERE id = 'tech_avionics';
UPDATE public.sub_roles SET names = jsonb_set(names, '{es}', '"Controlador de torre"'::jsonb) WHERE id = 'atc_tower';
UPDATE public.sub_roles SET names = jsonb_set(names, '{es}', '"Approach Controller"'::jsonb) WHERE id = 'atc_approach';
UPDATE public.sub_roles SET names = jsonb_set(names, '{es}', '"Controlador de tierra"'::jsonb) WHERE id = 'atc_ground';
UPDATE public.sub_roles SET names = jsonb_set(names, '{es}', '"Controlador de ruta"'::jsonb) WHERE id = 'atc_enroute';
UPDATE public.sub_roles SET names = jsonb_set(names, '{es}', '"Clase de negocios"'::jsonb) WHERE id = 'cabin_business';
UPDATE public.sub_roles SET names = jsonb_set(names, '{es}', '"Clase de Economía"'::jsonb) WHERE id = 'cabin_economy';
UPDATE public.sub_roles SET names = jsonb_set(names, '{es}', '"Purser"'::jsonb) WHERE id = 'cabin_purser';
UPDATE public.sub_roles SET names = jsonb_set(names, '{es}', '"Cabin Trainer"'::jsonb) WHERE id = 'cabin_trainer';
UPDATE public.sub_roles SET names = jsonb_set(names, '{es}', '"Crew de primera clase"'::jsonb) WHERE id = 'cabin_first';
UPDATE public.sub_roles SET names = jsonb_set(names, '{es}', '"Major Airline Dispatcher"'::jsonb) WHERE id = 'dispatcher_major';
UPDATE public.sub_roles SET names = jsonb_set(names, '{es}', '"Charter Dispatcher"'::jsonb) WHERE id = 'dispatcher_charter';
UPDATE public.sub_roles SET names = jsonb_set(names, '{es}', '"Dispatcher VIP"'::jsonb) WHERE id = 'dispatcher_vip';
UPDATE public.sub_roles SET names = jsonb_set(names, '{es}', '"Cargo Dispatcher"'::jsonb) WHERE id = 'dispatcher_cargo';
UPDATE public.sub_roles SET names = jsonb_set(names, '{es}', '"Empuja atrás Crew"'::jsonb) WHERE id = 'ground_pushback';
UPDATE public.sub_roles SET names = jsonb_set(names, '{es}', '"Baggage Handler"'::jsonb) WHERE id = 'ground_baggage';
UPDATE public.sub_roles SET names = jsonb_set(names, '{es}', '"Catering Crew"'::jsonb) WHERE id = 'ground_catering';
UPDATE public.sub_roles SET names = jsonb_set(names, '{es}', '"Refueling Crew"'::jsonb) WHERE id = 'ground_refueling';
UPDATE public.sub_roles SET names = jsonb_set(names, '{es}', '"De-icing Crew"'::jsonb) WHERE id = 'ground_deicing';
UPDATE public.sub_roles SET names = jsonb_set(names, '{es}', '"A320 Pilot"'::jsonb) WHERE id = 'pilot_a320';
UPDATE public.sub_roles SET names = jsonb_set(names, '{es}', '"A321 Pilot"'::jsonb) WHERE id = 'pilot_a321';
UPDATE public.sub_roles SET names = jsonb_set(names, '{es}', '"A350 Pilot"'::jsonb) WHERE id = 'pilot_a350';
UPDATE public.sub_roles SET names = jsonb_set(names, '{es}', '"B737-800 Pilot"'::jsonb) WHERE id = 'pilot_b737_800';
UPDATE public.sub_roles SET names = jsonb_set(names, '{es}', '"B737-900 Pilot"'::jsonb) WHERE id = 'pilot_b737_900';
UPDATE public.sub_roles SET names = jsonb_set(names, '{es}', '"B737 MAX Pilot"'::jsonb) WHERE id = 'pilot_b737_max';
UPDATE public.sub_roles SET names = jsonb_set(names, '{es}', '"B777 Pilot"'::jsonb) WHERE id = 'pilot_b777';
UPDATE public.sub_roles SET names = jsonb_set(names, '{es}', '"B787 Pilot"'::jsonb) WHERE id = 'pilot_b787';
UPDATE public.sub_roles SET names = jsonb_set(names, '{es}', '"Cessna Pilot"'::jsonb) WHERE id = 'pilot_cessna';
UPDATE public.sub_roles SET names = jsonb_set(names, '{es}', '"Helicopter Pilot"'::jsonb) WHERE id = 'pilot_helicopter';
UPDATE public.sub_roles SET names = jsonb_set(names, '{es}', '"ATR Pilot"'::jsonb) WHERE id = 'pilot_atr';
UPDATE public.sub_roles SET names = jsonb_set(names, '{es}', '"ICAO 4 Prep"'::jsonb) WHERE id = 'student_icao4';
UPDATE public.sub_roles SET names = jsonb_set(names, '{es}', '"Prep"'::jsonb) WHERE id = 'student_pilot_interview';
UPDATE public.sub_roles SET names = jsonb_set(names, '{es}', '"Prep"'::jsonb) WHERE id = 'student_cabin_interview';
UPDATE public.sub_roles SET names = jsonb_set(names, '{es}', '"ATC Interview Prep"'::jsonb) WHERE id = 'student_atc_interview';
UPDATE public.sub_roles SET names = jsonb_set(names, '{es}', '"Mantenimiento de la línea"'::jsonb) WHERE id = 'tech_line';
UPDATE public.sub_roles SET names = jsonb_set(names, '{es}', '"Técnico A-Check"'::jsonb) WHERE id = 'tech_a_check';
UPDATE public.sub_roles SET names = jsonb_set(names, '{es}', '"C-Check Technician"'::jsonb) WHERE id = 'tech_c_check';
UPDATE public.sub_roles SET names = jsonb_set(names, '{es}', '"Landing Gear Technician"'::jsonb) WHERE id = 'tech_landing_gear';
UPDATE public.sub_roles SET names = jsonb_set(names, '{es}', '"Técnico del motor"'::jsonb) WHERE id = 'tech_engine';
UPDATE public.sub_roles SET names = jsonb_set(names, '{es}', '"Wheels &quot; Brakes Technician"'::jsonb) WHERE id = 'tech_wheels';
UPDATE public.sub_roles SET names = jsonb_set(names, '{es}', '"Avionics Technician"'::jsonb) WHERE id = 'tech_avionics';
UPDATE public.sub_roles SET names = jsonb_set(names, '{it}', '"Regolatore di torre"'::jsonb) WHERE id = 'atc_tower';
UPDATE public.sub_roles SET names = jsonb_set(names, '{it}', '"Controller di Approccio"'::jsonb) WHERE id = 'atc_approach';
UPDATE public.sub_roles SET names = jsonb_set(names, '{it}', '"Regolatore di terra"'::jsonb) WHERE id = 'atc_ground';
UPDATE public.sub_roles SET names = jsonb_set(names, '{it}', '"Controllore in onda"'::jsonb) WHERE id = 'atc_enroute';
UPDATE public.sub_roles SET names = jsonb_set(names, '{it}', '"Business Class Crew"'::jsonb) WHERE id = 'cabin_business';
UPDATE public.sub_roles SET names = jsonb_set(names, '{it}', '"Classe Economy Crew"'::jsonb) WHERE id = 'cabin_economy';
UPDATE public.sub_roles SET names = jsonb_set(names, '{it}', '"Purser"'::jsonb) WHERE id = 'cabin_purser';
UPDATE public.sub_roles SET names = jsonb_set(names, '{it}', '"Allenatore della cabina"'::jsonb) WHERE id = 'cabin_trainer';
UPDATE public.sub_roles SET names = jsonb_set(names, '{it}', '"Prima classe Crew"'::jsonb) WHERE id = 'cabin_first';
UPDATE public.sub_roles SET names = jsonb_set(names, '{it}', '"Centrale di distribuzione aerea"'::jsonb) WHERE id = 'dispatcher_major';
UPDATE public.sub_roles SET names = jsonb_set(names, '{it}', '"Charter Dispatcher"'::jsonb) WHERE id = 'dispatcher_charter';
UPDATE public.sub_roles SET names = jsonb_set(names, '{it}', '"Distributore VIP"'::jsonb) WHERE id = 'dispatcher_vip';
UPDATE public.sub_roles SET names = jsonb_set(names, '{it}', '"Distributore di carico"'::jsonb) WHERE id = 'dispatcher_cargo';
UPDATE public.sub_roles SET names = jsonb_set(names, '{it}', '"Pushback Crew"'::jsonb) WHERE id = 'ground_pushback';
UPDATE public.sub_roles SET names = jsonb_set(names, '{it}', '"Manipolatore di bagagli"'::jsonb) WHERE id = 'ground_baggage';
UPDATE public.sub_roles SET names = jsonb_set(names, '{it}', '"Catering Crew"'::jsonb) WHERE id = 'ground_catering';
UPDATE public.sub_roles SET names = jsonb_set(names, '{it}', '"Refueling Crew"'::jsonb) WHERE id = 'ground_refueling';
UPDATE public.sub_roles SET names = jsonb_set(names, '{it}', '"De-icing Crew"'::jsonb) WHERE id = 'ground_deicing';
UPDATE public.sub_roles SET names = jsonb_set(names, '{it}', '"A320 pilota"'::jsonb) WHERE id = 'pilot_a320';
UPDATE public.sub_roles SET names = jsonb_set(names, '{it}', '"A321 pilota"'::jsonb) WHERE id = 'pilot_a321';
UPDATE public.sub_roles SET names = jsonb_set(names, '{it}', '"A350 Pilota"'::jsonb) WHERE id = 'pilot_a350';
UPDATE public.sub_roles SET names = jsonb_set(names, '{it}', '"B737-800 pilota"'::jsonb) WHERE id = 'pilot_b737_800';
UPDATE public.sub_roles SET names = jsonb_set(names, '{it}', '"B737-900 Pilota"'::jsonb) WHERE id = 'pilot_b737_900';
UPDATE public.sub_roles SET names = jsonb_set(names, '{it}', '"B737 MAX pilota"'::jsonb) WHERE id = 'pilot_b737_max';
UPDATE public.sub_roles SET names = jsonb_set(names, '{it}', '"B777 pilota"'::jsonb) WHERE id = 'pilot_b777';
UPDATE public.sub_roles SET names = jsonb_set(names, '{it}', '"B787 pilota"'::jsonb) WHERE id = 'pilot_b787';
UPDATE public.sub_roles SET names = jsonb_set(names, '{it}', '"Pilota Cessna"'::jsonb) WHERE id = 'pilot_cessna';
UPDATE public.sub_roles SET names = jsonb_set(names, '{it}', '"Pilota dell''elicottero"'::jsonb) WHERE id = 'pilot_helicopter';
UPDATE public.sub_roles SET names = jsonb_set(names, '{it}', '"Pilota ATR"'::jsonb) WHERE id = 'pilot_atr';
UPDATE public.sub_roles SET names = jsonb_set(names, '{it}', '"ICAO 4 Prep."'::jsonb) WHERE id = 'student_icao4';
UPDATE public.sub_roles SET names = jsonb_set(names, '{it}', '"Prep di intervista pilota"'::jsonb) WHERE id = 'student_pilot_interview';
UPDATE public.sub_roles SET names = jsonb_set(names, '{it}', '"Prep dell''intervista della cabina"'::jsonb) WHERE id = 'student_cabin_interview';
UPDATE public.sub_roles SET names = jsonb_set(names, '{it}', '"ATC Intervista Prep"'::jsonb) WHERE id = 'student_atc_interview';
UPDATE public.sub_roles SET names = jsonb_set(names, '{it}', '"Manutenzione della linea"'::jsonb) WHERE id = 'tech_line';
UPDATE public.sub_roles SET names = jsonb_set(names, '{it}', '"A-Check Technician"'::jsonb) WHERE id = 'tech_a_check';
UPDATE public.sub_roles SET names = jsonb_set(names, '{it}', '"C-Check Technician"'::jsonb) WHERE id = 'tech_c_check';
UPDATE public.sub_roles SET names = jsonb_set(names, '{it}', '"Ingranaggio di atterraggio tecnico"'::jsonb) WHERE id = 'tech_landing_gear';
UPDATE public.sub_roles SET names = jsonb_set(names, '{it}', '"Tecnica del motore"'::jsonb) WHERE id = 'tech_engine';
UPDATE public.sub_roles SET names = jsonb_set(names, '{it}', '"Ruote e freni Tecnici"'::jsonb) WHERE id = 'tech_wheels';
UPDATE public.sub_roles SET names = jsonb_set(names, '{it}', '"Avionics Technician"'::jsonb) WHERE id = 'tech_avionics';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pt}', '"Controlador da torre"'::jsonb) WHERE id = 'atc_tower';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pt}', '"Controlador de Abordagem"'::jsonb) WHERE id = 'atc_approach';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pt}', '"Controlador de terra"'::jsonb) WHERE id = 'atc_ground';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pt}', '"Controlador em rota"'::jsonb) WHERE id = 'atc_enroute';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pt}', '"Tripulação de Classe Executiva"'::jsonb) WHERE id = 'cabin_business';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pt}', '"Classe Econômica"'::jsonb) WHERE id = 'cabin_economy';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pt}', '"Busca"'::jsonb) WHERE id = 'cabin_purser';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pt}', '"Treinador de cabine"'::jsonb) WHERE id = 'cabin_trainer';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pt}', '"Tripulação de primeira classe"'::jsonb) WHERE id = 'cabin_first';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pt}', '"Expedidor de linha aérea principal"'::jsonb) WHERE id = 'dispatcher_major';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pt}', '"Expedidor de Cartas"'::jsonb) WHERE id = 'dispatcher_charter';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pt}', '"Enviador VIP"'::jsonb) WHERE id = 'dispatcher_vip';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pt}', '"Expedidor de Carga"'::jsonb) WHERE id = 'dispatcher_cargo';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pt}', '"Tripulação de apoio"'::jsonb) WHERE id = 'ground_pushback';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pt}', '"Manipulador de Bagagem"'::jsonb) WHERE id = 'ground_baggage';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pt}', '"Grupo de Catering"'::jsonb) WHERE id = 'ground_catering';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pt}', '"Tripulação de reabastecimento"'::jsonb) WHERE id = 'ground_refueling';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pt}', '"Tripulação de degelo"'::jsonb) WHERE id = 'ground_deicing';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pt}', '"Piloto A320"'::jsonb) WHERE id = 'pilot_a320';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pt}', '"Piloto A321"'::jsonb) WHERE id = 'pilot_a321';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pt}', '"Piloto A350"'::jsonb) WHERE id = 'pilot_a350';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pt}', '"Piloto B737-800"'::jsonb) WHERE id = 'pilot_b737_800';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pt}', '"Piloto B737-900"'::jsonb) WHERE id = 'pilot_b737_900';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pt}', '"Piloto B737 MAX"'::jsonb) WHERE id = 'pilot_b737_max';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pt}', '"Piloto B777"'::jsonb) WHERE id = 'pilot_b777';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pt}', '"Piloto B787"'::jsonb) WHERE id = 'pilot_b787';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pt}', '"Cessna Pilot"'::jsonb) WHERE id = 'pilot_cessna';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pt}', '"Piloto de helicóptero"'::jsonb) WHERE id = 'pilot_helicopter';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pt}', '"Piloto ATR"'::jsonb) WHERE id = 'pilot_atr';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pt}', '"ICAO 4 Preparação"'::jsonb) WHERE id = 'student_icao4';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pt}', '"Pilot Interview Prep"'::jsonb) WHERE id = 'student_pilot_interview';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pt}', '"Preparação da entrevista da cabine"'::jsonb) WHERE id = 'student_cabin_interview';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pt}', '"ATC Interview Prep"'::jsonb) WHERE id = 'student_atc_interview';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pt}', '"Manutenção da Linha"'::jsonb) WHERE id = 'tech_line';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pt}', '"Técnico de Verificação A"'::jsonb) WHERE id = 'tech_a_check';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pt}', '"Técnico de Verificação C"'::jsonb) WHERE id = 'tech_c_check';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pt}', '"Técnico em artes de desembarque"'::jsonb) WHERE id = 'tech_landing_gear';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pt}', '"Técnico do motor"'::jsonb) WHERE id = 'tech_engine';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pt}', '"Técnico de rodas e freios"'::jsonb) WHERE id = 'tech_wheels';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pt}', '"Técnico de Avionics"'::jsonb) WHERE id = 'tech_avionics';
UPDATE public.sub_roles SET names = jsonb_set(names, '{nl}', '"Tower controller"'::jsonb) WHERE id = 'atc_tower';
UPDATE public.sub_roles SET names = jsonb_set(names, '{nl}', '"Aanpakregelaar"'::jsonb) WHERE id = 'atc_approach';
UPDATE public.sub_roles SET names = jsonb_set(names, '{nl}', '"Grondcontroller"'::jsonb) WHERE id = 'atc_ground';
UPDATE public.sub_roles SET names = jsonb_set(names, '{nl}', '"En-route controller"'::jsonb) WHERE id = 'atc_enroute';
UPDATE public.sub_roles SET names = jsonb_set(names, '{nl}', '"Business Class Crew"'::jsonb) WHERE id = 'cabin_business';
UPDATE public.sub_roles SET names = jsonb_set(names, '{nl}', '"Economy Class Crew"'::jsonb) WHERE id = 'cabin_economy';
UPDATE public.sub_roles SET names = jsonb_set(names, '{nl}', '"Purser"'::jsonb) WHERE id = 'cabin_purser';
UPDATE public.sub_roles SET names = jsonb_set(names, '{nl}', '"Cabinetrainer"'::jsonb) WHERE id = 'cabin_trainer';
UPDATE public.sub_roles SET names = jsonb_set(names, '{nl}', '"Eerste klasse bemanning"'::jsonb) WHERE id = 'cabin_first';
UPDATE public.sub_roles SET names = jsonb_set(names, '{nl}', '"Major Airline Dispatcher"'::jsonb) WHERE id = 'dispatcher_major';
UPDATE public.sub_roles SET names = jsonb_set(names, '{nl}', '"Charter Dispatcher"'::jsonb) WHERE id = 'dispatcher_charter';
UPDATE public.sub_roles SET names = jsonb_set(names, '{nl}', '"VIP Dispatcher"'::jsonb) WHERE id = 'dispatcher_vip';
UPDATE public.sub_roles SET names = jsonb_set(names, '{nl}', '"Vrachtverzender"'::jsonb) WHERE id = 'dispatcher_cargo';
UPDATE public.sub_roles SET names = jsonb_set(names, '{nl}', '"Pushback crew"'::jsonb) WHERE id = 'ground_pushback';
UPDATE public.sub_roles SET names = jsonb_set(names, '{nl}', '"Bagage handler"'::jsonb) WHERE id = 'ground_baggage';
UPDATE public.sub_roles SET names = jsonb_set(names, '{nl}', '"Cateringploeg"'::jsonb) WHERE id = 'ground_catering';
UPDATE public.sub_roles SET names = jsonb_set(names, '{nl}', '"Bijtanken van bemanning"'::jsonb) WHERE id = 'ground_refueling';
UPDATE public.sub_roles SET names = jsonb_set(names, '{nl}', '"Bemanning van ijs"'::jsonb) WHERE id = 'ground_deicing';
UPDATE public.sub_roles SET names = jsonb_set(names, '{nl}', '"A320 Piloot"'::jsonb) WHERE id = 'pilot_a320';
UPDATE public.sub_roles SET names = jsonb_set(names, '{nl}', '"A321 Pilot"'::jsonb) WHERE id = 'pilot_a321';
UPDATE public.sub_roles SET names = jsonb_set(names, '{nl}', '"A350 Pilot"'::jsonb) WHERE id = 'pilot_a350';
UPDATE public.sub_roles SET names = jsonb_set(names, '{nl}', '"B737-800 Pilot"'::jsonb) WHERE id = 'pilot_b737_800';
UPDATE public.sub_roles SET names = jsonb_set(names, '{nl}', '"B737-900 Pilot"'::jsonb) WHERE id = 'pilot_b737_900';
UPDATE public.sub_roles SET names = jsonb_set(names, '{nl}', '"B737 MAX Pilot"'::jsonb) WHERE id = 'pilot_b737_max';
UPDATE public.sub_roles SET names = jsonb_set(names, '{nl}', '"B777 Pilot"'::jsonb) WHERE id = 'pilot_b777';
UPDATE public.sub_roles SET names = jsonb_set(names, '{nl}', '"B787 Pilot"'::jsonb) WHERE id = 'pilot_b787';
UPDATE public.sub_roles SET names = jsonb_set(names, '{nl}', '"Cessna Pilot"'::jsonb) WHERE id = 'pilot_cessna';
UPDATE public.sub_roles SET names = jsonb_set(names, '{nl}', '"Helikopterpiloot"'::jsonb) WHERE id = 'pilot_helicopter';
UPDATE public.sub_roles SET names = jsonb_set(names, '{nl}', '"ATR Pilot"'::jsonb) WHERE id = 'pilot_atr';
UPDATE public.sub_roles SET names = jsonb_set(names, '{nl}', '"ICAO 4 Prep"'::jsonb) WHERE id = 'student_icao4';
UPDATE public.sub_roles SET names = jsonb_set(names, '{nl}', '"Pilot Interview Prep"'::jsonb) WHERE id = 'student_pilot_interview';
UPDATE public.sub_roles SET names = jsonb_set(names, '{nl}', '"Cabin Interview Prep"'::jsonb) WHERE id = 'student_cabin_interview';
UPDATE public.sub_roles SET names = jsonb_set(names, '{nl}', '"ATC Interview Prep"'::jsonb) WHERE id = 'student_atc_interview';
UPDATE public.sub_roles SET names = jsonb_set(names, '{nl}', '"Lijnonderhoud"'::jsonb) WHERE id = 'tech_line';
UPDATE public.sub_roles SET names = jsonb_set(names, '{nl}', '"A-Check Technician"'::jsonb) WHERE id = 'tech_a_check';
UPDATE public.sub_roles SET names = jsonb_set(names, '{nl}', '"C-Check Technicus"'::jsonb) WHERE id = 'tech_c_check';
UPDATE public.sub_roles SET names = jsonb_set(names, '{nl}', '"Landing Gear Technicus"'::jsonb) WHERE id = 'tech_landing_gear';
UPDATE public.sub_roles SET names = jsonb_set(names, '{nl}', '"Motortechnicus"'::jsonb) WHERE id = 'tech_engine';
UPDATE public.sub_roles SET names = jsonb_set(names, '{nl}', '"Wielen en remmen technicus"'::jsonb) WHERE id = 'tech_wheels';
UPDATE public.sub_roles SET names = jsonb_set(names, '{nl}', '"Avionics Technician"'::jsonb) WHERE id = 'tech_avionics';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pl}', '"Sterownik wieży"'::jsonb) WHERE id = 'atc_tower';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pl}', '"Sterownik podejścia"'::jsonb) WHERE id = 'atc_approach';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pl}', '"Sterownik naziemny"'::jsonb) WHERE id = 'atc_ground';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pl}', '"Kontrola trasy"'::jsonb) WHERE id = 'atc_enroute';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pl}', '"Załoga klasy biznes"'::jsonb) WHERE id = 'cabin_business';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pl}', '"Klasa ekonomiczna Załoga"'::jsonb) WHERE id = 'cabin_economy';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pl}', '"Obsługa"'::jsonb) WHERE id = 'cabin_purser';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pl}', '"Trener kabiny"'::jsonb) WHERE id = 'cabin_trainer';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pl}', '"Załoga pierwszej klasy"'::jsonb) WHERE id = 'cabin_first';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pl}', '"Główny dowódca linii lotniczych"'::jsonb) WHERE id = 'dispatcher_major';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pl}', '"Dyspozytor Karty"'::jsonb) WHERE id = 'dispatcher_charter';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pl}', '"Rozjemca VIP"'::jsonb) WHERE id = 'dispatcher_vip';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pl}', '"Dyspozytor ładunków"'::jsonb) WHERE id = 'dispatcher_cargo';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pl}', '"Załoga Pushback"'::jsonb) WHERE id = 'ground_pushback';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pl}', '"Bagażnik"'::jsonb) WHERE id = 'ground_baggage';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pl}', '"Załoga cateringowa"'::jsonb) WHERE id = 'ground_catering';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pl}', '"Efuelling Crew"'::jsonb) WHERE id = 'ground_refueling';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pl}', '"Załoga odladzająca"'::jsonb) WHERE id = 'ground_deicing';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pl}', '"A320 Pilot"'::jsonb) WHERE id = 'pilot_a320';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pl}', '"A321 Pilot"'::jsonb) WHERE id = 'pilot_a321';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pl}', '"A350 Pilot"'::jsonb) WHERE id = 'pilot_a350';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pl}', '"B737- 800 Pilot"'::jsonb) WHERE id = 'pilot_b737_800';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pl}', '"B737- 900 Pilot"'::jsonb) WHERE id = 'pilot_b737_900';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pl}', '"B737 MAX Pilot"'::jsonb) WHERE id = 'pilot_b737_max';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pl}', '"B777 Pilot"'::jsonb) WHERE id = 'pilot_b777';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pl}', '"B787 Pilot"'::jsonb) WHERE id = 'pilot_b787';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pl}', '"Cessna Pilot"'::jsonb) WHERE id = 'pilot_cessna';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pl}', '"Pilot śmigłowca"'::jsonb) WHERE id = 'pilot_helicopter';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pl}', '"Pilot ATR"'::jsonb) WHERE id = 'pilot_atr';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pl}', '"ICAO 4 Prep"'::jsonb) WHERE id = 'student_icao4';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pl}', '"Pilot Interview Prep"'::jsonb) WHERE id = 'student_pilot_interview';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pl}', '"Interview Cabin Prep"'::jsonb) WHERE id = 'student_cabin_interview';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pl}', '"ATC Interview Prep"'::jsonb) WHERE id = 'student_atc_interview';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pl}', '"Konserwacja linii"'::jsonb) WHERE id = 'tech_line';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pl}', '"Technik A- Check"'::jsonb) WHERE id = 'tech_a_check';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pl}', '"Technik C- Check"'::jsonb) WHERE id = 'tech_c_check';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pl}', '"Technik lądowania"'::jsonb) WHERE id = 'tech_landing_gear';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pl}', '"Technik silnika"'::jsonb) WHERE id = 'tech_engine';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pl}', '"Technik kół i hamulców"'::jsonb) WHERE id = 'tech_wheels';
UPDATE public.sub_roles SET names = jsonb_set(names, '{pl}', '"Technik awioniki"'::jsonb) WHERE id = 'tech_avionics';
UPDATE public.sub_roles SET names = jsonb_set(names, '{el}', '"Ελεγκτής πύργου"'::jsonb) WHERE id = 'atc_tower';
UPDATE public.sub_roles SET names = jsonb_set(names, '{el}', '"Ελεγκτής προσέγγισης"'::jsonb) WHERE id = 'atc_approach';
UPDATE public.sub_roles SET names = jsonb_set(names, '{el}', '"Ελεγκτής εδάφους"'::jsonb) WHERE id = 'atc_ground';
UPDATE public.sub_roles SET names = jsonb_set(names, '{el}', '"Ελεγκτής κατά τη διαδρομή"'::jsonb) WHERE id = 'atc_enroute';
UPDATE public.sub_roles SET names = jsonb_set(names, '{el}', '"Πλήρωμα Business Class"'::jsonb) WHERE id = 'cabin_business';
UPDATE public.sub_roles SET names = jsonb_set(names, '{el}', '"Πλήρωμα κλάσης οικονομίας"'::jsonb) WHERE id = 'cabin_economy';
UPDATE public.sub_roles SET names = jsonb_set(names, '{el}', '"Ψυγείο"'::jsonb) WHERE id = 'cabin_purser';
UPDATE public.sub_roles SET names = jsonb_set(names, '{el}', '"Εκπαιδευτής καμπίνας"'::jsonb) WHERE id = 'cabin_trainer';
UPDATE public.sub_roles SET names = jsonb_set(names, '{el}', '"Πλήρωμα πρώτης θέσης"'::jsonb) WHERE id = 'cabin_first';
UPDATE public.sub_roles SET names = jsonb_set(names, '{el}', '"Μεγάλος αποστολέας αεροπορικών γραμμών"'::jsonb) WHERE id = 'dispatcher_major';
UPDATE public.sub_roles SET names = jsonb_set(names, '{el}', '"Αποστολέας χαρτών"'::jsonb) WHERE id = 'dispatcher_charter';
UPDATE public.sub_roles SET names = jsonb_set(names, '{el}', '"Αποστολέας VIP"'::jsonb) WHERE id = 'dispatcher_vip';
UPDATE public.sub_roles SET names = jsonb_set(names, '{el}', '"Αποστολέας φορτίου"'::jsonb) WHERE id = 'dispatcher_cargo';
UPDATE public.sub_roles SET names = jsonb_set(names, '{el}', '"Πλήρωμα Pushback"'::jsonb) WHERE id = 'ground_pushback';
UPDATE public.sub_roles SET names = jsonb_set(names, '{el}', '"Χειριστής αποσκευών"'::jsonb) WHERE id = 'ground_baggage';
UPDATE public.sub_roles SET names = jsonb_set(names, '{el}', '"Πλήρωμα τροφοδοσίας"'::jsonb) WHERE id = 'ground_catering';
UPDATE public.sub_roles SET names = jsonb_set(names, '{el}', '"Πλήρωμα ανεφοδιασμού"'::jsonb) WHERE id = 'ground_refueling';
UPDATE public.sub_roles SET names = jsonb_set(names, '{el}', '"Πλήρωμα αποπαγοποίησης"'::jsonb) WHERE id = 'ground_deicing';
UPDATE public.sub_roles SET names = jsonb_set(names, '{el}', '"A320 Πιλότος"'::jsonb) WHERE id = 'pilot_a320';
UPDATE public.sub_roles SET names = jsonb_set(names, '{el}', '"A321 Πιλότος"'::jsonb) WHERE id = 'pilot_a321';
UPDATE public.sub_roles SET names = jsonb_set(names, '{el}', '"A350 Πιλότος"'::jsonb) WHERE id = 'pilot_a350';
UPDATE public.sub_roles SET names = jsonb_set(names, '{el}', '"B737-800 πιλότος"'::jsonb) WHERE id = 'pilot_b737_800';
UPDATE public.sub_roles SET names = jsonb_set(names, '{el}', '"B737-900 Πιλότος"'::jsonb) WHERE id = 'pilot_b737_900';
UPDATE public.sub_roles SET names = jsonb_set(names, '{el}', '"B737 Πιλότος MAX"'::jsonb) WHERE id = 'pilot_b737_max';
UPDATE public.sub_roles SET names = jsonb_set(names, '{el}', '"B777 Πιλότος"'::jsonb) WHERE id = 'pilot_b777';
UPDATE public.sub_roles SET names = jsonb_set(names, '{el}', '"B787 Πιλότος"'::jsonb) WHERE id = 'pilot_b787';
UPDATE public.sub_roles SET names = jsonb_set(names, '{el}', '"Πιλότος Cessna"'::jsonb) WHERE id = 'pilot_cessna';
UPDATE public.sub_roles SET names = jsonb_set(names, '{el}', '"Πιλότος ελικοπτέρου"'::jsonb) WHERE id = 'pilot_helicopter';
UPDATE public.sub_roles SET names = jsonb_set(names, '{el}', '"Πιλότος ATR"'::jsonb) WHERE id = 'pilot_atr';
UPDATE public.sub_roles SET names = jsonb_set(names, '{el}', '"ΔΟΠΑ 4"'::jsonb) WHERE id = 'student_icao4';
UPDATE public.sub_roles SET names = jsonb_set(names, '{el}', '"Προετοιμασία Πιλοτικής Συνέντευξης"'::jsonb) WHERE id = 'student_pilot_interview';
UPDATE public.sub_roles SET names = jsonb_set(names, '{el}', '"Προετοιμασία συνέντευξης καμπίνας"'::jsonb) WHERE id = 'student_cabin_interview';
UPDATE public.sub_roles SET names = jsonb_set(names, '{el}', '"Προετοιμάστε τη συνέντευξη ATC"'::jsonb) WHERE id = 'student_atc_interview';
UPDATE public.sub_roles SET names = jsonb_set(names, '{el}', '"Συντήρηση γραμμής"'::jsonb) WHERE id = 'tech_line';
UPDATE public.sub_roles SET names = jsonb_set(names, '{el}', '"Τεχνικός A-Check"'::jsonb) WHERE id = 'tech_a_check';
UPDATE public.sub_roles SET names = jsonb_set(names, '{el}', '"Τεχνικός έλεγχος C"'::jsonb) WHERE id = 'tech_c_check';
UPDATE public.sub_roles SET names = jsonb_set(names, '{el}', '"Τεχνικός εργαλείων προσγείωσης"'::jsonb) WHERE id = 'tech_landing_gear';
UPDATE public.sub_roles SET names = jsonb_set(names, '{el}', '"Τεχνικός κινητήρα"'::jsonb) WHERE id = 'tech_engine';
UPDATE public.sub_roles SET names = jsonb_set(names, '{el}', '"Τεχνικός τροχών & φρένων"'::jsonb) WHERE id = 'tech_wheels';
UPDATE public.sub_roles SET names = jsonb_set(names, '{el}', '"Τεχνικός αεροναυπηγικής"'::jsonb) WHERE id = 'tech_avionics';
UPDATE public.sub_roles SET names = jsonb_set(names, '{zh}', '"塔楼控制器"'::jsonb) WHERE id = 'atc_tower';
UPDATE public.sub_roles SET names = jsonb_set(names, '{zh}', '"方法主计长"'::jsonb) WHERE id = 'atc_approach';
UPDATE public.sub_roles SET names = jsonb_set(names, '{zh}', '"地面控制员"'::jsonb) WHERE id = 'atc_ground';
UPDATE public.sub_roles SET names = jsonb_set(names, '{zh}', '"程序控制器"'::jsonb) WHERE id = 'atc_enroute';
UPDATE public.sub_roles SET names = jsonb_set(names, '{zh}', '"商务舱"'::jsonb) WHERE id = 'cabin_business';
UPDATE public.sub_roles SET names = jsonb_set(names, '{zh}', '"经济舱"'::jsonb) WHERE id = 'cabin_economy';
UPDATE public.sub_roles SET names = jsonb_set(names, '{zh}', '"菩萨"'::jsonb) WHERE id = 'cabin_purser';
UPDATE public.sub_roles SET names = jsonb_set(names, '{zh}', '"车厢教练员"'::jsonb) WHERE id = 'cabin_trainer';
UPDATE public.sub_roles SET names = jsonb_set(names, '{zh}', '"头等兵"'::jsonb) WHERE id = 'cabin_first';
UPDATE public.sub_roles SET names = jsonb_set(names, '{zh}', '"主要航空调度员"'::jsonb) WHERE id = 'dispatcher_major';
UPDATE public.sub_roles SET names = jsonb_set(names, '{zh}', '"宪章调度员"'::jsonb) WHERE id = 'dispatcher_charter';
UPDATE public.sub_roles SET names = jsonb_set(names, '{zh}', '"贵宾调度员"'::jsonb) WHERE id = 'dispatcher_vip';
UPDATE public.sub_roles SET names = jsonb_set(names, '{zh}', '"货物调度员"'::jsonb) WHERE id = 'dispatcher_cargo';
UPDATE public.sub_roles SET names = jsonb_set(names, '{zh}', '"推后乘务员"'::jsonb) WHERE id = 'ground_pushback';
UPDATE public.sub_roles SET names = jsonb_set(names, '{zh}', '"行李处理器"'::jsonb) WHERE id = 'ground_baggage';
UPDATE public.sub_roles SET names = jsonb_set(names, '{zh}', '"餐饮人员"'::jsonb) WHERE id = 'ground_catering';
UPDATE public.sub_roles SET names = jsonb_set(names, '{zh}', '"为船员加油"'::jsonb) WHERE id = 'ground_refueling';
UPDATE public.sub_roles SET names = jsonb_set(names, '{zh}', '"机组人员"'::jsonb) WHERE id = 'ground_deicing';
UPDATE public.sub_roles SET names = jsonb_set(names, '{zh}', '"A320 飞行员"'::jsonb) WHERE id = 'pilot_a320';
UPDATE public.sub_roles SET names = jsonb_set(names, '{zh}', '"A321 飞行员"'::jsonb) WHERE id = 'pilot_a321';
UPDATE public.sub_roles SET names = jsonb_set(names, '{zh}', '"A350 飞行员"'::jsonb) WHERE id = 'pilot_a350';
UPDATE public.sub_roles SET names = jsonb_set(names, '{zh}', '"B737-800 飞行员"'::jsonb) WHERE id = 'pilot_b737_800';
UPDATE public.sub_roles SET names = jsonb_set(names, '{zh}', '"B737-900 飞行员"'::jsonb) WHERE id = 'pilot_b737_900';
UPDATE public.sub_roles SET names = jsonb_set(names, '{zh}', '"B737 MAX 飞行员"'::jsonb) WHERE id = 'pilot_b737_max';
UPDATE public.sub_roles SET names = jsonb_set(names, '{zh}', '"B777 试点"'::jsonb) WHERE id = 'pilot_b777';
UPDATE public.sub_roles SET names = jsonb_set(names, '{zh}', '"B787 试点"'::jsonb) WHERE id = 'pilot_b787';
UPDATE public.sub_roles SET names = jsonb_set(names, '{zh}', '"塞斯纳飞行员"'::jsonb) WHERE id = 'pilot_cessna';
UPDATE public.sub_roles SET names = jsonb_set(names, '{zh}', '"直升机飞行员"'::jsonb) WHERE id = 'pilot_helicopter';
UPDATE public.sub_roles SET names = jsonb_set(names, '{zh}', '"ATR 飞行员"'::jsonb) WHERE id = 'pilot_atr';
UPDATE public.sub_roles SET names = jsonb_set(names, '{zh}', '"民航组织4"'::jsonb) WHERE id = 'student_icao4';
UPDATE public.sub_roles SET names = jsonb_set(names, '{zh}', '"试点访谈准备"'::jsonb) WHERE id = 'student_pilot_interview';
UPDATE public.sub_roles SET names = jsonb_set(names, '{zh}', '"客厅访谈准备"'::jsonb) WHERE id = 'student_cabin_interview';
UPDATE public.sub_roles SET names = jsonb_set(names, '{zh}', '"ATC 访谈准备"'::jsonb) WHERE id = 'student_atc_interview';
UPDATE public.sub_roles SET names = jsonb_set(names, '{zh}', '"线路维护"'::jsonb) WHERE id = 'tech_line';
UPDATE public.sub_roles SET names = jsonb_set(names, '{zh}', '"检查技术员"'::jsonb) WHERE id = 'tech_a_check';
UPDATE public.sub_roles SET names = jsonb_set(names, '{zh}', '"C-检查技术员"'::jsonb) WHERE id = 'tech_c_check';
UPDATE public.sub_roles SET names = jsonb_set(names, '{zh}', '"着陆器技术员"'::jsonb) WHERE id = 'tech_landing_gear';
UPDATE public.sub_roles SET names = jsonb_set(names, '{zh}', '"发动机技术员"'::jsonb) WHERE id = 'tech_engine';
UPDATE public.sub_roles SET names = jsonb_set(names, '{zh}', '"车轮和刹车技术员"'::jsonb) WHERE id = 'tech_wheels';
UPDATE public.sub_roles SET names = jsonb_set(names, '{zh}', '"航空技术员"'::jsonb) WHERE id = 'tech_avionics';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ja}', '"タワーコントローラ"'::jsonb) WHERE id = 'atc_tower';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ja}', '"アプローチコントローラ"'::jsonb) WHERE id = 'atc_approach';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ja}', '"地上のコントローラー"'::jsonb) WHERE id = 'atc_ground';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ja}', '"コントローラー"'::jsonb) WHERE id = 'atc_enroute';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ja}', '"ビジネスクラスクルー"'::jsonb) WHERE id = 'cabin_business';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ja}', '"エコノミークラスクルー"'::jsonb) WHERE id = 'cabin_economy';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ja}', '"プリザー"'::jsonb) WHERE id = 'cabin_purser';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ja}', '"キャビントレーナー"'::jsonb) WHERE id = 'cabin_trainer';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ja}', '"ファーストクラスクルー"'::jsonb) WHERE id = 'cabin_first';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ja}', '"主要な航空会社のディスパッチャ"'::jsonb) WHERE id = 'dispatcher_major';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ja}', '"チャーターディスパッチ"'::jsonb) WHERE id = 'dispatcher_charter';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ja}', '"VIPのディスパッチャ"'::jsonb) WHERE id = 'dispatcher_vip';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ja}', '"貨物ディスパッチャ"'::jsonb) WHERE id = 'dispatcher_cargo';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ja}', '"プッシュバッククルー"'::jsonb) WHERE id = 'ground_pushback';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ja}', '"手荷物ハンドラ"'::jsonb) WHERE id = 'ground_baggage';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ja}', '"キャタリングクルー"'::jsonb) WHERE id = 'ground_catering';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ja}', '"給油クルー"'::jsonb) WHERE id = 'ground_refueling';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ja}', '"デコイシングクルー"'::jsonb) WHERE id = 'ground_deicing';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ja}', '"A320パイロット"'::jsonb) WHERE id = 'pilot_a320';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ja}', '"A321パイロット"'::jsonb) WHERE id = 'pilot_a321';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ja}', '"A350パイロット"'::jsonb) WHERE id = 'pilot_a350';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ja}', '"B737-800 パイロット"'::jsonb) WHERE id = 'pilot_b737_800';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ja}', '"B737-900 パイロット"'::jsonb) WHERE id = 'pilot_b737_900';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ja}', '"B737 マックスパイロット"'::jsonb) WHERE id = 'pilot_b737_max';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ja}', '"B777パイロット"'::jsonb) WHERE id = 'pilot_b777';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ja}', '"B787 パイロット"'::jsonb) WHERE id = 'pilot_b787';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ja}', '"セスナパイロット"'::jsonb) WHERE id = 'pilot_cessna';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ja}', '"ヘリコプターパイロット"'::jsonb) WHERE id = 'pilot_helicopter';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ja}', '"ATRパイロット"'::jsonb) WHERE id = 'pilot_atr';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ja}', '"ICAO 4 プレップ"'::jsonb) WHERE id = 'student_icao4';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ja}', '"パイロットインタビュープレップ"'::jsonb) WHERE id = 'student_pilot_interview';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ja}', '"キャビンインタビュープレップ"'::jsonb) WHERE id = 'student_cabin_interview';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ja}', '"ATCインタビュープレップ"'::jsonb) WHERE id = 'student_atc_interview';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ja}', '"ラインメンテナンス"'::jsonb) WHERE id = 'tech_line';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ja}', '"Aチェック技術者"'::jsonb) WHERE id = 'tech_a_check';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ja}', '"C-Checkの技術者"'::jsonb) WHERE id = 'tech_c_check';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ja}', '"着陸ギヤ技術者"'::jsonb) WHERE id = 'tech_landing_gear';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ja}', '"エンジンの技術者"'::jsonb) WHERE id = 'tech_engine';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ja}', '"ホイール&ブレーキ技術者"'::jsonb) WHERE id = 'tech_wheels';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ja}', '"アビオニクス技術者"'::jsonb) WHERE id = 'tech_avionics';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ko}', '"타워 컨트롤러"'::jsonb) WHERE id = 'atc_tower';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ko}', '"Approach 관제사"'::jsonb) WHERE id = 'atc_approach';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ko}', '"지상 관제사"'::jsonb) WHERE id = 'atc_ground';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ko}', '"En-route 컨트롤러"'::jsonb) WHERE id = 'atc_enroute';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ko}', '"비즈니스 클래스 Crew"'::jsonb) WHERE id = 'cabin_business';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ko}', '"경제 클래스 Crew"'::jsonb) WHERE id = 'cabin_economy';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ko}', '"구매하기"'::jsonb) WHERE id = 'cabin_purser';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ko}', '"캐빈 트레이너"'::jsonb) WHERE id = 'cabin_trainer';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ko}', '"퍼스트 클래스 승무원"'::jsonb) WHERE id = 'cabin_first';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ko}', '"주요 항공사 Dispatcher"'::jsonb) WHERE id = 'dispatcher_major';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ko}', '"헌터 Dispatcher"'::jsonb) WHERE id = 'dispatcher_charter';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ko}', '"VIP 디파처"'::jsonb) WHERE id = 'dispatcher_vip';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ko}', '"화물 Dispatcher"'::jsonb) WHERE id = 'dispatcher_cargo';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ko}', '"Pushback 승무원"'::jsonb) WHERE id = 'ground_pushback';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ko}', '"Baggage 손잡이"'::jsonb) WHERE id = 'ground_baggage';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ko}', '"카테고리"'::jsonb) WHERE id = 'ground_catering';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ko}', '"급유 승무원"'::jsonb) WHERE id = 'ground_refueling';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ko}', '"관련 기사"'::jsonb) WHERE id = 'ground_deicing';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ko}', '"A320 파일럿"'::jsonb) WHERE id = 'pilot_a320';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ko}', '"A321 파일럿"'::jsonb) WHERE id = 'pilot_a321';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ko}', '"A350 파일럿"'::jsonb) WHERE id = 'pilot_a350';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ko}', '"B737-800 파일럿"'::jsonb) WHERE id = 'pilot_b737_800';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ko}', '"B737-900 파일럿"'::jsonb) WHERE id = 'pilot_b737_900';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ko}', '"B737 MAX 파일럿"'::jsonb) WHERE id = 'pilot_b737_max';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ko}', '"B777 파일럿"'::jsonb) WHERE id = 'pilot_b777';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ko}', '"B787 파일럿"'::jsonb) WHERE id = 'pilot_b787';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ko}', '"Cessna 파일럿"'::jsonb) WHERE id = 'pilot_cessna';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ko}', '"헬리콥터 조종사"'::jsonb) WHERE id = 'pilot_helicopter';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ko}', '"ATR 파일럿"'::jsonb) WHERE id = 'pilot_atr';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ko}', '"ICAO 4 준비"'::jsonb) WHERE id = 'student_icao4';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ko}', '"파일럿 인터뷰 Prep"'::jsonb) WHERE id = 'student_pilot_interview';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ko}', '"캐빈 인터뷰 Prep"'::jsonb) WHERE id = 'student_cabin_interview';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ko}', '"ATC 인터뷰"'::jsonb) WHERE id = 'student_atc_interview';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ko}', '"선 정비"'::jsonb) WHERE id = 'tech_line';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ko}', '"A-Check 기술"'::jsonb) WHERE id = 'tech_a_check';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ko}', '"C-Check 기술"'::jsonb) WHERE id = 'tech_c_check';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ko}', '"착륙 장치 Technician"'::jsonb) WHERE id = 'tech_landing_gear';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ko}', '"엔진 기술"'::jsonb) WHERE id = 'tech_engine';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ko}', '"바퀴 & 브레이크 기술공"'::jsonb) WHERE id = 'tech_wheels';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ko}', '"Avionics 기술"'::jsonb) WHERE id = 'tech_avionics';
UPDATE public.sub_roles SET names = jsonb_set(names, '{id}', '"Tower Controller"'::jsonb) WHERE id = 'atc_tower';
UPDATE public.sub_roles SET names = jsonb_set(names, '{id}', '"Pendekatan Kendali"'::jsonb) WHERE id = 'atc_approach';
UPDATE public.sub_roles SET names = jsonb_set(names, '{id}', '"Controller tanah"'::jsonb) WHERE id = 'atc_ground';
UPDATE public.sub_roles SET names = jsonb_set(names, '{id}', '"Kendali En-route"'::jsonb) WHERE id = 'atc_enroute';
UPDATE public.sub_roles SET names = jsonb_set(names, '{id}', '"Kru Kelas Bisnis"'::jsonb) WHERE id = 'cabin_business';
UPDATE public.sub_roles SET names = jsonb_set(names, '{id}', '"Kru Kelas Ekonomi"'::jsonb) WHERE id = 'cabin_economy';
UPDATE public.sub_roles SET names = jsonb_set(names, '{id}', '"Purser"'::jsonb) WHERE id = 'cabin_purser';
UPDATE public.sub_roles SET names = jsonb_set(names, '{id}', '"Trainer kabin"'::jsonb) WHERE id = 'cabin_trainer';
UPDATE public.sub_roles SET names = jsonb_set(names, '{id}', '"First Class Crew"'::jsonb) WHERE id = 'cabin_first';
UPDATE public.sub_roles SET names = jsonb_set(names, '{id}', '"Mayor Airline Dispatcher"'::jsonb) WHERE id = 'dispatcher_major';
UPDATE public.sub_roles SET names = jsonb_set(names, '{id}', '"Charter Dispatcher"'::jsonb) WHERE id = 'dispatcher_charter';
UPDATE public.sub_roles SET names = jsonb_set(names, '{id}', '"Operator VIP"'::jsonb) WHERE id = 'dispatcher_vip';
UPDATE public.sub_roles SET names = jsonb_set(names, '{id}', '"Cargo Dispatcher"'::jsonb) WHERE id = 'dispatcher_cargo';
UPDATE public.sub_roles SET names = jsonb_set(names, '{id}', '"Pushback Crew"'::jsonb) WHERE id = 'ground_pushback';
UPDATE public.sub_roles SET names = jsonb_set(names, '{id}', '"Handler Bagasi"'::jsonb) WHERE id = 'ground_baggage';
UPDATE public.sub_roles SET names = jsonb_set(names, '{id}', '"Tim katering"'::jsonb) WHERE id = 'ground_catering';
UPDATE public.sub_roles SET names = jsonb_set(names, '{id}', '"Refueling Crew"'::jsonb) WHERE id = 'ground_refueling';
UPDATE public.sub_roles SET names = jsonb_set(names, '{id}', '"De- icing Crew"'::jsonb) WHERE id = 'ground_deicing';
UPDATE public.sub_roles SET names = jsonb_set(names, '{id}', '"A320 Pilot"'::jsonb) WHERE id = 'pilot_a320';
UPDATE public.sub_roles SET names = jsonb_set(names, '{id}', '"Pilot A321"'::jsonb) WHERE id = 'pilot_a321';
UPDATE public.sub_roles SET names = jsonb_set(names, '{id}', '"A350 Pilot"'::jsonb) WHERE id = 'pilot_a350';
UPDATE public.sub_roles SET names = jsonb_set(names, '{id}', '"B737- 800 Pilot"'::jsonb) WHERE id = 'pilot_b737_800';
UPDATE public.sub_roles SET names = jsonb_set(names, '{id}', '"B737- 900 Pilot"'::jsonb) WHERE id = 'pilot_b737_900';
UPDATE public.sub_roles SET names = jsonb_set(names, '{id}', '"B737 MAX Pilot"'::jsonb) WHERE id = 'pilot_b737_max';
UPDATE public.sub_roles SET names = jsonb_set(names, '{id}', '"B777 Pilot"'::jsonb) WHERE id = 'pilot_b777';
UPDATE public.sub_roles SET names = jsonb_set(names, '{id}', '"B787 Pilot"'::jsonb) WHERE id = 'pilot_b787';
UPDATE public.sub_roles SET names = jsonb_set(names, '{id}', '"Cessna Pilot"'::jsonb) WHERE id = 'pilot_cessna';
UPDATE public.sub_roles SET names = jsonb_set(names, '{id}', '"Pilot Helikopter"'::jsonb) WHERE id = 'pilot_helicopter';
UPDATE public.sub_roles SET names = jsonb_set(names, '{id}', '"Pilot ATR"'::jsonb) WHERE id = 'pilot_atr';
UPDATE public.sub_roles SET names = jsonb_set(names, '{id}', '"ICAO 4 Prep"'::jsonb) WHERE id = 'student_icao4';
UPDATE public.sub_roles SET names = jsonb_set(names, '{id}', '"Pilot Interview Prep"'::jsonb) WHERE id = 'student_pilot_interview';
UPDATE public.sub_roles SET names = jsonb_set(names, '{id}', '"Persiapan Interview Cabin"'::jsonb) WHERE id = 'student_cabin_interview';
UPDATE public.sub_roles SET names = jsonb_set(names, '{id}', '"Interview ATC Prep"'::jsonb) WHERE id = 'student_atc_interview';
UPDATE public.sub_roles SET names = jsonb_set(names, '{id}', '"Pemeliharaan Baris"'::jsonb) WHERE id = 'tech_line';
UPDATE public.sub_roles SET names = jsonb_set(names, '{id}', '"Periksa Teknisi"'::jsonb) WHERE id = 'tech_a_check';
UPDATE public.sub_roles SET names = jsonb_set(names, '{id}', '"Teknisi C-Check"'::jsonb) WHERE id = 'tech_c_check';
UPDATE public.sub_roles SET names = jsonb_set(names, '{id}', '"Teknisi Landing Gear"'::jsonb) WHERE id = 'tech_landing_gear';
UPDATE public.sub_roles SET names = jsonb_set(names, '{id}', '"Teknisi Mesin"'::jsonb) WHERE id = 'tech_engine';
UPDATE public.sub_roles SET names = jsonb_set(names, '{id}', '"Teknisi Roda & Rem"'::jsonb) WHERE id = 'tech_wheels';
UPDATE public.sub_roles SET names = jsonb_set(names, '{id}', '"Teknisi Avionics"'::jsonb) WHERE id = 'tech_avionics';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ru}', '"Контроллер башни"'::jsonb) WHERE id = 'atc_tower';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ru}', '"Подойди к контроллеру"'::jsonb) WHERE id = 'atc_approach';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ru}', '"Наземный контроллер"'::jsonb) WHERE id = 'atc_ground';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ru}', '"Рулевой контроллер"'::jsonb) WHERE id = 'atc_enroute';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ru}', '"Экипаж бизнес-класса"'::jsonb) WHERE id = 'cabin_business';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ru}', '"Экипаж экономического класса"'::jsonb) WHERE id = 'cabin_economy';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ru}', '"Продавец"'::jsonb) WHERE id = 'cabin_purser';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ru}', '"Каютный тренер"'::jsonb) WHERE id = 'cabin_trainer';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ru}', '"экипаж первого класса"'::jsonb) WHERE id = 'cabin_first';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ru}', '"Главный диспетчер авиакомпании"'::jsonb) WHERE id = 'dispatcher_major';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ru}', '"Чартерный диспетчер"'::jsonb) WHERE id = 'dispatcher_charter';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ru}', '"VIP-диспетчер"'::jsonb) WHERE id = 'dispatcher_vip';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ru}', '"Диспетчер грузов"'::jsonb) WHERE id = 'dispatcher_cargo';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ru}', '"Pushback Crew"'::jsonb) WHERE id = 'ground_pushback';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ru}', '"Погрузчик багажа"'::jsonb) WHERE id = 'ground_baggage';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ru}', '"Экипаж питания"'::jsonb) WHERE id = 'ground_catering';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ru}', '"Заправка экипажа"'::jsonb) WHERE id = 'ground_refueling';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ru}', '"Экипаж с обледенением"'::jsonb) WHERE id = 'ground_deicing';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ru}', '"Пилот A320"'::jsonb) WHERE id = 'pilot_a320';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ru}', '"Пилот A321"'::jsonb) WHERE id = 'pilot_a321';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ru}', '"Пилот A350"'::jsonb) WHERE id = 'pilot_a350';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ru}', '"Пилот B737-800"'::jsonb) WHERE id = 'pilot_b737_800';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ru}', '"Пилот B737-900"'::jsonb) WHERE id = 'pilot_b737_900';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ru}', '"Пилот B737 MAX"'::jsonb) WHERE id = 'pilot_b737_max';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ru}', '"Пилот B777"'::jsonb) WHERE id = 'pilot_b777';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ru}', '"Пилот B787"'::jsonb) WHERE id = 'pilot_b787';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ru}', '"Пилот Cessna"'::jsonb) WHERE id = 'pilot_cessna';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ru}', '"Пилот вертолета"'::jsonb) WHERE id = 'pilot_helicopter';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ru}', '"Пилот ATR"'::jsonb) WHERE id = 'pilot_atr';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ru}', '"ИКАО 4 Подготовка"'::jsonb) WHERE id = 'student_icao4';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ru}', '"Пилотное интервью Prep"'::jsonb) WHERE id = 'student_pilot_interview';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ru}', '"Интервью в каюте Prep"'::jsonb) WHERE id = 'student_cabin_interview';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ru}', '"Интервью Prep"'::jsonb) WHERE id = 'student_atc_interview';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ru}', '"Обслуживание линии"'::jsonb) WHERE id = 'tech_line';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ru}', '"Проверить техник"'::jsonb) WHERE id = 'tech_a_check';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ru}', '"Техник C-Check"'::jsonb) WHERE id = 'tech_c_check';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ru}', '"Техник Landing Gear"'::jsonb) WHERE id = 'tech_landing_gear';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ru}', '"Инженер-техник"'::jsonb) WHERE id = 'tech_engine';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ru}', '"Wheels & Brakes технический специалист"'::jsonb) WHERE id = 'tech_wheels';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ru}', '"Техник авионики"'::jsonb) WHERE id = 'tech_avionics';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ar}', '"برج المراقب المالي"'::jsonb) WHERE id = 'atc_tower';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ar}', '"المراقب المالي للنهج"'::jsonb) WHERE id = 'atc_approach';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ar}', '"المراقب المالي الأرضي"'::jsonb) WHERE id = 'atc_ground';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ar}', '"المراقب المالي المباشر"'::jsonb) WHERE id = 'atc_enroute';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ar}', '"درجة رجال الأعمال"'::jsonb) WHERE id = 'cabin_business';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ar}', '"درجة الاقتصاد"'::jsonb) WHERE id = 'cabin_economy';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ar}', '"Purser"'::jsonb) WHERE id = 'cabin_purser';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ar}', '"Cabin Trainer"'::jsonb) WHERE id = 'cabin_trainer';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ar}', '"الدرجة الأولى"'::jsonb) WHERE id = 'cabin_first';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ar}', '"Major Airline Dispatcher"'::jsonb) WHERE id = 'dispatcher_major';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ar}', '"Dispatcher"'::jsonb) WHERE id = 'dispatcher_charter';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ar}', '"VIP Dispatcher"'::jsonb) WHERE id = 'dispatcher_vip';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ar}', '"Cargo Dispatcher"'::jsonb) WHERE id = 'dispatcher_cargo';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ar}', '"Pushback Crew"'::jsonb) WHERE id = 'ground_pushback';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ar}', '"ناقل الحقيبة"'::jsonb) WHERE id = 'ground_baggage';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ar}', '"مقصورة الطعام"'::jsonb) WHERE id = 'ground_catering';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ar}', '"Refueling Crew"'::jsonb) WHERE id = 'ground_refueling';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ar}', '"De-icing Crew"'::jsonb) WHERE id = 'ground_deicing';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ar}', '"A320 Pilot"'::jsonb) WHERE id = 'pilot_a320';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ar}', '"A321 Pilot"'::jsonb) WHERE id = 'pilot_a321';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ar}', '"A350 Pilot"'::jsonb) WHERE id = 'pilot_a350';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ar}', '"B737-800 Pilot"'::jsonb) WHERE id = 'pilot_b737_800';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ar}', '"B737-900 Pilot"'::jsonb) WHERE id = 'pilot_b737_900';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ar}', '"B737 MAX Pilot"'::jsonb) WHERE id = 'pilot_b737_max';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ar}', '"B777 Pilot"'::jsonb) WHERE id = 'pilot_b777';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ar}', '"B787 Pilot"'::jsonb) WHERE id = 'pilot_b787';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ar}', '"Cessna Pilot"'::jsonb) WHERE id = 'pilot_cessna';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ar}', '"طيار طائرات الهليكوبتر"'::jsonb) WHERE id = 'pilot_helicopter';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ar}', '"ATR Pilot"'::jsonb) WHERE id = 'pilot_atr';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ar}', '"منظمة الطيران المدني الدولي ٤"'::jsonb) WHERE id = 'student_icao4';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ar}', '"Pilot Interview Prep"'::jsonb) WHERE id = 'student_pilot_interview';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ar}', '"Cabin Interview Prep"'::jsonb) WHERE id = 'student_cabin_interview';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ar}', '"ATC Interview Prep"'::jsonb) WHERE id = 'student_atc_interview';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ar}', '"الصيانة"'::jsonb) WHERE id = 'tech_line';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ar}', '"فني الشيك"'::jsonb) WHERE id = 'tech_a_check';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ar}', '"C-Check Technician"'::jsonb) WHERE id = 'tech_c_check';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ar}', '"لاند جير تقني"'::jsonb) WHERE id = 'tech_landing_gear';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ar}', '"فني مهندس"'::jsonb) WHERE id = 'tech_engine';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ar}', '"باحثة عن الفرامل"'::jsonb) WHERE id = 'tech_wheels';
UPDATE public.sub_roles SET names = jsonb_set(names, '{ar}', '"فني علوم الطيور"'::jsonb) WHERE id = 'tech_avionics';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fa}', '"کنترل کننده برج"'::jsonb) WHERE id = 'atc_tower';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fa}', '"کنترل کننده نزدیک"'::jsonb) WHERE id = 'atc_approach';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fa}', '"کنترل کننده زمینی"'::jsonb) WHERE id = 'atc_ground';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fa}', '"کنترل کننده روتر"'::jsonb) WHERE id = 'atc_enroute';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fa}', '"بازی Class"'::jsonb) WHERE id = 'cabin_business';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fa}', '"کلاس اقتصاد"'::jsonb) WHERE id = 'cabin_economy';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fa}', '"Purser"'::jsonb) WHERE id = 'cabin_purser';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fa}', '"مربی کابین"'::jsonb) WHERE id = 'cabin_trainer';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fa}', '"خدمه کلاس اول"'::jsonb) WHERE id = 'cabin_first';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fa}', '"سرگرد هواپیمایی Dispatcher"'::jsonb) WHERE id = 'dispatcher_major';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fa}', '"منشور Dispatcher"'::jsonb) WHERE id = 'dispatcher_charter';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fa}', '"نام انگلیسی : Dispatcher"'::jsonb) WHERE id = 'dispatcher_vip';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fa}', '"دانلود بازی Dispatcher"'::jsonb) WHERE id = 'dispatcher_cargo';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fa}', '"خدمه Pushback"'::jsonb) WHERE id = 'ground_pushback';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fa}', '"چمدان"'::jsonb) WHERE id = 'ground_baggage';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fa}', '"خدمه"'::jsonb) WHERE id = 'ground_catering';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fa}', '"بازسازی خدمه"'::jsonb) WHERE id = 'ground_refueling';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fa}', '"خدمه De-icing"'::jsonb) WHERE id = 'ground_deicing';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fa}', '"خلبان A320"'::jsonb) WHERE id = 'pilot_a320';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fa}', '"خلبان A321"'::jsonb) WHERE id = 'pilot_a321';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fa}', '"خلبان A350"'::jsonb) WHERE id = 'pilot_a350';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fa}', '"B 737-800 خلبان"'::jsonb) WHERE id = 'pilot_b737_800';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fa}', '"B 737-900 خلبان"'::jsonb) WHERE id = 'pilot_b737_900';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fa}', '"خلبان MAX"'::jsonb) WHERE id = 'pilot_b737_max';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fa}', '"خلبان B777"'::jsonb) WHERE id = 'pilot_b777';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fa}', '"B787 خلبان"'::jsonb) WHERE id = 'pilot_b787';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fa}', '"خلبان Cessna"'::jsonb) WHERE id = 'pilot_cessna';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fa}', '"خلبان هلیکوپتر"'::jsonb) WHERE id = 'pilot_helicopter';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fa}', '"خلبان ATR"'::jsonb) WHERE id = 'pilot_atr';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fa}', '"۴- Prep"'::jsonb) WHERE id = 'student_icao4';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fa}', '"مصاحبه آزمایشی Prep"'::jsonb) WHERE id = 'student_pilot_interview';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fa}', '"مصاحبه با Prep"'::jsonb) WHERE id = 'student_cabin_interview';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fa}', '"مصاحبه ATC Prep"'::jsonb) WHERE id = 'student_atc_interview';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fa}', '"خط نگهداری"'::jsonb) WHERE id = 'tech_line';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fa}', '"تکنسین A-Check"'::jsonb) WHERE id = 'tech_a_check';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fa}', '"C-Check Engineer"'::jsonb) WHERE id = 'tech_c_check';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fa}', '"فرود آمدن Gear"'::jsonb) WHERE id = 'tech_landing_gear';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fa}', '"تکنسین موتور"'::jsonb) WHERE id = 'tech_engine';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fa}', '"چرخ و ترمز تکنسین"'::jsonb) WHERE id = 'tech_wheels';
UPDATE public.sub_roles SET names = jsonb_set(names, '{fa}', '"تکنسین Avionics"'::jsonb) WHERE id = 'tech_avionics';
UPDATE public.sub_roles SET names = jsonb_set(names, '{hi}', '"टॉवर नियंत्रक"'::jsonb) WHERE id = 'atc_tower';
UPDATE public.sub_roles SET names = jsonb_set(names, '{hi}', '"दृष्टिकोण नियंत्रक"'::jsonb) WHERE id = 'atc_approach';
UPDATE public.sub_roles SET names = jsonb_set(names, '{hi}', '"ग्राउंड कंट्रोलर"'::jsonb) WHERE id = 'atc_ground';
UPDATE public.sub_roles SET names = jsonb_set(names, '{hi}', '"एन-रूट नियंत्रक"'::jsonb) WHERE id = 'atc_enroute';
UPDATE public.sub_roles SET names = jsonb_set(names, '{hi}', '"बिजनेस क्लास क्रू"'::jsonb) WHERE id = 'cabin_business';
UPDATE public.sub_roles SET names = jsonb_set(names, '{hi}', '"अर्थव्यवस्था वर्ग क्रू"'::jsonb) WHERE id = 'cabin_economy';
UPDATE public.sub_roles SET names = jsonb_set(names, '{hi}', '"पर्सर"'::jsonb) WHERE id = 'cabin_purser';
UPDATE public.sub_roles SET names = jsonb_set(names, '{hi}', '"केबिन ट्रेनर"'::jsonb) WHERE id = 'cabin_trainer';
UPDATE public.sub_roles SET names = jsonb_set(names, '{hi}', '"प्रथम श्रेणी लिपि"'::jsonb) WHERE id = 'cabin_first';
UPDATE public.sub_roles SET names = jsonb_set(names, '{hi}', '"प्रमुख एयरलाइन डिस्पैचर"'::jsonb) WHERE id = 'dispatcher_major';
UPDATE public.sub_roles SET names = jsonb_set(names, '{hi}', '"चार्टर डिस्पैचर"'::jsonb) WHERE id = 'dispatcher_charter';
UPDATE public.sub_roles SET names = jsonb_set(names, '{hi}', '"वीआईपी डिस्पैचर"'::jsonb) WHERE id = 'dispatcher_vip';
UPDATE public.sub_roles SET names = jsonb_set(names, '{hi}', '"कार्गो Dispatcher"'::jsonb) WHERE id = 'dispatcher_cargo';
UPDATE public.sub_roles SET names = jsonb_set(names, '{hi}', '"पुशबैक क्रू"'::jsonb) WHERE id = 'ground_pushback';
UPDATE public.sub_roles SET names = jsonb_set(names, '{hi}', '"बैगेज हैंडलर"'::jsonb) WHERE id = 'ground_baggage';
UPDATE public.sub_roles SET names = jsonb_set(names, '{hi}', '"कैटरिंग क्रू"'::jsonb) WHERE id = 'ground_catering';
UPDATE public.sub_roles SET names = jsonb_set(names, '{hi}', '"ईंधन भरने वाला क्रू"'::jsonb) WHERE id = 'ground_refueling';
UPDATE public.sub_roles SET names = jsonb_set(names, '{hi}', '"Deicing Crew"'::jsonb) WHERE id = 'ground_deicing';
UPDATE public.sub_roles SET names = jsonb_set(names, '{hi}', '"A320 पायलट"'::jsonb) WHERE id = 'pilot_a320';
UPDATE public.sub_roles SET names = jsonb_set(names, '{hi}', '"A321 पायलट"'::jsonb) WHERE id = 'pilot_a321';
UPDATE public.sub_roles SET names = jsonb_set(names, '{hi}', '"A350 पायलट"'::jsonb) WHERE id = 'pilot_a350';
UPDATE public.sub_roles SET names = jsonb_set(names, '{hi}', '"B737-800 पायलट"'::jsonb) WHERE id = 'pilot_b737_800';
UPDATE public.sub_roles SET names = jsonb_set(names, '{hi}', '"B737-900 पायलट"'::jsonb) WHERE id = 'pilot_b737_900';
UPDATE public.sub_roles SET names = jsonb_set(names, '{hi}', '"B737 मैक्स पायलट"'::jsonb) WHERE id = 'pilot_b737_max';
UPDATE public.sub_roles SET names = jsonb_set(names, '{hi}', '"B777 पायलट"'::jsonb) WHERE id = 'pilot_b777';
UPDATE public.sub_roles SET names = jsonb_set(names, '{hi}', '"B787 पायलट"'::jsonb) WHERE id = 'pilot_b787';
UPDATE public.sub_roles SET names = jsonb_set(names, '{hi}', '"सेस्ना पायलट"'::jsonb) WHERE id = 'pilot_cessna';
UPDATE public.sub_roles SET names = jsonb_set(names, '{hi}', '"हेलीकाप्टर पायलट"'::jsonb) WHERE id = 'pilot_helicopter';
UPDATE public.sub_roles SET names = jsonb_set(names, '{hi}', '"ATR पायलट"'::jsonb) WHERE id = 'pilot_atr';
UPDATE public.sub_roles SET names = jsonb_set(names, '{hi}', '"आईसीएओ 4 तैयारी"'::jsonb) WHERE id = 'student_icao4';
UPDATE public.sub_roles SET names = jsonb_set(names, '{hi}', '"पायलट साक्षात्कार तैयारी"'::jsonb) WHERE id = 'student_pilot_interview';
UPDATE public.sub_roles SET names = jsonb_set(names, '{hi}', '"केबिन साक्षात्कार तैयारी"'::jsonb) WHERE id = 'student_cabin_interview';
UPDATE public.sub_roles SET names = jsonb_set(names, '{hi}', '"एटीसी साक्षात्कार तैयारी"'::jsonb) WHERE id = 'student_atc_interview';
UPDATE public.sub_roles SET names = jsonb_set(names, '{hi}', '"लाइन रखरखाव"'::jsonb) WHERE id = 'tech_line';
UPDATE public.sub_roles SET names = jsonb_set(names, '{hi}', '"ए-चेक तकनीशियन"'::jsonb) WHERE id = 'tech_a_check';
UPDATE public.sub_roles SET names = jsonb_set(names, '{hi}', '"सी-चेक तकनीशियन"'::jsonb) WHERE id = 'tech_c_check';
UPDATE public.sub_roles SET names = jsonb_set(names, '{hi}', '"लैंडिंग गियर तकनीशियन"'::jsonb) WHERE id = 'tech_landing_gear';
UPDATE public.sub_roles SET names = jsonb_set(names, '{hi}', '"इंजन तकनीशियन"'::jsonb) WHERE id = 'tech_engine';
UPDATE public.sub_roles SET names = jsonb_set(names, '{hi}', '"पहियों और ब्रेक तकनीशियन"'::jsonb) WHERE id = 'tech_wheels';
UPDATE public.sub_roles SET names = jsonb_set(names, '{hi}', '"एवियोनिक्स तकनीशियन"'::jsonb) WHERE id = 'tech_avionics';
COMMIT;
